moby/buildkit

cmd/buildd/main.go
cmd/buildd/main_containerd.go
cmd/buildd/main_standalone.go
cmd/buildd/main_unsupported.go

Tested with the standalone controller.
Without this patch, the daemon fails to build an image:
ERRO[0008] /control.Control/Solve returned error: Lockfiles must be
given as absolute path names
error creating lockfile
.buildstate/content/ingest/b8bc9e0954dc1413b6ffd69c106a1d8967130398f50626b5c5a098c5149b0bf3/lock
github.com/tonistiigi/buildkit_poc/vendor/github.com/containerd/containerd/content.(*store).ingestPaths
/home/suda/gopath/src/github.com/tonistiigi/buildkit_poc/vendor/github.com/containerd/containerd/content/store.go:369
github.com/tonistiigi/buildkit_poc/vendor/github.com/containerd/containerd/content.(*store).Writer
/home/suda/gopath/src/github.com/tonistiigi/buildkit_poc/vendor/github.com/containerd/containerd/content/store.go:233 …

buildd: fix "Lockfiles must be given as absolute path names" error

---

cmd/buildctl/dump.go
cmd/buildctl/main.go

The last PR today 😄 
Example output:
```console
$ go run examples/llboput/example.go > a.llb
$ buildctl dump < a.llb
2017/06/12 09:51:52 ([]main.llbOp) (len=4 cap=4) {
(main.llbOp) {
Op: (pb.Op) &Op{Inputs:[],Op:&Op_Source{Source:&SourceOp{Identifier:docker-image://docker.io/library/busybox:latest,},},},
Digest: (digest.Digest) (len=71) sha256:74ecb5d790c33a213ba00f8f43d62947df1d4dea72f5ec13353a9b943f469f0f
},
(main.llbOp) {
Op: (pb.Op) &Op{Inputs:[&Input{Digest:sha256:74ecb5d790c33a213ba00f8f43d62947df1d4dea72f5ec13353a9b943f469f0f,Index:0,}],Op:&Op_Exec{Exec:&ExecOp{Meta:&Meta{Args:[/bin/sleep 1],Env:[],Cwd:/,},Mounts:[&Mount{Input:0,Selector:,Dest:/,Output:0,}],},},},
Digest: (digest.Digest) (len=71) sha256:1de5701b93648843bf2cf6ebf982b4f63ea55dcb9259e73a5bd6737505660d06
}, …
```

buildctl: add dump

---

cmd/buildctl/debug/dump.go

JSON seems much more readable. Problem is that it needs to be manually piped to `jq`.
@AkihiroSuda 

buildctl: use json for debugging

---

client/llb/llb.go
client/llb/meta.go
client/llb/meta_test.go
client/llb/state.go
client/llb/state_test.go
examples/buildkit/buildkit.go

This is a refactoring of the `llb` package internals.
Introduces new functions for controlling the metadata and mounts of `llb` states. The functions can be now used to modify both state and a single execution operation.
New functions:
`AddEnv`
`DelEnv`
`ClearEnv`
`Dir`
`Args`
`Reset` - replaces all metadata to the one from separate stage
`With` method is added for users to define their own pipelines of modification steps.
example:
```
s.AddEnv("FOO", "bar").
Run(llb.Args("ls", "-l"), llb.Dir("/proc")).
Reset(someotherState).
With(collectionOfSteps).
Run(llb.Shlex("ls -l"))
```
todo:
- `state.Save() / state.Restore()`
- better error reporting for `Validate()`
- tests that validate marshalled protobuf
I also modified the buildkit example to do the git clone step in parallel with the added …

llb: add more features to client package

---

solver/refcache.go
solver/solver.go
util/flightcontrol/flightcontrol.go
util/progress/multireader.go
util/progress/progress.go

fixes #24
This updates the solver so that when parallel build jobs share some vertexes they are executed only once. It makes sure that there is minimal overhead when building different targets of the same project at the same time.
A good way to test it is to run multiple versions of the `examples/buildkit` with different configurations(standalone vs containerd) and see how they share most of the steps.
Currently, the vertex-status and log objects are not shown on the second trace for vertexes that were already completed by the time that job began. This sould be solvable in a follow-up.
@AkihiroSuda 

solver: add vertex sharing on concurrent builds

---

.dockerignore
.gitignore

`docker build` was failing with `EPERM` if `sudo ./bin/buildd` was executed with the repo dir as wd.

.gitignore and .dockerignore: add .buildstate

---

solver/jobs.go
solver/refcache.go
solver/solver.go
util/flightcontrol/flightcontrol.go

~based on #43~
Cache the progress together with the snapshot reference until there are active jobs that use it.
@AkihiroSuda

Add progress replay for already completed active vertexes

---

solver/exec.go
solver/solver.go
solver/source.go

Small refactoring of ops runners with not functionality changes. Preparation for making these unit testable.
@AkihiroSuda 

solver: move ops to separate files

---

cmd/buildctl/build.go
cmd/buildd/main.go
util/appcontext/appcontext.go
vendor.conf
vendor/github.com/containerd/go-runc/command_linux.go
vendor/github.com/containerd/go-runc/runc.go
worker/runcworker/worker.go

Currently shutting down buildd would potentially leak mounts and breaks the output of running clients. This update gracefully shuts down all current handlers before shutting down the process.
~based on #49 (only last commit is new)~
includes fix for `go-runc` https://github.com/containerd/go-runc/pull/19
@AkihiroSuda

buildd: graceful shutdown on termination signals

---

cache/manager.go
cache/manager_test.go
cache/metadata.go
cache/metadata/metadata.go
cache/metadata/metadata_test.go
cache/refs.go
control/control_default.go
control/control_standalone_test.go
hack/test-unit
snapshot/blobmapping/snapshotter.go
vendor/github.com/stretchr/testify/require/doc.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/requirements.go

fixes #22 
fixes #27 
The goal was to make a central store where any other package can use set their custom metadata about snapshots. Currently used for blobmaps and size cache. Should be used for more meta information(tags, timestamps), instruction cache and content hashes.
The usability isn't quite perfect yet and I didn't refactor the locking yet. I'd hope to evaluate how good it fits when the other use cases are implemented.
@AkihiroSuda

persistent metadata helpers for snapshots

---

README.md
cmd/buildctl/debug.go
cmd/buildctl/debug/dumpbolt.go
cmd/buildctl/debug/dumpllb.go
cmd/buildctl/debug/dumpmetadata.go

- dump-llb: renamed from old `dump`. Now supports specifying LLB by filename as well (for consistency with other commands)
- dump-metadata: new command for dumping metadata.db
- dump-bolt: new command for dumping arbitrary boltdb file
cc @tonistiigi

buildctl debug: dump-{llb,metadata,bolt}

---

control/control.go
solver/exec.go
solver/jobs.go
solver/load.go
solver/refcache.go
solver/solver.go
solver/source.go
solver/vertex.go
source/manager.go

This PR makes the solver fully self contained, removing dependencies on other packages and llb definition. It makes the solver easily unit-testable and makes it easier to improve its algorithm.
I didn't move the llb definition to a different package yet, in case it turns out that keeping them together help in some test case or feature.
@AkihiroSuda I think I might have made #55 bit more complicated. Having a central concurrency limit should be easier now but as the solver doesn't know what the separate ops are it isn't that easy to assign individual values to them. You can update the `Op` interface if you want to expose more information to the solver, for example, `ConcurrencyGroup() string`

solver: remove llb dependency

---

cmd/buildctl/build.go

Add option for turning off interactive progressbar. The output is far from perfect atm but a starting point. Mostly useful if debug logs are needed from `buildctl`.
`buildctl --debug  build  --no-progress`

buildctl: non-interactive output support

---

cmd/buildctl/debug/dumpllb.go

Add basic dot visualization of llb:
```
go run ./examples/buildkit2/buildkit.go | buildctl debug dump-llb --dot | dot -Tsvg
```
[out.pdf](https://github.com/moby/buildkit/files/1154055/out.pdf)

buildctl: add dot output for visualizing llb

---

README.md
client/client_test.go
client/solve.go
cmd/buildctl/build.go
examples/buildkit3/buildkit.go
session/filesync/filesync.go
session/filesync/filesync_test.go
source/local/local.go

This PR adds support for using more than one local sources during build.
```
./buildkit3 --buildkit=local --runc=local | buildctl build --local buildkit-src=. --local runc-src=/path/to/runc
```

source: add multiple dir support for local source

---

cache/manager.go
cache/manager_test.go
cache/refs.go
solver/solver.go
source/git/gitsource.go
source/local/local.go

#76 was bit too agressive . When build was cancelled a snapshot could be removed because the node requiring it didn't complete yet and therefore it became unused. Then on the next invocation data was not found for these vertexes and they needed to be executed again. The solution is to add the retaining cache-policy added to some mutable references in #76 to immutable references as well, as soon as we know that there is a node that would want to use it later.
@AkihiroSuda 

solver: avoid removing references required for future cache

---

client/llb/exec.go

Forgot some previously supported `RunOption` functions in #84

llb: add missing runoptions and fixing scratch input

---

cache/contenthash/filehash.go
cache/contenthash/filehash_unix.go
cache/contenthash/filehash_windows.go
worker/oci/spec_unix.go

#91 should require this (as it imports content hash stuff)

Fix windows build

---

cache/contenthash/checksum.go
cache/contenthash/checksum_test.go
cache/instructioncache/cache.go
cache/metadata.go
cache/metadata/metadata.go
cache/refs.go
session/filesync/diffcopy.go
session/filesync/filesync.go
solver/build.go
solver/exec.go
solver/load.go
solver/solver.go
solver/source.go
solver/state.go
solver/vertex.go
source/local/local.go
vendor.conf
vendor/github.com/hashicorp/go-immutable-radix/iradix.go
vendor/github.com/hashicorp/go-immutable-radix/iter.go
vendor/github.com/hashicorp/go-immutable-radix/node.go
vendor/github.com/hashicorp/go-immutable-radix/raw_iter.go

fixes #86 
fixes #58 
fixes #35
This needed quite a big refactoring of the solver. Not fully convinced there isn't a better abstraction for this but all others I tried had even worse issues. It is important that once the content based hit is determined, the matched node itself doesn't need to exist in the cache if there is some top level node that has cache instead. This will let us do remote backend for the instruction cache and pull in as little data as possible on cache import.
@AkihiroSuda 

solver: implement content based cache support

---

util/profiler/profiler.go

Without this, profiles don't finish when the app is stopped with `ctrl^c` (like in buildd).

profiler: add noshutdown hooks

---

client/llb/exec.go
client/llb/state.go
examples/buildkit3/buildkit.go

Disables outputs on readonly mounts and directly links them to parents instead. Currently, these outputs would be committed and later cleaned up.

llb: skip outputs of readonly mounts

---

examples/dockerfile2llb/main.go

Example script for converting Dockerfile to llb without frontend so it can be debugged with `buildctl debug`.

examples: add example dockerfile converter

---

client/llb/resolver.go
client/llb/source.go
control/control.go
control/control_default.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/frontend.go
solver/solver.go
source/containerimage/pull.go
util/imageutil/config.go
vendor.conf

This makes sure that frontend and llb share the image resolver and makes sure that there are no duplicate calls to the registry. Previously repeated resolves from frontend were also cached because it used `llb.DefaultMetaResolver` but that is not safe for a long-running client like frontend.

imagesource: share config resolver with frontend

---

cmd/buildctl/build.go

buildctl: allow specifying trace file path

---

session/filesync/diffcopy.go
session/filesync/filesync.go
vendor.conf
vendor/github.com/tonistiigi/fsutil/validator.go
vendor/github.com/tonistiigi/fsutil/walker.go

vendor: update fsutil

---

cmd/buildctl/diskusage.go
util/progress/progressui/display.go
vendor.conf
vendor/github.com/tonistiigi/units/LICENSE
vendor/github.com/tonistiigi/units/bytes.go
vendor/github.com/tonistiigi/units/readme.md

The current units package isn't suitable for progressbars as the length of the output is constantly changing. Switch to another package that lets the client have full control of the output.

progressui: fix flicker on printing byte sizes

---

api/services/control/control.proto
cache/manager.go
cache/refs.go
client/graph.go
client/solve.go
control/control.go
solver/build.go
solver/jobs.go
solver/load.go
solver/solver.go
solver/vertex.go
source/containerimage/pull.go
util/bgfunc/bgfunc.go
util/progress/progressui/display.go

This contains the follow-up fixes mentioned in https://github.com/moby/buildkit/pull/117#issue-256534308
The main change is that there is no `LoadLLB` function anymore for converting LLB into a generic vertex graph. Now you can only load directly into a job (a build request). This makes sure that we can report correct progress for every request in the cases that the vertexsolver is shared between them.
Places where `[][]byte` is passed around should be replaced with https://github.com/moby/buildkit/pull/114#discussion_r137623400 later (cc @AkihiroSuda) 
This should also fix the encoder race/panic that has happened in CI a couple of times.

solver: fix shared request progress and cancellation

---

client/solve.go
control/control.go
frontend/dockerfile/dockerfile.go
frontend/frontend.go
frontend/gateway/gateway.go
hack/test-integration
solver/build.go
solver/jobs.go
solver/solver.go
solver/vertex.go

Reorganize some function to avoid big lists of arguments and share code with the llbbridge. 
You still can't launch a frontend yet from a nested build as it goes to another function `subBuild`. Need to figure out the case where the same subbuild is launched by multiple jobs without duplicating the vertexes of the subbuild for reporting.

Update solver public api

---

solver/build.go
solver/exec.go
solver/solver.go
solver/source.go

This has following advantages:
- content hash of an input can be calculated before all the inputs have been resolved
- the possibility that content cache hit may occur can be detected early and synchronized with other vertexes
- for distributed build content does not need to be on the same host to detect a cache hit

solver: replace contentkey with contentmask

---

README.md

document use of containerized buildctl

---

README.md
cmd/buildctl/main.go
hack/dockerfiles/test.Dockerfile
util/appdefaults/appdefaults_unix.go

This makes running `buildd` easier from a container. I've already pushed image `tonistiigi/buildkit:standalone`. I will release binaries for a preview build after this is merged.
ping @AkihiroSuda 

Update state directory defaults

---

cmd/buildd/main_unsupported.go

I was pretty confused by the error message. I hope the one I propose will make
it more clear for other newcommers.

buildd: better error msg for unsupported builds

---

doc.go

- Allows to add a "root" documentation on godoc.org
- Should fix errors when trying to depend on buildkit using golang/dep
Right now it does the following 
```
ensure Solve(): No versions of github.com/moby/buildkit met constraints:
master: Could not introduce github.com/moby/buildkit@master, as its subpackage github.com/moby/buildkit/util does not contain usable Go code (*build.NoGoError).. (Package is required by (root).)
preview1: Could not introduce github.com/moby/buildkit@preview1, as its subpackage github.com/moby/buildkit/util does not contain usable Go code (*build.NoGoError).. (Package is required by (root).)
```
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Add a go file on buildkit root folder

---

cache/contenthash/checksum_test.go
examples/buildkit0/buildkit.go
examples/buildkit1/buildkit.go
examples/buildkit2/buildkit.go
examples/buildkit3/buildkit.go
examples/nested-llb/main.go
frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/test.Dockerfile
hack/dockerfiles/vendor.Dockerfile

This also serves as a workaround for #145 as in `go1.9` `go test` ignores vendored packages.
The test changes are for tar header changes in https://github.com/moby/moby/pull/33935 . Unlike moby, buildkit does not inject the missing bits.

update to go1.9

---

cmd/buildctl/build.go
solver/jobs.go

- 3bf42a3: cache, solver: refactor Reference interface 
- 77d1305: cache: split metadatautil pkg 
- dd8a51c: cache: add ReleaseOpt
- be99b0b: solver: implement IgnoreCache LLB Metadata
cache is ignored if `IgnoreCache && cachedTime < jobCreatedTime`.
@tonistiigi Please verify whether this design is correct?

 solver: implement IgnoreCache LLB Metadata

---

cache/contenthash/checksum.go
cache/contenthash/checksum_test.go

There was an issue with updating the contenthash internals on a certain combination of changes. I struggled to hit this case with a test case because it also requires timing to match. The core of the issue was that when a big directory was deleted it also marked the parent directory dirty(invalidating cache) and the cache invalidation added the record about the already deleted directory back.
There is a related issue that the diff seems to emit deletion events for one level of children what is inconsistent. The current code should work around it but it would be more efficient if either the child events would never appear or appear fully recursively.
reported by @hinshun

contenthash: fix recursive directory deletes

---

cache/contenthash/filehash_unix.go

Use the Major/Minor functions from golang.org/x/sys/unix instead of
locally re-implementing them. This also makes sure they work correctly
for GOOS != linux.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

contenthash: use Major/Minor from golang.org/x/sys/unix

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go

based on #168 
New copy image is built from https://github.com/tonistiigi/copy/pull/1 , although after finishing it I don't think this is the correct way how this image should be built. I was trying to avoid reimplementing copy/extract in go and use standard tools but there is no easy way to implement `COPY --chown` in this method. So probably the implementation will change but chang in this repo should be ok.

dockerfile: Add ADD from archive support

---

client/llb/exec.go
client/llb/imagemetaresolver/resolver.go
client/llb/llbbuild/llbbuild.go
client/llb/marshal.go
client/llb/resolver.go
client/llb/source.go
client/llb/state.go
cmd/buildctl/build.go
cmd/buildctl/debug/dumpllb.go

Allows things like `llb.Image(..., llb.IgnoreCache)` `llb.Run(..., llb.IgnoreCache)` for vertexes. Implemented so that minimal changes are required for adding new metadata helpers.
@AkihiroSuda wdyt? Doesn't seem the cleanest but don't have better ideas atm. If this looks good to you I'll add some test coverage.

llb: allow defining metadata on operations

---

hack/dockerfiles/test.Dockerfile

The biggest update is the separation of `buildkit-containerd` and `container-runtime` stages that can be built into separate containers and used together like.
```
docker build -t containerd -f ./hack/dockerfiles/test.Dockerfile --target containerd-runtime .
docker build -t buildd-containerd -f ./hack/dockerfiles/test.Dockerfile --build-arg BUILDKIT_TARGET=containerd .
docker run -d --privileged -v /tmp:/tmp:rshared --name containerd containerd
docker run -d --privileged -p 1234:1234 --volumes-from containerd buildd-containerd --addr tcp://0.0.0.0:1234 --debug
docker exec containerd ctr image ls
export BUILDKIT_HOST=tcp://127.0.0.1:1234
buildctl du
```
@AkihiroSuda Do you have ideas for doing the `-v /tmp:/tmp:rshared` part better? It is needed for mounting the subpath in buildkit and …

hack: update test dockerfile

---

cache/manager.go

Fixes deletion race seen in CI:
```
Error Trace:	manager_test.go:92
Error:		Not equal: not found (expected)
!= locked (actual)
Diff:
--- Expected
+++ Actual
@@ -1,2 +1,2 @@
-(*errors.fundamental)(0xc42023d5c0)(not found)
+(*errors.fundamental)(0xc42023d580)(locked)
```
Appeared because mutable deletion is in a goroutine for not taking the manager lock on finalize. The bug itself shouldn't have had much impact as it only changed the return value between different errors.

cache: fix race on reloading mutableref

---

cache/manager.go
cache/metadata.go
cache/refs.go
client/client_test.go
exporter/containerimage/export.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go

~based on #195~
This PR fills in history array records, either from dockerfile commands or LLB descriptions. It also optimizes out empty layers and sets their history records to reflect that. 
Note the history items from dockerfile aren't 100% compatible with docker but carry the same content for the user. For the commands that were executed by LLB, the vertex digest is added as well. This should be replaced by cache checksum in the future but avoids wrong cache hits in other builders that are based on history array because the record wouldn't be unique otherwise. Buildkit itself will likely share cache on a side channel or write it as a single binary value and not repurpose history array for this. Unlike docker, the history records also don't use `sh -c #(nop)` prefixes. This is put …

image: set up history array on exported image config

---

cache/refs.go

Fixes the "snapshot not found" issue.
```
standalone.go:62: time="2017-12-09T16:56:09Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: not found
....
/go/src/github.com/moby/buildkit/vendor/github.com/containerd/containerd/errdefs/grpc.go:82
standalone.go:62: github.com/moby/buildkit/vendor/github.com/containerd/containerd.(*remoteSnapshotter).View
standalone.go:62: 	/go/src/github.com/moby/buildkit/vendor/github.com/containerd/containerd/snapshot.go:111
standalone.go:62: github.com/moby/buildkit/snapshot/blobmapping.(*Snapshotter).View
```
First commit fixes the issue. The second one fixes another possible related problem but didn't cause the problem this time.

cache: fix setting root labels on commit

---

client/llb/source.go
client/local.go
frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go
session/filesync/filesync.go
solver/pb/attr.go
source/identifier.go
source/local/local.go
vendor/github.com/docker/docker/builder/dockerignore/dockerignore.go

This is a different implementation than the one in `docker build --stream`. `.dockerignore` is pulled into the frontend and parsed there so that client doesn't need to know anything about that format.
The second commit adds shared key hint metadata to source op that is set by Dockerfile frontend. This is needed because 2 source requests are made to the same location. Without it, on the subsequent build, loading `dockerignore` will sync to a location where build context used to be and vice versa, making the incremental sync inefficient.

dockerfile: dockerignore support

---

frontend/dockerfile/dockerfile_test.go
source/git/gitsource.go
source/gitidentifier.go

The test exposed a problem for handling servers that don't support `depth`. Instead of doing some detection that would slow down the primary execution path just retry without `--depth` on error.

dockerfile: add test for building from git repo

---

Makefile
README.md
cmd/buildd/main.go
cmd/buildd/main_containerd_worker.go
cmd/buildd/main_oci_worker.go
examples/buildkit0/buildkit.go
examples/buildkit1/buildkit.go
examples/buildkit2/buildkit.go
examples/buildkit3/buildkit.go
examples/gobuild/main.go
frontend/dockerfile/dockerfile_test.go
hack/dockerfiles/test.Dockerfile
hack/test
util/testutil/integration/containerd.go
util/testutil/integration/oci.go
worker/runc/runc_test.go

Not `no_oci`, as it still conforms to the OCI spec

*: update build tags (`containerd` -> `no_oci_worker`)

---

README.md
client/client_test.go
client/exporters.go
client/solve.go
exporter/oci/docker.go
exporter/oci/export.go
worker/base/worker.go

```
buildctl build ... --exporter=docker --exporter-opt name=myimage | docker load
```
The exported tarball is compatible with Docker v1.10 and newer. Older versions that only accept the `v1.0` tarball will not work.
The tarball is also fully compatible with OCI. We can figure out later if containerd upstream is also interested of any of this code and in what way and what packages should contain what code(related to #215). My current thinking is that special package for `exporter/oci` is not needed and different variants can all be under `containerimage`.
based on #227

Add Docker exporter

---

examples/build-using-dockerfile/main.go

This subcommand mimics `docker build` CLI flags so that Docker users can
more easily get started with BuildKit.
The command name was inspired by `buildah bud`.

example: build-using-dockerfile

---

solver/solver.go

This is useful when building similar files from multiple sources concurrently. If there is a possibility for a content-based match it will wait for one source to finish before continuing with another. I'll make a better fix with the next solver refactor.

solver: add simple locking to catch content duplicates

---

README.md

readme: update instructions

---

solver/jobs.go
util/progress/progressui/display.go

- When part of the build was cached progress report for some vertexes could be skipped. 
- When building with frontends that dynamically load more vertexes client could temporarily report build as finished. 

progress: fix skipping cached vertex progress

---

cache/fsutil.go

Not mounting `readonly` here meant that the source snapshot for dockerignore and Dockerfile couldn't be reused(because another snapshot was created on top of it).

cache: mount readonly in readfile handler

---

client/client.go
cmd/buildctl/main.go
cmd/buildkitd/main.go

This PR adds logic and commandline flags for buildkitd and buildctl to configure TLS certificates, keys and CA certificates.
There are now the following three options:
* Use no TLS, the whole thing is opt-in and completely backward compatible
* Use a certificate and key on the server and a ca-certificate at the client
* an ephemeral key exchange is performed
* the client verifies the server certificate
* Use cert, key and ca-cert on server and client
* the connection is verified by both ends
From the API perspective this is implemented as the ClientOption WithCredentials() which takes pathes to the requested files as arguments.
To be able to effectively prevent man in the middle attacks or unauthorized access in unsecure networks, using TLS is the way to go in the current gRPC setup.

transport: add possibility to use TLS secured transport layer

---

hack/lint
hack/test
hack/update-vendor
hack/validate-vendor

`mktemp` in `macos` doesn't support `--tmpdir` flag.

hack: fix scripts for macos

---

cmd/buildkitd/main.go

buildkitd: fix index-out-of-range panic in parsing wrong addr string

---

cmd/buildctl/trace.go

```
$ buildctl
NAME:                             
buildctl - build utility       
USAGE:                            
buildctl [global options] command [command options] [arguments...]                                                                   
VERSION:                          
0.0.0                          
COMMANDS:                         
du       disk usage          
prune    clean up build cache                                  
build    build               
debug    debug utilities     
help, h  Shows a list of commands or help for one command      
GLOBAL OPTIONS:                   
--debug                enable debug output in logs               
--addr value           buildkitd address (default: …
```

buildctl: fix nil panic

---

solver2/solver/index.go
solver2/solver/index_test.go
solver2/solver/jobs.go
solver2/solver/llb/vertex.go
solver2/solver/memorycache.go
solver2/solver/memorycache_test.go
solver2/solver/pipe.go
solver2/solver/pipe_test.go
solver2/solver/progress.go
solver2/solver/result.go
solver2/solver/scheduler.go
solver2/solver/scheduler_test.go
solver2/solver/types.go

This PR adds a new solver pkg implementation that is meant to replace the existing solver in the future.
Some benefits compared to existing one:
- Different definitions that return the same cache keys are deduplicated even if they are evaluated in parallel. For example, if `alpine:latest` and `alpine@sha256:deadbeef` are used in the same or concurrent build they (and all commands on top of them) are only evaluated once.
- Smarter evaluation of inputs and smarter cache loading. A problem with current solver was that because all inputs were evaluated in parallel, if we got a cache match for the parent node later in the process there was a wasted effort that needed to be canceled. This was especially bad on using remote cache together with source files relying on content-based cache. New …

solver: new implementation

---

frontend/dockerfile/dockerfile2llb/convert.go
vendor/github.com/docker/docker/builder/dockerfile/shell/equal_env_unix.go
vendor/github.com/docker/docker/builder/dockerfile/shell/equal_env_windows.go
vendor/github.com/docker/docker/builder/dockerfile/shell/lex.go

 Remove shell parser for dockerfile2llb, using moby upstream package 

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go

There was a bug when second copy created an extra basename in the destination path.
@vdemeester 

dockerfile: fix issues with duplicate copy instructions

---

solver-next/edge.go
solver-next/index.go
solver-next/memorycache.go
solver-next/memorycache_test.go
solver-next/scheduler_test.go
solver-next/types.go

A selector can be used to connect an identifier to the input that is merged with the input's cache key. One example where this will be used is using a mount in `execop` that mounts a subdirectory. The name of that subdirectory is added to the cache chain so that if this directory changes, cache would need to be reevaluated. The selector is not just included in the base digest so that result based cache doesn't need to include it. For example, if the location of the source files differs but they still have the same content you still get a cache match.

solver: implement selector for cachemap

---

solver-next/edge.go
solver-next/internal/pipe/pipe.go
solver-next/memorycache.go
solver-next/memorycache_test.go
solver-next/result.go
solver-next/scheduler_test.go
solver-next/types.go

Add export support to solver-next. This turned out to be a bit more complicated than I had liked. Hopefully, I can simplify it a bit with the actual json registry format as there is no need to track the connections of the cache records there, it can just return every record that points to it in the json. I'm also not sure if it actually makes sense to track the cache connections in `Query()` instead of just using all the children cache keys. It seems like a tiny optimization that adds a lot of complexity. If there is no practical case where this can be used to make the cache chain grow on every invocation, it can be removed in the future.

solver: add cache export support

---

cmd/buildkitd/main_oci_worker.go
worker/runc/runc.go
worker/runc/runc_test.go

Part of rootless mode ( https://twitter.com/_AkihiroSuda_/status/955698849560997888 ).
overlayfs is generally not available in userns (except Ubuntu, Plamo Linux, and some distros)
ref: https://github.com/moby/buildkit/issues/257 https://github.com/moby/buildkit/issues/252 https://github.com/cyphar/rootlesscontaine.rs/pull/6

worker/oci: allow using naive snapshotter

---

cmd/buildkitd/main_oci_worker.go
worker/runc/runc.go
worker/runc/runc_test.go

For deduplicating https://github.com/jessfraz/img/blob/f8acce2bab651ed2dc2a9ce737f3d143cbba2484/worker/runc/workeropt.go
(fuseserver and differs would be handled outside of this function)
cc @jessfraz
part of https://github.com/jessfraz/img/issues/21

worker/oci: allow specifying arbitrary snapshotter factory

---

session/manager.go

Session prefix is used in "dev-mode" of gateway frontend to build both frontend and actual build job using frontend together. It sets a prefix to session so that local sources created with a common name (eg. "context" for dockerfile) do not collide. The local source itself had logic to correct this prefix.
The problem is that this conflicts with other use cases of the session like authentication tokens. As a quick solution, we can just skip the prefix as it is can never be used for lookup anyway. I think the more correct solution is to expose a special prefix name either to the frontend or inject it in llbbridge . Currently, sessionID is reused for this just because it is a variable that is passed together with a build, not because there is actually a different session.
Testing:
``` …
```

session: clear prefix on lookup

---

exporter/oci/export.go
util/dockerexporter/dockerexporter.go

@stevvooe @dmcgowan 
Maybe we want to move this to containerd?

exporter/oci: split reusable dockerexporter

---

README.md
solver/pb/ops.pb.go
solver/pb/ops.proto

llb: update docs

---

solver-next/boltdbcachestorage/storage.go
solver-next/cache.go
solver-next/cache_test.go
solver-next/cachestorage.go
solver-next/cachestorage_testsuite.go
solver-next/edge.go
solver-next/memorycachestorage.go
solver-next/types.go

This adds support for gradually releasing cache for objects that have been deleted. The cache chain remains intact until it still points to at least a single result, with `Query` calls returning cache records with `Loadable` set to false.

solver: add support for releasing cached results

---

source/containerimage/pull.go
worker/base/worker.go

When using `--frontend=gateway.v0` in order to use a tagged image as the
frontend it is currently required to push the tag to a registry, so that
buildkit can pull it. One can use the `image@sha256:digest` form but this is
inconvenient for the development cycle.
Instead, if the pull fails check check the local image store (if there is one,
which is worker dependent) for a suitable image and if so use that.
With this I can now:
buildctl build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --exporter=image --exporter-opt=name=docker.io/ijc25/fe:dev
builtctl build --frontend=gateway.v0 --frontend-opt=source=ijc25/fe:dev --exporter=image --exporter-opt=name=hello-world:dev
Without any push to a registry.
I am using the containerd worker.
Signed-off-by: Ian Campbell …

Use local images if pull fails

---

client/client_test.go
source/containerimage/pull.go

As well as reverting the wrong change from #296 and adding an integration test this fixes the cache/gc management in `puller.Snapshot`. Best explained by the commit message of the middle commit:
```
Correct content-store management after schema1 conversion
The previous code had 3 issues:
- The original schema 1 manifest remained in `ongoing.added` but was not added
to the content store by the conversion. #296 tried to address this in an
incorrect way and was reverted by the previous commit. Instead switch in the
schema2 manifest, which was otherwise missed.
- Empty layers in the schema 1 manifest are not propagated to the schema 2
version, meaning they are not referenced by anything and hence are never
freed up and therefore leak
- The new schema 2 image config is generated by the …
```

Improved schema1 support

---

hack/dockerfiles/vendor.Dockerfile
vendor.conf

At the moment vendor.conf is missing entries for `github.com/tonistiigi/llb-gobuild`
and `github.com/morikuni/aec` due in part because of a combination of
https://github.com/LK4D4/vndr/issues/62 and https://github.com/LK4D4/vndr/issues/63.
The issue vndr#63 (related to lack of `github.com/morikuni/aec`) can be worked
around by removing the vendor directory before rerunning `vndr`, so do so.
Due to vndr#62 the issue with `github.com/tonistiigi/llb-gobuild` cannot be
detected at the moment, but pass `-strict` to `vndr` in anticipation of a fix
there.
This will make the CI fail on this PR (I hope). Once it has done so I will push an extra patch which fixes things by adding the `github.com/morikuni/aec` entry to `vendor.conf`.
I will not add the `github.com/tonistiigi/llb-gobuild` since the …

vendoring: try to catch more vendoring issues & fixup an existing one

---

solver-next/boltdbcachestorage/storage.go
solver-next/cache.go
solver-next/cache_test.go
solver-next/edge.go
solver-next/memorycachestorage.go
solver-next/result.go
solver-next/scheduler.go
solver-next/scheduler_test.go

This fixes the case where on content based cache match the new definition based key was not stored. Meaning that on next invocation a content based match (that is much more expensive in remote cache cases) was needed again. 
Also fixes result releasing bugs.

solver-next: add support for cache tracking through query

---

solver-next/boltdbcachestorage/storage.go
solver-next/cache.go
solver-next/cache_test.go
solver-next/cachestorage.go
solver-next/cachestorage_testsuite.go
solver-next/edge.go
solver-next/memorycachestorage.go
solver-next/types.go

This changes the cache management away from every cachekey tracking its full dependencies, making the code simpler and heavily reducing the duplicate calls.
The second commit simplifies the storage backend, removing the main contentkeyinfo storage and only persisting the links.
At least some changes still required(follow-up):
- Exporter should export the indirect deps for keys found by definition if they are roots (for the additional content based key)
- Internalkey should be different by backend(starts to matter for combined cache managers)
- Prune should call `cachestorage.Release()`
- Maybe: By adding a new method `GetRecords()` to cache interface we could avoid calling `WalkResults` for each input and only call it once per parent edge.

solver: simplify cache storage backend

---

examples/gobuild/main.go

containerd master doesn't build with `go1.9` anymore

examples: fix gobuild example

---

solver-next/edge.go

I saw `TestHugeGraph` failing in CI. The issue seemed to be that cache function got called twice on certain conditions because the child pipe got canceled and then restarted because of other child pipes changed the internal state of the edge. I think there is no need to ever cancel a child pipe that is already running because of the internal state change. Eventually, one of the parents will complete and cancel the incoming request, closing down the pipes. If this doesn't happen we need the result anyway so it is more performant to keep it running.

solver: don’t cancel child pipes from state change

---

client/llb/exec.go
client/llb/llbbuild/llbbuild.go
client/llb/llbbuild/llbbuild_test.go
client/llb/source.go
client/llb/state.go

This brings in the following optimization:
- cache for state marshalling is checked before remarshalling its children
- validation calls are cached
- digest of the cached marshalled content is cached instead of recomputing
@AkihiroSuda The last one has the least meaningful impact and is the only one that breaks the public API for the package. I'm willing to remove that one if you think it is not worth it. The other 2 have a big impact on very big graphs. 

client: speed up llb marshal

---

client/llb/exec.go

This seems to have missed out on an update/refactor at some point and was not
usable in its previous form without duplicating the `runOptionFunc`
scaffolding.
I tried to use this with:
```
run := llb.Image("busybox:latest").Dir("/src").Run(
llb.ReadonlyRootFS(),
```
and got:
```
OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v1.linux/buildkit/z6784cdfkkt1ht90tenq4h67n/rootfs\\\" at \\\"/proc\\\" caused \\\"mkdir /run/containerd/io.containerd.runtime.v1.linux/buildkit/z6784cdfkkt1ht90tenq4h67n/rootfs/proc: read-only file system\\\"\"": unknown
```
so at least for some …

Convert ReadonlyRootFS to a RunOption

---

client/client_test.go
executor/oci/spec_unix.go
solver/llbop/exec.go

Otherwise the daemon panics.
This was my mistake on the client side but I suppose we don't want the daemon crashing...

Check that mounts have a Source when generating the OCI spec

---

util/throttle/throttle.go
util/throttle/throttle_test.go
worker/containerd/containerd.go
worker/runc/runc.go

Throttle invoking the gc after object deletion for performance.

worker: throttle calls to gc

---

client/client_test.go
executor/containerdexecutor/executor.go
executor/executor.go
executor/runcexecutor/executor.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/gateway/gateway.go
hack/test
solver/llbop/exec.go
worker/runc/runc_test.go

busybox image):
OCI runtime create failed: container_linux.go:348:
starting container process caused "process_linux.go:402:
container init caused \"rootfs_linux.go:58:
mounting \\\"proc\\\" to rootfs \\\"/.../rootfs\\\" at \\\"/proc\\\"
caused \\\"mkdir /.../rootfs/proc: read-only file system\\\"\"": unknown
This is because we were setting the underlying snapshot readonly so the various
mountpoints (here /proc) cannot be created. This would not be necessary if
those mountpoints were present in images but they typically are not.
The right way to get around this (used e.g. by `ctr`) is to use a writeable
snapshot but to set root readonly in the OCI spec. In this configuration the
rootfs is writeable when mounts are processed but is then made readonly by the
runtime (runc) just before …

Make llb.ReadonlyRootFS usable with common container images

---

source/git/gitsource.go
source/git/gitsource_unix.go
source/git/gitsource_windows.go

Fixing issue where context cancellation didn't work for some git commands that were spawning helper processes. There may be a go issue in here, eg. `CommandContext` could kill the process group if `setpgid` is set.

git: fix cancellation on blocking remotes

---

client/solve.go
cmd/buildctl/build.go
session/auth/auth.go
session/auth/authprovider/authprovider.go

Separate `authprovider` pkg so that everything that needs to import `client` (for example just for types) doesn't need dependency from `docker/cli`.

session: separate authprovider to package

---

solver-next/boltdbcachestorage/storage.go
solver-next/cachestorage.go
solver-next/cachestorage_testsuite.go
solver-next/edge.go
solver-next/exporter.go
solver-next/jobs.go
solver-next/memorycachestorage.go
solver-next/scheduler_test.go
solver-next/types.go

Add support for an operation to return multiple cache keys. Index parameter is added to `CacheMap` method that is incremented every time the method is called and the function returns a bool to indicate if more results may be expected. Currently, only root nodes can return multiple keys. If a key causes a cache match the later ones are not queried.
This will be used for image source where one key is the manifest digest and another image config digest(or chainID) so that you can get a quick match by one but if only blobs/config changes in the image it will not invalidate the cache. For HTTP sources this can be used to have a first cache key that is "url+etag" and a second one that is the checksum of the content. Currently, we only support checksum of the content, meaning that we need to …

solver: add support for multiple cache keys

---

cache/blobs/blobs.go
cache/cacheimport/import.go
cache/contenthash/checksum_test.go
cache/manager.go
cache/manager_test.go
cache/refs.go
executor/containerdexecutor/executor.go
executor/oci/spec_unix.go
executor/runcexecutor/executor.go
snapshot/blobmapping/snapshotter.go
snapshot/containerd/snapshotter.go
snapshot/localmounter.go
snapshot/localmounter_unix.go
snapshot/localmounter_windows.go
snapshot/snapshotter.go
source/containerimage/pull.go
source/git/gitsource_test.go
source/http/httpsource_test.go

Wrap mounts with an interface to allow more freedom on implementing them when a stateless mounts array cannot be created.
@dmcgowan 

snapshot: update mounts to mountable interface

---

frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go

Add test for `LABEL` and a way to override labels with frontend-opt similarily to `docker build --label`

dockerfile: add test for labels

---

solver-next/edge.go
solver-next/scheduler.go

This is a fix for flakiness of `TestCacheExportingMergedKey`. The problem was that if a merged key caused a new cache record to be saved, the deps from the original source were not carried over. Didn't appear if one the merge target already had a cache-match or result.
Also, make sure that the slow cache key from source is maintained, although in almost all cases if this key exists, it should also be the key that caused the match and already captured by the destination.

solver: fix flaky merged keys test

---

solver-next/edge.go
solver-next/exporter.go
solver-next/scheduler_test.go
solver-next/types.go

Add support for configuring how the build cache is meant to be exported. Currently, only added option is to export in "minimal" mode that means that only a single result is exported with the ref conversion, other results are only exported if the remote reference already exists for them(in practice this means already exported cache or parent layers).
There is also a way to set vertex options to override export decision per vertex.

solver: support cache export options

---

solver-next/edge.go
solver-next/index.go
solver-next/index_test.go
solver-next/jobs.go
solver-next/scheduler.go
solver-next/scheduler_test.go

Update the event dispatcher in scheduler to keep the order of the events and therefore avoid possibilities of the dispatcher running twice if a previous event wasn't yet processed. This is mostly for readability of the scheduler debug traces while previously there could be traces that were not associated with a clear trigger event. Although the this will avoid some duplicate work I don't expect a performance increase because the dispatching itself now requires a lock per message, while previously it was per message group. In my testing, I didn't notice any meaningful effect to performance.
Also, clean up the public API. Some functions were public although they were not really usable with public methods.

solver: event dispatcher update and public api cleanup

---

cache/manager.go
source/containerimage/pull.go

Fix another containerd gc race case that showed up in the `llbsolver-next` integration tests. For example https://travis-ci.org/moby/buildkit/builds/377155580
The problem is that when the refs are deleted there is no way to synchronously delete the underlying containerd snapshot as well. So if the timing is correct the cache will see if there is a reference to an ID, and even though it has been deleted the `snapshotter.Stat` still returns fine as the gc has not cleaned it up yet and the ref is recreated. What makes things worse is that this reference has lost all its metadata about blob references, so the cache/image exporter would use a differ for reconstructing these blobs instead of using the original ones.
Didn't find a better solution than to add an extra method. The original `Get` …

cache: avoid reloading snapshots in gc queue

---

cache/refs.go
solver-next/llbsolver/ops/exec.go

Add helper methods for dealing with refs. ~~`New` avoids having access to cachemanager directly.~~ `Clone()` avoids calling much heavier `Get()/Release()` method every time a ref is passed through ops.
edit: removed `New`

cache: helper methods for immutableref

---

cache/metadata.go
cache/refs.go
solver-next/edge.go
solver-next/jobs.go

This was initially disabled in `llbsolver-next` for performance. With https://github.com/moby/buildkit/pull/376 this should be tolerable now. It can still be made much better with moving these write to async but that can be done in a separate, lower priority issue.

cache: reenable last used metadata

---

client/client_windows.go

This makes `tcp://w.x.y.z:port` work from Windows based clients (perhaps
talking to a remote Linux based buildkitd or one running in a container with
Docker for Windows and TCP port forwarding).

client: support non-npipe server addresses on Windows

---

frontend/dockerfile/dockerfile_test.go
vendor.conf
vendor/github.com/tonistiigi/fsutil/receive.go
vendor/github.com/tonistiigi/fsutil/send.go

This commit fixes the case when "!" is provided alone as a dockerignore
pattern resulting in buildkit hanging. An integration test is added to
guard the bug.
The bug was due to incorrect error propagation in the fsutil package.
Thus this commit vendors a newer, fixed version of fsutil.
Ref https://github.com/tonistiigi/fsutil/pull/30

dockerfile: fix hanging when encountering invalid dockerignore pattern

---

frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile2llb/directives.go
frontend/dockerfile/dockerfile2llb/directives_test.go

Add syntax directive for specifying the builder reference so that new dockerfile features can be targeted. New Dockerfile features can be added now without breaking backward compatibility or requiring users to upgrade. The base one would remain compatible with current moby/docker.
@tiborvass 

dockerfile: add syntax directive for introducing new features

---

examples/buildkit0/buildkit.go
examples/buildkit1/buildkit.go
examples/buildkit2/buildkit.go
examples/buildkit3/buildkit.go

libseccomp-dev is required for building containerd:
```
> make bin/containerd
..
Package libseccomp was not found in the pkg-config search path.
..
```

examples/buildkit*: add libseccomp-dev

---

.dockerignore
.gitignore
cmd/buildctl/main.go
cmd/buildkitd/main.go
hack/dockerfiles/test.Dockerfile
version/version.go

Close #397 
Follows containerd convention:
https://github.com/containerd/containerd/blob/cff5e75df87b39c7c4134ccaf58db3abeec46e3d/Makefile#L22-L24

hack: embed git revison into binaries

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go
solver/llbsolver/bridge.go
solver/llbsolver/result.go
source/containerimage/pull.go
worker/result.go

Currently, a build that pulls an image that doesn't have any layers would error. This lets the source return a `nil` result that behaves like an empty directory on file accesses.
The update to the dockerfile is optional. It would work without it as well but this way we can detect an image that will not produce a result early.

Allow empty results in llbsolver

---

client/llb/imagemetaresolver/resolver.go
source/containerimage/pull.go
util/imageutil/config.go

This PR is really an issue for discussion with some illustrative code attached. It solves an issue for me on the client side but breaks the build of buildkitd.
I have a setup with a buildkit client (grpc) which runs on any of Linux/Mac/Win and talks (via tcp) to a `buildkitd` backend running on Linux (actually in a Docker container). I developed and tested on Linux and all was well but when I came to run on Mac buildkit was unable to pull the required base image -- because there was no Darwin image in the manifest (obviously), this happened because the pull was in this case running on the client e.g. `llb.Image(ref, llb.WithMetaResolver(imagemetaresolver.Default())` where `runtime.GOOS == "darwin"`.
What I actually wanted was to resolve the `linux/amd64` image unconditionally. If I apply …

handling of foreign platform clients

---

frontend/dockerfile/dockerfile2llb/convert.go
source/http/httpsource.go

- Enable --no-cache for `COPY/ADD` commands because the checksum ignores modtime
- HTTP: include modtime in the cache checksum so the cache is invalidated if header changes in the server.

Fixes for cache invalidation on modtime change

---

solver/llbsolver/ops/exec.go
source/git/gitsource.go
util/progress/logs/logs.go

Historically exec ops also print stdout to daemon logs. Remove this, but leave an environment variable toggle if someone wants to use it during development.

exec: make stdio debugging optional

---

client/llb/source.go
frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile_test.go
solver/pb/attr.go
source/identifier.go

Add clearer support for all supported git transports that optionally switch to another attribute field instead of making invalid URLs. Also, update dockerfile to accept https://../repo.git as a git URL instead of HTTP URL

git: support all git transports

---

snapshot/localmounter.go

e.g. https://github.com/genuinetools/img/issues/97 (going to be solved in https://github.com/genuinetools/img/pull/111)
```
$ img build -t foo .
Building docker.io/library/foo:latest
Setting up the rootfs... this may take a bit.
[+] Building 0.0s (2/2) FINISHED                                                                                      
=> local://dockerfile (Dockerfile)                                                                              0.0s
=> => transferring dockerfile: 216B                                                                             0.0s
=> local://context (.dockerignore)                                                                              0.0s
=> => transferring context: 02B …
```

snapshot: wrap mount err

---

hack/dockerfiles/test.Dockerfile

I noticed that the dockerfile does not work with some older docker versions that don't have a fix for https://github.com/moby/moby/pull/35456 . This temporarily makes it work again for these versions.
@AkihiroSuda 

hack: mitigate bug in old docker version

---

util/system/seccomp_linux.go
util/system/seccomp_noseccomp.go

Fixes the issue described in https://github.com/genuinetools/img/issues/97#issuecomment-394144596

support when build without seccomp build tag

---

executor/oci/mounts.go
executor/oci/spec_unix.go
worker/runc/runc_test.go

containerd/oci_specs mounts `/run`, which is not
required by buildkit.
Fixes #429 
Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>

Default mounts set for buildkit

---

executor/runcexecutor/executor.go

Carry https://github.com/moby/buildkit/pull/298

oci-executor: eval symlink for root

---

cmd/buildctl/build.go
examples/build-using-dockerfile/main.go
util/progress/progressui/display.go
util/progress/progressui/printer.go

closes #33
Add a streaming text output with logs for builds that attempts to be readable, responsive and supporting parallel running nodes.
Enabled on `buildctl build --no-progress`, `buildctl build 2>&1 | cat` or when there is no console.
~wip: I want to make the switching between parallel outputs better. TODO with the planned algorithm in code. But this should be good enough for initial feedback.~
@AkihiroSuda @tiborvass @vdemeester @dhiltgen

progressui: add better streaming text build status

---

client/client_test.go
frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/convert_norunmount.go
frontend/dockerfile/dockerfile2llb/convert_runmount.go
frontend/dockerfile/instructions/bflag.go
frontend/dockerfile/instructions/commands.go
frontend/dockerfile/instructions/commands_runmount.go
frontend/dockerfile/instructions/parse.go
hack/test
solver/llbsolver/ops/exec.go

This implements moby/moby#32507 (missing tmpfs support atm) as an experimental feature of Dockerfile frontend. The main `dockerfile.v0` frontend is unaffected. 
It can be used by building the frontend with a `dfrunmount` build tag and then loading it with either the gateway frontend or syntax directive (or `gateway-devel` to run from source on development).
The keys from the `--mount` options are taken from the ones supported by `docker run`. I'm not sure if we want to keep the ambiguous ones.
I also ran into a case where a scratch mount would error if binded. This was explicitly validated with a test but I don't think that is required. Even though there is no use case for this we can just create an empty temporary readonly directory instead of failing the build. @ijc 
example:1
```
from …
```

dockerfile: add run --mount support

---

util/libcontainer_specconv/example.go
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go
vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
vendor/github.com/opencontainers/runc/libcontainer/user/user.go

For https://github.com/opencontainers/runc/pull/1819

vendor runc ad0f5255060d36872be04de22f8731f38ef2d7b1

---

client/client.go
client/client_test.go
cmd/buildctl/debug/workers.go
cmd/buildctl/main.go
examples/build-using-dockerfile/main.go
frontend/dockerfile/dockerfile_test.go

This allows two things:
- The caller to set a shorter timeout than the existing 30s (the 30s remains as
a backstop). Use this in `buildctl` to reduce the timeout to demonstrate
(also on the theory that a CLI tool shouldn't need a very long timeout).
- The caller can arrange for the context to be cancelled for other reasons, use
this in `buildctl` to plumb through the Ctrl-C handling, meaning that
`buildctl` now exits almost immediately on Ctrl-C instead of after several
seconds.

client: take a context.Context to New().

---

frontend/gateway/gateway.go

Digest from `ResolveImageConfig` should be optional and gateway should work without it as well.

gateway: allow digest to be optional

---

control/control.go
examples/buildkit0/buildkit.go
examples/buildkit1/buildkit.go
examples/buildkit2/buildkit.go
examples/buildkit3/buildkit.go
examples/gobuild/main.go
examples/nested-llb/main.go
solver/llbsolver/bridge.go
solver/llbsolver/solver.go
solver/llbsolver/vertex.go

This builds on #461 #462 to add validation of runtime platforms to the exec ops.
Only last commit is new. Will rebase after other are merged.
@tiborvass

llbsolver: validate runtime platforms for exec op

---

executor/containerdexecutor/executor.go
executor/oci/user.go
executor/runcexecutor/executor.go
frontend/dockerfile/dockerfile_test.go

- This PR fixes issue #412 by adding the missing supplementary group IDs whenver `containerdexecutor` or `runcexecutor` is called.
- Lift over some dockerfile build tests from moby to enhance buildkit testing.
- Added separate fix in containerd (TBP)
cc @tonistiigi 
Signed-off-by: Anda Xu <anda.xu@docker.com>

add missing supplementary group IDs

---

hack/dockerfiles/test.Dockerfile

The error appears in
```
RUN go build -ldflags "$(cat .tmp/ldflags)" -o /buildctl.exe ./cmd/buildctl
```
and
```
RUN go build -ldflags "$(cat .tmp/ldflags)" -o /buildkitd.exe ./cmd/buildkitd
```
We ignore ".tmp" by ".dockerignore" file, so `COPY . .`
does not copy ".tmp".
This commit changes the image for "cross-windows" and removes
not needed instructions which are done by "buildkit-base".
This is follow up of https://github.com/moby/buildkit/pull/398

Fix "cat: can't open '.tmp/ldflags': No such file or directory" errors

---

README.md

The readme examples used an old image. I'm not sure if it would make sense to push the master build to `tonistiigi/dockerfile` to make it more clear. I think it would be better to do that after #466 .
At the time of posting this PR `tonistiigi/dockerfile:master` and `tonistiigi/dockerfile:latest` point to the same image, but `tonistiigi/dockerfile:latest` requires manual updating.
related #469

readme: update dockerfile image

---

cmd/buildkitd/main.go
cmd/buildkitd/main_linux.go
cmd/buildkitd/main_nolinux.go
cmd/buildkitd/main_oci_worker.go
executor/runcexecutor/executor.go

* rootless: fix default path configuration
* if buildkitd is being executed as the mapepd-root ($USER==root)
in a rootless container, we need to enable the rootless mode but
we don't want to honor $HOME.
* rootless: bail if euid != 0

Fix rootless

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/convert_norunmount.go
frontend/dockerfile/dockerfile2llb/convert_runmount.go

`dispatchStates` manages a collection of `dispatchState`.
By `dispatchStates`, we can aggregate how to find `dispatchState`
in one place and `dispatchStatesByName` local variable in `Dockerfile2LLB`
can be removed.

Introduce `dispatchStates` type

---

frontend/dockerfile/instructions/commands.go

`ADD` does not support git.
Ref: https://github.com/moby/moby/issues/14704#issuecomment-298134333

Update documents of `AddCommand`

---

cmd/buildctl/debug/dumpllb.go

The command, used as the dot label, can contain quotes which need escaping when
used within the quoted string.
Formatting with `%q` rather than `\"%s\"` does this for us.
I don't believe digests or the shapes can ever contain quotes (or other unusual
characters) but switch them to `%q` as well for consistency.

buildctl: quote quotes in dot dump of llb

---

frontend/dockerfile/dockerfile_test.go

Fix orders of `require.Equal` argument to "expected, actual"

---

cache/remotecache/export.go
cache/remotecache/import.go
cache/remotecache/registry/registry.go
cmd/buildkitd/main.go
control/control.go
frontend/frontend.go
solver/llbsolver/bridge.go
solver/llbsolver/solver.go
util/contentutil/fetcher.go
util/contentutil/fetcher_test.go
util/contentutil/pusher.go

ref: #224 
This PR decouples `cacheimport` from Docker registry so that caches can be copied from a worker to another worker without registry.
The interface almost corresponds to @tonistiigi 's proposal (https://github.com/moby/buildkit/issues/224#issuecomment-352098469), but there is no `WorkerRef` yet.

decouple remotecache from Docker registry

---

README.md
hack/dockerfiles/test.Dockerfile
util/testutil/integration/containerd.go

Having '/' in a worker name is confusing.

integration: rename "/opt/containerd-1.0/bin/containerd" worker to "containerd-1.0"

---

util/rootless/specconv/specconv_linux.go

Signed-off-by: Noel Georgi <18496730+frezbo@users.noreply.github.com>
@AkihiroSuda This was failing when I updated `img` to use latest buildkit. Not sure if its the right fix.
Build Error:
```
img (aws:rean-gov-sd)(kc)(git:master)*$ make   BUILDTAGS=""
+ img
go build -tags "" -ldflags "-w -X github.com/genuinetools/img/version.GITCOMMIT=bcebacfc-dirty -X github.com/genuinetools/img/version.VERSION=v0.4.6" -o img .
vendor/github.com/moby/buildkit/util/rootless/specconv/specconv_linux.go:66:20: invalid operation: uNextContainerID += u.Count (mismatched types int64 and int)
vendor/github.com/moby/buildkit/util/rootless/specconv/specconv_linux.go:77:20: invalid operation: gNextContainerID += g.Count (mismatched types int64 and int)
make: *** [Makefile:37: img] Error 2
```

Fixing mismatch

---

hack/test

We don't need it once we have assigned to `$iid`, so remove it otherwise it can
be leaked if any of the `docker run` lines fails (since we immediately exit due
to `set -e`).
(was an unrelated bonus in #492, not carried in #495)

hack/test: remove `$iidfile` earlier

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/instructions/commands.go
frontend/dockerfile/instructions/parse.go

`keyValuePair` is enough in this case. We can avoid create `ArgCommand` out of Parser by replacing them with `keyValuePair`.
And stop to update Value of ArgCommand.

Use simple `keyValuePair` to `dispatchOpt.metaArgs` and `dispatchState.buildArgs`

---

cache/blobs/blobs.go
cache/manager.go
cache/manager_test.go
cache/refs.go
frontend/dockerfile/dockerfile_test.go
solver/llbsolver/bridge.go

Do not finalize records unless the blobs or child snapshots are needed. In other cases just mark the record as retained so it does not get cleaned up.
This fixes an issue where currently in Dockerfile, `dockerfile` and `dockerignore` locals would not be reused on repeated builds because the local refs were the output of build and therefore committed into an immutable snapshot.

cache: avoid commit on finalize when possible

---

frontend/dockerfile/shell/lex.go
frontend/dockerfile/shell/lex_test.go

I think to process word with map (from string to string) is common pattern.
For example these codes concat key and value with "="
https://github.com/moby/moby/blob/facad557440a0c955beb615495b8d0175f25e4e3/builder/dockerfile/builder.go#L287
https://github.com/moby/moby/blob/facad557440a0c955beb615495b8d0175f25e4e3/builder/dockerfile/dispatchers.go#L226
By adding `ProcessWordWithMap`, we can remove these setup codes.

Add `ProcessWordWithMap` to `Lex`

---

client/llb/source.go

These sources are not platform specific so avoid setting platform value that causes parallel requests to calculate the cache key again.

llb: don't fill platform on static sources

---

cmd/buildkitd/main.go
cmd/buildkitd/main_containerd_worker.go
cmd/buildkitd/main_oci_worker.go

split out from #499 for easier review
Containerd does not currently support configuring additional runtime platforms and always only returns an array with only one item containing the detected platform. This adds the same flag `oci` worker supports until containerd gets this support.
@dmcgowan @AkihiroSuda Ok to add additional runtime conf to containerd config?

buildkitd: allow custom worker platforms for containerd

---

cache/blobs/blobs.go
cache/metadata.go
source/containerimage/pull.go
util/winlayers/applier.go
util/winlayers/context.go
util/winlayers/differ.go
worker/containerd/containerd.go
worker/runc/runc.go

split from #499 for easier review
The tar blobs containing the layers have a different structure in linux and windows. The current differ ignores that and hopes that the differ is compatible with the blob.
For example, linux blobs directly contain the rootfs for the container while windows container have a structure like `Files/`, `Hives/`, `UtilityVM` with the `Files` directory containing the actual rootfs. Additionally, the records in the windows layer tarball need to contain specific PAX headers that are required for the files to be accessible from the container.
In order to allow cross-build from one os to another, this PR enables additional features in the differ that enable it to apply and diff windows layers on linux, with existing linux snapshotters. On apply only contents of …

diff: implement windows layer support for linux

---

frontend/dockerfile/dockerfile2llb/convert.go

In the case when the second argument of `toEnvList` is `nil`,
we can use `ProcessWordWithMap` and avoid string contatination
and string split.

Use `ProcessWordWithMap` in simple cases

---

source/local/local.go

FollowPaths is a special case of IncludePatterns and
should behave same way.

local: add followpaths to the cache key

---

frontend/dockerfile/dockerfile2llb/convert.go

`dispatchEnv` called in `Dockerfile2LLB` does 2 things
* `AddEnv` to `d.state`
* `addEnv` to update `d.image.Config.Env`
But updating `d.image.Config.Env` has no effect on `d.image.Config.Env` because this is in for-loop of `range d.image.Config.Env`. So replace it with `d.state = d.state.AddEnv(parts[0], v)`.
And omit commit argument of `dispatchEnv `.

Refactoring dispatchEnv

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/convert_test.go

Extract parsing logic of "key=val" as `parseKeyValue`

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/convert_test.go
frontend/dockerfile/shell/lex.go
frontend/dockerfile/shell/lex_test.go

* Use `ProcessWord(s)WithMap` to avoid string contatination and string split.
* Omit needless argument `override` from `addEnv`

Refactor `toEnvList`

---

executor/runcexecutor/executor.go

moby creates workdir 0755 if the directory specified by workdir does not exist.
https://github.com/moby/moby/blob/master/container/container.go#L256-L284
buildkit will create workdir 0700, but in this case build of the existing Dockerfile may fail.
For example, when Execute command by RUN on workdir as non-root user
Is there a reason to create workdir at 0700 in buildkit?

Create workdir the same permission as existing moby

---

solver/edge.go
solver/jobs.go
solver/llbsolver/solver.go
solver/result.go
solver/scheduler.go
solver/scheduler_test.go
solver/types.go

Cache keys for multi-key roots only worked for the vertex itself but only a single key was linked to the parent vertex.

solver: improve multi-key root caching

---

util/apicaps/caps.go
util/apicaps/caps_test.go

We need to capture `c` within the loop, otherwise all of the entries of `m` end
up pointing to the same thing, which is the last cap in `range caps`.
The symptom was that all caps were enabled/disabled based on the last cap's
setting and not their own.
Add a test for this.
Noticed when adding a cap for #533 that the test didn't fail when I disabled it...

apicaps: record the correct caps when constructing a CapSet

---

client/client_test.go
exporter/containerimage/export.go
exporter/containerimage/exptypes/types.go
exporter/containerimage/writer.go
exporter/exporter.go
exporter/local/export.go
exporter/oci/export.go
frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/platform.go
frontend/dockerfile/dockerfile_test.go
frontend/gateway/gateway.go
solver/llbsolver/solver.go
source/containerimage/pull.go
util/dockerexporter/dockerexporter.go
util/pull/pull.go
util/testutil/tar.go

~based on #496~
Add support for:
- exporting map of references with local/image/oci exporter
- specifying multiple target platforms for Dockerfile frontend
- Implicit platform build args in Dockerfile. Updated version of https://github.com/moby/moby/issues/32487
Example:
```
from --platform=$BUILDPLATFORM busybox AS bb
arg TARGETPLATFORM
run echo "i am $TARGETPLATFORM" > /whoami
from scratch
copy --from=bb whoami .
```
```
buildctl build --frontend-opt platform=linux/arm,linux/amd64,windows/arm,windows/amd64 --frontend=dockerfile.v0 --local context=. --local dockerfile=. --exporter=local --exporter-opt output=/tmp/out
```
```
> ls -l /tmp/out
drwxr-xr-x 2 root root 4096 Jul 10 22:49 linux_amd64
drwxr-xr-x 2 root root 4096 Jul 10 22:49 linux_arm_v7
drwxr-xr-x 2 root root 4096 Jul 10 22:49 …
```

exporter: export multiple refs with local/image exporter

---

solver/llbsolver/solver.go

I saw this:
panic: assignment to entry in nil map
goroutine 3173 [running]:
github.com/moby/buildkit/exporter/oci.(*imageExporterInstance).Export(0xc42094ac40, 0xecac60, 0xc4211ca690, 0xed12c0, 0xc42000fca8, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/moby/buildkit/exporter/oci/export.go:113 +0x156
github.com/moby/buildkit/solver/llbsolver.(*Solver).Solve.func2(0xecac60, 0xc4211ca690, 0xc4202207c0, 0x0)
/go/src/github.com/moby/buildkit/solver/llbsolver/solver.go:132 +0x7d
github.com/moby/buildkit/solver/llbsolver.inVertexContext(0xecac60, 0xc4211ca690, 0xe2ec38, 0x1d, 0xc420d43400, 0x0, 0x0)
/go/src/github.com/moby/buildkit/solver/llbsolver/solver.go:203 +0x1f6
github.com/moby/buildkit/solver/llbsolver.(*Solver).Solve(0xc4203f7dc0, 0xecac60, 0xc420deb830, 0xc4203ed200, 0x19, 0xc4202ff840, …

solver: avoid dereferencing nil res.Metadata

---

exporter/containerimage/export.go
exporter/oci/export.go

Failure to do so would potentially lead to a panic. Belt & braces followup
for #555.
`localExporterInstance` has no `e.meta` to merge and makes no use of the
`Metadata` anyhow (since that doesn't seem to make sense for a local export) so
is unmodified.

Initialise `src.Metadata` in all `{image,oci}ExporterInstance.Export`

---

exporter/containerimage/export.go
exporter/oci/export.go

I think this was just a thinko.
Should the `local` one reject a non-empty `opt` argument to `Resolve`? (cf https://github.com/moby/buildkit/pull/557#discussion_r207817906)

exporters: allow for more than one non-standard metadata key

---

exporter/containerimage/export.go

**What**
Allow that the "name" option of the container image exporter to accept a comma separated list of target names. The code will then loop through it and tag/push to every given target.
**Why**
This allows us to have one Solve() call which will result in multiple images being pushed with minimal overhead. The alternative would have been to call Solve() multiple times and rely on the cache to speed things up but that would be far from optimal.

exporters: containerimage: allow targetName to contain multiple values

---

executor/containerdexecutor/executor.go
executor/oci/spec_unix.go
executor/runcexecutor/executor.go
util/network/network.go
worker/containerd/containerd.go
worker/runc/runc.go
worker/runc/runc_test.go

I separated out part of the work done by @kunalkushwaha in #309 
This only adds the changes made to the executors and the new network provider interface so should be safe to merge. I will use this for bridge networking in moby integration similar way as the cni PR does.
@kunalkushwaha @AkihiroSuda

 executor: allow network providers

---

frontend/dockerfile/dockerfile2llb/convert_nosecrets.go
frontend/dockerfile/dockerfile2llb/convert_runmount.go
frontend/dockerfile/dockerfile2llb/convert_secrets.go
frontend/dockerfile/instructions/commands_nosecrets.go
frontend/dockerfile/instructions/commands_runmount.go
frontend/dockerfile/instructions/commands_secrets.go

Add secret mounts support for Dockerfile using the `RUN --mount` as a base.
```
RUN --mount=type=secret,id=mysecret,target=/foo/bar cmd
```
```
buildctl build --secret id=mysecret,src=path/to/secret
```
ID defaults to the basename of the target and target defaults to `/run/secrets/<id>`.
Pushed an image with support to be used in Dockerfiles:
```
```

dockerfile: implement secret type mounts

---

frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile

Make it easy to export manifest list when building the custom Dockerfile frontend versions.
Docker 18.06 users can set args manually, the defaults still work as well for current platform.

dockerfile: allow multi-target external builds

---

cmd/buildctl/build.go
examples/build-using-dockerfile/main.go
util/progress/progressui/display.go

In clients which are doinging multiple builds or phases it can be useful to say
something more specific here (e.g. "Building first image", "Probing" etc)

progressui: allow caller to customise "Building" string

---

client/build.go
client/build_test.go
client/buildid/metadata.go
client/solve.go
control/control.go
control/gateway/gateway.go
examples/build-using-dockerfile/main.go
frontend/dockerfile/cmd/dockerfile-frontend/main.go
frontend/gateway/gateway.go
frontend/gateway/grpcclient/client.go
solver/llbsolver/solver.go

opening to leave some comments to @ijc 
ref #472

access gateway API from client

---

vendor.conf
vendor/github.com/gogo/googleapis/LICENSE

This is the next commit and merely adds a LICENSE file.
There is one more PR after this point (https://github.com/gogo/googleapis/pull/3) but that requires more extensive changes to bump the other gogo protobuf stuff to match.

Bump github.com/gogo/googleapis to b23578765ee5

---

executor/containerdexecutor/executor.go
executor/oci/spec_unix.go
executor/runcexecutor/executor.go
util/network/host.go
util/network/network.go
util/network/none.go
worker/containerd/containerd.go
worker/runc/runc.go

This fixes the issues where buildkit and callers do not have to be a
subpreaper in order to use networking.  I can add CNI provider later,
with a hidden sub command to create a new network namespace and bind
mount it to buildkit's state dir.
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Refactor networking with ns paths

---

source/identifier.go

Out of the two ResolveMode types in buildkit, only the lower-level one in client/llb
had a String() method. This patch makes the ResolveMode type from the source package
also have a String() method.

source: Have ResolveMode implement fmt.Stringer interface

---

cmd/buildctl/build.go
cmd/buildctl/build_test.go
frontend/dockerfile/dockerfile_test.go

Fixes #443 
Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>

--no-progress replaced with --progress

---

client/client_test.go
solver/llbsolver/solver.go

Propagate anything in the `frontend.*` namespace from the `frontend.Result`
into the `client.SolveResponse`.
I'm a bit unsure about sticking this stuff in to `ExporterResponse`. Perhaps adding a `FrontendMetadata` field to `SolveResponse` might be a better plan? And in that case including everything instead of just `frontend.*` I guess.
WIP because I think it's only really testable once #533 lands.

Allow some Metadata to be return from frontend to the control client

---

solver/llbsolver/bridge.go

This seems wasteful. I think there is no side-effects of the Load+Build of the
definition which would make a difference to the frontend solve.
Note that this changes the presedence of the actual result, previously the
frontend result would overwrite the definition's one, while now the frontend
would not be run.

solver: Don't solve both the provided Defininiton & frontend

---

solver/edge.go
solver/scheduler.go
solver/scheduler_test.go

fixes https://github.com/moby/moby/issues/37603
The issue is from the mixed handling of `dep.keys` and `dep.keyMap` while they have a different meaning(with `keyMap` only containing the keys that have also passed the query against current node).
I'll follow up with another change that adds a non-intrusive handling for these kinds of errors instead of a panic.
@AkihiroSuda @tiborvass

solver: fix panic on creating input requests

---

solver/edge.go
solver/scheduler.go
solver/scheduler_test.go

Instead of panicking on scheduler bugs, try to fix the error case and if that doesn't work clean up and fail the build leaving daemon usable for next requests.
related to #590
@AkihiroSuda @tiborvass

solver: gracefully handle scheduler bugs

---

client/client_test.go
exporter/containerimage/export.go
exporter/oci/export.go

Returning a metadata item named "image.name" will set the name to use.
This is my less ambitious (not templated) replacement for #572, although since the client-gateway stuff has been merged it is now rebased on that and includes a test case so it is a fair bit more code.
This will (probably) conflict with #574 because it adds the same import of the gateway client package in the same place.

exporters: allow frontend control of the exported image name

---

cache/manager.go

- Fixes possible case for deadlock where 2 records share the mutex
- Fix and optimize the size calculation of records that do not have size stored in metadata

fixes for cache prune

---

cmd/buildkitd/config/config.go
cmd/buildkitd/config/config_test.go
cmd/buildkitd/main.go
cmd/buildkitd/main_containerd_worker.go
cmd/buildkitd/main_oci_worker.go
util/appdefaults/appdefaults_unix.go
util/appdefaults/appdefaults_windows.go
vendor.conf
vendor/github.com/BurntSushi/toml/COPYING
vendor/github.com/BurntSushi/toml/README.md
vendor/github.com/BurntSushi/toml/decode.go
vendor/github.com/BurntSushi/toml/decode_meta.go
vendor/github.com/BurntSushi/toml/doc.go
vendor/github.com/BurntSushi/toml/encode.go
vendor/github.com/BurntSushi/toml/encoding_types.go
vendor/github.com/BurntSushi/toml/encoding_types_1.1.go
vendor/github.com/BurntSushi/toml/lex.go
vendor/github.com/BurntSushi/toml/parse.go
vendor/github.com/BurntSushi/toml/type_check.go
vendor/github.com/BurntSushi/toml/type_fields.go

Add a toml config file for configuring the buildkitd daemon. This has come up several times before where it was very cumbersome to use the flags. The intention for finally adding it is that it is required for implementing the gc policies support as gc policies are too big to be managed with cli flags. All CLI flags still work and override config if set.
The default path is `/etc/buildkit/buildkitd.toml`, overridable with `--config`.
Example:
```
root = "/var/lib/buildkit"
debug = false
[grpc]
address = ["unix:///run/buildkit/buildkitd.sock"]
debugAddress = "0.0.0.0:6060"
uid = 0
gid = 0
[grpc.tls]
cert = "/etc/buildkit/tls_cert.pem"
key = "/etc/buildkit/tls_key.pem"
ca = "/etc/buildkit/tls_ca.pem"
[worker.oci]
enabled = true
snapshotter = "overlayfs"
rootless = true …
```

buildkitd: add config file support

---

cmd/buildkitd/main_containerd_worker.go
cmd/buildkitd/main_oci_worker.go
util/testutil/integration/containerd.go
util/testutil/integration/oci.go

Otherwise:
panic: assignment to entry in nil map
goroutine 1 [running]:
main.applyOCIFlags(0xc4200e71e0, 0xc420400000, 0x0, 0x0)
/go/src/github.com/moby/buildkit/cmd/buildkitd/main_oci_worker.go:97 +0x1ac
main.ociWorkerInitializer(0xc4200e71e0, 0xc4204104e0, 0xc420400000, 0x43409b, 0x12, 0xc42026b0f8, 0x4337fc, 0xc420000180)
/go/src/github.com/moby/buildkit/cmd/buildkitd/main_oci_worker.go:118 +0x50
main.newWorkerController(0xc4200e71e0, 0xc4204104e0, 0xc420400000, 0xc420422000, 0xe5dc54, 0x11)
/go/src/github.com/moby/buildkit/cmd/buildkitd/main.go:520 +0x324
main.newController(0xc4200e71e0, 0xc420400000, 0x1c0, 0x0, 0x0)
/go/src/github.com/moby/buildkit/cmd/buildkitd/main.go:489 +0xdc
main.main.func3(0xc4200e71e0, 0x0, 0x0)
/go/src/github.com/moby/buildkit/cmd/buildkitd/main.go:203 …

Initialise workers' label maps before assigning.

---

executor/containerdexecutor/executor.go
executor/runcexecutor/executor.go
worker/containerd/containerd.go

- allow customized `CgroupPath` to be set for runcexecutor
- the purpose of this change is to support `--cgroup-parent` propagation from dockerd
- Moby side changes https://github.com/moby/moby/pull/37644
Note: To make sure the minimum changes in buidlkit behavior, if `buildkitd` is used as a standalone builder, it will still use `buildkit` namespace as top level in `/sys/fs/cgroup`. Only in moby `docker/buildkit` or `<cgroup-parent>/buildkit` will be used as cgroup path.
Signed-off-by: Anda Xu <anda.xu@docker.com>

allow customized cgroup-parent for runcexecutor

---

cache/remotecache/registry/registry.go
cmd/buildkitd/config/config.go
cmd/buildkitd/config/config_test.go
cmd/buildkitd/main.go
cmd/buildkitd/main_containerd_worker.go
cmd/buildkitd/main_oci_worker.go
exporter/containerimage/export.go
source/containerimage/pull.go
util/pull/resolver.go
util/push/push.go
util/resolver/resolver.go
worker/base/worker.go

#606
Config allows:
```
[registry."docker.io"]
mirrors=["localhost:5000"]
http=true
```
I'll follow up with a change that makes integration tests use a local mirror so we have test coverage.

resolver: add config support for mirrors/plainhttp

---

cmd/buildkitd/config/config.go
cmd/buildkitd/config/config_test.go
cmd/buildkitd/main_containerd_worker.go
worker/containerd/containerd.go

allow user to customize containerd namespace, not just `buildkit`. it
can help user to integration with existing data easily.

cmd,worker: support customize namespace for containerd worker

---

cache/manager.go
cache/refs.go
worker/base/worker.go
worker/cacheresult.go
worker/worker.go

The usage counters on `du -v` that are also used gc were not working properly. Most notably they increased when `du` itself was run. There were other issues as well with extra counting mutable releases, increasing the count on startup when cache was checked and not increasing counters for parent nodes.

cache: fix usage counters

---

Makefile
cache/contenthash/checksum_test.go
client/llb/llbbuild/llbbuild.go
client/llb/llbbuild/llbbuild_test.go
control/control.go
examples/buildkit0/buildkit.go
examples/buildkit1/buildkit.go
examples/buildkit2/buildkit.go
examples/buildkit3/buildkit.go
examples/nested-llb/main.go
frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
hack/dockerfiles/generated-files.Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/test.Dockerfile
hack/dockerfiles/vendor.Dockerfile
solver/scheduler.go

For consistency with Moby (moby/moby#37358)

update Go to 1.11

---

client/client.go
cmd/buildctl/debug/workers.go
cmd/buildctl/main.go
examples/build-using-dockerfile/main.go

Corrects the logic for quickly showing error when socket is down.

buildctl: replace withblock with dial error check

---

frontend/dockerfile/dockerfile2llb/convert_runmount.go

Allow `target=` in `RUN --mount` to be relative to the current working directory.
docker.io/tonistiigi/dockerfile:runmount20180917
docker.io/tonistiigi/dockerfile:secrets20180917

dockerfile: allow relative paths in mount targets

---

util/contentutil/copy.go
util/contentutil/fetcher.go
util/contentutil/refs.go
util/testutil/integration/containerd.go
util/testutil/integration/oci.go
util/testutil/integration/registry.go
util/testutil/integration/run.go

Use a local mirror for integration tests instead of pulling images all the time.
In the future, we may want to pass in the list of images per package as some of them are dockerfile specific. Also it may be easier (especially for the cleanup) if we would switch to `TestMain`.
For sharing between packages one can set `export BUILDKIT_REGISTRY_MIRROR_DIR=$(mktemp -d)`, but then they need to clean up this dir themselves as well. We could also set it in `hack/test` script later.

integration: use local registry mirrors

---

executor/runcexecutor/executor.go

Apparently killing `runc run` can still leak the container process, so change the cancel to manual signal send like in containerd executor.
This also fixes a case where cgroups could be leaked because the cleanup didn't run as part of `runc run` when it was killed.

runc: fix process leak on cancellation

---

client/build_test.go
client/client_test.go
cmd/buildctl/buildctl_test.go
frontend/dockerfile/dockerfile_test.go
util/testutil/integration/containerd.go
util/testutil/integration/oci.go
util/testutil/integration/run.go

based on #618
replaces #552
Allow running dockerfile tests in builtin, client and gateway modes.
By default tests builtin and client for all workers. Follow up should push an external gateway to the local registry and test that as well.
Filtering can be done with regular `--run` flag. eg `go test --run ///frontend=builtin -v ./frontend/dockerfile` to run all tests with only builtin or `go test --run /TestCmdShell/worker=oci/frontend=client -v ./frontend/dockerfile` for a specific test,worker,frontend combination.
Also accepts environment variables: `FRONTEND_BUILTIN_ONLY`, `FRONTEND_CLIENT_ONLY`.
To test external gateway:
```
FRONTEND_GATEWAY_ONLY=docker.io/tonistiigi/dockerfile:master go test -v ./frontend/dockerfile
```
@ijc

dockerfile: enable frontend selection in integration tests

---

exporter/containerimage/writer.go
worker/base/worker.go

Noticed a typo while trying to reproduce a bug (I think it's `COPY --chown` related).

Fix typo in error getting diff pairs

---

cache/contenthash/checksum.go
cache/contenthash/checksum_test.go
cache/contenthash/path.go
executor/oci/spec_unix.go
frontend/dockerfile/dockerfile_test.go

Fix handling of paths that contain symlinks in the parent components in the checksum calculation

contenthash: fix issues on symlinks on parent paths

---

snapshot/imagerefchecker/checker.go

`images.Dispatch` calls handlers concurrently so the map access needs to be protected.

imagerefchecker: fix concurrent map access

---

client/llb/exec.go
client/llb/llbtest/platform_test.go
client/llb/meta.go
client/llb/state.go
solver/llbsolver/ops/exec.go
solver/pb/caps.go

Setting the default `PATH` in the `llb.State` on the client side means it
depends on the `GOOS` of the buildkit client, rather than of the environment
where it will actually execute.
Instead defer this to execution time and insert the default PATH at that point
if one is not present. Doing this in executor/oci/spec_unix.go covers both the
runc and containerd executors at once.
No special handling is needed for a Windows executor since there is no fallback
path in that case.
Fixes #604

Push setting of default PATH down into the executor(s)

---

frontend/dockerfile/dockerfile2llb/convert.go

Example Dockerfile:
```
FROM busybox
ARG foo=abc
ENV bar=def
RUN echo $foo $bar $baz
```
Output without fix:
```
#5 [2/2] RUN echo  def
#5       digest: sha256:647df948c9689163efaf92b24b38779bc9f8b350482ecc3de3533f86a544c196
#5         name: "[2/2] RUN echo  def "
#5      started: 2018-09-29 19:01:11.376665368 +0000 UTC
#5 0.764 abc def
#5    completed: 2018-09-29 19:01:12.320141054 +0000 UTC
#5     duration: 943.475686ms
```
Output with fix:
```
#5 [2/2] RUN echo abc def
#5       digest: sha256:647df948c9689163efaf92b24b38779bc9f8b350482ecc3de3533f86a544c196
#5         name: "[2/2] RUN echo abc def "
#5      started: 2018-09-29 19:01:11.376665368 +0000 UTC
#5 0.764 abc def
#5    completed: 2018-09-29 19:01:12.320141054 +0000 UTC
#5     duration: 943.475686ms
```
Signed-off-by: Tibor Vass …

dockerfile: substitute build args in addition to env vars in RUN's CustomName

---

frontend/dockerfile/instructions/commands_nosecrets.go
hack/test

fixes #657
This is a temp fix. I'll do something better soon that also tests all variants.
I'm also ok with just removing `dfextall`, replacing it with a list of tags that we count as experimental and building with `-tags $(cat ./extalltags)`
@AkihiroSuda 

dockerfile: fix building dfextall

---

client/llb/exec.go
frontend/dockerfile/dockerfile2llb/convert_nossh.go
frontend/dockerfile/dockerfile2llb/convert_runmount.go
frontend/dockerfile/dockerfile2llb/convert_ssh.go
frontend/dockerfile/instructions/commands_nossh.go
frontend/dockerfile/instructions/commands_runmount.go
frontend/dockerfile/instructions/commands_ssh.go
hack/test

* Needs to be compiled with `dfrunmount dfssh`
* Implemented options:
* `type`(required): needs to be `ssh`
* `target`(optional): the socket path in the container
* `id`(optional): id
Test script:
#!/bin/bash
set -exu -o pipefail
REF=localhost:5000/dfssh:latest
ssh-add -l
sudo buildctl build --frontend=dockerfile.v0 --local context=. --local dockerfile=frontend/dockerfile/cmd/dockerfile-frontend \
--frontend-opt "build-arg:BUILDTAGS=dfrunmount dfssh" \
--exporter=image --exporter-opt name=$REF --exporter-opt push=true
mkdir -p /tmp/foo
cd /tmp/foo
cat << EOF > Dockerfile
FROM alpine
RUN apk add --no-cache openssh-client
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh ssh git@gitlab.com
EOF
sudo buildctl build --ssh default=$SSH_AUTH_SOCK …

dockerfile: add support for RUN --mount=type=ssh

---

client/client_test.go
executor/oci/hosts.go
executor/oci/spec_unix.go
solver/pb/caps.go

FIx problems from where containerd and moby default spec differ
- cgroups not mounted inside container
- hostname not set and not resolvable
- constant open file limit (fixes #643)

executor: fix spec incompatibilities

---

solver/jobs.go
util/tracing/multispan.go

Some opentracing providers were lost with the solver refactor. This adds back the previous support.
Sharing a trace for 2 parallel jobs waiting on the same vertex is still not supported. In this case, the first job wins and span would only be logged for it.

solver: fix opentracing providers

---

frontend/gateway/grpcclient/client.go

This will produce a "requested feature is not supported" style error message
with some more specific details about the build server configuration rather
than a more generic gRPC "unsupported" error message.

gateway: check for `ReadDir` and `StatFile` caps on client side

---

solver/index.go

Check for nil value in the cache key index map.

solver: fix possible nil dereference

---

frontend/dockerfile/dockerfile2llb/convert.go

Wrap parse error that doesn't contain the original reference value.

dockerfile: wrap reference parse error

---

cache/blobs/blobs.go
snapshot/blobmapping/snapshotter.go
util/pull/pull.go
worker/base/worker.go

Uncompressed label was set on a wrong object. There is still a possible race left where differ could match a blob before the label update has run. But that needs a containerd fix in the differ.

fix setting uncompressed label on content

---

.travis.yml
Makefile
cmd/buildkitd/main_oci_worker.go
hack/binaries
hack/cross
hack/dockerfiles/test.Dockerfile
hack/dockerfiles/test.buildkit.Dockerfile
hack/lint
hack/test
hack/update-generated-files
hack/util
hack/validate-generated-files
util/testutil/integration/oci.go
worker/runc/runc_test.go

hack: update test dockerfiles to buildkit

---

frontend/dockerfile/dockerfile2llb/convert.go

fixes #679
The destination path could be empty when a variable replacement replaced the path with an empty value.

dockerfile: fix empty dest directory panic

---

client/build_test.go
client/client_test.go
cmd/buildctl/build_test.go
cmd/buildctl/buildctl_test.go
cmd/buildctl/diskusage_test.go
cmd/buildctl/prune_test.go
frontend/dockerfile/dockerfile_test.go
frontend/frontend_test.go
util/testutil/integration/run.go

Rework integration tests so that it does not create too many daemon helper processes. When `t.Parallel()` is reached currently it would pause the test and put it into a queue for future execution, but because daemons are already started at this point it will create a lot of new daemon instances. Change is to automatically make all integration tests parallel and run the initialization code after test already has resumed. If some test in the future requires to be run without `t.Parallel()` it can do so by making its name end with `NoParallel` suffix.

testutil: avoid excessive daemons in integration tests

---

hack/dockerfiles/test.Dockerfile
hack/dockerfiles/test.buildkit.Dockerfile

Apply https://github.com/shadow-maint/shadow/pull/132 so that newuidmap/newgidmap
doesn't require CAP_SYS_ADMIN
Close https://github.com/moby/buildkit/issues/671

rootless: use Giuseppe's newuidmap/newgidmap

---

frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
frontend/dockerfile/dockerfile2llb/convert_norunmount.go
frontend/dockerfile/dockerfile2llb/convert_runmount.go
frontend/dockerfile/dockerfile2llb/convert_secrets.go
frontend/dockerfile/dockerfile2llb/convert_ssh.go
frontend/dockerfile/dockerfile_mount_test.go
frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/instructions/commands_nosecrets.go
frontend/dockerfile/instructions/commands_nossh.go
frontend/dockerfile/instructions/commands_runmount.go
frontend/dockerfile/instructions/commands_secrets.go
frontend/dockerfile/instructions/commands_ssh.go
frontend/dockerfile/release/experimental/tags
frontend/dockerfile/release/mounts/tags
frontend/dockerfile/release/secrets/tags
frontend/dockerfile/release/ssh/tags
hack/dockerfiles/test.Dockerfile
hack/dockerfiles/test.buildkit.Dockerfile
hack/test
util/contentutil/refs.go
util/testutil/integration/frombinary.go
util/testutil/integration/registry.go
util/testutil/integration/run.go

dockerfile: add testing external dockerfile features

---

hack/dockerfiles/test.buildkit.Dockerfile

@tonistiigi sorry for my mistake and plz close this one if you are already working on this fix

test.buildkit.Dockerfile: fix rootless-base-external

---

util/testutil/integration/containerd.go

Failed in CI with `address already in use`

testutil: use different containerd debug sock

---

.travis.yml
frontend/dockerfile/cmd/dockerfile-frontend/hack/release

Add release deployment for external dockerfile implementations:
Based on #528. Missing daily feature releases.
git tag `dockerfile/1.2.3` creates multi-platform images for `latest`, `1.2.3`, `1.2`, and `1`
git tag `dockerfile/1.2.3-experimental` creates multi-platform images for `experimental`, `1.2.3-experimental`, `1.2-experimental`, and `1-experimental`
Master builds for `master` and `master-experimental` tags are already live at https://hub.docker.com/r/tonistiigi/dockerfile/tags/
@tiborvass @andrewhsu @AkihiroSuda 

dockerfile: add release tag deployments

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/shell/lex.go
frontend/dockerfile/shell/lex_test.go

```
FROM alpine
RUN echo "Hey $name"
```
When building the above Dockerfile, the RUN command used to show: `echo Hey `
With this patch it now shows `echo "Hey $name"`.
However, because it is very useful for debugging to see the values variables can take,
they are expanded if set.
```
FROM alpine
ENV name=Jude
RUN echo "Hey $name"
```
Building the above Dockerfile makes the RUN command show: `echo "Hey Jude"`.

dockerfile: RUN's CustomName no longer consume quotes and only replaces environment variables if set

---

cmd/buildctl/build.go
examples/build-using-dockerfile/main.go

buildctl: support --no-cache for Dockerfile frontend

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go

The same image, just switches to `docker/dockerfile-copy` for the output.

dockerfile: update copy source repo

---

hack/dockerfiles/test.Dockerfile

This PR skips the stage for building buildkit on other architectures rather than `amd64` or `386`. Only for these architectures, the pair GOOS/GOARCH wih GOOS=darwin and GOOS=window is valid
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

Set GOARCH to amd64 for darwin/windows building stage

---

frontend/dockerfile/docs/experimental.md

Still could use a separate doc explaining `dockerfile-upstream` and https://github.com/moby/buildkit/issues/528

dockerfile: update image refs

---

solver/jobs.go

The op methods set session from vertex to the context before calling but it was missing for the one-off calls in vertex context. Most notably `ResolveImageConfig` is called this way, meaning that when called to the gateway frontend the session was lost and authentication didn't work for that call.
Reported in https://github.com/moby/buildkit/issues/720#issuecomment-438911728
Note that fix actually disables a workaround for grc.io authentication because a side effect of this bug caused manifest and blob pulls happen together.

llbsolver: keep session for context calls

---

cmd/buildctl/build.go

Allow `--import-cache` on frontends similarily to #708
Related to #723

buildctl: allow import-cache on frontend builds

---

hack/dockerfiles/test.Dockerfile
hack/dockerfiles/test.buildkit.Dockerfile

shadow-maint/shadow@52c081b (20181028) caused a regression that results in
`newuidmap: open of uid_map failed: Permission denied`.
The regression was fixed in shadow-maint/shadow@59c2dab (20181125).
Note that docker.io/moby/buildkit images are not affected by the
regression, because we forgot to update the rootless-base-external
image when we updated the shadow package before.
Related: genuinetools/img#191 genuinetools/img#196

update shadow to 20181125

---

executor/oci/spec_unix.go

Docker and containerd defaults differ here. Use Docker value for compatibility.
fixes #744

oci: avoid nonewprivileges in default spec

---

snapshot/snapshotter.go

The `err == nil` is probably a typo of `err1 != nil`.
Found using gocritic linter `badCond` checker.

snapshot: fix impossible condition

---

frontend/dockerfile/dockerfile2llb/convert_secrets.go
frontend/dockerfile/dockerfile2llb/convert_ssh.go
frontend/dockerfile/dockerfile_secrets_test.go
frontend/dockerfile/dockerfile_ssh_test.go
frontend/dockerfile/docs/experimental.md
frontend/dockerfile/instructions/commands_runmount.go
solver/llbsolver/ops/exec.go

 dockerfile: allow setting file mode/uid for ssh and secrets

---

frontend/dockerfile/parser/parser.go
frontend/dockerfile/parser/testfiles-negative/only_comments/Dockerfile

`docker build` panics on a dockerfile with no instructions (e.g., a dockerfile that contains only comments). This patch produces a parse error for such a dockerfile -- we detect this by determining whether the root AST node has an invalid "StartLine" position.
See https://github.com/moby/moby/pull/38487 for more discussion.

Have parser error on dockerfiles without instructions

---

hack/dockerfiles/generated-files.buildkit.Dockerfile
hack/update-generated-files

To avoid dropping the extra files from the exported `update` target image in the repo, the output from `go generate` is thrown in `generated-files/` and only that directory is untarred back into the repo.
Result of nuking a generated file and regenerating it:
```
$ rm api/types/worker.pb.go
$ git status
On branch clean-generated-files-export
Changes not staged for commit:
(use "git add/rm <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
deleted:    api/types/worker.pb.go
no changes added to commit (use "git add" and/or "git commit -a")
$ make generated-files
...
$ git status
On branch clean-generated-files-export
nothing to commit, working tree clean
```
Also still works fine when generating via buildkit directly:
```
$ …
```

`make generated-files` only copies over generated files from scratch container

---

cmd/buildkitd/config/config.go
cmd/buildkitd/main_oci_worker.go
docs/rootless.md
executor/containerdexecutor/executor.go
executor/oci/mounts.go
executor/oci/mounts_test.go
executor/oci/spec_unix.go
executor/runcexecutor/executor.go
worker/runc/runc.go
worker/runc/runc_test.go

`--oci-worker-no-process-sandbox` is useful for running in a Kubernetes container without `securityContext.procMount=Unmasked`.
Note that  this mode  allows build executor containers to `kill` (and potentially `ptrace`, depending on the (future) seccomp configuration for build containers) an arbitrary process in the BuildKit host namespace.
This mode should be enabled only when the BuildKit is running in a container as an unprivileged user.
Fix https://github.com/moby/buildkit/issues/765
Unlike kaniko/makisu, `buildkitd` container requires seccomp and apparmor to be disabled. (Kubernetes disables them by default)
```console
$ docker run -d --name buildkitd --security-opt seccomp=unconfined --security-opt apparmor=unconfined -p 1234:1234 moby/buildkit:rootless --addr tcp://0.0.0.0:1234 …
```

support --oci-worker-no-process-sandbox

---

exporter/containerimage/writer.go
frontend/dockerfile/dockerfile_test.go

fixes #776
Fill in the timestamps for metadata commands from the surrounding layers.

dockerfile: ensure metadata commands have created time

---

cache/remotecache/v1/cachestorage.go
cache/remotecache/v1/chains.go
solver/cache_test.go
solver/cachemanager.go
solver/cachestorage.go
solver/combinedcache.go
solver/edge.go
solver/llbsolver/bridge.go
solver/llbsolver/ops/source.go
solver/memorycachestorage.go
solver/types.go
worker/cacheresult.go

Improves #615 #777
- Avoid exporting local cache keys based on random seed because they would be regenerated on every run.
- Keep original creation date when copying record from remote store to local instead of using the current time.
Its possible there are still some edge cases that can be improved but these require extra debugging. This should cover most of it. Some cases where uploaded cache changes over time are by-design as if over time new metadata is determined that applies to same record, we want to upload that data as well.

Make exported build cache deterministic

---

cache/remotecache/import.go
cache/remotecache/inline/inline.go
cache/remotecache/v1/cachestorage.go
cache/remotecache/v1/chains.go
cache/remotecache/v1/doc.go
cache/remotecache/v1/parse.go
cache/remotecache/v1/utils.go
client/client_test.go
cmd/buildkitd/main.go
exporter/containerimage/exptypes/types.go
exporter/containerimage/writer.go
solver/cachemanager.go
solver/combinedcache.go
solver/llbsolver/solver.go
util/imageutil/config.go
worker/base/worker.go

fixes #752
based on  #615
Exporting with `--export-cache type=inline` importing is connected with the regular registry importer that falls back to inline if the registry ref is not a special cache manifest.
TODO:
- tests
- currently not deterministic on local sources
- @AkihiroSuda I'm thinking of changing the value to base64 of the protobuf and turn the existing cacheconfig types to proto (manifest list variant will remain json). maybe even store digests as bytes with a custom marshaler. thoughts?

allow exporting cache metadata in the image config

---

frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_mount_test.go
frontend/dockerfile/dockerfile_secrets_test.go
frontend/dockerfile/dockerfile_ssh_test.go
frontend/dockerfile/dockerfile_test.go

Allow customizing the names that dockerfile uses for locals with opts.

dockerfile: allow custom context names

---

source/containerimage/pull.go

fixes genuinetools/img#218
regression from #634
Puller expected error to be returned for schema1 config but that function was changed later, so the second cachekey for a schema1 image became constant. Issue appeared because on parallel builds, base stages for both images would be cached by the same key.

pull: fix second cachekey for schema1

---

source/http/httpsource.go
source/http/httpsource_test.go

When testing with github source URLs I found that the http source implementation didn't cooperate very well. From tracing the requests it seems to be a server fault but made some changes to handle misbehaving servers better.
Instead of sending multipe if-none-match headers (that should be supported) now join them into a single value.
Do an extra HEAD request for detecting the unchanged etag, in case server does not actually handle the in-none-match header.

http: add better support for misconfigured servers

---

solver/llbsolver/ops/exec.go
worker/base/worker.go

Use vertex platform instead of the current system one. This shouldn't break any cache unless qemu was used. Even when qemu was used the issue would not cause any cache collisions because the base images for run were scoped by platform, but better to stop using invalid data for cache key calculation.

exec: fix platform value in cache key

---

client/client_windows.go

strings.Replace call with n=0 argument makes no sense
as it will do nothing. Probably -1 is intended.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

client: fix strings.Replace call args

---

cmd/buildctl/build.go
cmd/buildctl/common/common.go
cmd/buildctl/common/trace.go
cmd/buildctl/debug/workers.go
cmd/buildctl/diskusage.go
cmd/buildctl/main.go
cmd/buildctl/prune.go
cmd/buildkitd/main.go

* buildkitd: `--tlscacert` had been ignored
* buildctl: TLS flags had been ignored for `buildctl debug workers`

Fix TLS issues

---

cmd/buildctl/build.go

buildctl: add `b` as an alias for `build`

---

solver/llbsolver/ops/exec.go
solver/llbsolver/ops/exec_test.go

fix #853
The issue only appeared when one of the checksummed paths contained another.

llbsolver: fix selectors dedupe

---

README.md
cache/remotecache/local/local.go
client/build_test.go
client/client_test.go
client/solve.go
cmd/buildctl/build.go
cmd/buildctl/build/allow.go
cmd/buildctl/build/build.go
cmd/buildctl/build/exportcache.go
cmd/buildctl/build/exportcache_test.go
cmd/buildctl/build/importcache.go
cmd/buildctl/build/importcache_test.go
cmd/buildctl/build/local.go
cmd/buildctl/build/opt.go
cmd/buildctl/build/output.go
cmd/buildctl/build/secret.go
cmd/buildctl/build/ssh.go
cmd/buildctl/build_test.go
examples/build-using-dockerfile/main.go
frontend/dockerfile/dockerfile_test.go

See https://github.com/moby/buildkit/pull/807#issuecomment-468146089
---
Fix #774

buildctl: new CLI ("Option C+")

---

hack/util

Make sure detection also works on `sh` and not only in bash.

hack: fix buildkit detection of sh

---

client/solve.go

Additional options causes panic and buildctl always adds `mode` option as well.
@AkihiroSuda for 0.4

buildctl: fix panic on exporting cache

---

solver/llbsolver/vertex.go

The `defaultPlatform` got on the build system include the variant for arm v6, v7 etc.
This is an important information for us to find the matched platform, but this information
is missed since the code doesn't include variant when assemble the platform information.
And since "V8" variant for arm64 is normalized to an empty string, so we need to take care
of this as well.

Don't miss the Variant for arm32 platform

---

cache/remotecache/inline/inline.go

Moby integration doesn't have a contentstore yet. Therefore the descriptors are not over compressed data. This change allows both compressed and uncompressed digests on inline export that should be safe because the collisions are not possible.

remotecache: allow uncompressed digest in inline export

---

hack/images

typo from https://github.com/moby/buildkit/pull/847/files#diff-ed0ae453c7dab73db35f74c6092f6e88R74
I manually retagged the `v0.4.0` images so no need to run it again.
@AkihiroSuda 

hack: fix tagging latest images on release

---

util/testutil/integration/containerd.go
util/testutil/integration/oci.go

closes #857
This looks like the most likely reason for #857 flakiness

integration: disable gc

---

solver/llbsolver/ops/file_test.go

saw this in ci https://travis-ci.org/moby/buildkit/builds/508667135#L5042
The backend causing this is only used in tests.
```
fatal error: concurrent map writes
goroutine 167 [running]:
runtime.throw(0xf97e4b, 0x15)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000069da8 sp=0xc000069d78 pc=0x721402
runtime.mapassign_faststr(0xe90e00, 0xc00034e5d0, 0xc000038b40, 0xd, 0x7)
/usr/local/go/src/runtime/map_faststr.go:211 +0x42a fp=0xc000069e10 sp=0xc000069da8 pc=0x706b1a
github.com/moby/buildkit/solver/llbsolver/ops.(*testFileRefBackend).Prepare(0xc00030ac30, 0x1096e00, 0xc00027f400, 0x107bf60, 0xc00034e690, 0x0, 0x2, 0xc000354080, 0x3, 0x3)
/src/solver/llbsolver/ops/file_test.go:666 +0xb8 fp=0xc000069ea0 sp=0xc000069e10 pc=0xddf6a8 …
```

ops: fix concurrent map writes in test

---

client/llb/fileop.go
solver/pb/caps.go

Allows a better error if fileop is used with a daemon that doesn't support it. Dockerfile frontend will never hit this cause it has a fallback builtin.

client: set cap if fileop used

---

frontend/dockerfile/dockerfile_test.go
snapshot/containerd/content.go
util/imageutil/config.go

There's a bug where if you build dockerfiles and get cache matches and then run prune, the blobs do not get deleted. This is is because on pull the layers blobs are set as root, metadata blobs are not set as roots, and layers point to metadata blobs and metadata blobs point to layers(this comes from containerd). This makes sure that when last layers are deleted the metadata gets deleted as well. Problem appears when dockerfile frontend looks up the config on the subsequent build when the cache already exists. It receives an `erralreadyexists` and makes the manifest/config a root. Now when layers roots deleted manifests still remain and because they keep references to layers, layers remain as well.
Fix is to determine the cases where root labels should not be added on `erralreadyexists` by …

content: fix setting wrong gc labels on config query

---

frontend/dockerfile/cmd/dockerfile-frontend/hack/release
frontend/dockerfile/dockerfile_test.go
hack/binaries
hack/cross
hack/images
hack/lint
hack/release-tar
hack/test
hack/update-generated-files
hack/update-vendor
hack/validate-generated-files
hack/validate-vendor

This patch replace "--frontend-opt" to "--opt" for the place
where it is appliable.

Stop using the deprecated flag "--frontend-opt" for build

---

cmd/buildkitd/main.go
util/binfmt_misc/amd64_check.go
util/binfmt_misc/amd64_check_amd64.go
util/binfmt_misc/arm64_check.go
util/binfmt_misc/arm64_check_arm64.go
util/binfmt_misc/arm_check.go
util/binfmt_misc/arm_check_arm.go
util/binfmt_misc/check.go
util/binfmt_misc/detect.go

Check the validity of the platforms

---

frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile_test.go

Implements https://github.com/moby/moby/issues/12886#issuecomment-306247989 allowing different Dockerfiles to define different subsets of the context files.
Frontend will first check for `<path/to/Dockerfile>.dockerignore` and if it is found it will be used instead of the root `.dockerignore`

dockerfile: add dockerignore override support

---

client/client.go
client/connhelper/connhelper.go
cmd/buildctl/dialstdio.go
cmd/buildctl/main.go
go.mod
go.sum
hack/dockerfiles/test.Dockerfile
hack/dockerfiles/test.buildkit.Dockerfile
vendor/github.com/docker/cli/AUTHORS
vendor/github.com/docker/cli/cli/config/config.go
vendor/github.com/docker/cli/cli/config/configfile/file.go
vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn.go
vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn_linux.go
vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn_nolinux.go
vendor/modules.txt

Usage:
```console
$ docker run -d --name buildkit-rootless --security-opt seccomp=unconfined --security-opt apparmor=unconfined moby/buildkit:local-rootless --oci-worker-no-process-sandbox
$ export BUILDKIT_HOST=docker://buildkit-rootless
$ buildctl build ...
```
Part of #769 
`kubepod+experimental://` helper will be also added later.

client: add docker:// connhelper 

---

README.md
client/exporters.go
client/solve.go
cmd/buildctl/build/output.go
exporter/local/export.go
exporter/tar/export.go
frontend/dockerfile/dockerfile_test.go
go.mod
go.sum
vendor/github.com/tonistiigi/fsutil/fs.go
vendor/github.com/tonistiigi/fsutil/tarwriter.go
vendor/modules.txt
worker/base/worker.go

Add a possibility to export to a tarball on the client side. Similar to local exporter but allows preserving the uid/gid values.
`buildctl build -o type=tar,dest=foo.tar ...`
`buildctl build -o type=tar ... > foo.tar`
~depends on https://github.com/tonistiigi/fsutil/pull/65~

exporter: add tarball exporter

---

hack/dockerfiles/test.Dockerfile

Run this command:
`docker build -f ./hack/dockerfiles/test.Dockerfile --target integration-tests`
will throw this error message:
`Executing busybox-1.29.3-r10.trigger OK: 184 MiB in 43 packages
Creating mailbox file: No such file or directory`
Not impact functionality but a little bit annoying.

test: avoid the error message when creating a user

---

go.mod
go.sum
util/progress/progressui/display.go
vendor/github.com/jaguilar/vt100/.travis.yml
vendor/github.com/jaguilar/vt100/LICENSE
vendor/github.com/jaguilar/vt100/README.md
vendor/github.com/jaguilar/vt100/command.go
vendor/github.com/jaguilar/vt100/go.mod
vendor/github.com/jaguilar/vt100/go.sum
vendor/github.com/jaguilar/vt100/scanner.go
vendor/github.com/jaguilar/vt100/vt100.go
vendor/modules.txt

https://asciinema.org/a/9JVmaYkpIhTsxNBQws5KMk0Zt
@tiborvass @AkihiroSuda @ijc

progressui: add logs to interactive output + fixes

---

client/llb/exec.go
frontend/dockerfile/dockerfile2llb/convert_runmount.go
frontend/dockerfile/dockerfile_mount_test.go
solver/llbsolver/ops/exec.go

Avoid opting out of content cache when readwrite mounts are used in Dockerfiles.
fix #903

dockerfile: allow content cache for rw mounts

---

client/connhelper/connhelper.go
client/connhelper/docker/docker.go
cmd/buildctl/main.go

Removes cli repo dependency from client so it can be vendored to moby.
@AkihiroSuda @tiborvass 

connhelper: refactor helpers to own packages

---

util/progress/progressui/display.go

buildx can merge progress from multiple builds. When a repeated vertex appears with an initial state, avoid resetting the vertex that would cause a duplicate vertex in the jobs array.

progressui: allow vertex reset

---

solver/llbsolver/solver.go

llbsolver: use deterministic digest for one-off progress

---

frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/instructions/commands.go

Signed-off-by: Hao Hu <hao.hu.fr@gmail.com>
for fixing the issue https://github.com/moby/moby/issues/35018

Expand chown value of COPY command

---

.mailmap
MAINTAINERS

No affiliation change (NTT).
The former email address will continue to be available for the time
being.
For daily communication, I still prefer to use my gmail.com address.

MAINTAINERS: update Akihiro Suda's email address

---

README.md

`vab` is a small build frontend that uses buildkit to build images or
output files localy from a Dockerfile.  Its pretty sweet.
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Replace boss callout with vab

---

util/binfmt_misc/detect.go

workaround for https://github.com/containerd/containerd/issues/3225 . Otherwise arm64 gets detected twice on native nodes.
@chendave 

binfmt_misc: detect arm64 properly

---

frontend/dockerfile/parser/parser.go
frontend/dockerfile/parser/testfiles-negative/only_comments/Dockerfile

backport of https://github.com/moby/buildkit/pull/771 for the docker-18.09 branch
See https://github.com/moby/moby/pull/38487 for more discussion.

[18.09 backport] Have parser error on dockerfiles without instructions

---

README.md
client/connhelper/kubepod/kubepod.go
client/connhelper/kubepod/kubepod_test.go
cmd/buildctl/main.go

Fix #769
Relates to tonistiigi/buildx#22
Usage:
$ kubectl run --generator=run-pod/v1 --image moby/buildkit:master-rootless bk -- --oci-worker-no-process-sandbox
$ export BUILDKIT_HOST=kube-pod://bk

new connhelper: kube-pod

---

hack/binaries
hack/dockerfiles/test.buildkit.Dockerfile

Applying the patch that @tonistiigi suggested in https://github.com/moby/buildkit/issues/928#issuecomment-483535274
This makes setting build-tags more convenient;
make binaries BUILDKITD_TAGS="$(cat frontend/dockerfile/release/experimental/tags)"

hack/binaries: add BUILDKITD_TAGS

---

exporter/containerimage/writer.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/image.go

Arm variant is missing in the current image config, causing issues when working with manifest lists. The types are planned to be updated https://github.com/dmcgowan/docker/issues/45 . With this PR we start adding variant info to images built with buildkit so we don't have to rebuild everything when types eventually land in spec.
@tiborvass @dmcgowan 

exporter: put arm variant in the image config

---

frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile_test.go

Allow specifying a subdir when building from a remote context. For example, if building from tarball that contains multiple projects.

dockerfile: allow subdirs for remote contexts

---

cache/contenthash/checksum_test.go
cache/manager_test.go
cmd/buildctl/build_test.go
exporter/containerimage/export.go
exporter/containerimage/writer.go
snapshot/containerd/snapshotter.go
snapshot/snapshotter.go
source/git/gitsource_test.go
source/http/httpsource_test.go
vendor/modules.txt
worker/base/worker.go
worker/containerd/containerd.go
worker/runc/runc.go

It is enhancement which allows to unpack image into containerd
snapshotter storage by `--output type=image,<.>=<.>,unpack=true`.
In order to support this feature, we needs to extend the Snapshotter
witwh `Name() string` function. Because we needs to set gc label for
snapshotter which need snapshotter name.
fix: #908

exporter: support unpack opt for image exporter

---

executor/runcexecutor/executor.go

This flag allows DOCKER_BUILDKIT to be running on minikube host: https://github.com/kubernetes/minikube/issues/4143
moby/builder/build-next needs to be updated to set NoPivot when
$DOCKER_RAMDISK is set.
This flag is deprecated from its birth and not exposed to the standalone buildkitd OCI worker.
See https://github.com/kubernetes/minikube/issues/3512

runexecutor: support NoPivot

---

executor/oci/spec_unix.go

Fix #987 
Let's release v0.5.1 with this

executor/oci: remove /proc masks for NoProcessSandBox mode

---

control/gateway/gateway.go
session/manager.go
solver/jobs.go
util/progress/progress.go

To avoid race conditions related to broadcasting prior to the intended thread having invoked Wait already you need to lock the wrapping mutex before broadcasting.
https://pastebin.com/tNitJ5L2 demonstrates why unlocked broadcasts are problematic.

Add missing locks around broadcasts

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/convert_test.go

Signed-off-by: Stepan Blyshchak <stepanblischak@gmail.com>
By creating a simple dockerfile like this:
```Dockerfile
FROM alpine:latest AS stage0
FROM alpine:latest AS stage1
COPY --from=stage1 bin /
```
and building using following command:
DOCKER_BUILDKIT=1 /usr/bin/docker build -t test .
dockerd crashes (part of log):
```
runtime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow
runtime stack:
runtime.throw(0x1d33169, 0xe)
/usr/local/go/src/runtime/panic.go:617 +0x74
runtime.newstack()
/usr/local/go/src/runtime/stack.go:1041 +0x6f4
runtime.morestack()
/usr/local/go/src/runtime/asm_amd64.s:429 +0x84
goroutine 677 [running]:
github.com/docker/docker/vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb.isReachable(0x0, 0xc0008b8900, …
```

[dockerfile2llb] fix daemon crash: check for circular dependency in convert

---

session/grpchijack/dial.go

From #936 
```
==================
WARNING: DATA RACE
Write at 0x00c0000d5a50 by goroutine 6:
google.golang.org/grpc.(*clientStream).CloseSend()
/src/vendor/google.golang.org/grpc/stream.go:757 +0x64
github.com/moby/buildkit/api/services/control.(*controlSessionClient).CloseSend()
<autogenerated>:1 +0x62
github.com/moby/buildkit/session/grpchijack.(*conn).Close.func1()
/src/session/grpchijack/dial.go:96 +0x5df
sync.(*Once).Do()
/usr/local/go/src/sync/once.go:44 +0xde
github.com/moby/buildkit/session/grpchijack.(*conn).Close()
/src/session/grpchijack/dial.go:90 +0x7d
github.com/moby/buildkit/session.(*Session).Close()
/src/session/session.go:111 +0x103
github.com/moby/buildkit/client.(*Client).solve.func2.1() …
```

session/grpchijack: fix race

---

client/solve.go

cleanup: no need to mkdir when importing cache

---

frontend/gateway/gateway.go
frontend/gateway/grpcclient/client.go

mitigates #991
From logs in #991 , something seems to go wrong when calling `ServeConn` on frontend stdio. Not sure what is the error and hopefully it can be captured from the daemon logs. This fixes error handling in this case by making the build error instead of leaving it hanging.
@msg555

gateway: handle grpc server errors

---

hack/dockerfiles/test.Dockerfile
hack/dockerfiles/test.buildkit.Dockerfile

Now the child process is killed when the parent dies (rootless-containers/rootlesskit#66)
ref: https://github.com/moby/moby/pull/39222

bump up rootlesskit to v0.4.1

---

README.md

Adding additional example to the local file export, as discussed in #963

add testresult example to readme

---

cmd/buildkitd/main_oci_worker.go

buildkitd: use asyncremove on overlay

---

frontend/dockerfile/dockerfile2llb/convert_runmount.go
frontend/dockerfile/dockerfile_mount_test.go
frontend/dockerfile/docs/experimental.md
frontend/dockerfile/instructions/commands_runmount.go

Allow setting `uid/gid/mode` on cache mounts. The real fix would be to implement this in LLB (with tmpfs mount), the current is a workaround directly in frontend to support all versions of the daemon.
There are some issues on doing chown/chmod on the root path that need to be investigated and probably need containerd changes. @dmcgowan  The current implementation uses subdir to overcome that. 

dockerfile: allow uid/gid in cache mounts

---

README.md
examples/buildctl-daemonless/buildctl-daemonless.sh
hack/dockerfiles/test.Dockerfile
hack/dockerfiles/test.buildkit.Dockerfile

The script spawns ephemeral daemon for "daemonless" UX.
Usage:
```
docker run -it --rm  \
--security-opt seccomp=unconfined --security-opt apparmor=unconfined \
-e BUILDKITD_FLAGS=--oci-worker-no-process-sandbox \
-v /path/to/dir:/tmp/work \
--entrypoint buildctl-daemonless.sh \
moby/buildkit:master-rootless \
build --frontend dockerfile.v0 --local context=/tmp/work --local dockerfile=/tmp/work
```
Replace #979 #1005 
Close #977

add buildctl-daemonless.sh

---

cache/manager.go
cache/refs.go

from a trace provided by @msg555 . An alternative would be to release in a goroutine.

cache: fix releasing parent on error

---

cache/contenthash/checksum.go
cache/manager.go
source/local/local.go

When the transfer of local sources is canceled or errors, checksum calculation is left in undefined state. After another build completes the transfer, the checksums may not correspond to the actual data on disk. With this quick patch, we always clean up the ref on error so next build starts from empty state. Later this could be optimized, for example do a full scan instead.
The reason this didn't show up very often is because of the lru cache for cache context. If cache was looked up from lru it still had the previous incomplete state that matched the disk state in 99% of cases(depending on where exactly the error happened).

local: handle canceled uploads

---

client/llb/imagemetaresolver/resolver.go
control/control.go
snapshot/blobmapping/snapshotter.go
snapshot/containerd/content.go
source/containerimage/pull.go
util/imageutil/config.go
util/leaseutil/manager.go
util/pull/pull.go
vendor/modules.txt
worker/base/worker.go
worker/containerd/containerd.go
worker/runc/runc.go

This fixes a race where gc cleans up a ref that holds the same blob that is pulled by another ref. Now blobs are kept by a lease during pull, avoiding containerd for cleaning them up. And inserting a blob mapping recreates the root label.
fixes #992 (traces in #991)
@dmcgowan @AkihiroSuda @msg555

pull: fix content blobs deletion on pull race

---

frontend/dockerfile/parser/parser.go
frontend/dockerfile/parser/parser_test.go

`StartLine` is already public. Tests pass locally.
https://github.com/moby/buildkit/issues/1028
cc @tonistiigi

frontend/dockerfile/parser: export endLine (make public)

---

client/client_test.go

use the image in the registry for verifying digests instead of a dummy (non-existent) image that can be cleaned up by gc.

fix flaky TestBasicInlineCacheImportExport

---

source/containerimage/pull.go
util/pull/resolver.go

pull: add cache for gcr bug

---

cmd/buildkitd/config/config.go
cmd/buildkitd/config/config_test.go
cmd/buildkitd/main.go
cmd/buildkitd/main_containerd_worker.go
cmd/buildkitd/main_oci_worker.go
executor/containerdexecutor/executor.go
executor/oci/resolvconf.go
executor/runcexecutor/executor.go
vendor/modules.txt
worker/containerd/containerd.go
worker/runc/runc.go
worker/runc/runc_test.go

This patch allows downstream code to pass a DNSConfig that is
then used by executor/oci.GetResolvConf.
This would allow the BuildKit-based builder in Docker to honor
the docker daemon's DNS configuration, thus fixing a feature gap
with the legacy builder.

executor: allow setting DNSConfig to be used by resolvconf

---

worker/base/worker.go

fix #991
Fixes issue when gc/prune runs in the middle of the cache import. The issue is that if the imported record already exists it is skipped on unpack but might be released before the reference is taken on the unpacked records. Fix is to take a ref temporarily on unpack if it exists.
I think there are still small cases that can go wrong on pull, eg. when there is an extra condition with multiple blobs matching same snapshot. I want to refactor the whole cache record management on top of https://github.com/containerd/containerd/pull/3304 that should fix all of these races. Hopefully this should be good enough fix all the practical cases where this issue can turn up.
@msg555

worker: fix gc race on fromremote

---

solver/llbsolver/ops/build.go
solver/llbsolver/ops/exec.go
solver/llbsolver/ops/file.go
solver/llbsolver/ops/source.go
solver/llbsolver/vertex.go

closes #1030 
closes #1031 
closes #1037

llbsolver: add more llb validation

---

frontend/dockerfile/builder/build.go
util/testutil/integration/registry.go

backslash(`\`) can be used freely, without the need of escaping.
regular expressions have their own escape sequences, raw strings can improve their readability.

Simplify regular expression by using raw string literal

---

executor/oci/spec.go
executor/oci/spec_unix.go
executor/oci/user.go
hack/dockerfiles/test.buildkit.Dockerfile

Because only buildctl but not buildkitd supports windows, the packages were not cross built in CI.
First commit adds changes to buildkit-flavored Dockerfile to build buildkitd for windows, only when doing hack/cross so that it is released in hack/release.
Second commit makes the test pass.

executor/oci: Fix windows compile

---

hack/dockerfiles/test.buildkit.Dockerfile

Looks like due to a bug in Dockerfile frontend, only the BUILDKITD_TAGS
build arg was taken into account, not the env var.
This fixes cgo call issues at runtime for os/user as seen in https://travis-ci.org/moby/buildkit/builds/556573787
I'll fix the bug in a followup, but quick repro:
```
FROM busybox
ARG foo
ENV foo="bar $foo"
RUN echo foo is $foo
```
```
$ buildctl build --opt build-arg:foo='' --frontend dockerfile.v0 --local dockerfile=. --progress plain --local context=. --no-cache
...
#5 [2/2] RUN echo foo is bar
#5 0.165 foo is
#5 DONE 0.2s
```

hack: fix runtime panic due to osuser build tag not set

---

frontend/dockerfile/dockerfile2llb/convert_runmount.go

dockerfile: do not add linked and cache paths to context sources

---

exporter/containerimage/export.go
exporter/oci/export.go
vendor/modules.txt
worker/base/worker.go

fixes https://github.com/docker/buildx/issues/101
If images are exported without the containerd imagestore, manifests and configs are temporary and released after export. If the same image is built twice in parallel one build may release the manifest+config before the export for another finishes.
@dmcgowan @shykes 

exporter: keep lease when exporting images

---

go.mod
go.sum
vendor/github.com/containerd/containerd/README.md
vendor/github.com/containerd/containerd/images/archive/importer.go
vendor/github.com/containerd/containerd/metadata/content.go
vendor/github.com/containerd/containerd/mount/mount_linux.go
vendor/github.com/containerd/containerd/remotes/docker/handler.go
vendor/github.com/containerd/containerd/remotes/docker/resolver.go
vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
vendor/github.com/containerd/containerd/vendor.conf
vendor/modules.txt

To update containerd with go mod, it is NOT possible to simply do:
```
go get github.com/containerd/containerd@7c1e88399ec0
```
because it would result in:
```
v1.2.1-0.20190507210959-7c1e88399ec0
```
which is an incorrect version prefix as we want the commit 7c1e88399
from master to have higher priority than a tagged version such as v1.2.*
We want to use a `v1.3.0-0.` prefix even though v1.3.* tags do not exist,
so that when they do, those do have higher priority compared to 7c1e88399.
In other words, containerd's master branch corresponds to a v1.3 dev branch.
The following was thus used to update containerd:
```
go get -d github.com/containerd/containerd@v1.3.0-0.20190507210959-7c1e88399ec0
go get -d github.com/opencontainers/runc@v1.0.0-rc8
make vendor
```
Signed-off-by: Tibor Vass …

vendor: update containerd to 7c1e88399

---

client/client_test.go
executor/oci/spec_unix.go

There were two bugs: Mount was matched by Type which is actually
`cgroup`, not `sysfs`. And the second problem was that copy of the value
was modified, not value in the slice.
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

Fix updating /sys/fs/cgroup mount to 'rw'

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/convert_norunsecurity.go
frontend/dockerfile/dockerfile2llb/convert_runsecurity.go
frontend/dockerfile/dockerfile_runsecurity_test.go
frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/docs/experimental.md
frontend/dockerfile/instructions/commands_runsecurity.go
frontend/dockerfile/release/experimental/tags

This follows syntax suggested in #950.
Example:
RUN --ents=security.insecure cat /proc/self/status | grep CapEff
#84 0.093 CapEff:	0000003fffffffff

Implement frontend support for RUN --security=insecure

---

frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
hack/dockerfiles/generated-files.Dockerfile
hack/dockerfiles/generated-files.buildkit.Dockerfile
hack/dockerfiles/test.buildkit.Dockerfile

`golang` image switched to `buster` and `btrfs` package changed and broke the build. In addition to patch fix the golang images to a distro so this doesn't happen again.

hack: unbreak upgrade to buster

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/convert_test.go
frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/shell/lex.go
frontend/dockerfile/shell/lex_test.go

This bug was discovered when making #1071

dockerfile: fix handling of empty build-arg also used as env

---

frontend/dockerfile/dockerfile2llb/convert_runmount.go
frontend/dockerfile/dockerfile_mount_test.go

Default cache mount ID to target path if not set.

dockerfile: fix default cache IDs

---

executor/containerdexecutor/executor.go
executor/runcexecutor/executor.go
frontend/dockerfile/dockerfile_test.go

fixes https://github.com/moby/buildkit/issues/973#issuecomment-514443912
if workdir exists with specific mode/owner no not try to recreate it with default settings.

executor: ignore workdir if already exists

---

cache/manager.go
cache/metadata/metadata.go
client/client_test.go
solver/llbsolver/bridge.go
solver/llbsolver/ops/exec.go
solver/llbsolver/solver.go
solver/llbsolver/vertex.go
worker/base/worker.go
worker/worker.go

fixes https://github.com/docker/buildx/issues/109
No-cache doesn't really work in combination with cache mounts as it is solver level and caches instructions. But the behavior is non-obvious from the user perspective. So if no-cache is used in a run operation that uses cache mounts, all cache volumes with the matching id are released before the build even starts now.

solver: support no-cache for exec cache mounts

---

hack/update-vendor

hack: fix update-vendor script when using PREFER_BUILDCTL=1

---

cache/refs.go

fixes #1091
Add a special handling for readonly overlay mounts from active snapshots that removes the upper directory.
@dmcgowan @denzp
@dmcgowan While I think this is fine to do in cases buildkit already knows mount is readonly I think there should be some lower-level protection because the APIs all support getting multiple mounts. I would expect ref counting for overlay mount lifecycle in containerd so it doesn't crash on runtime or if this is not possible I think I need to add a refcounting snapshot wrapper in buildkit.

cache: force overlay readonly by removing upperdir

---

client/client_test.go
client/solve.go
cmd/buildctl/build/output.go
examples/build-using-dockerfile/main.go
exporter/oci/export.go
exporter/tar/export.go
frontend/dockerfile/dockerfile_test.go
session/filesync/diffcopy.go
session/filesync/filesync.go
vendor/modules.txt

Allow `oci` exporter visibility to exporter metadata. For example, to see if the data already exists and report it back to the daemon. Later this should be extended by adding the contentstore api to the control api, and the exporter can use that to pull individual blobs during the export phase.

exporter: allow oci exporters visibility to response metadata

---

cmd/buildctl/debug/dumpllb.go
examples/buildkit3/buildkit.go

Hey,
First of all - thank you for putting so much work on `buildkit`!
<br />
Onto the PR - in the `buildctl` code, I added a case for `Op_File` in order to allow folks to visualize the LLB's graph look when leveraging the `--dot`-based output.
As I had to inspect the json-based output quite a few times, I end up implementing that in the `--dot` one, which made my life way easier. Do you think this is a valid addition? I wasn't sure if there was a reason for such case not being treated there.
To make that demonstrable, I end up modifying the `buildkit3` to leverage file operations. 
Also, I'm not very sure about the format (`action{prop1=<val1>,...},...`) - wdyt?
<br/>
Thank you!

debug: add `fileop` to `--dot`

---

control/control.go
solver/result.go
util/pull/resolver.go

follow-up to moby/buildkit#1082
we tried to detect these places with lint on moby/buildkit#1082 but seems it doesn't work reliably
related to: https://github.com/docker/buildx/issues/129

correct int64 alignment

---

cmd/buildkitd/main_containerd_worker.go
cmd/buildkitd/main_oci_worker.go
util/network/cniprovider/cni.go
util/network/cniprovider/cni_unsafe.go
util/network/cniprovider/createns_linux.go
util/network/cniprovider/createns_nolinux.go
util/network/netproviders/network.go
util/network/network.go
worker/containerd/containerd.go
worker/runc/runc.go
worker/runc/runc_test.go

Separate CNI support to own package so it doesn't need to be imported in moby.

network: refactor cni support to multiple packages

---

cache/remotecache/v1/utils.go

Updated record comparator to do a full lexicographical comparison on cache records
Signed-off-by: Mark Gordon <msg555@gmail.com>

remotecache: other fix to record sorting

---

frontend/dockerfile/dockerfile2llb/convert_runmount.go
frontend/dockerfile/dockerfile_mount_test.go
solver/llbsolver/ops/exec.go
solver/pb/caps.go

#922 had a bug that caused readwrite mounts with no outputs to be mounted as readonly
Fix this and add a cap so that new frontends would rather use inefficient caching than mount in a wrong way when talking with old servers.

ops: fix readwrite mounts it no output

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go

The legacy builder handles relative source paths as they were absolute and so does the copy image. Fileop based implementation took the workdir of source stage into an account. While this behavior can be quite useful it is better to revert to the behavior that is compatible with old builders.
Found when looking at https://github.com/moby/buildkit/issues/1123

dockerfile: ignore relative source paths for compatibility

---

cache/remotecache/import.go
cache/remotecache/inline/inline.go
frontend/dockerfile/dockerfile_test.go
solver/combinedcache.go
solver/jobs.go

Fix issues where inline cache was exported to/imported from manifest lists. Previously the importer could only match one submanifest and exporter didn't export in deterministic order.

remotecache: fix inline cache in manifest lists

---

frontend/dockerfile/builder/build.go
source/git/gitsource.go
source/git/gitsource_test.go

Fix issues with keeping `.git` directory around on git checkouts. Also add a build arg for triggering git context to keep the git directory. Normally this should be the default but because the option was broken before I'd rather not break anyone.

git: updates for keep git dir

---

cache/blobs/blobs.go
cache/refs.go
executor/containerdexecutor/executor.go
executor/oci/spec_unix.go
executor/runcexecutor/executor.go
snapshot/localmounter.go
snapshot/localmounter_unix.go
snapshot/localmounter_windows.go
snapshot/snapshotter.go
solver/llbsolver/file/refmanager.go
solver/llbsolver/ops/exec.go
util/testutil/integration/oci.go

There is an issue in the fileop implementation that can call release twice on a mount. Refactor the interface to avoid such issues in the future.
BuildKit own mounts are stateless and not affected but a different mountable implementation could get confused.
related to https://github.com/moby/buildkit/issues/1134

 fix possible double release on mountable

---

executor/runcexecutor/executor.go

runcexecutor: avoid setting oomscoreadj from main process

---

client/client_test.go
frontend/dockerfile/dockerfile_test.go
go.mod
go.sum
vendor/github.com/containerd/continuity/fs/copy.go
vendor/github.com/containerd/continuity/fs/fstest/file.go
vendor/github.com/containerd/continuity/fs/fstest/testsuite.go
vendor/github.com/tonistiigi/fsutil/copy/copy.go
vendor/github.com/tonistiigi/fsutil/copy/copy_darwin.go
vendor/github.com/tonistiigi/fsutil/copy/copy_linux.go
vendor/github.com/tonistiigi/fsutil/copy/copy_unix.go
vendor/github.com/tonistiigi/fsutil/copy/copy_windows.go
vendor/github.com/tonistiigi/fsutil/stat.go
vendor/modules.txt

Adds tests and vendors https://github.com/tonistiigi/fsutil/pull/67
Also vendors https://github.com/containerd/continuity/pull/143

Fix socket handling

---

client/client_test.go
solver/llbsolver/bridge.go

llbsolver: fix error on multiple cache importers

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/convert_norunnetwork.go
frontend/dockerfile/dockerfile2llb/convert_norunsecurity.go
frontend/dockerfile/dockerfile2llb/convert_runnetwork.go
frontend/dockerfile/dockerfile2llb/convert_runsecurity.go
frontend/dockerfile/dockerfile_runnetwork_test.go
frontend/dockerfile/dockerfile_runsecurity_test.go
frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/docs/experimental.md
frontend/dockerfile/instructions/commands_runnetwork.go
frontend/dockerfile/instructions/commands_runsecurity.go
frontend/dockerfile/release/experimental/tags

Following a similar pattern to #1081, this adds support in the experimental Dockerfile for `RUN` instructions with customised networking modes:
```
RUN --network=none ip link list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```
Allowed arguments for `--network` are:
* `none` - No networking is available during the invocation (useful for preventing external effects)
* `host` - Expose the host's network stack to the invocation (requires the `network.host` entitlement)
* `default` - The invocation is run in the standard internal network (equivalent to not specifying the network)

Implement support for RUN --network=none|default|host

---

source/http/httpsource.go

Fixes #905 and #784.
If a single ETag is requested in `If-None-Match`, some servers do not include that (unambiguous) ETag header in the response.
**This has *not* been tested.** I'm developing on a Mac and not able to devote much more time to this bug, but figured it was worth at least a beginner shot at fixing it.
Detailed description from https://github.com/moby/buildkit/issues/905#issuecomment-528058142 partially reproduced below:
<details>
<summary><b>Reproduction Steps</b></summary>
<p>
```dockerfile
FROM scratch
ADD https://storage.googleapis.com/gpt-2/models/774M/checkpoint
```
The first run (or a run after the cache is cleared) succeeds:
```sh
DOCKER_BUILDKIT=1 docker build .
```
> ```
> [+] Building 0.3s (5/5) FINISHED
>  => [internal] load .dockerignore …
```

http: Handle missing but unambiguous ETags in response

---

solver/edge.go
solver/internal/pipe/pipe.go

fix cases where some events were dropped resulting inefficient parallelization.
issue shows with following dockerfile:
```
FROM alpine as one
RUN mkdir -p /opt/one/
RUN sleep 5
FROM alpine as two
RUN mkdir -p /opt/two/
RUN sleep 5
FROM alpine as three
RUN mkdir -p /opt/three/
RUN sleep 5
FROM alpine as four
RUN mkdir -p /opt/four/
RUN sleep 5
FROM alpine:latest
COPY --from=one /opt/one /opt/one
COPY --from=two /opt/two /opt/two
COPY --from=three /opt/three /opt/three
COPY --from=four /opt/four /opt/four
```
It is possible that cases like this became more likely after `FileOp` introduction as it reduces the number of cache keys for `COPY` command in dockerfile.

solver: fix pipe signaling on incoming updates

---

executor/runcexecutor/executor.go
go.mod
go.sum
vendor/github.com/containerd/go-runc/.travis.yml
vendor/github.com/containerd/go-runc/command_linux.go
vendor/modules.txt

brings in fix for https://github.com/containerd/go-runc/pull/54
and updates the caller for a new expected result of https://github.com/containerd/go-runc/pull/52 (was vendored in #1107)

vendor: update go-runc to e029b79d

---

executor/oci/resolvconf.go
executor/oci/resolvconf_test.go

executor/oci: fix panic when resolv.conf does not exist 

---

cmd/buildkitd/main.go

buildkitd: disable TLS for UNIX sockets

---

frontend/dockerfile/dockerfile2llb/convert.go

This adds a one space padding, so that the output of stages that have 10 steps or more align better;
Before:
=> [dev 1/24] RUN groupadd -r docker                                        0.7s
=> [dev 2/24] RUN useradd --create-home --gid docker unprivilegeduser       1.0s
=> [dev 3/24] RUN ln -sfv /go/src/github.com/docker/docker/.bashrc ~/.bas   0.9s
=> [dev 4/24] RUN echo "source /usr/share/bash-completion/bash_completion"  1.0s
=> [dev 5/24] RUN ln -s /usr/local/completion/bash/docker /etc/bash_c       0.8s
=> [dev 6/24] RUN ldconfig                                                  1.6s
=> [dev 7/24] RUN --mount=type=cache,sharing=locked,id=moby-dev-aptlib,    44.8s
=> [dev 8/24] RUN pip3 install yamllint==1.16.0                             4.0s
=> [dev 9/24] COPY --from=swagger …

frontend: add padding to align steps in stage

---

cache/manager.go
cache/migrate_v2.go

follow-up to #1176
Allow tracking descriptors without blobs data so it can be used in moby where current implementation doesn't have a content store yet.

cache: follow-up updates to storage leases

---

README.md
docs/rootless.md

BuildKit with crun works fine on cgroup2 system.
Tested both Rootful and Rootless on Fedora 31, with crun v0.10.2.

docs for Fedora 31 users

---

client/client_test.go
solver/llbsolver/file/backend.go
solver/pb/caps.go

Fixes #1232 .
Where should tests go? In `client/llb/fileop_test.go`?

Implement file action remove for wildcards

---

hack/update-generated-files

There's a typo in `./hack/update-generated-files` which causes the error:
```sh
$ make generated-files
./hack/update-generated-files
+ :
+ progressFlag=
+ '[' '' == true ']'
++ awk '$1 == "github.com/gogo/protobuf" { print $2 }' go.mod
+ gogo_version=v1.2.0
+ case $buildmode in
+ echo 'Unsupported build mode: docker-buildkit'
Unsupported build mode: docker-buildkit
+ exit 1
Makefile:35: recipe for target 'generated-files' failed
make: *** [generated-files] Error 1
```

Fix update generated files via docker buildkit

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go
session/sshforward/ssh.go
solver/llbsolver/ops/exec.go

[19.03] bugfixes cherry-pick

---

examples/kubernetes/README.md
examples/kubernetes/statefulset.privileged.yaml
examples/kubernetes/statefulset.rootless.yaml

Parallel mode releaxes the pod creation order constraint.
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#parallel-pod-management

examples/kubernetes: use Parallel mode for StatefulSet

---

README.md
exporter/containerimage/export.go

New exporter attrs that allow naming dangling images (without name, only prefix) and canonical references that also contain the image digest.

exporter: add canonical and dangling image naming

---

cache/refs.go

fixes https://github.com/moby/buildkit/issues/1250
@bpaquet @tiborvass

cache: fix possible concurrent maps write on parent release

---

cache/refs.go

19.03 version of https://github.com/moby/buildkit/pull/1256
@tiborvass @andrewhsu 

[19.03] cache: fix possible concurrent maps write on parent release

---

examples/kubernetes/deployment+service.privileged.yaml
examples/kubernetes/deployment+service.rootless.yaml
examples/kubernetes/pod.privileged.yaml
examples/kubernetes/pod.rootless.yaml
examples/kubernetes/statefulset.privileged.yaml
examples/kubernetes/statefulset.rootless.yaml

Our team is on the way to migrate to buildkit. In order for us to monitor our CICD stack we needed to have a readiness and liveness probe for the deployment. 
Thanks to the help of @AkihiroSuda 
#1261

Add readiness and liveness probe to the kubernetes examples

---

session/sshforward/sshprovider/agentprovider.go

Closes https://github.com/moby/buildkit/issues/1265
@tonistiigi

Inherit extended agent so we get modern sign hashes

---

frontend/dockerfile/instructions/parse.go

Before this change, the error message would show the invalid name in lowercase:
docker build -<<'EOF'
FROM busybox AS foo:$BAR
EOF
[+] Building 0.2s (2/2) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                                                             0.0s
=> => transferring dockerfile: 67B …

frontend/dockerfile: show original stagename in error-message

---

README.md
cache/blobs/blobs.go
cache/blobs/compression.go
client/client_test.go
exporter/containerimage/export.go
exporter/containerimage/writer.go
exporter/oci/export.go
worker/base/worker.go

Allow user to choose the compression type for layer data. Gzip is
default compression for layer exporter, which consume more Cpu resources
and take long time to export. With compression option, user can use
nocompressed option to export to save time. And future, zstd is one new
option for end-user.

exporter: support compression for layer blob data

---

cmd/buildkitd/config/config.go
cmd/buildkitd/main_oci_worker.go
docs/buildkitd.toml.md
worker/runc/runc.go
worker/runc/runc_test.go

To support switching the OCI worker binary via buildkitd and without modifying the Dockerfile, an optional command-line flag was added to main_oci_worker.go that allowed for input the name of an OCI worker binary (ex. crun). This OCI worker binary would then replace the current buildkit-runc with a symbolic link to that binary. The above was done using the os/exec package's Command func.
fix #1230 
Signed-off-by: Jeffrey Huang <jeffreyhuang23@gmail.com>

Fix issue #1230 (add --oci-worker-binary)

---

client/solve.go

Allow build to run even if import cache of type=local is not found
Added an additional check in solve.go to catch errors thrown when
local import caches are not found. If none are found, continues as
if no import cache was specified.
fix #1240
Signed-off-by: Nikhil Pandeti <nikhil.pandeti@utexas.edu>

Fix issue #1240 (ignore non-existent local cache)

---

cmd/buildctl/common/common.go
cmd/buildctl/main.go

Added a command-line flag (tlsdir) to buildctl that allowed for specifying a directory that contains a ca.pem, cert.pem, and key.pem. This command-line flag acts an alias of --tlscacert, --tlscert, and --tlskey. --tlsdir cannot be used at the same time as those flags, and will cause an error if done. The pkg/errors package has been added to cmd/buildctl/common/common.go to allow for the creation of this error message.
fix #1200
Signed-off-by: Jeffrey Huang <jeffreyhuang23@gmail.com>

Fixed issue #1200 (buildctl: add --tlsdir)

---

frontend/gateway/gateway.go
frontend/gateway/grpcclient/client.go
frontend/gateway/pb/gateway.pb.go
frontend/gateway/pb/gateway.proto
frontend/gateway/pb/ref.go

Partially fixes #871 
It moves non-array `ref` and `refs` map to array types while maintaining backwards compatibility. We need to detect clients without array ref capability (server need to detect client cap so `apicap` can't be used here), so `AllowResultArrayRef` was added.
Previous proto fields `Result_Ref` and `Result_RefMap` was moved to `Result_RefDeprecated` and `Result_RefMapDeprecated` respectively.
Some open questions:
1. Should we change the following struct/interfaces in this PR too?
https://github.com/moby/buildkit/blob/5c9365b6f4c2232a2d743a5792a2e708d7790fc4/frontend/result.go#L5-L9
https://github.com/moby/buildkit/blob/5c9365b6f4c2232a2d743a5792a2e708d7790fc4/frontend/gateway/client/result.go#L12-L17
2. In order to implement #751 after this PR, we need to add edge digests …

Change result type to array of refs

---

util/imageutil/config.go

When built image with Dockerfile and  the BaseImage was built and push by an older versions Docker which wrongly used application/octet-stream as the media type.
The build job will failed: 
`error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: encountered unknown type application/octet-stream; children may not be fetched`
[docker distribution ##2243](https://github.com/docker/distribution/issues/2243)
[docker distribution ##1621](https://github.com/docker/distribution/issues/1621)
Signed-off-by: genglu <genglu.gl@antfin.com>

fix baseimage with unknown application/octet-stream as config media type

---

frontend/gateway/grpcclient/client.go
frontend/gateway/pb/caps.go
solver/pb/caps.go

Fixes #1327
Fixes #1321 
Regression introduced by: https://github.com/moby/buildkit/pull/1269
When using frontend built from regression commit and beyond, the frontend does not check for a server capability for ref arrays and sends ref arrays to the return API.
This PR, adds the apicap `CapProtoRefArray` and sends the appropriate ref/refarray to the return API depending on the apicap.
---
Reproduced with following steps:
Build the frontend from `master` of this repository:
```sh
$ DOCKER_BUILDKIT="1" docker build -t docker/dockerfile-upstream:regress -f ./frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile .
```
Then building an image using `Docker 19.03` (with an older buildkitd):
```Dockerfile
FROM alpine
```
Inspecting the image:
```sh
$ docker inspect -f "{{.RootFS.Layers}}" …
```

Detect support for protobuf array ref on server on frontend return call

---

solver/combinedcache.go

fix #1319
Avoid panic on race from the combined cache. There is still an issue as the error should be handled gracefully but at least avoid panic atm.

solver: avoid panic on combined cache load

---

go.mod
go.sum
vendor/github.com/tonistiigi/fsutil/diff.go
vendor/github.com/tonistiigi/fsutil/diff_containerd.go
vendor/github.com/tonistiigi/fsutil/diskwriter.go
vendor/github.com/tonistiigi/fsutil/go.mod
vendor/github.com/tonistiigi/fsutil/go.sum
vendor/github.com/tonistiigi/fsutil/receive.go
vendor/github.com/tonistiigi/fsutil/types/stat.go
vendor/modules.txt

backport of https://github.com/moby/buildkit/pull/1317 for the v0.6.x release
full diff: https://github.com/tonistiigi/fsutil/compare/3d2716dd0a4d...0f039a052ca1
- tonistiigi/fsutil#68 fix gocrypto commit
- tonistiigi/fsutil#69 receive: use filter on receive diff
- prevents incremental transfers with userns because the metadata
on disk is always different than the one being transferred.

[v0.6 backport] vendor: update fsutil 0f039a052ca1

---

cmd/buildkitd/main.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go
session/sshforward/sshprovider/agentprovider.go
solver/combinedcache.go
util/flightcontrol/flightcontrol.go

https://github.com/moby/buildkit/pull/1202 buildkitd: disable TLS for UNIX sockets
https://github.com/moby/buildkit/pull/1270 Inherit extended agent so we get modern sign hashes
https://github.com/moby/buildkit/pull/1316 ensure context is cancelled to prevent goroutine leaks with containerd worker
https://github.com/moby/buildkit/pull/1328 solver: avoid panic on combined cache load
https://github.com/moby/buildkit/pull/1324 dockerfile: clear onbuild rules after triggering
@AkihiroSuda @thaJeztah

[v0.6] cherry-picks for v0.6.4

---

Dockerfile

Kubernetes runAsNonRoot requires `USER` in Dockerfile to be numeric:
https://github.com/kubernetes/kubernetes/blob/v1.18.0-alpha.2/pkg/kubelet/kuberuntime/security_context.go#L98

Dockerfile: support Kubernetes runAsNonRoot

---

hack/images

When `make images` with buildmode docker-buildkit,
DOCKER_BUILDKIT=1 should be added to environments.
Signed-off-by: Lu Jingxiao <lujingxiao@huawei.com>
**What I met**
```bash
hack/images local moby/buildkit
+ docker build --platform=linux/amd64 -t moby/buildkit:local .
"--platform" is only supported on a Docker daemon with experimental features enabled
make: *** [images] Error 1
commit 8a267827cdfd672e4890f23f51c4153c6f0802b3
```
**With this patch**
```bash
hack/images local moby/buildkit
+ docker build --platform=linux/amd64 -t moby/buildkit:local .
[+] Building 19.6s (17/29)
=> [internal] load build definition from Dockerfile                                                                                                                                                         0.0s
=> => …
```

Makefile: specify DOCKER_BUILDKIT when make images

---

cmd/buildkitd/main.go
executor/containerdexecutor/executor.go
util/appdefaults/appdefaults_windows.go
worker/containerd/containerd.go

A bunch of small changes that fix blocking issue for supporting Buildkit on Windows against containerd.
This doesn't result in working Windows support, but the remaining areas of support are harder-to-solve, relating (so far) to either container spec generation, various aspects of network namespace handling, or various LLB commands that refuse to work if they cannot do user id mapping.
This is to advance #616, but does not complete it.

Low-hanging Windows fruit

---

hack/util

> All the other scripts in hack/ use bash, and this makes the lone `==` used in _hack/util_ work, rather than logging a complaint:
> > ./hack/validate-vendor: 31: [: pull_request: unexpected operator
Edit: Rewritten, above description no longer describes the change.

Remove bashism from shared shell script

---

frontend/gateway/forwarder/forward.go
frontend/gateway/gateway.go
frontend/result.go
solver/llbsolver/bridge.go
solver/llbsolver/ops/build.go
solver/llbsolver/solver.go
solver/types.go
worker/result.go

With https://github.com/moby/buildkit/pull/1286 previous solve results can be used as inputs for the new requests. One of the issues with the current implementation is that the main build is blocked and cannot start while the nested `Solve` request happens. This could be inefficient for parallelization and caching. Eg. buildkit supports caching even if you don't have the layer data for your whole cache chain(this is how inline remote cache works even with multi-stage builds), but the nested solve does not know that it may be just used for getting a future cache hit and needs to return local layers.
This PR changes the behavior of `Solve()` method for frontends. They now return results without actually starting the build. Results are evaluated only if the result ends up as the return value …

solver: evaluate solve results lazily

---

Dockerfile

follow-up: https://github.com/moby/buildkit/pull/1343#issue-366707884
fixes: https://github.com/docker/buildx/issues/145
```
[+] Building 23.2s (23/23) FINISHED
=> [internal] load .dockerignore                                                                                                                                                                                       0.0s
=> => transferring context: 34B                                                                                                                                                                                        0.0s
=> [internal] load build definition from Dockerfile …
```

dockerfile: update static base images

---

executor/oci/spec_unix.go
frontend/dockerfile/dockerfile_runsecurity_test.go
frontend/dockerfile/dockerfile_test.go
solver/pb/caps.go
util/entitlements/security/security_linux.go

fixes https://github.com/docker/buildx/issues/220
Unlike `docker run --privileged` we don't mount all the devices from host because that would give inconsistent environments for different hosts that we would like to avoid (and later solve with constraints). But we can mount a whitelist of devices that are always created by regular distros and commonly used. Permissions are granted to users to read/write all the devices, for the missing ones you just need to `mknod` the device yourself.
Devices currently created with `--security=insecure`:
- kmsg
- fuse
- cuse
- loop-control + loopN
- net/tun
- kvm

mount whitelist of devices on insecure security mode

---

frontend/dockerfile/shell/envVarTest
frontend/dockerfile/shell/lex.go
frontend/dockerfile/shell/lex_test.go

The aim is to add `${name?word}` and `${name:?word}` [[src](https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_02)] to allow enforcing environment variables/build args to be set, e.g.
```Dockerfile
ARG REQUIRED
ENV NOT_EMPTY=${REQUIRED:?}
ENV NOT_UNSET=${REQUIRED?}
```

Expand shell variable expansion - add mandatory variables

---

solver/llbsolver/ops/exec.go
solver/llbsolver/ops/exec_test.go

fix #1322
regression from https://github.com/moby/buildkit/commit/7b1bae7a42f412262e43da80f9dd9cf86c06fae2#diff-0d2115e5c32fba316a7eaa987331881cR228
#1092 added another global lock to protect writes to the global map of shared cache mounts. Because the lock is taken too early if conflicts with the locking order of the release method. In case the first shared cache mount is released at the same time another mount is taken with the same key locks are held in the opposite order leading to a deadlock. This PR fixes the ordering issue and makes sure the global lock is not taken before it is needed, improving the efficiency of the mounts with locking sharing mode.
Refactored code to allow unit tests. Tests added for the deadlock case and for all of the sharing methods.
@cpuguy83

ops: fix deadlock on releasing shared mounts 

---

client/client_test.go
solver/exporter.go

fixes #1336
@drodriguezhdez @aiordache  
This seems enough to fix the cycle issue (including a case with a longer cycle that doesn't appear with the original repro). But this area needs a bit more analysis, comments and maybe some debugging tooling to verify that the exported chain is still optimal, even in the cycle case. Also needs tests for the repros.

solver: avoid recursive loop on cache-export

---

cache/contenthash/tarsum.go

fix #1330
Security/system xattrs are assigned by the system and are not application-specific.

contenthash: ignore system and security xattrs in calculation

---

docs/rootless.md

The rootless mode is almost feature complete and now should be out of experimental.
(We still don't support cgroups, but it is not specific to rootless)

rootless: graduate from experimental

---

cache/remotecache/registry/registry.go
cmd/buildkitd/config/config.go
cmd/buildkitd/main.go
cmd/buildkitd/main_containerd_worker.go
cmd/buildkitd/main_oci_worker.go
exporter/containerimage/export.go
source/containerimage/pull.go
util/pull/resolver.go
util/push/push.go
util/resolver/resolver.go
util/tracing/tracing.go
worker/base/worker.go

fixes #1394
fixes #1271
@dmcgowan 

resolver: update to new registryhosts based config

---

README.md
client/solve.go

Fix #1242
When `--import-cache type = local` is specified, if a custom tag is included, the cache can be used.

support specifying a custom tag using --import-cache type=local

---

Dockerfile

Previously, `docker buildx build  --platform=linux/arm/v7 --target rootless .`
was failing with `failed to load LLB: runtime execution on platform
linux/arm/v7 not supported`.
Fix #1390

Dockerfile: put fuse3 to rootless-base-internal

---

hack/images

Would like to do rc release for v0.7 as there have been many changes, including to the CI pipeline. This makes sure that a tag like `v0.7.0-rc1` doesn't overwrite `latest/rootless` tags on release. Dockerfile release file already seems to take this into an account. 

hack: allow rc releases without overwriting latest tags

---

cmd/buildkitd/main_containerd_worker.go

Working on k3c @ibuildthecloud noticed this seeming typo.

buildkitd: fix containerd-cni-config-path typo

---

cmd/buildkitd/config.go
cmd/buildkitd/config/config.go
cmd/buildkitd/config_test.go
cmd/buildkitd/main.go
docs/buildkitd.toml.md
util/resolver/resolver.go

resolver: support self signed certificates

---

source/git/gitsource.go

This fixes the following situation:
* The ref is a branch (eg `master`)
* The git source was previously used in another build, with the same URL and branch, but the branch was pointing to a different hash at the time
* The git fetch instruction throws an error, because locally the branch is tracked as a tag and tags are considered immutable. (As the git source had been previously used, the tag already exists locally.)
By using the `--force` flag, the git fetch forces the local tag update.
I've tested this in my own custom application. It fixes an error that looks like this:
```
rpc error: code = Unknown desc = failed to fetch remote git@github.com:vladaionescu/earthly.git: exit status 1
```
Buildkitd log:
```
time="2020-03-28T01:04:00Z" level=error msg="/moby.buildkit.v1.Control/Solve …
```

Add --force flag in git fetch command

---

.travis.yml

These tests were accidentally skipped in travis.
Thanks @drodriguezhdez for reporting this.

travis: make sure buildctl integration tests run

---

util/resolver/resolver.go

The golang net/http package uses http2 client to serve https by default,
if let Transport.TLSNextProto is nil. And net/http package doesn't
provide tunnable value for http2 flow control which will limit push
performance.
Before this commit, use GODEBUG="http2debug=1" buildkitd to pushing
one image from dockerfile like
```
$ about 700MB
FROM scratch
ADD ./golang-1.13.0-stretch.tar.gzip /
```
and use ifstat to monitor network interface and found that
```
$ ifstat -i enp0s3
enp0s3
KB/s in  KB/s out
0.47      0.67
0.44      0.51
19.72     11.56
62.25   2184.41
96.34   3514.28
93.89   3508.31
95.41   3515.53
91.61   3433.22
95.82   3579.68
90.36   3388.89
93.64   3513.03
93.32   3478.04
...
$ log from buildkitd
2020/03/31 17:40:33 http2: Transport received WINDOW_UPDATE stream=11 len=4 …
```

resolver: disable http2 for pushing

---

client/llb/exec.go
client/llb/meta.go
client/llb/state.go

@hinshun the suggestion in https://github.com/moby/buildkit/pull/1426#discussion_r403423877 doesn't really work because `llb.Dir()` already exists for the form `Run(llb.Dir(path))`. This PR generalizes these functions so they can be now also used in form `state.With(llb.Dir(path))`. Note that this does not solve the use-case in https://github.com/moby/buildkit/pull/1426#discussion_r403423877 though as the function takes a path and not another stage as an input so need a new syntax for that.

llb: make generic runoptions stateoptions

---

client/client.go
client/solve.go

Sessions need a way to run independently of a `Solve` and that isn't possible without being to hijack the underlying GRPC connection of a BuildKit client.
This a first step towards #1432, unblocking usage of shared sessions, but will require more design and  implementation to support multiple sessions.

Allow sessions to hijack the connection outside of a solve

---

util/progress/progressui/printer.go

fixes https://github.com/moby/buildkit/issues/1412
Currently, `docker build --progress=plain` truncates output, which makes it
difficult to debug problems during build (the step that failed may not be the
cause of the failure).
For example, in the following build, the output of the `RUN echo ...` is truncated:
DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain -t foo -<<EOF
FROM busybox
RUN echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut lorem nec leo euismod vestibulum. Donec tortor nisl, iaculis at vehicula vel, interdum eu orci. Integer velit lacus, congue id magna eu, mollis accumsan augue. Aliquam non venenatis risus, eu posuere libero. Vestibulum ante ipsum primis in faucibus orci luctus." > /somewhere
RUN echo "something went wrong"; exit 1
EOF
#5 …

progress: disable truncating by default when using --progress=plain

---

util/entitlements/entitlements.go

Make sure entitlement errors coming from missing daemon configuration and missing `--allow` on build are not the same.

entitlements: separate daemon and client errors

---

frontend/gateway/gateway.go
frontend/gateway/pb/caps.go

fixes #957
`Solve()` calls made from the gateway frontend do not reliably return metadata. Seems it wasn't really ever working properly but over commits it seemed to lost support even for some cases that worked before https://github.com/moby/buildkit/commit/303b5da7131cd11fb1934784fef61fb1a5c2a6a8#diff-35ffd957a392f33dd60921b3168d8fd9L391 . 
@hinshun Suprised you haven't hit this in hlb. It doesn't appear in dockerfile default path because subsolve for `#syntax` comes from builtin frontend usually. But as soon as we add nested builds capabilities this should be quite easy to hit, so I added a capability that allows this bug to be detected for cleaner errors.

gateway: fix metadata getting lost on subsolve

---

cmd/buildkitd/main.go
frontend/dockerfile/instructions/commands.go
frontend/dockerfile/instructions/parse.go
frontend/dockerfile/parser/errors.go
frontend/dockerfile/parser/parser.go

Allow any dockerfile parsing error from the token or instruction parser to be tracked to the causing source line.

dockerfile: include parser error location

---

frontend/dockerfile/instructions/parse.go

`errors.As(err, UnknownInstruction)` should be used instead.

dockerfile: remove IsUnknownInstruction

---

frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/instructions/commands.go

Signed-off-by: Jörg Franke <359489+NewJorg@users.noreply.github.com>
fixes https://github.com/moby/moby/issues/40726

Expand chown value of ADD command

---

solver/llbsolver/file/backend.go

fixes https://github.com/moby/moby/issues/34645#issuecomment-615173214
replaces https://github.com/moby/buildkit/pull/1448
regression from #1342

file: fix double-remap of old uid value

---

cache/manager.go
cache/manager_test.go
cache/migrate_v2.go
cache/refs.go
cache/remotecache/registry/registry.go
cmd/buildctl/build.go
executor/oci/user.go
session/content/content_test.go
snapshot/containerd/content.go
solver/errdefs/vertex.go
util/network/cniprovider/cni.go
util/rootless/specconv/specconv_linux.go

```
[5/5] RUN --mount=target=/go/src/github.com/moby/buildkit 	gometalinter ...
0.435 util/rootless/specconv/specconv_linux.go:1::warning: file is not goimported (goimports)
1.320 cache/manager.go:1::warning: file is not goimported (goimports)
1.335 cache/manager_test.go:1::warning: file is not goimported (goimports)
1.337 cache/migrate_v2.go:1::warning: file is not goimported (goimports)
1.342 cache/refs.go:1::warning: file is not goimported (goimports)
1.454 cache/remotecache/registry/registry.go:1::warning: file is not goimported (goimports)
2.285 cmd/buildctl/build.go:1::warning: file is not goimported (goimports)
3.082 executor/oci/user.go:1::warning: file is not goimported (goimports)
4.333 session/content/content_test.go:1::warning: file is not goimported (goimports)
4.614 …
```

Fix goimports linting

---

hack/build_ci_first_pass
hack/cross

I noticed these warnings in CI logs;
+buildctl build --progress=plain --frontend=dockerfile.v0 --opt context=git://github.com/moby/buildkit#refs/pull/1482/merge --opt build-arg:BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 --opt platform=linux/amd64,linux/arm/v7,linux/arm64,linux/s390x,linux/ppc64le,darwin/amd64,windows/amd64 --import-cache cicache.buildk.it/moby/buildkit/master:binaries-cross-helper
WARN[0000] --import-cache <ref> is deprecated. Please use --import-cache type=registry,ref=<ref>,<opt>=<optval>[,<opt>=<optval>] instead.

CI: fix "--import-cache" deprecation warnings

---

examples/buildctl-daemonless/buildctl-daemonless.sh

Allow dynamic max retries on socket connect for buildctl

---

cmd/buildkitd/main_oci_worker.go

Specifying `--oci-worker-rootless` for real root is meaningless and should be prohibited

buildkitd: prohibit --oci-worker-rootless for real root

---

solver/edge.go
solver/scheduler_test.go

solver: gracefully handle cache loading errors

---

examples/buildctl-daemonless/buildctl-daemonless.sh

When the special positional params character isn't enclosed in double quotes it prevents users from passing in arguments spanning multiple words. For example, `--opt build-arg:"word1 word2"` passes `word2` as a separate parameter to buildkit. Enclosing `$@` in double quotes treats each parameter as a separate word.
More here:
https://tiswww.case.edu/php/chet/bash/bashref.html#index-_0024_0040

Fix shell args expansion in buildctl-daemonless.sh

---

README.md

Project [bldr](https://github.com/talos-systems/bldr) provides a way to package and build software as container
images leveraging LLB/buildkit as backend. It translates high-level
`.yaml` build instructions into LLB instructions.

Add `bldr` project link to README as LLB language frontend

---

cache/refs.go

fixes #1510 
When one of the parallel requests is canceled error will be returned without the callback finishing. In that case, the value will be nil and type isn't controlled by the callback. 

cache: avoid nil dereference

---

client/llb/exec.go

skip tmpfs mounts when calculating indexes for llb.GetMount

---

frontend/gateway/grpcclient/client.go
util/testutil/integration/sandbox.go

Looks like these timeouts can be hit under heavy load in integration tests.

increase test context timeouts

---

Dockerfile
solver/llbsolver/bridge.go
solver/llbsolver/ops/exec.go
solver/llbsolver/ops/exec_binfmt.go
solver/llbsolver/solver.go
solver/llbsolver/vertex.go

fixes #1513
This allows emulation for multi-arch in 6 most popular architectures without kernel being configured with binfmt_misc. If kernel is configured binfmt_misc is used instead.
Currently, all the qemu binaries are included with the image. After gzip for x86 this means ~7MB size increase. https://github.com/tonistiigi/binfmt/releases/tag/test0 That should be ok for most cases. I'm not sure if it is ok for Moby though so maybe we should also allow qemu to be pulled from the image during build. There may be licensing issues as well for shipping these qemu binaries with dockerd.
Another possible optimization would be to avoid cloning emulator binary for each exec. Some cache could be introduced. 
The approach of switching entrypoint seems to work on my test builds but lmk if you can …

exec: use qemu emulator automatically

---

cache/contenthash/tarsum.go

contenthash: allow security.capability in cache checksum

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/instructions/commands.go
frontend/dockerfile/instructions/parse.go
solver/llbsolver/file/backend.go

I found that llb.CopyInfo already support mode option, but I'm not sure why there is no support for --chmod in COPY/ADD command. So I made little change to support it.
By the way, --chmod is really useful for us to make a smaller docker image in a easy way.
Signed-off-by: Chen Bin <chen.bin11@zte.com.cn>

dockerfile: add --chmod support for COPY/ADD command

---

cmd/buildkitd/main.go
cmd/buildkitd/main_oci_worker.go
solver/llbsolver/ops/exec.go
util/entitlements/security/security_linux.go

The implementation in libcontainer/system is quite complicated, and we only use it to detect if user-namespaces are enabled.
In addition, the implementation in containerd uses a sync.Once, so that detection (and reading/parsing `/proc/self/uid_map`) is only performed once.

use containerd/sys to detect UserNamespaces

---

client/llb/source.go
solver/pb/attr.go
solver/pb/caps.go
source/git/gitsource.go
source/gitidentifier.go
source/identifier.go

Allow git to authorize with a http token. The value is pulled in with secrets. The secret names are configurable in LLB. Default names are `GIT_AUTH_HEADER` and `GIT_AUTH_HEADER.<host>` for raw authorization header and `GIT_AUTH_TOKEN` and `GIT_AUTH_TOKEN.<host>` for the `x-access-token` style basic auth value that github uses. Not sure if this is the best approach but want to make this simple to use for the default case. Could also add some hardcoded logic for common hosts like github/bitbucket.

git: support for token authentication

---

client/client_test.go
cmd/buildctl/build_test.go
frontend/dockerfile/dockerfile_test.go
util/testutil/integration/containerd.go
util/testutil/integration/run.go
util/testutil/integration/sandbox.go

Before this, the check was always returning that containerd wasn't running and
thus skipping the rest of several test cases.
[Here's a go playground w/ a stripped down example that I believe shows the `interface{}` check wasn't working as expected.](https://play.golang.org/p/hUOwF6F31W7)

client test: Fix check for whether sandbox has containerd

---

cache/blobs/compression.go
client/client_test.go
exporter/containerimage/writer.go

There are a few bugs in the image export related code being fixed here. GetMediaTypeForLayers was iterating over diffPairs in the wrong order, resulting in it always returning nil for images with more than one layer. This actually worked most of the time because it accidentally triggered a separate codepath meant to handle v0.6 migrations where mediatypes left empty get filled in. However, fixing that bug revealed another existing bug where the "oci" parameter in the image exporter was never passed to GetDiffPairs, resulting in newly created images to always have oci layer media types even when docker types are used for the rest of the image descriptors (manifests, config, etc.).
Due to the interaction between these various bugs, the only practical end effect previously was that …

image export: Use correct media type when creating new layer blobs. 

---

util/progress/progressui/display.go

old value ended with a `.` on `sec > 1000` and was plain wrong on `sec > 10000`

progressui: fix logs time formatting

---

util/contentutil/pusher.go
util/push/push.go

This allows to work around the containerd issue on
tracking push status on pushing manifest lists.
https://github.com/containerd/containerd/issues/2706
FYI @hairyhenderson

push: dedupe push handlers

---

Dockerfile

release note: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc91
vendored library isn't updated in this commit (waiting for containerd to vendor runc rc91)

update runc binary to v1.0.0-rc91

---

cmd/buildctl/build/secret.go
session/secrets/secretsprovider/file.go
session/secrets/secretsprovider/store.go

Support `--secret id=foo,env=MY_ENV` as an alternative for storing a secret value to a file. `--secret id=GIT_AUTH_TOKEN` will load env if it exists and the file does not.

secrets: allow providing secrets with env

---

executor/containerdexecutor/executor.go
executor/executor.go
executor/runcexecutor/executor.go
solver/llbsolver/ops/exec.go
worker/base/worker.go
worker/containerd/containerd_test.go
worker/runc/runc_test.go
worker/tests/common.go

First step for #749 refactor Executor interface to allow for Run (pid1) vs Exec'ing into running containers.  Implements proposal outlined in: https://github.com/moby/buildkit/issues/749#issuecomment-655206042

Update Executor interface for Run and Exec

---

cache/remotecache/inline/inline.go

fixes #1388
Blob digest shouldn't be used as a unique identifier as it may appear multiple times in the layer chain. Especially in moby where the digest is not compressed.

inline cache: fix handling of duplicate blobs

---

Dockerfile
client/client_test.go
cmd/buildctl/build_test.go
frontend/dockerfile/dockerfile_test.go
worker/containerd/containerd.go

Per https://github.com/moby/buildkit/pull/1314#discussion_r364477958, this hard-coding was needed to support containerd 1.2, which as of BuildKit 0.7.0 is no longer supported for the containerd worker.
Contributes towards #616

Use containerd's default runtime shim instead of hard-coded runtime v1

---

snapshot/localmounter.go
snapshot/localmounter_unix.go
snapshot/localmounter_windows.go

Due to current deficiencies in the Windows implementation of containerd's Mount.Mount, we need different behaviour for mounting on Windows and Unix platforms.
Specifically:
* Windows mounts can only mount in-place, and hence only one mount should be in the list.
* BuildKit doesn't own the mount directory, so should not try and remove it on unmount.
See discussion leading to https://github.com/moby/buildkit/pull/1314#discussion_r372018865
Contributes towards #616

Split LocalMounter.Mount into Windows and Unix

---

cache/contenthash/tarsum.go

backport for the v0.6 / docker-19.03 branch
- https://github.com/moby/buildkit/pull/1393 contenthash: ignore system and security xattrs in calculation
- fixes https://github.com/moby/buildkit/issues/1330 COPY cache not re-used depending on SELinux environment
- addresses https://github.com/moby/moby/issues/39003#issuecomment-574615437
- https://github.com/moby/buildkit/pull/1526 contenthash: allow security.capability in cache checksum

[v0.6 backport] contenthash: ignore system and security xattrs in calculation

---

frontend/dockerfile/builder/build.go
hack/util
util/testutil/integration/oci.go
util/testutil/integration/sandbox.go

Travis will now correctly build on branches in forks that do not exist in moby/buildkit, so I don't need to actually create the PR just to see if the build will pass. Or ignore the 'build failed' emails from Travis.
There's also a couple of other fixes that came up when I was working on #1387, iterating on the integration tests.

Make Travis usable for forks

---

util/testutil/integration/containerd.go
util/testutil/integration/run.go

A recent change updated the containerd shim built for integ tests to the newer
v2, but the integ test code itself was still hardcoded to look for the older
shim binary and, when that binary wasn't found, skip running the test. This
caused all containerd tests to be skipped.
The fix here updates the binary name to v2 and also removes the branch that
will skip a test when the requirements check fails.
You can see the containerd tests getting skipped prior to this change by searching for "failed to lookup containerd-shim binary: missing requirements" here for example: https://travis-ci.org/github/moby/buildkit/jobs/708809890

Use new containerd shim in integ tests; don't skip on requirement error.

---

cache/remotecache/inline/inline.go

fixes #1388 cache-from working unreliably
Blob digest shouldn't be used as a unique identifier as it may appear multiple times in the layer chain. Especially in moby where the digest is not compressed.

[v0.6 backport] inline cache: fix handling of duplicate blobs

---

cache/remotecache/v1/cachestorage.go
cache/remotecache/v1/chains.go

Before this change, walkAllResults did not skip an item if it had already been
visited, so walking the graph of results actually followed every single possible
path in the graph instead of just visiting each item once.
On small graphs this wasn't noticeable, but on sufficiently large remote cache
imports this rapidly scaled out of control. For example, I first encountered
this when importing a max-cache from a build of a full linux rootfs from source
(which takes about 30 minutes to build w/out cache on an 18-core machine) and
after 30 minutes the cache import was still running with all CPUs pegged at 100%
To fix this, walkAllResults now keeps a map of already visited items (keyed by
their pointer) and skips visiting an item if it's already been visited, making
it usable on large remote …

remotecache: Only visit each item once when walking results.

---

hack/images

Since travis does checkouts with depth 50 we had to reach 50 commits from the last release for master deploy to start failing. Regression from #1404

hack: unblock master deploy

---

solver/llbsolver/file/user_nolinux.go

chowning files still requires Linux.
Contributes towards #616

Support not chowning files on all platforms

---

cache/contenthash/filehash.go
client/client_test.go

This reproduces an error with tar trying to archive a socket, which is similar to the one that was fixed in https://github.com/moby/buildkit/pull/1144
```
client_test.go:1696: 
Error Trace:	client_test.go:1696
run.go:165
Error:      	Received unexpected error:
rpc error: code = Unknown desc = failed to compute cache key: failed to create hash for /root/socket.sock: archive/tar: sockets not supported
github.com/moby/buildkit/util/stack.Enable
/src/util/stack/stack.go:51
github.com/moby/buildkit/util/grpcerrors.FromGRPC
/src/util/grpcerrors/grpcerrors.go:162
github.com/moby/buildkit/util/grpcerrors.UnaryClientInterceptor
/src/util/grpcerrors/intercept.go:22
google.golang.org/grpc.(*ClientConn).Invoke
/src/vendor/google.golang.org/grpc/call.go:35 …
```

fix socket handling during copy

---

snapshot/localmounter_windows.go

This re-aligns this behaviour with the Unix localmounter.
containerd will not currently generate bind-mounts, but I have proposed this in https://github.com/containerd/containerd/pull/4419. In the meantime, this means that any BuildKit-created read-only bind-mounts will do the right thing.
Contributes to #616

Locally shortcut read-only bind mounts on Windows

---

cache/contenthash/filehash.go
cache/contenthash/tarsum.go
cache/refs.go
cache/remotecache/inline/inline.go
client/client_test.go
solver/edge.go
solver/scheduler_test.go
util/contentutil/pusher.go
util/push/push.go

- solver: gracefully handle cache loading errors https://github.com/moby/buildkit/pull/1498
- cache: avoid nil dereference https://github.com/moby/buildkit/pull/1511
- contenthash: allow security.capability in cache checksum https://github.com/moby/buildkit/pull/1526
- push: dedupe push handlers https://github.com/moby/buildkit/pull/1548
- inline cache: fix handling of duplicate blobs https://github.com/moby/buildkit/pull/1568
- fix socket handling during copy https://github.com/moby/buildkit/pull/1581

[v0.7] cherry picks

---

cache/remotecache/v1/cachestorage.go
cache/remotecache/v1/chains.go

https://github.com/moby/buildkit/pull/1577
Missed this in the latest batch.

[v0.6] remotecache: only visit each item once when walking results

---

cache/remotecache/v1/cachestorage.go
cache/remotecache/v1/chains.go

pick https://github.com/moby/buildkit/pull/1577

[v0.7] remotecache: only visit each item once when walking results.

---

.github/workflows/windows.yaml

Only a few tests are able to be run, because the integration test support code fails to compile on Windows, taking effect before the `SKIP_INTEGRATION_TESTS` env-var is handled.
NOTE: GitHub Actions are not currently enabled on moby/buildkit. You can see the results at https://github.com/TBBle/buildkit/tree/windows-CI-on-GitHub_Actions
Contributes towards: #616

Add initial GitHub Actions-based Windows CI

---

cache/refs.go

backport of https://github.com/moby/buildkit/pull/1511
fixes https://github.com/moby/buildkit/issues/1510
This was seen on Docker Desktop "edge" (which switched to use BuildKit by default)

[v0.6 backport] cache: avoid nil dereference

---

.github/workflows/windows.yaml
cache/contenthash/checksum.go
cache/contenthash/checksum_test.go
cache/contenthash/filehash.go
cache/contenthash/filehash_unix.go
cache/contenthash/filehash_windows.go
cache/manager_test.go
client/client_test.go
client/llb/llbtest/platform_test.go
executor/oci/mounts.go
executor/oci/mounts_test.go
frontend/dockerfile/dockerfile_test.go
source/git/gitsource_test.go
source/http/httpsource_test.go
util/network/cniprovider/createns_windows.go
util/rootless/specconv/specconv_nonlinux.go
util/system/path_windows_test.go
util/testutil/integration/run.go
util/testutil/integration/sandbox.go
util/testutil/integration/sandbox_unix.go
util/testutil/integration/sandbox_windows.go

This makes
```PowerShell
${ENV:SKIP_INTEGRATION_TESTS}=1
go test ./...
```
only show test failures, rather than build failures, which puts us in a much better position to actually fix test failures and/or mark tests on not-for-Windows.
I've also skipped tests which fail due to missing support in containerd, to reduce the failing-test noise levels.
Apart from fixes in #1594, all unit tests now pass, but there's a couple of code changes that probably need close attention to confirm the fix was correct:
* 9b0c2906ee52b2992b8ee399d7f71a387bf86df8
* 8c31a337cd6918fb96e6a73a054c6870d141715d
Contributes towards: #616

Fix test failures in unit tests on Windows

---

hack/images

After rootless changes that rebuild from source deploy ci in master takes a lot of time (~40min). This should cut it down by reusing cache from previous master build.

hack: use caching for master deploy

---

executor/containerdexecutor/executor.go
executor/oci/user.go
executor/runcexecutor/executor.go

Noticed this was unused, but perhaps this was meant to be used at some point, in which case feel free to close

executor/oci.GetUser(): remove unused context

---

hack/test

It also doesn't need dockerd added to its container when it builds.
Recording the clarification I received at https://github.com/moby/buildkit/pull/1606#issuecomment-664462494
I had looked at moving it into a build stage, adding it to the Dockerfile, but since it doesn't produce any artifacts, it sad weirdly there.

Clarify the gateway 'test' as a build-test

---

.github/workflows/windows.yaml
solver/testutil/cachestorage_testsuite.go

On Windows, the resolution of time.Now() can be surprisingly low: 15ms according to the comments in the source of time.Now().

Ensure that time has passed between foo0 and foo1

---

.github/workflows/windows.yaml
cmd/buildkitd/main_containerd_worker.go
executor/oci/mounts.go
executor/oci/mounts_test.go
executor/oci/spec.go
executor/oci/spec_unix.go
executor/oci/spec_windows.go

Contributes to #616
There's only a couple of things that are host-platform limited, i.e., security and process modes.
Everything else is specific to a target-platform. We can tell if we're targeting a Linux platform, either on Linux or LCOW, by the presence of the Linux key in the generated spec.
This doesn't introduce support for LCOW, as we'd need to plumb that down from the caller. It will probably also need massaging to work with LCOW, as some of the setup code here is probably incorrect for LCOW, e.g., the bind-mounts list may be incorrect.
----
It's actually a much smaller change than it looks, but a lot of code moved from _spec_unix.go_ to _spec.go_. If you compare old spec_unix.go to new _spec.go_, the changes in `GenerateSpec` and the lack of changes in the _other_ functions …

Unify OCI Spec generation across all host platforms

---

cmd/buildctl/build/secret.go

`type=env,env=foo` would not work before

buildctl: improve secret parsing

---

util/pull/resolver.go
util/resolver/resolver.go

- Containerd config loading repeatedly calls hosts config callback, creating new authorizer. Now authorizer is cached. Also client was recreated if the host had a custom configuration.
- Keep-alive was disabled with HTTP2 but shouldn't have been. HTTP/2 remains disabled.
- EnsureManifestLoaded check (for gcr broken auth) had regressed and wasn't working because a struct was cloned
This should significantly improve performance for registry communication. Still a lot of things to improve but at least all regressions should be gone now. For further changes, I'd need to make more auth helper functions public in containerd to avoid copy-paste.
@sipsma @fuweid

resolver: fix resolver reuse

---

executor/containerdexecutor/executor.go
executor/executor.go
executor/runcexecutor/executor.go
worker/tests/common.go

More incremental work for #749 
This returns the process exit status from Run/Exec so we can send it in the ExitMessage.  This also plumbs in a Resize channel to handle resize events.
I will have another PR soon with the proto changes and server side changes for that, I just wanted to get these executor changes in to keep the PRs managable.   I have some questions about client side so I will add those questions/proposals to #749 
Through testing I found `runc` to be challenging since it will not create a pty like `containerd` does.  So for now I modified runc to just return "not implemnted" error when tty is requested.  I am trying to understand how `containerd` manages the pty with the console-socket option on `runc` so I hope to find a solution soon, but will likely be another follow up …

return exit status from executor Run/Exec

---

.travis.yml

after_failure does not get triggered after deploy failure. 

travis: replace after_failure with after_script

---

client/connhelper/dockercontainer/dockercontainer.go
client/connhelper/kubepod/kubepod.go

fixes #1626 
Dial context is canceled after connection is
established so can’t be used for a long running process.

client: fix connhelper context canceling

---

README.md
client/connhelper/podmancontainer/podmancontainer.go
client/connhelper/podmancontainer/podmancontainer_test.go
cmd/buildctl/main.go

Similar to `docker-container://` but for Podman containers.

new connection helper: podman-container://<CONTAINER>

---

go.mod
solver/errdefs/vertex.go
util/grpcerrors/grpcerrors.go
util/stack/stack.go

Also switches current types to json(default in containerd/typeurl).
Adds better future compatibility to typed errors that now have to be registered with full name and avoids depending on either google/protobuf or gogo when this library would be used. This makes sure the code can be moved around between repositories in the future if needed and new encoders added. Reused contained/typeurl package but in the future this should probably be switched to a custom implementation. These changes should not be breaking.
These changes are not compatible with current typed errors in master. No release version is affected.
@hinshun @AkihiroSuda 

grpcerrors: use full typeurl registration

---

client/client.go

fixes #1566 
This PR sets custom `:authority` pseudo header with `Host` part of address url via `grpc.WithAuthority` dial option.  
This is because:
- grpc-go uses a slightly different naming scheme(https://github.com/grpc/grpc/blob/master/doc/naming.md)
- This will end up setting rfc non-complient :authority header to address string (e.g. tcp://127.0.0.1:1234)
- valid authority header does not contain a scheme https://tools.ietf.org/html/rfc3986#section-3.2
I think current `--addr` option uses `net.URL` even though custom connection helpers like `kube-pod://, dockercontainer://`.  So, I think that taking `url.Host` part wouldn't  cause a serial problem.

Setting `Host` part  of address url to `:authority` pseudo header

---

MAINTAINERS

Thanks for all the great contributions to BuildKit you have done so far @coryb @sipsma . Welcome to maintainers.
Already agreed with the vote in Slack, but feel free to check the e-mails are correct etc.

add sipsma and coryb as maintainers

---

util/network/cniprovider/cni.go

This PR removes a dangling `if err != nil {}` check that was already done right above. I tried to follow contribution guidelines, but let me know if I missed something.
Signed-off-by: Miguel Ángel Jimeno <miguelangel4b@gmail.com>

cni: remove duplicate error check

---

Dockerfile
cache/manager.go
cache/opts.go
cache/refs.go
cache/remote.go
client/client_test.go
cmd/buildctl/build_test.go
cmd/buildkitd/config/config.go
cmd/buildkitd/main_containerd_worker.go
cmd/buildkitd/main_oci_worker.go
source/containerimage/pull.go
util/testutil/integration/containerd.go
util/testutil/integration/run.go
util/testutil/integration/sandbox.go

Related issues: 
- https://github.com/moby/buildkit/issues/1396
- https://github.com/containerd/stargz-snapshotter/pull/53
Throughout building steps, "pulling base image" is one of the time-consuming steps.
Recently, containerd community started "Stargz Snapshotter" (containerd/stargz-snapshotter) non-core subproject for speeding up image pulling. With this snapshotter, we can directly mount stargz-formatted (but still docker-compatible) image to nodes, which takes much shorter than downloading the whole of the image to nodes.
This commit solves the performance problem on pulling base images for "dev" stages using stargz snapshotter.
We introduced new RecordType "snapshot" for unexported base images. These images aren't guaranteed to have their whole contents in the content store but …

Support stargz snapshotter for dev stages

---

.travis.yml
worker/containerd/containerd_test.go

fixes issue #1637, containerd worker tests now running as integration tests:
https://travis-ci.org/github/moby/buildkit/jobs/722986753#L2677

ensure containerd is running for worker tests

---

client/client_test.go
frontend/dockerfile/dockerfile_test.go

CI is broken and the issue seems to be not a buildkit change but a change in busybox image used in test.
```
nogroup:x:65534:
nobody:x:65534:
```
We should probably also pin to a specific version to avoid this. But corrected the tests atm.
@tianon I assume this change was intentional and we don't expect a rollback.

fix tests after busybox update

---

source/containerimage/pull.go

In containerd, there is a size limit for label size ([4096 chars](https://github.com/containerd/containerd/blob/c862000ab96364d71559afadd82f6d8155dc5463/labels/validate.go)).
If an image has many layers (> (4096-43)/72 > 55), `containerd.io/snapshot/remote/stargz.layers` will hit the limit of label size and the remote snapshot preparation will fail.
This commit fixes this by limiting the size of the label.

Limit size of additional label for avoiding preparation failure

---

client/client_test.go
frontend/dockerfile/dockerfile_test.go

backport of https://github.com/moby/buildkit/pull/1681
cherry-pick wasn't clean, because `testDockerfileAddChownExpand()` is not yet in this branch (was added in https://github.com/moby/buildkit/pull/1473)

[v0.6 backport] fix tests after busybox update

---

util/progress/progressui/display.go

backport of https://github.com/moby/buildkit/pull/1486
addresses https://github.com/moby/buildkit/issues/1479

[v0.6 backport] progressui: fix panic on terminals with zero height

---

client/client_test.go
frontend/dockerfile/dockerfile_test.go

backport of https://github.com/moby/buildkit/pull/1681
cherry-pick wasn't clean, because `testDockerfileAddChownExpand()` is not yet in this branch (was added in https://github.com/moby/buildkit/pull/1473)

[v0.7 backport] fix tests after busybox update

---

client/llb/source.go

If client has been updated using `llb.Git` fails by default against old daemons. Change it so it only fails if client opts in to using the new token features.

client: avoid checking token cap on default case

---

Dockerfile

Allow stargz target in Dockerfile to use golang build cache

---

session/sshforward/sshprovider/agentprovider.go
session/sshforward/sshprovider/agentprovider_test.go

I tested this with https://github.com/tilt-dev/tilt, which links in the SSHProvider code directly and calls buildkit with the API library
Before this change, ssh mounts failed with 
```
could not parse ssh: [default]: failed to parse C:/Users/nick/AppData/Local/Temp/ssh-fEsqO14952/agent.14952: ssh: no key found
```
After this change, they worked correctly.
Fixes https://github.com/moby/buildkit/issues/914

sshprovider: on Windows, ModeSocket might not be set on the ssh socket

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/instructions/commands.go
frontend/dockerfile/instructions/parse.go
frontend/dockerfile/instructions/parse_test.go
frontend/dockerfile/parser/testfiles/args/Dockerfile
frontend/dockerfile/parser/testfiles/args/result

`ENV` accepts multiple definitions with a single command, no reason why `ARG` should behave any differently.

dockerfile: allow multiple values for ARG

---

frontend/gateway/grpcclient/client.go
session/grpc.go

The dockerfile frontend is sending an invalid value (`""`, empty string) for the HTTP/2 "authority" pseudo-header. As per https://github.com/grpc/grpc-go/issues/3854, it seems this can be fixed in Buildkit by specifying a non-empty target when creating the DialContext.
I have verified that with this change the authority header now indicates "localhost".

Make HTTP/2 authority pseudo-header spec-compliant

---

cmd/buildctl/build.go
session/auth/auth.go
session/auth/auth.pb.go
session/auth/auth.proto
session/auth/authprovider/authprovider.go
session/auth/authprovider/tokenseed.go
util/progress/progresswriter/multiwriter.go
util/progress/progresswriter/printer.go
util/progress/progresswriter/progress.go
util/progress/progresswriter/reset.go
util/progress/progresswriter/writer.go
util/resolver/authorizer.go
vendor/golang.org/x/crypto/nacl/sign/sign.go
vendor/modules.txt

Instead of sharing credentials with the daemon use session to request temporary tokens requested from the cli side. The tokens are still reused with resolvers like before and efficiency shouldn't suffer. @sipsma 
~Marking wip to add client-side progress injection making token requests visible. This turned out to be more complicated and I'm moving code from buildx to buildkit to achieve it.~

auth: fetch tokens from client side

---

util/resolver/authorizer.go

In [Earthly](https://github.com/earthly/earthly), we've seen errors that look like these:
```
rpc error: code = Canceled desc = failed to load cache key: failed to authorize: failed to fetch oauth token: context canceled
```
```
rpc error: code = Canceled desc = failed to load cache key: failed to authorize: failed to fetch anonymous token: context canceled
```
When these are encountered, new builds stop working altogether, because the error remains cached permanently in buildkitd. Restarting buildkitd fixes the problem.
The change in this PR prevents context.Canceled errors from being cached at all.
Related issue in Earthly: https://github.com/earthly/earthly/issues/245
CC @alexcb @agbell

Prevent context canceled errors from being permanent in authorizer

---

util/grpcerrors/grpcerrors.go
util/grpcerrors/intercept.go
util/stack/stack.go

Mark some common functions as helpers so they don't show up on top of (almost all) stack traces.

stack: remove helper functions from error stack traces

---

client/build_test.go
executor/runcexecutor/executor.go
executor/runcexecutor/executor_common.go
executor/runcexecutor/executor_linux.go
frontend/gateway/grpcclient/client.go

This reuses some of the containerd logic for handling console io.   The basic outline is that now all runc calls are made with `detach: true` and an associated pidfile.  We have a `SIGCHLD` reaper so we can get notified when the detached pid exits (and determine exit status).   When a tty is requested we use the `console-socket` options in runc so that runc creates the pty pair and returns the ptm via the socket.
I tried naively creating a pty pair in buildkit and setting the input streams to the pts, which mostly worked, except the ptm resize had no effect this way, it seems using the `console-socket` is the only way to allow resize events to propagate.
Unfortunately this is a linux only implementation since the containerd libraries in use are linux only: …

add tty support for runc executor

---

exporter/containerimage/export.go
exporter/containerimage/writer.go
util/push/push.go

Fixes https://github.com/docker/setup-buildx-action/issues/29
Manifests with Docker media types do not define `Annotations` for descriptor like oci spec does. Normally registries just ignore JSON keys they don't understand but GCR is picky and produces `400` error for such manifest. This PR makes sure that annotations are never in Docker manifests and also removes the internal annotations from OCI manifests as they do not add anything to the image context.
@sipsma I believe this is a regression from `GetRemote` changes that now handle full descriptors.
If you hit this another workaround is to switch to oci mediatypes. `-o type=image,oci-mediatypes=true,push=true`
Also found another GCR issue in containerd while debugging this. If you hit 401 specifically in GCR you are probably hitting …

exporter: avoid descriptor annotations on docker manifests

---

client/build_test.go
executor/runcexecutor/executor.go
executor/runcexecutor/executor_common.go
executor/runcexecutor/executor_linux.go
go.mod
go.sum
vendor/github.com/containerd/go-runc/.travis.yml
vendor/github.com/containerd/go-runc/go.mod
vendor/github.com/containerd/go-runc/go.sum
vendor/github.com/containerd/go-runc/io_unix.go
vendor/github.com/containerd/go-runc/runc.go
vendor/github.com/containerd/go-runc/runc_unix.go
vendor/github.com/containerd/go-runc/runc_windows.go
vendor/modules.txt

This fixes status error handling for runc exec, also makes status error messages common between runc and containerd executors.
Pulls in latest go-runc mod.  `Runc.PdeathSignal`  has been moved upstream to be `unix` only, so I have made the corresponding fix for the runc executor also.

update go-runc  module, use runc.ExitError for container exec status

---

cache/remotecache/v1/utils.go
executor/containerdexecutor/executor.go
executor/runcexecutor/executor.go
executor/stubs.go
exporter/containerimage/exptypes/types.go
exporter/containerimage/writer.go
frontend/dockerfile/dockerfile_secrets_test.go
snapshot/imagerefchecker/checker.go

Fixes https://github.com/moby/moby/issues/38667 by removing the empty files that were created for the mountpoints. Otherwise, paths used for secrets or `/etc/resolv.conf` would remain in the image as empty files.
While testing with the fix I discovered cases where empty layers were not handled properly for cache export. Extra commits fix these cases. After that, the example case in https://github.com/moby/buildkit/issues/1727 now produces reproducible digests.

clear file mount stubs and fix empty layer cases

---

solver/llbsolver/result.go

I noticed this while working on code related to the solver. The bug noted by the `FIXME` is very likely the common issue with for loops + goroutines. The variable `sel` is not in the closure of the function, so you can fix it by re-declaring the variables in the body of the loop, or calling it with an anonymous function. Re-declaring seems cleaner because there's less nesting.

Enable parallelization of NewContentHashFunc

---

session/auth/authprovider/tokenseed.go

fixes: https://github.com/moby/buildkit/pull/1660#issuecomment-707575924
Allow client-side tokens to work even if the config directory is readonly. Token seeds are kept in memory only and reset on each invocation. This means tokens are not reused like in the default case as they can't be verified for a new client but that performance loss can be expected on a weird setup like this.
@mkasprzyk @sipsma 

authprovider: allow readonly config dir

---

Dockerfile

Dockerfile: don’t remove debug info on buildkitd/runc binaries

---

client/llb/exec.go
client/llb/llbtest/platform_test.go
examples/buildkit0/buildkit.go
examples/buildkit1/buildkit.go
examples/buildkit2/buildkit.go
examples/buildkit3/buildkit.go
examples/nested-llb/main.go
exporter/containerimage/writer.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/defaultshell.go
frontend/dockerfile/dockerfile2llb/defaultshell_unix.go
frontend/dockerfile/dockerfile2llb/defaultshell_windows.go
frontend/dockerfile/dockerfile2llb/image.go
frontend/dockerfile/dockerfile_test.go
frontend/gateway/container.go
solver/llbsolver/ops/exec.go
util/system/path.go
util/system/path_unix.go
util/system/path_windows.go

dockerfile: set correct default path and shell based on OS

---

README.md
cache/remotecache/export.go
cache/remotecache/local/local.go
cache/remotecache/registry/registry.go

remotecache: allow oci mediatypes on exporting to registry

---

client/build_test.go
source/containerimage/pull.go
util/pull/pull.go

cc @tonistiigi 
Reproduce with `make test TESTPKGS=./client TESTFLAGS="--run /TestClientSlowCacheRootfsRef -v"`
Only errors with `worker=containerd-1.3`:
```
--- PASS: TestClientGatewayIntegration/TestClientSlowCacheRootfsRef/worker=oci-rootless (0.80s)
client_test.go:3214: checkAllReleasable: skipping check for exported tars in non-containerd test
--- PASS: TestClientGatewayIntegration/TestClientSlowCacheRootfsRef/worker=oci (2.71s)
client_test.go:3214: checkAllReleasable: skipping check for exported tars in non-containerd test
--- PASS: TestClientGatewayIntegration/TestClientSlowCacheRootfsRef/worker=containerd (3.25s)
--- PASS: TestClientGatewayIntegration/TestClientSlowCacheRootfsRef/worker=oci-snapshotter-stargz (3.37s)
client_test.go:3214: checkAllReleasable: skipping check for …
```

Add test for second solve using rootfs of first solve that error'ed from CalcSlowCache

---

frontend/dockerfile/parser/parser.go
frontend/dockerfile/parser/parser_test.go
frontend/dockerfile/parser/testfiles/trailing-backslash/Dockerfile
frontend/dockerfile/parser/testfiles/trailing-backslash/result

fixes https://github.com/docker/for-win/issues/5254
If the line-continuation marker (`\`) is escaped, it should not be treated as such, but as a literal backslash, for example, the following should produce 5 `ENV` instructions:
```dockerfile
FROM hello-world
ENV A path
ENV B another\\path
ENV C trailing\\backslash\\
ENV D This gets appended to C
ENV E hello\
\
world
```

Dockerfile: fix parsing of trailing backslash

---

cmd/buildkitd/config/config.go
cmd/buildkitd/main.go
cmd/buildkitd/main_oci_worker.go

https://github.com/moby/moby/pull/41601#issuecomment-718730085
`cmd/buildkitd/config` pkg is imported and used by other packages including moby/moby.
Though stargz snapshotter configuration is currently effective only with buildkitd + OCI worker, `cmd/buildkitd/config` consumer needs to introduce an indirect dependency to stargz snapshotter's config pkg (`github.com/containerd/stargz-snapshotter/stargz/config`), which is too much.
This commit solves this by delaying decoding the stargz config until OCI worker's initialization phase.

Delay decoding stargz config for avoiding extra dependency for config pkg

---

util/network/cniprovider/createns_linux.go

Instead of removing the file `nativeID`, we were removing the dir containing all `nativeID`s. This was causing a race between the `MkdirAll` trying to create the `cni` dir and any `nativeID`s being removed, where the entire `cni` dir was wiped.
The errors looked cryptic: `failed to mount: no such file or directory` and was only showing up in highly-parallel buildkit-in-buildkit situations (like in Earthly's [integration tests](https://github.com/earthly/earthly/blob/main/examples/tests/Earthfile)).

Fix race in CNI namespaces

---

client/client.go
control/control.go
util/progress/logs/logs.go

fixes #1539
If the build produces a lot of logs it can slow down the build (especially on remote client) and reach grpc message size limit. Add some reasonable limits per process: 1MB max output and 100KB/s. If the process reaches this limit the progress output will be clipped. The limits are configurable with env if anyone wants to abuse the logic.

progress: add log limits and clipping

---

Dockerfile

Following-up: https://github.com/moby/buildkit/issues/1663
Currently moby/buildkit image misses fuse dependency (fusermount) so currently stargz support doesn't work on that image. 
This commit fixes this issue.

Add fuse dependency to moby/buildkit image

---

Dockerfile

QEMU usermode emulation is robust enough for running `apk add --no-cache git xz`, so can we can safely remove the pre-built git stage.

Dockerfile: remove pre-built git stage

---

cache/remote.go
solver/llbsolver/result.go
solver/llbsolver/solver.go
worker/cacheresult.go
worker/result.go

This fixes panics in the moby integration of buildkit when using cache.
Panics come from nil Differ in computeBlobChain which is called in GetRemote().
GetRemote() got moved from Worker to ImmutableRef during the lazy-pull refactor.
However, the ability to easily override GetRemote() got lost with that refactor.
This patch attempts to allow for the override while keeping changes minimal.

Allow worker to override GetRemote(), needed in moby integration

---

Makefile

The DESTDIR is supposed to be an optional staging location,
while the prefix says where software is going to be installed.
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
https://www.gnu.org/prep/standards/html_node/DESTDIR.html
Using standard variables make it easier to package (works out-of-the-box)
From #1794

Use standard Makefile install variables

---

cache/remote.go
cache/remotecache/export.go
util/contentutil/copy.go
util/contentutil/copy_test.go
util/contentutil/fetcher_test.go
util/imageutil/config.go
util/progress/logs/logs.go
util/pull/pull.go
util/push/push.go
util/resolver/retryhandler/retry.go

Unlike docker, containerd does not perform retries on dropped connections. This adds basic retry backoff mechanisms for certain errors while logging them instead. Note that chunk based resume is still missing on push.

add retry handlers to push/pull

---

go.mod
go.sum
vendor/modules.txt

github.com/Microsoft/go-winio v0.4.15 was tagged; same commit as was already vendored, so no code-changes.

vendor: github.com/Microsoft/go-winio v0.4.15

---

Dockerfile

Seems to be slightly faster. How much depends on the system but at least don't see it hurting performance.

Dockerfile: use pigz to uncompress

---

client/llb/source.go
util/sshutil/keyscan.go

- This is a followup PR to #1782 where we discovered that ssh-based git clones were not working.
- This also adds the default ssh mount, and automatically scans for a key when none are given.

Fix parsing ssh-based git sources

---

frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile2llb/convert_test.go

We have an unstable registry which sometimes cause the failure of fetching base-image manifest(config), but it didn't fail the build job. Then the built image will discard some run-time config defined in base-image(like ONBUILD, ENV...) 
logs like this:
> #3 [internal] load metadata for sofa-jdk8-4484-7u2:20200214_5...
> #3 ERROR: failed to fetch schema1 manifest: httpReaderSeeker: failed open: could not fetch content descriptor sha256:b659f107d54f2e1e746745be4252f0f7828b0ed10ff875256d8a1ebac58ef1d4 (application/vnd.docker.distribution.manifest.v1+prettyjws) from remote: not found
> 
> #4 [1/3] FROM sofa-jdk8-4484-7u2:20200214_5...
> #4 resolve acs-reg.alipay.com/image-mybank/sofa-jdk8-4484-7u2:20200214_56f781c 0.0s done
> #4 DONE 0.0s
Meet error but not exist 
I think we should return …

dockerfile build:  fix not exit when meet error in load config metadata

---

executor/containerdexecutor/executor.go
executor/runcexecutor/executor.go
frontend/gateway/gateway.go
frontend/gateway/grpcclient/client.go
solver/errdefs/exit.go

relates to https://github.com/docker/cli/pull/2843
Copy this const to a local constant to prevent importing the containerd client in the front-end.
For consistency, I also updated the executor code to use the same const, although not strictly needed.

copy  containerd.UnknownExitStatus to local const

---

Dockerfile

`git` stage can't be used as it is a cross-compilation stage.
regression from #1780

dockerfile: fix base stage platform for exported image

---

go.mod
go.sum
vendor/golang.org/x/crypto/ssh/client_auth.go
vendor/golang.org/x/crypto/ssh/kex.go
vendor/modules.txt

I noticed some parts being deprecated, but looks like those are not used in this codebase. There are some (performance) enhancements in the changes, so thought I'd open a PR anyway 😅 
full diff: https://github.com/golang/crypto/compare/75b288015ac94e66e3d6715fb68a9b41bf046ec2...c1f2f97bffc9c53fc40a1a28a5b460094c0050d9
relevant changes:
- ssh: improve error message for KeyboardInteractiveChallenge
- ssh: remove slow unnecessary diffie-hellman-group-exchange primality check
other changes (not in vendor);
- ssh/terminal: replace with a golang.org/x/term wrapper
- Deprecates ssh/terminal in favor of golang.org/x/term
- ssh/terminal: add support for zos
- ssh/terminal: bump x/term dependency to fix js/nacl
- pkcs12: document that we use the wrong PEM type
- pkcs12: drop PKCS#12 attributes with …

vendor: golang.org/x/crypto v0.0.0-20201117144127-c1f2f97bffc9

---

util/sshutil/keyscan.go

- make use of standard net.SplitHostPort and net.JoinHostPort functions

Fix sshkeyscan to work with ipv6

---

Dockerfile

This is a workaround for https://github.com/golang/go/issues/35305 which makes it possible to successfully push to a local registry using
```bash
$ docker buildx build --push --tag localhost:5000/foo .
```
assuming, of course, that the builder instance currently in use has been created using
```bash
$ docker buildx create --driver-opt network=host
```
The workaround is no longer going to be necessary once Go 1.16 is used for builds.

images: Create simple /etc/nsswitch.conf file

---

cache/refs.go

Following-up: https://github.com/moby/buildkit/pull/1825
> Looking at the code I'm not sure why this function gets called at all on non-stargz. If it is not needed it makes the default path slower and should be avoided.
Since this patch, checking logic is enabled only for the configuration with "stargz" snapshotter. Currently this is done by checking the name of the snapshotter but we should find more generic way when more implementations of remote snapshotters are supported by BuildKit.
cc: @tonistiigi

Check remote snapshot availability only for stargz

---

.github/workflows/validate.yml
.travis.yml
hack/lint
hack/util
hack/validate-generated-files
hack/validate-shfmt
hack/validate-vendor

Refactor validate for GitHub Actions

---

frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile_test.go

This was supported by the legacy builder moby/moby#10858

dockerfile: allow lowercase dockerfile name

---

cache/refs.go

Otherwise the error result may cause a panic.
@ktock Looking at the code I'm not sure why this function gets called at all on non-stargz. If it is not needed it makes the default path slower and should be avoided.

cache: handle nil result from flightcontrol

---

solver/jobs.go
solver/llbsolver/bridge.go
solver/llbsolver/errdefs/exec.go
solver/llbsolver/solver.go

There was two code paths that seem to lead to the original error (with all the error results) being dropped, so this PR is an approach at guaranteeing the err results are accounted for.
Dangerous code paths:
- https://github.com/moby/buildkit/blob/b0ed56c6d0e068fe8010e0aebdf2e166f4a6e4e3/solver/llbsolver/bridge.go#L236
- https://github.com/moby/buildkit/blob/b0ed56c6d0e068fe8010e0aebdf2e166f4a6e4e3/solver/llbsolver/bridge.go#L244
I'm unsure if this addresses the issue with #1818

Guarantee err results are released when result proxy is released

---

client/build_test.go

client: temporarily skip testClientSlowRootfsRef for containerd

---

docs/rootless.md

Isolating network namespace with `rootlesskit --net=slirp4netns` is recommended for protecting localhost sockets and abstract sockets on the host.
This is not meaningful for running rootless buildkitd inside a container (because netns is already isolated), so slirp4netns is not added in Dockerfile.

docs/rootless.md: add instruction for isolating netns

---

client/build_test.go
frontend/gateway/gateway.go
solver/errdefs/context.go
source/containerimage/pull.go

fixes #1820
Cancellation errors should not be stored but when cancel error came from containerd client it was not matched by regular `errors.Is` check. This would not have happened if containerd used the same wrapped typed errors as buildkit but current containerd API does not allow me to add buildkit rpc wrapping to containerd calls. So instead use a special cancellation detection.
Also fix clearing the temporary leases so they could not accidentally cancel the context as well.
@crazy-max 

fix invalid cancellation errors on pull

---

frontend/dockerfile/instructions/parse.go
frontend/dockerfile/instructions/parse_test.go

Addressing issue #1119.
Added check to `parseEntrypoint` ensuring at least one argument is provided. Added ENTRYPOINT to the list of commands requiring at least one argument in `parse_test.go` as well.
Signed-off-by: Andrew Chang <chang331006@gmail.com>

Ensure ENTRYPOINT command has at least one argument

---

frontend/dockerfile/instructions/parse.go
frontend/dockerfile/instructions/parse_test.go

This reverts commit 174bcf85efbd65ffdc19acfb7d0cab653e78a979 (https://github.com/moby/buildkit/pull/1862),
This commit attempted to fix a situation where an empty entrypoint was specified, causing a confusing error when running the image (https://github.com/moby/buildkit/issues/1119), however, allowing the entrypoint to be reset should be a valid use-case, and running such image on docker 20.10 at least produces an informative error;
docker build -t foo -<<'EOF'
FROM busybox
ENTRYPOINT []
EOF
Or, to reset a previously set entrypoint:
docker build -t foo -<<'EOF'
FROM busybox AS one
ENTRYPOINT ["/bin/busybox"]
FROM one AS two
ENTRYPOINT []
EOF
If no command is specified for the image above:
docker run -it --rm foo
docker: Error response from daemon: No command specified.
See 'docker run …

Revert "Ensure ENTRYPOINT command has at least one argument"

---

client/llb/fileop.go
client/llb/state_test.go

If source root sets the platform for a state, vertexes should
keep that instead of using the global value passed on marshal.
Already worked properly for exec, but not for file.

llb: make sure fileop uses the platform for current state

---

solver/jobs.go

Previous versions of buildkit leaked job IDs. Cleanup was added in #1752 but it is too agressive. As `Solve()` and `Status()` requests are made in parallel, `Solve()` could finish up before `Status()` arrives and receives " job ID not found".
Saw this failing in an integration test.

solver: delay before discarding job

---

client/llb/source.go
source/gitidentifier.go
source/identifier.go
util/sshutil/transport_validation.go
util/sshutil/transport_validation_test.go

This fixes `docker buildx build github.com/foo/bar`. github.com is a special hostname hardcoded in dockerfile frontend but recent updates in LLB layer made it so that url without protocol could not be passed to `llb.Git()`. This fixes it from both client and server side. Only one side is really needed to have it working again.
@alexcb

fix building from git url without a protocol

---

util/flightcontrol/flightcontrol.go
util/flightcontrol/flightcontrol_test.go

There was a race with context getting cancelled and new request
arriving that could resulted new request to receive cancelled result
as well. This happened because lock was held when getting the Done()
channel but it could have been already released by the time returned
channel was closed.

flightcontrol: fix possible invalid cancellation

---

solver/edge.go

This reverts commit 706129170dcdb01e6592073491056e9fe105a673 from #1863 with some modification.
Preprocess should not be taken into account when calculating
cache-slow state. But it should be used to detect if dep is complete
so preprocess runs before parent's exec function.

solver: fix slow-cache status tracking with preprocess

---

util/compression/compression.go

fixes #1877
Using the original mediatype for compression detection tried to push with a foreign mediatypes that is not always allowed by registries.
The current logic doesn't support other compressions than gzip. Future change should allow storing multiple blobs with different compressions/no-compression and convert from one compression to other if needed.

handle foreign mediatypes on push

---

README.md
docs/images-readme.md

This is the base for readme at https://hub.docker.com/r/moby/buildkit . Maybe in the future, this can be automated so tags don't need to be modified manually.

docs: add readme used for registry images

---

client/client_test.go
exporter/containerimage/export.go
exporter/containerimage/writer.go
exporter/oci/export.go

Accessing config digest is important when exporting to Docker where manifests digests are not yet supported. 
Related https://github.com/docker/buildx/issues/420

exporter: return config digest when exporting single-arch image

---

frontend/frontend_test.go
solver/llbsolver/solver.go

Returning `nil,nil` from frontend could result in a `nil dereference panic`.
The added test actually does not catch this as the client gateway has no issue, but added for future safety. Testing frontends via a gateway is kind of complicated outside of dockerfile atm.

allow nil return from frontend

---

hack/bootstrap-buildx
hack/install-buildx
hack/util

DOCKER_BUILDKIT CLI is slightly different from buildx.
It is hard to maintain DOCKER_BUILDKIT as a buildx alternative.

hack/util: install buildx when not installed

---

client/build_test.go
executor/containerdexecutor/executor.go
executor/containerdexecutor/executor_test.go
executor/runcexecutor/executor.go
frontend/gateway/errdefs/exit.go
frontend/gateway/gateway.go
frontend/gateway/grpcclient/client.go

resolves #1811
moved the variable from errdefs to be next to the executor interfaces
also renaming the variable since it is returned from both runc and container executor

move UnknownExitStatus to executor package from errdefs

---

.github/workflows/buildx-image.yml

Ref. docker/buildx#479 docker/buildx#419
Simple workflow to be able to create/update the buildkit tag for [buildx docker-container driver](https://github.com/docker/buildx/blob/master/driver/bkimage/bkimage.go). Only members with `write` access to this repo are allowed to trigger this workflow.
We could also add more restrictions:
* Specific users that can trigger the workflow: `if: contains('["AkihiroSuda","tonistiigi"]', github.actor)`
* Specific prefix to avoid tag corruption (`buildx-`?)
* Immutability?

Dispatch workflow for buildx image

---

README.md
cmd/buildkitd/main.go
cmd/buildkitd/main_unix.go
cmd/buildkitd/main_windows.go
examples/systemd/buildkit.service
examples/systemd/buildkit.socket
vendor/github.com/coreos/go-systemd/v22/activation/files.go
vendor/github.com/coreos/go-systemd/v22/activation/listeners.go
vendor/github.com/coreos/go-systemd/v22/activation/packetconns.go
vendor/modules.txt

Used go-systemd code from moby/moby daemon
Only added `buildkitd --addr fd://` for now.
Closes #1923

Add support for fd:// for socket activation

---

Dockerfile
solver/llbsolver/ops/exec_binfmt.go

Fixes bugs with executing scripts with shebang and adds 386 emulator.
https://github.com/tonistiigi/binfmt/compare/2e0b0261e390a974d419c163039865d89919738b...e78b54eb5a1a00538a003acd431df71b9e4c97e6

update qemu emulators

---

Dockerfile

fixes #1946 #docker/buildx#511
Seccomp 2.4.2 with https://github.com/seccomp/libseccomp/commit/bf747eb21e428c2b3ead6ebcca27951b681963a0 is needed for new time64 syscalls not to error in applications.
The result is very hacky because debian does not provide compatible packages for s390x/pcc64le (yet?). Hopefully, this can all be removed and moved to alpine with https://github.com/tonistiigi/xx/pull/14 but there is still some work to do with that(namely lld doesn't work for s390x) and not sure when I'll have time to complete it.

fix seccomp compatibility in 32bit arm

---

util/resolver/authorizer.go

resolver: avoid error caching on token fetch

---

client/client_test.go
solver/llbsolver/ops/file.go

Cache mismatch can happen if fileop switches input indexes
between different actions.
To minimize breaking cache for existing users I try to detect common
order of input indexes. If the order is correct then indexes are not put
into the checksum for backward compatibility.
@aluzzardi 

fileop: fix checksum to contain indexes of inputs

---

frontend/dockerfile/instructions/bflag.go
frontend/dockerfile/instructions/bflag_test.go
frontend/dockerfile/instructions/commands.go
frontend/dockerfile/instructions/parse.go
frontend/dockerfile/instructions/parse_test.go

- relates to https://github.com/moby/moby/pull/41912 "builder: produce error when using unsupported Dockerfile option"
- relates to https://github.com/moby/moby/issues/41911 [20.10] Classic builder silently ignores unsupported Dockerfile command flags
The FlagsUsed contains a list of flags that were used, which allows the classic (non-buildkit) builder in dockerd to produce an error when non-supported options are used in a Dockerfile.
This is a short-term solution; a more permanent solution will be to keep track of which version of the Dockerfile syntax is supported, and to have the classic builder pass the maximum supported version of the syntax.

frontend/dockerfile: add RunCommand.FlagsUsed field

---

cmd/buildkitd/config/config.go
cmd/buildkitd/main_containerd_worker.go
cmd/buildkitd/main_oci_worker.go
executor/containerdexecutor/executor.go
executor/oci/spec.go
executor/oci/spec_unix.go
executor/oci/spec_windows.go
executor/runcexecutor/executor.go
go.mod
worker/containerd/containerd.go
worker/containerd/containerd_test.go
worker/runc/runc.go
worker/runc/runc_test.go

this forward-ports this change to master from the v0.8 release branch (change was included in docker 20.10.3)
Set's an apparmor profile on the OCI spec if one is configred on the worker.
Adds selinux labels to containers (only added if selinux is enabled on the system).
This assumes that the specified apparmor profile is already loaded on the system and does not try to load it or even check if it is loaded.
SELinux support requires the `selinux` build tag to be added. Likewise, `runc` would require both the `apparmor` and `selinux` build tags.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
Vendored go-selinux to v1.8.0
Fixed tests
(cherry picked from commit 68bb095353c65bc3993fd534c26cf77fe05e61b1)
Signed-off-by: Sebastiaan van Stijn …

[master] Add support for apparmor/selinux

---

Dockerfile

backport of https://github.com/moby/buildkit/pull/1955
fixes #1946 #docker/buildx#511
Seccomp 2.4.2 with https://github.com/seccomp/libseccomp/commit/bf747eb21e428c2b3ead6ebcca27951b681963a0 is needed for new time64 syscalls not to error in applications.
The result is very hacky because debian does not provide compatible packages for s390x/pcc64le (yet?). Hopefully, this can all be removed and moved to alpine with https://github.com/tonistiigi/xx/pull/14 but there is still some work to do with that(namely lld doesn't work for s390x) and not sure when I'll have time to complete it.

[v0.8 backport] fix seccomp compatibility in 32bit arm

---

client/client_test.go
solver/llbsolver/ops/file.go

backport of https://github.com/moby/buildkit/pull/1965
Cache mismatch can happen if fileop switches input indexes
between different actions.
To minimize breaking cache for existing users I try to detect common
order of input indexes. If the order is correct then indexes are not put
into the checksum for backward compatibility.

[v0.8 backport] fileop: fix checksum to contain indexes of inputs

---

frontend/dockerfile/instructions/bflag.go
frontend/dockerfile/instructions/bflag_test.go
frontend/dockerfile/instructions/commands.go
frontend/dockerfile/instructions/parse.go
frontend/dockerfile/instructions/parse_test.go

backport of https://github.com/moby/buildkit/pull/1954
- relates to https://github.com/moby/moby/pull/41912 "builder: produce error when using unsupported Dockerfile option"
- relates to https://github.com/moby/moby/issues/41911 [20.10] Classic builder silently ignores unsupported Dockerfile command flags
The FlagsUsed contains a list of flags that were used, which allows the classic (non-buildkit) builder in dockerd to produce an error when non-supported options are used in a Dockerfile.
This is a short-term solution; a more permanent solution will be to keep track of which version of the Dockerfile syntax is supported, and to have the classic builder pass the maximum supported version of the syntax.

[v0.8 backport] frontend/dockerfile: add RunCommand.FlagsUsed field

---

Dockerfile
solver/llbsolver/ops/exec_binfmt.go

backport of https://github.com/moby/buildkit/pull/1953
Fixes bugs with executing scripts with shebang and adds 386 emulator.
https://github.com/tonistiigi/binfmt/compare/2e0b0261e390a974d419c163039865d89919738b...e78b54eb5a1a00538a003acd431df71b9e4c97e6

[v0.8 backport] update qemu emulators

---

frontend/dockerfile/builder/build.go

This sets the platform prefix based on the `BUILDKIT_MULTI_PLATFORM`
value (if set).  This is similar to the changes here in
docker/buildx@7f58ad45fab9ab0e8c961cac6599ce0e8b100ad2
This is in relation to @tonistiigi's comment here https://github.com/docker/buildx/pull/467#issuecomment-744088189
I'm not sure if this is the right place.

Support BUILDKIT_MULTI_PLATFORM arg in Dockerfile

---

frontend/gateway/container.go
solver/llbsolver/errdefs/exec.go
solver/llbsolver/ops/exec.go
solver/llbsolver/ops/file.go
solver/result.go
solver/scheduler.go
solver/scheduler_test.go
solver/types.go
worker/result.go

fix #1958
fixes / addresses https://github.com/docker/for-linux/issues/1203
Issues:
- Cache mount may not be committed because it is shared between multiple vertexes and multiple builds. I think we should make it more type-safe, eg. if `ExecError` dealt with `cache.Ref` instead of `Result` it would have been clear that you can get an object like this from a cache mount. Or any operation with a mutable reference that has been committed should fail right away. We could try a more complicated approach later, eg try to wait for error handler to get full ownership of mount ref by checking that everything else has released it. In practical cases, I think the current is ok and when a debug container creates a cache mount it comes back with the same state anyway if nothing else is changing the …

Fix reference count issues on typed errors with mount references

---

util/resolver/resolver.go

partly fixes #1984
Make sure to always use the same tcp connection pool. Otherwise, if some builds pull tens of images in parallel client/server can't handle that.
This should also be capped in the higher level because currently still all layers start showing progress instantly, even if most are waiting on the connection pool. Ideally, we could start showing progress from the first byte but not sure how easy/clean that is to implement.

resolver: fix tcp connections limit

---

source/git/gitsource.go

fix https://github.com/docker/build-push-action/issues/300
When setting the token for the request scope it to the main URL only so that it is not used for fetching irrelevant submodules. If submodules don't understand the token they can fail the fetch.
This is documented in https://git-scm.com/docs/git-config#Documentation/git-config.txt-httplturlgt
@crazy-max @MarshalX

git: set token only for main remote access

---

frontend/dockerfile/docs/syntax.md
frontend/gateway/container.go
solver/llbsolver/errdefs/exec.go
solver/llbsolver/ops/exec.go
solver/llbsolver/ops/file.go
solver/result.go
solver/scheduler.go
solver/scheduler_test.go
solver/types.go
worker/result.go

backports of:
- https://github.com/moby/buildkit/pull/1916 dockerfile/docs: fix frontend image tags
- fixes https://github.com/moby/buildkit/issues/1907
- ~https://github.com/moby/buildkit/pull/1986 resolver: fix tcp connections limit~ (see https://github.com/moby/buildkit/issues/1988#issuecomment-782508241 and https://github.com/moby/buildkit/pull/1989)
- https://github.com/moby/buildkit/pull/1963 Fix reference count issues on typed errors with mount references
- fixes https://github.com/moby/buildkit/issues/1958 errors on releasing mounts with typed execerror refs
- fixes / addresses https://github.com/docker/for-linux/issues/1203 invalid mutable ref when using shared cache mounts
```
git cherry-pick -s -S -x 1218e37c239c1d6d27446d748a49abc6434e7dee
git cherry-pick -s -S -x …
```

[v0.8 backport] Fix reference count issues on typed errors, docs: fix frontend image tags 

---

source/git/gitsource.go

backport of https://github.com/moby/buildkit/pull/1987
fix https://github.com/docker/build-push-action/issues/300
When setting the token for the request scope it to the main URL only so that it is not used for fetching irrelevant submodules. If submodules don't understand the token they can fail the fetch.
This is documented in https://git-scm.com/docs/git-config#Documentation/git-config.txt-httplturlgt

[v0.8 backport] git: set token only for main remote access

---

cache/remotecache/v1/utils.go

fix #1992
Moby image exporter does not remove empty layers causing inline cache to go out of sync. This allows behavior to be configured so it can be turned off in moby.
Regression from 85dd12d875f98e2e2fac819b0eb8abdbf0d35f77
There is still an issue that empty layers (ones optimized after differ, not metadata commands) can get out of sync in the history array of the image after cache import. Don't really know what to do about it as there is no information to determine that a `RUN` command didn't create a layer without running it.

allow skipping empty layer detection on cache export

---

cache/remotecache/v1/utils.go

(cherry picked from commit 29af1397e204096b4b1a9e4a6dcf86f47028d573)
Backport of #1993

[v0.8] allow skipping empty layer detection on cache export

---

codecov.yml

Disable Codecov [annotations](https://docs.codecov.io/docs/github-checks-beta#yaml-configuration-for-github-checks-and-codecov).
cc @tonistiigi 

Disable GitHub Checks Patch Annotations

---

util/apicaps/caps.go

This is needed for https://github.com/docker/buildx/pull/535 so that client can check for a cap in remote set even if it has not been initialized in the vendored code.

caps: add contains method

---

util/resolver/retryhandler/retry.go

In Earthly, we are seeing frequent errors [like these](https://github.com/earthly/earthly/runs/2179559918#step:6:2759) in large builds. This change helps reduce such instances.
```
Error: failed to load cache key: failed to do request: Head https://registry-1.docker.io/v2/alpine/git/manifests/v2.30.1: net/http: TLS handshake timeout
```
This is the net/http error type produced in such instances: https://golang.org/src/net/http/transport.go#L2835, which implements the `net.Error` interface. This catches other similar situations too, by matching on `net.Error`.
Signed-off-by: Vlad A. Ionescu <vladaionescu@users.noreply.github.com>

Retry on temporary network failures

---

solver/llbsolver/file/backend.go

I saw these, and there was no comment in the code explaining if there was a reason for this; these were added in 2be999ba52ec6c3e75d3514b4228b23f67bc34c7 (https://github.com/moby/buildkit/pull/809), but couldn't find a mention about these particular lines in the review comments, and I couldn't think of a special reason for it ':-)

solve: remove duplicate filepath.Join

---

util/contentutil/copy.go
util/imageutil/config.go
util/progress/logs/logs.go
util/resolver/retryhandler/retry.go

Some registries can be flaky and return intermittent 5xx errors. This
change allows those errors to be retried, similarly to network-level
errors.
Note that this needs the upstream containerd fix
https://github.com/containerd/containerd/pull/5276 to work reliably.
This was tested with a registry that was modified to return 504 on every
other manifest PUT. Without the change, exports to the registry fail
every other attempt.  With the change and the related containerd change,
exports to the registry always succeed.
Signed-off-by: Aaron Lehmann <alehmann@netflix.com>

Add retry on image push 5xx errors

---

session/auth/authprovider/tokenseed.go

authprovider: allow errors on seed unmarshal

---

cache/metadata/metadata.go

fix https://github.com/moby/buildkit/issues/1913
Mentioned in https://github.com/moby/buildkit/issues/1913#issuecomment-751909103 that this may require pooling but since atm it is only used in contentcache that already has own lru cache, extra pooling isn't needed for this case.
@vladaionescu 

metadata: clone external data

---

client/llb/source.go
util/gitutil/git_protocol.go
util/gitutil/git_protocol_test.go

- the git protocol detection is required by buildx, and should reside in
a seperate exported gitutil package. (see https://github.com/docker/buildx/pull/578 )

Move git protocol detection into seperate util

---

api/services/control/control.proto

Lots of client implementations have been already depending on the
current controller API, so the API should not be considered experimental.

api/services/control: move out of experimental

---

Dockerfile
util/testutil/integration/containerd.go
util/testutil/integration/oci.go
util/testutil/integration/sandbox.go

Carry https://github.com/moby/buildkit/pull/2001 , with testutil fix (https://github.com/moby/buildkit/pull/2017#issuecomment-797302456)

[Carry 2001] Dockerfile: update containerd to 1.4.3  + fix testutil

---

worker/containerd/containerd.go
worker/worker.go

e.g.,
```
Labels:
org.mobyproject.buildkit.worker.containerd.namespace:   buildkit
org.mobyproject.buildkit.worker.containerd.uuid:        343cfb49-cce9-453f-b21c-e5d22ca2cb47
org.mobyproject.buildkit.worker.executor:               containerd
org.mobyproject.buildkit.worker.hostname:               suda-ws01
org.mobyproject.buildkit.worker.snapshotter:            overlayfs
```
Planned to be used by nerdctl to detect whether containerd exporter can be used

worker/containerd: expose namespace and UUID as labels

---

cache/contenthash/checksum.go
cache/contenthash/checksum_test.go
frontend/dockerfile/dockerfile_test.go

fixes #2008
While we generally ignore the basename in this layer, for wildcards
there in no other place to add the basename to the checksum as they
can not be resolved earlier. Before the basename that was in the
checksum was the wildcard itself, so if the wildcard remained same,
content remained same but the file where wildcard pointed to was
renamed, the cache was not invalidated.
Unfortunately, this change breaks cache for all copy commands that
use a wildcard.

contenthash: include basename in content checksum for wildcards

---

source/git/gitsource.go

As reported on https://lgtm.com/projects/g/moby/buildkit/alerts/?mode=list https://lgtm.com/projects/g/moby/buildkit/rev/c47972dc5a9e2f4fc0a58d299b6f096161203fbb (can't seem to get a permalink)
Makes sure to never assign to a `nil` `v` (possible if `err != nil`).

Fix potential crash on nil value

---

client/client_test.go
solver/llbsolver/ops/exec.go

A bug in `cloneExecOp` prevented mounts from being included in the digest
computed for the `execOp` cache map. This could lead to an exec being
wrongly cached when a different mount was used for a subsequent
execution.
Repro case:
https://gist.github.com/aaronlehmann/cfeaefc028df8127fb85b9b5f9125f2d
In this example, pass2 should generate an empty diff because the /from
and /to mounts are the same busybox image. But before the fix, it uses
the cached result from pass1 (with different mounts) instead.
Signed-off-by: Aaron Lehmann <alehmann@netflix.com>

Fix missing mounts in execOp cache map

---

util/resolver/authorizer.go

Some registries (notably Quay) issue tokens that expire without providing an `expires in` value in the authorization payload. Therefore, if a token produces a 401, we should remove it and re-fetch.
I admit this is a hack... likely incomplete and/or the wrong way to approach it. Any guidance would be great. The point is that we need to avoid using tokens that may have expired.
This (or a better approach) should resolve https://github.com/moby/buildkit/issues/2055 (and also thereby resolve https://github.com/earthly/earthly/issues/890, too)

Remove potentially expired tokens

---

source/git/gitsource.go
source/git/gitsource_test.go
source/git/redact_credentials.go

this is to prevent errors such as
failed to fetch remote https://user:password@github.com/user/private-repo-failure.git: exit status 128
from leaking the password; now it will be displayed like:
failed to fetch remote https://user:xxxxx@github.com/user/private-repo-failure.git: exit status 128

Redact credentials from URLs before returning errors

---

README.md
cmd/buildctl/build.go
cmd/buildctl/build_test.go
cmd/buildctl/buildctl_test.go

Output build metadata (such as image digest) to a file based on a flag to `buildctl`.
Fixes #1158.
```
buildctl build --frontend=dockerfile.v0 --metadata-file meta.json --local context=. --local dockerfile=.. --output type=image,name=foo:latest,push=false
```
```
{"containerimage.config.digest":"sha256:9ba453cfcf085ebe34d7e3bc0cd13e02038361693a53d8663ddca8f83e26447d","containerimage.digest":"sha256:475f3a5ec8513c157acc20aacf3c872afb3b508ed40f9e9fb519d31897b7a3f0","image.name":"foo:latest"}
```
@tonistiigi @AkihiroSuda This is based on the comments from #1315.

Add --metadata-file flag to output build metadata

---

Dockerfile

Golang wrapper tag is not being used anymore and was replaced with regular xx v2

Dockerfile: don't use wrong tag for xx

---

frontend/dockerfile/dockerfile2llb/convert_runmount.go
frontend/dockerfile/dockerfile_mount_test.go
frontend/dockerfile/instructions/commands.go
frontend/dockerfile/instructions/commands_runmount.go

This PR adds support for variable expansion in RUN mounts.
Resolves https://github.com/moby/buildkit/issues/815
Caveats:
- `from` expansion is not supported.
- Expansion is not supported in `ONBUILD RUN` commands (I don't even think mounts work there).

feat(run-mount): add support for variable expansion

---

hack/install-buildx

relates to https://github.com/moby/moby/pull/41949 https://github.com/moby/moby/pull/41949#discussion_r566371210
With this patch:
PREFIX=$(pwd)/foo/bar VERSION=v0.5.0 sh -c ./install-buildx
Installing buildx v0.5.0 as /Users/sebastiaan/Projects/test/test_buildx_install/foo/bar/bin/buildx
+ mkdir -p /Users/sebastiaan/Projects/test/test_buildx_install/foo/bar/bin
+ rm -f /Users/sebastiaan/Projects/test/test_buildx_install/foo/bar/bin/buildx.download
+ curl -f -L -o /Users/sebastiaan/Projects/test/test_buildx_install/foo/bar/bin/buildx.download https://github.com/docker/buildx/releases/download/v0.5.0/buildx-v0.5.0.darwin-amd64
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   634  100   634    0     0   2313 …

hack/install-buildx: allow overriding variables

---

util/progress/progressui/printer.go

This doesn't carry much information unless debugging LLB layer and is confusing.
@thaJeztah 

progressui: don't print vertex digest

---

client/client_test.go
frontend/gateway/container.go
solver/llbsolver/ops/exec.go

- Currently buildkit & containerd depend on runc rc93
- Runc rc94 brings in commit: https://github.com/opencontainers/runc/commit/2192670a2430054c1e539ca7a3bf0ddc43b0bc3d
- Relative mountpoints used to be treated as relative to root, but now fails at runtime
- Dockerfile frontend handles relative path mountpoints for the runmount
- Buildkit doesn't handle in the executor which means other frontends may encounter the `mount destination not absolute` error in runc rc94
- Executor should respect the execop cwd for relative mountpoints

Transform relative mountpoints for exec mounts in the executor

---

client/client_test.go
frontend/gateway/container.go
solver/llbsolver/ops/exec.go

pick #2123
There will probably not be another v0.8 release (runc security issue does not apply to buildkit directly) but pick for possible vendor update in Docker.
Signed-off-by: Edgar Lee <edgarl@netflix.com>
(cherry picked from commit a57ae2746fe679e8678d6ab5f61d19366b4c7b70)

[v0.8] Transform relative mountpoints for exec mounts in the executor

---

hack/dockerfiles/generated-files.Dockerfile
hack/update-generated-files
util/stack/stack.pb.go

This patch updates the script and Dockerfile to prevent issues when using go
modules.
The first change is to use a plain `git clone` instead of `go get -d` to download
the source. While (like "pre go-modules") `go get -d` won't *build* the binaries
when go modules are used, it *will* use go modules to download the package
(and dependencies); as a result:
- no git repository will be cloned in gopath
- go modules will be downloaded for "master" (not the version that we specify
to build)
Note: Once we update to Go 1.16, this script could be updated to use `go install <repo>@version`
The second change is an update to the `update-generated-files` script to detect
the correct version of google/protobuf to use from the `go.mod`'s  `replace` rule,
to make sure we generate (and verify) using the …

generated files: update google/protobuf v1.3.5, protoc v3.14.0 and fix install for go modules

---

session/sshforward/sshprovider/agentprovider.go
session/sshforward/sshprovider/agentprovider_unix.go
session/sshforward/sshprovider/agentprovider_windows.go

Use Windows OpenSSH agent named pipe as fallback SSH agent socket path when available.
Recognize named pipe paths when on Windows and use winio.DialPipe() to connect.
Existing functionality is not affected. Tested on both Windows and Ubuntu.
See issue #2124 for further details.

Support for Windows OpenSSH agent forwarding

---

go.mod
go.sum
vendor/github.com/docker/cli/cli/config/config.go
vendor/github.com/docker/docker/client/client.go
vendor/github.com/docker/docker/pkg/archive/archive.go
vendor/github.com/docker/docker/pkg/archive/archive_linux.go
vendor/github.com/docker/docker/pkg/archive/archive_other.go
vendor/github.com/docker/docker/pkg/signal/signal.go
vendor/github.com/ishidawataru/sctp/.travis.yml
vendor/github.com/ishidawataru/sctp/sctp_linux.go
vendor/modules.txt

- pkg/signal: ignore SIGURG on all platforms
- pkg/archive: use v2 capabilities in layer archives
- update ishidawataru/sctp to fix possible socket leak when bind fails
docker/cli:
- config: print deprecation warning when falling back to ~/.dockercfg

go.mod: update docker and docker cli to v20.10.7

---

cache/manager.go

Fix #2153
It should be possible for this to happen when gc/prune runs in the middle of `Search` and `Get` calls. Not found error was already handled but not cleanly. The code that causes the panic was added later, previously there was no panic for this case but if there was a fallback option only one search result was tried.

cache: fix possible nil dereferences

---

solver/pb/caps.go
source/git/gitsource.go
source/git/gitsource_test.go
source/gitidentifier.go

fixes #1684
wip: trying to see if I can also add backward compatibility to support old buildkit versions in https://github.com/moby/buildkit/compare/tonistiigi:git-subdir-wip. Looks tricky but may be possible.
@crazy-max @chris-crone

git: support subdir component

---

.github/CONTRIBUTING.md
hack/test
util/testutil/integration/run.go

Fixes for the mirror handling in tests. When `TEST_KEEP_CACHE=1` is set no requests should be made to external registries between invocations.

test: fix mirror cache handling

---

cmd/buildkitd/config/config.go
util/push/push.go
util/resolver/resolver.go

relates to https://github.com/moby/moby/pull/42465#issuecomment-855086782
This allows using the resolver package without having to import the buildkit daemon configuration.
~Aliasses were added in the config package for backward compatibility, and to allow for the config package to diverge / extend the internal type if needed.~

move RegistryConfig to resolver package

---

.github/workflows/build.yml
Dockerfile
examples/buildkit0/buildkit.go
examples/buildkit1/buildkit.go
examples/buildkit2/buildkit.go
examples/buildkit3/buildkit.go
examples/nested-llb/main.go
frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
hack/dockerfiles/generated-files.Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/vendor.Dockerfile
source/git/redact_credentials_go114.go
util/archutil/Dockerfile

depends on https://github.com/moby/buildkit/pull/2146
relates to https://github.com/moby/moby/pull/40353 https://github.com/moby/moby/pull/40353#issuecomment-849982605
This updates all occurrences of Go 1.13 to Go 1.16; also updated the code that's used to redact credentials in URLs to use the Go implementation (based on https://github.com/golang/go/commit/e3323f57df1f4a44093a2d25fee33513325cbb86, it's available in Go 1.15 and up).

update to go 1.16

---

go.sum

The vendor validation CI did run on an up-to-date merge-base in #2144 and broke master.

vendor: fix broken gosum

---

docs/stargz-estargz.md

Since https://github.com/moby/buildkit/pull/1733, OCI worker + Stargz Snapshotter supports `~/.docker/config.json`-based auth. This commit fixes the doc about it.

Fix doc about Stargz Snapshotter and registry authentication

---

.golangci.yml
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_heredoc_test.go
frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/docs/syntax.md
frontend/dockerfile/instructions/commands.go
frontend/dockerfile/instructions/parse.go
frontend/dockerfile/instructions/parse_heredoc_test.go
frontend/dockerfile/instructions/parse_test.go
frontend/dockerfile/parser/parser.go
frontend/dockerfile/parser/parser_heredoc.go
frontend/dockerfile/parser/parser_heredoc_test.go
frontend/dockerfile/parser/parser_test.go
frontend/dockerfile/release/labs/tags

relates to https://github.com/moby/moby/issues/34423
As mentioned in #2121, I've been making progress towards implementing heredocs in Dockerfiles, and thought it might be time to open a PR for it :tada: 
I've essentially got all the functionality I think we'd need before wanting to merge, though I'm sure there's some fixes/tests to write before that.
Things that definitely need resolving before a merge is really possible:
I'd really appreciate any feedback anyone has on the current design and implementation!

Dockerfile heredocs

---

cache/manager.go

fix #2157
fix #2061
`remove()` needs to be called while holding the manager lock (even documented). Afaics the reason prune releases manager lock early is to avoid holding it for the potentially slow size calculation. This PR moves size calculation to a separate step to avoid that.

cache: avoid concurrent maps write on prune

---

cache/metadata/metadata.go

fix #2111
The locks usage is mixed up because two locks separate locks
are actually needed. With a specific lock, calls to SetValue
can be protected.

metadata: hold lock on storageitem update

---

frontend/dockerfile/dockerfile2llb/convert.go

When the wrong image name is used in Dockerfile and the registry responds with an error the source mapping with the Dockerfile `FROM` line was not kept.
Because it is such a common error and contained doesn't include image name in the error I also added extra wrapping for that.

dockerfile: ensure config resolve errors keep source location

---

Dockerfile
util/resolver/retryhandler/retry.go

Remove workarounds that were needed before go1.16

Dockerfile: remove nsswitch as default in go1.16

---

cmd/buildkitd/main.go
cmd/buildkitd/main_oci_worker.go
solver/llbsolver/mounts/mount.go
util/entitlements/security/security_linux.go

This utility was moved to a separate package, which has no dependencies.
related: https://github.com/moby/moby/pull/42536

replace uses of deprecated containerd/sys.RunningInUserNS()

---

Dockerfile

fuse-overlayfs is available as an apk since Alpine 3.14.

 Dockerfile: install fuse-overlayfs from apk

---

client/llb/async.go
client/llb/async_test.go
client/llb/definition.go
client/llb/definition_test.go
client/llb/exec.go
client/llb/fileop.go
client/llb/llbbuild/llbbuild.go
client/llb/llbbuild/llbbuild_test.go
client/llb/meta.go
client/llb/resolver_test.go
client/llb/source.go
client/llb/state.go
examples/buildkit1/buildkit.go

This fixes async llb operations not having access to marshal constraints. Image sources meta resolver did not pick up platform from marshal. First two commits add this capability to library and third one fixes the platform issue.

llb: ensure meta resolver uses platform form constraints

---

cache/contenthash/checksum.go
client/client_test.go

Fix this panic when copying from an image with no layers:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xdd8c17]
goroutine 326 [running]:
github.com/moby/buildkit/cache/contenthash.(*cacheManager).Checksum(0xc0005ec030, 0x1682c00, 0xc000842140, 0x0, 0x0, 0xc0005d4023, 0x1, 0x0, 0x0, 0x0, ...)
/src/cache/contenthash/checksum.go:95 +0x37
github.com/moby/buildkit/cache/contenthash.Checksum(0x1682c00, 0xc000842140, 0x0, 0x0, 0xc0005d4023, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
/src/cache/contenthash/checksum.go:59 +0xd5
github.com/moby/buildkit/solver/llbsolver.NewContentHashFunc.func1.1(0x0, 0x4425d6)
/src/solver/llbsolver/result.go:59 +0x20a
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00056a360, …
```

Avoid nil pointer dereference when copying from image with no layers

---

executor/containerdexecutor/executor.go

fixes #2133
The closing of the IO was not synchronized for containerd processes (both Exec and Run).   The tests failed ~5% of the time with unexpected output from previous Exec calls because we reuse the buffers but they continued to be written to after the `Reset` calls.  We just need to wait for the IO to complete before returning from Exec/Run.  I ran the test 1000 times in a row with no errors:
```
TESTPKGS="./worker/containerd" TESTFLAGS="-v --count=1000 --parallel=6 --failfast --timeout=120m -run TestContainerdWorkerIntegration/TestContainerdWorkerExec$" ./hack/test integration
```

ensure containerd io is complete and closed before returning

---

util/flightcontrol/flightcontrol.go
util/flightcontrol/flightcontrol_test.go

Avoid contention between a lot of calls coming in with the same key. This should reduce/remove to occasional timeout error that still pop up sometimes. It's possible go1.16 update changed the timings to make timeout errors more likely.
I've changed the retry logic for the default path. The timing is changed a bit and you can get a response even if the shared function already just completed but I don't think this is visible for the caller side.
Also increased timeout(now only for error/cancel cases) because there has been no indication of a deadlock.
As follow-ups, I wonder if randomizing the backoff could help a bit. Maybe timeouts sometimes appear because competing goroutines get the same backoff and then compete again. Would really like to completely remove timeout as time-based checks …

flightcontrol: reduce contention between goroutines

---

cache/remotecache/export.go
exporter/containerimage/writer.go
exporter/local/export.go
exporter/oci/export.go
exporter/tar/export.go
solver/jobs.go
solver/llbsolver/solver.go
source/containerimage/pull.go
source/local/local.go
util/flightcontrol/flightcontrol.go
util/progress/controller/controller.go
util/progress/logs/logs.go
util/progress/multireader.go
util/progress/progress.go
util/progress/progress_test.go
util/pull/pullprogress/progress.go
util/push/push.go
worker/base/worker.go

fixes #2112
To prevent leaks with `Close` not being called on `progress.Writer` there is an expectation that everywhere we `Write` to a `progress.Writer` we should also be calling `Close` when the writing is complete.  I looked through the code and currently the only occurrence of `Write` without `Close` was in the `progress.Controller`. Moving the lifecycle management of the `progress.Writer` into the reference-counted implementation of the Controller fixes the leak.

[#2112] progress.Controller should own the progress.Writer to prevent leaks

---

frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile

fix #2206
Looks like this broke in #2037 with migration from debian to alpine.
@coryb 

dockerfile: fix git version detection

---

frontend/dockerfile/dockerfile_heredoc_test.go
frontend/dockerfile/instructions/parse.go
frontend/dockerfile/parser/parser.go
frontend/dockerfile/parser/parser_heredoc.go

This start to address some of #2170, extending heredoc support into the `ONBUILD` command. This pretty much just lets heredocs work exactly as expected when combined with `ONBUILD`.
```dockerfile
ONBUILD RUN <<EOF
echo "thing to do as on-build trigger"
EOF
```
With this structure, it should be possible to extend this in the future to `HEALTHCHECK`, however, we'd need some support for heredocs in `CMD` (which I think works nicer in a separate PR, since it's actually unrelated to this).

Add support for heredocs in the ONBUILD command

---

client/client_test.go
client/llb/source.go
frontend/dockerfile/builder/build.go
session/filesync/diffcopy.go
session/filesync/filesync.go
solver/pb/attr.go
solver/pb/caps.go
source/identifier.go
source/local/local.go

fixes #1368
Allows new `llb.Differ` property to configure what algorithm should be used when transferring file changes. Dockerfile frontend is updated to not trust metadata comparison for Dockerfile/dockerignore transfer. This can be extended in the future with some content-based comparison for better precision.

Allow none differ on local source to avoid false Dockerfile matches

---

client/client_test.go
frontend/dockerfile/dockerfile_test.go
solver/llbsolver/ops/exec.go
util/grpcerrors/grpcerrors.go

Before:
```
------
> [st3 2/2] RUN sleep 1 && echo foobar && exit 1:
------
Dockerfile:9
7 |     
8 |     from alpine as st3
9 | >>> run sleep 1 && echo foobar && exit 1
10 |     
11 |     from scratch
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c sleep 1 && echo foobar && exit 1]: exit code: 1
```
After:
```
------
> [st3 2/2] RUN sleep 1 && echo foobar && exit 1:
#10 2.308 foobar
------
Dockerfile:9
7 |     
8 |     from alpine as st3
9 | >>> run sleep 1 && echo foobar && exit 1
10 |     
11 |     from scratch
error: failed to solve: process "/bin/sh -c sleep 1 && echo foobar && exit 1" did not complete successfully: exit code: 1
```
Expecting tests that …

Improve build errors and remove useless grpc prefix

---

util/progress/progressui/display.go
util/progress/progressui/printer.go

On "plain" progress mode logs are printed as they appear. That means that when error happens the stderr of the process containing helpful logs might have been already printed before and the user would need to scroll up from the error to find this.  This adds a buffer that keeps last logs for all vertexes, if an error happens that buffer is printed out in the error summary so it always appears in the end of the build.

progressui: print logs for failed step as summary in plain mode

---

frontend/dockerfile/parser/parser.go
frontend/dockerfile/parser/parser_heredoc_test.go
frontend/dockerfile/shell/lex.go

Previously, heredoc names have been restricted to simple alphanumeric strings. However, heredocs should support much more complex use-cases, including quoting anywhere, as well as allowing special symbols like `.` for easily expressing file extensions.
This patch adds support for these more complex cases, by using the shell lexer to parse each heredoc name. Additionally, we include improvements to the lexer to optionally preserve escape tokens to avoid problems when lexing words that have already been lexed before.
Not quite sure how I missed this before in the first iteration, since all shells support some really complex word rules for the naming of heredocs, but now there's some tests to catch these weirder cases. The main one of use is doing something like `COPY <<file.txt /` which …

Improve heredoc parsing to allow more generic shell-words

---

frontend/dockerfile/dockerfile2llb/convert.go

This resolves #2167, following up on providing better progress messages for heredoc commands.
To summarize:
- File creation in a scratch container gets a nice `internal` progress message
- Simple heredocs (fake and shebang, but not complex ones) get a summary of the first line of the heredoc
- The commit message for copied files now includes a heredoc (instead of hiding it)
Not quite sure whether the shortening looks ok, but I kind of like it :smile: You can get messages like:
```
RUN <<EOF (echo $(whoami) >> cmd1)
```
or
```
RUN <<EOF (#!/usr/bin/env python3...)
```

Improve progress and history messages for heredoc-related commands

---

cache/blobs.go
cache/manager.go
cache/manager_test.go
cache/refs.go
solver/llbsolver/bridge.go

Finalize was only used outside the cache package in one place, which
called it with the commit arg set to false. The code path followed
when commit==false turned out to essentially be a no-op because
it set "retain cache" to true if it was already set to true.
It was thus safe to remove the only external call to it and remove it
from the interface. This should be helpful for future efforts to
simplify the equal{Mutable,Immutable} fields in cacheRecord, which exist
due to the "lazy commit" feature that Finalize is tied into.

Remove unneeded Finalize method from ImmutableRef.

---

solver/llbsolver/file/refmanager.go

Small thing but probably worth fixing. Didn't notice in real world, just while looking at the code.

Fix ref leak if fileop ref fails to mount.

---

cache/contenthash/checksum.go
cache/manager.go
frontend/gateway/gateway.go
session/secrets/secrets.go

I noticed this when building a Dockerfile that failed because a file didn't
exist, so went through error messages that looked like they had a duplicate
"not found" in the output;
[+] Building 0.9s (6/9)
=> [internal] load build definition from Dockerfile                0.2s
=> => transferring dockerfile: 306B                                0.0s
=> [internal] load .dockerignore                                   0.1s
=> => transferring context: 2B                                     0.0s
=> [internal] load metadata for docker.io/library/alpine:latest    0.0s
=> CACHED [1/5] FROM docker.io/library/alpine                      0.0s
=> [internal] load build context                                   0.6s
=> => transferring context: 701B                                   0.5s
=> ERROR [2/5] ADD …

Remove duplicate "not found" from some error messages

---

README.md
cache/blobs.go
cache/converter.go
cache/refs.go
cache/remote.go
client/client_test.go
exporter/containerimage/export.go
exporter/containerimage/writer.go
exporter/oci/export.go
solver/llbsolver/result.go
solver/llbsolver/solver.go
vendor/github.com/containerd/containerd/images/converter/converter.go
vendor/github.com/containerd/containerd/images/converter/default.go
vendor/github.com/containerd/containerd/images/converter/uncompress/uncompress.go
vendor/modules.txt
worker/cacheresult.go
worker/result.go

resolves: https://github.com/moby/buildkit/issues/1911
Currently, exporter's `compression` flag is applied only to newly created layers. So the exported image can be a mix of several compression types (uncompressed and gzip) even if the `compression` type is specified.
It would be great if we can specify the compression type of all layers of the finally exported image.
This commit introduces a new exporter flag `force-compression` enabling to specify the compression type of the exported layers. If layers don't match the type specified by `compression` option, they are forcefully converted to the targeting type.
In addition to making sure the final compression type, this flag, in the future, will also help users to quickly catch up and try with updates & trends on novel image layer formats …

exporter: Enable to specify the compression type for all layers of the finally exported image

---

cmd/buildctl/main.go
cmd/buildkitd/main.go

Close #2026 
Add full timestamp to logs like below.
```
INFO[2021-07-06T23:53:12+09:00] auto snapshotter: using overlayfs
WARN[2021-07-06T23:53:12+09:00] using host network as the default
```
Before
```
INFO[0000] auto snapshotter: using overlayfs
WARN[0000] using host network as the default
```
This is my first PR. I'm sorry if I'm inadequate.

Add full timestamp to logs

---

source/git/gitsource.go
source/git/gitsource_test.go
source/gitidentifier.go
source/gitidentifier_test.go

carry #2011
fix moby/moby#41914
@LeviHarrison

[carry] Automatically detect default git branch

---

frontend/dockerfile/builder/build.go
frontend/dockerfile/dockerfile2llb/convert.go
frontend/dockerfile/dockerfile_mount_test.go
frontend/dockerfile/dockerfile_test.go
frontend/dockerfile/instructions/bflag.go
frontend/dockerfile/instructions/commands_runmount.go
frontend/dockerfile/instructions/parse.go
frontend/dockerfile/instructions/parse_test.go
frontend/dockerfile/parser/parser.go
frontend/dockerfile/parser/split_command.go
go.mod
go.sum
solver/llbsolver/bridge.go
util/suggest/error.go
vendor/github.com/agext/levenshtein/.gitignore
vendor/github.com/agext/levenshtein/.travis.yml
vendor/github.com/agext/levenshtein/DCO
vendor/github.com/agext/levenshtein/LICENSE
vendor/github.com/agext/levenshtein/MAINTAINERS
vendor/github.com/agext/levenshtein/NOTICE
vendor/github.com/agext/levenshtein/README.md
vendor/github.com/agext/levenshtein/go.mod
vendor/github.com/agext/levenshtein/levenshtein.go
vendor/github.com/agext/levenshtein/params.go
vendor/github.com/agext/levenshtein/test.sh
vendor/modules.txt

Detects mistyped:
- instructions
- stage names
- flags
- mount keys
- mount types

dockerfile: add suggestions to how to fix certain errors

---

cache/manager.go
cache/manager_test.go

GetByBlob checks to see if there are any other blobs with the same
(uncompressed) ChainID and, if so, reuses their unpacked snapshot if it
exists.
The problem is if this code finds a match, it was trying to get the
matching record, but couldn't do so when the match is lazy because the
caller doesn't necessarily have descriptor handlers setup for it.
This commit changes the behavior to just ignore any match with the same
ChainID that's also lazy as they just aren't usable for the
snapshot-reuse optimization.
Fixes #2226

Ignore missing providers for blobs w/ same chainid.

---

cmd/buildkitd/main.go
util/log/log.go

Set `log.G` with a `GetLogger` with Fields `traceID` and `spanID` when tracing exists.
example image `docker.io/morlay/buildkit:log-with-tracing`
logs in buidlkit will be

log should with traceID and spanID

---

solver/llbsolver/file/user_linux.go

When running a ``WORKDIR`` instruction, buildkit will create that folder and chown it to the currently set user. For this, it will try to read the ``/etc/passwd`` file to get the proper UID, and if that user is not found in the file, the root user will be considered as the owner.
However, Windows images do not have that file, which will result in an error while building the image. We can consider not finding
the ``/etc/passwd`` file as the same as not finding the user in the file, which would solve this issue.
Fixes: https://github.com/docker/buildx/issues/378

Skips getting UID/GUID if passwd/group file is not found

---

cache/opts.go
cache/remote.go
cache/remotecache/export.go
cache/remotecache/local/local.go
cache/remotecache/registry/registry.go
source/containerimage/pull.go
util/contentutil/copy.go
util/contentutil/copy_test.go
util/contentutil/fetcher_test.go
util/imageutil/config.go
util/pull/pull.go
util/push/push.go
util/resolver/retryhandler/retry.go

This is a safer alternative until we figure out why
`http.Transport` based limiting fails.
Some connections like cache export/import do not have a
domain key atm and these connections use a global pool.
Previous attempt https://github.com/moby/buildkit/pull/1986
@robtaylor @michaelhelmick

add per domain semaphore to limit concurrent connections

---

cache/remotecache/gha/gha.go
go.mod
go.sum
vendor/github.com/tonistiigi/go-actions-cache/cache.go
vendor/modules.txt

Allows replacing `http.DefaultClient` with `tracing.DefaultClient`

vendor: update go-actions-cache with custom client support

---

.github/workflows/build.yml

Fixes #2230
This is a new matrix for our tests to reduce build time by splitting up with the used workers. The number of runners deployed is quite substantial (37 now and 7 before) but we save about 17 minutes with this.
Will continue to work on it to reduce the number of runners and see if we can save that much time.
cc @tonistiigi 

Enhance test matrix

---

source/containerimage/pull.go

fix dropped pull progress output due to canceled context

---

cache/remotecache/registry/registry.go
util/contentutil/copy.go
util/imageutil/config.go
util/pull/pull.go
util/push/push.go
util/resolver/limited/group.go
util/resolver/retryhandler/retry.go

closes #2257
The previous implementation #2247 had many issues. Eg. on fetch, even if
the data already existed and no remote connections were needed
the request would still be waiting in the queue. Or if two fetches
of the same blob happened together they would take up two places in the queue
although there was only one remote request.
The second commit adds one extra connection to high-priority requests as described in #2257 .
Third commit fixes resuming incomplete downloads if there is previous data. Looks
like this broke with lazy pulling support and data was always repulled. This also looked
weird in the progress output because progress saw previous data but numbers were not
moving as builder was repelling that data again.
@sipsma @aaronlehmann @AkihiroSuda

new implementation for limiting tcp connections 
