moby/buildkit

README.md
=> GitHub Actions cache docs

.github/workflows/build.yml
https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1
=> Bump to codecov/codecov-action v2

README.md
Since the addition of the GitHub Action cache exporter, there is some confusion for some users around the available options for each kind of exporter. This PR splits cache options doc for each exporter in their dedicated section.
=> Split cache options doc for each exporter

hack/dockerfiles/generated-files.Dockerfile
Looks like redirection on `github.com/google/protobuf` is not working anymore and redirects to https://github.com/google/protobuf.dart which fails on CI:
```
#10 [gobuild-base 3/6] RUN set -e; 	arch=$(echo amd64 | sed -e s/amd64/x86_64/ -e s/arm64/aarch_64/); 	wget -q https://github.com/google/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-${arch}.zip && unzip protoc-3.11.4-linux-${arch}.zip -d /usr/local
#10 ERROR: process "/bin/sh -c set -e; \tarch=$(echo $TARGETARCH | sed -e s/amd64/x86_64/ -e s/arm64/aarch_64/); \twget -q https://github.com/google/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-${TARGETOS}-${arch}.zip && unzip protoc-${PROTOC_VERSION}-${TARGETOS}-${arch}.zip -d /usr/local" did not complete successfully: exit code: 8
```
Moved to …
=> Fix protoc link

util/tracing/otlptracegrpc/client.go
relates to https://github.com/docker/docker-ce-packaging/pull/561
This import comment caused compilation of buildx to fail if `GO111MODULE` was
set to `off`:
Without `GO111MODULE` set (but with `-mod=vendor`:
echo $GO111MODULE
export PKG=github.com/docker/buildx
export LDFLAGS="-X ${PKG}/version.Version=$(git describe --match 'v[0-9]*' --always --tags) -X ${PKG}/version.Revision=$(git rev-parse HEAD) -X ${PKG}/version.Package=${PKG}"
GOFLAGS=-mod=vendor go build -o bin/docker-buildx -ldflags "${LDFLAGS}" ./cmd/buildx
bin/docker-buildx version
github.com/docker/buildx v0.6.0 d9ee3b134cbc2d09513fa7fee4176a3919e05887
When setting `GO111MODULE=off`, it fails on the incorrect import path in the
vendored file (looks like GO111MODULE=on ignores import-path comments?):
export GO111MODULE=off …
=> util/tracing: remove incorrect import enforcing comment

client/build_test.go, frontend/gateway/gateway.go
While working with the gateway exec for debugging solves we noticed that security mode was getting dropped in the frontend gateway layer.  Adding a test to verify gateway exec with `SecurityModeInsecure`.
=> fix SecurityMode being dropped on gateway container Start

examples/systemd/buildkit.socket
The systemd default is 666, it seems.
https://www.freedesktop.org/software/systemd/man/systemd.socket.html
=> Set default socket permissions to 660

cache/contenthash/checksum.go, cache/contenthash/checksum_test.go
This adds a little extra testing around ** patterns, and adds a
(currently skipped) test for copying directories under symlinks (#2300).
It removes an extra call to `filepath.FromSlash` in `shouldIncludePath`
and an unused argument to that function.
=> Additional tests and cleanup for cache/contenthash

client/build_test.go, executor/containerdexecutor/executor.go, executor/containerdexecutor/executor_test.go, executor/runcexecutor/executor.go, frontend/gateway/gateway.go, frontend/gateway/grpcclient/client.go, frontend/gateway/pb/exit.go
This will allow clients to retrieve exit error codes returned during a
solve without parsing the error messages.
cc @coryb
=> Allow ExitError type to be transmitted over GRPC

hack/dockerfiles/generated-files.Dockerfile
Now that this repository moved to go1.16, we can use 'go install' to install these binaries, as mentioned in https://github.com/moby/buildkit/pull/2146
Before:
#11 [gobuild-base 4/6] RUN git clone https://github.com/gogo/protobuf.git /go/src/github.com/gogo/protobuf 	&& cd /go/src/github.com/gogo/protobuf 	&& git checkout -q v1.3.2 	&& go install ./protoc-gen-gogo ./protoc-gen-gogofaster ./protoc-gen-gogoslick
#11 0.061 Cloning into '/go/src/github.com/gogo/protobuf'...
#11 DONE 12.7s
#12 [gobuild-base 5/6] RUN git clone https://github.com/golang/protobuf.git /go/src/github.com/golang/protobuf 	&& cd /go/src/github.com/golang/protobuf 	&& git checkout -q v1.3.5 	&& go install ./protoc-gen-go
#12 0.093 Cloning into '/go/src/github.com/golang/protobuf'...
#12 DONE 2.7s
After:
#11 …
=> generated files: use "go install" to install binaries

util/stack/generate.go
follow-up to https://github.com/moby/buildkit/pull/2305
Generating the util/stack protos failed when updating protoc-gen-go to v1.5.2;
it looks like this is the only proto that's not generated using protoc-gen-gogo):
util/stack/generate.go
protoc-gen-go: unable to determine Go import path for "stack.proto"
Please specify either:
• a "go_package" option in the .proto source file, or
• a "M" argument on the command line.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
--go_out: protoc-gen-go: Plugin failed with status code 1.
util/stack/generate.go:3: running "protoc": exit status 1
Newer protobuf versions expect a go package to be set. Other .proto files in
this repository use the bare package name, but with protoc-gen-go v1.5.2, …
=> Fix  util/stack to work with newer protoc-gen-go

cache/blobs.go, cache/manager_test.go, cache/refs.go, cache/remote.go, solver/jobs.go, source/containerimage/pull.go, util/compression/compression.go, util/flightcontrol/flightcontrol_test.go
Fixes #2270 
@tonistiigi The possible bug involving the executor host's file turned out to not be an issue because in that code branch the `hostname` var was in practice always set to `defaultHostname`. So this primarily fixes the bug in `computeBlobchain` and a few other smaller possible ones.
=> Fix flightcontrol test and usage bugs

control/control.go
=> control: fix 64bit alignment for buildcount

go.mod, go.sum, vendor/github.com/Azure/go-ansiterm/winterm/ansi.go, vendor/github.com/moby/term/windows/console.go, vendor/modules.txt
full diff: https://github.com/moby/term/compare/bea5bbe245bf...3f7ff695adc6a35abc925370dd0a4dafb48ec64d
updates Azure/go-ansiterm to fix integer overflow on arm
=> go.mod: github.com/moby/term v0.0.0-20210619224110-3f7ff695adc6

cache/blobs.go, cache/blobs_linux.go, cache/blobs_linux_test.go, cache/blobs_nolinux.go, util/testutil/integration/sandbox.go
Fixes: https://github.com/moby/buildkit/issues/1704
Fixes: https://github.com/moby/buildkit/issues/1192
Currently, BuildKit creates diff blobs by comparing the whole filesystem object of a snapshot to its parent, using walking differ but it turned out it can long time.
This commit is a PoC for the faster diff approach specifically aiming at overlayfs-based snapshotter.
This PR computes a diff blob of an overlayfs-based snapshot using its "upper" directory instead of using walking differ. That upper directory contains the diff between that snapshot and its parent so we don't need to compare the whole filesystem objects between them.
~Snapshotter must provide the label `containerd.io/snapshot/overlay.upperdir` which contains the path to the upper directory of this snapshot. When this label …
=> Compute diff from the upper directory of overlayfs-based snapshotter

go.mod
Split the `indirect` packages of go.mod.
After go1.17, all `indirect` packages are listed in the go.mod file.
In addition, has been introduced the ability to list `indirect` packages separately.
Split the `indirect` package to make the dependency packages clearer.
---
This pull request is no-op to codes, just formatted.
=> go.mod: split the indirect packages

cache/contenthash/checksum.go, cache/contenthash/checksum_test.go
As discussed in #2300, `includedPaths` does not resolve symlinks when
looking up the source path in the prefix tree. If the user requests a
path that involves symlinks (for example, /a/foo when a symlink /a -> /b
exists), includedPaths will not find it, and will expect nothing to be
copied. This does not match the actual copy behavior implemented in
fsutil, which will follow symlinks in prefix components of a given path,
so it can end up caching an empty result even though the copy will
produce a non-empty result, which is quite bad.
To fix this, use `getFollowLinks` to resolve the path before walking it.
In the wildcard case, this is done to the non-wildcard prefix of the
path (if any), which matches the behavior in fsutil.
Fixes the skipped test, and also the repro case here: …
=> Follow links in includedPaths to resolve incorrect caching when source path is behind symlink

util/bklog/log.go, util/tracing/detect/detect.go
enhance https://github.com/moby/buildkit/pull/2235
=> bklog: only log tracing ids when span exporter not nil

README.md, docs/build-repro.md, exporter/containerimage/export.go, exporter/containerimage/exptypes/types.go, exporter/containerimage/writer.go, exporter/oci/export.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile2llb/convert_test.go, frontend/dockerfile/dockerfile2llb/image.go, frontend/dockerfile/dockerfile_test.go, frontend/gateway/gateway.go, solver/jobs.go, solver/llbsolver/bridge.go, solver/llbsolver/ops/source.go, solver/llbsolver/solver.go, solver/scheduler_test.go, solver/types.go, source/containerimage/pull.go, source/git/gitsource.go, source/git/gitsource_test.go, source/gitidentifier.go, source/http/httpsource.go, source/http/httpsource_test.go, source/identifier.go, source/local/local.go, source/manager.go, source/types/types.go, util/buildinfo/buildinfo.go, util/buildinfo/export.go, worker/tests/common.go
Fixes #2269
* BuildKit image: `crazymax/buildkit:buildsources`
* Dockerfile frontend image: `crazymax/dockerfile:master`
* Repo example: [crazy-max/buildkit-buildsources-test](https://github.com/crazy-max/buildkit-buildsources-test)
Create and boot builder:
```console
$ docker buildx create \
--name buildsources \
--driver docker-container \
--driver-opt image=crazymax/buildkit:buildsources \
--use
$ docker buildx inspect --bootstrap
```
Build image:
```console
$ docker buildx bake --set *.context=https://github.com/crazy-max/buildkit-buildsources-test.git#master \
git://github.com/crazy-max/buildkit-buildsources-test.git
```
Image config generated with the above command:
```text
{
"architecture": "amd64",
"config": {
"Env": [
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/ …
```
=> Generate and embed build sources

go.mod
As @thaJeztah suggested on https://github.com/moby/buildkit/pull/2331#discussion_r702737246, Sort and moved self-managed indirect dependencies and pinned (`replace` ) to the new block.
=> go.mod: sort and move self managed indirect dependencies to first block

control/control.go, solver/jobs.go, util/resolver/authorizer.go, util/resolver/pool.go
closes #2367
closes #2088
hosts mutex is called on initialization, meaning `GetResolver` might
block if it is in the middle of auth exchange. This is currently bad
in the case where the Job initialization needs to register a name before
timeout is reached.
Authorizer stores the current `session.Group` so if it is
overwritten for another resolver it means that session might
have been dropped and authentication will fail. I haven't been able
to reproduce this issue so not 100% it fixes the case but even if it is
a different race it looks incorrect anyway.
For the Job registration, we might want to do some follow-up change
that avoids running things before job ID is registered.
@maxlaverse
=> resolver timeout fixes

frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile_test.go, frontend/dockerfile/docs/syntax.md
Fixes docker/buildx#474
Closes docker/buildx#776
Set the hostname based on the `BUILDKIT_SANDBOX_HOSTNAME` build-arg value. Also add documentation around the current available built-in build args and make build-arg const name more consistent.
=> Add BUILDKIT_SANDBOX_HOSTNAME build-arg

cache/remotecache/v1/cachestorage.go
This PR aims at fixing issues #1980 and #2198. It does so by ensuring that all results get returned by `cache.remotecache.v1.(*cacheResultStorage).LoadWithParents`, and not only partial results, as can be the case when 2 or more vertexes point to the same result.
See https://github.com/moby/buildkit/issues/2198#issuecomment-924064592 for more information about my understanding of the issue.
=> Fix flakiness during import of a cache with empty layers removed

util/progress/progressui/display.go, util/progress/progressui/term.go, util/progress/progressui/term_windows.go
relates to
* #1108
* docker/buildx#560
* https://github.com/docker/compose/issues/8629
Attempt to use ANSI colors suitable for most terms:
___
We could also use another SGR code for blue like cyan which [seems ok across major terms](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit):
There is also the dichromatic palette for color blind. I guess there is a lot of discussion around this topic, so feel free to give your opinion. And another topic around [`NO_COLOR`](https://no-color.org/) that we can discuss in a follow-up.
cc @thaJeztah 
=> Enhance ANSI colors for progress ui

cmd/buildkitd/config/config.go, util/push/push.go, util/resolver/config/config.go, util/resolver/resolver.go
Follow-up #2361 
Move resolver config to a dedicated package to avoid importing resolver dependencies while using `cmd/buildkitd/config` package.
=> Move resolver config to a dedicated package

.github/workflows/build.yml, .github/workflows/validate.yml
https://github.com/moby/buildkit/pull/1997 was never merged to master.
=> make sure ci runs on version branches

solver/edge.go, solver/scheduler.go
Follow up of https://github.com/moby/buildkit/pull/2382
I couldn't find an easy way to get an `&edgeState{}` as Value of the errored pipe. It seems the simplest solution is to not cast the Value in such a situation. Eventually we could also check if the Value can be cast, and return if it's not the case, but I'm not sure if it brings anything. Thoughts @tonistiigi  ?
Having `target==nil` would end up with the following error.
```
ERRO[2021-10-01T21:34:06Z] /moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = failed to get edge: inconsistent graph state
error: failed to solve: failed to get edge: inconsistent graph state
```
/cc @jamesalucas
=> don't cast Value when pipe is errored

cache/remotecache/v1/cachestorage.go, control/control.go, frontend/dockerfile/dockerfile_secrets_test.go, frontend/dockerfile/instructions/commands_runmount.go, solver/jobs.go, util/resolver/authorizer.go, util/resolver/pool.go
dockerfile: fix parsing required key without value #2304
control: fix 64bit alignment for buildcount #2324
resolver timeout fixes #2369
Fix flakiness during import of a cache with empty layers removed #2372
=> [v0.9] cherry-picks

cache/blobs.go
Following up https://github.com/moby/buildkit/pull/2366#pullrequestreview-764367581 and #2388
Fuse-overlayfs snapshotter doesn't provide overlayfs mounts so overlayfs differ cannot be used. Disable overlayfs differ for that snapshotter.
=> Do not enable overlayfs differ for fuse-overlayfs-snapshotter

cache/blobs_linux.go
Fixes:  #2365
Alternative of #2366
This commit mitigates the recent performance regression of layer exports with containerd worker + overlayfs differ.
The following measures time to take for `exporting layers` of the following Dockerfile with changing the layer size from 50MB to 1GB ([source](https://github.com/ktock/buildkit/blob/f19220892329be43ac566f03b4aa0a5020eb1c99/hack/overlay/tools/measure.sh)).
```dockerfile
FROM ghcr.io/stargz-containers/ubuntu:20.04-org
RUN head -c ${SIZE} </dev/urandom > /sample
```
Measured on GitHub Actions `ubuntu-20.04` runner.
The regression is mitigated by this patch.
https://github.com/ktock/buildkit/actions/runs/1295331304
The overlay differ + containerd worker shows about 2x slower exports.
|`${SIZE}`|overlay differ(sec)|walking …
=> Differ: write diff to the content store over bufio writer

cache/remotecache/gha/gha.go, go.mod, go.sum, solver/jobs.go, util/contentutil/multiprovider.go, vendor/github.com/dimchansky/utfbom/.gitignore, vendor/github.com/dimchansky/utfbom/.travis.yml, vendor/github.com/dimchansky/utfbom/LICENSE, vendor/github.com/dimchansky/utfbom/README.md, vendor/github.com/dimchansky/utfbom/utfbom.go, vendor/github.com/tonistiigi/go-actions-cache/LICENSE, vendor/github.com/tonistiigi/go-actions-cache/cache.go, vendor/github.com/tonistiigi/go-actions-cache/retry.go, vendor/modules.txt, worker/base/worker.go
fixes https://github.com/moby/buildkit/issues/2325
fixes https://github.com/moby/buildkit/issues/2332
Vendors https://github.com/tonistiigi/go-actions-cache/pull/8 https://github.com/tonistiigi/go-actions-cache/pull/6
=> fixes for github actions cache

cache/converter.go, cache/manager_test.go
Annotation `"containerd.io/uncompressed"` is required to be set for each blob descriptor and is used e.g. for creating image config.
Make sure this is set to the converted blobs so that they will be handled correctly.
=> converter: make sure uncompressed digest annotation is set

.github/workflows/build.yml, frontend/dockerfile/cmd/dockerfile-frontend/hack/release, hack/build_ci_first_pass, hack/cross, hack/images, hack/release-tar, hack/test, hack/util
=> Use gha cache on CI

cache/remotecache/export.go, cache/remotecache/gha/gha.go, cache/remotecache/inline/inline.go, cache/remotecache/v1/chains.go, cache/remotecache/v1/chains_test.go, cache/remotecache/v1/utils.go, solver/llbsolver/solver.go
fix #2426
When reexporting blobs that matched cache check that the blob is still available. Otherwise exporting would ask to provide the blob and would fail on requesting it.
The downside of this is that we need to check more blobs and do more requests against github API, meaning it would be easier to hit rate limits.
Another approach would be to try to export a broken chain that would continue to fail on the next builds. An additional problem with that is that one could do `--cache-from type=gha --cache-to type=registry` and then pushing a broken export would be quite a bad failure as blobs are not allowed to just disappear randomly in the registry like they are in github cache.
In the future maybe it makes sense to create an LRU cache for the github API URL requests that would keep …
=> gha: fix handling removed blobs on reexport

frontend/gateway/gateway.go, frontend/gateway/grpcclient/client.go
This allows a frontend to reexec its processes with different arguments without relying on a different external resource that needs to be pulled.
The LLB definition of the frontend is mounted at `/run/config/buildkit/metadata/frontend.bin` . gRPC client also has `CurrentFrontend` method but I didn't expose it in the gateway client (yet).
=> gateway: allow access to current frontend definition

docs/buildkitd.toml.md, docs/rootless.md
Kernel-mode overlayfs is now widely available, so we can simplify docs/rootless.md
=> update rootless docs

cache/remotecache/registry/registry.go, util/contentutil/refs.go, util/push/push.go
fixes docker/buildx#834
Since 1.5 containerd pusher has an issue https://github.com/containerd/containerd/issues/6242 and deadlocks after first error appears(eg. connection dropped or registry error). Purely by coincidence, this error was not affecting buildkit until v0.9.1 because the incorrect logic is behind an interface detection check https://github.com/containerd/containerd/blob/5b09dc5eb0c671d87dc3482d5f63326a4416b74d/remotes/handlers.go#L172-L173 and Buildkit used a wrapper around pusher object.
In v0.9.2 while fixing another issue that wrap was removed and exposed this issue. https://github.com/moby/buildkit/pull/2403/files#diff-9f53bfee1c63146562c6d43b0bc3e476d9e966c93a1b8904031d37ea2f0896bfL82
I have reported this to containerd. Meanwhile, this adds arbitrary wrap around all …
=> push: workaround deadlock in containerd pusher

cache/blobs_linux.go, util/overlay/overlay_linux.go, util/overlay/overlay_linux_test.go
This allows the overlay diff logic to be re-used by the snapshot package
as part of merge+diff op.
Splitting this out as a separate commit from #2335 as suggested there.
FYI @ktock this just migrates the code you wrote previously in order to make it re-usable, in case you are looking for where it went in the future.
=> Move overlay diff to util package.

util/imageutil/config.go
It's better to error out in case there is an ambiguous manifest instead of preferring the image manifest. Newer containerd does not allow such blobs to be pulled anymore.
=> imageutil: make mediatype detection more stricter

util/progress/progressui/display.go
The "defer" is bound to the original value of the ticker, and won't stop
a ticker that's created later in the function. Example:
https://play.golang.org/p/puat5JEf5Jw
Ran into this in a health checker that periodically created buildkit
clients.
cc @coryb
=> Fix ticker leak in DisplaySolveStatus

util/overlay/overlay_linux.go, util/overlay/overlay_linux_test.go
This change results in the overlay differ comparing files to determine
if they are actually part of the diff. This is needed to resolve
differences between the blobs created by the overlay differ and the
double-walking differ.
Before this change, the overlay differ always just assumed that if a
file was in the upperdir it must be part of the diff and included it as
an add or a modify change. However, there are situations in which files
can appear in the upperdir without having been modified or even opened.
For example, if "foo" is a file or dir present in the lowerdirs of an
overlay mount and you run "mv foo footmp; mv footmp foo", then the
upperdir will contain foo (in addition to any files found under foo if
it's a dir). In this situation, the double-walking differ would not
include foo …
=> overlay differ: Do file comparison in some cases.

hack/install-buildx
- Fix unbound var error for BINDIR, PREFIX
- Update buildx version 0.5.1 => 0.7.1
=> hack: update install-buildx

README.md
Incorporating some additional information about export caches as explained in https://github.com/moby/buildkit/issues/2477
- implications to image and cache size
- cache keys
- to and from type mismatch
cc @tonistiigi
=> Clarify Export cache docs

cache/blobs.go, client/build_test.go, client/client_test.go, cmd/buildctl/buildctl_test.go, frontend/dockerfile/dockerfile_heredoc_test.go, frontend/dockerfile/dockerfile_mount_test.go, frontend/dockerfile/dockerfile_runnetwork_test.go, frontend/dockerfile/dockerfile_runsecurity_test.go, frontend/dockerfile/dockerfile_secrets_test.go, frontend/dockerfile/dockerfile_ssh_test.go, frontend/dockerfile/dockerfile_test.go, frontend/frontend_test.go, snapshot/diffapply_unix.go, snapshot/diffapply_windows.go, snapshot/localmounter.go, snapshot/merge.go, snapshot/snapshotter_test.go, solver/jobs_test.go, util/overlay/overlay_linux.go, util/testutil/integration/containerd.go, util/testutil/integration/oci.go, util/testutil/integration/run.go, util/testutil/integration/sandbox.go, worker/containerd/containerd_test.go
These are the initial commits of #2434 split out as suggested in that PR. @tonistiigi responded and updated from your comments about these commits in that PR, let me know if you'd prefer there be one PR-per-commit rather than grouping them here.
=> DiffOp Preparation Commits

executor/oci/mounts.go
It looks like the intent is to keep track of the index in 'ret' where a
destination was written, but that's not what the current code is doing.
=> Fix out-of-bounds panic in dedupMounts

client/client.go
fixes https://github.com/moby/buildkit/issues/2510
`google.golang.org/grpc@v1.42.0` (updated recently in https://github.com/moby/buildkit/pull/2481) introduced better handling for `:authority` pseudo-header implemented in https://github.com/grpc/grpc-go/pull/4817. This requires `WithAuthority` dial option value must match with the server name of its transport creds.  
The current implementation always uses `url.Host ("host:port")` of `--addr` as an authority pseudo-header value because [HTTP/2(RFC7540)](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.3) defines so, i.e the authority portion of target URI without userinfo part.  This causes grpc-go's authority validation to fail.
This PR fixes the issue so that it uses `ServerName` in the tls config as `:authority` header when …
=> Setting just servername to :authority pseudo header in client when using TLS.

README.md
BuildKit-Nix ( https://github.com/AkihiroSuda/buildkit-nix ) is a frontend to use Nix derivations as Dockerfiles (`docker build -f default.nix .`)
=> README.md: add buildkit-nix frontend

README.md
Recently [Gitpod started using buildkit](https://github.com/gitpod-io/gitpod/tree/main/components/image-builder-bob) to build [all of its workspaces images](https://twitter.com/csweichel/status/1470312552399790090). We'd be excited to be listed as project which uses buildkit.
=> README.md: Add Gitpod as consuming project

client/client_test.go, executor/containerdexecutor/executor.go, executor/oci/user.go
fixes #2341
Ensure that unset user has same supplementary groups as root.
=> executor: make sure supplementary groups are set for unset user

frontend/dockerfile/builder/build.go, frontend/dockerfile/builder/caps.go, frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_test.go
Related https://github.com/moby/moby/issues/37129
Related https://github.com/docker/buildx/issues/447#issuecomment-732537029
Stages and implicit stages from image names can be
redefined with build options.
This enables using more that one source directory
and reusing results from other builds. This can also
be used to use a local image from other build without
including a registry.
Contexts need to be defined as `context:name=` frontend
options. The value can be image, git repository,
URL, local directory, or a frontend input.
E.g.
```
FROM alpine AS base
..
..
```
`buildctl build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --opt context:alpine=docker-image://alpine:3.15`
`buildctl build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --local …
=> dockerfile: add support for named contexts

source/git/gitsource_unix.go
If the ref is invalid we are seeing a panic from `umask-git` because
the error type is not always a unix.WaitStatus:
```
#1 0.227 fatal: Not a valid object name 000111222333444555666777888999aaabbbcccd^{commit}
#1 0.229 panic: interface conversion: interface {} is syscall.WaitStatus, not unix.WaitStatus
#1 0.229
#1 0.229 goroutine 1 [running]:
#1 0.229 github.com/moby/buildkit/source/git.gitMain()
#1 0.229 	/src/source/git/gitsource_unix.go:66 +0x27d
#1 0.229 github.com/docker/docker/pkg/reexec.Init(...)
#1 0.229 	/src/vendor/github.com/docker/docker/pkg/reexec/reexec.go:26
#1 0.229 main.init.0()
#1 0.229 	/src/cmd/buildkitd/main.go:76 +0xf6
#1 0.633 fatal: reference is not a tree: 000111222333444555666777888999aaabbbcccd
#1 0.635 panic: interface conversion: interface {} is …
```
=> fix panic from umask-git on invalid ref

client/client_test.go, snapshot/snapshotter.go, snapshot/staticmountable.go, util/overlay/overlay_linux.go, util/overlay/overlay_linux_test.go
#2490
Overlayfs differ cannot calculate diff correctly if redirect_dir is enabled.
~~This commit fixes this issue by falling back to walking differ if redirect_dir is enabled as done in moby (https://github.com/moby/moby/pull/34342).~~ This commit fixes this issue by disabling redirect_dir if it's supported by kernel. 
This'll cause performance drawback on such kernels so we should fix overlayfs differ to handle redirect_dir correctly on these kernels.
cc @sipsma
=> Disable redirect_dir for avoiding incorrect diff

frontend/dockerfile/builder/build.go
Currently in progressbar image name has `//` prefix.
=> dockerfile: fix image name when loaded named context

solver/edge.go, solver/scheduler.go
Fixes #2526
Though we still need to figure out how #2526 triggered `markFailed` in the first place.
=> Remove goto statements causing failed edges to never unpark

frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile_test.go
When loading named context from a local directory first see if it contains a `.dockerignore` file and apply it as a filter if it does.
=> dockerfile: apply dockerignore on loading local contexts

session/auth/authprovider/authprovider.go
Always do OAuth2 if `creds` is a refresh token, not a username / password pair.
Resolves #2554.
=> Refine FetchToken Logic

cache/remotecache/inline/inline.go, cache/remotecache/v1/parse.go, cache/remotecache/v1/spec.go, client/client_test.go, client/mergediff_test.go
This change enables inline cache to work as expected with MergeOp by
supporting a new type of result, DiffResult, which enables results to be
specified as a specific ordered set of layers inside an image.
Previously, results could only be specified with a singe layer index,
which meant that they had to start at the image's base layer and end at
that index. That meant that merge inputs couldn't be specified as they
are often a subset of the image layers that don't begin at the base.
=> remote cache: support arbitrary layers as results

cache/refs.go
Fixes https://github.com/moby/buildkit/pull/2491#issuecomment-1010123172
Currently, read-only option for a mount is sometimes ignored and this seems to lead to conflicts between (unexpectedly-)writable overlay mounts (related: https://github.com/moby/buildkit/issues/2334).
cc @tonistiigi @crazy-max
=> cache: do not ignore readonly option

cache/manager_test.go
This adds test coverage for ensuring the readonly parameter is honored
as expected in the ref Mount methods. There was a regression introduced
during #2335 that went unnoticed until identified and fixed in #2562.
This test coverage should help prevent similar regressions in the
future.
=> cache: add coverage for Mount readonly parameter.

cache/manager.go, cache/manager_test.go
Before this, there could be crash during a call to finalize a ref that
occured after the snapshot was committed but before committing the
metadata that indicates the immutable ref no longer had an
equalMutable. This resulted in a situation where any future calls to
finalize that ref would fail.
Now, if that situation happens, the cache will notice when it's
initially loaded that the ref has an equalMutable that's missing its
snapshot and that its own snapshot exists. It will then just use the
correctly committed snapshot and clear the equalMutable field.
Fixes #2557
=> cache: handle crash after snapshot commit

solver/llbsolver/ops/exec_binfmt.go
Instead of doing a direct string comparison we should
use `platforms.Only` so that we can also detect the
variants that are compatible but don’t match directly.
=> exec: check full platform vector when checking for emulator

cache/manager.go, cache/manager_test.go
Before this change, the lower and upper parents provided to the cache
manager Diff method were not cloned, which resulted in some code paths
incorrectly providing them directly as the parents of the returned ref.
This meant that if they were released after the call to Diff, the diff
ref could become incorrectly invalidated.
Now, the lower and upper are cloned and unit test coverage has been
added to test that ref release is handled correctly.
=> cache: improve diff ref release logic.

util/tracing/env/traceenv.go, util/tracing/exec/traceexec.go
open-telemetry/opentelemetry-specification#740 has decided to
promote different set of env for CLI propagation.
Switch to use them so we are more consistent with other
tools. Old ones should be removed in a future release.
=> tracing: move to newer env names

frontend/dockerfile/dockerfile2llb/convert.go
On cross-compilation this PR now shows both build and target platform on progressbar, not only the platform or the current stage.
When both platforms have the same OS it is only shown once for less verbosity.
```
=> [linux/arm64 2/3] RUN apk add vim                                                                                                                         2.7s
=> [linux/arm64 3/3] RUN sleep 1                                                                                                                             1.3s
=> [linux/arm64->amd64 3/3] RUN sleep 1                                                                                                                      1.3s
=> [linux/arm64->windows/amd64 3/3] RUN sleep 1 …
```
=> dockerfile: show target platform on cross compiling

go.mod, go.sum, solver/llbsolver/ops/exec.go, source/git/gitsource.go, util/progress/logs/logs.go, vendor/github.com/armon/circbuf/.gitignore, vendor/github.com/armon/circbuf/LICENSE, vendor/github.com/armon/circbuf/README.md, vendor/github.com/armon/circbuf/circbuf.go, vendor/modules.txt
=> keep buffer of logs to show on failure when regular logs are clipped

Dockerfile
Alpine 3.15 contains https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/25365 , so we can now install shadow-uidmap frok APK.
Close #2038
Close #2580
=> Dockerfile: update Alpine to 3.15 (install shadow-uidmap from APK)

source/git/gitsource.go, source/git/gitsource_test.go
This fixes errors such as:
error: cannot update ref 'refs/heads/v2.30.0': trying to write non-commit object 2d9685d47a7e516281aa093bf0cddc8aafa72448 to branch 'refs/heads/v2.30.0'
which occur when cloning a tag rather than branch.
=> Add support for annotated git tags

frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_heredoc_test.go, frontend/dockerfile/instructions/commands.go, frontend/dockerfile/instructions/parse_heredoc_test.go, frontend/dockerfile/parser/parser_heredoc_test.go, frontend/dockerfile/shell/lex.go
Woops :smile:
From the commit message:
> In the contents of COPY/ADD, we perform expansion on variables using a lexer. However, this lexer, by default, removes quotes as well expanding variables - this isn't really the kind of behavior we're after, as it feels quite unintuitive.
>     
> To fix this, we introduce a new ExpandRaw function, which commands can implement that implement an alternative expansion that preserves quotes (and possibly other characters/features in the future).
>     
> Additionally, we introduce new tests to more clearly define the behavior. One major note is that backslashes are not passed and are processed, following normal escape rules (so that we can use `$` symbols directly).
This fixes #2439 but does also leave backslashes in COPY not working quite as one …
=> Fix #2439 (`COPY` with Heredocs eats quotes)

README.md, cache/blobs.go, cache/blobs_linux.go, cache/converter.go, cache/estargz.go, cache/manager_test.go, cache/refs.go, cache/remote.go, cache/remotecache/v1/cachestorage.go, exporter/containerimage/export.go, exporter/containerimage/writer.go, exporter/exporter.go, exporter/oci/export.go, solver/cachestorage.go, solver/llbsolver/result.go, solver/llbsolver/solver.go, solver/memorycachestorage.go, solver/types.go, util/compression/compression.go, worker/cacheresult.go, worker/result.go
replaces #2350
`compression-level` option can be set on export to
define the preferred speed vs compression ratio. The
value is a number dependent on the compression algorithm.
@ktock 
=> exporter: support for compression-level

cache/converter.go
Writing blobs to content store should be wrapped with bufio to avoid performance regression on containerd worker.
This converts a zstd image to gzip.
Dockerfile
```dockerfile
FROM ghcr.io/ktock/tomcat:10.0.0-jdk15-openjdk-buster-zstd
```
command
```
buildctl build --progress=plain --frontend=dockerfile.v0 --local context=/tmp/ctx2 --local dockerfile=/tmp/ctx2 \
--output type=oci,dest=/tmp/out.tar,oci-mediatypes=true,compression=gzip,force-compression=true
```
|branch|time to export layers|
|---|---|
|master|69.5s|
|PR|12.2s|
<details>
<summary>full log (master)</summary>
```console
--output type=oci,dest=/tmp/out.tar,oci-mediatypes=true,compression=gzip,force-compression=true
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile:
#1 transferring dockerfile: 96B …
```
=> cache: write blob to the content store via bufio during conversion

util/resolver/pool.go
Currently, unlazying blobs created by the previous build seems to fail because `resolver.Resolver.WithSession()` doesn't propagate session to authorizer during unlazying.
This commit fixes this issue.
- buildkit version: master (a640b47cb19c4f0ff47f2444f3215ee851598a8e)
```console
FROM ghcr.io/stargz-containers/ubuntu:20.04-org
EOF
--output type=oci,dest=/tmp/out.tar,oci-mediatypes=true,compression=zstd,force-compression=true
```
The second build in the above fails with the following error:
```
ERRO[2022-02-07T06:11:09Z] /moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = failed to ensure compression type of "zstd": failed to copy: httpReadSeeker: failed open: no active sessions
```
<details>
<summary>full log</summary>
```console
#1 [internal] load build …
```
=> Resolver: ensure `WithSession` to pass the session to the resolver

client/mergediff_test.go
The merge diff tests were using some common LLB state objects across
multiple test cases, which each have their own buildkit client and ran
in parallel. The LLB client library does not appear to currently work
with such use cases where LLB states are shared, with errors about
concurrent map writes to marshal state constraints occasionally being
hit during test runs.
Until that issue is addressed (or it's made explicit that the LLB client
library is not expected to work in such a way), this works around the
problem by not sharing states and instead using common funcs that return
distinct state instances.
The issue this is working around is tracked [here](https://github.com/moby/buildkit/issues/1668).
=> Work around concurrent map write issue in tests.

cmd/buildctl/build.go, cmd/buildctl/build_test.go, cmd/buildctl/buildctl_test.go, exporter/containerimage/export.go, exporter/containerimage/exptypes/types.go, exporter/oci/export.go
fixes #2558 
```shell
$ ./hack/binaries
$ sudo ./bin/buildkitd &
$ sudo ./bin/buildctl build --progress plain --frontend gateway.v0 --opt source=docker/dockerfile --metadata-file metadata.json --local context=. --local dockerfile=. --output type=oci,dest=test.tar
$ cat metadata.json  | jq
```
```json
{
"containerimage.buildinfo": {
"sources": [
{
"pin": "sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300",
"ref": "docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300",
"type": "docker-image"
}
]
},
"containerimage.config.digest": "sha256:2937f66a9722f7f4a2df583de2f8cb97fc9196059a410e7f00072fc918930e66",
"containerimage.descriptor": {
"annotations": {
"config.digest": …
```
=> image exporter: return image descriptor in response

client/mergediff_test.go, snapshot/diffapply_unix.go, snapshot/merge.go
Before this, there was a bug triggered under the following conditions:
1. An overlay snapshotter was being used, which caused the optimization
of preparing a new snapshot off of the base layers to be triggered
2. The base layers contained a directory that had contents
3. One subsequent layer deleted that directory w/out recreating it
4. A later layer recreated the directory
In this case, what happened was a whiteout device would be created as
part of 3 above but then in step 4 the whiteout device would be removed
and replaced with a plain directory. The problem is that such a
directory doesn't block out the files from step 2 and it doesn't know
about them because they are in a lowerdir (not the upperdir being
applied to).
The simplest fix, which this commit implements, is to just set the …
=> diffApply: set dir opaque when overwriting whiteout

client/llb/imagemetaresolver/resolver.go, util/contentutil/refs.go, util/resolver/authorizer.go, util/resolver/pool.go, version/version.go
Instead of using containerd defaults set our own user-agent on registry requests.
For dev versions I added some pattern matching to avoid putting sha in the requests as it would be useless for any kind of statistics.
(The double value comes from some tracing artifact, there is no actual double header).
=> resolver: set buildkit own user-agent

solver/llbsolver/file/unpack.go
use unpigz to decompress, found that  many  ` /usr/bin/unpigz -d -c  ` processes left;
> $  ps aux | grep unpigz 
root        490  0.0  0.0  40672  1104 ?        Sl   05:22   0:00 /usr/bin/unpigz -d -c
root       2491  0.0  0.0  40672  1104 ?        Sl   05:44   0:00 /usr/bin/unpigz -d -c
root       3861  0.0  0.0  40672  1188 ?        Sl   06:04   0:00 /usr/bin/unpigz -d -c
root       5080  0.0  0.0  40672  1312 ?        Sl   06:19   0:00 /usr/bin/unpigz -d -c
root       6754  0.0  0.0  40672  1088 ?        Sl   06:52   0:00 /usr/bin/unpigz -d -c
root       8515  0.0  0.0  40672  1128 ?        Sl   07:14   0:00 /usr/bin/unpigz -d -c
root       9879  0.0  0.0  40672  1312 ?        Sl   07:34   0:00 /usr/bin/unpigz -d -c
root      11095  0.0  0.0  40672  1168 ?        Sl   07:49   0:00 …
=> Close readclosers returned by DecompressStream

cache/blobs.go, cache/converter.go, cache/manager_test.go, cache/refs.go, cache/remote.go
Fixes: #2346
Currently, a compression variant of a ref is not visible from another. This leads to duplicated conversion as mentioned in #2346.
This commit allows refs sharing compression variants with each other.
When a ref converts a blob (compression blob A) to another compression (compression blob B), Blob A and B are linked together using GC label to make sure that all linked variants are released together (i.e. they aren't released even when refs lease only some of them). (Maybe in the future we can switch to the lease-based approach as discussed in  #2347. But how can we manage the ref counter of the lease itself among refs in a simple way?)
When a ref exports a compression variant, it first walks all linked compression variant blobs and checks if there is a blob that can be reused …
=> cache: Allow sharing compression variants among refs

README.md, client/build_test.go, client/client_test.go, docs/build-repro.md, examples/dockerfile2llb/main.go, exporter/containerimage/export.go, exporter/containerimage/exptypes/types.go, exporter/containerimage/writer.go, exporter/oci/export.go, frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile2llb/convert_test.go, frontend/dockerfile/dockerfile2llb/image.go, frontend/dockerfile/dockerfile_buildinfo_test.go, frontend/dockerfile/dockerfile_test.go, frontend/dockerfile/docs/syntax.md, solver/jobs.go, solver/llbsolver/bridge.go, solver/llbsolver/ops/source.go, solver/llbsolver/solver.go, solver/types.go, util/buildinfo/buildinfo.go, util/buildinfo/buildinfo_test.go, util/buildinfo/types/types.go
follow-up #2311
store additional build dependencies such as `frontend` and `attrs`.
```shell
$ docker buildx build --push --platform linux/amd64,linux/arm64 \
--build-arg "BUILDKIT_CONTEXT_KEEP_GIT_DIR=1" \
--tag "crazymax/buildkit:buildattrs" \
https://github.com/crazy-max/buildkit.git#buildinfo-attrs
$ docker buildx build --push --platform linux/amd64,linux/arm64 \
--build-arg "CHANNEL=mainline" \
--build-arg "BUILDKIT_CONTEXT_KEEP_GIT_DIR=1" \
--tag "crazymax/dockerfile:buildattrs" \
--file "./frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile" \
https://github.com/crazy-max/buildkit.git#buildinfo-attrs
$ docker buildx bake https://github.com/crazy-max/buildx.git#inline-buildattrs binaries
$ cp ./bin/buildx ~/.docker/cli-plugins/docker-buildx
```
Pre-built frontend `# …
=> buildinfo: add build attributes and frontend

frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/docs/syntax.md, frontend/dockerfile/instructions/commands.go, frontend/dockerfile/instructions/parse.go
replaces #2423
fixes https://github.com/moby/buildkit/issues/2414
Enables smarter file copy logic using the mergeop implementation. See docs in the PR contents.
Not 100% sure about the flag name. 
Currently on top of #2513 for the progress groups support.
TODO/follow-up:
- Tests for cache semantics
- Support for `--chown` (currently same as with `--link=false`)
=> dockerfile: add COPY --link for copy via merging layers

session/auth/authprovider/authprovider.go, util/resolver/authorizer.go
fixes #2454
Reverts #2062 and replace with a default expiration time for the case where expiration time is not sent by the server.
@jmacelroy @dchw
=> Fix cross-repo push fallback when access to the source repo is not granted

Dockerfile, go.mod, go.sum, vendor/github.com/containerd/containerd/RELEASES.md, vendor/github.com/containerd/containerd/images/archive/importer.go, vendor/github.com/containerd/containerd/oci/spec_opts.go, vendor/github.com/containerd/containerd/platforms/platforms.go, vendor/github.com/containerd/containerd/remotes/docker/authorizer.go, vendor/github.com/containerd/containerd/remotes/docker/pusher.go, vendor/github.com/containerd/containerd/remotes/docker/status.go, vendor/github.com/containerd/containerd/version/version.go, vendor/modules.txt
https://github.com/containerd/containerd/compare/v1.6.0-rc.1...v1.6.0-rc.2
=> Bump github.com/containerd/containerd to v1.6.0-rc.2

util/progress/controller/controller.go
A panic was encountered where writes to progress status hit a nil
writer. While not easy to reproduce, this commit fixes a likely culprit.
The use of atomics in the controller was not safe against a race such as
the following:
1. One goroutine calls Start, incrementing count but not yet setting
writer.
2. A second goroutine calls Start, increments count again but sees that
count >1 and thus doesn't try to set writer.
3. The second goroutine then calls Status, assuming the writer has been
set, but the first goroutine still hasn't set the writer yet, causing
a nil pointer exception.
This commit fixes that issue by just using a mutex instead of atomics.
It also adds a nil check for the writer just to be safe against panics
due to unknown issues in the future as missing a status update is …
=> progress: fix sync issue in controller.

cache/refs.go, client/client_test.go
Fixes #2334
Currently, `MutableRef.Mounts` can return writable overlayfs mounts that can be mounted to multiple directories.
However, mounting a writable overlayfs to multiple places can result in an error.
This commit avoids this issue by the approach suggested in https://github.com/moby/buildkit/issues/2334#issuecomment-906839236.
> One potential fix is to use a trick where you can create a single overlay mount somewhere and then bind-mount the root of that overlay mount multiple places.
=> Fix shared cache mounts result in overlay corruption

cmd/buildkitd/main.go
fix #2536
The issue in the cli package that added extra
field has been fixed now.
Looks like the issue was fixed with https://github.com/urfave/cli/pull/981
=> buildkitd: fix handling multiple addr flags

cmd/buildkitd/main.go
fix #2542
Looks like the panic comes because this function returns an empty object instead of setting the default options. New behavior is that if the default config does not exist there is no error, if toml parsing fails it is a real error and if there is a file error(eg. EPERM) then warning is printed.
=> buildkitd: handle config loading errors correctly

solver/llbsolver/bridge.go
encounter that issue while working on #2654:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd33ab9]
goroutine 533 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
/src/vendor/go.opentelemetry.io/otel/sdk/trace/span.go:307 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000d7ec00, {0x0, 0x0, 0x0})
/src/vendor/go.opentelemetry.io/otel/sdk/trace/span.go:346 +0x9a2
panic({0x11b68a0, 0x1e58990})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/moby/buildkit/frontend/gateway.(*llbBridgeForwarder).Solve(0xc0006be000, {0x1538c28, 0xc000b5d4d0}, 0xc000da8640) …
```
=> fix nil pointer dereference in bridge result

cache/remotecache/registry/registry.go, client/client_test.go, source/containerimage/pull.go, util/contentutil/multiprovider.go, util/estargz/labels.go, worker/base/worker.go
Currently, stargz-snapshotter performs lazy pulling for estargz-fromatted base images but doesn't for estargz-formatted remote (inline) caches. This is because registry cache importer doesn't pass snapshot labels to stargz-snapshotter. This commit fixes this issue.
Since this commit, if remote cache is exported as estargz (currenly this only happens for inline caches) and stargz-snapshotter is enabled, remote caches aren't unlazied even when running commands on it.
Example of exporting estargz-formatted inline cache:
```
buildctl build --progress=plain --frontend=dockerfile.v0 --local context=/tmp/ctx --local dockerfile=/tmp/ctx \
--output type=image,name=registry2-buildkit:5000/sample1/img:1,push=true,compression=estargz,force-compression=true,oci-mediatype=true \
--export-cache …
```
=> Enable estargz-based lazy pulling on registry cache importer

.github/workflows/build.yml, cache/blobs.go, cmd/buildkitd/config/config.go, cmd/buildkitd/main_containerd_worker.go, docs/rootless.md, executor/containerdexecutor/executor.go, util/testutil/integration/containerd.go, worker/containerd/containerd.go, worker/containerd/containerd_test.go
Fixes #1325
This commit adds support for rootless containerd worker.
This also enables integration tests for rootless containerd worker configuration.
Rootless containerd can run using rootlesskit following [containerd's document](https://github.com/containerd/containerd/blob/main/docs/rootless.md).
```
$ rootlesskit --copy-up=/run --state-dir=/path/to/rootlesskit-state-dir containerd -c config.toml
```
Example `config.toml`:
```toml
version = 2
root = "/home/penguin/.local/share/containerd"
state = "/run/user/1001/containerd"
[grpc]
address = "/run/user/1001/containerd/containerd.sock"
```
Then buildkitd can join the same namespace as containerd.
```
$ nsenter -U --preserve-credentials -m -t $(cat /path/to/rootlesskit-state-dir/child_pid) \
buildkitd --oci-worker=false …
```
=> Support rootless containerd worker

docs/merge+diff.md, examples/README.md, examples/buildkit4/buildkit.go
Docs for merge+diff, added a new example that improves on the previous ones by utilizing MergeOp. More example use cases are inlined to the doc.
=> Merge+Diff docs+examples

client/build.go, client/solve.go, frontend/gateway/grpcclient/client.go
fixes #2599
Currently the local cache import only worked with client.Solve
function.
=> client: make sure local cache import is propagated via gateway API

cache/contenthash/checksum_test.go, cache/manager.go, cache/manager_test.go, cache/refs.go, go.mod, solver/llbsolver/mounts/mount_test.go, source/git/gitsource_test.go, source/http/httpsource_test.go, worker/base/worker.go, worker/containerd/containerd.go, worker/runc/runc.go
Following-up https://github.com/moby/buildkit/pull/2637#discussion_r807235198
Currently, if buildkitd crashes before unmounting temporary (writable) overlayfs mounts, it could leak these mounts.
Then if buildkitd started up again, same issue of duplicating overlay mounts can happen because the old mounts remain on the host.
This commit fixes this issue by introducing a directory `cachemounts` under `/var/lib/buildkit/` for storing all temporary overlay mounts.
When buildkitd starts, it cleans up all existing (old) mounts under that directory so we can avoid the issue of duplicating overlay mounts.
=> cache: Clean up temporary mount pool on restart

cmd/buildkitd/main_oci_worker.go, go.mod, go.sum, vendor/github.com/containerd/stargz-snapshotter/snapshot/snapshot.go, vendor/modules.txt
Fixes  #2667
This patch updates stargz-snapshotter to fix the issue of the panic on restart. (containerd/stargz-snapshotter#659)
This was because a code path that shouldn't be executed by BuildKit happens if there are some existing snapshots on restart.
We can reproduce the panic using the following example
1. Buliding an image with lazy pulling
```console
FROM ghcr.io/stargz-containers/ubuntu:20.04-esgz
RUN echo hello > /hello
EOF
--output type=oci,dest=/tmp/out.tar
```
2. Restarting buildkitd. Here, we encounter panic with message `buildkitd: failed to restore remote snapshot` as described in #2667.
=> stargz: fix panic on restart

cmd/buildkitd/main.go, util/bklog/log.go
Related to  #2656
Currently, bklog overwrites `(github.com/containerd/containerd/log).G` and doesn't preserve the logger set by `(github.com/containerd/containerd/log).WithLogger`.
This causes log fields set by `(github.com/containerd/containerd/log).WithLogger` are dropped.
This commit fixes this issue by allowing `bklog.GetLogger` to get logger set by `(github.com/containerd/containerd/log).WithLogger`.
=> Do not drop logger set by containerd

frontend/dockerfile/dockerfile2llb/convert.go
=> dockerfile: fix COPY —link to keep previous llb state

client/client_test.go, docs/build-repro.md, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_buildinfo_test.go, solver/llbsolver/solver.go, util/buildinfo/buildinfo.go, util/buildinfo/buildinfo_test.go, util/buildinfo/types/types.go
follow-up https://github.com/moby/buildkit/pull/2476
=> buildinfo: named input contexts support

.github/workflows/build.yml, Dockerfile
Let's switch to the latest test release to make sure CI doesn't catch anything.
=> ci: update buildkit to latest rc

snapshot/merge.go
The stargz snapshotter creates separate FUSE mounts for each lazy
snapshot and non-FUSE mounts for newly created local snapshots. This
means that hardlinking during diffApply fails. The code then falls back
to doing a copy, which works fine, but it also results in a ton of debug
logs about the failing hardlinks to be printed. This change just results
in those noisy log lines no longer appearing.
Related to #2671
=> merge: disable stargz hardlinking

solver/jobs.go, solver/llbsolver/solver.go, util/progress/controller/controller.go
This commit fixes more issues where vertex progress updates were using
the same ID and incorrectly deduplicating with each other. A previous
commit addressed this in solver/jobs.go but the same problem existed
elsewhere.
The update results in a random ID being used for vertex start/stop
events as it is the simplest approach that works everywhere in a
consistent pattern.
=> progress: use unique id for vertex start/stop

cache/manager_test.go, cache/refs.go
Following-up  #2603
Though compression variants are linked using gc labels, they can be ignored and garbage collected because the lease of each ref has a lable [`containerd.io/gc.flat` which ignores the label references of the leased blob](https://github.com/containerd/containerd/blob/v1.6.0/docs/garbage-collection.md#garbage-collection-labels).
This commit fixes this issue by introducing a new lease for compression variants. This lease doesn't have `containerd.io/gc.flat` label to allow label references.
Reproducing issue:
1. Doing the following builds on containerd worker
```console
FROM ghcr.io/stargz-containers/alpine:3.10.2-org
RUN /bin/touch /foo
EOF
--output type=oci,dest=/tmp/out.tar,compression=uncompressed,force-compression=true
```
2. Here, uncompressed blob variant …
=> Fix refs ignoring gc labels of contents

client/client_test.go, util/testutil/integration/run.go, util/testutil/integration/sandbox.go
Currently, `testPullZstdImage` in `client_test.go` doesn't seem to test pulling of zstd image but use locally cached one. This commit ensures that test checks if pulling zstd image work.
According to the fixed test, 2 limitations for zstd images are found.
1. applier service of containerd supports only zstd mediatype with oci-mediatpye but doesn't support zstd with docker-medatype ([related containerd code](https://github.com/containerd/containerd/blob/4595cdef8921c4a87e409b2b004e823afa600df3/images/mediatypes.go#L57-L106))
2. applier service of containerd 1.4 doesn't support zstd ([related commit](https://github.com/containerd/containerd/commit/30802fac7303648863b7f18b7d6ab4f5336390ec))
This commit fixes that test to make it aware of these limitations.
=> test: Ensure testPullZstdImage pulls zstd image

cache/remotecache/v1/utils.go, client/client_test.go, exporter/containerimage/exptypes/types.go, exporter/containerimage/writer.go, frontend/dockerfile/dockerfile_test.go, snapshot/imagerefchecker/checker.go
This fixes an issue related to inline caching resulting in cache import errors like this one: `invalid layer index 29`. The cause of this is the image writer optimizing the final image by removing empty layers. Because this takes place after the inline cache manifest has been constructed, the indexes of the layers from the inline cache manifest end up being incorrect. Sometimes they end up being out of bounds.
Originally reported as an issue in Earthly here: https://github.com/earthly/earthly/issues/1635.
CC @tonistiigi 
Signed-off-by: Vlad A. Ionescu <vladaionescu@users.noreply.github.com>
=> Eliminate auto-removal of empty layers

cmd/buildctl/common/trace.go
This commit fixes the error on `buildctl debug`.
```console
NAME:
buildctl debug - debug utilities
USAGE:
buildctl debug command [command options] [arguments...]
COMMANDS:
dump-llb       dump LLB in human-readable format. LLB can be also passed via stdin. This command does not require the daemon to be running.
dump-metadata  dump the meta in human-readable format.  This command requires the daemon NOT to be running.
workers        list workers
OPTIONS:
--help, -h  show help
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb53517]
goroutine 1 [running]:
github.com/moby/buildkit/cmd/buildctl/common.AttachAppContext.func2(0xc0006bee78, {0x0, 0x0}) …
```
=> Fix nil error on `buildctl debug`

util/progress/progressui/display.go, util/progress/progressui/printer.go
fixes #2681
Generate index when vertex is printing, not when it is received.
=> progressui: fix possible out of order indexing on plain mode

Dockerfile, frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile, frontend/dockerfile/cmd/dockerfile-frontend/hack/release, hack/dockerfiles/generated-files.Dockerfile, hack/dockerfiles/lint.Dockerfile, hack/dockerfiles/shfmt.Dockerfile, hack/dockerfiles/vendor.Dockerfile, hack/images, hack/util
follow-up #2679
buildinfo attributes were not included because the built-in build-arg `BUILDKIT_INLINE_BUILDINFO_ATTRS` requires buildx >= 0.8 which is not currently available on GitHub runners so use `buildinfo-attrs` output opt instead.
=> ci: opt-in buildinfo attrs with output opt

cache/blobs_linux.go, util/overlay/overlay_linux.go
Fixes #2655
This commit fixes that exporting layers doesn't cancelled cleanly.
master version:
```
#7 exporting layers
#7 exporting layers 2.5s done
#7 ERROR: missing lease requirement for setBlob
------
> exporting to oci image format:
------
error: failed to solve: Canceled: context canceled```
```
PR version:
```
#7 exporting layers
#7 exporting layers 2.7s done
#7 CANCELED
error: failed to solve: Canceled: context canceled
```
=> overlay differ: cancel diff calculation cleanly

client/prune.go, client/workers.go, cmd/buildctl/debug/workers.go
For https://github.com/containerd/nerdctl/pull/858#discussion_r819255971
<details>
<summary><code>buildctl debug workers --format '{{json .}}' | jq .</code></summary>
<p>
```json
[
{
"id": "arw1g9hrf1gyogbj9q07r7bz3",
"labels": {
"org.mobyproject.buildkit.worker.executor": "oci",
"org.mobyproject.buildkit.worker.hostname": "suda-ws01",
"org.mobyproject.buildkit.worker.snapshotter": "overlayfs"
},
"platforms": [
{
"architecture": "amd64",
"os": "linux"
},
{
"architecture": "amd64",
"os": "linux",
"variant": "v2"
},
{
"architecture": "amd64",
"os": "linux",
"variant": "v3"
},
{
"architecture": "amd64",
"os": "linux",
"variant": "v4"
},
{
"architecture": "386",
"os": "linux"
}
],
"gcPolicy": [
{
"filter": [
"type==source.local,type==exec.cachemount,type==source.git.checkout"
],
"all": false, …
```
=> buildctl debug workers: add --format option

cache/estargz.go, cache/manager_test.go
Default `estargz` compression level to `gzip.DefaultCompression`. This is consistent with other compression methods and possibly a better tradeoff as `BestCompression` is quite slow. If users want to use a different level they can set it manually.
=> cache: set default compression for estargz

client/mergediff_test.go, snapshot/diffapply_unix.go
A previous commit fixed an issue where directories that overwrite
whiteout devices needed to be set to be opaque. While that was needed,
it wasn't enough because directories also need to be set opaque if they
are overwriting anything that isn't a directory, such as a file or a
symlink. This commit updates the code to handle that situation in
general.
=> diffapply: make overwritten dirs opaque.

client/client_test.go, frontend/dockerfile/dockerfile_test.go
Fixes https://github.com/moby/buildkit/pull/2685#pullrequestreview-900491854
On the master branch, `CacheImportExport` tests are flaky. This patch deflakes these tests.
- https://github.com/moby/buildkit/runs/5445980508?check_suite_focus=true#step:6:1759
- https://github.com/moby/buildkit/runs/5425504420?check_suite_focus=true#step:6:1254
- https://github.com/moby/buildkit/runs/5425504420?check_suite_focus=true#step:6:1254
(On my machine, `testBasicLocalCacheImportExport` failed about 3 tiems in 100 attemptions).
Current cache implementation defers release-related logic using goroutine.
https://github.com/moby/buildkit/blob/bbf149ba70a54740fdf9c251dda6451b84cd452f/cache/refs.go#L1361-L1367
This seems to cause the situation where a build has finished but the following …
=> test: deflake `CacheImportExport` tests

frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_buildinfo_test.go, frontend/gateway/gateway.go, solver/llbsolver/bridge.go, solver/llbsolver/solver.go, util/buildinfo/buildinfo.go, util/buildinfo/buildinfo_test.go, util/imageutil/buildinfo.go
follow-up #2654
fixes an issue where sources for buildinfo dependencies were not merged. this also deduplicates sources from main buildinfo that only belong to dependencies.
=> buildinfo: merge build sources for deps

.github/workflows/build.yml
Since go1.17 is set on all other containers, using go1.16 in only one pipeline can lead to unexpected behaviour
and difference during test.
This PR just update Golang version to 1.17 in `build.yaml` to have the same Go version everywhere in the CI
Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>
=> Bump Golang version from 1.16 to 1.17 in windows build CI

cmd/buildctl/build/exportcache.go, cmd/buildctl/build/importcache.go, cmd/buildctl/build/importcache_test.go, cmd/buildctl/build/util.go
When using `buildctl`, it's not explained in the documentation that GitHub attributes `url` and `token` must be manually set to make this works.
That miscomprehension is visible with #2706.
To do not meet that error again, this commit add a precision on how use GitHub cache with buildctl.
Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>
=> Load GitHub runtime environment when using buildctl

cache/opts.go, solver/cacheopts.go, solver/jobs.go, solver/llbsolver/ops/diff.go, solver/llbsolver/ops/exec.go, solver/llbsolver/ops/file.go, solver/llbsolver/ops/merge.go, worker/base/worker.go
This centralizes the location where ProgressKey gets set, which works
because it only needs information about the vertex, nothing op-specific.
Addresses this comment: https://github.com/moby/buildkit/pull/2708#discussion_r821126775
=> Set ProgressKey in solver instead of ops.

cache/manager_test.go, cache/refs.go, snapshot/merge.go
A temporary lease ctx was previously made during the snapshotter Merge
method but it was not passed to diffApply, which may have meant that
temporary View snapshots created there could be garbage collected by
containerd at any time.
It's possible this was encountered in CI, but I was unable to reproduce
the failure after 1000 attempts locally, so this commit is just a best
guess at the problem.
I can't be sure because I couldn't reproduce it but this is my best guess at the CI error @crazy-max pointed out [here](https://github.com/moby/buildkit/pull/2725#issuecomment-1066521712).
I also included a commit for a separate issue I noticed while fixing the main one: 
`cache: check that diff upper isn't nil`
Before this, if you called DiskUsage when …
=> snapshot: use temporary lease during diffapply

client/build_test.go, client/client_test.go, client/mergediff_test.go, frontend/dockerfile/dockerfile_test.go, util/testutil/integration/dockerd.go, util/testutil/integration/sandbox.go
- Replace the current private method with a reusable helper.
- Add reason messages for skipping. Places where I removed the call are skipped anyway for a different requirement(buildctl,containerd) or in some cases I did not understand why such test should be skipped and requires new evaluation. For the entitlements tests, I was not sure what the actual reason is so left empty.
=> integration: add helper for skipping tests with dockerd

go.mod, go.sum, vendor/modules.txt
no changes to code we use, but the v2.8.0 module was borked
full diff: https://github.com/docker/distribution/compare/v2.8.0...v2.8.1
=> vendor: github.com/docker/distribution v2.8.1

Dockerfile, go.mod, go.sum, vendor/github.com/containerd/containerd/Vagrantfile, vendor/github.com/containerd/containerd/oci/spec.go, vendor/github.com/containerd/containerd/oci/spec_opts.go, vendor/github.com/containerd/containerd/version/version.go, vendor/modules.txt
Includes a fix for CVE-2022-24769
=> Dockerfile: containerd v1.6.2/v1.5.11 and vendor containerd v1.6.2

util/testutil/integration/dockerd.go
follow-up https://github.com/moby/moby/pull/43431#issuecomment-1079895253
=> integration: don't error if connection already closed with dockerd worker

.github/workflows/build.yml, Dockerfile, examples/buildkit0/buildkit.go, examples/buildkit1/buildkit.go, examples/buildkit2/buildkit.go, examples/buildkit3/buildkit.go, examples/buildkit4/buildkit.go, examples/nested-llb/main.go, frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile, frontend/dockerfile/instructions/parse.go, hack/dockerfiles/generated-files.Dockerfile, hack/dockerfiles/lint.Dockerfile, hack/dockerfiles/vendor.Dockerfile, solver/testutil/cachestorage_testsuite.go, util/archutil/Dockerfile, util/resolver/retryhandler/retry.go, util/testutil/integration/run.go
=> update to go 1.18

exporter/containerimage/export.go
#2754
Related https://github.com/containerd/containerd/issues/3225
Platforms options are normalized but exporter doesn't normalize the default platform (i.e. uses `platfroms.DefaultString()`).
This mismatch seems to cause the unpack failure on arm.
https://github.com/moby/buildkit/blob/d7744bcb3532b8efb0ee59cc5a805a3f06e6aa9a/frontend/dockerfile/builder/build.go#L672
=> exporter: normalize default platform string

util/progress/progressui/printer.go
The plain progress has a loop that iterates over each vertex the trace
knows about (rather than just the updated ones). Before this, that loop
was not checking to see if a vertex was supposed to be skipped due to
being in a group or due to being hidden.
This resulted in vertexes being printed unnecessarily. It also led to a
rare case where a vertex with nil lastBlockTime could be set to the
'current' field, which could then result in a nil pointer exception.
The update here just adds the appropriate checks to the loop.
=> progressui: fix printing of hidden vertexes.

client/llb/state.go, frontend/dockerfile/dockerfile2llb/convert.go
This fixes the case where the named context source is input with a different platform than the target platform. For example when including a cross-compilation stage.
=> dockerfile: fix named context input platform resolution

Dockerfile, util/testutil/integration/containerd.go
Fixes #2736
The pre-existing `/run/containerd` causes "permission denied" error in rootlesskit namespace when it's copied-up.
We need to do `rm -f /run/containerd` to remove the copied-up symbolic link to `/run/containerd` on the parent namespace.
The actual `/run/containerd` directory on the host is not affected.
This is a recommended configuration to run containerd with rootlesskit: https://github.com/containerd/containerd/blob/v1.6.1/docs/rootless.md#daemon .
=> test(worker=containerd-rootless): make sure cleanup pre-existing state dir

.github/workflows/build.yml, .github/workflows/buildx-image.yml, .github/workflows/validate.yml
#2771 
backport to `v0.10` branch to avoid failures for the next release
=> [v0.10] ci: set buildx 0.8.2 version

version/version.go
Pretty awful typo that made the User-Agent version to always be v0.0.0. I renamed the variable to it is less likely to use it in an incorrect place.
=> version: fix parsing user-agent version

control/control.go, solver/llbsolver/solver.go
The list of arguments for llbsolver.New() was a bit unwieldy, and
made it unclear what each of the arguments was for, so I wondered
if it would make sense to either define an Opt struct for this, or
to implement functional arguments (which could be an alternative).
=> solver/llbsolver: add Opt struct for llbsolver.New()

examples/kubernetes/deployment+service.rootless.yaml, examples/kubernetes/job.rootless.yaml, examples/kubernetes/pod.rootless.yaml, examples/kubernetes/statefulset.rootless.yaml
Kubernetes added the official `securityContext.seccompProfile` support in Kubernetes 1.19.
Seccomp is still disabled by default.
The legacy `container.seccomp.security.alpha.kubernetes.io/<PODNAME>` annotation has been deprecated and will be unsupported in Kubernetes 1.25.
https://kubernetes.io/docs/tutorials/security/seccomp/
A test cluster can be created with the following minikube command:
```
minikube start --feature-gates SeccompDefault=true --extra-config kubelet.seccomp-default=true
```
Fix  #2515
=> examples/kubernetes: replace deprecated seccomp annotations with securityContext

examples/kubernetes/deployment+service.rootless.yaml, examples/kubernetes/job.rootless.yaml, examples/kubernetes/pod.rootless.yaml, examples/kubernetes/statefulset.rootless.yaml
cherry-pick #2782
(cherry picked from commit 5e2cfb89f85f5e938ec193faa041da817e0bcaaf)
=> [v0.10] examples/kubernetes: replace deprecated seccomp annotations with securityContext

frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile2llb/convert_runmount.go, frontend/dockerfile/dockerfile_mount_test.go, frontend/dockerfile/dockerfile_test.go
FileOp has been supported since BuildKit v0.5 / Dockerfile v1.1 (Apr 2019): 8a4674bab
Fix #2772
=> dockerfile: remove non-FileOp mode

.github/CONTRIBUTING.md
fixes https://github.com/moby/buildkit/issues/2797
The https://dockr.ly/slack should be updated frequently if the invite expires.
=> contributing: update slack invite link

cmd/buildctl/build.go, cmd/buildctl/build/exportcache.go, cmd/buildctl/build/exportcache_test.go, cmd/buildctl/build/importcache.go, cmd/buildctl/build/opt.go, cmd/buildctl/build/output.go, cmd/buildctl/build_test.go, frontend/dockerfile/dockerfile_test.go
| Removed flags                            | Replacement                                                           |
|--------------------------------|------------------------------------------------|
| `--exporter`, `--exporter-opt` | `--output type=<type>[,<opt>=<optval>]`         |
| `--frontend-opt`                        | `--opt <opt>=<optval>`                                         |
| `--export-cache-opt`               | `--export-cache type=<type>,<opt>=<optval>` |
| Deprecated but retained forms  | Replacement                                                     |
|--------------------------------|---------------------------------------------|
| `--export-cache <ref>`             | `--export-cache type=registry,ref=<ref>`     |
| `--import-cache <ref>`             | …
=> buildctl: remove deprecated flags (`--exporter`, `--exporter-opt`, `--frontend-opt`, ...)

examples/dockerfile2llb/main.go
https://github.com/moby/buildkit/blob/86c33b66e176a6fc74b88d6f46798d3ec18e2e73/frontend/dockerfile/dockerfile2llb/convert.go#L73
The stdout is for `*llb.State`, `--partial-image-config-file` is for `*Image`, `--partial-metadata-file` is for `*binfotypes.BuildInfo`.
The `*binfotypes.BuildInfo` contains source information for `docker-image` but does not contain other source information such as `http`.
=> examples/dockerfile2llb: add `--partial-image-config-file`, `--partial-metadata-file`

README.md, client/client_test.go, client/mergediff_test.go, exporter/containerimage/export.go
Some blobs in the result image can be lazy (i.e. not existing in the local content store).
This doesn't allow non-buildkit containerd clients (e.g. ctr, nerdctl, ...) fetching the resulting image from containerd.
Unpack doesn't solve this because it only unlazies the default platform of the image.
```console
FROM ubuntu:20.04
CMD echo hello
EOF
--local context=/tmp/ctx --local dockerfile=/tmp/ctx \
--opt platform=linux/amd64,linux/arm64 \
--output=type=image,unpack=true,name=foo
ctr: failed to get reader: content digest sha256:185e8a4c100571f111d924b5d4399d89f163bf95d71ce2c6a33f656a66c52f0a: not found
```
This commit fixes this by adding a new option `ensure-blobs` to containerimage exporter.
This option unlazies blobs of the build result.
=> exporter: containerimage: Add an option to unlazy image blobs

cache/manager.go, cache/manager_test.go
Before this, merge and diff refs were incorrectly not being marked as
committed, which meant that when cache was reloaded they would be marked
as mutable, which in turn lead to them being removed by the cache
manager's init method. If the ref was a parent, this could cause an
inconsistent state to arise.
I can no longer reproduce the problem in #2740 after this fix, but that problem was not totally consistent for me to reproduce locally, so appreciate if you can give it a try too @tonistiigi 
~I also haven't 100% connected every dot between the problem being fixed here and the exact error message that was arising in that issue, so I will continue investigating to make sure there's not more problems besides the one patched in this PR.~
EDIT: I …
=> cache: set committed to true for merge+diff refs.

cache/manager.go, cache/manager_test.go
=> [v0.10.2] cherry-picks

cache/remotecache/v1/doc.go
Fixes some typos and defines `"chains"` key that was added in `v0.10`.
=> remotecache: update spec documentation

Dockerfile, go.mod, go.sum, vendor/github.com/containerd/containerd/Vagrantfile, vendor/github.com/containerd/containerd/image.go, vendor/github.com/containerd/containerd/pkg/kmutex/kmutex.go, vendor/github.com/containerd/containerd/pkg/kmutex/noop.go, vendor/github.com/containerd/containerd/unpacker.go, vendor/modules.txt
https://github.com/containerd/containerd/compare/5ff8fce1fcc6...v1.6.3
=> vendor: github.com/containerd/containerd v1.6.3

client/connhelper/ssh/ssh.go, client/connhelper/ssh/ssh_test.go, cmd/buildctl/main.go
Fixes #2032
Note: second commit adds a new feature: `ssh://.../path/to/socket` to change the `--addr` that gets passed to `buildctl`. This is not allowed by Docker CLI's implementation so maybe should not be here.
I needed this as I run `buildkitd` rootless meaning socket is not under `/run/buildkit` root path. It's not *needed* per se as a workaround is:
```shell
#!/bin/sh -eu
exec $HOME/bin/buildctl --addr unix:///run/user/1000/buildkit/buildkitd.sock "$@"
```
I'm leaving this second commit in for discussion but I expect you'll want me to remove it.
=> Port SSH connhelper from github.com/docker/cli/cli/connhelper/ssh

frontend/gateway/forwarder/forward.go, worker/workercontroller.go
Dockerfile frontend makes many calls to BuildOpts() function
after named build context support was added. Previously it 
only did one per build. The assumption is that BuildOpts()
is fast and does not need to be cached on the caller side.
In current implementation BuildOpts() listed the workers
in a way that triggered the platform emulation check to be
triggered to with could take 50-100ms to complete what adds
up if there are many Dockerfile stages.
This commit adds caching to BuildOpts. If frontend was
loaded through an external image then it was already cached
and this issue did not appear.
The second commit disables rechecking emulators in this case even for the first attempt. This was added in https://github.com/moby/buildkit/pull/1381 but I think rechecking it with every build is …
=> Fix builtin dockerfile frontend performance

client/client_test.go, client/llb/resolver.go, client/llb/source.go, solver/pb/attr.go, solver/pb/caps.go, source/containerimage/pull.go, source/identifier.go
Adds a new `WithLayerLimit` option to `llb.Image`
only pulls specified number of layers instead of
full image.
This can be used in combination with DiffOp/MergeOp
to pull any subset of layers from an image in any order.
=> Allow pulling partial layer chains from an image

frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_test.go
This fixes an issue where `$PATH` was being overwritten while converting
to LLB since we never actually passed it an image object so when it
checks to see if the `PATH` env var is set PATH is indeed not set since
we wind up with an empty `Image`.
=> Resolve docker-image named context config AOT

Dockerfile
Improve Dockerfile after testing outline with #2841
=> Dockerfile: update comments

README.md
I created a frontend for Python projects. It simplifies creating images for a specific Python version and a given list of dependencies. It supports all of the pip based specific syntax with ssh and local dependencies as well as requirements.txt files. I added my frontend to the list of referenced frontends.
=> Add PyDockerfile to list of frontends

client/solve.go, exporter/local/export.go, exporter/tar/export.go, go.mod, go.sum, session/filesync/filesync.go, vendor/github.com/tonistiigi/fsutil/walker.go, vendor/modules.txt
fixes https://github.com/moby/buildkit/issues/2837
=> vendor: upgrade github.com/tonistiigi/fsutil

frontend/dockerfile/dockerfile_test.go
- backport of https://github.com/moby/buildkit/pull/2854
- relates to https://github.com/moby/moby/pull/43571
(cherry picked from commit 3bed8e2ea3183ed9c2f0d19f956c405a160014ec)
=> [v0.10 backport] dockerfile: fix named contexts test for dockerd

session/auth/authprovider/authprovider.go
The Docker CLI supports a field called "registrytoken" within the auth
config that may contain a previously resolved bearer token. If a
value is present, it is used verbatim and OAuth token retrieval using
username/password or identity token is skipped.
Support this same functionality in the buildkit client by checking for
this field's value prior to credential based auth in `FetchToken`. If a
value is set for `AuthConfig.RegistryToken`, short circuit and return
the token value as is.
This feature helps to support registry setups that integrate with third
party auth systems such as GitLab's JWT OmniAuth provider.
=> authprovider: support registrytoken field in docker auth config

util/contentutil/copy.go
Support cross repo mounting for the CopyChain API, by recursively copying the top-level descriptors' `containerd.io/distribution.source.*` annotations into its childrens descriptors (if not already present).
See https://github.com/docker/buildx/pull/1137.
=> Support cross-repo mounting for contentutil.CopyChain

cmd/buildctl/build.go, session/auth/authprovider/authprovider.go
Hiya - I've got a use case for passing the Docker config content over the wire (SSH) to a central server that talks back to SSH-tunneled Buildkit sockets. To do this I need to pass the Docker config directly to the auth provider instead of loading it from the local machine, since in this case that would be the central server, which doesn't have any config.
Thanks for making Buildkit!
*edit: I don't actually need this anymore, but I think it's a reasonable refactor since it lets the caller choose whether they want to do I/O. I'll leave it open, but feel free to close if it's not worth it.*
=> NewDockerAuthProvider: take docker config instead of loading it

.github/workflows/build.yml, .github/workflows/buildx-image.yml, .github/workflows/dockerd.yml, .github/workflows/validate.yml
add concurrency check in our workflows to ensure that only a single workflow using the same concurrency group will run at a time. it allows to reduce job build queue in our pipeline (we are limited to 20 concurrent jobs atm with the [Free plan](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits)).
more info: https://docs.github.com/en/actions/using-jobs/using-concurrency
=> ci: add concurrency check

cmd/buildkitd/main.go
Have an option to send the `Solve()` daemon-side stacktraces to the client along with an error. Enabled via `--send-stacktraces` or config file option.
Should not be enabled in most cases. However, when running tests, this can be very useful. If the error occurs in the daemon, the output logs now can tell where the error occurred.
Discussed with @tonistiigi [here](https://github.com/moby/buildkit/pull/2827#issuecomment-1151705920)
I probably should make this a Draft PR, but it gets across what I was trying to do, and is functional. Happy to change into some other format, if that is better.
We also probably should enable it for all usage inside CI, if this is good.
=> Add return stack traces

Dockerfile, go.mod, go.sum, vendor/modules.txt
follow-up https://github.com/moby/buildkit/pull/2584#issuecomment-1024663748 https://github.com/moby/buildkit/pull/2701#issuecomment-1058860726 https://github.com/moby/buildkit/pull/2833#discussion_r860528385
closes #2878 
vendor runc https://github.com/opencontainers/runc/compare/v1.1.1...v1.1.3 and update binary.
=> Dockerfile: update runc to 1.1.3

README.md, client/client_test.go, exporter/containerimage/annotations.go, exporter/containerimage/export.go, exporter/containerimage/exptypes/annotations.go, exporter/containerimage/opts.go, exporter/containerimage/writer.go, exporter/exporter.go, exporter/oci/export.go, solver/pb/caps.go
Fixes #1220
This PR introduces support for creating and attaching annotations to the exporter. These annotations can be specified via frontends, or via the exporter output parameters (with the latter overriding the former).
For now, this is just the containerimage exporter, but we should probably add it to the other exporters as well, at the very least the oci exporter :eyes:
=> Add annotations support to output

README.md
[envd ![](https://img.shields.io/github/stars/tensorchord/envd.svg?style=social)](https://github.com/tensorchord/envd) uses buildkit llb to build development environments for machine learning.
Thank buildkit contributors and maintainers for the awesome project!
Signed-off-by: Ce Gao <ce.gao@outlook.com>
=> chore: Add llb adopter `envd`

README.md
Prompted by #2925, I've made some minor updates to the options documentation, which should hopefully make the docs across exporters more consistent and easy to read.
Specifically:
- Add an example on exporting multiple images.
- Consistently avoid using full stops `.` at ends of lines opt , unless there is a following sentence.
- Rephrase options descriptions to always start with a verb.
- Notate defaults more clearly where possible.
- Use angle brackets `<>` instead of square brackets `[]` to document parameters, and ensure parameters of interest are shown with this syntax. This was chosen to avoid confusion with the literal square brackets that are used in the new annotation syntax.
- Use pipes `|` to represent a selection of possible options instead of commas, which is a standard …
=> Readme opts tidy

frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile_test.go
Thanks to @ciaranmcnulty for raising this on the docker community slack [here](https://dockercommunity.slack.com/archives/C7S7A40MP/p1655805439087709).
Images built using docker-image:// passed through buildkit named contexts had the wrong Image.Created timestamp, using the timestamp from the used image, instead of the current datetime.
To fix, we perform the same input cleanup as in Dockerfile2LLB, and explicitly set the timestamp to nil.
=> dockerfile: fix created timestamp

frontend/dockerfile/docs/reference.md
Clarify the USER command to remove phrasing that suggests the ENTRYPOINT and CMD commands must follow the USER (the order doesn't actually matter).
Fixes #2955.
=> docs: clarify USER command explanation

cmd/buildkitd/main_containerd_worker.go
As discussed in https://github.com/moby/buildkit/issues/2965, the current rootless containerd worker doesn't allow fallbacks when it can't access to the containerd socket (e.g. by permission denied). But we should perform a fallback to keep the backward compatibility with the previous version of buildkitd.
This commit fixes this issue by adding a fallback logic for the case when buildkitd failed to access to the containerd socket.
main
```console
$ rootlesskit buildkitd --addr=unix:///tmp/buildkit/buildkitd.sock
INFO[2022-07-19T01:49:45Z] auto snapshotter: using overlayfs            
INFO[2022-07-19T01:49:45Z] found worker "8envtv9nxu2808m374pct8b4z", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:2f891249d0b4 …
```
=> rootless: containerd worker: Add fallback when buildkitd cannot access to conainerd

frontend/gateway/gateway.go, solver/errdefs/context.go, solver/jobs.go, solver/llbsolver/bridge.go, source/containerimage/pull.go
This should fix the `EOF` errors happening more frequently in the CI.
The problem is that when context is canceled in the middle of a fetch stream(grpc stream pushing to containerd), in certain conditions it ends with `EOF` errors instead of cancel error what actually triggered the case. This is deep in containerd libraries so can't be fixed here so instead we need to have more exception cases on checking the errors.
The errors are cached both in solver and in the image resolver so I combined them both to use same helper function.
=> fix cancellation error not being detected and erroneously cached

client/client_test.go, client/llb/source.go
oci-layout source is platform-scpecific, we should use provided
platform to resolve correct image.
Now I can see the problem with building for another arch and seems we reuse image with host arch for build: https://github.com/linuxkit/linuxkit/pull/3797#issuecomment-1189217020
=> Add oci-layout to platformSpecificSource

README.md, docs/annotations.md
The annotations syntax described in the README is helpful as a reference, but not useful to learn how annotations work. This new piece of documentation should help fill that role, to help introduce users to how to use the new feature.
=> docs: add dedicated annotations guide with examples

solver/llbsolver/solver.go
Fixes an issue with bake's progress output, where multiple exporters of the same type might be invoked, resulting in the logs writing over each other within the same section. Additionally, this will be important in the context of #2760, where the progress logs per output need to be appropriately separated.
Sample bake file:
```hcl
group "default" {
targets = ["foo", "bar", "baz"]
}
target "foo" {
target = "foo"
tags = [
"docker.io/x/y:foo"
]
output = ["type=image,push=true,registry.insecure=true"]
}
target "bar" {
target = "bar"
tags = [
"docker.io/x/y:bar"
]
output = ["type=image,push=true,registry.insecure=true"]
}
target "baz" {
target = "baz"
tags = [
"docker.io/x/y:baz"
]
output = ["type=image,push=true,registry.insecure=true"]
}
```
Before:
```
...
=> [bar] exporting to image …
```
=> Ensure exporter progress logs are properly keyed

solver/llbsolver/file/refmanager.go, solver/llbsolver/ops/file.go
Now buildkit ignore `llb.customname` when use fileOpCopy.
The histroy will always `fileop target`
=> feat: fileop description could be set by vertex name

README.md
- `orange` is not a named color anymore.
- A colon (`:`) is the correct separator.
=> Fix `BUILDKIT_COLORS` example in README

frontend/dockerfile/docs/reference.md
As discussed with @thaJeztah, it's better to use a stub file and maintain the frontmatter section upstream.
=> docs(dockerfile): remove frontmatter section

exporter/containerimage/export.go, util/grpcerrors/grpcerrors.go
- Extract containerimage export push function
- Wrap push error with target name
- Use original error's message for gRPC error
Fixes #2019.
Registry push error from buildx before this change:
```
=> ERROR exporting to image                                                                                                                                                                                1.1s
=> => exporting layers                                                                                                                                                                                     0.0s
=> => exporting manifest sha256:d2cfb97f444d76147c440c6b86b333d388735b75b3644718cb5a4e0ad4e23762 …
```
=> Add context to registry push errors

util/resolver/retryhandler/retry.go
This lets code which embeds BuildKit override the default value of 8
seconds.
=> Expose maximum retry backoff as a variable

frontend/gateway/forwarder/forward.go, frontend/gateway/gateway.go, solver/llbsolver/bridge.go, solver/result.go
Previously, a frontend returning two identical references caused a
double-release error, as the gateway expects each ref to be unique.
However, there are scenarios where a frontend might reasonably be
expected to provide identical refs, e.g. for 2 platforms that have
binary compatibility, or for the upcoming attestations use-case.
To solve this issue, we refactor the ResultProxy implementation to
support cloning. Since the underlying Result supports reference
counting, we can avoid needing to add another layer of refcounts, and
simply clone the underlying refs.
Additionally, we then use the new Cloning functionality in the gateway
and forwarder (e.g. dockerfile) frontends, and ensure that the same
ResultProxy is never returned twice in a result. This means that
identical refs over the …
=> Clone ResultProxy at gateway boundaries

client/diskusage.go, client/info.go, cmd/buildctl/common/common.go, cmd/buildctl/debug/info.go, cmd/buildctl/debug/workers.go, cmd/buildctl/diskusage.go, cmd/buildctl/prune.go
- `buildctl du --format '{{json .}}'`: the template is applied to `[]*UsageInfo`
- `buildctl prune --format '{{json .}}'`: the template is applied to `UsageInfo`
- `buildctl debug info --format '{{json .}}'`: the template is applied to `*Info`
```console
$ buildctl du --format '{{json .}}'
[{"id":"s1d9pk3439ap6e5tt67bndctk","mutable":false,"inUse":false,"size":8979670,"createdAt":"2022-07-31T06:57:11.046458864Z","lastUsedAt":"2022-07-31T06:57:13.862022729Z","usageCount":1,"parents":null,"description":"pulled from docker.io/library/alpine@sha256:7580ece7963bfa863801466c0a488f11c86f85d9988051a9f9c68cb27f6b7872","recordType":"regular","shared":false},{"id":"u0nmub83lksjb9qu04y23v48m","mutable":true,"inUse":false,"size":2805760,"createdAt":"2022-07-31T06:57:11.68658936Z","lastUsedAt":"2022-07- …
```
=> `buildctl (du|prune|debug info)`: support `--format {{json .}}`

.golangci.yml, frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile2llb/convert_addgit.go, frontend/dockerfile/dockerfile2llb/convert_noaddgit.go, frontend/dockerfile/dockerfile_addgit_test.go, frontend/dockerfile/docs/reference.md, frontend/dockerfile/instructions/commands.go, frontend/dockerfile/instructions/parse.go, frontend/dockerfile/release/labs/tags, util/gitutil/git_ref.go, util/gitutil/git_ref_test.go
e.g.,
```dockerfile
FROM alpine
ADD --keep-git-dir=true https://github.com/moby/buildkit.git#v0.10.1 /buildkit
```
Close #775
Expected to be used with:
- https://github.com/moby/buildkit/pull/2943
=> dockerfile (labs): implement `ADD <git ref>` 

client/solve.go
This fixes what appears to be a bug from an old refactor to allow
shared sessions:
https://github.com/moby/buildkit/commit/ef58b61d83f9030f54355ef0b68424ef8519fd75
Without this, the session cannot really be shared effectively since it always closed by the first solve.
As discussed in slack: https://dockercommunity.slack.com/archives/C7S7A40MP/p1658286226946059
There are no current users outside the openllb/hlb project, so should not have an impact:
https://sourcegraph.com/search?q=context:global+SessionPreInitialized+-file:%28%5E%7C/%29vendor/+&patternType=literal
cc @aaronlehmann
=> do not close sessions after client solve if pre-initialized

client/llb/sourcemap.go, client/llb/state.go, client/llb/state_test.go
When a LLB contains duplicated vertcies with different source information, it's possible that some of the location infomations are lost.
This is make it difficult to do source-level debugging for some vertecies.
This commit fixes this issue.
e.g.
```Dockerfile
FROM ghcr.io/stargz-containers/ubuntu:20.04-org AS a
FROM ghcr.io/stargz-containers/ubuntu:20.04-org AS b
FROM scratch
COPY --from=a / /
COPY --from=b / /
```
Location info of `FROM` at line 2 is lost.
```json
{
"locations": {
"sha256:20ed82fdf481a640454f8113dde5f2e292c725b9b0dff5082c6a3b0c9470e186": {
"locations": [
{
"ranges": [
{
"start": {
"Line": 1
},
"end": {
"Line": 1
}
}
]
}
]
},
"sha256:f1768aff48a1c6860a01777144ff6eea79748963a56aa490f61680e2e37c732c": {
"locations": [
{
"ranges": [
{
"start": {
"Line": 4
},
"end": { …
```
=> Avoid losing source location information when vertices duplicate

worker/containerd/containerd.go, worker/label/label.go, worker/runc/runc.go, worker/worker.go
follow-up https://github.com/docker/buildx/pull/1260#discussion_r941397989
=> worker: move labels const to its own package

frontend/dockerfile/docs/reference.md
Just close the quote and add a suitable term. :slightly_smiling_face:
=> Fix cut-off link text to "get started" tutorial

frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_test.go
Fixes image build contexts not respecting the platform specified in the
Dockerfile `FROM --platform` argument.
Before this change buildkit always resolves images using the target
platform, but `FROM` may specifiy something else (such as
$BUILDPLATFORM).
=> Pass platform arg for stage state to ContextByName

frontend/dockerfile/docs/reference.md
I was wondering how using `--mount=type=cache` for Apt data would work on a CI server where builds might happen in parallel, considering that just two parallel Apt commands on a desktop system won't work. I found my answers in moby/buildkit#1662 and moby/buildkit#455, and thought it might be useful to gather them in the reference for future users.
=> Add "sharing=locked" to Apt cache example

frontend/gateway/container.go, frontend/gateway/forwarder/forward.go, frontend/gateway/gateway.go
Even when client does not release a container it should
be released automatically on disconnect.
This is buildkit-side fix for https://github.com/docker/buildx/pull/1257
@ktock @coryb 
=> frontend: make sure interactive containers are released on disconnect

frontend/subrequests/outline/outline.go
These newlines accidentally go to stdio. If this happens
at the wrong time it blocks grpc.
=> dockerfile: fix writing to wrong writer for outline response

.github/workflows/build.yml, .github/workflows/dockerd.yml
follow-up https://github.com/moby/buildkit/pull/3024#issuecomment-1215501319
Align test flags for linux and windows runners.
I tested with an extended matrix for windows runners: https://github.com/crazy-max/buildkit/actions/runs/2866740805
* `windows-2019` / `go 1.18.1`: `github.com/moby/buildkit/util/flightcontrol	713.146s	coverage: 65.8% of statements`
* `windows-2022` / `go 1.18.1`: `github.com/moby/buildkit/util/flightcontrol	444.752s	coverage: 65.8% of statements`
* `windows-2019` / `go 1.18.2`: `github.com/moby/buildkit/util/flightcontrol	804.799s	coverage: 65.8% of statements`
* `windows-2022` / `go 1.18.2`: `github.com/moby/buildkit/util/flightcontrol	338.622s	coverage: 65.8% of statements`
* `windows-2019` / `go 1.18.3`: `github.com/moby/buildkit/util/flightcontrol	600.374s …
=> ci: align test flags

.github/workflows/buildx-image.yml, .github/workflows/validate.yml
@jedevc found an issue with the frontend in the lint step: https://github.com/moby/buildkit/runs/7856267216?check_suite_focus=true#step:4:44
```
#5 DONE 4.8s
lint.Dockerfile:1
1 | >>> # syntax=docker/dockerfile-upstream:master
2 |     
3 |     FROM golang:1.18-alpine
error: failed to solve: frontend grpc server closed unexpectedly
```
but debug logs are not available for this step unfortunately.
=> ci: missing buildkitd debug flag for some steps

client/client.go, hack/dockerfiles/lint.Dockerfile
Signed-off-by: Pranav Pandit <pranavp@microsoft.com>
=> Remove deprecated function call to fix lint error

util/network/cniprovider/cni.go
👋 I'm using Buildkit's CNI support in a project of mine and found that I need to additionally configure the [`firewall` plugin](https://www.cni.dev/plugins/current/meta/firewall/), otherwise starting Docker seems to break network connectivity.
Configuring this plugin requires me to switch to a "chained CNI config" which is a special type of config:
* it has to be named `.conflist` in order for `cnitool` to recognize it as one
* it has to be passed to `go-cni` using `cni.WithConfListFile` rather than `cni.WithConfFile`
I opted to double down on `cnitool`'s behavior here to keep the distinction from bubbling up to separate fields in `buildkitd.toml`, but I'm happy to do that instead.
=> support .conflist CNI configs

solver/jobs.go
Fixes https://github.com/moby/buildkit/issues/3040
Exec could sometimes return nil, which would then result in a segmentation fault, as the code attempts to access a field in the nil
result to return. This patch introduces a sanity check before accessing any parts of the field.
=> solver: forward nil return value from sharedOp.Exec

session/grpc.go
This adds configuration values, and logging for the gRPC healthcheck ping. By adjusting these values larger, you can get builds with many/large files to work in a bandwidth-starved environment.
Sample configuration section:
```
[health]
frequency = "10s"
timeout = "1m"
allowedFailures = 3
```
This config is completely optional, and leaving it blank (or omitting it) maintains the old behavior.
It also adds logging. A debug message for each completed healthcheck, and a warning for each failure. It also prints when it cancels the context, so if you do have odd cancellations in your use case, they have a chance at being traced back to here. Here is a small log snippet with some failing and recovering happening:
```
time="2022-08-02T22:28:02Z" level=debug msg="diff applied" d=91.038907ms …
```
=> Add config, logging for healthcheck

frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile_test.go
Fixes https://github.com/moby/buildkit/issues/3033
Config from the OCI source was previously not correctly parsed and returned from the contextByName function, preventing fields like the WorkingDir from correctly being propogated through.
This fix ensures that the config is correctly json-parseable, and that the data is properly returned.
CC @deitch
=> dockerfile: fix oci source to load image config data

Dockerfile, client/client_test.go, executor/containerdexecutor/executor.go, executor/runcexecutor/executor.go, hack/fixtures/dns-cni.conflist, util/network/cniprovider/cni.go, util/network/host.go, util/network/network.go, util/network/none.go, util/testutil/integration/containerd.go, util/testutil/integration/dockerd.go, util/testutil/integration/oci.go, util/testutil/integration/run.go
This PR passes the hostname along to the network provider. The CNI provider sets it as `K8S_POD_NAME`, the rest ignore it.
My goal is to be able to use the [`dnsname` CNI plugin](https://github.com/containers/dnsname) for inter-container networking in Buildkit. Using DNS works great because it lets me keep non-reproducible values like IP addresses out of LLB, maximizing cache reuse for builds that depend on services.
The `dnsname` plugin uses the "container name" as its address, which it reads from an arg called `K8S_POD_NAME`. This arg seems to be used by other CNI plugins too. It's kind of a bummer that this arg name isn't something more generic. This plugin is actually designed for `podman` which sets the same arg; it seems to be a de-facto standard at this point. :/
The hostname seems …
=> cni: set hostname as K8S_POD_NAME

examples/buildctl-daemonless/buildctl-daemonless.sh
we use [buildctl-daemonless.sh](https://github.com/moby/buildkit/blob/master/examples/buildctl-daemonless/buildctl-daemonless.sh) inside a [rootless-pod](https://github.com/moby/buildkit/blob/master/examples/kubernetes/pod.rootless.yaml) based on `moby/buildkit:master-rootless` to perform our builds and call it via a CI/CD tool, which returns a non-zero exit code, as the trap cannot kill the process, as it is already gone, in case everything went fine
so we need to catch the error code from kill, which tries to kill a process that doesn't exist anymore and the suggestion is to just add `|| true`, because we don't care about the exit code of kill
```
#17 DONE 4.2s
sh: can't kill pid 65: No such process
command terminated with exit code 1
```
not sure if this script is automatically baked …
=> ignore if kill can't find pid that is already gone

client/solve.go, control/control.go, solver/llbsolver/bridge.go
Fixes #2974.
I've kept [the server-side code for translating the legacy request](https://github.com/moby/buildkit/blob/f8a60e2c1de918bc6a114fb9ae9381cd37407efb/control/control.go#L216-L243) for now so that this will continue to work with existing clients. We should be able to delete this once enough clients have been updated, perhaps in the following release?
I've also added some simple validation in the client for the `ref` attr on registry cache options, and some extra context around errors from the `ResolveCacheExporterFunc`s.
=> Stop using legacy cache import/export in client

solver/jobs.go
Follow up to #3043.
We introduce a new boolean `execDone` to track whether we've successfully completed an `Exec` call in the past, since `nil` is a possible return value from `Exec`.
We have some similar logic for `cacheDone` set by `CacheMap`, hence the name of the new bool, but I wonder if we might want to handle `nil` return values for that as well? Not sure if that would ever trigger, and also not super familiar with the logic here :eyes:
https://github.com/moby/buildkit/blob/c58f1286e62cd98fc31526b54d7261fa024942cb/solver/jobs.go#L747-L752
=> solver: correct cache nil return value in Exec

exporter/containerimage/image/docker_image.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile2llb/image.go, util/imageutil/schema1.go, util/imageutil/schema1_test.go
fix bug #3052
Original `convertSchema1ConfigMeta` fuction using
the wrong `ocispec.Image` type to unmarshal schemaV1
image config, Which miss OnBbuild field, the correct
`Image` type was defined in `frontend/dockerfile/dockerfile2llb/image.go`,
I move its definition to `exporter/containerimage/image`, then both 
package `util/imageutil` and `frontend/dockerfile` could 
use the correct `Image` type.
Signed-off-by: frank yang <yyb196@gmail.com>
=> fix bug that cann't recognize ONBUILD in schemaV1 img

client/client_test.go, exporter/containerimage/export.go, exporter/containerimage/opts.go, exporter/containerimage/writer.go, exporter/oci/export.go, frontend/dockerfile/dockerfile_test.go, util/testutil/imageinfo.go
Follow up to #2935, dependent on #3038.
The new annotations and attestations features both utilize annotations in the OCI image format. Many registries allow setting these annotation fields on docker formats, however, notably, GCR will reject these objects (see https://github.com/moby/buildkit/pull/1730) and only allow them for OCI media types.
To work around this, we enable oci-mediatypes when annotations that require OCI are enabled by the user, printing a warning to the user, similar to how we already do for stargz compression.
In the long-term, we should want to look at switching the default for oci-mediatypes to `true`, so enabling this for users who want to use the new annotations and attestations is a good way to test drive this, and try to catch any potential issues that might …
=> Force oci-mediatypes for containerimage outputs that utilize annotations

README.md, cache/remotecache/s3/s3.go
fixes #3056 
was looking first at an issue using github actions and s3 cache exporter: https://github.com/docker/build-push-action/issues/647. this will partially fix it but also need client-side support on buildx so user can use `aws-actions/configure-aws-credentials` in gha along with `docker/build-push-action`.
cc @bpaquet
=> cache(s3): handle session token for temporary credentials

util/progress/progressui/printer.go
This edge case was already handled for `CANCELED` or `ERROR`, but not `DONE` (or `CACHED`, which shouldn't have logs, but 🤷).
Before:
```console
$ docker buildx build --progress=plain --no-cache - <<<$'FROM bash\nRUN echo -n no newline'
...
#5 [2/2] RUN echo -n no newline
#5 0.268 no newline#5 DONE 0.3s
...
```
After:
```console
$ docker buildx build --progress=plain --no-cache - <<<$'FROM bash\nRUN echo -n no newline'
...
#5 [2/2] RUN echo -n no newline
#5 0.268 no newline
#5 DONE 0.3s
...
```
=> Fix no-newline-at-end-of-RUN output issue

solver/llbsolver/mounts/mount_test.go
Follow up to https://github.com/moby/buildkit/pull/3031: some tests have a hardcoded time delay in them, so timeouts need to be increased there as well.
The `TestCacheMountLockedRefs` seems to often fail on windows, see an [example](https://github.com/moby/buildkit/runs/8095275332?check_suite_focus=true#step:5:974)). Hopefully no other tests should need increasing.
=> llbsolver: increase test timeout for mount lock tests

solver/llbsolver/solver.go
Follows up #3036.
Somehow some duplicate code ended up in the exporter, resulting in `.Result()` called twice on each `ResultProxy` when exporting multiple `Refs`. The `ConvertResult` call handles the conversions completely, so we don't need the loop.
=> solver: fixup generic result conversion

solver/llbsolver/mounts/mount.go
This is a somewhat pedantic edge case, but I think we should create the mount point for secret files even if the source secret file is empty.  Otherwise, it is hard to debug why secrets are not showing up when requested in the LLB.  Currently, they are just silently ignored which was pretty confusing and caused me to waste time debugging my pipeline only to finally realize my secrets were corrupt and empty.
If allowing an empty secret mount is not acceptable, perhaps we could just add a warning to the buildkit log to indicate we are ignoring the empty mount, although I suspect other users might not have ready access to the buildkit logs and maybe continue to be confused like me.
=> mount empty secrets

frontend/dockerfile/instructions/parse.go, frontend/dockerfile/instructions/parse_test.go, frontend/dockerfile/parser/testfiles/health/Dockerfile, frontend/dockerfile/parser/testfiles/health/result
- fixes https://github.com/docker/cli/issues/3771
While these intervals have a minimum value when set:
// MinimumDuration puts a minimum on user configured duration.
// This is to prevent API error on time unit. For example, API may
// set 3 as healthcheck interval with intention of 3 seconds, but
// Docker interprets it as 3 nanoseconds.
const MinimumDuration = 1 * time.Millisecond
It should be possible to set them to `0` (which is teh default). This patch
updates the Dockerfile parser to use the same logic as the docker daemon uses;
if healthConfig.StartPeriod != 0 && healthConfig.StartPeriod < containertypes.MinimumDuration {
return errors.Errorf("StartPeriod in Healthcheck cannot be less than %s", containertypes.MinimumDuration)
}
0 is the default value, so should be ok to explicitly …
=> frontend: fix Healthcheck intervals and retries not accepting default values

cache/manager.go
- depends on https://github.com/moby/buildkit/pull/3079
- back port of https://github.com/moby/buildkit/pull/2177
- fixes https://github.com/moby/buildkit/issues/2157
- fixes https://github.com/moby/buildkit/issues/2061
remove() needs to be called while holding the manager lock
(cherry picked from commit 5429fe1b6369e74bde267bda1186410d004962ee)
=> [0.8 backport] cache: avoid concurrent maps write on prune

cache/metadata/metadata.go
- depends on https://github.com/moby/buildkit/pull/3079
- back port of https://github.com/moby/buildkit/pull/2178
- fixes https://github.com/moby/buildkit/issues/2111
- relates to https://github.com/containerd/containerd/pull/4855
The locks usage is mixed up because two locks separate locks
are actually needed. With a specific lock, calls to SetValue
can be protected.
(cherry picked from commit 976b7e9a972f36254a72653b552b58f990812bfd)
=> [0.8 backport] metadata: hold lock on storageitem update

exporter/containerimage/image/docker_image.go, frontend/dockerfile/dockerfile2llb/image.go
The OCI image spec now supports has a Variant field, so this custom field is no longer needed.
=> exporter/containerimage/image: Image: remove custom Variant field

.github/workflows/build.yml, .github/workflows/buildx-image.yml, .github/workflows/dockerd.yml, .github/workflows/validate.yml, client/client_test.go, frontend/dockerfile/dockerfile_test.go
Carry changes from https://github.com/moby/buildkit/pull/3003 related to missing skip tests for dockerd worker. Also removes concurrency check in dockerd workflow otherwise we can only trigger one run at a time.
=> integration: skip for dockerd

frontend/dockerfile/docs/reference.md
I see 2nd and 3rd row deliver same meaning in `different ENTRYPOINT / CMD combinations:` table, hence one can be deleted to not confuse people.
Also last row contradicts below line from [CMD](https://docs.docker.com/engine/reference/builder/#cmd):
If CMD is used to provide default arguments for the ENTRYPOINT instruction, both the CMD and ENTRYPOINT instructions should be specified with the JSON array format. 
In last row of the table, CMD is not in JSON array format.
Please clarify/suggest what is correct behaviour. I can add suggested changes to this PR.
Signed-off-by: Jitender Kumar <jitender.kumar@intel.com>
=> [reference.md] remove duplicate entry from `different ENTRYPOINT / CMD combinations` table

cmd/buildctl/build.go
This ensures that the new oci-layout can be loaded using buildctl (see https://github.com/moby/buildkit/pull/2827#discussion_r970570028).
Example usage:
```
buildctl --addr tcp://localhost:1234 build \
--frontend=dockerfile.v0 \
--local context=. --local dockerfile=. \
--opt context:foo=oci-layout://foodir@sha256:79a06bdbfbf27b365be61ca38646b07b451681475c284ad79deed506ab192917 \
--oci-layout foodir=./path/to/oci/dir
```
Previously, the `--oci-layout` flag was not registered with cobra, so could not be provided correctly.
CC @deitch @tonistiigi
=> buildctl: define oci-layout flag

cmd/buildkitd/config/config.go, cmd/buildkitd/main.go, cmd/buildkitd/main_containerd_worker.go, cmd/buildkitd/main_oci_worker.go, control/control.go, docs/buildkitd.toml.md, executor/containerdexecutor/executor.go, executor/runcexecutor/executor.go, util/network/cniprovider/cni.go, util/network/cniprovider/createns_linux.go, util/network/cniprovider/createns_unix.go, util/network/cniprovider/createns_windows.go, util/network/host.go, util/network/network.go, util/network/none.go, worker/base/worker.go, worker/containerd/containerd.go, worker/runc/runc.go, worker/worker.go, worker/workercontroller.go
This adds `netNSPoolSize` pool options which allow setting a target network namespace pool size. buildkitd will create this number of network namespaces at startup (without blocking). When a container execution finishes, the network namespace gets returned to the pool. If the pool goes above the target size, there is a grace period to allow network namespaces to be reused, and if this passes without reuse, the extra namespaces will be released.
=> Add network namespace pool support

README.md, client/solve.go
This follows up on https://github.com/moby/buildkit/pull/1295:
> LGTM, but we need this in --export-cache as well.
(which never seemed to make it in)
Allow overriding the tag field for the local cache, which enables "scoping" cache exports, to allow multiple outputs to a single location.
I've also reworked the `if` statement that was added to read the `tag` parameter, which is quite challenging to mentally parse.
=> Allow `tag` parameter for cache exporter `type=local`

source/containerimage/ocilayout.go, source/containerimage/pull.go
Split out timeout fix from: https://github.com/moby/buildkit/pull/3118.
In the scenario with no session id, then the oci-layout resolver would still attempt to load a caller with the empty session id. This inevitably failed, and would fallback to any caller, but this would take 5 seconds to fail with the configured timeout.
In a fresh pull of an OCI image context, this could take up to 15 seconds, as 3 separate calls to the relevant functions would be made.
This patch fixes the issue by correctly identifying this case, and directly falling through to any caller. Additionally, if a session id is present, it will always be loaded with no fallback available. To do this consistently, the helper methods are refactored into a more consistent withCaller function.
CC @deitch
=> source: avoid hang if no session id for oci-layout

README.md
Wikimedia's Release Engineering Team wrote Blubber in 2017 to standardize its image builds. The canonical implementation was a YAML-to-Dockerfile transpiler but has recently been refactored to be used as a BuildKit frontend.
=> README.md: Add Blubber to the list of frontends

docs/attestation-storage.md
Fixes #3128.
This PR adds attestation storage details as they are currently implemented.
In the future, changes to the format and storage of attestations should update both the implementation and the corresponding docs here.
=> Add attestation storage details

frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile_test.go
Mentioned by @ciaranmcnulty on [the community slack](https://dockercommunity.slack.com/archives/C7S7A40MP/p1664121664955829).
Previously, there was no simple way to create an empty named context, requiring external steps such as creating an empty directory. This change allows a single one-line context to represent the empty state.
Example usage:
```console
docker buildx build . --build-context alpine=docker-image://scratch
```
=> dockerfile: allow named context for docker-image://scratch

docs/rootless.md, examples/kubernetes/README.md, examples/kubernetes/deployment+service.rootless.yaml, examples/kubernetes/job.rootless.yaml, examples/kubernetes/pod.rootless.yaml, examples/kubernetes/statefulset.rootless.yaml
Dockerfile has `VOLUME /home/user/.local/share/buildkit` by default too, but the default VOLUME does not work with rootless on Google's Container-Optimized OS as it is mounted with `nosuid,nodev`.
So the volume has to be explicitly mounted as an `emptyDir` volume.
Tested with GKE Autopilot 1.24.3-gke.200 (kernel 5.10.123+, containerd 1.6.6).
Fix #879
Thanks to Andrew Grigorev (@ei-grad) and Ben Cressey (@bcressey).
=> rootless: support Google Container-Optimized OS (Fix ` Options:[rbind ro]}]: operation not permitted` errors)

docs/rootless.md, examples/kubernetes/README.md, examples/kubernetes/deployment+service.rootless.yaml, examples/kubernetes/job.rootless.yaml, examples/kubernetes/pod.rootless.yaml, examples/kubernetes/statefulset.rootless.yaml
=> [v0.10 backport] rootless: support Google Container-Optimized OS

README.md
Moved the repo from https://github.com/AkihiroSuda to https://github.com/reproducible-containers
=> README.md: AkihiroSuda/buildkit-nix -> reproducible-containers/buildkit-nix

source/git/gitsource.go
WalkDir is more performant as it doesn't perform an os.Lstat on every visited file or directory.
=> source/git: Snapshot(): use filepath.WalkDir

client/client_test.go, exporter/oci/export.go
The annotation value can be now overridden with `--output type=oci,annotation-manifest-descriptor.org.opencontainers.image.created=...`.
=> exporter/oci: allow overriding `org.opencontainers.image.created`

.github/workflows/build.yml
GitHub has [deprecated the `set-output` command as of today](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), and introduced a new file to write outputs to in the same format already used for environment variables.
=> Replace deprecated set-output workflow command

client/client_test.go, control/control.go, exporter/containerimage/exptypes/types.go, exporter/containerimage/opts.go, exporter/containerimage/writer.go, exporter/local/export.go, exporter/tar/export.go, exporter/util/epoch/parse.go, frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_test.go, frontend/dockerfile/docs/reference.md, solver/pb/caps.go
addresses #1058
Allows reproducible timestamps for layer and image timestamps.
Implemented as a frontend-opt because in the future, the same option could be detected by frontend for custom behavior
and the same value should also apply timestamps for FileOps. Definition for `SOURCE_DATE_EPOCH` can be found in https://reproducible-builds.org/docs/source-date-epoch/
In local and tar exporter, setting the build-arg sets overwrites the timestamp for the output files.
There is also a secondary implementation inside the Dockerfile frontend. This allows getting reproducible image manifests even on old buildkit, by just defining `#syntax` to point to new Dockerfile image.
In Dockerfiles the build-arg can also be exposed to inner processes by defining `ARG SOURCE_DATE_EPOCH` inside the stage.
This …
=> Add support for SOURCE_DATE_EPOCH

go.mod, go.sum, vendor/modules.txt
it's the same commit: https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.2...c182affec369
=> go.mod: matttproud/golang_protobuf_extensions v1.0.2 (use tag)

hack/azblob_test/test1/Dockerfile, hack/azblob_test/test2/Dockerfile, hack/s3_test/test1/Dockerfile, hack/s3_test/test2/Dockerfile
`s3` and `azblob` integration tests are flaky when pulling images from `mcr.microsoft.com` and `public.ecr.aws` mirrors like: https://github.com/moby/buildkit/actions/runs/3245518525/jobs/5323188241#step:5:1889
```
#3 [internal] load metadata for mcr.microsoft.com/mirror/docker/library/busybox:1.34
time="2022-10-13T20:43:49Z" level=error msg="/moby.buildkit.v1.frontend.LLBBridge/Solve returned error: rpc error: code = Unknown desc = mcr.microsoft.com/mirror/docker/library/busybox:1.34: failed to copy: httpReadSeeker: failed open: unexpected status code https://mcr.microsoft.com/v2/mirror/docker/library/busybox/blobs/sha256:475448aba2e23f23c3959720ce0140cc5303d87109e18ca9c63e0b6ae7b943d8: 500 Internal Server Error"
time="2022-10-13T20:43:49Z" level=error …
```
=> fix flaky s3 and azblob integration tests

.github/workflows/build.yml, frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
closes https://github.com/docker/buildx/issues/1295
Adds support for mips platforms of the dockerfile frontend image since https://github.com/tonistiigi/xx/pull/62 has been merged.
Not possible for the main Dockerfile atm as alpine only supports big-endian mips packages. Does not seem to have been updated for about a year: http://dl-cdn.alpinelinux.org/alpine/edge/releases/mips64/ so not sure that's a priority on their side.
If we want to add support in the main Dockerfile, I guess we have to use a debian base image for this arch.
cc @tianon 
=> dockerfile: release frontend for mips platforms

util/testutil/integration/dockerd.go
This env-var was added in to prevent the Swarm integration tests (which load images, and because of that don't have a registry-digest) from pulling images; see https://github.com/moby/moby/commit/e2226223e614716749cdb7701a130c7449f5f854
Given that BuildKit integration tests don't run Swarm services, this env-var should not be needed here.
=> util/testutil/integration: remove DOCKER_SERVICE_PREFER_OFFLINE_IMAGE

Dockerfile, source/git/gitsource.go, source/git/gitsource_test.go
Prevent git commands we run from reading the user or system configuration, or cloning submodules from the local filesystem.
Signed-off-by: Cory Snider <csnider@mirantis.com>
=> source/git: isolate git from local system

client/build_test.go, frontend/gateway/gateway.go
Without this, the included test case will result in buildkitd panicking.
Diagnosed here: https://github.com/dagger/dagger/pull/3330#discussion_r993789155
Also possibly related to https://github.com/moby/buildkit/issues/3134 (unless that one was already fixed)
=> Check nil worker ref in llbBridgeForwarder.

.golangci.yml, cache/contenthash/tarsum.go, util/grpcerrors/grpcerrors.go
`structcheck` is abandoned, and has been replaced by the `unused` linter. See https://golangci-lint.run/usage/linters/#structcheck for more information.
> The owner seems to have abandoned the linter. Replaced by unused.
=> lint: remove structcheck

frontend/dockerfile/dockerfile_test.go
- taken from https://github.com/moby/buildkit/pull/3206
=> testNamedImageContextPlatform skip direct push with dockerd

.github/workflows/build.yml, .github/workflows/buildx-image.yml, .github/workflows/dockerd.yml, .github/workflows/validate.yml, frontend/dockerfile/dockerfile_test.go
backports:
- https://github.com/moby/buildkit/pull/3031
- https://github.com/moby/buildkit/pull/3101
- https://github.com/moby/buildkit/pull/3207
=> [0.10 backport] integration: skip for dockerd

frontend/dockerfile/builder/build.go
Having the prefixes like this makes them easier to find, when they're with everything else.
=> chore: use private consts for dockerfile prefixes

docs/dev/README.md
Add links to the recording of the architecture overview session/slides to the dev docs.
=> docs: add links to architecture overview session

.github/workflows/build.yml, frontend/dockerfile/docs/reference.md
BuildKit overview and Dockerfile frontend sections have been added in https://github.com/docker/docs/pull/15958 and now cover "BuildKit", "External Dockerfile frontend" and "syntax" sections so we can just keep the actual Dockerfile specification. Same for "Usage" section with `docker build` moved to the new Build section and also reworked in https://github.com/docker/docs/pull/15958. cc @dvdksn
=> docs(dockerfile): update usage and syntax sections

cache/blobs.go, cache/blobs_linux.go, cache/blobs_nolinux.go, cache/converter.go, cache/manager_test.go, cache/refs.go, cache/remote.go, cache/remotecache/local/local.go, cache/remotecache/registry/registry.go, cache/remotecache/v1/cachestorage.go, exporter/containerimage/export.go, exporter/containerimage/opts.go, exporter/exporter.go, exporter/local/export.go, exporter/oci/export.go, exporter/tar/export.go, solver/llbsolver/solver.go, util/compression/compression.go, util/compression/estargz.go, util/compression/gzip.go, util/compression/uncompressed.go, util/compression/zstd.go, util/iohelper/helper.go
Introduce a new `compression.Type` interface, which needs
to be implemented for each compression type, by that we can
reduce the number of switch case statements and ensure that
we don't miss the handle of any compression types, and also
make more easily for supporting new compression types.
This is a commit for code improvement, so no logical changes.
A successful test can be found [here](https://github.com/imeoer/buildkit/actions/runs/3248812112).
=> compression: introduce compression.Type interface

client/client_test.go, frontend/dockerfile/dockerfile_test.go
follow-up https://github.com/moby/buildkit/pull/3205#pullrequestreview-1149745020
More skips required for dockerd worker. Also removes `println` in `testOCILayoutPlatformSource`.
=> integration: more skips for dockerd

exporter/local/export.go, exporter/oci/export.go, exporter/tar/export.go
This changes the output names in the buildkit progress output as follows:
`docker`:
- `"exporting to oci image format"` -> `"exporting to docker image format"`
`local`:
- `"exporting to client"` -> `"exporting to client directory"`
`tar`:
- `"exporting to client"` -> `"exporting to client tarball"`
=> exporter: clarify exporter names

.golangci.yml, client/client_test.go, frontend/dockerfile/dockerfile_ssh_test.go, frontend/dockerfile/dockerignore/dockerignore_test.go, session/auth/auth.go, solver/scheduler_test.go, source/git/gitsource_unix.go, util/archutil/check_unix.go, util/stack/stack.go, util/testutil/echoserver/server.go, util/testutil/integration/containerd.go, util/testutil/integration/registry.go, util/testutil/integration/run.go, util/testutil/integration/sandbox.go, util/tracing/otlptracegrpc/connection.go, util/winlayers/applier.go, util/winlayers/differ.go
Replaces https://github.com/moby/buildkit/pull/2449.
For the default excludes rules:
- Potential hardcoded credentials and implicit memory aliasing for giving lots of false positives on correct behaviour (e.g. where the addressed value never leaves the loop, or we break immediately after).
- TLS MinVersion warnings (we need to coordinate with other projects upstream if we want to do this).
- `net/http/cgi` blocklist, since it [errors for a vulnerability in a version of Go that we don't target](https://github.com/securego/gosec/blob/7f2308bd85afa9531ddba4f46f1e58fd53da0615/rules/blocklist.go#L85) (1.16, we now use generics so buildkit won't even compile with that version).
=> Add gosec to linters

cache/contenthash/checksum.go
Using filepath.Join() breaks convertPathToKey() on Windows. Windows should be able to deal with both forward and backslashes. Using backslashes in paths here, will break the way we generate cache keys. convertPathToKey() currently replaces '/' with 0. Changing every code path to accomodate the Windows specific path separator is a lot more involved than allowing Windows to just handle the forward slash paths.
=> Use path.Join to generate cache keys

client/build_test.go, frontend/gateway/gateway.go, worker/result.go
Fixes https://github.com/moby/buildkit/issues/3134
Incredibly obscure case. I was *accidentally* pushing images with no layers and then pulling them and trying to do an exec, the only reason I hit it. But worth a fix since it's a panic.
=> Fix nil panic on scratch ref release.

docs/buildkitd.toml.md, frontend/dockerfile/docs/reference.md
I'm working on the new BuildKit section on Docker docs website and wants to include the `buildkitd.toml.md` page but needs to format it a bit before.
Also fixes parse directive toc in dockerfile reference.
And carry changes from https://github.com/docker/cli/pull/1467. More needs to be carry from docker/cli repo but can do that in a follow-up: https://github.com/docker/cli/pulls?q=is%3Aopen+is%3Apr+label%3Aarea%2Fbuilder+label%3Akind%2Fdocs (cc @dvdksn)
=> Docs updates and fixes

.github/workflows/build.yml
Fix warning in our workflow:
```
upload-coverage
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: codecov/codecov-action
```
=> ci: update codecov action to v3

README.md
Adds [Depot](https://depot.dev) to the list of BuildKit users - we're running hosted BuildKit on behalf of our customers. 🙂 
Signed-off-by: Jacob Gillespie <jacobwgillespie@gmail.com>
=> Add depot.dev to the list of BuildKit users

cmd/buildkitd/config/config.go, cmd/buildkitd/main_containerd_worker.go, cmd/buildkitd/main_oci_worker.go, executor/containerdexecutor/executor.go, executor/oci/spec.go, executor/oci/spec_unix.go, executor/oci/spec_windows.go, executor/runcexecutor/executor.go, worker/containerd/containerd.go, worker/containerd/containerd_test.go, worker/label/label.go, worker/runc/runc.go, worker/runc/runc_test.go
=> Make SELinux labels opt-in (`--oci-worker-selinux=<BOOL>`)

executor/containerdexecutor/executor.go
Deleting a containerd task whose status is Created fails with a "precondition failed" error. This is because (aside from Windows) a process is spawned when the task is created, and deleting the task while the process is running would leak the process if it was allowed. Change the deferred `task.Delete` call to pass the `WithProcessKill` delete option so the cleanup has a chance to succeed in the event that the `p.Start` call inside `runProcess` returns an error.
Signed-off-by: Cory Snider <csnider@mirantis.com>
=> containerdexecutor: clean up task if Start() fails

frontend/dockerfile/instructions/commands.go, frontend/dockerfile/instructions/parse.go, frontend/dockerfile/parser/parser.go
:tada: Replaces #2952.
The parser documentation hasn't been updated in some time, so this patch adds some additional doc strings where relevant, and attempts to clean up the entire package to be more readable from a developer documentation point-of-view.
=> dockerfile: enhance parser documentation

client/client_test.go, exporter/containerimage/export.go
Fixes: https://github.com/moby/buildkit/issues/3212 When trying to build scratch images and unpacking is true, containerd worker results in a panic. In order to avoid this, unpack only when num layers are greater than 0.
Signed-off-by: Manu Gupta <manugupt1@gmail.com>
=> Do not unpack when there are no layers present.

cache/remotecache/azblob/exporter.go, cache/remotecache/export.go, cache/remotecache/gha/gha.go, cache/remotecache/inline/inline.go, cache/remotecache/s3/s3.go, client/client_test.go, control/control.go, solver/llbsolver/solver.go, solver/llbsolver/util/util.go, solver/llbsolver/util/util_test.go, solver/result/result.go
=> Multiple cache exports

.github/CONTRIBUTING.md, README.md, docs/images-readme.md
follow-up https://github.com/moby/buildkit/issues/3131
=> fix link to community slack

cache/metadata/metadata.go
This prevents unnecessary calls (and disk writes) to the metadata cache db when there are no items in the queue.
Some quick testing on my laptop with a cache containing 26,000 items; this change reduced buildkit startup time from roughly 46 seconds down to 2 seconds.
=> Skip boltdb update call when queue is empty

client/client_test.go, exporter/oci/export.go
=> OCI exporter: support SOURCE_DATE_EPOCH for "org.opencontainers.image.created"

.github/workflows/build.yml, Dockerfile, client/client_test.go
containerd 1.4 has reached EOL on March 3, 2022
https://github.com/containerd/containerd/blob/main/RELEASES.md
=> integration: remove containerd 1.4

exporter/containerimage/writer.go, util/imageutil/schema1.go
Use double spaces for JSON marshalling instead of triple spaces.
I noticed this first in https://github.com/moby/buildkit/pull/3240/files#diff-93b81ebb2d74a7ff89a643dfd137603e309b87754076de895b0c15dd4626a169L208, but there's a few other guilty culprits, as well as [this one in buildx](https://github.com/docker/buildx/blob/1f6612b118018028ab2ed5b01b85d500eb7cb556/util/imagetools/create.go#L141) found by @crazy-max.
I *assume* this is a mistake that's somehow been propagated via copy-paste-fu, instead of an intentional design decision?
=> chore: use double spaces when marshalling manifests/indexes

frontend/dockerfile/dockerfile_test.go, util/testutil/integration/run.go
As noticed in https://github.com/moby/buildkit/pull/3001#issuecomment-1282462464 by @DYefimov:
> FYI, there are two copies of testDockerfileAddArchiveWildcard inside the dockerfile_test.go allTests array:
https://github.com/moby/buildkit/blob/6bff1509/frontend/dockerfile/dockerfile_test.go#L92
https://github.com/moby/buildkit/blob/6bff1509/frontend/dockerfile/dockerfile_test.go#L95
Looks like a rebase mistake from a few years ago?
This PR removes the duplicate, and adds a panic to `TestFuncs that is triggered if a single function is added to a call of `TestFuncs` more than once to prevent this happening again in the future :tada:
=> Duplicate test runs

cmd/buildkitd/config/config.go, cmd/buildkitd/main_containerd_worker.go, cmd/buildkitd/main_oci_worker.go, executor/containerdexecutor/executor.go, executor/oci/spec.go, executor/oci/spec_unix.go, executor/oci/spec_windows.go, executor/runcexecutor/executor.go, worker/containerd/containerd.go, worker/containerd/containerd_test.go, worker/label/label.go, worker/runc/runc.go, worker/runc/runc_test.go, worker/worker.go
Cherry-pick
- #3014
- #3203
Cherry-picking #3203 was not clean, and resolved by removing `NetworkProviders: np`
<details>
<p>
```console
$ git cherry-pick -xsS bd57e5f6b8d0f9583c1f20cbe4867b0138848920
Auto-merging cmd/buildkitd/config/config.go
Auto-merging cmd/buildkitd/main_containerd_worker.go
Auto-merging cmd/buildkitd/main_oci_worker.go
Auto-merging executor/containerdexecutor/executor.go
Auto-merging executor/runcexecutor/executor.go
Auto-merging worker/containerd/containerd.go
CONFLICT (content): Merge conflict in worker/containerd/containerd.go
Auto-merging worker/containerd/containerd_test.go
Auto-merging worker/runc/runc.go
Auto-merging worker/runc/runc_test.go
error: could not apply bd57e5f6... Make SELinux labels opt-in (`--oci-worker-selinux=<BOOL>`)
hint: After resolving the …
```
=> [0.10 backport] Make SELinux labels opt-in (`--oci-worker-selinux=<BOOL>`)

.github/workflows/build.yml, Dockerfile, go.mod, go.sum, vendor/github.com/tonistiigi/fsutil/walker.go, vendor/modules.txt
fixes #3257
- Brings in panic fix for #3257 https://github.com/tonistiigi/fsutil/pull/122 . This patch is the only difference in vendor and no branching of from upstream default branch was needed.
- Update Go to 1.18 in the main Dockerfile because 1.17 is EOL and would show up in the security scan of new release. There is no known (security) impact with this update.
=> [v0.10] fixes for v0.10.6

Dockerfile, hack/test
See https://github.com/moby/moby/blob/v20.10.21/hack/dind#L28-L38
Fix #3265
=> integration: add ENTRYPOINT to fix nested cgroup v2

docs/build-repro.md, frontend/dockerfile/dockerfile_buildinfo_test.go, util/buildinfo/buildinfo_test.go
- backport of https://github.com/moby/buildkit/pull/3275
- relates to https://github.com/moby/moby/pull/44452
Some tests were depending on the sha256sum of https://raw.githubusercontent.com/moby/moby/master/README.md
(cherry picked from commit ae97234682b1c6ccd746df7397259c43b40aa81c)
=> [v0.10 backport] moby/moby/master -> moby/moby/v20.10.21

exporter/containerimage/annotations.go, exporter/containerimage/export.go, exporter/containerimage/opts.go, exporter/containerimage/writer.go, exporter/oci/export.go
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/issues/3277, by preventing confusion around what functionality is supported.
This PR resolves two issues with annotation attachment, where inputs will be accepted even if they are not used - we should explicitly error in these cases.
1. Index + Index descriptor annotations are not supported for single platform builds produced by the Dockerfile so we should explicitly error (@tonistiigi, should we have a user accessible way to force this? We can the `FrontendAttrs["multi-platform"]` key, but could we also expose a `build-arg`? Automatically detecting annotations like attestations and using `ForceRefsProcessor` is possible but kind of ugly here, since we'd have to parse exporter options before doing a solve).
2. Valid platforms that …
=> Introduce annotation sanity checks

client/client_test.go, client/solve.go, cmd/buildctl/build/output.go, exporter/local/export.go, exporter/oci/export.go, source/containerimage/ocilayout.go
Fixes https://github.com/moby/buildkit/issues/1219.
This feature adds support for specifying `unpack=true` to the oci exporter options to unpack the resulting result for the client.
This requires changes to the client to ensure that when `unpack=true` is provided, we expose a directory instead of a single file.
Because of how the containerd API is designed, the image layout file structure is only directly exposed as part of the `archiveexporter.Export` method which produces a tar - so we need to unpack it on the buildkit server before syncing it back to the client. I can't quite work out if there's a better way to do this without needing to change the containerd API.
=> oci exporter: support exporting directories

cmd/buildctl/build.go, examples/dockerfile2llb/main.go, frontend/attestations/sbom/sbom.go, frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile2llb/convert_test.go, frontend/dockerfile/dockerfile_test.go, solver/llbsolver/proc/sbom.go
:hammer_and_wrench: Fixes #3185 
:arrow_up: Follows up #2983 
This patch adds `BUILDKIT_SBOM_SCAN_CONTEXT` and `BUILDKIT_SBOM_SCAN_STAGE` which can configure scanning of the build context and intermediate dockerfile stages respectively.
To use these, the underlying Dockerfile must declare these args, and optionally assign a default value. `BUILDKIT_SBOM_SCAN_CONTEXT` must either be set in the global meta args before a FROM or in the target stage, while `BUILDKIT_SBOM_SCAN_STAGE` must be set in each target stage.
The user can additionally override the values set in the Dockerfile to change the behavior.
=> BUILDKIT_SBOM_SCAN build args

frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_addchecksum_test.go, frontend/dockerfile/instructions/commands.go, frontend/dockerfile/instructions/parse.go
We cannot use checksum from environment variables (for example with `ADD --checksum=${HASH} ${LINK} /tmp/foo`), which made this option useless in cases when we define url using environment variables and adjust them using some logic around.
Let's add checksum field to Expand function to fill it before sending out.
PR contains implementation and test
=> Allow to use checksum in ADD from ENV

control/control_test.go
:arrow_up: Follow-up #3271 
Return args order is not guaranteed (since we use a map internally), so we need to make sure the test does not rely on order of returns.
=> test: fix flaky duplicate cache test

frontend/attestations/parse.go, frontend/attestations/sbom/sbom.go, frontend/dockerfile/dockerfile_test.go
:warning: Requires updates in [buildkit-syft-scanner](https://github.com/jedevc/buildkit-syft-scanner)
Since we construct the args for the image based on the Entrypoint + Cmd, we shouldn't error out early if no Cmd is set, but only if neither Entrypoint or Cmd are set.
Additionally, we should avoid setting BUILDKIT_SCAN_SOURCE_EXTRAS if no extras have been specified.
=> sbom: fix minor inconsistencies in sbom protocol

client/client_test.go, exporter/attestation/generate.go, exporter/containerimage/writer.go, exporter/local/export.go, exporter/tar/export.go, frontend/gateway/client/attestation.go, frontend/gateway/forwarder/forward.go, solver/llbsolver/proc/provenance.go, solver/result/attestation.go, solver/result/result.go, util/staticfs/merge.go, util/staticfs/merge_test.go, util/staticfs/static.go, util/staticfs/static_test.go
Implements the `local` exporter part of #3184.
The attestation extraction logic is moved to a separate utils package, so that other exporters can use it. Additionally, the bundling logic is slightly reworked, to add an explicit Unbundle step before Extracting. This ensures that the Extract method can perform a one-to-one translation from result.Attestations to intoto.Statements, which allows for deriving intermediate properties such as the Path.
The attestation files are exported similar to another platform ref, with file names equivalent to the original attestation files had (though this should be pretty easy to change if we'd prefer a separate output location specified by the user).
I'm not quite sure what to put for the `subject` field for intoto (unless there's a canonical way of …
=> Export attestations for local exporter

cache/contenthash/filehash.go, client/client_test.go
Fixes #3291
It is a bit of a mess to understand what cases `FileInfoHeader` fills in these values and in what cases it does not.
Draft as needs a regression test
@flx42
=> contenthash: fix uid/gid in contenthash

client/llb/source.go, frontend/dockerfile/builder/build.go, source/containerimage/ocilayout.go, source/containerimage/pull.go, source/identifier.go
:cherries: Cherry-picked off of https://github.com/moby/buildkit/pull/3118 (since it seems unlikely we'll take the functionality in the way that it's implemented for v0.11)
This PR introduces improvements to the user-facing error messages of the dockerfile oci-layout functionality. Essentially, we achieve this by using all of containerd's/distribution's reference parsers instead of doing manual string manipulation.
The main internal-api change that this introduces is combining the reference with the digest together in the OCILayout llb - we can just pass the whole thing together, instead of needing to later reconstruct it back together.
Signed-off-by: Justin Chadwell <me@jedevc.com>
=> Refactor reference parsing for oci-layout

client/client_test.go, executor/stubs.go, util/system/atime_unix.go, util/system/atime_windows.go
=> MountStubsCleaner: preserve timestamps

.golangci.yml, cache/compression_nydus.go, cache/manager_test.go, cache/refs.go, cache/remotecache/azblob/exporter.go, cache/remotecache/azblob/importer.go, cache/remotecache/azblob/utils.go, cmd/buildkitd/main.go, exporter/containerimage/annotations.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerignore/dockerignore.go, frontend/dockerfile/instructions/bflag.go, frontend/dockerfile/instructions/errors_unix.go, frontend/dockerfile/instructions/errors_windows.go, frontend/dockerfile/instructions/parse.go, frontend/dockerfile/parser/line_parsers.go, frontend/dockerfile/parser/parser.go, identity/randomid.go, snapshot/snapshotter_test.go, util/archutil/generate.go, util/compression/compression.go, util/compression/estargz.go, util/entitlements/security/security_linux.go, util/overlay/overlay_linux.go, util/resolver/authorizer.go, util/sshutil/keyscan.go, util/system/path_windows.go, util/tracing/otlptracegrpc/client.go, util/tracing/otlptracegrpc/errors.go
In general, we prefer to use `github.com/pkg/errors` wherever possible, since it provides stacktraces, and we try and enforce this in code-review. However, this is easy to forget (especially for me :smile:) - so we should provide a linting rule to ban using `fmt.Errorf`. This should stop these leaking through in future PRs.
This PR adds a linter rule to `forbidigo`, to ban this function, requesting that users switch to using the `errors` package. As part of this, we also need to update all the instances of `fmt.Errorf`, which was useful to cleanup some cases of code-rot.
=> chore: remove fmt.Errorf across the codebase in preference of errors.Errorf/Wrap

client/client_test.go, executor/stubs.go, util/system/atime_unix.go
On Linux, an empty directory is usually 4096 bytes, not 0, so we need an additional explicit check here.
Signed-off-by: Justin Chadwell <me@jedevc.com>
=> executor: stubs cleaner should remove empty directory mounts

api/services/control/control.pb.go, api/services/control/control.proto, client/client.go, client/diskusage.go, client/info.go, client/prune.go, client/solve.go, client/workers.go, cmd/buildctl/debug.go, cmd/buildctl/debug/logs.go, cmd/buildctl/debug/monitor.go, cmd/buildkitd/main.go, control/control.go, solver/llbsolver/history.go, solver/llbsolver/solver.go, solver/pb/generate.go, solver/progress.go, util/grpcerrors/grpcerrors.go, util/progress/multireader.go, worker/base/worker.go, worker/worker.go
fixes #3050
For testing 2 new commands added to `buildctl`:
```
buildctl debug monitor [--completed]
```
Will listen on event on new builds coming in and completing. If `--completed` is passed, then shows previous builds stored on disk.
```
buildctl debug logs [refid] [--progress=auto]
```
Shows logs for an active build. RefID can be obtained with the `monitor` command. Eventually, this would also work for completed builds.
=> add build history APIs

cmd/buildctl/debug/logs.go, exporter/containerimage/attestations.go
=> ci: unbreak linter

client/client_test.go, exporter/containerimage/attestations.go, frontend/dockerfile/dockerfile_test.go
:arrow_up: Follow-up https://github.com/moby/buildkit/pull/3258 and https://github.com/moby/buildkit/pull/3308
We should switch the tests to not use invalid spdx properties, to ensure we test the codepaths for the layer supplements. We also need to switch to using `assert.Subset` since (if done correctly), these maps will be populated with additional contents.
=> Tidy-up of SBOM layer supplements

client/client_test.go, exporter/local/export.go, exporter/local/fs.go, exporter/tar/export.go
:arrow_up: Follow-up to #3197
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/issues/3184 by adding attestations to the tar exporter (local exporter support added in #3197).
This PR refactors the `tar` exporter to share filesystem generation methods in common with the `local` exporter, which therefore lets it generate attestations in the same way.
This refactor is similar to the `ImageWriter` component shared between the `containerimage` and `oci` packages, except for this we have a `CreateFS` function for the `local` and `tar` packages.
=> Export attestations for tar exporter

exporter/attestation/unbundle.go, exporter/local/fs.go
:arrow_up: Follow-up https://github.com/moby/buildkit/pull/3197#discussion_r1025902880
Consistently validate all attestations when unbundling, to prevent inconsistent attestations error behavior across different exporters.
=> exporter: validate attestations on unbundle

go.mod, go.sum, vendor/modules.txt
- relates to https://github.com/moby/buildkit/pull/3236
- relates to https://github.com/moby/buildkit/issues/3187
This module made a whoopsie, and updated to `google.golang.org/protobuf` in a patch release, but `google.golang.org/protobuf` is not backward compatible with `github.com/golang/protobuf`.
Updating the minimum version to v1.0.4 which corrects this, to prevent users of buildkit as a module from accidentally pulling in the wrong version:
- v1.0.3 switched to use `google.golang.org/protobuf`; https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.2..v1.0.3
- This was reverted in v1.0.4 (which is the same as v1.0.2); https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.3..v1.0.4
- And a `v2` was created instead; …
=> go.mod: golang_protobuf_extensions v1.0.4 - prevent incompatible versions

frontend/dockerfile/docs/reference.md
Continuation of https://github.com/docker/docs/pull/8654. jedevc previously said:
> I think explicitly calling out how ENV variables are inherited is a good idea though, though it should be under that section rather that right after the named stages.
=> Document ENV inheritance in multi-staged builds

Dockerfile
related to https://github.com/moby/moby/issues/44570
Update to Alpine 3.17. For `riscv64` BuildKit image we use `alpine:edge` as this arch is not yet supported. This also enforces Alpine version for the golang image.
=> Dockerfile: update Alpine to 3.17

Dockerfile, client/client_test.go
follow-up #3350
Align Alpine version for the Go image to fix https://github.com/moby/moby/issues/44570.
Needs to backport
* https://github.com/moby/buildkit/pull/3269
=> [0.10] Dockerfile: enforce Alpine version for Go image

Dockerfile
Remove orphan `containerd-runtime` stage.
Was added in https://github.com/moby/buildkit/pull/666/files#diff-d4df02cc7c752c203625dc3d58ba3dcbda82247290de3554493a2ef1d50a25c0R181-R187 but doesn't look necessary anymore.
=> Dockerfile: remove containerd-runtime stage

cmd/buildkitd/constants_unix.go, cmd/buildkitd/constants_windows.go, cmd/buildkitd/main.go, cmd/buildkitd/main_containerd_worker.go, util/appdefaults/appdefaults_unix.go, util/appdefaults/appdefaults_windows.go
This change adds Windows specific default settings. I don't think there is a generic default path for CNI binaries and config files. For example, containerd uses ```C:\Program Files\containerd\cni\conf``` and ```C:\Program Files\containerd\cni\bin``` as defaults.
=> [Windows] Define defaults on Windows

go.mod, go.sum, vendor/github.com/containerd/containerd/leases/lease.go, vendor/github.com/containerd/containerd/rootfs/diff.go, vendor/github.com/containerd/containerd/version/version.go, vendor/modules.txt
- Fix nil pointer deference for Windows containers in CRI plugin
- Fix lease labels unexpectedly overwriting expiration
- Fix for simultaneous diff creation using the same parent snapshot
full diff: https://github.com/containerd/containerd/v1.6.10...v1.6.11
=> vendor: github.com/containerd/containerd v1.6.11

.github/workflows/dockerd.yml, client/build_test.go, client/client_nydus_test.go, client/client_test.go, client/mergediff_test.go, frontend/dockerfile/dockerfile_buildinfo_test.go, frontend/dockerfile/dockerfile_heredoc_test.go, frontend/dockerfile/dockerfile_outline_test.go, frontend/dockerfile/dockerfile_provenance_test.go, frontend/dockerfile/dockerfile_targets_test.go, frontend/dockerfile/dockerfile_test.go, go.mod, go.sum, util/testutil/dockerd/daemon.go, util/testutil/integration/dockerd.go, util/testutil/integration/run.go, util/testutil/integration/sandbox.go, vendor/modules.txt
Integration tests for `dockerd` worker with `containerd-snapshotter` was not enabled. This adds a new matrix item to the dockerd workflow to run tests using this snapshotter. Direct push is enabled with containerd snapshotter on most tests. Some of them have still issues (see comments review below).
Tested here: https://github.com/crazy-max/buildkit/actions/runs/3257273194 with Docker version `https://github.com/rumpl/moby.git#c8d`.
Also add missing skips for some tests with dockerd worker:
___
`TestTargetsDescribeDefinition`: https://github.com/crazy-max/buildkit/actions/runs/3235292532/jobs/5299596379#step:9:1016
```
=== CONT  TestIntegration/TestTargetsDescribeDefinition/worker=dockerd/frontend=client
dockerfile_targets_test.go:165: 
Error Trace:	dockerfile_targets_test.go:165 …
```
=> integration: containerd snapshotter with dockerd

exporter/containerimage/attestations.go
:arrow_up: Follow-up https://github.com/moby/buildkit/pull/3258#discussion_r1029881355
Handle whiteouts by explicitly ignoring them - since SBOMs ideally shouldn't contain records of files that aren't actually contained in the final image, this is already an edge case. However, if it does, it's reasonable to return the layer that created the file, instead of the layer that removed it.
=> sbom: discard whiteout files when searching for files in layers

client/build.go, client/solve.go, control/control.go, exporter/containerimage/opts.go, exporter/containerimage/writer.go, exporter/local/export.go, exporter/local/fs.go, exporter/tar/export.go, exporter/util/epoch/parse.go, exporter/util/multiplatform/parse.go, frontend/dockerfile/builder/build.go
:arrow_up: Follow-up to #3197.
This PR corrects the behaviour of the local exporter with the `multi-platform` argument. Essentially, the problem boils down to the fact that we can't distinguish at the exporter level between the results produced by the following:
```
$ buildctl build --opt platform=linux/amd64 --opt attest:sbom
$ buildctl build --opt platform=linux/amd64 --opt attest:sbom --opt build-arg:BUILDKIT_MULTI_PLATFORM=true
```
We'd like the former to produce a flat file structure through the local exporter, and the latter to produce an explicitly nested file structure through the same exporter. However, both of these produce Refs instead of a singular Ref, so we can't just look at the Result to know which one.
To solve this, we can handle this case like `SOURCE_DATE_EPOCH`, and …
=> Fixup attestation platforms for the local exporter

solver/llbsolver/solver.go
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/pull/3230#issuecomment-1346065831.
=> solver: use unmodifed cache exporter Name() as log message

frontend/dockerfile/builder/build.go
In case of oci layout `FROM --platform=` notation does not pass platform
constraint. In case of pointing onto digest of multi-platform index we
try to resolve target platform, which is wrong.
fixes https://github.com/moby/buildkit/issues/3396
Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>
=> Pass platform constraint for oci layout

exporter/containerimage/writer.go, solver/llbsolver/provenance.go
It is unsafe to map direct modifications in the
Annotations make of the Remote descriptor. The same map inside the Descriptor could be used in other
components.
=> containerimage: fix removeinternalannotations

.github/workflows/build.yml, Dockerfile, frontend/dockerfile/cmd/dockerfile-frontend/hack/release, hack/images, hack/util
=> ci: opt-in sbom and provenance

frontend/dockerfile/docs/reference.md
Signed-off-by: David Karlsson <david.karlsson@docker.com>
=> docs: update run --mount verbiage

frontend/attestations/sbom/sbom.go, frontend/dockerfile/dockerfile2llb/convert.go
From the following Dockerfile:
```dockerfile
ARG BUILDKIT_SBOM_SCAN_STAGE=true
FROM alpine:latest AS base
RUN echo test > /test
FROM scratch
COPY --from=base /test /
```
we get:
```
$ docker buildx build --builder=dev . --sbom=true --provenance=true -o ./dir
$ ls ./dir
provenance.json  sbom-base.spdx.json  sbom.spdx.json  foo
```
=> Improved SBOM filenames

frontend/dockerfile/parser/directives.go
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/pull/2937/files/9b73e88f26f5efd148d4e09350fc963f6af61b97#r1047904770 (from @tianon):
> This probably should've just been DetectSyntax, right? 
>
> (The function itself doesn't have the FromDockerfile suffix on the name )
=> chore: fixup dockerfile DetectSyntax doc comment

frontend/dockerfile/dockerfile2llb/convert.go
Previously, we only checked for direct dependencies of the stage, and direct dependencies of any of its parents. However, transitive dependencies would not be detected.
To resolve this, we add a new `findReachable` function, to find all dependencies, including the transitive dependencies. The logic of this new function doesn't need to worry about circular dependencies: those should never be returned from the `toDispatchState` function as they are invalid.
Signed-off-by: Justin Chadwell <me@jedevc.com>
=> dockerfile: collect all dependencies as extra scan targets

go.mod, go.sum, vendor/github.com/spdx/tools-golang/spdx/v2_2/creation_info.go, vendor/github.com/spdx/tools-golang/spdx/v2_2/document.go, vendor/github.com/spdx/tools-golang/spdx/v2_2/package.go, vendor/github.com/spdx/tools-golang/spdx/v2_3/creation_info.go, vendor/github.com/spdx/tools-golang/spdx/v2_3/package.go, vendor/modules.txt
The relevant commits including refactoring to the struct tags, preventing unneccessary output from the resulting sbom as we import and re-export it.
This should help reduce the size of the resulting SBOMs (minimally).
For example, before:
```json
"externalRefs": [
{
"referenceCategory": "SECURITY",
"referenceType": "cpe23Type",
"referenceLocator": "cpe:2.3:a:musl:musl:1.2.3-r4:*:*:*:*:*:*:*",
"comment": ""
},
```
Then, after:
```json
"externalRefs": [
{
"referenceCategory": "SECURITY",
"referenceType": "cpe23Type",
"referenceLocator": "cpe:2.3:a:musl:musl:1.2.3-r4:*:*:*:*:*:*:*"
},
```
See https://github.com/spdx/tools-golang/pull/174 - when this is merged, we can remove the `replace` directive.
=> vendor: replace spdx/tools-golang with jedevc/spdx-tools-golang

control/control.go, frontend/attestations/sbom/sbom.go, frontend/dockerfile/builder/build.go, frontend/dockerfile/dockerfile2llb/convert.go, solver/llbsolver/proc/sbom.go
:hammer_and_wrench: Fixes #3412 (cc @tianon)
If any of the stages that we would have generated sboms for match the no-cache filter, then the no-cache filter should also be applied to the sbom generation.
Note: this fix only applies for dockerfile-generated SBOMs - fallback SBOMs generated by buildkit won't use the `no-cache` frontend attribute.
=> dockerfile: apply no-cache to generated sboms

solver/jobs.go, solver/llbsolver/provenance.go, solver/llbsolver/provenance/buildconfig.go, solver/llbsolver/provenance/predicate.go, util/tracing/detect/recorder.go
- Make sure same invocation ID is used for all platforms part of same build
- Cut session identifiers from the provenance
- Add Digestmapping to the provenance attestation. Instead of digests provenance uses more readable `stepN` names. But this means that build step can't be combined with the same step in the status logs or opentelemetry. To fix that I added a map that contains mapping from original LLB digests for each step.
- Filter out cache imports. This may be improved in the future, but for now we want to make sure there is no leakage of cache backends that require authentication or `type=local` cache that is not reproducible.
=> Fixes for provenance attestations

frontend/dockerfile/dockerfile2llb/convert_runmount.go, solver/pb/caps.go
I'm unsure if this is exposed via public API
=> Fix typo in CapExecMountBindReadWriteNoOutput

frontend/dockerfile/dockerfile_provenance_test.go, solver/llbsolver/proc/provenance.go, solver/llbsolver/provenance/buildconfig.go, solver/llbsolver/provenance/predicate.go
- add possibility to override filename for provenance
- provenance: move hermetic field into a correct struct. I think putting the field under "completeness" field isn't really correct as it doesn't signify the completeness of another field. It is now in the same level as "reproducible" field.
- provenance: fix the order of the build steps. Previous sorting was not correct in complex graphs.
=> Provenance attestation fixes

docs/buildkitd.toml.md, util/resolver/resolver.go, util/resolver/resolver_test.go, util/resolver/utils.go
Allow the use of mirror registry such as Harbor in buildkit with the possibility to have one registry host and multiple proxy_cache projects inside
example:
buildkit side:
```
[registry."docker.io"]
mirrors = ["core.harbor.domain/proxy.docker.io"]
[registry."quay.io"]
mirrors = ["core.harbor.domain/proxy.quay.io"]
```
harbor side:
```
proxy_cache projects named:
- proxy.docker.io (configured for hub.docker.io endpoint)
- proxy.quay.io (configured for quay.io endpoint)
```
Let's take this Dockerfile to be built by buildkit:
```
FROM ubuntu:22.04
RUN echo test
```
With the mirror configuration above, buildkit will pull ubuntu:22.04 from  `core.harbor.domain/proxy.docker.io/library/ubuntu:22.04`
=> feat: handle mirror url with path

session/sshforward/copy.go
The GRPC docs on RecvMsg say:
> RecvMsg blocks until it receives a message into m or the stream is
> done. It returns io.EOF when the client has performed a CloseSend.
> On any non-EOF error, the stream is aborted and the error contains
> the RPC status.
So if EOF is received that just means the client won't be sending anymore data. But it may still be expecting to read data, so we shouldn't close the conn yet.
This was encountered in real life when forwarding a docker socket to a container, where it appears that the docker CLI closes its write side of the connection after requesting the stdout/stderr stream of a container but then expects to read data after that.
Related issue in dagger: https://github.com/dagger/dagger/issues/4073
=> sshforward: skip conn close on stream CloseSend.

executor/containerdexecutor/executor.go
In order to support identity mapping and user namespaces, dockerd needs to defer the creation of a container's network namespace to the runtime and hook into the container lifecycle to configure the network namespace before the user binary is started. The standard way to do so is by configuring a `createRuntime` OCI lifecycle hook, in which the OCI runtime executes a specified process in the runtime environment after the container has been created and before it is started. In the case of dockerd the network namespace needs to be configured from the daemon process, which necessitates that the hook process communicate with the daemon process. This is complicated and slow. All the hook process does is inform the daemon of the container's PID and wait until the daemon has finished applying …
=> [RFC] containerdexecutor: add network namespace callback

frontend/dockerfile/dockerfile_test.go
It looks like there's some changes between `busybox:1.34.0` and up; version 1.34.0 of the image did not have a `/usr/bin` directory (only `/usr/sbin`);
docker run --rm -it busybox:1.34.0 ls -al /usr/
total 12
drwxr-xr-x    3 root     root          4096 Sep 13  2021 .
drwxr-xr-x    1 root     root          4096 Dec 27 14:45 ..
drwxr-xr-x    2 daemon   daemon        4096 Sep 13  2021 sbin
But 1.34.1 and up do;
docker run --rm -it busybox:1.34.1 ls -al usr/
total 16
drwxr-xr-x    4 root     root          4096 Dec 21 18:28 .
drwxr-xr-x    1 root     root          4096 Dec 27 14:44 ..
drwxr-xr-x    2 root     root          4096 Dec 21 18:28 bin
drwxr-xr-x    2 daemon   daemon        4096 Dec 21 18:28 sbin
It's not immediately apparent what caused this change, or if it's in busybox itself, or …
=> frontend: fix testMultiStageImplicitFrom to account for busybox changes

frontend/dockerfile/dockerfile_test.go
backport of 
- https://github.com/moby/buildkit/pull/3436
It looks like there's some changes between `busybox:1.34.0` and up; version 1.34.0 of the image did not have a `/usr/bin` directory (only `/usr/sbin`);
docker run --rm -it busybox:1.34.0 ls -al /usr/
total 12
drwxr-xr-x    3 root     root          4096 Sep 13  2021 .
drwxr-xr-x    1 root     root          4096 Dec 27 14:45 ..
drwxr-xr-x    2 daemon   daemon        4096 Sep 13  2021 sbin
But 1.34.1 and up do;
docker run --rm -it busybox:1.34.1 ls -al usr/
total 16
drwxr-xr-x    4 root     root          4096 Dec 21 18:28 .
drwxr-xr-x    1 root     root          4096 Dec 27 14:44 ..
drwxr-xr-x    2 root     root          4096 Dec 21 18:28 bin
drwxr-xr-x    2 daemon   daemon        4096 Dec 21 18:28 sbin
It's not immediately apparent …
=> [v0.10 backport] frontend: fix testMultiStageImplicitFrom to account for busybox changes

frontend/dockerfile/dockerfile_test.go
- backport of https://github.com/moby/buildkit/pull/3436
It looks like there's some changes between `busybox:1.34.0` and up; version 1.34.0 of the image did not have a `/usr/bin` directory (only `/usr/sbin`);
docker run --rm -it busybox:1.34.0 ls -al /usr/
total 12
drwxr-xr-x    3 root     root          4096 Sep 13  2021 .
drwxr-xr-x    1 root     root          4096 Dec 27 14:45 ..
drwxr-xr-x    2 daemon   daemon        4096 Sep 13  2021 sbin
But 1.34.1 and up do;
docker run --rm -it busybox:1.34.1 ls -al usr/
total 16
drwxr-xr-x    4 root     root          4096 Dec 21 18:28 .
drwxr-xr-x    1 root     root          4096 Dec 27 14:44 ..
drwxr-xr-x    2 root     root          4096 Dec 21 18:28 bin
drwxr-xr-x    2 daemon   daemon        4096 Dec 21 18:28 sbin
It's not immediately apparent …
=> [v0.11 backport] frontend: fix testMultiStageImplicitFrom to account for busybox changes

README.md, client/client_test.go, control/control.go, control/control_test.go, solver/llbsolver/solver.go
fix: https://github.com/moby/buildkit/issues/2578
=> feat: allow ignoring remote cache-export error if failing

util/tracing/detect/detect.go, util/tracing/detect/threadsafe.go
**Background:**
After enabling Open Telemetry export to Jaeger using the `JAEGER_TRACE` env var, started seeing occasional panics across our fleet of `buildkitd` containers. A [helpful pointer](https://github.com/open-telemetry/opentelemetry-go/issues/3063#issuecomment-1205459214) from the people at the OpenTelemetry Go repo indicated a possible concurrency problem. Wrapping the `ExportSpans` with a mutex solved the problem completely.
**Issue:** https://github.com/moby/buildkit/issues/3004
**Testing:** Before this fix, would get several panics a day. After, have gone for several weeks without any panics.
I've also run the suggested tests: `./hack/test integration gateway dockerfile`.
=> Solve panic due to concurrent access to ExportSpans

go.mod, go.sum, vendor/github.com/containerd/containerd/version/version.go, vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn.go, vendor/github.com/docker/docker/errdefs/http_helpers.go, vendor/modules.txt
full diff: https://github.com/containerd/containerd/compare/v1.6.13...v1.6.14
full diff: https://github.com/docker/docker/compare/v23.0.0-beta.1...v23.0.0-rc.1
full diff: https://github.com/docker/cli/compare/v23.0.0-beta.1...v23.0.0-rc.1
=> vendor: docker and docker/cli v23.0.0-rc.1

go.mod, go.sum, vendor/github.com/containerd/containerd/version/version.go, vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn.go, vendor/github.com/docker/docker/errdefs/http_helpers.go, vendor/modules.txt
- backport of https://github.com/moby/buildkit/pull/3435
full diff: https://github.com/containerd/containerd/compare/v1.6.13...v1.6.14
full diff: https://github.com/docker/docker/compare/v23.0.0-beta.1...v23.0.0-rc.1
full diff: https://github.com/docker/cli/compare/v23.0.0-beta.1...v23.0.0-rc.1
=> [0.11 backport] vendor: docker and docker/cli v23.0.0-rc.1

cache/remotecache/s3/s3.go
the word `updated_at` in s3 Metadata will be converted to `x-amz-meta-updated_at` in the http header, but the http headers which contain `_` can't pass some http gateway, such as tencent cloud object storage gateway.
=> [remotecache/s3] fix: "updated_at" in http header can't pass some http gateway, "_" -> "-"

exporter/attestation/unbundle.go, exporter/containerimage/attestations.go, frontend/attestations/sbom/sbom.go, frontend/gateway/forwarder/forward.go, solver/llbsolver/proc/provenance.go, solver/result/attestation.go
The frontend isn't allowed to create provenance attestations - only buildkit is allowed to do this.
We do the check in two stages:
- Verify in the solver that the frontend set a reason for generating the attestation, and then that reason **wasn't** for provenance
- Validate in the exporter (after unbundling) that the attestation predicate was valid for the specified reason. For now, we allow any SLSA provenance attestation for provenance and only allow SPDX for SBOMs.
=> Filter frontend provenance attestations

go.mod, go.sum, vendor/github.com/spdx/tools-golang/spdx/v2_2/package.go, vendor/github.com/spdx/tools-golang/spdx/v2_3/package.go, vendor/modules.txt
Followup to 9c7c061e95e20f5548674ed90bf0269e5e7e1441.
Removes the temporary replacement for jedevc/spdx-tools-golang, since the required commits have been merged upstream [here](https://github.com/spdx/tools-golang/pull/174#event-8148897690).
See https://github.com/jedevc/spdx-tools-golang/compare/json-tags...spdx:tools-golang:main for the full diff - these changes affect parsers that we don't use, so this should not result in any concrete changes.
CC @thaJeztah.
=> vendor: update spdx/tools-golang to d6f58551be3f

docs/attestations/sbom-protocol.md, exporter/containerimage/attestations.go, frontend/attestations/sbom/sbom.go, solver/result/attestation.go
:arrow_up: Follow-up to #3258.
Previously, we would attempt to add file data for every single SBOM - however, if these SBOMs were taken of layers that were not exported, then these could be wrong.
To workaround this, for the file layer details to be added to the resulting SBOM, we require that the scanner add a metadata property to indicate the default value. This is configurable, since in the future we may want behavior that allows the frontend to specify no file layers, or wants an SBOM with layers other than the default.
There are some other possible solutions in the future: the "proper" way to do this would be to attach a second ref to every single attestation, so that we could track exactly what part of the build the attestation was about, so that we could then correctly identify …
=> Only supplement SBOMs with file-layer info for specified SBOMs

executor/oci/resolvconf.go, executor/oci/resolvconf_test.go
- relates to https://github.com/moby/moby/pull/44234
We only need the content here, not the checksum, so simplifying the code by just using os.ReadFile(), using resolvconf.Path() for the location.
Also reversing the logic for custom options; The existing code was always parsing the host's resolv.conf to read the nameservers, searchdomain and options, but those options were only needed if they were not configured in DNSConfig. This patch reverses the logic to only parse the resolv.conf if no options are present in the passed DNSConfig.
There's some more optimisations to make (but changes in libnetwork are needed for that); resolvconf.FilterResolvDNS() still parse the resolv.conf file, even if we just generated it (in which case we're generating a resolv.conf, after which we're parsing the …
=> executor/oci: GetResolvConf(): simplify handling of resolv.conf

client/ociindex/ociindex.go, client/solve.go
To provide a nicer interface for https://github.com/docker/buildx/pull/1456.
=> ociindex utility package refactor

util/pull/pullprogress/progress.go
@sipsma I'm not sure if this is best solution so feel free to open an alternative but discovered that the current state is not quite correct.
When `case <-ctx.Done():` gets called it doesn't return out of the function but sets `onFinalStatus` to return after iteration. But then it calls `manager.Status(ctx` that is guaranteed to error because we already know that the context is closed. Because the error handling is relaxed it doesn't error the function but still logs error message every time.
=> progress: fix clean context cancelling

go.mod, go.sum, vendor/github.com/tonistiigi/fsutil/send.go, vendor/modules.txt
Brings in fix for https://github.com/tonistiigi/fsutil/pull/144
=> vendor: update fsutil to fb43384

frontend/dockerfile/dockerfile_provenance_test.go, frontend/dockerfile/dockerfile_test.go, solver/llbsolver/proc/provenance.go
Requesting provenance on build that returned `nil` resulted in daemon panic.
Theoretically, one could argue that even nil ref could have a provenance with frontend and build-arg names but trying to keep it turned out to be very complicated with a lot of functions needing exceptions as provenance is tracked per ref, not per result. If this becomes an issue somehow (are there any legit nil result builds?) then it can be revisited later. For now provenance is skipped for such builds, even if requested.
=> llbsolver: fix panic when requesting provenance on nil result

exporter/containerimage/export.go, exporter/containerimage/opts.go, exporter/containerimage/writer.go
As discussed with @tonistiigi, we don't need the complexity of https://github.com/moby/buildkit/pull/3403, we just need to rework the behavior of inline attestations slightly.
- For the `local` and `tar` exporters, never export inline attestations
- For the `oci` and `docker` exporters, only export inline attestations if we are already exporting an image index (e.g. in the case of a multi-platform image, or if we have other attestations to export as well)
- For the `image` exporter, always export inline attestations, forcing generation of an index even if we otherwise wouldn't.
No corresponding buildx changes are necessary.
=> exporter: force enabling inline attestations for image export

util/testutil/integration/pins.go, util/testutil/integration/run.go
=> testutil: pin busybox and alpine used in releases

hack/azblob_test/test1/Dockerfile, hack/azblob_test/test2/Dockerfile
Follow-up to https://github.com/moby/buildkit/pull/3469#issuecomment-1374688261
=> azblob_test: pin busybox to avoid "Illegal instruction" error

util/testutil/integration/pins.go, util/testutil/integration/run.go
* backport of #3469
To fix issues with BuildKit integration tests on moby: https://github.com/moby/moby/actions/runs/3858934057/jobs/6578023712#step:9:2694
=> [v0.10 backport] testutil: pin busybox and alpine used in releases

.github/workflows/build.yml, docs/attestations/slsa-definitions.md, exporter/attestation/unbundle.go, hack/azblob_test/test1/Dockerfile, hack/azblob_test/test2/Dockerfile
=> [v0.11] cherry-picks

cmd/buildkitd/main.go
workaround for https://github.com/moby/buildkit/issues/3445
=> [v0.11] make tracing socket forward error non-fatal

.github/workflows/dockerd.yml, util/testutil/dockerd/config.go, util/testutil/integration/dockerd.go
follow-up https://github.com/moby/moby/pull/44772#issuecomment-1376216194
Verified on my fork: https://github.com/crazy-max/buildkit/actions/runs/3877830239/jobs/6613351059#step:8:1744
Also update dockerd workflow following changes on moby: https://github.com/moby/moby/pull/44546
=> integration: set mirrors and entitlements with dockerd worker

.github/workflows/build.yml, .github/workflows/buildx-image.yml, .github/workflows/dockerd.yml, .github/workflows/validate.yml, util/testutil/dockerd/config.go, util/testutil/integration/dockerd.go
* backport of https://github.com/moby/buildkit/pull/3482
Wasn't a clean cherry-pick due lack of https://github.com/moby/buildkit/pull/3176
Also encounter an issue on CI when building on `ubuntu-latest` (22.04): https://github.com/crazy-max/buildkit/actions/runs/3878639330/jobs/6615033505#step:9:26
```
+ docker buildx build --cache-from=type=gha,scope=integration-tests --cache-from=type=gha,scope=binaries --target integration-tests --output type=docker,name=buildkit-tests --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 https://github.com/crazy-max/buildkit.git#refs/heads/0.10_backport_integration-dockerd-mirror --progress=plain
#1 [internal] booting buildkit
#1 starting container buildx_buildkit_builder-70cdfac4-26c1-4d4d-b0d3-0dc9af310a5e0 done
#1 ERROR: Error response from daemon: …
```
=> [v0.10 backport] integration: set mirrors and entitlements with dockerd worker

README.md, cache/remotecache/azblob/utils.go
By default account name is parsed from request uri host (account url) but when product style url is disabled, account name is not part of the host. This new attribute allows to specify the account name in such case.
cc @vangarp
=> azblob cache: account_name attribute

README.md, hack/dockerfiles/generated-files.Dockerfile, hack/validate-generated-files
add node:19-alpine image to install doctoc, and generate the validated README.md,
then use to base image to check the git difference.
it will fail when README toc does not match the generated one.
so that we do not have to check it manually https://github.com/moby/buildkit/pull/3468#discussion_r1063945863
=> ci: add ci to check README toc

client/connhelper/nerdctlcontainer/nerdctlcontainer.go, cmd/buildctl/main.go
1. --addr support nerdctl-container://container?namespace=ns
2. import nerdctlcontainer in the main package to initialize the nerdctl container support
=> feat: add namespace support for nerdctl container

frontend/dockerfile/builder/build.go, frontend/dockerfile/instructions/bflag.go, frontend/dockerfile/instructions/commands_runmount.go, frontend/dockerfile/instructions/commands_runnetwork.go, frontend/dockerfile/instructions/commands_secrets.go, frontend/dockerfile/instructions/commands_ssh.go, frontend/dockerfile/instructions/parse.go, frontend/dockerfile/instructions/parse_test.go, frontend/dockerfile/parser/parser.go, frontend/dockerfile/shell/equal_env_unix.go, frontend/dockerfile/shell/equal_env_windows.go, frontend/dockerfile/shell/lex_test.go
See individual commits for details;
These became obsolete in https://github.com/moby/buildkit/commit/906e34510de0f4e39a7f79173d110cff10c90f3b, which always enabled them.
Before/After:
BenchmarkParseBuildStageName-10     180793      5972   ns/op    8355 B/op     126 allocs/op
BenchmarkParseBuildStageName-10    1980735       605.5 ns/op      48 B/op       3 allocs/op
Also renamed a variable that collided with an import.
Also fix some grammar issues in the GoDoc, and some nits in the tests.
Before/after:
BenchmarkToUpper-10          11979394            96.31 ns/op          10 B/op           2 allocs/op
BenchmarkEqualFold-10        40687216            29.65 ns/op           0 B/op           0 allocs/op
This is makes it easier to discover what values are acceptable;
- Generated docs shows them …
=> frontend/dockerfile: some minor refactor and optimizations

frontend/dockerfile/docs/reference.md
We've received feedback from users who were confused that we were
using `user` as the build arg in this example. The cause of the
confusion was that `user` is too similar to the pre-defined `$USER`
variable. Changing to `username` to hopefully remediate this issue.
=> docs: clarified build argument example by changing the variable name

docs/build-repro.md
=> [v0.11 backport] docs/build-repro.md: add the SOURCE_DATE_EPOCH section

frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_test.go
fixes #3495
On multi-platform builds warning as disabled for secondary platforms to avoid duplicates, but nil value can cause a panic.
Regression from https://github.com/moby/buildkit/commit/ec9a3ac14119da55d18b26fec68137b845aa30a4#diff-c876ea8bd639239ba60cde8cc40c2c2dd761f361564d4465b139b7b628e815bbR481
=> dockerfile: fix panic on warnings with multi-platform

cache/remotecache/registry/registry.go
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/issues/3266.
Users attempt to use `registry.insecure` in the `registry` cache exporter (which makes sense, since many other options are shared, such as `oci-mediatypes`) - as in https://github.com/docker/buildx/issues/1370.
We should support `registry.insecure` in the registry supporter, using similar a similar code pattern to the corresponding exporter code.
=> Add registry.insecure option to registry exporter

util/tracing/detect/otlp.go
This checks if the OTEL_TRACES_EXPORTER is "otlp."
Signed-off-by: Chris Goller <goller@gmail.com>
=> fix(tracing): spelling of OTEL_TRACES_EXPORTER value

session/sshforward/copy.go
PR #3431 caused connections closed on the remote side of a sshforward session to not always result in the local side reading an EOF from the connection. This change restores that behavior by closing the write side of the forwarded connection after reading an EOF from the stream. Since only the write side is being closed, it doesn't prevent the remote side from continuing to read from the connection.
=> Propagate sshforward send side connection close

frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile_test.go, session/sshforward/copy.go, util/tracing/detect/otlp.go
=> [v0.11] cherry picks

examples/kubernetes/create-certs.sh
Add client value for --dry-run flag
```bash
$ ./create-certs.sh 127.0.0.1
W0118 15:45:11.833516   92593 helpers.go:663] --dry-run is deprecated and can be replaced with --dry-run=client.
W0118 15:45:11.869140   92594 helpers.go:663] --dry-run is deprecated and can be replaced with --dry-run=client.
```
Signed-off-by: George <george@betterde.com>
=> examples: optimize --dry-run flag

.github/workflows/build.yml
Similar in style to #3178, cc @tianon 
Official image builds are performed on native infrastructure, including [i386](https://hub.docker.com/u/i386). However, we don't publish a dockerfile for i386, so these builds would be unable to use `# syntax = docker/dockerfile:1` like we would for the other architectures.
=> dockerfile: release frontend for i386 platform

frontend/dockerfile/dockerfile_test.go, util/testutil/integration/pins.go
Tests bit-for-bit reproducibility of OCI tar
=> dockerfile: add testReproSourceDateEpoch

Dockerfile
Looks like containerd binary is not aligned with what we currently vendor: https://github.com/moby/buildkit/blob/b6051af2d9c276098552cc54aa579cece5949c20/go.mod#L18
=> [0.11] Dockerfile: update containerd to v1.6.14

.github/workflows/build.yml
In https://github.com/moby/buildkit/pull/3345, we modified the buildkit repo to point to a specific experimental version of buildkit, so we could test attestation support.
Now that moby/buildkit:latest points to v0.11 which contains attestations, we can revert back to using the old tag.
=> ci: use moby/buildkit:latest in build action

go.mod, go.sum, vendor/github.com/containerd/containerd/remotes/docker/pusher.go, vendor/github.com/pelletier/go-toml/README.md, vendor/github.com/pelletier/go-toml/SECURITY.md, vendor/github.com/pelletier/go-toml/marshal.go, vendor/github.com/pelletier/go-toml/parser.go, vendor/github.com/pelletier/go-toml/toml.go, vendor/modules.txt
Brings in patches for pusher error handling regression. https://github.com/containerd/containerd/pull/7990
=> vendor: update containerd to v1.6.16-0.1709cfe273d9

hack/shell
This broke when the entrypoint for the stage changed.
=> hack: add correct entrypoint to shell script

cache/manager.go, cache/opts.go, cache/remotecache/local/local.go, util/contentutil/multiprovider.go, worker/base/worker.go
Another approach for solving #3229  and https://github.com/docker/buildx/issues/1325
Quote from #3229:
> As reported in docker/buildx#1325, there seems a case where a build result with lazy local cache fails to unlazied on the following (or concurrent) build assigned the different session.
The difference between this and #3229  is that this PR fixes that issue by making the local cache importer non-lazy so this is simpler implementation than #3229 . As soon as the cache record is created, it is unlazied using the session provided from the importer.
=> Make local cache importer non-lazy

cmd/buildctl/debug.go, cmd/buildctl/debug/histories.go, cmd/buildctl/main.go, cmd/buildctl/prunehistories.go
```console
$ buildctl debug histories
TYPE            REF                             CREATED                         COMPLETED                       GENERATION      PINNED
COMPLETE        40d2kg3dqh8dflruacpyd7bdz       2023-01-13T18:35:33+09:00       2023-01-13T18:35:35+09:00       2               *
COMPLETE        ks37bedzwtb7446srrlnb28li       2023-01-13T18:38:06+09:00       2023-01-13T18:38:08+09:00       0
COMPLETE        mmsit25ck1w6qzcja5cdcstfx       2023-01-13T18:38:00+09:00       2023-01-13T18:38:05+09:00       1
$ buildctl prune-histories
TYPE            REF                             CREATED                         COMPLETED                       GENERATION
COMPLETE        ks37bedzwtb7446srrlnb28li       2023-01-13T18:38:06+09:00       2023-01-13T18:38:08+09:00       1 …
```
=> buildctl: add `buildctl debug histories, buildctl prune-histories`

cmd/buildkitd/main_windows.go, util/system/getuserinfo/userinfo_windows.go
This utility allows us to mount the ```buildkitd``` executable inside a Windows container and fetch the SID of any existing user. This is to work around the fact that the SAM hive data structures are undocumented and there is no API to inspect an offline SAM hive to fetch the security info of an existing user.
We will use this utility when determining the SID of the user when we conduct ```FileOps``` and is part of a replacement for: https://github.com/moby/buildkit/pull/3248
Depends on: https://github.com/moby/moby/pull/44847
=> [Windows] Add get-user-info utility

.github/CONTRIBUTING.md, hack/test
when working behind a proxy, the build command has to specify the `--build-arg HTTP_PROXY` etc...
this PR checks the `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY` env and set it to build arg when it exists.
=> test: add proxy build args when existed

util/progress/progressui/init.go
:bug: Fixes https://github.com/moby/buildkit/issues/3537
The NO_COLOR specification says that color should be disabled if NO_COLOR is set *and not empty*.
cc @spkane (author of the original NO_COLOR PR in https://github.com/moby/buildkit/pull/2954)
=> progress: keep color enabled with NO_COLOR empty

exporter/util/epoch/parse.go, frontend/dockerfile/builder/build.go
The timezone information is not exposed to the uint64 representation, but exposed to RFC3339 representation.
This was making the image config non-reproducible depending on the host timezone
=> SOURCE_DATE_EPOCH: drop timezone

client/client_test.go, solver/llbsolver/mounts/mount.go
=> do not mount secrets that are optional and missing from solve opts

frontend/dockerfile/docs/reference.md
If semicolons are used, `docker build` will complete and return 0 even when some commands between semicolons fail
Signed-off-by: Andy Alt <andy5995@users.noreply.github.com>
=> docs: change semicolons to double ampersands

client/build_test.go, client/client_test.go, util/testutil/integration/dockerd.go, util/testutil/integration/sandbox.go
- backports https://github.com/moby/buildkit/pull/3567
- relates to https://github.com/moby/moby/pull/44686#discussion_r1094414342
=> [0.11 backport] integration: fix compat check for CNI DNS test 

frontend/dockerfile/docs/reference.md
The dockerfile:1-labs frontend is now updated to 1.5-labs, which includes this feature
=> docs: update syntax for labs channel in examples

.github/workflows/dockerd.yml, util/testutil/dockerd/config.go, util/testutil/integration/dockerd.go
- backport of https://github.com/moby/buildkit/pull/3482
- relates to https://github.com/moby/moby/pull/44916#issuecomment-1416646298
- follow-up https://github.com/moby/moby/pull/44772#issuecomment-1376216194
- Also update dockerd workflow following changes on moby: https://github.com/moby/moby/pull/44546
=> [0.11 backport] integration: set mirrors and entitlements with dockerd worker 

cache/remotecache/inline/inline.go
In moby (not containerd backed), only uncompressed digests exists. The layer indexing goes wrong because map of indexes only works on compressed digests.
=> inline cache: fix blob indexes by uncompressed digest

cache/remotecache/inline/inline.go
pick #3580
(cherry picked from commit 39ff1c04fef4a66906ccebfafba4ed0ff9b0a85b)
=> [v0.10] inline cache: fix blob indexes by uncompressed digest

.github/workflows/build.yml
Like the BuildKit image job, create a matrix for the frontend one so builds are done in //. Will save some time in the pipeline.
=> ci: create matrix for building frontend image

hack/images
Attestation flags should not be set when loading image to docker otherwise:
```
$ ./hack/images local moby/buildkit
+ BUILDX_NO_DEFAULT_LOAD=true
+ BUILDX_BUILDER=
+ docker buildx build --tag=moby/buildkit:local --output=type=docker,buildinfo-attrs=true --attest=type=sbom --attest=type=provenance,mode=max .
ERROR: docker exporter does not currently support exporting manifest lists
```
=> hack: do not set attest flags when exporting to docker

cache/metadata.go
fix for moby/moby#44943
In older BuildKit versions, snapshotID was not always set if the record was not created with GetByBlob method. Old code defaulted to cache record ID in that case, but that broke with the metadata interface refactor.
Regression for this fallback is in:
before: https://github.com/moby/buildkit/commit/a9f1980ebbe85053232f8c512e9a906e5d568aa9#diff-e4a99c1c50054f36891bbe03da3784b5d2d4ca6b279ff32c7999d3ac5db48dc7L81
after: https://github.com/moby/buildkit/commit/a9f1980ebbe85053232f8c512e9a906e5d568aa9#diff-e4a99c1c50054f36891bbe03da3784b5d2d4ca6b279ff32c7999d3ac5db48dc7R250
It doesn't appear in current versions (at least) because `snapshotID` is explicitly set in `finalize/commit` https://github.com/moby/buildkit/commit/a9f1980ebbe85053232f8c512e9a906e5d568aa9#diff-94cb4 …
=> [v0.10] cache: add fallback for snapshotID

source/gitidentifier_test.go, util/gitutil/git_ref.go, util/gitutil/git_ref_test.go
fixes https://github.com/docker/buildx/issues/1604
Git context detection in the frontend https://github.com/moby/buildkit/blob/ecc5937ca6d3e20b402331e2520df25c9b73e3ed/frontend/dockerfile/builder/build.go#L700-L703
does not match `myrepo.git#:myfolder` but should be supported.
Also adds more test cases to be sure we don't miss anything else.
Looking at our docs in https://docs.docker.com/build/building/context/#git-repositories 
@dvdksn "Commit Used" for `myrepo.git` and `myrepo.git#:myfolder` should be instead `default branch` imo.
I also wonder if we should mutualize the logic from https://github.com/moby/buildkit/blob/ecc5937ca6d3e20b402331e2520df25c9b73e3ed/source/gitidentifier.go#L23-L54 with https://github.com/moby/buildkit/blob/ecc5937ca6d3e20b402331e2520df25c9b73e3ed/util/gitutil/g …
=> git context: fix support for empty git ref with subdir

go.mod, go.sum, vendor/github.com/docker/cli/cli/config/configfile/file.go, vendor/github.com/docker/docker/client/container_wait.go, vendor/modules.txt
client: improve error messaging on crash
full diff: https://github.com/docker/docker/compare/v23.0.0-rc.3...v23.0.0
Fix issue where one bad credential helper causes none to be returned
full diff: https://github.com/docker/cli/compare/v23.0.0-rc.3...v23.0.0
=> vendor: github.com/docker/docker, github.com/docker/cli v23.0.0

cache/metadata.go
same as #3595
In older BuildKit versions snapshotID was not always set if record was not created with GetByBlob method. Old code defaulted to cache record ID in that case but that broke with the metadata interface refactor.
=> cache: add fallback for snapshotID

cache/manager.go
Debugging https://github.com/moby/buildkit/issues/2631 and trying to understand how #3447 might fix this I found this case where we link to another snapshot that has the same chainID(uncompressed digest) but different blobID(compressed digest). In that case, we can mark the blob as `!blobOnly` while the ref is actually lazy. That does not look correct.
This case should be quite hard to hit, but maybe there are some layers with very common files that could make it more likely. @ohmer is testing if this is enough to fix the issue they are seeing.
Looking at @imeoer patch https://github.com/moby/buildkit/pull/3447 again it doesn't look very scary, so if this patch doesn't fully fix this, we could pick that as well, but I'm worried that we don't understand the actual issue, then and it will …
=> cache: don’t link blobonly based on chainid

.github/workflows/build.yml, frontend/dockerfile/cmd/dockerfile-frontend/hack/release, hack/images, hack/release-tar
fixes #3542 
Disables cache on release for some stages so packages are always installed and up to date.
=> hack: do not cache some stages on release

cache/remotecache/azblob/exporter.go, cache/remotecache/gha/gha.go, cache/remotecache/local/local.go, cache/remotecache/registry/registry.go, cache/remotecache/s3/s3.go, exporter/containerimage/opts.go, util/compression/attrs.go
First two commits move attributes parsing for compression in its own package so we can remove dedup ones in remotecache and exporter packages. This could then be used for other remote caches if we want to implement compression (cc @bpaquet).
Also set explicit names for registry and local cache exporters as well.
Last commit sets more appropriate names for gha, s3 and azblob remote caches (cc @bpaquet @vangarp).
=> remotecache: small enhancements

client/client_test.go, exporter/containerimage/attestations.go
BuildKit should generate comments for each file indicating what layer the file can be found in. However, when [buildkit-syft-scanner](https://github.com/docker/buildkit-syft-scanner) switched to using chroot as a temporary hack (see https://github.com/docker/buildkit-syft-scanner/pull/13), all paths in the SBOM were prefixed with `/`. This minor format change meant that the exporter's layer finder would not find this file, as they would be discovered without the `/` prefix.
To fix this, we just need to canonicalize the file paths, both on entry to the function, and for each file discovered.
Additionally, I also noticed a bug in the whiteout detection - we should only be checking the final path component for whiteouts, not the entire path... and also a panic with a scratch layer, and an …
=> Fix bugs in SBOM layer comment generation

.github/workflows/dockerd.yml, hack/test, util/testutil/dockerd/daemon.go, util/testutil/integration/dockerd.go
Setting bip and default address pool might not be necessary when testing locally but is useful when running on GitHub Runners to avoid overlapping with others on this address space: https://github.com/moby/moby/blob/3ba527d82af53cf752aa6ec39daac14626c41b0f/libnetwork/ipamutils/utils.go#L18-L20
Needs follow-up on moby to set the right env in: https://github.com/moby/moby/blob/3ba527d82af53cf752aa6ec39daac14626c41b0f/.github/workflows/buildkit.yml#L105-L110
=> integration: set custom flags for dockerd worker

exporter/containerimage/writer.go, frontend/dockerfile/dockerfile_test.go
[opencontainers/image-spec](https://github.com/opencontainers/image-spec) now contains the MediaType field for all of its structs (since https://github.com/opencontainers/image-spec/commit/5b82148fa647734a2c6095b2eab9b502fbca227e, part of the v1.1.0-rc2 release which we already vendor).
With this update, we can avoid manually wrapping the internal data types to present this field.
=> exporter: remove wrappers for oci data types

source/git/gitsource.go
follow-up https://github.com/docker/buildx/pull/1592#discussion_r1099990894
=> git: override the locale to ensure consistent output

cache/remotecache/gha/gha.go
Saw this error in CI
```
ERROR: failed to solve: failed to compute cache key: failed to copy: invalid status response 416 The range specified is invalid for the current size of the resource. for https://ki6cacprodeus1file5.blob.core.windows.net/2ff2ce0399e5464697755b110c91788d/d7eb6ee20e7bed11ac20501ac56bd055?sv=2019-07-07&sr=b&sig=9HSdAre3Gb4Ze9oOBRtnlFxRSkqAWnf5dueVJ3DPwhY%3D&se=2023-02-11T01%3A34%3A32Z&sp=r&rscl=x-e2eid-19509829-00204bd7-8d7f39b2-ab93df7f, range: bytes=20588289-
```
This has been reported before as well but can't find a tracking issue atm. This is the same issue https://github.com/tonistiigi/go-actions-cache/pull/14 debug was added.
I confirmed that it was coming because of the `offset == size`. There might be some containerd bug that causes this read and that usually …
=> gha: avoid range requests with too big offset

util/testutil/integration/run.go
When running tests with `hack/shell` currently registry mirror directory needs to be created manually each time as it is inside a newly created volume.
=> integration: make sure registry directory exists

Dockerfile
* backport of https://github.com/moby/buildkit/pull/3627
=> [0.11 backport] Dockerfile: update xx to 1.2.1

.github/workflows/build.yml, cache/manager.go, cache/metadata.go, cache/remotecache/gha/gha.go, client/client_test.go, exporter/containerimage/attestations.go, exporter/util/epoch/parse.go, frontend/attestations/sbom/sbom.go, frontend/dockerfile/builder/build.go, frontend/dockerfile/cmd/dockerfile-frontend/hack/release, frontend/dockerfile/docs/reference.md, hack/images, hack/release-tar, solver/llbsolver/mounts/mount.go, util/progress/progressui/init.go
- #3556
- #3558
- #3559
- #3561
- #3566
- #3577
- #3583
- #3594
- #3605
- #3618
=> [v0.11] cherry-picks for v0.11.3

cache/remotecache/v1/cachestorage.go, client/client_test.go, control/control.go, solver/cache_test.go, solver/cachemanager.go, solver/cachestorage.go, solver/combinedcache.go, solver/edge.go, solver/jobs.go, solver/llbsolver/bridge.go, solver/memorycachestorage.go, solver/types.go, worker/cacheresult.go
Fixes https://github.com/docker/buildx/issues/1306
Currently, cache cannot reuse lazy layers that returns `cache.NeedsRemoteProviderError` on `cacheresult.cacheResultStorage.Exist()`.
This causes the issue that cache doesn't reuse lazy layers as reported in https://github.com/docker/buildx/issues/1306 .
This commit tries to fix this issue by allowing `cache.NeedsRemoteProviderError` during cache lookup.
=> Fix cache cannot reuse lazy layers

.github/workflows/.test.yml, .github/workflows/build.yml, .github/workflows/buildkit.yml, .github/workflows/buildx-image.yml, .github/workflows/dockerd.yml, .github/workflows/frontend.yml, .github/workflows/test-os.yml, .github/workflows/validate.yml, README.md
Split dockerfile frontend integration tests and build in a dedicated workflow so we have a clear separation of concerns and also avoid building the frontend when a BuildKit tag is pushed and vice versa with a dockerfile tag.
Also create a reusable workflow for our tests and move test-os job to a dedicated workflow.
=> ci: move frontend integration tests and build to a dedicated workflow

frontend/dockerui/build.go
As pointed out by @cpuguy83 , when cross-compiling windows images, the manifest descriptors do not contain `OSVersion` that is used on windows. There is currently no way to pass `OSVersion` as containerd has not defined the `os/arch/variant` serialization for that field, but if base image used by the build has `OSVersion` defined we can just use that one. In image config `OSVersion` was already set before by the base image.
=> set osversion in index descriptor from base image

.github/workflows/test-os.yml
regression from https://github.com/moby/buildkit/pull/3237
=> ci: fix missing TESTFLAGS env var in test-os workflow

.github/workflows/buildkit.yml, .github/workflows/dockerd.yml, .github/workflows/frontend.yml, Dockerfile, hack/build_ci_first_pass, hack/cross
follow-up https://github.com/moby/buildkit/pull/3237 and carry some changes from https://github.com/moby/buildkit/pull/3204
`cross` job is pretty slow atm as it needs to build every platforms in the same runner. It was also used only for cache without any other purpose. This PR splits the cross job per platform to build binaries and merge them together in the `binaries` job for release. This should reduce build time to create binaries by about 20min.
=> ci: split cross job

control/control.go
Context: in Dagger we're experimenting w/ a custom cache exporter/importer implementation that would be configured entirely server-side (as opposed to remote cache configuration today which is specified by clients).
To start with, the idea is to just have clients always specify this custom cache exporter in their solve requests and then the implementation server-side can decide whether+how to actually do the caching.
We thankfully can do this w/out forking buildkit by just creating our own main func to replace buildkitd's and plug in our custom implementation [here](https://github.com/sipsma/buildkit/blob/6ca5ee16821881fd6267ee95a0c4f5b88c664f1d/cmd/buildkitd/main.go#L668-L668).
The only problem is that we sometimes want to skip cache export …
=> Skip configuring cache exporter if it is nil.

util/resolver/resolver.go
This guards against the case where an existing http connection is reused; however the server fails to respond to the second request.
=> specify a `ResponseHeaderTimeout` value

.github/workflows/.test.yml, .github/workflows/buildkit.yml, .github/workflows/frontend.yml, .github/workflows/test-os.yml, .golangci.yml, Dockerfile, cmd/buildkitd/debug.go, examples/buildkit0/buildkit.go, examples/buildkit1/buildkit.go, examples/buildkit2/buildkit.go, examples/buildkit3/buildkit.go, examples/buildkit4/buildkit.go, examples/nested-llb/main.go, frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile, frontend/gateway/container.go, go.mod, hack/dockerfiles/generated-files.Dockerfile, hack/dockerfiles/lint.Dockerfile, hack/dockerfiles/vendor.Dockerfile, solver/scheduler_test.go, source/http/httpsource.go, util/archutil/Dockerfile, util/compression/compression.go, util/testutil/integration/run.go
Update to Go 1.20 and golangci-lint to 1.51.1 as well.
Also needs to fix lint and gosec issues following this update:
```
#11 22.12 cmd/buildkitd/debug.go:40:5: G114: Use of net/http serve function that has no support for setting timeouts (gosec)
#11 22.12       go http.Serve(l, m)
#11 22.12          ^
#11 22.12 util/compression/compression.go:84:13: var-declaration: should omit type gzipType from declaration of var Default; it will be inferred from the right-hand side (revive)
#11 22.12 var Default gzipType = Gzip
#11 22.12             ^
#11 22.12 source/http/httpsource.go:391:24: response body must be closed (bodyclose)
#11 22.12       resp, err := client.Do(req)
#11 22.12                             ^
#11 22.12 util/testutil/integration/run.go:167:3: SA1019: rand.Seed has been …
```
=> update to Go 1.20

client/llb/definition.go, client/llb/definition_test.go, frontend/dockerfile/dockerfile_test.go
See integ test case for repro, it causes a server-side panic.
Probably a bunch of possible fixes on different levels but opted for the "lowest-level" one by handling this case in `NewDefinitionOp` for now; reduces what was a panic to an `err` return there. Let me know if it's preferable to handle this elsewhere and make `NewDefinitionOp` return `nil, nil` in this case or something like that @tonistiigi
=> Fix buildkitd panic when frontend input is nil.

docs/stargz-estargz.md
Major issues/limitations of stargz-snapshotter have been resolved and it's almost feature complete. I think it now should be out of experimental.
=> stargz-snapshotter: graduate from experimental

.github/workflows/build.yml, .github/workflows/validate.yml
* backport of https://github.com/moby/buildkit/pull/3657
Not a clean cherry-pick because we need additional commits that refactored the pipeline.
=> [0.10 backport] ci: trigger workflows on push to release branches

.github/workflows/build.yml, .github/workflows/validate.yml
* backport of https://github.com/moby/buildkit/pull/3657
Not a clean cherry-pick because we need additional commits that refactored the pipeline.
=> [0.11 backport] ci: trigger workflows on push to release branches

executor/oci/user.go, frontend/dockerfile/dockerfile_test.go
Apply `ensureAdditionalGids()` from https://github.com/containerd/containerd/commit/3eda46af12b1deedab3d0802adb2e81cb3521950
(CVE-2023-25173, https://github.com/advisories/GHSA-hmfx-3pcx-653p)
=> Ensures that the primary GID is also included in the additional GIDs

executor/oci/user.go, frontend/dockerfile/dockerfile_test.go
Cherry-pick:
- https://github.com/moby/buildkit/pull/3651
=> [0.11 backport] Ensures that the primary GID is also included in the additional GIDs

cache/remote.go
```
newDesc.Annotations = nil
for _, k := range addAnnotations {
newDesc.Annotations[k] = desc.Annotations[k]
}
```
The codes may cause buildkitd panic: assignment to entry in nil map
=> fix a possible panic on cache

client/client_test.go
This fixes hang in TestSBOMSupplements which caused a timeout.
Observed here: https://github.com/moby/moby/pull/44079
This test is skipped for `dockerd` worker so it wasn't visible without containerd.
```
=== CONT  TestIntegration/TestSBOMSupplements/worker=dockerd
client_test.go:8401: dockerd worker can not currently run this test due to missing features (direct push, sbom)
```
=> test: Close buildkit client in TestSBOMSupplements

client/client_test.go
- Cherry-pick: https://github.com/moby/buildkit/pull/3675
This fixes hang in these tests which caused a timeout.
Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>
(cherry picked from commit 3b0aa6949de9857e4209844ee0bc3fd31cebe490)
=> [v0.11 backport] test/client: Close buildkit client

client/llb/definition.go
Currently source information stored in DefinitionOp isn't propagated to the vertices available from `DefinitionOp.Inputs()`. This commit changes this and makes the source information available in the input vertices as well. This would be useful for inspecting/debugging each vertex in the LLB with keeping track the source location.
=> llb: Allow DefinitionOp to track sources

cmd/buildkitd/main.go, cmd/buildkitd/main_unix.go, cmd/buildkitd/main_windows.go, executor/oci/spec.go, executor/oci/spec_unix.go, executor/oci/spec_windows.go
* The tracing socket is a named pipe on Windows
* Sets proper permissions on the named pipe
* Sets proper environment variables inside the executor
* Defines proper mount for the tracing socket
=> [Windows] Fix tracing listener

frontend/dockerfile/shell/lex.go, frontend/dockerfile/shell/lex_test.go
:hammer_and_wrench: Partial implementation of https://github.com/moby/buildkit/issues/2389#issuecomment-963499426
POSIX allows the colon in variable expansion to be optional, see https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05
This PR updates buildkit's variable expansion to include this, so all the following are now supported:
- `${FOO-bar}`, `${FOO:-bar}`
- `${FOO+bar}`, `${FOO:+bar}`
- `${FOO?bar}`, `${FOO:?bar}`
Additionally, I've updated the tests to use matrix-style tests, essentially filling out the table from "[2.6.2 Parameter Expansion](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05)", to track for regressions.
As a next-step, I'm looking at implementing support for the rest of …
=> Allow POSIX variable substitution to remove optional colon 

cache/refs.go, docs/rootless.md, examples/kubernetes/sysctl-userns.privileged.yaml, executor/oci/spec.go, snapshot/localmounter_unix.go, util/rootless/mountopts/mountopts_linux.go, util/rootless/mountopts/mountopts_others.go, util/strutil/strutil.go
Fix #3098
Tested on Bottlerocket OS 1.12.0 (aws-k8s-1.25), kernel 5.15.79 (`eksctl --version=1.25 -node-ami-family=Bottlerocket` using eksctl 0.132.0)
=> rootless: support Bottlerocket OS

client/llb/definition.go
- cherry-picked from https://github.com/moby/buildkit/pull/3678
=> [0.11 backport] Allow DefinitionOp to track sources

client/connhelper/kubepod/kubepod.go, client/connhelper/kubepod/kubepod_test.go
When specifying multiple contexts in kubeconfig, we sometimes set the context name to something like "user@cluster" for convenience.
However, current kubepod connhelper considers this kind of context name to be invalid.
```bash
$ buildctl --addr "kube-pod://bk?context=user@cluster" build --frontend=dockerfile.v0 --local context=. --local dockerfile=.
error: unsupported context name: "user@cluster"
```
kubepod connhelper should not validate context name for the following reasons:
- While [this K8s documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names) mentions name constraints for K8s resources, context is not applicable because it is not a resource.
- `kubectl` also does not validate its name except empty check.
- …
=> remove context name validation from kubepod connhelper

version/version.go
:arrow_up: Follow-up to https://github.com/docker/buildx/pull/1637#discussion_r1108625166.
:link: Similar to https://github.com/docker/buildx/pull/1670.
Ensures that the BuildKit version always begins with a `v` (as in the version tagging convention we use). This will only apply in cases when users build buildkit from scratch *without* using the provided build scripts (and just using `go build` directly).
=> version: add "v" prefix to version for tagging convention consistency

.github/workflows/docs-upstream.yml, frontend/dockerfile/docs/reference.md
closes https://github.com/docker/docs/issues/16875
fix liquid syntax issue and also adds a conformance validation workflow for the upstream docs.
=> dockerfile(docs): fix liquid syntax

frontend/dockerfile/dockerfile_test.go, util/testutil/integration/pins.go
Fix the test so it works on non-amd64. Currently, the test cases failure even though there is a skip as the mirroring code already failed because it tries to mirror amd64 image from `arm64v8` namespace.
=> dockerfile: fix reproducible digest test for non-amd64

client/client_test.go, client/mergediff_test.go, frontend/dockerfile/dockerfile_test.go, hack/test, util/testutil/integration/dockerd.go, util/testutil/integration/sandbox.go
follow-up https://github.com/moby/moby/pull/44079#issuecomment-1456934350
Adds ability to enforce features compatibility check through env vars in integration tests.
For example to disable `integration.FeatureCacheExport` and `integration.FeatureCacheImport` feature you can set `BUILDKIT_TEST_DISABLE_FEATURES=cache_export,cache_import`. Set `BUILDKIT_TEST_ENABLE_FEATURES=cache_export,cache_import` to enable.
Also adds extra features compat for specific cache backends and mergediff.
=> integration: enforce features compat through env vars

client/build_test.go, client/client_test.go
follow-up https://github.com/moby/buildkit/pull/3713#issuecomment-1468285613
=> integration: missing feature compat checks

client/build_test.go, client/client_test.go, client/mergediff_test.go, frontend/dockerfile/dockerfile_test.go, hack/test, util/testutil/integration/dockerd.go, util/testutil/integration/sandbox.go
backport of:
* https://github.com/moby/buildkit/pull/3711
* https://github.com/moby/buildkit/pull/3715
Not a clean cherry-pick. `testBasicS3CacheImportExport`, `testBasicAzblobCacheImportExport` and `testBasicGhaCacheImportExport` are missing on `v0.11` branch.
=> [0.11 backport] integration: enforce features compat through env vars

control/control.go
`translateLegacySolveRequest` will not return any error, therefore, there is no need to check for errors returned.
Signed-off-by: chengjoey [zchengjoey@gmail.com](mailto:zchengjoey@gmail.com)
=> chore: `translateLegacySolveRequest` does not need to return error checking

executor/oci/user.go, frontend/dockerfile/dockerfile_test.go
Cherry-pick
- https://github.com/moby/buildkit/pull/3651
- https://github.com/moby/buildkit/pull/3668
=> [0.10 backport] Ensures that the primary GID is also included in the additional GIDs

frontend/dockerfile/docs/reference.md
- closes https://github.com/docker/cli/pull/3560
- closes https://github.com/moby/buildkit/issues/3721
Applying the patch from @darkvertex from https://github.com/docker/cli/pull/3560
=> Update builder.md to document newly supported --chmod features in both ADD and COPY statements.

executor/runcexecutor/executor.go, executor/runcexecutor/executor_common.go, executor/runcexecutor/executor_linux.go
This patch makes the process handling consistent between runc.Run and runc.Exec usage.  Previously runc.Run would use context.Background for the runc.Run process and would monitor the request context for shutdown requests, sending a SIGKILL to the container pid1 process. This allowed runc.Run to gracefully shutdown and reap child processes.  This logic was not used for runc.Exec where instead we were passing in the request context to runc.Exec, and if that request context was cancelled the runc process would immediately terminate preventing runc from reaping the child process.  In this scenario the extra pid will remain forever and then when the pid1 process will get wedged in zap_pid_ns_processes syscall upon shutdown waiting fo the zombie pid to exit.
With this fix both runc.Run and …
=> fix process termination handling for runc exec

.github/workflows/.test.yml, .github/workflows/test-os.yml, .gitignore, Dockerfile, hack/test
follow-up https://github.com/moby/buildkit/pull/2900 and https://github.com/moby/buildkit/pull/3411
Atm it's not easy to go through the logs and quickly find what tests are currently failing.
With this change we'll have [GitHub annotations](https://developer.github.com/changes/2019-09-06-more-check-annotations-shown-in-files-changed-tab/) for failed tests directly reported in "Files changed" for a pull request.
Tested here: https://github.com/crazy-max/buildkit/pull/12/files
___
___
=> ci: output annotations for failures

cache/refs.go, docs/rootless.md, examples/kubernetes/sysctl-userns.privileged.yaml, executor/oci/spec.go, snapshot/localmounter_unix.go, util/rootless/mountopts/mountopts_linux.go, util/rootless/mountopts/mountopts_others.go, util/strutil/strutil.go
Cherry-pick (clean):
- https://github.com/moby/buildkit/pull/3697
=> [0.11 backport] rootless: support Bottlerocket OS

client/ociindex/ociindex.go
:hammer_and_wrench: Fixes https://github.com/docker/buildx/issues/1672
This code is used by both the local cache exporter backend and the oci exporter when tar=false is set. Previously, these components would not create the oci-layout file which is required by opencontainers/image-spec.
With this change, clients will now create this file next to index.json.
cc @benibr
=> client: create oci-layout file in StoreIndex

solver/llbsolver/solver.go
Recording build history calls into `LeaseManager`, which can block for several seconds. This can trigger a 3 second timeout in `GatewayForwarder` while it waits for a build ID to be registered.  Longer-term, we should figure out the performance issues in the containerd metadata DB, but this addresses the immediate problems of timeouts that manifest in these error messages:
forwarding Ping: no such job 93oss3bmbagcpq8yokla3921z
=> Register builds before recording build history

client/build_test.go, frontend/gateway/grpcclient/client.go
This fixes an issue where the tty message handling loop will go into a tight loop and never exit upon context.Canceled.  There is select statement in `(*procMessageForwarder).Recv` that [returns nil on ctx.Done](https://github.com/moby/buildkit/blob/5e08ad3a8a91e7b73ac0f0047edbadd866afa59c/frontend/gateway/grpcclient/client.go#L590-L591), but [the control loop in `(*container).Start` did not exit](https://github.com/moby/buildkit/blob/5e08ad3a8a91e7b73ac0f0047edbadd866afa59c/frontend/gateway/grpcclient/client.go#L921-L934) on this condition.  I think the intent was to flush out any inflight messages on cancel, but this is already done in `(*procMessageForwarder) Close`.
=> fix gateway exec tty cleanup on context.Canceled

client/client_test.go, solver/llbsolver/vertex.go
Before this, in the case where nothing was mutated the visited memo would never be updated, thus causing exponential complexity.
Now the memo is updated even when nothing is mutated, just setting old and new to be the same digest.
---
This was causing real world performance regressions for dagger (due to the fact that dagger tries to by default propagate mount changes across every Exec, you can end up with fairly complicated LLB graphs pretty easily): https://github.com/dagger/dagger/issues/4620
=> llbsolver: Fix performance of recomputeDigests

solver/llbsolver/history.go
The sorting in history GC was wrong. We want a reverse sort so we can skip the N newest records, not the N oldest.
=> llbsolver: fix sorting of history records

client/build_test.go, client/client_test.go, executor/runcexecutor/executor.go, executor/runcexecutor/executor_common.go, executor/runcexecutor/executor_linux.go, frontend/gateway/grpcclient/client.go, solver/llbsolver/history.go, solver/llbsolver/solver.go, solver/llbsolver/vertex.go
- #3722
#3658
#3726
#3732
#3733 (not merged)
@coryb @aaronlehmann @sipsma
=> [0.11] cherry picks for v0.11.5

Makefile, README.md, docker-bake.hcl, docs/generate.go, docs/reference/buildctl.md, hack/dockerfiles/docs.Dockerfile
This patch ensures that we keep `buildctl.md` up-to-date over time, by creating a script to auto-generate, inspired by the technique used by buildx (which we can't use directly, since we don't use the docker cli).
=> docs: add auto-generated sections to buildctl.md

client/client.go, client/client_test.go
This allows consumers of buildkit's client API to manually specify grpc options, such as underlying transport details, or creating interceptors for requests.
Some example use cases:
- Manual configuration of the grpc connection details, e.g. keepalive times, user agents, etc.
- Configuration of grpc headers using interceptors, which could be useful for grpc-level proxies (e.g. as in https://github.com/moby/buildkit/issues/3154) - this is the kind of case I'm specifically interested in.
Maybe this isn't the right approach? If we're interested in manually setting headers, maybe we would want a dedicated `ClientOpt` type?
=> client: allow grpc dial option passthrough

cmd/buildkitd/main.go, control/control.go
This makes it possible for callers to customize the full CacheManager used by buildkit without having to rewrite/fork the whole control package.
---
@tonistiigi trivial change, this just makes it easier for Dagger to wrap a CacheManager in order to play around with adding more debugging and related features to it
=> Provide CacheManager to Controller instead of CacheKeyManager.

client/build_test.go, executor/runcexecutor/executor.go, executor/runcexecutor/executor_common.go, executor/runcexecutor/executor_linux.go
This reverts commit 2f79b149127d8fb34e530f9534b0a73ff58ef62b.
Regression caused #3751
Summary:
This commit ended up masking rather than solving the original problem, which was unreaped zombie processes caused by cancelling the context for `runc exec` processes initiated via the gateway `(*Client).NewContainer` apis.  More discussion for a proper fix in #3754
=> v0.11: Revert "fix process termination handling for runc exec"

solver/llbsolver/ops/file.go
FileOpSolver keeps internal state about the vertex that has been loaded into it and should not be reused.
possibly fixes #3748
I don't have any theory of why this issue should be more likely in the latest release.
@sipsma @jedevc
=> fileop: create new fileOpSolver instance per Exec call

client/client.go, client/client_test.go
This provides some compile-time safety around options passed when creating a buildkit client.
Before this change since a ClientOpt is an empty interface anything and everything could be passed in.
This is a breaking change since before consumers could pass in a raw grpc.DialOption, this now needs to be wrapped with `client.WithGRPCDialOption(grpcOpt)`
Consumers could also pass in something tat was not a client opt at all and it was completely ignored.
=> Make ClientOpts type safe

client/client.go, cmd/buildctl/common/common.go
Additionally, this splits out WithCredentials into separate methods:
- WithCredentials configures the client credentials presented to the server
- WithServerConfig configures the name and ca certificate to check the server's certificate against
- WithServerConfigSystem configures the name to check the server's certificate against - the ca certificate is automatically pulled from the system store.
This essentially splits out the different possible TLS combinations into:
- No TLS - none of the above client options
- TLS verifying the server against a known CA cert - use WithServerConfig
- TLS verifying the server against a system cert - use WithServerConfigSystem
- mTLS verifying the server against a known CA cert - use WithServerConfig + WithCredentials
- mTLS verifying the server against …
=> Add client opts to enable system certificates

cache/remotecache/s3/s3.go
When trying to use S3 cache with anonymous credentials (for example, for importing publicly available layers), the cache is not used.
Solution: enable anonymous credentials
According to the API documentation:
"If using the `NewFromConfig` constructor you'll need to explicitly set
the `Credentials` member to nil, if the external config resolved a
credential provider."
This change allows setting these empty credentials so that the client can be used anonymously.
--- 
This would solve my issues described in https://github.com/docker/buildx/issues/1666 and would generally allow users to share cache publicly (for example, in fork PRs)
=> Problem: can't use anonymous S3 credentials

executor/runcexecutor/executor.go, executor/runcexecutor/executor_common.go, executor/runcexecutor/executor_linux.go, worker/containerd/containerd_test.go, worker/runc/runc_test.go, worker/tests/common.go
This fixes the incorrect kill handling introduced in b76f8c02482e11b3b480e0c6ddf54cc91a667730.  We need to send the
SIGKILL to the in-container process, not the `runc` process.  This patch adds an abstraction over the kill handling:
- for `runc run` processes use `runc kill`
- for `runc exec` processes, read pid (in host PID namespace) from pidfile created by `runc exec`, then send the signal directly to that process.
Also use the kill abstraction when we receive a SIGKILL over the signal channel for containers created by gateway NewContainer
~~The pid returned on the started channel from runc.(Run|Exec) seems to be the pid of the runc monitor process, not the pid of the process run in the container.  I have confirmed the pid written to the pidfile is the host pid of the process in the …
=> runc worker: fix sigkill handling

solver/llbsolver/ops/file.go
cherry-pick #3753
FileOpSolver keeps internal state about the vertex that has been loaded into it and should not be reused.
(cherry picked from commit e7caa2e8422b1faaefe6c4504a38d428e7cc881b)
=> [v0.11] fileop: create new fileOpSolver instance per Exec call

cache/manager.go, cache/opts.go, cache/remotecache/local/local.go, util/contentutil/multiprovider.go, worker/base/worker.go
https://github.com/moby/buildkit/pull/3493
https://github.com/moby/buildkit/issues/3770
=> [v0.10] cherry-pick: Make local cache importer non-lazy

client/client_test.go, source/http/httpsource.go, util/testutil/httpserver/server.go
The go http library will normally implicitly set an Accept-Encoding of gzip to requests and then transparently decompress the response body. However, if the Accept-Encoding header is explicitly set by the caller it will no longer transparently decompress the body. This was causing HTTP LLB sources to have unexpectedly compressed contents.
The fix here just unsets the Accept-Encoding header after the HEAD request. Another possible fix would be to do our own gzip decompression after reading the body if it was gzipped, but this approach seemed slightly simpler.
cc @tonistiigi this fixes some ephemeral test failures we are getting in Dagger
=> Fix gzip decoding of HTTP sources.

go.mod, go.sum, vendor/modules.txt
A bogus dependency on github.com/kr/pretty was somehow added to go.mod by dependabot in PR #3759 (6fb8f99e06ac6004a5d4f123e5de61de1da6a2f0)
=> go.mod: remove github.com/kr/pretty

Dockerfile
Cherry-pick:
- https://github.com/moby/buildkit/pull/3762
=> [v0.11 backport] Dockerfile: RUNC_VERSION=v1.1.5

solver/llbsolver/proc/sbom.go
:arrow_up: Follow-up to https://github.com/moby/buildkit/pull/3462.
This fixes the panic that we can trigger in https://github.com/docker/buildx/pull/1640#issuecomment-1513000048.
This scenario would happen if we returned a result containing no refs, but the solve opt specified we should have some platforms, we'd still attempt to access them, and panic.
This is probably a candidate for cherry-picking. 
cc @ktock
=> Add checks to avoid provenance and sbom post processing if not results were created

cache/remotecache/s3/s3.go
Reverts moby/buildkit#3692
See #3785
We need a better solution for anonymous creds
=> Revert "Problem: can't use anonymous S3 credentials"

client/client_test.go, solver/cachemanager.go
Before this any refs that were loaded but not put into results would be leaked.
---
~~cc @tonistiigi noticed in certain load tests I was running w/ Dagger that cache refs were leaking, this fixes it. I am still trying to understand the exact circumstances it arises in.~~
~~I know for sure it only happens when using a cacheManager constructed from a remote cache import. And I also *think* it might happen when there are multiple results that end up with the same layers (i.e. two image refs resolve to the same set of layers). However, the context in which this was triggered involved cache manifest json constructed by custom code, not by the normal buildkit code, so I don't know if it's possible to trigger this using a cache manifest generated by buildkit upstream.~~
Either way, I think this …
=> solver: Release unused refs in LoadWithParents

client/client_test.go, util/winlayers/differ.go
Looks like we had some duplicated imports.
While there *is* a revive rule for this, it's disabled by default... and enabling it requires manually listing out every single rule we want to enable 1-by-1. So I think it's maybe not worth enabling it, at least until we can resolve #3796.
=> chore: tidy up duplicated imports

client/llb/definition.go, client/llb/definition_test.go
`DefinitionOp.inputCache` can be shared and written among calls of `DefinitionOp.Inputs()`.
When walking vertices of DefinitionOp in parallel using `DefinitionOp.Inputs()`, it causes panic as of now.
This commit fixes this issue by using `sync.Map` for `DefinitionOp.inputCache` allowing it written in parallel.
=> Avoid panic on parallel walking on DefinitionOp

.golangci.yml, hack/dockerfiles/lint.Dockerfile
This PR bumps up golangci-lint to v1.52.2 https://github.com/golangci/golangci-lint/releases/tag/v1.52.2
With this version, the linter fails with a lot of `unused-parameter` failures. Though this PR fixes the code to pass the linter, maybe we can disable it if unnecessary.
=> bump up golangci-lint to v1.52.2

exporter/containerimage/writer.go, frontend/dockerfile/dockerfile2llb/image.go
The OCI image spec is considering to change the Image struct and embedding the
Platform type (see [opencontainers/image-spec#959](https://github.com/opencontainers/image-spec/pull/949)) in the go implementation.
BuildKit currently uses some struct-literals to propagate the platform fields,
which will break once those changes in the OCI spec are merged.
Ideally (once that change arrives) we would update the code to set the Platform
information as a whole, instead of assigning related fields individually, but
in some cases in the code, image platform information is only partially set
(for example, OSVersion and OSFeatures are not preserved in all cases). This
may be on purpose, so needs to be reviewed.
This patch keeps the current behavior (assigning only specific fields), but
removes the …
=> Update uses of Image platform fields in OCI image-spec

docs/build-repro.md
https://github.com/moby/buildkit/commit/6d061b9a3a92501961687085d296e88dae28c9f8 updated the policy format, but the corresponding build repro docs still use the old format.
This patch fixes the example to use the newer policy format.
=> docs: fixup build repro doc with updated policy format

util/testutil/integration/containerd.go, util/testutil/integration/dockerd.go, util/testutil/integration/run.go, util/testutil/integration/sandbox.go, util/testutil/integration/util.go
If a process is started but exits early because of an error, don't hang and instead detect process exit.
This happens when the process doesn't exist (for example, when `registry` binary is missing).
This helps to know what's wrong instead of having to use the debugger.
=> test: don't hang if a process doesn't run

Dockerfile, frontend/dockerfile/dockerfile_ssh_test.go, session/sshforward/copy.go
Fixes https://github.com/moby/buildkit/issues/3840
=> ssh: add fallback to ensure conn is closed in all cases.

cache/manager.go
Noticed a few cache refs leaked occasionally during long running tests. Debugged by changing `immutableRef` and `mutableRef` to store the stack trace of the caller when they are created, saw that it leaked on the lines fixed here.
I considered whether we should leave the stack traces in those data structures but I saw it was taking up a ton of memory, so probably best for local debugging only for now cc @tonistiigi
=> cache: always release ref when getting size in usage.

cmd/buildkitd/config/config.go, cmd/buildkitd/config/gcpolicy.go, cmd/buildkitd/config/gcpolicy_unix.go, cmd/buildkitd/config/gcpolicy_windows.go, cmd/buildkitd/config/load_test.go, cmd/buildkitd/main.go, cmd/buildkitd/main_containerd_worker.go, cmd/buildkitd/main_oci_worker.go, docs/buildkitd.toml.md, solver/llbsolver/history.go
In addition to parsing the raw number of bytes, we can additionally supporting reading short notations from strings, such as "50MB", or "10GB". We can also support different percentages, such as "20%", which allows for consuming a maximum percentage of the disk easily (previously, only the default was set to 10%, with no ability to change to use an arbitrary percentage).
=> buildkitd: allow multiple units for gc config

util/progress/progressui/display.go, util/progress/progressui/printer.go
Prefix numbers should only be assigned before printing, not when receiving data.
fixes #3834
=> progressui: fix possible zero prefix numbers in logs

solver/llbsolver/solver.go
`func notifyStarted(ctx context.Context, v *client.Vertex, cached bool) func(err error, cached bool)` of `solver/llbsolver/solver.go` is not referenced elsewhere and the value of `cached` is always `false`.
So I thought it would be better to write the value of `cached` directly in the function and modify it this way.
=> solver: drop unneeded variable

cache/manager_test.go, cache/refs.go, snapshot/diffapply_unix.go, snapshot/snapshotter.go, snapshot/snapshotter_test.go, util/overlay/overlay.go, util/overlay/overlay_linux.go
Factorize code that check for an overlay mount type by using a function instead.
This will allow supporting other overlay-based mount types more easily in the future (for example fuse-overlayfs).
=> overlay: use function to check for overlay-based mounts

solver/llbsolver/history.go
Make sure if a request is marked deleted (but not deleted yet because it has active reference), it doesn't show up in Listen responses anymore.
While debugging this, I also noticed 2 other small issues. Added in separate commits.
cc @aaronlehmann
=> fixes for history events

control/control.go
When error appears on sending to network, channel
still needs to be read empty to ensure that the other side does not get blocked on sending to the channel.
=> control: fix possible deadlock on network error

cmd/buildkitd/main.go, cmd/buildkitd/service_unix.go, cmd/buildkitd/service_windows.go, vendor/golang.org/x/sys/windows/svc/mgr/config.go, vendor/golang.org/x/sys/windows/svc/mgr/mgr.go, vendor/golang.org/x/sys/windows/svc/mgr/recovery.go, vendor/golang.org/x/sys/windows/svc/mgr/service.go, vendor/golang.org/x/sys/windows/svc/security.go, vendor/golang.org/x/sys/windows/svc/service.go, vendor/modules.txt
This branch adds the abilitity to run buildkitd as a Windows service. Most of this code is shared with dockerd and containerd, with slight changes to adapt it to buildkit.
Not sure if this should be merged before everything else gets in and buildkit actually runs on Windows, so marking this as draft.
=> [Windows] Add Windows service support

README.md, cache/remotecache/export.go, cache/remotecache/import.go, cache/remotecache/local/local.go, cache/remotecache/registry/registry.go, client/client_test.go, frontend/dockerfile/dockerfile_test.go
This feature addition is an extension to the remote and local cache feature. This generally follows @joadrp's Proposal in #2251 while also taking in Tonis' comment on thread regarding an opt-in key for exporting with this new cache manifest format. https://github.com/moby/buildkit/issues/2251#issuecomment-879567871
To summarize, this commit adds:
- README change detailing the new `export-cache` key for both local and registry types
- added logic to plumb through `image-manifest` bool key with default False (opt-in) to the contentCacheExporter.
- added export contentCacheImporter logic to support both the new Image Manifest approach as well as the existing Image Index approach based on above key
- added import cache manifest inference logic to support and detect both the old and new cache …
=> Import/export support for OCI compatible image manifest version of cache manifest (opt-in on export, inferred on import)

util/testutil/integration/containerd.go, util/testutil/integration/dockerd.go, util/testutil/integration/oci.go, util/testutil/integration/run.go, util/testutil/integration/sandbox.go
This PR exposes the integration test workers as public, performing a few small refactors to make them more flexible (so that the caller can always enforce a custom name).
This is designed to be used in the context of https://github.com/docker/buildx/pull/1770, where we [wrap the `moby` worker to create the `docker` driver worker](https://github.com/docker/buildx/pull/1770/files#diff-592a8568a609f6623b5465a4a56ba7a9041a37f2394ed5d39385f78ec887694eR32-R38), and [wrap the `oci` worker to create the `remote` driver worker](https://github.com/docker/buildx/pull/1770/files#diff-247f899685dd94607c2a773712563962bb322403652cb4932771b9c56440c7d4R32-R36).
This allows us to avoid copying all the logic to spin up buildkit sandboxes inside of buildx, and to share that logic, so that we can …
=> Expose testutil integration workers as public

exporter/containerimage/export.go, exporter/containerimage/writer.go, exporter/oci/export.go, solver/llbsolver/solver.go, util/attestation/types.go, util/contentutil/copy.go, util/contentutil/types.go, util/imageutil/config.go, util/push/push.go
:arrow_up: Follow-up to #3063
This moves the containerd suppressions for media type warnings from the
exporter package into the push and copy packages which allow them to be
used by all lower-level buildkit utilities, e.g. tests: https://github.com/moby/buildkit/blob/81d19ad945cdbf921d182c50fc91169b1375b44d/util/testutil/integration/run.go#L256-L258.
Previously, this would cause containerd media type warnings to be printed in test logs if an image with attestations was copied into the local image cache.
While working on this, I also noticed that we can remove our custom definition of the `application/vnd.in-toto+json` media type and replace it with `intoto.PayloadType` (which we were already using in some places, but inconsistently).
=> Move containerd media type warnings for attestations

client/llb/diff.go, client/llb/exec.go, client/llb/fileop.go, client/llb/merge.go, client/llb/source.go, client/llb/sourcemap.go, client/llb/state.go
This is just a first round of "would have been useful to me" sort of documentation and examples for the LLB client API. This is not in any way exhaustive.
=> Add some doc strings for LLB functions

exporter/containerimage/writer.go, frontend/dockerfile/dockerfile2llb/image.go
- backport of https://github.com/moby/buildkit/pull/3104
- relates to https://github.com/moby/moby/pull/45437
The OCI image spec is considering to change the Image struct and embedding the Platform type (see opencontainers/image-spec#959) in the go implementation. BuildKit currently uses some struct-literals to propagate the platform fields, which will break once those changes in the OCI spec are merged.
Ideally (once that change arrives) we would update the code to set the Platform information as a whole, instead of assigning related fields individually, but in some cases in the code, image platform information is only partially set (for example, OSVersion and OSFeatures are not preserved in all cases). This may be on purpose, so needs to be reviewed.
This patch keeps the current …
=> [0.11 backport] Update uses of Image platform fields in OCI image-spec

session/session.go
Build call runs solve, session and status calls in parallel using errgroup. Session is closed after the solve call returns. If solve call returns very quickly there is a possibility that this close signal comes before the session has even been established. In that case session is established later and is kept running. This doesn't happen forever; there is a 3 second timeout in https://github.com/moby/buildkit/blob/v0.11.6/client/solve.go#L236 while we wait for the server to shut all other requests down gracefully. This means that when this case happens, for user's perspective, there is a 3-second pause, and after that everything continues normally.
=> session: fix run and close synchronization

session/session.go
- backport of https://github.com/moby/buildkit/pull/3881
(cherry picked from commit 64580e7bc084fafb405ff19f0ccb2c097e951698)
=> [0.11 backport] session: fix run and close synchronization

go.mod, go.sum, vendor/github.com/containerd/nydus-snapshotter/pkg/converter/convert_unix.go, vendor/modules.txt
In order to fix a bug when converting nydus image with an empty blob layer.
It fixes https://github.com/moby/buildkit/pull/3814#issuecomment-1554245344
=> bump nydus-snapshotter dependence to v0.8.2

client/client_test.go
If a different snapshotter service is used, it will walk on the wrong snapshotter, overlayfs, instead of the actual used one by containerd.
=> test: use appropriate snapshotter service to walk snapshots

control/control.go, snapshot/containerd/content.go, solver/llbsolver/history.go, util/leaseutil/manager.go, worker/base/worker.go, worker/runc/runc.go, worker/worker.go
Migrate history objects to separate namespace to holding
reference to a blob does not interfere with the GC labels
held for the same blobs by the containerd image store.
fixes #3797
@vvoland
=> llbsolver: move history blobs to a separate namespace

solver/llbsolver/provenance/predicate.go
:hammer_and_wrench: Fixes https://github.com/docker/buildx/issues/1836.
> ```
> panic: no ':' separator in digest ""
> goroutine 4749 [running]:
> github.com/docker/docker/vendor/github.com/opencontainers/go-digest.Digest.sepIndex({0x0, 0x0})
>         /go/src/github.com/docker/docker/vendor/github.com/opencontainers/go-digest/digest.go:153 +0x9a
> github.com/docker/docker/vendor/github.com/opencontainers/go-digest.Digest.Algorithm(...)
>         /go/src/github.com/docker/docker/vendor/github.com/opencontainers/go-digest/digest.go:122
> github.com/docker/docker/vendor/github.com/moby/buildkit/solver/llbsolver/provenance.slsaMaterials({{0xc001df0500, 0x3, 0x3}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
>         /go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solv …
```
=> provenance: fix possible empty digest access

solver/llbsolver/provenance/predicate.go
:cherries: Cherry-pick of #3896.
=> [v0.11] provenance: fix possible empty digest access

session/grpc.go
- backports https://github.com/moby/buildkit/pull/3882
- relates to https://github.com/moby/buildkit/issues/3871#issuecomment-1555406539
(cherry picked from commit de53eb0072e4a8feed27e670e045445f7289eabf)
=> [0.11 backport] session: avoid logging healthcheck error on canceled connection

go.mod, go.sum, vendor/github.com/containerd/go-runc/runc.go, vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go, vendor/modules.txt
full diff: https://github.com/containerd/go-runc/compare/f5d58d02d6c8...v1.1.0
=> vendor: github.com/containerd/go-runc v1.1.0

cache/refs.go, util/bklog/log.go
The trace logs now also include the pointer value of the ref, which serves as its "ID" amongst all the refs for the underlying record.
They also now include equal{Mutable,Immutable} IDs, which are otherwise hard to determine with the Usage API.
Finally, LazyStackTrace now has a MarshalText method which returns the same value as the existing String method. This allows it to work with custom logrus hooks that rely on marshaling the fields.
=> cache: add a few more fields to ref trace logs.

client/llb/diff.go, client/llb/fileop.go, client/llb/merge.go, client/llb/state_test.go
Afaics FileOp has the same behavior independently from the target platform, so don't include the platform value in the LLB digest. The same already happens for MergeOp/DiffOp.
Atm. when doing multi-platform builds, copying the same files in both architectures can create different LLB. BuildKit solver will discover that the vertexes are the same after doing the cache key computation but this means that it goes to the "merging edges" code path and some vertexes will be canceled. This means inefficient and more complicated codepath as well as weird output to the user.
I also discovered https://github.com/moby/buildkit/pull/1889 but have no memory of the full intentions behind it.
While modifying the tests to make sure that platform is still carried over correctly if run steps happen after …
=> llb: don't include platform in fileop proto

client/client_test.go, exporter/local/export.go, exporter/local/fs.go, exporter/tar/export.go
Pulled out the various exporter fixups from https://github.com/moby/buildkit/pull/3403, since we won't merge new attestation options for now.
=> Various exporter refactoring fixes

session/auth/authprovider/authprovider.go, session/auth/authprovider/authprovider_test.go
this looks like it was an accidental logic error during refactoring...but maybe there's some reason it's intended that i don't understand?
=> authprovider: fix a bug where registry-1.docker.io auth was always a cache miss

client/client_test.go, exporter/containerimage/writer.go, frontend/dockerfile/dockerfile_provenance_test.go, frontend/dockerfile/dockerfile_test.go, solver/llbsolver/provenance.go, solver/llbsolver/provenance/capture.go, solver/llbsolver/provenance/predicate.go, util/purl/image.go, util/purl/image_test.go
Previously, OCI layout sources were being incorrectly recorded in the materials.
There were two main issues:
- The URI was the docker reference, not a PURL. [The line to do a PURL translation was being used as a no-op](https://github.com/moby/buildkit/blob/36917a9b5e943b48fa67cf173f086e69ca7a477f/solver/llbsolver/provenance/predicate.go#L104).
- The image was being duplicated in the materials list. This was because we were not distinguishing between remote and local images in calls to `ResolveImageConfig` (which can take a `ResolverType` parameter to read from local oci stores).
Now locally loaded images are more reasonably recorded in the materials. See the added test.
=> Ensure Provenance Material URIs for OCI sources are configured to use `pkg:oci` PURLs 

control/control.go, exporter/containerimage/export.go, exporter/containerimage/exptypes/keys.go, exporter/containerimage/exptypes/types.go, exporter/containerimage/opts.go, exporter/exptypes/keys.go, exporter/util/epoch/parse.go
Make containerdimage attribute key names public, to make it easier for *some downstream* projects to use them without hardcoding them on their side 😅 .
=> containerimage: Export option keys

solver/llbsolver/history.go
The temporary lease must be passed via the context for the call to w.Commit() to prevent the cleanup of metadata resources before they are fully referenced.
This fixes https://github.com/moby/buildkit/issues/3921
=> llbsolver: set temporary lease in Commit context

solver/jobs.go
This fixes:
fatal error: concurrent map read and map write
```
goroutine 151083 [running]:
github.com/moby/buildkit/solver.(*Job).walkProvenance(0xc0005663c0, {0x1cf5008, 0xc00b1270e0}, {0x47?, {0x1cf7e60?, 0xc006e4a680?}}, 0xc00a1fc690, 0xc0200a7d28?)
/src/solver/jobs.go:545 +0x105
github.com/moby/buildkit/solver.(*Job).walkProvenance(0xc0005663c0, {0x1cf5008, 0xc00b1270e0}, {0x47?, {0x1cf7e60?, 0xc006e4a880?}}, 0xc00a1fc690, 0x163d22c9738c10eb?)
/src/solver/jobs.go:556 +0x273
github.com/moby/buildkit/solver.(*Job).walkProvenance(0xc0005663c0, {0x1cf5008, 0xc00b1270e0}, {0x47?, {0x1cf7e60?, 0xc006e4a900?}}, 0xc00a1fc690, 0x0?)
/src/solver/jobs.go:556 +0x273
github.com/moby/buildkit/solver.(*Job).walkProvenance(0xc0005663c0, {0x1cf5008, 0xc00b1270e0}, {0x47?, {0x1cf7e60?, 0xc006e4aac0?}}, …
```
=> solver: lock before using actives

frontend/gateway/gateway.go
According to [gRPC ClientStream interface documentation](https://pkg.go.dev/google.golang.org/grpc@v1.53.0#ClientStream.SendMsg) it isn't safe to call SendMsg on the same stream in different goroutines, which we do in LLBBridgeServer implementation. The generated bindings don't provide a mechanism to avoid this scenario. This change wraps LLBBridgeServer implementation with a custom locking behavior.
Should fix the scenario described by @sipsma in https://github.com/moby/buildkit/pull/3832
=> gateway: wrap ExecProcessServer Send calls with a mutex

util/progress/progressui/printer.go
fixes https://github.com/moby/buildkit/pull/3838#issuecomment-1581619566
@tianon 
@jedevc This is a client side fix, so should go to buildx.
=> progressui: fix index printing on partial rows

snapshot/localmounter_windows.go
This change leverages the recent changes in containerd to properly mount ```windows-layers```. The ```containerd``` mounter cannot handle bind mounts. These mounts will be implemented in ```buildkit``` using the bind filter.
Depends on:
* https://github.com/moby/buildkit/pull/3782
Note: this branch will not build until #3782 merges.
=> [Windows] Fix local mounter on Windows

solver/jobs.go
Related to #2303 
---
This PR attempts to fix the `panic: failed to get edge` error using the reproduction posted by @coryb here: https://github.com/moby/buildkit/issues/2303#issuecomment-1593711074.
It appears that it's possible for the digest merging logic in `loadUnlocked` to fail to accurately track which digest a vertex is using when it applies the `IgnoreCache` / `!IgnoreCache` merging logic. Specifically, a digest can get removed from the `actives` list too early if a vertex isn't tracking the correct digest.
It seems to be possible to get into this state with the following steps in order:
1. `loadUnlocked` is called with a vertex where `IgnoreCache` is false - this will add to actives using `v.Digest()`.
2. While that digest is active, another job calls `loadUnlocked` with the …
=> Fix issue with digest merge (inconsistent graph state)

util/testutil/integration/containerd.go, util/testutil/integration/dockerd.go, util/testutil/integration/oci.go, util/testutil/integration/run.go
This is so that we can allow workers to provision and manage resources that have a lifetime greater than a single sandbox.
Although none of our current workers currently implement this method, we want to implement this for buildx downstream to allow reusing docker daemons between docker-container workers.
=> tests: add worker cleanup method to interface

client/llb/imagemetaresolver/resolver.go, util/contentutil/refs.go
`NewResolver` calls `NewDockerAuthorizer` and `ConfigureDefaultRegistries`, both of which set the client if none is set;
https://github.com/containerd/containerd/blob/dd5e9f653813b3177c3b70ea03e20aaed397e1f9/remotes/docker/authorizer.go#L91-L99
```go
func NewDockerAuthorizer(opts ...AuthorizerOpt) Authorizer {
var ao authorizerConfig
for _, opt := range opts {
opt(&ao)
}
if ao.client == nil {
ao.client = http.DefaultClient
}
...
```
https://github.com/containerd/containerd/blob/dd5e9f653813b3177c3b70ea03e20aaed397e1f9/remotes/docker/registry.go#L156-L174
```go
func ConfigureDefaultRegistries(ropts ...RegistryOpt) RegistryHosts {
var opts registryOpts
for _, opt := range ropts {
opt(&opts)
}
return func(host string) ([]RegistryHost, error) {
config := RegistryHost{
Client: …
```
=> remove uses of deprecated ResolverOptions.Client

frontend/dockerfile/docs/reference.md
This known issue is long obsolete, as it was resolved in current AufS versions, and the AuFS storage driver was deprecated and removed.
=> docs: dockerfile: remove "known issues" related to AuFS

frontend/dockerui/config.go, frontend/dockerui/namedcontext.go, frontend/gateway/container/container.go, frontend/gateway/container/util.go, frontend/gateway/forwarder/forward.go, frontend/gateway/forwarder/frontend.go, frontend/gateway/gateway.go, solver/llbsolver/ops/exec.go
This allows overwriting the definition of `#syntax` names same as can be done with other dockerfile names.
=> gateway: enable named contexts for gateway frontend

frontend/dockerfile/dockerfile_provenance_test.go, frontend/dockerfile/dockerfile_test.go, solver/llbsolver/solver.go
fixes #3928
fixes #3562
depends on #3860
If resultProxy has been created but the result has not been
evaluated then it shouldn't show missing provenance error
for that result.
This patch works together with the previous one that fixes
error reporting on provenance creation.
https://github.com/moby/buildkit/compare/master...tonistiigi:buildkit:fix-missing-provenance?expand=1#diff-2fc2e99eea0899fac8a14da1878d67aa8520bed09be4de598226d4d29450d6c8R279
=> handle missing provenance for non-evaluated result 

hack/shell
Dev stage now requires custom entrypoint for containerd tests so setting entrypoint would override that and make the tests fail.
=> shell: start shell from cmd, not entrypoint

client/client_test.go
I was trying to debug #3401 but couldn't repro or understand how the race is possible as long as tests do not have inner parallelization. Adding more debug so if it happens again we have some extra data.
=> client: add extra debug to tests

client/client.go, cmd/buildctl/common/common.go, cmd/buildctl/main.go, docs/reference/buildctl.md
Provide a `WaitForReady` client method that performs a preflight request and specifies `grpc.WaitForReady(true)` to ensure that the `grpc.ClientConn` has established the underlying connection and that it can be considered available.
Performing this request prior to solves makes the client more robust in environments where the server is behind a proxy or part of a service mesh (e.g. Istio/Envoy). In these environments, connections may be prematurely closed prior to any client requests due to circuit breaking on max connections.
For the moment, this incurs a redundant request to `ListWorkers` which seemed to be the more backwards compatible request to make as a preflight; `Info` is not available in older versions. If buildkitd ever implements the `grpc.health.v1.Health` directly on its …
=> buildctl: Provide --wait option

cache/blobs.go, cache/filelist.go, cache/manager.go, cache/refs.go, cache/remote.go, client/llb/async.go, executor/oci/hosts.go, executor/oci/resolvconf.go, frontend/dockerui/config.go, solver/jobs.go, solver/llbsolver/bridge.go, solver/llbsolver/ops/file.go, source/containerimage/pull.go, util/flightcontrol/flightcontrol.go, util/flightcontrol/flightcontrol_test.go, util/pull/pull.go, util/push/push.go, util/resolver/authorizer.go, util/resolver/pool.go
This should be much safer than the `interface{}` casts.
=> move flightcontrol to use generics

Dockerfile
Also update Alpine edge digest.
=> dockerfile: update Alpine to 3.18

Makefile, docker-bake.hcl, hack/dockerfiles/vendor.Dockerfile
same as https://github.com/docker/buildx/pull/758
```shell
$ make mod-outdated
...
#12 145.6 +------------------------------------------------------------------------------+--------------------------------------+------------------------------------+--------+------------------+
#12 145.6 |                                    MODULE                                    |               VERSION                |            NEW VERSION             | DIRECT | VALID TIMESTAMPS |
#12 145.6 +------------------------------------------------------------------------------+--------------------------------------+------------------------------------+--------+------------------+
#12 145.6 | github.com/Azure/azure-sdk-for-go/sdk/azidentity                             | v1.1.0                               | …
```
=> dockerfile: mod-outdated target to check modules updates

client/client_test.go, exporter/containerimage/writer.go, solver/llbsolver/history.go
When moving blobs to history namespace also move the blobs the labels point to, but don't move actual image layers.
fixes #3893
@vvoland 
This was removed in https://github.com/moby/buildkit/commit/2be7e546e9502ded67f2c59be362dbed39fb9219 because I didn't want history objects to keep layers from getting deleted. But I didn't think about the case where image store using the same blob might still need the layers. Now when we move the blobs to separate history namespace, we can leave the layers in labels because if there is no image, then the main manifest will be released.
=> containerimage: keep layer labels for exported images

README.md, client/client_test.go, exporter/local/export.go, exporter/local/fs.go
adds `split` local exporter option which can be used to split result in subfolders when multiple references are exported (default `true`).
=> export(local): split opt

util/overlay/overlay_linux.go
Even with this commit, the `COPY --from=0 / /` workaround mentioned in `docs/build-repro.md` is *still* needed for most Dockerfiles. (See PR #3980 for the reason)
Partially closes #3168 (for overlayfs and stargz)
Relevant: 
- containerd/containerd#8764
=> overlay: set whiteout timestamps to 1970-01-01 (not to SOURCE_DATE_EPOCH)

frontend/dockerfile/dockerfile2llb/convert.go
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/issues/3889
Previously, it appears the permissions were 0664, which seems to be a typo of the above - there's no real reason for these permissions to be higher, so we can bring them down to be consistent with everywhere else we create files.
=> dockerfile: heredoc should use 0644 permissions

exporter/containerimage/export.go, exporter/oci/export.go
From slack:
> **jed**: for the unlazying stuff we do in the exporter - should we perform this in parallel over all the refs? I notice when it's pulling images, we actually pull two different architectures in sequence, instead of in parallel.
It's a pretty quick fix with an errgroup, but maybe it's intentional as is?
>
> **tonistiigi**: No reason this could be intentional
We can unlazy all the references in parallel, since these perform network operations, we should attempt to pull them all together, instead of one-after-each-other.
~~We can also use the `EachRef` helper to simplify the iteration over all the references - I think this now would include the attestation references? I don't think this affects anything since attestation references weren't lazily computed, and it just makes …
=> exporter: unlazy references in parallel

.golangci.yml, frontend/dockerfile/dockerfile2llb/convert.go, frontend/dockerfile/dockerfile2llb/convert_addchecksum.go, frontend/dockerfile/dockerfile2llb/convert_addgit.go, frontend/dockerfile/dockerfile2llb/convert_noaddchecksum.go, frontend/dockerfile/dockerfile2llb/convert_noaddgit.go, frontend/dockerfile/dockerfile_addchecksum_test.go, frontend/dockerfile/dockerfile_addgit_test.go, frontend/dockerfile/docs/reference.md, frontend/dockerfile/release/labs/tags
Graduate the following syntaxes added in `dockerfile:1.5-labs`:
- #2799 
- #3093
=> dockerfile: graduate `ADD <git ref>` and `ADD --checksum=<checksum>` from labs

client/client_test.go, exporter/containerimage/export.go
:hammer_and_wrench: Fix https://github.com/docker/buildx/pull/1813#issuecomment-1564619467 (see point 2 in https://github.com/moby/buildkit/issues/3891#issuecomment-1614641533)
:arrow_up: Fixes up https://github.com/moby/buildkit/pull/3251
cc @vvoland @rumpl
In https://github.com/moby/buildkit/pull/3251, we added an overly restrictive check for `unpackImage` which, while preventing it from unpacking images with no layers, also prevented it from unpacking multi-platform images.
This PR pushes the check further down into `unpackImage`, so that we can still unpack multi-platform images.
(Maybe also worth a cherry-pick back to the v0.11 branch?)
=> Fix containerimage multi-platform unpack

cache/util/fsutil.go
All messages returned by `os.Open` are guaranteed to return a `PathError`. However, as these error messages are printed, they include the temporary directory for the mounted reference which is not useful to the caller.
On an error, we can restore the filename in the PathError to the requested filename, as also seen in [os.DirFS](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/os/file.go;l=627-634).
In the following example, we perform a docker build in an empty directory:
Before:
```
$ docker buildx build .
[+] Building 0.0s (2/2) FINISHED                                                                                       docker:desktop-linux
=> [internal] load .dockerignore …
```
=> gateway: restore original filename in ReadFile error message

executor/resources/cpu.go
fix #3997
If kernel is configured with CONFIG_PSI_DEFAULT_DISABLED then PSI files exist but are unreadable.
=> allow ENOTSUP for PSI cgroup files

frontend/dockerfile/dockerfile_test.go, session/filesync/filesync.go
fixes #3927
Another option would be to create a second set of keys that use encoded values, but I think this should be safe enough and maintain backward compatibility.
=> filesync: fix handling non-ascii in file paths

.github/CONTRIBUTING.md, Dockerfile, Makefile, hack/test
This introduces new `BUILDFLAGS`, `VERIFYFLAGS`, and `CGO_ENABLED` build-args,
which can be used to change how buildkitd is compiled.
This, for example, can be used to enable the go data race detector during
integration testing:
CGO_ENABLED=1 BUILDFLAGS="-race" TESTFLAGS="-v -test.run=TestClientGatewayIntegration/TestClientGatewaySolve" TESTPKGS=./client ./hack/test integration
This additionally introduces a new `make test-race` target, which
simplifies how to run all tests with the race detector.
=> dockerfile: arg for controlling go build flags

exporter/containerimage/export.go
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/issues/3891
:warning: Requires https://github.com/moby/buildkit/pull/3982
This is a tricky case - essentially, we should not fail the unpack if buildkit has not built for it's native platform (e.g. building a `linux/amd64` image on a `linux/arm64` BuildKit).
Ideally, we would try and find a better candidate to unpack, but this is kinda tricky, since determining the intentions of the client is not super easy here. Firstly, we don't what the client's supported architectures are, so we can't determine which ones to unpack, and secondly, we don't even know what the user intends to do with the results.
By just disabling this error for now, with https://github.com/moby/moby/pull/45647, we'll just end-up loading each architecture on …
=> Skip over non-native platforms when unpacking image

util/resolver/resolver.go
Ref #3995
This reverts commit 73ef9e2e2c2199903cf3f21f1c8de026bdf629b5.
Setting timeout here may cause timeouts on uploading big layer blob.
@alexcb
=> Revert "specify a `ResponseHeaderTimeout` value"

executor/resources/sampler.go
Protect against data race occuring while both sampler.Run and sub.Close accesses the same data from multiple threads.
=> sampler data race fix

util/pull/pullprogress/progress.go
There's a context which gets recreated via
ctx = context.TODO()
which races with
go func() {
<-ctx.Done()
ticker.Stop()
}()
To prevent this, the original context reference should be passed in via an arg.
=> pullprogress data race

client/llb/fileop.go, client/llb/meta.go, client/llb/meta_test.go, client/llb/state.go, frontend/dockerfile/dockerfile2llb/convert.go, frontend/gateway/container/container.go, solver/llbsolver/file/backend.go, solver/llbsolver/ops/exec.go, util/system/path.go
This change properly handles paths on different platforms. In short, this change checks the target platform we're building an image for and applies normalization steps to make sure the file paths are valid. This makes buildkit properly handle paths on both *nix systems and on Windows.
Depends on:
* https://github.com/moby/buildkit/pull/3906
* https://github.com/moby/buildkit/pull/3907
Replaces:
* https://github.com/moby/buildkit/pull/3322 (see https://github.com/moby/buildkit/pull/3322#issuecomment-1560864125)
Note: This branch will fail to build until dependencies are merged. Leaving the old branch up, as it contains a longer discussion related to the changes in these 3 PRs.
Here is a test run with all 3 branches merged: https://github.com/gabriel-samfira/buildkit/actions/runs/5091195907 …
=> Handle file paths base on target platform

client/client_test.go, executor/oci/spec.go, executor/oci/spec_unix.go, executor/oci/spec_windows.go, frontend/dockerfile/dockerfile_test.go
This is not set by default by containerd default spec but needed for the cgroup mounts to be scoped to the ID by runc.
closes #3985
=> oci: make sure cgroupns is enabled if supported

client/client_test.go, util/compression/compression.go, util/compression/zstd.go, util/winlayers/applier.go
Before this, buildkit was able to create and push layers of type `vnd.docker.image.rootfs.diff.tar.zstd` but if you tried to then pull and unpack those layers in buildkit, you'd get an error from containerd: `failed to get stream processor for application/vnd.docker.image.rootfs.diff.tar.zstd: no processor for media-type`
While that media type is not official, [support for exporting it was added to buildkit in the past anyways since it works in practice and is accepted by many registries](https://github.com/moby/buildkit/pull/2344#discussion_r703068189). It thus seems logical that buildkit should also support pulling and unpacking those layers too.
~~The fix works by just registering a custom stream processor w/ containerd.~~
There is support for registering stream processors in …
=> compression: register docker zstd stream processor

cache/contenthash/checksum.go
Multiple calls to GetCacheContext may occur from multiple threads; however they should only occur when dealing with an ImmutableRef. For this case we still need to perform a lock to prevent data race warnings; however in reality the linkMap will be unused.
=> contenthash: data race

hack/test
related to
* https://github.com/moby/moby/pull/45932#issuecomment-1632069512
* https://github.com/moby/moby/issues/45935
Will allow to match go version used in moby during BuildKit tests.
=> hack: allow to set GO_VERSION during tests

Dockerfile
* follow-up https://github.com/moby/buildkit/pull/4018
Didn't catch we didn't have a `GO_VERSION` arg on v0.11 branch.
=> [0.11] Dockerfile: missing GO_VERSION arg

cmd/buildctl/common/common.go
:arrow_up: Follow up to #3586 
When combined with `--wait`, this ensures that we get a fast response when the server eventually opens up for connections.
=> buildctl: set max backoff delay to 1 second

frontend/dockerfile/dockerfile_test.go, session/filesync/filesync.go
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/pull/3946#discussion_r1257971201
This ensures that files with '%' and '+' can still be properly copied.
To prevent regressions, this also adds in a couple of example test cases.
=> filesync: escape special query characters

solver/llbsolver/solver.go
The order of rules in policy matters. Eg. in [DENY *, ALLOW ref] mixing the order would deny all sources so map can't be used to deduplicate the rules.
@cpuguy83 @tianon
=> llbsolver: fix policy rule ordering

client/client_test.go, util/testutil/containerd/containerd.go, util/testutil/integration/sandbox.go
- relates to https://github.com/moby/buildkit/pull/3263
- relates to https://github.com/docker/buildx/pull/1948
This function was introduced in 601dd5ba9b58cb309455f5ac1f905cb74b23e611, but brings in "containerd" as a dependency for testutil/integration, which results in many (indirect) dependencies.
Before this PR
After this PR
=> testutil: move CheckContainerdVersion to a separate package

Dockerfile
- partial backport of https://github.com/moby/buildkit/pull/3789
- only updated runc, but can also include the stargz and nerdctl versions ❓ 
- update runc to v1.1.7 (similar to https://github.com/moby/buildkit/pull/3886)
- update containerd to v1.6.21 (similar to https://github.com/moby/buildkit/pull/3886)
=> [0.11] Dockerfile: update runc v1.1.7, containerd v1.6.21

client/client_test.go, util/testutil/containerd/containerd.go, util/testutil/integration/sandbox.go
- backport of https://github.com/moby/buildkit/pull/4027
- relates to https://github.com/moby/buildkit/pull/3263
- relates to https://github.com/docker/buildx/pull/1948
This function was introduced in 601dd5ba9b58cb309455f5ac1f905cb74b23e611, but brings in "containerd" as a dependency for testutil/integration, which results in many (indirect) dependencies.
(cherry picked from commit 619a20df406b345e5ae319aa25d626dbde60c091)
=> [0.12 backport] testutil: move CheckContainerdVersion to a separate package

go.mod, go.sum, vendor/github.com/docker/docker/api/swagger.yaml, vendor/github.com/docker/docker/api/types/system/info.go, vendor/github.com/docker/docker/api/types/system/runtime.go, vendor/github.com/docker/docker/api/types/system/security_opts.go, vendor/github.com/docker/docker/api/types/types.go, vendor/github.com/docker/docker/api/types/types_deprecated.go, vendor/github.com/docker/docker/client/client.go, vendor/github.com/docker/docker/client/container_attach.go, vendor/github.com/docker/docker/client/container_exec.go, vendor/github.com/docker/docker/client/distribution_inspect.go, vendor/github.com/docker/docker/client/hijack.go, vendor/github.com/docker/docker/client/image_build.go, vendor/github.com/docker/docker/client/image_create.go, vendor/github.com/docker/docker/client/image_load.go, vendor/github.com/docker/docker/client/image_push.go, vendor/github.com/docker/docker/client/image_search.go, vendor/github.com/docker/docker/client/info.go, vendor/github.com/docker/docker/client/interface.go, vendor/github.com/docker/docker/client/plugin_install.go, vendor/github.com/docker/docker/client/plugin_push.go, vendor/github.com/docker/docker/client/plugin_upgrade.go, vendor/github.com/docker/docker/client/request.go, vendor/github.com/docker/docker/client/service_create.go, vendor/github.com/docker/docker/client/service_update.go, vendor/modules.txt
- relates to https://github.com/moby/moby/pull/45942
- relates to https://github.com/moby/moby/issues/45935
- relates to https://github.com/moby/buildkit/pull/4021
notable changes:
- client: define a "dummy" hostname to use for local connections fixes "invalid host" errors when compiled with go1.20.6 or go1.19.11
full diff: https://github.com/docker/docker/compare/98d3da79ef9c...8e51b8b59cb81efba9491bb98a80396f2e578fe4
=> vendor: github.com/docker/docker 8e51b8b59cb8 (master, v25.0.0-dev)

executor/resources/sys.go, executor/resources/sys_linux.go, executor/resources/sys_nolinux.go, solver/llbsolver/solver.go
- relates to https://github.com/moby/buildkit/pull/3860
- relates to https://github.com/moby/moby/pull/45966#issuecomment-1643548223
- relates to https://github.com/moby/moby/pull/46035
Commit 509cfa3916386d3d736ff9754c5caa8969724c4a (https://github.com/moby/buildkit/pull/3860) introduced the SysSampler, which measures resource consumption. However, for this it depends on prometheus' procfs. That package does not have build-tags but is a Linux-only implementation, which (by default) attempts to access `/proc`; https://github.com/prometheus/procfs/blob/v0.9.0/fs.go#L26-L33 https://github.com/prometheus/procfs/blob/v0.9.0/internal/fs/fs.go#L23-L24
This patch splits the implementation of "resource" into platform-specific files, and stubs out the NewSysSampler() on non-Linux platforms.
=> executor/resource: stub out NewSysSampler on Windows

executor/resources/sys.go, executor/resources/sys_linux.go, executor/resources/sys_nolinux.go, solver/llbsolver/solver.go
- backport of https://github.com/moby/buildkit/pull/4040
- relates to https://github.com/moby/buildkit/pull/3860
- relates to https://github.com/moby/moby/pull/45966#issuecomment-1643548223
- relates to https://github.com/moby/moby/pull/46035
Commit 509cfa3916386d3d736ff9754c5caa8969724c4a (https://github.com/moby/buildkit/pull/3860) introduced the SysSampler, which measures resource consumption. However, for this it depends on prometheus' procfs. That package does not have build-tags but is a Linux-only implementation, which (by default) attempts to access `/proc`; https://github.com/prometheus/procfs/blob/v0.9.0/fs.go#L26-L33 https://github.com/prometheus/procfs/blob/v0.9.0/internal/fs/fs.go#L23-L24
This patch splits the implementation of "resource" into platform-specific files, and …
=> [0.12 backport] executor/resource: stub out NewSysSampler on Windows

go.mod, go.sum, vendor/github.com/docker/docker/api/swagger.yaml, vendor/github.com/docker/docker/api/types/system/info.go, vendor/github.com/docker/docker/api/types/system/runtime.go, vendor/github.com/docker/docker/api/types/system/security_opts.go, vendor/github.com/docker/docker/api/types/types.go, vendor/github.com/docker/docker/api/types/types_deprecated.go, vendor/github.com/docker/docker/client/client.go, vendor/github.com/docker/docker/client/container_attach.go, vendor/github.com/docker/docker/client/container_exec.go, vendor/github.com/docker/docker/client/distribution_inspect.go, vendor/github.com/docker/docker/client/hijack.go, vendor/github.com/docker/docker/client/image_build.go, vendor/github.com/docker/docker/client/image_create.go, vendor/github.com/docker/docker/client/image_load.go, vendor/github.com/docker/docker/client/image_push.go, vendor/github.com/docker/docker/client/image_search.go, vendor/github.com/docker/docker/client/info.go, vendor/github.com/docker/docker/client/interface.go, vendor/github.com/docker/docker/client/plugin_install.go, vendor/github.com/docker/docker/client/plugin_push.go, vendor/github.com/docker/docker/client/plugin_upgrade.go, vendor/github.com/docker/docker/client/request.go, vendor/github.com/docker/docker/client/service_create.go, vendor/github.com/docker/docker/client/service_update.go, vendor/modules.txt
- backport of https://github.com/moby/buildkit/pull/4034
- relates to https://github.com/moby/moby/pull/45942
- relates to https://github.com/moby/moby/issues/45935
- relates to https://github.com/moby/buildkit/pull/4021
notable changes:
- client: define a "dummy" hostname to use for local connections fixes "invalid host" errors when compiled with go1.20.6 or go1.19.11
full diff: https://github.com/docker/docker/compare/98d3da79ef9c...8e51b8b59cb81efba9491bb98a80396f2e578fe4
(cherry picked from commit 806a19d4bb8e6346d528b420dab2012ff3209eed)
=> [0.12 backport] vendor: github.com/docker/docker 8e51b8b59cb8 (master, v25.0.0-dev)

frontend/dockerfile/dockerfile_test.go, go.mod, go.sum, vendor/github.com/containerd/containerd/Vagrantfile, vendor/github.com/containerd/containerd/container.go, vendor/github.com/containerd/containerd/images/archive/exporter.go, vendor/github.com/containerd/containerd/oci/spec_opts.go, vendor/github.com/containerd/containerd/oci/spec_opts_windows.go, vendor/github.com/containerd/containerd/task.go, vendor/github.com/containerd/containerd/task_opts.go, vendor/github.com/containerd/containerd/version/version.go, vendor/modules.txt
release notes: https://github.com/containerd/containerd/releases/tag/v1.6.21
Notable Updates
- update runc binary to v1.1.7
- Remove entry for container from container store on error
- oci: partially restore comment on read-only mounts for uid/gid uses
- windows: Add ArgsEscaped support for CRI
- oci: Use WithReadonlyTempMount when adding users/groups
- archive: consistently respect value of WithSkipDockerManifest
full diff: https://github.com/containerd/containerd/compare/c0efc63d3907...v1.6.21
=> [0.11] vendor: github.com/containerd/containerd v1.6.21

util/testutil/integration/pins.go
=> [0.11 backport] test: update pinned alpine and busybox images

client/client_test.go
* follow-up https://github.com/moby/moby/pull/45981#issuecomment-1646218160
https://github.com/moby/buildkit/pull/3713 didn't include cache backend compat check for `s3` and `azblob` as they were not yet backported to this branch (done in https://github.com/moby/buildkit/pull/4030).
=> [0.11] integration: missing cache compat check for s3 and azblob

cache/blobs.go, cache/blobs_linux.go, cache/compression_nydus.go, cache/manager.go, cache/manager_test.go, cache/refs.go, cache/remotecache/azblob/exporter.go, cache/remotecache/azblob/importer.go, cache/remotecache/gha/gha.go, cache/remotecache/import.go, cache/remotecache/inline/inline.go, cache/remotecache/s3/s3.go, exporter/containerimage/export.go, exporter/containerimage/writer.go, util/compression/estargz.go, util/compression/nydus.go, util/pull/pull.go, util/winlayers/differ.go
Dedupe the several "containerd.io/uncompressed" constants and literals into `github.com/containerd/containerd/labels.LabelUncompressed`
=> Dedupe "containerd.io/uncompressed" constants and literals

cache/compression_nydus.go, util/compression/nydus.go
https://github.com/moby/buildkit/pull/4058 refactored to use `github.com/containerd/containerd`, however, the import was not added to files with the nydus build tag.
=> nydus: fix missing imports

frontend/dockerfile/dockerignore/dockerignore.go, frontend/dockerfile/dockerignore/dockerignore_test.go, frontend/dockerui/config.go, frontend/dockerui/namedcontext.go
- relates to https://github.com/docker/cli/pull/4457
I'm considering moving this package to https://github.com/moby/patternmatcher (but no final "decision" yet). At least let's clean up this package a bit in case.
- don't use a temp-file for the test as all we need is a reader
- use a const and string-literal for the test-content, which makes it
slightly more readable
- don't use hard-coded tests for each line, but use an "expected" slice
- don't fail early if line-numbers don't match
Use "doc links" where possible, and better describe the function.
Before:
After:
While this function would usually be used for read a `.dockerignore` file,
it accepts a Reader and can also be used to handle ignore patterns from
other files (e.g. `Dockerfile.dockerignore`) or other sources. The error
was also …
=> frontend/dockerfile/dockerignore: assorted cleanups

cmd/buildkitd/main_containerd_worker.go, cmd/buildkitd/main_oci_worker.go, examples/buildkit0/buildkit.go, examples/buildkit1/buildkit.go, examples/buildkit2/buildkit.go, examples/buildkit3/buildkit.go, examples/buildkit4/buildkit.go, examples/gobuild/main.go, worker/containerd/containerd_test.go, worker/runc/runc_test.go
https://github.com/moby/buildkit/pull/3243 removed the `buildkitd.oci_only` and `buildkitd.containerd_only` binaries.
This PR cleans up the old build tags that were used for this, which we can now tidy up, since they shouldn't be in use anymore(?)
=> chore: remove old `no_{oci,containerd}_worker` build tags

executor/resources/monitor.go, executor/resources/types/types.go, executor/runcexecutor/executor.go
Before this, the runc executor did not close the cgroupRecord when the container exited non-zero, which resulted in goroutines leaking.
---
Verified the fix manually by getting goroutine stack dumps after builds that included failed execs finished, which previously showed a bunch of goroutines like this:
```
goroutine 748062 [select]:
github.com/moby/buildkit/executor/resources.(*Sampler[...]).run(0x1905f80)
/go/pkg/mod/github.com/moby/buildkit@v0.12.1-0.20230723195917-40aabfe76809/executor/resources/sampler.go:92 +0x70
created by github.com/moby/buildkit/executor/resources.(*Sampler[...]).Record
/go/pkg/mod/github.com/moby/buildkit@v0.12.1-0.20230723195917-40aabfe76809/executor/resources/sampler.go:83 +0x184
```
and now after the fix they are gone. Not sure if there's reasonable ways of …
=> executor: fix resource sampler goroutine leak

util/progress/progresswriter/reset.go
Picked from https://github.com/docker/buildx/pull/1968 (the `progress.Writer` interface is slightly different between buildx/buildkit, so we need this patch in both places).
No other parts of the progress rendering modify the inputs, so we should avoid this as well.
This actually fixes an edge case in pushWithMoby which writes the same VertexStatus multiple times, modifying the timestamps and similar. However, if the operation takes long enough the small time difference can accumulate, and move the Start time far into the past.
=> progress: don't modify ResetTime inputs

session/filesync/filesync.go, source/local/local.go
Found this while poking through filesync code, and thought I'd propose this.
It looks like the `override-excludes` property has been deprecated for several years - I can't find where this is actually used in the docker cli, so I think it may be worth finally actually removing. Maybe there's some reason we should still hang onto it? As far as I can tell though, it was never really used:
```
❯ git remote -v
origin	git@github.com:jedevc/cli.git (fetch)
origin	git@github.com:jedevc/cli.git (push)
upstream	git@github.com:docker/cli.git (fetch)
upstream	git@github.com:docker/cli.git (push)
$ git log upstream/master -SOverrideExcludes
commit 6fef143dbcf5fdcb436d05cf8e67d56c24bc4e6e
Author: CrazyMax <crazy-max@users.noreply.github.com>
Date:   Thu Feb 3 10:37:55 2022 +0100
Set buildx as default …
```
=> filesync: remove deprecated override-excludes

cmd/buildkitd/main.go, cmd/buildkitd/main_unix.go, cmd/buildkitd/main_windows.go, util/appdefaults/appdefaults_unix.go, util/appdefaults/appdefaults_windows.go, util/testutil/integration/containerd.go, util/testutil/integration/oci.go, util/testutil/integration/sandbox.go, util/testutil/integration/sandbox_unix.go, util/testutil/integration/sandbox_windows.go
fixes https://github.com/moby/buildkit/issues/4036
=> set tracing socket path to runtime dir

cmd/buildkitd/main.go, executor/resources/monitor.go, executor/resources/types/types.go, executor/runcexecutor/executor.go
- #3483 (https://github.com/moby/buildkit/pull/4078#pullrequestreview-1558652026)
- #4081
=> [v0.12.1] cherry-picks

docs/build-repro.md, frontend/dockerfile/dockerfile_test.go
We can't avoid squashing even after just fixing up whiteout timestamps (https://github.com/moby/buildkit/pull/3560#discussion_r1247003628) ; Squashing is still needed to apply the `touch`-ed timestamps across multiple `RUN` instructions.
Squashing will no longer be needed if we can merge:
- #3560.
=> docs/build-repro.md: fix description about squashing

.github/workflows/test-os.yml
=> ci(test-os): bump actions

frontend/dockerfile/docs/reference.md
ADD --checksum and git url graduated in v1.6,
removing the references to labs channel since
they are now in stable.
=> docs: removed labs ref for ADD checksum and git

frontend/dockerfile/docs/reference.md
Cherry-pick (clean):
- https://github.com/moby/buildkit/pull/4085
=> [0.12 backport] docs: removed labs ref for ADD checksum and git

client/build_test.go, client/client_nydus_test.go, client/client_test.go, client/mergediff_test.go, cmd/buildctl/build_test.go, cmd/buildctl/buildctl_test.go, frontend/dockerfile/dockerfile_heredoc_test.go, frontend/dockerfile/dockerfile_outline_test.go, frontend/dockerfile/dockerfile_provenance_test.go, frontend/dockerfile/dockerfile_runnetwork_test.go, frontend/dockerfile/dockerfile_targets_test.go, frontend/dockerfile/dockerfile_test.go, frontend/frontend_test.go, solver/jobs_test.go, util/testutil/helpers/azurite.go, util/testutil/helpers/minio.go, util/testutil/integration/registry.go, util/testutil/integration/run.go, util/testutil/integration/sandbox.go, util/testutil/integration/util.go, util/testutil/workers/backend.go, util/testutil/workers/containerd.go, util/testutil/workers/dockerd.go, util/testutil/workers/features.go, util/testutil/workers/oci.go, util/testutil/workers/sysprocattr_unix.go, util/testutil/workers/sysprocattr_windows.go, util/testutil/workers/util.go, worker/containerd/containerd_test.go
This patch splits up the integration test package down into several parts, the core integration helpers, the buildkit test workers and various test helpers.
With this, we can split the worker features off as well, which improves the general reusability of the package, so we can create our own custom features in buildx where we reuse this package.
=> tests: refactor integration test package

docs/build-repro.md, frontend/dockerfile/dockerfile_test.go
=> [0.12 backport] docs/build-repro.md: fix description about squashing

docs/build-repro.md, frontend/dockerfile/dockerfile_test.go
=> [0.11 backport] docs/build-repro.md: fix description about squashing

cmd/buildkitd/config/config.go, cmd/buildkitd/config/load_test.go, cmd/buildkitd/main.go, docs/buildkitd.toml.md, util/testutil/integration/sandbox.go, util/testutil/workers/containerd.go, util/testutil/workers/oci.go, util/testutil/workers/util.go
fixes https://github.com/moby/buildkit/issues/4100
Using an env var to set the otel socket path for the integration tests in https://github.com/moby/buildkit/pull/4078 requires to preserve the environment variables when using sudo for rootless mode but we can't use `-E` when we run a login shell (`-i`).
Specifying `BUILDKIT_TRACE_SOCKET` in buildkitArgs for oci and containerd workers in integration tests is tedious as tmpdir is not yet defined so I switched from an env var to a new `otel-socket-path` flag for the buildkitd command. I took the opportunity to also set a new section in the TOML config if that makes sense. Let me know if you prefer a new PR for this or if the flag is enough.
=> integration: fix rootless tests

cmd/buildctl/main.go, cmd/buildkitd/config/config.go, cmd/buildkitd/main.go, docs/buildkitd.toml.md, docs/reference/buildctl.md
This pull-request introduce a configuration option to set the log format to JSON. The option is available both via the config file and CLI arguments.
Solves https://github.com/moby/buildkit/issues/3133
config file entry
```toml
[log]
format = "json"
```
CLIs argument:
- `buildkitd --log-format json`
- `buildctl --log-format json`
Original work from @moeghanem and @benjamin010095. I forked https://github.com/moby/buildkit/pull/3824 and squashed the commits into a single one.
See also:
- https://github.com/moby/buildkit/pull/3824
- https://github.com/moby/buildkit/pull/3823
- https://github.com/moby/buildkit/pull/3822
=> Add support for JSON formatted logs

frontend/dockerfile/docs/reference.md
Unlike .gitignore, `*.md` in .dockerignore doesn't match `subdir/foo.md`. While the logic is in github.com/moby/patternmatcher, it is worth to note the difference in the reference document.
=> Clarify the behavior of wildcards in .dockerignore file

cache/refs.go, solver/cachekey.go, solver/cachemanager.go, solver/llbsolver/mounts/mount.go, solver/types.go, util/bklog/log.go
This adds trace logs to the solver's cache manager to assist debugging
cache misses+hits.
It also replace the LazyStackTrace struct with a function that returns a
stack trace string only if trace level is enabled, an empty string
otherwise. This makes it easier to use with logrus hooks that pass the
fields around to different goroutines without needing to try to "unlazy"
the fields first.
=> Improve cache related trace logging.

docs/annotations.md
Fix https://github.com/moby/buildkit/issues/4112.
This behavior was changed in https://github.com/moby/buildkit/pull/3283, but the corresponding docs were not updated.
=> Update docs to note that index annotations fail if an index is not produced

docs/buildkitd.toml.md
Fixes https://github.com/moby/buildkit/issues/4115.
In https://github.com/moby/buildkit/pull/3773 we added configurable percentages, however, the associated docs mention that the percentage is of "available disk space", which is technically incorrect. It should be "total disk space".
=> docs: update gcpolicy percentage to refer to total space

util/testutil/integration/sandbox.go, util/testutil/workers/features.go
This is intended to act as a helper to allow checking for the presence of sandbox worker features without skipping a test (which allows for defining different behavior if a feature is available or not).
=> test: add HasFeatureCompat helper

.github/workflows/test-os.yml, hack/Vagrantfile.freebsd13, hack/dockerfiles/freebsd-smoke.Dockerfile
related to https://github.com/moby/buildkit/actions/runs/5862123682/job/15893429656#step:5:12
It should have failed at https://github.com/moby/buildkit/blob/67e1e6d8075869b691abd1f2f1e5b96e10d7313e/hack/Vagrantfile.freebsd13#L40 but instead provisioning continue.
=> chore: split vagrant provisioning

cmd/buildkitd/main.go
Fixes https://github.com/moby/buildkit/issues/3591.
Buildkitd now supports a health service:
$ grpcurl -plaintext localhost:1234 list
...
grpc.health.v1.Health
...
Which can be used to implement a lightweight health check on the running server:
$ grpcurl -plaintext localhost:1234 grpc.health.v1.Health/Check
{
"status": "SERVING"
}
=> buildkitd: add grpc.health.v1.Health service

.github/workflows/.test.yml, .github/workflows/test-os.yml
Can't manage to repro https://github.com/moby/buildkit/issues/4146 so trying to correlate with specific runner configuration by dumping runner context on failure.
=> ci: dump context on failure

client/build_test.go, control/gateway/gateway.go, solver/errdefs/jobs.go, solver/jobs.go, solver/scheduler_test.go
Atm it returns `codes.Unknown`:
```
rpc error: code = Unknown desc = no such job <buildid>
```
But we should explicitly wrap `codes.NotFound`.
=> solver: wrap gRPC codes.NotFound on unknown build ID

solver/llbsolver/provenance.go
ResolveImageConfig can be called concurrently - for example, by dockerfile2llb during conversion, we loop through each stage and resolve the base image for that stage.
In the case that two calls to ResolveImageConfig finish at roughly the same time, we can hit an edge case where we attempt to modify the bridge's image records at the same time.
To fix this, we just need to use the bridge's mutex to prevent concurrent access here.
This should fix the following stack trace found in CI (https://github.com/moby/buildkit/actions/runs/5889475633/job/15972815280?pr=4041):
sandbox.go:144: goroutine 1079 [running]:
sandbox.go:144: github.com/moby/buildkit/solver/llbsolver.(*provenanceBridge).ResolveImageConfig(0xc000431e00, {0x1c2b040?, 0xc0008e5b30?}, {0xc00094ba00?, 0xc0003728f0?}, {0x0, …
=> solver: fix possible race for provenance ResolveImageConfig

docs/annotations.md, docs/buildkitd.toml.md, util/progress/multiwriter.go
- #4116
- #4121
- #4120
@crazy-max @jsternberg
=> [v0.12] v0.12.2 cherry-picks

examples/create-certs/Dockerfile, examples/create-certs/README.md, examples/create-certs/docker-bake.hcl
* relates to https://github.com/docker/docs/pull/17745
Adds a bake definition to ease BuildKit certs creation when using the Buildx `remote` driver.
Can be tested with:
```
SAN="localhost 127.0.0.1" docker buildx bake "https://github.com/crazy-max/buildkit.git#contrib-create-certs:examples/create-certs"
```
=> examples: create certs bake definition

solver/llbsolver/file/backend.go, solver/llbsolver/file/backend_test.go
The os.RemoveAll() call returns nil if the path doesn't exist. When the rmPath function is called with allowNotFound set to false, it doesn't change the behaviour of the function.
Change the code so if allowNotFound is set to false, we first check whether the file exists. If it doesn't exist, return an error.
Add tests for three relevant cases.
=> file: Fix incorrect handling of non-existent files in llbsolver's rmPath

client/graph.go, cmd/buildctl/build.go, docs/reference/buildctl.md, examples/build-using-dockerfile/main.go, util/progress/progressui/display.go, util/progress/progresswriter/printer.go
This adds an additional display output for the progress indicator to
support a json output. It refactors the progressui package a bit to add
a new method that takes in a `SolveStatusDisplay`. This
`SolveStatusDisplay` can be created by the user using `NewDisplay` with
the various modes as input parameters.
The json output will print the status updates and log messages for the
vertexes that have had updates. Each JSON blob has the same format and
it matches closely with the raw underlying status updates. The display
will still attempt to regulate the number of messages that come through
and will batch various events together if events are sent too quickly
according to the default parameters for rate limiting set in the
progressui package.
At the moment, there is no public API for creating …
=> progressui: adds a json output that shows raw events for the solver status

exporter/containerimage/image/docker_image.go
`StopTimeout` seems to have been copied accidentally and not really used. Remove to avoid confusion.
Ref: moby/moby#46313
=> docker: cleanup fields in image definition

source/git/source.go, source/git/source_test.go, util/gitutil/git_cli.go, util/gitutil/git_cli_helpers.go
Inspired by @vito's changes to the git operations in https://github.com/moby/buildkit/pull/3960#discussion_r1276334704
Essentially, this helps to reduce the number of arguments to each call to git, and makes any changes less error-prone, and makes the whole thing more reusable. When this is merged, we can use it in buildx as well, where we already have a similar implementation in https://github.com/docker/buildx/blob/master/build/git.go (since https://github.com/docker/buildx/pull/1297).
At the moment, this just has the basic `Run` operation, but I'm wondering if we want to add more utilities, as in the buildx implementation? I'll have a look and try and put together a list of utilities to include.
=> Centralize git cli operations

util/progress/progress_test.go
Without this commit, `go test -race ./util/progress` sees a race due to the
shadowed `ctx` variable.
```
==================
WARNING: DATA RACE
Read at 0x00c000206040 by goroutine 25:
github.com/moby/buildkit/util/progress.TestProgress.func1()
github.com/moby/buildkit/util/progress/progress_test.go:25 +0x44
golang.org/x/sync/errgroup.(*Group).Go.func1()
golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x6c
Previous write at 0x00c000206040 by goroutine 6:
github.com/moby/buildkit/util/progress.TestProgress()
github.com/moby/buildkit/util/progress/progress_test.go:28 +0x4a0
testing.tRunner()
testing/testing.go:1576 +0x188
testing.(*T).Run.func1()
testing/testing.go:1629 +0x40
Goroutine 25 (running) created at:
golang.org/x/sync/errgroup.(*Group).Go() …
```
=> util/progress: silence go test -race

.github/workflows/test-os.yml, hack/Vagrantfile.freebsd13
Sometimes, vagrant provisioning fails on build step. This may be mitigated by factoring the build step out of the vagrant box and cross-compiling FreeBSD binaries instead.
This change
- Adds steps to setup go, and compile binaries on the host machine
- Adjusts vagrant provisioners accordingly
=> FreeBSD CI: cross-compile binaries

session/filesync/filesync.go
Before this, CopyFileWriter just used metadata.NewOutgoingContext to set metadata, which results in any pre-existing metadata from the provided context to be removed.
Now, it gets the current metadata and then sets its own on top of that, so any pre-existing unrelated metadata is retained.
---
In Dagger we are integrating with buildkit at a somewhat deeper level and are making use of grpc metadata sent to client session attachables. There's a few other workarounds we can make if this change isn't desired for some reason, but overall just having buildkit retain unrelated grpc metadata during this call would be most convenient.
=> filesync: append rather than replace grpc md.

worker/base/worker.go
I've recently had corruption in bolt and while reviewing the code I happened to notice that
the metastore was not closed.   I don't have any reason to believe this caused my corruption issue
but probably good to do.
=> fix(metadata): close store on exit

client/llb/sourcemap.go, frontend/dockerfile/dockerfile_provenance_test.go, frontend/dockerfile/dockerfile_test.go
If build contains multiple subbuilds all of their sources are tracked in provenance attestations. When some subbuilds are coming from same source file (eg. same Dockerfile but different targets) currently the same file would appear in multiple times. This detects such duplicates and makes sure definitions from multiple subbuilds can map to same file.
=> llb: avoid duplicate instances of sourcemaps in provenance

source/http/source.go
I found this minor mistake not returning an err while reading the sources.  Looks like this was introduced during a refactor some time ago.
=> fix: return err when unable to hash

.github/workflows/.test.yml, .github/workflows/buildkit.yml, .github/workflows/dockerd.yml, .github/workflows/frontend.yml, .github/workflows/test-os.yml, .github/workflows/validate.yml
Github Actions are not kept up to date. We have the Dependabot conf https://github.com/moby/buildkit/blob/master/.github/dependabot.yml though but does not seem handled on the repo.
@tonistiigi Can you check if Dependabot is disabled on the repo? I think it should be under https://github.com/moby/buildkit/settings/security_analysis
=> ci: update github actions to latest stable

.golangci.yml, cmd/buildkitd/main.go, executor/resources/monitor.go
follow-up https://github.com/moby/buildkit/pull/3705
Looks to be an oversight from https://github.com/moby/buildkit/pull/3860.
=> use bklog instead of logrus

client/client.go, cmd/buildctl/common/common.go
:hammer_and_wrench: Fixes regression https://github.com/moby/buildkit/issues/4164, while preserving the spirit of https://github.com/moby/buildkit/pull/4015.
:arrow_backward: Reverts #4015.
When calling `client.Wait`, we want to avoid the default backoff behavior, because we want to achieve a quick response back once the server becomes active.
To do this, without modifying the entire client's exponential backoff configuration, we can use `conn.ResetConnectBackoff`, while attempting to reconnect every second.
Here are some common scenarios under the new `client.Wait` implementation:
- Server is listening: the call to `Info` succeeds quickly, and we return.
- Server is listening, but is behind several proxies and so latency is high: the call to `Info` succeeds slowly (up to …
=> Manually implement `client.Wait` backoffs

docs/buildkitd.toml.md
This support exists but was not documented in the example file.
It was implemented in [PR #1040](https://github.com/moby/buildkit/pull/1040/files#diff-505703229c6ae3d8dc2cac5ffce71376d27b24c18f119fa55d34d7c51105f034R55-R58) (June 2019), and that test snippet now lives here:
https://github.com/moby/buildkit/blob/97e0efaab19ba9881505a8b699d517b8ed413718/cmd/buildkitd/config/load_test.go#L67-L70
Closes: https://github.com/moby/buildkit/issues/3045
=> docs: Add `[dns]` snippet to `buildkitd.toml` example file

util/progress/progressui/display.go
Follow-up to #4113.
#4113 heavily refactored the interface to the progress display - since the parsing of display modes is now moved into `progressui.NewDisplay` and cannot be performed by a consumer, then we need to add the `quiet` mode as supported by buildx.
=> progress: add new quiet display mode

solver/llbsolver/solver.go
Backports https://github.com/moby/buildkit/pull/4014 to v0.11 so we can pull this into moby v24.
--
The older of rules in policy matters. Eg. in [DENY *, ALLOW ref] mixing the order would deny all sources so map can't be used to deduplicate the rules.
(cherry picked from commit 22d84461e4ed2e861c15ee1a1695dc75da27a9e3)
=> v0.11: backport llbsolver: fix policy rule ordering

README.md
Add a link to kraftkit LLB plugin for building unikernels via Unikraft and Docker.
=> Add Unikraft's kraft.yaml to list of LLB languages.

session/auth/authprovider/authprovider.go
This would segfault if SetLogger had not been called, because progresswriter.Wrap returns nil when its logger arg is nil, causing Credentials to return nil, nil.
=> authprovider: Fix error return from Credentials when logger is nil

util/progress/progressui/display.go
The original intention of accepting `console.File` was that the current
uses of this function in the codebase were always files and it seemed
helpful to restrict the API to `console.File` to aid developers into
passing the correct output.
There are circumstances outside of the codebase where the `io.Writer`
versions are used so `NewDisplay` has now been adapted to take an
`io.Writer` to allow for those cases more easily.
Related to https://github.com/moby/buildkit/pull/4113#issuecomment-1707144624.
=> progressui: modify NewDisplay to accept io.Writer instead of console.File

solver/llbsolver/ops/diff.go, solver/llbsolver/ops/merge.go
The digest of the merge/diff ops' CacheMap would be json strings like:
```
{"Type":"buildkit.merge.v0","Merge":{"inputs":[{"input":0},{"input":1}]}}
```
rather than a sha256.
I'm not sure what will happen with this change.
Also, even with this change I think all merge ops with two inputs would still hash to the same digest.  Is this ok?
I checked on all the other ops and they all correctly are sha256.
=> fix: use sha256 for merge/diff op cache maps
