- cmd/buildctl/diskusage.go
example output:
```
2017/06/12 08:57:49 ([]*client.UsageInfo) (len=4 cap=4) {
(*client.UsageInfo)(0xc4201251c0)({
ID: (string) (len=64) "fd61df8cfd7c3c236178beda263fe0caa631231ead8883d36c732f75beec8e93",
Mutable: (bool) false,
InUse: (bool) false,
Size: (int64) 4096
}),
(*client.UsageInfo)(0xc4201251e0)({
ID: (string) (len=71) "sha256:4ac76077f2c741c856a2419dfdb0804b18e48d2e1a9ce9c6a3f0605a2078caba",
Mutable: (bool) false,
InUse: (bool) true,
Size: (int64) 383803919
}),
(*client.UsageInfo)(0xc420125200)({
ID: (string) (len=64) "9aa83e93470e637ca3f88cce0448c5fdeb9b5f8741c37a96f4d49ab3d1fdbd5d",
Mutable: (bool) false,
InUse: (bool) true,
Size: (int64) 20480
}),
(*client.UsageInfo)(0xc420125240)({
ID: (string) (len=64) "a9a29e27f3fdd6f02e21438d37d9013199256593dd5bad4a4ecd04a2ca39cef6", …
```
> buildctl: du: use spew dump

- cmd/buildctl/debug.go
- cmd/buildctl/debug/dump.go
- cmd/buildctl/main.go
For https://github.com/tonistiigi/buildkit_poc/pull/5#issuecomment-307976424
> buildctl dump -> buildctl debug dump

- .travis.yml
- cache/refs.go
- gometalinter.json
- hack/dockerfiles/lint.Dockerfile
- hack/lint
- hack/test
- hack/validate-vendor
- util/progress/progress.go
- util/progress/progress_test.go
- add gometalinter.json
- fix go vet failures
- hack/test: add test for `go build ./...`
- add hack/validate-vendor
https://github.com/tonistiigi/buildkit_poc/pull/4#issuecomment-307977515
> Improve CI

- util/progress/progressui/display.go
- vendor.conf
- vendor/golang.org/x/time/LICENSE
- vendor/golang.org/x/time/PATENTS
- vendor/golang.org/x/time/README
- vendor/golang.org/x/time/rate/rate.go
- vendor/golang.org/x/time/rate/rate_go16.go
- vendor/golang.org/x/time/rate/rate_go17.go
> progress: add terminal size detection

- worker/runcworker/worker.go
> worker: detect missing runc early

- util/progress/progressui/display.go
@AkihiroSuda Does this look better to you? Still writes everything but doesn't clear. For writing only changed parts I think we would need to track the cursor position.
Still think there is a possible iTerm issue in here as both versions have no problems on stable build.
> progress: better protection against flickering

- cmd/buildd/debug.go
- cmd/buildd/main.go
- vendor.conf
- vendor/golang.org/x/net/http2/configure_transport.go
- vendor/golang.org/x/net/http2/errors.go
- vendor/golang.org/x/net/http2/go18.go
- vendor/golang.org/x/net/http2/http2.go
- vendor/golang.org/x/net/http2/not_go18.go
- vendor/golang.org/x/net/http2/pipe.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/idna/idna.go
- vendor/golang.org/x/net/trace/events.go
- vendor/golang.org/x/net/trace/trace.go
Add some more visibility to the buildd internals
@AkihiroSuda 
> buildd: enable debug handlers

- vendor.conf
- vendor/github.com/containerd/go-runc/monitor.go
remove fork and bring in containerd/go-runc#20 fix
> vendor: update go-runc

- hack/update-vendor
- hack/validate-vendor
> hack: pin to specific version of vndr

- client/llb/state.go
- control/control_standalone_test.go
- solver/exec.go
- solver/pb/const.go
- worker/oci/spec_unix.go
- worker/runcworker/worker.go
- worker/worker.go
Fixes random mount order.
@AkihiroSuda 
> worker: change mounts map to slice

- control/control_standalone.go
- control/control_standalone_test.go
- examples/buildkit2/buildkit.go
> remove unused code

- Makefile
- client/client_test.go
- client/client_windows.go
- cmd/buildctl/debug/dumpmetadata.go
- cmd/buildctl/main.go
- cmd/buildd/main.go
- hack/dockerfiles/test.Dockerfile
- hack/test-integration
- util/appcontext/appcontext.go
- util/appcontext/appcontext_unix.go
- util/appcontext/appcontext_windows.go
- util/appdefaults/appdefaults_unix.go
- util/appdefaults/appdefaults_windows.go
> support building on windows (no functional worker yet)

- cmd/buildctl/build.go
- session/filesync/diffcopy.go
- session/filesync/filesync.go
- session/filesync/tarstream.go
- source/local/local.go
- util/progress/progressui/display.go
- vendor.conf
- vendor/github.com/tonistiigi/fsutil/receive.go
- vendor/github.com/tonistiigi/fsutil/receive_unsupported.go
> source: add progress to local sources

- client/llb/llb.go
- solver/pb/const.go
- solver/pb/ops.pb.go
- solver/pb/ops.proto
> llb: add custom types for input indexes

- util/flightcontrol/flightcontrol.go
It was possible that `retry` error was returned to the first caller and was not handled. `errRetry` is returned when it detects that a function is running but has already completed before the waiter could be attached. In this case, currently, we just restart the function instead of reusing the result.
> flightcontrol: better errRetry handling

- .travis.yml
- hack/test
- hack/test-binaries
> .travis.yml: build Windows binaries

- client/llb/exec.go
- solver/exec.go
- vendor.conf
- vendor/github.com/mitchellh/hashstructure/LICENSE
- vendor/github.com/mitchellh/hashstructure/README.md
- vendor/github.com/mitchellh/hashstructure/hashstructure.go
- vendor/github.com/mitchellh/hashstructure/include.go
- worker/containerdworker/worker.go
- worker/oci/spec_unix.go
- worker/runcworker/worker.go
- worker/worker.go
> llb: add support for mounting subpath of reference

- README.md
> README.md: add badges

- client/client.go
> client: allow empty address for the system-default value

- client/llb/exec.go
- client/llb/llbbuild/llbbuild.go
- client/llb/source.go
- client/llb/state.go
> llb: add cache for marshalers

- solver/exec.go
> contenthash: use selector for content path

- client/llb/resolver.go
- client/llb/source.go
usage: `llb.Image("docker.io/library/golang:alpine", llb.WithDefaultMetaResolver)`
> llb: add meta resolver from image

- client/llb/resolver.go
#101 and #102 caused a merge conflict that broke ci
> fix CI after containerd update

- util/progress/progressui/display.go
> progressui: fix wrapping error on tabs

- frontend/dockerfile/dockerfile2llb/convert.go
- solver/exec.go
Fixes up some path handling and only mounts subpaths to speed up content checksums. Source for helper image is in https://github.com/tonistiigi/copy
> dockerfile: improve copy implementation

- examples/gobuild/main.go
- examples/gobuilder/gobuilder.go
Example of generating llb for a `go build`
Rough hack atm. I plan to change it to nested build and move to another repo. But could be useful temporarily for trying some big graphs. No support for cgo yet.
you should use #117 when trying these
@AkihiroSuda 
> examples: add example for generating llb from go

- cache/manager.go
- client/llb/resolver.go
- client/llb/source.go
- frontend/dockerfile/dockerfile.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/frontend.go
- solver/exec.go
- solver/solver.go
- source/containerimage/pull.go
- util/imageutil/config.go
In separate commits:
- Cleanup to the dockerfile frontend
- Add ONBUILD support
- Resolve reference to digest to avoid repulling it later instead of current results cache. This also fixes a panic with unsafe map writes(cc @vdemeester )
> Dockerfile frontend update

- client/solve.go
- worker/runcworker/worker.go
> remove generateID duplicates

- examples/buildkit0/buildkit.go
- examples/buildkit1/buildkit.go
- examples/buildkit2/buildkit.go
- examples/buildkit3/buildkit.go
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> Update runc to rc4 in examples 👼

- cache/cacheimport/export.go
- exporter/containerimage/export.go
- util/push/push.go
> exporter: allow push to http registry

- cache/refs.go
- solver/solver.go
> cache, solver: refactor Reference interface

- frontend/dockerfile/cmd/dockerfile-frontend/main.go
- frontend/dockerfile/dockerfile.go
- frontend/dockerfile/dockerfile2llb/convert.go
```
buildctl build --frontend dockerfile.v0 --frontend-opt=context=git://github.com/moby/moby
buildctl build --frontend gateway.v0 --frontend-opt=source=tonistiigi/dockerfile:next  --frontend-opt=context=git://github.com/tonistiigi/buildkit_http_sample
```
> dockerfile: allow building from git

- README.md
> readme: add more examples

- cache/blobs/blobs.go
- cache/cacheimport/export.go
- control/control_containerd.go
- control/control_standalone.go
- exporter/containerimage/export.go
> Export compressed blobs

- cache/manager.go
- cache/manager_test.go
- cache/refs.go
- session/grpchijack/dial.go
- snapshot/blobmapping/snapshotter.go
- solver/jobs.go
- solver/solver.go
- source/identifier.go
- util/bgfunc/bgfunc_test.go
- worker/containerdworker/worker.go
Fixed some warnings from the report card. Should cover everything but the missing comments.
> cleanup linter warnings

- vendor.conf
- vendor/github.com/tonistiigi/fsutil/receive.go
> vendor: update fsutil to efacb76f11

- source/containerimage/pull.go
Last containerd vendor had a fix for https://github.com/containerd/containerd/issues/1791 so bringing in schema1 pull support for image source.
> containerimage: add schema1 pull support

- cmd/buildctl/build.go
- cmd/buildctl/main.go
- util/progress/progressui/display.go
> buildctl: disable progressbar if no console

- cmd/buildd/main.go
> buildd: allow multiple listener addresses

- cache/blobs/blobs.go
- client/llb/state.go
- exporter/local/export.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/image.go
- frontend/dockerfile/dockerfile_test.go
- solver/solver.go
> dockerfile: return valid empty image config for scratch

- client/client_test.go
- hack/dockerfiles/test.Dockerfile
- util/testutil/integration/containerd.go
- util/testutil/integration/registry.go
- util/testutil/integration/run.go
- util/testutil/integration/standalone.go
> client: add tests for differ and pushed data

- cache/contenthash/checksum_test.go
- cache/manager_test.go
- cache/metadata/metadata_test.go
- client/client_test.go
- client/llb/llbbuild/llbbuild_test.go
- client/llb/state_test.go
- cmd/buildctl/diskusage_test.go
- control/control_standalone_test.go
- frontend/dockerfile/dockerfile2llb/convert_test.go
- session/filesync/filesync_test.go
- source/git/gitsource_test.go
- source/http/httpsource_test.go
- util/bgfunc/bgfunc_test.go
- util/flightcontrol/flightcontrol_test.go
- util/progress/progress_test.go
These tests don't have any shared resources so they should work fine in parallel.
> set more tests to parallel

- client/llb/imagemetaresolver/resolver.go
> imageresolver: fix concurrent map writes

- source/git/gitsource.go
- source/git/gitsource_test.go
port of https://github.com/moby/moby/pull/35737
> git: fix checking out submodules

- worker/containerdworker/worker.go
> worker: fix containerd cancellation and cleanup

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
`EXPOSE` uses custom variable replacement rules that were not implemented yet. 
> dockerfile: add support for EXPOSE args

- frontend/dockerfile/dockerfile2llb/convert.go
- source/containerimage/pull.go
- util/imageutil/config.go
- imageutil: avoid pulling unwanted manifests
- source: avoid parallel resolve of same config
- dockerfile: avoid pulling config for unreachable stages
This mostly increases the startup time on building dockerfiles.
> Optimize config resolve

- worker/runc/runc_test.go
Saw this test fail with a "nil dereference" panic (I think because of network problem). Change to require so it stops with the correct error.
> runc: change runc test to require

- executor/containerdexecutor/executor.go
fixes issue introduced in #201 . Cancellation timeout was created too early.
> containerd: fix cancellation issue

- .travis.yml
- Makefile
- README.md
- hack/dockerfiles/test.Dockerfile
> Makefile: add `install` and `clean`

- README.md
- client/client_test.go
- client/exporters.go
- client/solve.go
- cmd/buildctl/build.go
- exporter/containerimage/export.go
- exporter/containerimage/writer.go
- exporter/oci/export.go
- session/filesync/diffcopy.go
- session/filesync/filesync.go
- util/progress/progressui/display.go
- vendor/github.com/containerd/containerd/images/oci/exporter.go
- vendor/github.com/containerd/containerd/images/oci/importer.go
- worker/worker.go
Exports OCI image bundle to the client
```
buildctl build ... --exporter=oci --exporter-opt output=path/to/output.tar
buildctl build ... --exporter=oci > output.tar
```
> exporter: add OCI exporter

- frontend/dockerfile/dockerfile.go
> dockerfile: fix wrong context passed to build

- solver/load.go
- solver/source.go
- source/identifier.go
> source: add function for parsing llb to identifier

- cmd/buildctl/debug/dumpmetadata.go
- worker/runc/runc.go
> buildctl: fix dump-metadata

- solver/llbsolver.go
- worker/base/worker.go
- worker/worker.go
requested in https://github.com/moby/buildkit/pull/220#issuecomment-352545974
> worker, solver: s/ResolveVertex/ResolveOp/g

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
https://github.com/tonistiigi/copy/pull/2
Switches copy binary to go implementation to support this. If we add `CopyOp` it should use the same implementation. I also created extraction part for fsutil before realizing that `--chown` can't be really used with archives. So didn't include that yet in copy image, but this could be switched on later.
This should be the last missing Dockerfile feature that I know about. Let me know if there is anything else missing(or better - create a failing test for it).
> dockerfile: add copy —-chown support

- .travis.yml
- hack/lint
- hack/test
- hack/update-vendor
- hack/validate-vendor
> travis: use the default version of Docker Engine (17.09)

- README.md
> readme: fix word

- frontend/gateway/gateway.go
> gateway: allow skipping tag in source parameter

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: fix copy with wildcards and add tests

- client/client_test.go
- exporter/containerimage/writer.go
> exported: fix image creation time on export

- client/client_test.go
> client: fix tests to wait snapshots to become releasable

- vendor.conf
- vendor/github.com/tonistiigi/fsutil/walker.go
bring in https://github.com/tonistiigi/fsutil/pull/21
> vendor: update fsutil to 0b8b62dee

- README.md
- examples/buildkit0/buildkit.go
- examples/buildkit1/buildkit.go
- examples/buildkit2/buildkit.go
- examples/buildkit3/buildkit.go
- hack/dockerfiles/test.Dockerfile
- vendor.conf
- vendor/github.com/containerd/containerd/archive/tar.go
- vendor/github.com/containerd/containerd/cio/io.go
- vendor/github.com/containerd/containerd/client.go
- vendor/github.com/containerd/containerd/defaults/defaults_unix.go
- vendor/github.com/containerd/containerd/defaults/defaults_windows.go
- vendor/github.com/containerd/containerd/defaults/doc.go
- vendor/github.com/containerd/containerd/dialer/dialer.go
- vendor/github.com/containerd/containerd/fs/copy_linux.go
- vendor/github.com/containerd/containerd/fs/copy_unix.go
- vendor/github.com/containerd/containerd/log/context.go
- vendor/github.com/containerd/containerd/metadata/buckets.go
- vendor/github.com/containerd/containerd/metadata/images.go
- vendor/github.com/containerd/containerd/metadata/namespaces.go
- vendor/github.com/containerd/containerd/oci/spec_opts.go
- vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
- vendor/github.com/containerd/containerd/plugin/context.go
> update containerd (binary: v1.0.1, library: Jan 23, 2018)

- cache/instructioncache/local/localinstructioncache.go
- client/client_windows.go
- client/llb/meta.go
- frontend/dockerfile/dockerfile2llb/convert.go
- gometalinter.json
- session/grpchijack/dial.go
- solver/llbbridge.go
- solver/load.go
- source/containerimage/pull.go
it tends to help keeping uneeded code out O:)
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> Add deadcode to the linter

- solver-next/edge.go
- solver-next/index.go
- solver-next/jobs.go
- solver-next/scheduler.go
- solver-next/scheduler_test.go
> solver: add ignore-cache vertex options

- cmd/buildctl/buildctl_test.go
test for bugs like https://github.com/moby/buildkit/pull/265
> buildctl: add test for usage

- client/client_test.go
> client: test duplicate entries in result tarballs

- solver-next/jobs.go
- solver-next/scheduler_test.go
> solver: add tests for subbuild

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: fix copy from implicit stage

- solver-next/boltdbcachestorage/storage.go
- solver-next/boltdbcachestorage/storage_test.go
- solver-next/cache.go
- solver-next/cachestorage.go
- solver-next/cachestorage_testsuite.go
- solver-next/memorycachestorage.go
- solver-next/memorycachestorage_test.go
> solver: add boltdb cache store and test suite

- frontend/gateway/gateway.go
> gateway: typo fix

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
I discovered an issue where contenthash was ignoring some files that appeared between the directory name and its subfiles. So for example having files `foo`, `foo.go`, `foo/bar`, `foo.go` was ignored as it was counted as being after a directory but not counted as files under `foo/`. The fix is to switch from `/` to `NULL` in the boltdb keys so they always appear next to each other.
> contenthash: fix ignored files from path separator

- solver-next/jobs.go
If a vertex has already been loaded by the same job it can be skipped with all of its children.
> solver: faster vertex loading

- worker/base/worker.go
> export cache

- client/llb/imagemetaresolver/resolver.go
- util/contentutil/buffer.go
- util/contentutil/buffer_test.go
- util/contentutil/copy.go
- util/contentutil/copy_test.go
- util/contentutil/fetcher.go
- util/contentutil/fetcher_test.go
- util/contentutil/multiprovider.go
- util/contentutil/multiprovider_test.go
> util: add contentutil helpers

- executor/runcexecutor/executor.go
- hack/dockerfiles/test.Dockerfile
- vendor/github.com/containerd/containerd/contrib/README.md
- vendor/github.com/containerd/containerd/contrib/seccomp/seccomp.go
- vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
> add containerd package for default seccomp profile

- client/client_test.go
- client/exporters.go
- client/solve.go
- cmd/buildctl/build.go
- examples/build-using-dockerfile/main.go
- frontend/dockerfile/dockerfile_test.go
- session/filesync/filesync.go
Fix https://github.com/moby/buildkit/issues/325
> client: support passing io.WriteCloser via SolveOpt for FSSyncTargetFile

- client/client_test.go
- client/solve.go
- cmd/buildctl/build.go
close https://github.com/moby/buildkit/issues/327
> client: disallow empty output for exportation

- api/services/control/control.pb.go
- cache/contenthash/checksum.pb.go
- frontend/gateway/pb/gateway.pb.go
- hack/update-generated-files
- hack/validate-generated-files
- session/auth/auth.pb.go
- session/filesync/filesync.pb.go
- solver/pb/ops.pb.go
First bump the generated files to gogoproto v0.5 (as seen in `vendor.conf`) and then update the update/validate scripting to get the version from `vendor.conf` so they stay in sync.
Fix the message telling users how to regenerate while I'm there.
> Consolidate gogoproto versions

- util/push/push.go
> util: make push depend on provider

- executor/runcexecutor/executor.go
- worker/runc/runc.go
> runc: make command name configurable

- executor/runcexecutor/executor.go
> runc: set command name from config

- source/git/gitsource.go
- source/git/gitsource_test.go
> git: fix cachemap bug on sha identifier

- cache/cacheimport/v1/cachestorage.go
- client/client_test.go
Also fixes the result checking that broke in #349 that makes the test pass
>  client: add basic cache import test

- cache/refs.go
> cache: fix refs unlocking bug

- snapshot/containerd/snapshotter.go
Avoid race where a reference is asked while it has been removed but not cleaned up by snapshotter GC yet. Currently, it is possible that stat returns ok although snapshot will get deleted when gc completes and next calls to prepare will fail because of a missing parent.
> snapshotter: avoid snapshot removal race

- docs/solver.md
> solver-next: add design doc

- cache/cacheimport/v1/doc.go
- cache/manager.go
- frontend/dockerfile/dockerfile_test.go
- worker/base/worker.go
> cache: maintain creation time with remote cache

- snapshot/containerd/content.go
Similar fix as #358 for the contentstore
> containerd: avoid contentstore race

- exporter/containerimage/export.go
> exporter/containerimage: error on malformed boolean option

- exporter/containerimage/export.go
> exporter/containerimage: fix handling empty option values

- hack/dockerfiles/test.Dockerfile
- util/testutil/integration/containerd.go
Fix https://github.com/moby/buildkit/issues/331
> integration: add containerd v1.1

- frontend/dockerfile/dockerfile2llb/convert.go
> dockerfile: ensure Labels map is not accessed when nil

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: allow builds from http context

- source/containerimage/pull.go
- util/pull/pull.go
- util/pull/resolver.go
ref: https://github.com/genuinetools/img/pull/90
> split puller from source/containerimage into util/pull

- source/http/httpsource.go
> http: allow setting transport from options

- docs/solver.md
> docs: fix typos

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
Fix https://github.com/moby/buildkit/issues/386
> dockerfile: fix `ADD https://.../foo.tar.gz /local/foo.tar.gz` 

- frontend/dockerfile/dockerfile_test.go
> dockerfile: add global arg test

- client/client_test.go
- client/llb/meta.go
- client/llb/meta_test.go
> llb: fix relative working directory in client

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
https://github.com/tonistiigi/copy/pull/3
> dockerfile: use updated tonistiigi/copy:v0.1.1 image

- executor/containerdexecutor/executor.go
- executor/runcexecutor/executor.go
- util/system/seccomp_linux.go
- util/system/seccomp_nolinux.go
> executor: runtime check if seccomp is supported

- solver/llbsolver/ops/exec.go
Forgot to remove this debug message in #400
> exec: remove debug

- util/progress/progressui/display.go
> progressui: handle zero window size

- README.md
- docs/rootless.md
@tonistiigi thanks for finding the typo
> fix rootless docs

- docs/rootless.md
- examples/buildkit0/buildkit.go
- examples/buildkit1/buildkit.go
- examples/buildkit2/buildkit.go
- examples/buildkit3/buildkit.go
- hack/dockerfiles/test.Dockerfile
I'll try to add integration test as well in a follow-up PR.
> test.Dockerfile: new target: "rootless"

- cmd/buildkitd/main_oci_worker.go
before: `org.mobyproject.buildkit.worker.snapshotter:auto`
after:  `org.mobyproject.buildkit.worker.snapshotter:overlayfs`
> oci-worker: resolve snapshotter label to real name

- cmd/buildctl/build.go
My `/tmp` was unexpectedly full of `/tmp/buildctlXXXXXXXXX`, lets stop doing
that by default.
Suggesting `/dev/null` as an example seemed a bit strange with the default
changed, so dropped that too while editing.
> buildctl: do not trace unless asked.

- source/identifier.go
> source: remove debug

- frontend/dockerfile/dockerfile2llb/convert.go
> dockerfile: update copy image to v0.1.3

- client/client_test.go
- vendor.conf
- vendor/github.com/tonistiigi/fsutil/walker.go
> vendor: update fsutil to fix local source bug

- README.md
> readme: remove usage warning

- frontend/dockerfile/builder/build.go
> dockerfile: escape git regexp

- frontend/gateway/gateway.go
This could cause concurrent maps access panic.
@tiborvass 
> gateway: protect gateway forwarder map access

- frontend/dockerfile/dockerfile2llb/convert.go
- vendor.conf
- vendor/github.com/containerd/containerd/images/image.go
- vendor/github.com/containerd/containerd/platforms/database.go
- vendor/github.com/containerd/containerd/platforms/platforms.go
- vendor/github.com/containerd/containerd/vendor.conf
Update containerd to have a fix for arm platform filtering and switch dockerfile copy image to the version that is a manifest list with arm support.
> vendor: update containerd to 08f7ee982

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_test.go
Related: https://github.com/moby/moby/issues/37325
> Ensure BaseName of Stage is not blank

- frontend/dockerfile/shell/equal_env_unix.go
- frontend/dockerfile/shell/equal_env_windows.go
> Fix a typo

- util/testutil/integration/oci.go
- This PR re-enables the debug messages from integration tests.
Signed-off-by: Anda Xu <anda.xu@docker.com>
> Re-enable debug log

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_test.go
> Return an error when copying from url

- util/progress/progressui/display.go
> progressui: fix log line separation bug

- vendor.conf
- vendor/github.com/containerd/console/console_linux.go
- vendor/github.com/containerd/containerd/cio/io.go
- vendor/github.com/containerd/containerd/container.go
- vendor/github.com/containerd/containerd/oci/spec_unix.go
- vendor/github.com/containerd/containerd/vendor.conf
- vendor/github.com/containerd/typeurl/types.go
Make sure updated maskedpaths are used.
> vendor: update containerd to b4163374

- client/client_test.go
- client/llb/source.go
- client/llb/state.go
- solver/pb/attr.go
> llb: set unique ID to local sources without session

- util/progress/progressui/printer.go
Do not keep printing "done" items and only report progress at most every 5s.
I think this is more of a strawman than a real fix, partly because I'm not sure it's not an issue server side that the "done" items keep getting repeated and partly because it might be the case that some other display format might be even better (discussed at the end).
I noticed this because these log dominate our CI log files and make it rather hard to actually find anything since it can be pages and pages of repeating sha256 lines.
My test case is to start a fresh buildkitd (with no caches, I'm using OCI worker since that makes it a bit easier than removing things from container level) and then:
```
$ cat Dockerfile.maven
FROM maven:latest
$ buildctl build …
```
> Reduce verbosity of non-console solve status.

- frontend/dockerfile/forward.go
- solver/llbsolver/vertex.go
> frontend: fix two data races

- vendor.conf
- vendor/github.com/tonistiigi/units/bytes.go
> vendor: update units to 6950e57a

- control/control.go
> control: fix data race on prune

- frontend/gateway/gateway.go
> gateway: fix product env passing

- exporter/local/export.go
- session/filesync/diffcopy.go
- session/filesync/filesync.go
- vendor.conf
- vendor/github.com/tonistiigi/fsutil/fs.go
- vendor/github.com/tonistiigi/fsutil/send.go
split out from #499 for easier review
> vendor: update fsutil to cb2ad947b

- source/containerimage/pull.go
> image: fix platform passing on config resolve

- client/llb/imagemetaresolver/resolver.go
> imagemetaresolver: use platform in cache

- frontend/dockerfile/instructions/parse.go
> Add a description about metaArgs return value

- frontend/dockerfile/dockerfile2llb/convert_test.go
> Add test cases for `addEnv` which is a bit complicated function

- util/testutil/integration/oci.go
> integration: skip rootless if unsupported

- cmd/buildctl/build.go
- session/secrets/secretsprovider/file.go
- session/secrets/secretsprovider/secretsprovider.go
> buildctl: allow passing secret values from files

- control/control.go
- solver/boltdbcachestorage/storage.go
- solver/cachemanager.go
- solver/llbsolver/result.go
- solver/llbsolver/solver.go
- solver/testutil/cachestorage_testsuite.go
- worker/cacheresult.go
fix #529 
First commit is the fix for #529 . The second commit is another issue I discovered while testing this that left some records still to bolt after release.
> Fix cache metadata release

- frontend/dockerfile/dockerfile_test.go
- vendor.conf
- vendor/github.com/tonistiigi/fsutil/diff_containerd.go
- vendor/github.com/tonistiigi/fsutil/diskwriter.go
Brings in a fix for incremental local source upload when a directory changed to a file in the context
>  vendor: update fsutil to b19464cd

- cache/contenthash/checksum_test.go
- vendor.conf
- vendor/github.com/containerd/containerd/archive/tar.go
- vendor/github.com/containerd/containerd/client.go
- vendor/github.com/containerd/containerd/client_opts.go
- vendor/github.com/containerd/containerd/lease.go
- vendor/github.com/containerd/containerd/leases/id.go
- vendor/github.com/containerd/containerd/leases/lease.go
- vendor/github.com/containerd/containerd/leases/proxy/manager.go
- vendor/github.com/containerd/containerd/metadata/adaptors.go
- vendor/github.com/containerd/containerd/metadata/gc.go
- vendor/github.com/containerd/containerd/metadata/leases.go
- vendor/github.com/containerd/containerd/plugin/plugin.go
- vendor/github.com/containerd/containerd/services.go
- vendor/github.com/containerd/containerd/snapshots/native/native.go
- vendor/github.com/containerd/containerd/sys/reaper.go
- vendor/github.com/containerd/containerd/sys/reaper_linux.go
- vendor/github.com/containerd/containerd/task.go
- vendor/github.com/containerd/containerd/task_opts.go
- vendor/github.com/containerd/containerd/vendor.conf
- - -
Fix https://github.com/moby/buildkit/issues/520#issuecomment-406329609 via https://github.com/containerd/containerd/pull/2485
> vendor: update containerd

- util/winlayers/applier.go
In case of an error on unpack there was a race that could cause `bufio.Read` to be called after compressstream has called `bufio.Reset(nil)` and that causes a panic.
fyi @tiborvass 
> winlayers: discard reader on apply errors

- solver/jobs.go
- solver/llbsolver/bridge.go
- solver/llbsolver/solver.go
Show in output of build when image config is resolved.
Would be nice to connect this with the source operation in Dockerfile output somehow but no good ideas atm.
> llbsolver: show status of resolving image config

- README.md
- client/client_test.go
- cmd/buildctl/build_test.go
- cmd/buildkitd/main_containerd_worker.go
- examples/buildkit0/buildkit.go
- examples/buildkit1/buildkit.go
- examples/buildkit2/buildkit.go
- examples/buildkit3/buildkit.go
- examples/gobuild/main.go
- frontend/dockerfile/dockerfile_test.go
- hack/dockerfiles/test.Dockerfile
- util/testutil/integration/containerd.go
- vendor.conf
- vendor/github.com/containerd/containerd/archive/tar_windows.go
- vendor/github.com/containerd/containerd/cio/io_windows.go
- vendor/github.com/containerd/containerd/client.go
- vendor/github.com/containerd/containerd/client_opts.go
- vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
- vendor/github.com/containerd/containerd/vendor.conf
> update containerd (binary: v1.1.3, library: Aug 23, 2018)

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: never use entrypoint for run commands

- client/solve.go
Reset uid of session files same way for buildctl as moby does it.
> client: reset user ID for synced dirs

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
> dockerfile: allow overriding copy image

- frontend/dockerfile/dockerfile2llb/convert.go
> dockerfile: update copy helper to v0.1.4

- frontend/dockerfile/dockerfile2llb/convert_secrets.go
- frontend/dockerfile/instructions/commands_runmount.go
> dockerfile: add required option for secrets

- client/llb/state.go
- frontend/dockerfile/dockerfile2llb/convert.go
Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>
> function name fixed SetMarhalDefaults -> SetMarshalDefaults

- solver/jobs.go
> solver: fix data race

- vendor.conf
- vendor/github.com/tonistiigi/fsutil/walker_unix.go
> vendor: update fsutil to 7e391b0

- frontend/dockerfile/dockerfile2llb/convert.go
> dockerfile: set default PATH for arg replacement

- frontend/dockerfile/dockerfile2llb/convert.go
- util/imageutil/config.go
- util/imageutil/schema1.go
> imageutil: fix getting schema1 configs

- client/llb/state.go
- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/gateway/client/client.go
- frontend/gateway/forwarder/forward.go
- frontend/gateway/grpcclient/client.go
Allow llb marshal to access the supported LLB caps.
> gateway: allow access to apicaps

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: add test for chown destination

- executor/containerdexecutor/executor.go
- executor/runcexecutor/executor.go
- solver/jobs.go
> runcexecutor: make sure to return canceled

- solver/edge.go
> solver: fix early resolution of cache-fast deps

- solver/scheduler_test.go
> solver: add TestSlowCacheAvoidLoadOnCache test

- client/llb/exec.go
- frontend/gateway/grpcclient/client.go
- solver/pb/caps.go
> define CapMountSSH

- util/flightcontrol/flightcontrol.go
> flightcontrol: add exponential backoff to Group.Do

- executor/containerdexecutor/executor.go
- executor/runcexecutor/executor.go
> executor: clean up static config files

- frontend/dockerfile/instructions/commands_runmount.go
> dockerfile: fix ssh required option

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
- util/contentutil/refs.go
- util/testutil/integration/run.go
Built on https://travis-ci.org/tonistiigi/copy/builds/434472083#L1932
Minimal actual meaningful changes. mostly just build script update: https://github.com/tonistiigi/copy/compare/v0.1.5..v0.1.7
> dockerfile: update default copy image

- .gitignore
- .travis.yml
- cmd/buildctl/main.go
- cmd/buildkitd/main.go
- hack/dockerfiles/test.Dockerfile
- hack/dockerfiles/test.buildkit.Dockerfile
- hack/release
- hack/release-tar
depends on #666
test release running in https://travis-ci.org/moby/buildkit/builds/439928849
> hack: add release script

- vendor.conf
- vendor/github.com/tonistiigi/fsutil/walker.go
https://github.com/tonistiigi/fsutil/compare/f567071bed2416e4d87d260d3162722651182317...2862f6bc5ac9b97124e552a5c108230b38a1b0ca
> vendor: update fsutil to 2862f6bc

- frontend/dockerfile/dockerfile_test.go
> dockerfile: add test for empty copy directory

- .travis.yml
- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
- frontend/dockerfile/cmd/dockerfile-frontend/hack/detect
- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
- frontend/dockerfile/cmd/dockerfile-frontend/main.go
- frontend/dockerfile/cmd/dockerfile-frontend/version.go
> dockerfile: setup master release deployment

- frontend/dockerfile/dockerfile2llb/convert.go
> dockerfile: disable network for copy

- .travis.yml
- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
- frontend/dockerfile/cmd/dockerfile-frontend/hack/check-daily-outdated
- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
Add daily feature release deployments for dockerfile frontend based on #528 . Usually, these would only be used for very new things so we can probably turn this off for mounts soon.
> dockerfile: add daily feature releases

- hack/dockerfiles/test.Dockerfile
- hack/dockerfiles/test.buildkit.Dockerfile
> unfork newuidmap/newgidmap

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
> contenthash: clean readlink value

- frontend/dockerfile/docs/experimental.md
> dockerfile: document more mount options

- frontend/dockerfile/dockerfile2llb/convert.go
> dockerfile: avoid urls in context filter

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: allow symlinks on reading Dockerfile

- cmd/buildctl/build.go
> buildctl: fix frontends ignore-cache setting

- frontend/dockerfile/dockerfile2llb/convert.go
- solver/internal/pipe/pipe.go
> dockerfile2llb/pipe: remove the useless assignment

- source/git/gitsource.go
- worker/base/worker.go
> worker/base: allow running without `git` installed

- README.md
- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
- hack/dockerfiles/generated-files.buildkit.Dockerfile
- hack/dockerfiles/lint.buildkit.Dockerfile
- hack/dockerfiles/test.buildkit.Dockerfile
> update dockerfile repo location

- docs/experimental-syntaxes.md
@tonistiigi @sudo-bmitch (or @bmitchboxboat ? 🤔 😂 ) @cpuguy83 🤗
> docs: make experimental frontend features better discoverable

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- README.md
fixes https://github.com/moby/buildkit/issues/753
> Add CONTRIBUTING, CODE_OF_CONDUCT

- .mailmap
- AUTHORS
- MAINTAINERS
- hack/generate-authors
fixes https://github.com/moby/buildkit/issues/45
> Add MAINTAINERS, AUTHORS files

- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
- frontend/gateway/gateway.go
> gateway: allow frontends without network

- cmd/buildkitd/config/config.go
- cmd/buildkitd/config/config_test.go
- cmd/buildkitd/config/gcpolicy.go
- cmd/buildkitd/config/gcpolicy_unix.go
- cmd/buildkitd/config/gcpolicy_windows.go
- cmd/buildkitd/main.go
- cmd/buildkitd/main_containerd_worker.go
- cmd/buildkitd/main_oci_worker.go
> Allow quick config of GC

- .travis.yml
- hack/dockerfiles/test.buildkit.Dockerfile
> travis: include win/darwin binaries in cross

- cmd/buildctl/build.go
> fix `if err != nil { return nil }`

- source/git/gitsource.go
- source/git/gitsource_unix.go
> git: avoid leaking lock files on cancellation

- solver/jobs.go
> solver: deadlock fix

- cmd/buildctl/build.go
> buildctl: detect empty stdin with empty frontend

- solver/llbsolver/vertex.go
Provide better error handling on invalid definition.
> llbsolver: validate digest on load

- client/client_test.go
> test: make sure `--export-cache type=inline` is not needed for import

- cmd/buildkitd/main.go
- cmd/buildkitd/main_containerd_worker.go
- cmd/buildkitd/main_oci_worker.go
- control/control.go
- solver/llbsolver/bridge.go
- solver/llbsolver/ops/source.go
- solver/llbsolver/solver.go
- source/containerimage/pull.go
- source/git/gitsource.go
- source/git/gitsource_test.go
- source/http/httpsource.go
- source/http/httpsource_test.go
- source/local/local.go
- source/manager.go
- worker/base/worker.go
- worker/containerd/containerd.go
- worker/runc/runc.go
- worker/runc/runc_test.go
- worker/worker.go
> decouple SessionManager from Worker

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
- solver/llbsolver/result.go
Required for fileop. Separated out from #809
> contenthash: add wildcard and nofollow support

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
> contenthash: fix symlink parent reference

- cmd/buildkitd/main.go
> buildkitd: fix default platforms conf

- solver/edge.go
> solver: change early input resolve strategy

- hack/binaries
- hack/test
It's a really small change ...
remove useless spaces
> rm useless spaces

- client/client_test.go
- client/solve.go
- go.mod
- go.sum
- session/filesync/diffcopy.go
- session/filesync/filesync.go
- vendor/github.com/tonistiigi/fsutil/diskwriter.go
- vendor/github.com/tonistiigi/fsutil/stat_unix.go
- vendor/github.com/tonistiigi/fsutil/walker.go
- vendor/modules.txt
> vendor: update fsutil to 1bdbf123ad

- client/client_test.go
- exporter/oci/export.go
- util/dockerexporter/dockerexporter.go
carry #802
fixes #797
@hpandeycodeit @AkihiroSuda
> exporter: multiple names support in docker exporter

- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
- hack/binaries
- hack/images
- hack/test
- hack/update-generated-files
- hack/update-vendor
- util/binfmt_misc/Makefile
> Stop using the deprecated way for build

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
Noticed this while working on https://github.com/tonistiigi/fsutil/pull/62
When hardlinks are transferred with a changestream their checksums may become incompatible with the hashing that happens when a directory is walked. In the worst case, this could cause the hardlink to cause a wrong cache hit (although that is very unlikely). With the change, we switch all hardlinks directly to the checksum of the source.
> contenthash: fix hardlinks checksum on handlechange

- client/client_test.go
- exporter/containerimage/export.go
- util/push/push.go
`name=foo/bar,push=true,push-by-digest=true` can now be used to push image by digest only and not update the latest tag.
@dmcgowan 
> exporter: allow push by digest in image exporter

- client/client.go
required for https://github.com/tonistiigi/buildx/pull/10
> client: allow setting custom dialer

- client/build_test.go
- client/client_test.go
- cmd/buildctl/buildctl_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/frontend_test.go
- util/testutil/integration/containerd.go
- util/testutil/integration/oci.go
- util/testutil/integration/registry.go
- util/testutil/integration/run.go
Update integration package so it could be used for more usecases and extended with external sandbox implementations.
> integration: generalize pkg

- cmd/buildkitd/main.go
- cmd/buildkitd/main_containerd_worker.go
- cmd/buildkitd/main_oci_worker.go
Handle errors on loading default config instead of ignoring the values.
> buildkitd: error on config load error

- solver/llbsolver/ops/exec.go
- solver/llbsolver/ops/exec_test.go
backport of https://github.com/moby/buildkit/pull/858
@thaJeztah 
(cherry picked from commit 6d859fc9b08904d57a2305902fcbaef773b793fa)
> [docker-18.09] llbsolver: fix selectors dedupe

- cmd/buildctl/build.go
- util/progress/progressui/display.go
- util/progress/progressui/printer.go
Improve plain progress readability, example: https://gist.github.com/tonistiigi/8a5af70c4e54bfb8b894d40b3d86321c
fixes #863
> better plain mode progress

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_test.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: handle args with unset values

- frontend/dockerfile/dockerfile_mount_test.go
- frontend/dockerfile/instructions/commands_runmount.go
> dockerfile: make tmpfs mount readwrite by default

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
- cache/manager.go
- cache/manager_test.go
- cache/refs.go
- cmd/buildkitd/config/config.go
- cmd/buildkitd/main_oci_worker.go
- cmd/buildkitd/util.go
- executor/containerdexecutor/executor.go
- executor/oci/spec_unix.go
- executor/runcexecutor/executor.go
- exporter/local/export.go
- exporter/tar/export.go
- session/filesync/diffcopy.go
- session/filesync/filesync.go
- snapshot/containerd/snapshotter.go
- snapshot/snapshotter.go
- solver/llbsolver/file/backend.go
- solver/llbsolver/ops/exec.go
- source/git/gitsource.go
- source/git/gitsource_test.go
- source/http/httpsource.go
- source/http/httpsource_test.go
- source/local/local.go
- vendor/modules.txt
- worker/base/worker.go
- worker/containerd/containerd.go
- worker/runc/runc.go
- worker/runc/runc_test.go
add support for mapping files used by buildkit with user namespace for extended security
> userns remapping support base

- util/binfmt_misc/check.go
- util/binfmt_misc/check_unix.go
- util/binfmt_misc/check_windows.go
> binfmt_misc: fix building on windows

- cmd/buildctl/build.go
The change will make it more explicit on how to use the options.
> Minor improvement on the CLI usage

- frontend/dockerfile/docs/experimental.md
- suppress the irrelated warning message
- export `stderr` besides `stdout` to the output file
> doc: make sure the intended message is redirected to file successfully

- .mailmap
- AUTHORS
> Update AUTHORS and mailmap

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile_test.go
This allows dockerfile to be outside of the build context when building from a remote context. We check if the key for dockerfile local was sent with a request and if it was we use the dockerfile from the local instead of the one in the remote.
This enables implementing https://github.com/moby/moby/issues/38254
@AkihiroSuda @thaJeztah 
> dockerfile: allow external dockerfile on remote context

- client/solve.go
Refactors client so it can use a preintialized session and share session for multiple builds. The support is somewhat limited atm as client side exporters using session can only be invoked once but should work at least for building the same Dockerfile with different targets.
buildx branch that uses this: https://github.com/tonistiigi/buildx/compare/bake...bake-shared-session
> client: add shared session possibility

- solver/llbsolver/bridge.go
fix https://github.com/moby/moby/issues/39019
> llbsolver: make remote cache errors not fatal

- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
- hack/images
> hack: fix csv values

- client/llb/exec.go
> llb: fix security mode cap check

- session/auth/authprovider/authprovider.go
Prevents https://github.com/docker/cli/issues/1862
> session: add lock to fix hang

- cmd/buildkitd/main.go
> buildkitd: create buildkitd.lock under root

- cmd/buildkitd/main.go
- go.mod
- go.sum
- vendor/github.com/coreos/go-systemd/LICENSE
- vendor/github.com/coreos/go-systemd/NOTICE
- vendor/github.com/coreos/go-systemd/daemon/sdnotify.go
- vendor/github.com/coreos/go-systemd/daemon/watchdog.go
- vendor/modules.txt
> buildkitd: support sd_notify

- cmd/buildctl/build.go
- session/auth/authprovider/authprovider.go
> authprovider: set stderr

- executor/containerdexecutor/executor.go
- executor/runcexecutor/executor.go
- frontend/dockerfile/dockerfile_test.go
> executor: make sure cwd created with correct user

- client/connhelper/dockercontainer/dockercontainer.go
- client/connhelper/dockercontainer/dockercontainer_test.go
> connhelper/dockercontainer: support Docker context

- docs/buildkitd.toml.md
> Add default configuration as a reference

- cache/manager.go
- cache/metadata/metadata.go
- cache/refs.go
- cache/remotecache/import.go
- cache/remotecache/v1/cachestorage.go
- cache/remotecache/v1/parse.go
- cache/util/fsutil.go
- frontend/gateway/grpcclient/client.go
- session/auth/auth.go
- session/content/caller.go
- session/filesync/diffcopy.go
- session/filesync/filesync.go
- session/secrets/secrets.go
- session/sshforward/copy.go
- session/sshforward/ssh.go
- session/upload/upload.go
- solver/edge.go
- solver/llbsolver/bridge.go
- solver/llbsolver/ops/exec.go
Make sure errors on critical paths are with tracing data so that error reports are more useful.
> add more error tracing

- client/client_test.go
- client/llb/exec.go
- client/llb/meta.go
- client/llb/state.go
- client/llb/state_test.go
- frontend/dockerfile/dockerfile_test.go
> llb: fix excessive formatting

- README.md
I've been working on an OSS tool that uses buildkit to work with monorepos effectively.
Just a small PR to add it to the list, thanks!
> Add sanic to list of projects using buildkit

- util/pull/resolver.go
> util: patch atomic 64bit alignment

- frontend/dockerfile/builder/build.go
> dockerfile: set optional cache ID namespace with build-arg

- frontend/dockerfile/dockerfile_secrets_test.go
- frontend/dockerfile/instructions/commands_runmount.go
> dockerfile: allow required flag to take value

- util/flightcontrol/flightcontrol.go
closes #990
While I can't see how this error could appear unless one goroutine does not get scheduled for many seconds while another one constantly does even if it calls unsched each time, this patch should make it so that the second goroutine always waits for other to finish before retrying, limiting the possibility of timeout even more.
@AkihiroSuda @tiborvass 
> flightcontrol: mitigate retry timeout error

- cache/remotecache/v1/utils.go
> remotecache: fix records sorting

- cache/remotecache/import.go
> remotecache: fix concurrent write

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
> contenthash: fix symlinks with unscanned parents

- .travis.yml
- client/client_test.go
- hack/binaries
- hack/build_ci_first_pass
- hack/cross
- hack/dockerfiles/test.buildkit.Dockerfile
- hack/images
- hack/login_ci_cache
- hack/test
- hack/util
- util/testutil/integration/run.go
> Use buildkit cache and parallelization in CI

- session/sshforward/copy.go
- session/sshforward/ssh.go
- session/sshforward/sshprovider/agentprovider.go
> session: release forwarded ssh socket connection per connection

- .travis.yml
> travis: print main buildkit logs on job failure

- hack/dockerfiles/generated-files.buildkit.Dockerfile
- hack/dockerfiles/lint.buildkit.Dockerfile
- hack/dockerfiles/vendor.buildkit.Dockerfile
Main dockerfile was already updated before. Change others as well for consistency.
> hack: update to dockerfile-1.1

- client/client_test.go
- frontend/dockerfile/dockerfile_runnetwork_test.go
> dockerfile: skip cni tests on rootless

- README.md
Rio does in fact use buildkit.
> Update Rio status

- hack/util
> hack: fix unbound ci vars

- go.mod
- go.sum
- hack/dockerfiles/test.Dockerfile
- hack/dockerfiles/test.buildkit.Dockerfile
- util/leaseutil/manager.go
- vendor/github.com/containerd/containerd/.appveyor.yml
- vendor/github.com/containerd/containerd/RELEASES.md
- vendor/github.com/containerd/containerd/images/archive/importer.go
- vendor/github.com/containerd/containerd/metadata/containers.go
- vendor/github.com/containerd/containerd/metadata/content.go
- vendor/github.com/containerd/containerd/metadata/db.go
- vendor/github.com/containerd/containerd/metadata/images.go
- vendor/github.com/containerd/containerd/metadata/leases.go
- vendor/github.com/containerd/containerd/metadata/snapshot.go
- vendor/github.com/containerd/containerd/namespaces/context.go
- vendor/github.com/containerd/containerd/oci/spec.go
- vendor/github.com/containerd/containerd/process.go
- vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
- vendor/github.com/containerd/containerd/remotes/docker/pusher.go
- vendor/github.com/containerd/containerd/remotes/docker/resolver.go
- vendor/github.com/containerd/containerd/vendor.conf
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
- worker/runc/runc.go
Uses cleaned up lease manager interface in metadata package
> Update to containerd 1.3.0

- session/sshforward/ssh.go
- solver/llbsolver/ops/exec.go
> exec: fix mount options on userns remapping

- README.md
Fix #1234
This has been already implemented.
> README.md: fix description about local cache

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: fix copy symlinks on copied dir

- exporter/containerimage/writer.go
These were erroneously removed in https://github.com/moby/buildkit/pull/1176
> exporter: keep blob refs on images

- solver/types.go
I wanted to improve the godocs of the solver types based on:
- https://github.com/moby/buildkit/blob/master/docs/solver.md
- https://dockercommunity.slack.com/archives/C7S7A40MP/p1572918118341900
> Improve solver type godocs

- cache/blobs/blobs.go
This adds an alternative differ method that can be used instead of regular containerd `Compare`. We will use this in docker where storage/diff is managed by moby layerstore.
> blobs: allow alternative compare-with-parent diff

- .github/CONTRIBUTING.md
> CONTRIBUTING.md: fix broken link

- util/push/push.go
For new built layers, it can be pushed into remote registry. However, it
might not be pulled as base layer. Before this commit, the dist repo
source label for mountFrom call only is updated at pull stage. Without
mountFrom, it will take long time to push existing layers which can be
mountFrom. Based on this case, we should update dist repo source after
pushing layer successfully.
> push: update dist repo source for mountFrom

- cmd/buildctl/debug/dumpmetadata.go
> cmd/buildctl: dump metadata from metadata_v2.db

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/diff.go
- vendor/github.com/tonistiigi/fsutil/diff_containerd.go
- vendor/github.com/tonistiigi/fsutil/diskwriter.go
- vendor/github.com/tonistiigi/fsutil/go.mod
- vendor/github.com/tonistiigi/fsutil/go.sum
- vendor/github.com/tonistiigi/fsutil/receive.go
- vendor/github.com/tonistiigi/fsutil/types/stat.go
- vendor/modules.txt
full diff: https://github.com/tonistiigi/fsutil/compare/3d2716dd0a4d...0f039a052ca1
- tonistiigi/fsutil#68 fix gocrypto commit
- tonistiigi/fsutil#69 receive: use filter on receive diff
- prevents incremental transfers with userns because the metadata
on disk is always different than the one being transferred.
> vendor: update fsutil 0f039a052ca1

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: clear onbuild rules after triggering

- cache/manager.go
> fix: Fix typo

- Dockerfile
@tonistiigi : Please update Docker Hub `tonistiigi` images?
> Dockerfile: update dependencies (including runc rc10)

- go.mod
- go.sum
- solver/llbsolver/file/backend.go
- solver/llbsolver/file/unpack.go
- solver/llbsolver/file/user_linux.go
- vendor/github.com/tonistiigi/fsutil/.travis.yml
- vendor/github.com/tonistiigi/fsutil/copy/copy.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_linux.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_unix.go
- vendor/github.com/tonistiigi/fsutil/copy/mkdir.go
- vendor/github.com/tonistiigi/fsutil/copy/stat_bsd.go
- vendor/github.com/tonistiigi/fsutil/copy/stat_sysv.go
- vendor/github.com/tonistiigi/fsutil/go.mod
- vendor/github.com/tonistiigi/fsutil/go.sum
- vendor/modules.txt
fix for https://github.com/moby/moby/issues/40335
~depends on https://github.com/tonistiigi/fsutil/pull/70~
> fileop: keep correct user for parent dir on userns

- go.mod
- go.sum
- hack/dockerfiles/test.buildkit.Dockerfile
- solver/llbsolver/file/backend.go
- solver/llbsolver/file/unpack.go
- solver/llbsolver/file/user_linux.go
- vendor/github.com/tonistiigi/fsutil/.travis.yml
- vendor/github.com/tonistiigi/fsutil/copy/copy.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_linux.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_unix.go
- vendor/github.com/tonistiigi/fsutil/copy/mkdir.go
- vendor/github.com/tonistiigi/fsutil/copy/stat_bsd.go
- vendor/github.com/tonistiigi/fsutil/copy/stat_sysv.go
- vendor/github.com/tonistiigi/fsutil/go.mod
- vendor/github.com/tonistiigi/fsutil/go.sum
- vendor/modules.txt
https://github.com/moby/buildkit/pull/1344
https://github.com/moby/buildkit/pull/1342
> [v0.6] cherry picks

- cmd/buildkitd/main_windows.go
- hack/cross
- solver/llbsolver/file/user_nolinux.go
> file: fix compilation on windows

- cmd/buildkitd/main_windows.go
- hack/cross
- solver/llbsolver/file/user_nolinux.go
https://github.com/moby/moby/pull/40440#issuecomment-580568387
> [v0.6] file: fix compilation on windows

- MAINTAINERS
@hinshun has been a very valuable contributor to the project, especially for the solver component.
Thanks and welcome @hinshun :+1:
> MAINTAINERS: add @hinshun

- solver/llbsolver/ops/exec.go
> [v0.6] ops: fix deadlock on releasing shared mounts

- cmd/buildkitd/main.go
- control/control.go
- solver/llbsolver/solver.go
- solver/llbsolver/vertex.go
- util/binfmt_misc/detect.go
- worker/base/worker.go
- worker/worker.go
- worker/workercontroller.go
> update supported platforms without restart

- README.md
Fix #1294
Signed-off-by: Lu Jingxiao <lujingxiao@huawei.com>
> README.md: update description of inline cache use for output

- Dockerfile
For avoiding qemu-user overhead
> Dockerfile: cross-compile fuse-overlayfs and idmap

- solver/cachemanager.go
hoping this will fix
moby/buildkit#1313
moby/moby#40624
docker/buildx#240
Can't be 100% sure as still don't have a way to repro but looks like the only way this would make sense.
@bpaquet @Antiarchitect @teohhanhui If any of you has a way to test out this patch, let us know in comments about the results.
> solver: avoid looping over same keys in loadwithparents

- frontend/dockerfile/builder/build.go
This effectively passes through FrontendInputs (added in #1361) from `dockerfile.v0`to `gateway.v0` (when forwarding requests that contain a custom `syntax=`)
/cc @hinshun
> dockerfile: forward FrontendInputs to the gateway

- client/client_test.go
- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/tarwriter.go
- vendor/modules.txt
Signed-off-by: Xiaofan Zhang <xiaofan.zhang@clinc.com>
> vendor: update fsutil to c2c7d7b0e144 and symlink test

- solver/cachemanager.go
backport of https://github.com/moby/buildkit/pull/1413
to address:
moby/buildkit#1313
moby/moby#40624
docker/buildx#240
> [docker-19.03 backport] solver: avoid looping over same keys in loadwithparents

- client/llb/resolver.go
- client/llb/resolver_test.go
- client/llb/source.go
> llb: update image meta resolver to async callback

- client/llb/definition.go
When leveraging #1428 to resolve image configs asynchronously, `st.Marshal(ctx)` blocks until all configs for that `llb.State` has been resolved. However, when marshaling multiple `llb.State` that share a `DefinitionOp` in the graph, it encounters a concurrent map write panic.
> Protect defop map when marshalling concurrently

- frontend/dockerfile/parser/json_test.go
- frontend/dockerfile/parser/line_parsers.go
- frontend/dockerfile/parser/line_parsers_test.go
- frontend/dockerfile/parser/parser.go
- frontend/dockerfile/parser/parser_test.go
- frontend/dockerfile/parser/split_command.go
- frontend/dockerfile/parser/testfiles/escape-nonewline/Dockerfile
- frontend/dockerfile/parser/testfiles/escape-with-syntax/Dockerfile
- frontend/dockerfile/parser/testfiles/escape-with-syntax/result
> dockerfile: fix parsing multiple directives

- client/client_test.go
- frontend/dockerfile/builder/build.go
- go.mod
- go.sum
- source/git/gitsource.go
- util/entitlements/entitlements.go
- util/resolver/resolver.go
- vendor/github.com/tonistiigi/fsutil/tarwriter.go
- vendor/modules.txt
https://github.com/moby/buildkit/pulls?q=is%3Apr+label%3Aneeds-cherry-pick%2Fv0.7+is%3Aclosed
> [v0.7] cherry-picks for v0.7.1

- hack/test
> hack: unbreak testing

- cmd/buildctl/build.go
- cmd/buildctl/main.go
- solver/errdefs/source.go
> buildctl: cleaner typed error printing

- session/filesync/filesync.go
additional fix for https://github.com/docker/buildx/pull/281
> filesync: avoid ignoring close error

- session/filesync/filesync.go
- solver/llbsolver/file/backend.go
(cherry picked from commit 625f6ecc8273a5a1bedfa667c44f89e383b5bd05)
> [docker 19.03] file: fix double-remap of old uid value

- frontend/gateway/gateway.go
- frontend/gateway/pb/caps.go
> [docker-19.03] gateway: fix metadata getting lost on subsolve

- util/progress/progressui/display.go
> progressui: fix panic on terminals with zero height

- frontend/gateway/gateway.go
- frontend/gateway/pb/caps.go
- session/filesync/filesync.go
- solver/llbsolver/file/backend.go
https://github.com/moby/buildkit/pulls?q=is%3Apr+label%3Aneeds-cherry-pick%2Fv0.7+is%3Aclosed
> [v0.7] cherry-picks

- .travis.yml
> travis: update base image

- .travis.yml
- Dockerfile
- hack/images
Fix #1378
Please see git commit message for the details
> Dockerfile: ditch ROOTLESS_BASE_MODE=external

- .travis.yml
- Dockerfile
- hack/images
> [v0.7] Dockerfile: ditch ROOTLESS_BASE_MODE=external

- .travis.yml
> travis: avoid cleaning up container

- client/client_test.go
- solver/exporter.go
Backport of https://github.com/moby/buildkit/pull/1382 for the docker-19.03 / v0.6.x branch
- fixes https://github.com/moby/buildkit/issues/1336 --export-cache option crashes buildkitd on custom frontend
- fixes https://github.com/moby/buildkit/issues/1313 Dockerd / buildkit in a infinite loop and burning cpu
- fixes / addresses https://github.com/moby/moby/issues/41044 19.03.9 goroutine stack exceeds 1000000000-byte limit
- fixes / addresses https://github.com/moby/moby/issues/40993 Multistage docker build fails with unexpected EOF
> [v0.6 backport] solver: avoid recursive loop on cache-export

- client/llb/exec_test.go
@tonistiigi follow up unit tests for #1521.  Let me know if this is not what you had in mind.
> add unit test for getmount output index

- executor/oci/mounts.go
fixes https://github.com/moby/buildkit/issues/1522
---
Signed-off-by: Chanhun Jeong <chanhun.jeong@navercorp.com>
Signed-off-by: Sunho Kim <z.sunno@navercorp.com>
> fix mount options for userns env

- cache/migrate_v2.go
Avoid calling snapshotter functions if mutable exists as mutable ID should be used instead then. Found this as one of the issues causing https://github.com/moby/moby/issues/41077
> cache: avoid snapshot migration on shallow refs

- solver/progress.go
When a vertex was running and progress stream ends it is marked as canceled. This is not correct if it was actually marked cached and might have been started by another parallel job. This PR records if vertex was marked as cached before and avoids setting the cancellation error then.
> solver: fix marking already cached vertex as cancelled

- frontend/frontend.go
- frontend/gateway/gateway.go
- solver/llbsolver/bridge.go
- worker/base/worker.go
- worker/runc/runc_test.go
- worker/tests/common.go
- worker/worker.go
This is another intermediate PR towards #749  as discussed on slack:
https://dockercommunity.slack.com/archives/C7S7A40MP/p1594851331488900
> add Run/Exec to FrontendLLBBridge interface

- cmd/buildkitd/main.go
- frontend/gateway/grpcclient/client.go
- util/testutil/integration/oci.go
- util/testutil/integration/run.go
- util/testutil/integration/sandbox.go
- util/testutil/integration/util.go
Fixes for releasing of resources and better logs on errors. Another fix coming in https://github.com/tonistiigi/fsutil/pull/83
> integration: tests flakiness fixes

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/.gitignore
- vendor/github.com/tonistiigi/fsutil/chtimes_nolinux.go
- vendor/github.com/tonistiigi/fsutil/diff.go
- vendor/github.com/tonistiigi/fsutil/diskwriter.go
- vendor/github.com/tonistiigi/fsutil/diskwriter_unix.go
- vendor/github.com/tonistiigi/fsutil/followlinks.go
- vendor/github.com/tonistiigi/fsutil/fs.go
- vendor/github.com/tonistiigi/fsutil/hardlinks.go
- vendor/github.com/tonistiigi/fsutil/send.go
- vendor/github.com/tonistiigi/fsutil/stat.go
- vendor/github.com/tonistiigi/fsutil/tarwriter.go
- vendor/github.com/tonistiigi/fsutil/validator.go
- vendor/github.com/tonistiigi/fsutil/walker.go
- vendor/modules.txt
full diff: https://github.com/tonistiigi/fsutil/compare/ae3a8d753069...8f851f9d2045
notable changes:
- walker: fix notadir error
- improving error returns
- more typed errors
- remove extra verbosity (eg. PathError already contains action and path)
- ensure stack traces are added to errors
> vendor: update tonistiigi/fsutil v0.0.0-20200720184806-8f851f9d2045

- util/testutil/integration/util.go
Writing to a buffered writer is not safe concurrently.
This showed up as a panic in #1581 ci. FYI @alexcb
Regression from #1579
> integration: lock buffer for concurrent writes

- examples/buildctl-daemonless/buildctl-daemonless.sh
> [v0.7] buildctl-daemonless.sh cherry-picks

- Dockerfile
> [v0.7] Dockerfile cherry-picks

- .travis.yml
- Makefile
- hack/binaries
- hack/cross
- hack/dockerfiles/shfmt.Dockerfile
- hack/generate-authors
- hack/images
- hack/lint
- hack/login_ci_cache
- hack/release-tar
- hack/shfmt
- hack/test
- hack/update-generated-files
- hack/update-vendor
- hack/util
- hack/validate-generated-files
- hack/validate-shfmt
- hack/validate-vendor
> hack: add shfmt

- util/push/push.go
- util/resolver/resolver.go
fixes #1586
fixes https://github.com/moby/moby/issues/41059#issuecomment-639697242
> push: reenable setting insecure exporter opt

- util/resolver/resolver.go
> resolver: enable tracing on default transport

- go.mod
- go.sum
- vendor/github.com/opentracing-contrib/go-stdlib/LICENSE
- vendor/github.com/opentracing-contrib/go-stdlib/nethttp/client.go
- vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go
- vendor/github.com/opentracing-contrib/go-stdlib/nethttp/status-code-tracker.go
- vendor/github.com/opentracing/opentracing-go/.travis.yml
- vendor/github.com/opentracing/opentracing-go/CHANGELOG.md
- vendor/github.com/opentracing/opentracing-go/ext.go
- vendor/github.com/opentracing/opentracing-go/ext/field.go
- vendor/github.com/opentracing/opentracing-go/ext/tags.go
- vendor/github.com/opentracing/opentracing-go/go.mod
- vendor/github.com/opentracing/opentracing-go/go.sum
- vendor/github.com/opentracing/opentracing-go/gocontext.go
- vendor/github.com/opentracing/opentracing-go/log/field.go
- vendor/github.com/opentracing/opentracing-go/log/util.go
- vendor/github.com/opentracing/opentracing-go/noop.go
- vendor/modules.txt
Saw that go-stdlib now had tagged releases, and opentracing-go did a minor release, so updated that as well
> vendor: update opentracing-go v1.2.0, go-stdlib v1.0.0

- client/llb/definition.go
- client/llb/definition_test.go
[llb.State.Marshal uses a vertexCache map (keyed by the llb.Vertex interface
value) to memoize which vertexes it has already visited while marshalling.](https://github.com/moby/buildkit/blob/279d686fec8dc496150c18daed1bd6c8e74a135b/client/llb/state.go#L174-L183)
However, before this change, llb.DefinitionOp was constructing new pointers for
each value in the return slice of Inputs(), which meant that each input had a
different key in the vertexCache (due to being different pointer values). This
meant no memoization actually occured. I noticed this while using
llb.DefinitionOp with a fairly large graph when my program crashed after using
more than 16GB of RSS during a call to llb.State.Marshal.
The fix here avoids changing vertexCache as that would impact many other
vertex implementations. …
> llb: Cache DefinitionOp inputs to support memoization during Marshal

- session/secrets/secretsprovider/store.go
The `doesEnvExist()` utility was copied from the classic builder, and was developed when `os.LookupEnv()` did not yet exist.
Now that it's available, replace our custom implementation in favor of Golang's function.
> secretsprovider.NewStore() simplify env handling

- frontend/dockerfile/builder/build.go
Originally from https://github.com/moby/moby/pull/41331
Following
>I think this might be better in buildkit repo dockerfile implementation where the regular `#syntax` redirect is as well.
>_Originally posted by @tonistiigi in https://github.com/moby/moby/pull/41331#issuecomment-671097962_
> build-arg add support BUILDKIT_SYNTAX

- go.mod
- go.sum
- util/resolver/authorizer.go
- vendor/github.com/containerd/containerd/README.md
- vendor/github.com/containerd/containerd/remotes/docker/auth/fetch.go
- vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
- vendor/github.com/containerd/containerd/remotes/docker/pusher.go
- vendor/github.com/containerd/containerd/remotes/errors/errors.go
- vendor/github.com/containerd/containerd/snapshots/native/native.go
- vendor/github.com/containerd/containerd/vendor.conf
- vendor/modules.txt
Primary intention of this update is to aid debugging registry errors (see https://github.com/docker/buildx/issues/300).
xref https://github.com/containerd/containerd/pull/4523
> vendor: update containerd to d4e7820

- frontend/gateway/grpcclient/client.go
> client: allow build callback to return nil result

- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
deployment broke with #1675 
https://travis-ci.org/github/moby/buildkit/jobs/733546242#L271
> hack: fix release script

- frontend/dockerfile/instructions/commands.go
- frontend/dockerfile/instructions/parse.go
- frontend/dockerfile/instructions/parse_test.go
- frontend/dockerfile/parser/line_parsers.go
- frontend/dockerfile/parser/parser.go
If comment is associated with a named stage/arg parse it together with the instruction.
~depends on #1692~
> dockerfile: parse comments associated with args and stages

- cache/remotecache/v1/chains.go
fixes #1509
Adds validation to remove broken links caused by loops in cache graph. Don't really like this solution at all and I think some cache may be still missed on loops but better fix requires better tooling to analyze the cache graphs. This is good enough to remove the error.
Overall, a loop in the cache graph is a clear indication of a user error in the build request/dockerfile and results in an inefficient build. But we shouldn't just break if this happens.
@bgaillard @cpuguy83 @vladaionescu 
> remotecache: validate out broken links from loops

- cmd/buildkitd/debug.go
Allow gc to be triggered through the debug api.
> debug: enable gc triggers

- solver/jobs.go
> solver: make sure job id cleared after build

- docs/stargz-estargz.md
Fixes: #1753
This commit adds a documentation about the stargz/eStargz-based lazy pull support.
> Add documentation about stargz/eStargz-based lazy pull functionality

- go.mod
- go.sum
- vendor/github.com/google/shlex/go.mod
- vendor/github.com/google/shlex/shlex.go
- vendor/modules.txt
full diff: https://github.com/google/shlex/compare/6f45313302b9c56850fc17f99e40caebce98c716...e7afc7fbc51079733e9468cdfd1efcd7d196cd1d
- Remove unnecessary UnreadRune call
- Add go.mod
> vendor: github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510

- cache/manager.go
- cache/refs.go
> Fixes needed to vendor buildkit into moby

- cache/refs.go
- solver/edge.go
- solver/jobs.go
- solver/llbsolver/ops/build.go
- solver/llbsolver/ops/exec.go
- solver/llbsolver/ops/file.go
- solver/llbsolver/result.go
- solver/scheduler_test.go
- solver/types.go
> solver: add input preprocess capability

- util/sshutil/keyscan.go
> fix assumption that ssh port must be 2 digits

- Dockerfile
Defining an alias stage overrides the `--platform` hint.
> Dockerfile: define alpine version with build arg

- README.md
> Switch to travis-ci.com

- .golangci.yml
- .travis.yml
- .yamllint.yml
- examples/kubernetes/deployment+service.privileged.yaml
- examples/kubernetes/deployment+service.rootless.yaml
- examples/kubernetes/job.privileged.yaml
- examples/kubernetes/job.rootless.yaml
- examples/kubernetes/pod.privileged.yaml
- examples/kubernetes/pod.rootless.yaml
- examples/kubernetes/statefulset.privileged.yaml
- examples/kubernetes/statefulset.rootless.yaml
- hack/dockerfiles/lint.Dockerfile
> Add yamllint

- hack/test
> Fix cache for CI

- codecov.yml
> Disable Codecov comments

- worker/base/worker.go
When using cache mounts with `--no-cache` the cleanup process may skip deleting index reference because metadata struct is out of sync. This results in lookup errors printed to the logs.
> cache-mounts: avoid leaking old index on no-cache

- .github/workflows/build.yml
- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
- hack/util
Follow-up #1824 #1835
Push is [disabled](https://github.com/moby/buildkit/pull/1840/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R415) until we have migrated to GitHub Actions.
> Refactor frontend for GitHub Actions

- .github/workflows/build.yml
- .travis.yml
> Allow push with GitHub Actions

- .github/workflows/build.yml
> Fix GitHub Release event

- .github/workflows/build.yml
- Makefile
- hack/images
> Fix rootless tag

- .github/workflows/build.yml
- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
- hack/build_ci_first_pass
- hack/cross
- hack/images
- hack/release-tar
- hack/test
- hack/util
> Fix CI cache

- .github/workflows/build.yml
> Disable frontend build on schedule event

- hack/images
> Export to local dir for GHA

- Dockerfile
Protect against this image accidentally changing
> dockerfile: pin binfmt image

- solver/llbsolver/mounts/mount.go
> mounts: handle optional ssh mount

- solver/edge.go
- solver/scheduler.go
> solver: improve slow cache detection logging

- hack/images
> hack: fix tagging ga releases

- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
> dockerfile: fix escaping in release script

- codecov.yml
To avoid unexpected coverage changes. See https://docs.codecov.io/docs/commit-status
> Tweak codecov delta

- Dockerfile
- hack/dockerfiles/generated-files.Dockerfile
- hack/dockerfiles/lint.Dockerfile
- hack/dockerfiles/shfmt.Dockerfile
- hack/dockerfiles/vendor.Dockerfile
> update Dockerfiles to 1.2

- worker/runc/runc_test.go
> add debug for runcworker test

- docs/images-readme.md
- frontend/dockerfile/docs/syntax.md
> docs: Change buildkit 0.8.0 -> 0.8.1 and an instance of dockerfile 1.2.0 to 1.2

- frontend/dockerfile/docs/syntax.md
> dockerfile/docs: fix frontend image tags

- cache/blobs.go
CompareWithParent is not used in the current code.
> cache: remove unused CompareWithParent interface

- .github/workflows/buildx-image.yml
> Fix buildx-image workflow

- client/llb/source.go
- source/gitidentifier.go
- source/gitidentifier_test.go
- util/sshutil/transport_validation.go
- util/sshutil/transport_validation_test.go
- fix IsSSHTransport to also check for explicitly-defined ssh-based git repos
> Check for explicit ssh git URL

- util/progress/logs/logs.go
noticed on https://github.com/docker/setup-buildx-action/pull/50
Also increase defaults 2x
@crazy-max
> logs: fix clipping configuration

- util/resolver/authorizer.go
backport of https://github.com/moby/buildkit/pull/1957
fixes #1928
closes #1933
> [v0.8 backport] resolver: avoid error caching on token fetch

- util/resolver/resolver.go
This reverts commit 58dc579d5784e663a55a96d8277c3a2a8f45132f.
ref https://github.com/moby/buildkit/issues/1988#issuecomment-782508241
> Revert "resolver: fix tcp connections limit"

- .github/workflows/build.yml
- .github/workflows/validate.yml
> make sure ci runs on v0.8 branch

- Dockerfile
> Dockerfile: update runc to rc93

- Dockerfile
#1998 
(cherry picked from commit da323d7728a3948ca79af323f5833dce2b82c155)
> [0.8] Dockerfile: update runc to rc93

- frontend/dockerfile/docs/syntax.md
One has doubt his guess of the obvious is correct unless it is mentioned in documentation.
> Explain the cache identity

- util/push/push.go
> push: avoid overwriting tags on push

- cache/remotecache/v1/chains.go
- cache/remotecache/v1/utils.go
- frontend/dockerfile/dockerfile_test.go
- solver/edge.go
- solver/scheduler.go
fix #2002
@adriankostrubiak-tomtom
Exporting cache with loops might still have inefficiency issues but this should fix the fatal errors.
> remotecache: check loops on marshaling cache config

- cache/remotecache/v1/chains.go
Items may be reused by the cache resulting concurrent writes.
> remotecache: lock backlinks cache

- solver/jobs.go
adds error handler for https://github.com/moby/buildkit/issues/2041#issuecomment-814012772
> solver: check for input index existence

- codecov.yml
> Disable codecov patch check

- worker/workercontroller.go
Now the default worker is always printed first.
> buildctl debug workers: make the ordering deterministic

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
- client/client_test.go
- codecov.yml
- frontend/dockerfile/dockerfile_test.go
- solver/llbsolver/ops/exec.go
- util/contentutil/copy.go
- util/imageutil/config.go
- util/progress/logs/logs.go
- util/resolver/retryhandler/retry.go
> [v0.8] cherry-picks

- hack/dockerfiles/lint.Dockerfile
> lint: update golangci

- README.md
A new tool for building containers.
> Add rancher kim to tools using buildkit

- Dockerfile
fix docker/buildx#620
@tscholak
> Dockerfile: add openssh to images

- hack/dockerfiles/generated-files.Dockerfile
- hack/shell_backup
> hack: update proto generators for arm64

- hack/shell
Accidentally already committed this in as part of a review update in #2154 so at least move it to the correct name.
> add hack/shell helper for dev shell environment

- session/filesync/diffcopy.go
With opentelemetry interceptor the successful context transfer streams are left hanging if closesend is not called, even if stream finished cleanly with EOF.
Opened upstream issue for this https://github.com/open-telemetry/opentelemetry-go-contrib/issues/818
> filesync: ensure sendclose is always called

- session/auth/auth.go
- util/resolver/authorizer.go
> session: make sure all token request keep correct context

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
Fix #2114, noticed the fix was a simple one-liner while in the area for heredocs.
I've also added an integration test, so hopefully it shouldn't cause a regression later.
> Fix file modes with remote ADD commands

- Dockerfile
- go.mod
- go.sum
- vendor/github.com/golang/snappy/AUTHORS
- vendor/github.com/golang/snappy/CONTRIBUTORS
- vendor/github.com/golang/snappy/decode.go
- vendor/github.com/golang/snappy/encode_arm64.s
- vendor/modules.txt
> remove go fork for building windows/arm64

- client/build_test.go
- client/client_test.go
- cmd/buildctl/build_test.go
- frontend/dockerfile/dockerfile_heredoc_test.go
- frontend/dockerfile/dockerfile_mount_test.go
- frontend/dockerfile/dockerfile_runnetwork_test.go
- frontend/dockerfile/dockerfile_runsecurity_test.go
- frontend/dockerfile/dockerfile_secrets_test.go
- frontend/dockerfile/dockerfile_ssh_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/errors_test.go
- frontend/frontend_test.go
- solver/jobs_test.go
- util/testutil/integration/containerd.go
- util/testutil/integration/dockerd.go
- util/testutil/integration/oci.go
- util/testutil/integration/run.go
- util/testutil/integration/sandbox.go
> integration: add common context base to all integration tests

- Dockerfile
https://github.com/opencontainers/runc/releases/tag/v1.0.0
> update runc binary to v1.0.0 GA

- .github/workflows/build.yml
- Dockerfile
> enable riscv64 build

- Dockerfile
https://github.com/tonistiigi/binfmt/releases/tag/buildkit%2Fv6.0.0-15
> Update QEMU emulators

- session/auth/authprovider/authprovider.go
close #2211 
As the title says, I removed meaningless encode.
> Remove meaningless encode

- session/auth/authprovider/tokenseed.go
> authprovider: handle eaccess on storing token seeds

- .github/workflows/build.yml
Use our CI to test everything is fine with the RC
> github: update CI buildkit to v0.9.0-rc1

- exporter/containerimage/writer.go
This can be a significant amount of time that isn't currently accounted
for in traces.
Signed-off-by: Aaron Lehmann <alehmann@netflix.com>
> Add span for layer export

- client/client_test.go
- cmd/buildctl/build_test.go
- exporter/containerimage/export.go
- exporter/containerimage/exptypes/types.go
- exporter/containerimage/writer.go
- exporter/oci/export.go
> Exporter config digest typo

- examples/buildctl-daemonless/buildctl-daemonless.sh
> daemonless: wait for daemon to finish before exit

- .github/workflows/build.yml
> github: update CI buildkit to v0.9.0

- cmd/buildkitd/config/config.go
- docs/buildkitd.toml.md
> add docs for new config options

- MAINTAINERS
🥳 Welcome @ktock @crazy-max to maintainers! Thank you for the great work you've been doing in the repo.
Already agreed in Slack. Please verify e-mails etc. in the MAINTAINERS file.
> add ktock and crazy-max to maintainers

- docs/images-readme.md
> docs: update images-readme to v0.9

- Dockerfile
- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
- frontend/dockerfile/docs/syntax.md
- hack/dockerfiles/generated-files.Dockerfile
- hack/dockerfiles/lint.Dockerfile
- hack/dockerfiles/shfmt.Dockerfile
- hack/dockerfiles/vendor.Dockerfile
> Update Dockerfile references to use 1.3

- frontend/dockerfile/dockerfile_secrets_test.go
- frontend/dockerfile/instructions/commands_runmount.go
fix #2293
regression  from #2089 @omermizr
> dockerfile: fix parsing required key without value

- hack/shell
> hack: allow mounting in workdir in shell

- api/services/control/control.pb.go
- api/services/control/control.proto
- cache/metadata/metadata.go
- client/solve.go
- session/filesync/filesync.go
> Clean up old TODOs

- cache/remotecache/gha/gha.go
- go.mod
- go.sum
- solver/edge.go
- solver/jobs.go
- solver/scheduler.go
- util/contentutil/multiprovider.go
- vendor/github.com/dimchansky/utfbom/.gitignore
- vendor/github.com/dimchansky/utfbom/.travis.yml
- vendor/github.com/dimchansky/utfbom/LICENSE
- vendor/github.com/dimchansky/utfbom/README.md
- vendor/github.com/dimchansky/utfbom/go.mod
- vendor/github.com/dimchansky/utfbom/utfbom.go
- vendor/github.com/tonistiigi/go-actions-cache/LICENSE
- vendor/github.com/tonistiigi/go-actions-cache/cache.go
- vendor/github.com/tonistiigi/go-actions-cache/go.mod
- vendor/github.com/tonistiigi/go-actions-cache/go.sum
- vendor/github.com/tonistiigi/go-actions-cache/retry.go
- vendor/modules.txt
- worker/base/worker.go
Picks: 
- fixes for github actions cache #2387
- return an error instead of panicking when failing to get edge #2382
- don't cast Value when pipe is errored #2385
> [v0.9] cherry-picks

- cache/remotecache/registry/registry.go
- go.mod
- go.sum
- util/contentutil/refs.go
- util/imageutil/config.go
- util/push/push.go
- vendor/github.com/containerd/containerd/.mailmap
- vendor/github.com/containerd/containerd/images/image.go
- vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
- #2461
- #2469
- update containerd to v1.5.8
> [v0.9] cherry-pick and update containerd

- source/git/gitsource.go
There is still no guarantee that two fetches will produce same `.git` directory but this takes care of the obvious things like snapshot address as origin URL and timestamps in ref logs.
> git: make fetch with keep-git-dir more deterministic

- util/sshutil/keyscan.go
nothing interesting, just noticing these when I had the file open in my editor
> util/sshutil: minor linting / warning nits

- cache/blobs.go
- cache/manager.go
- cache/manager_test.go
This fixes an issue where merge refs were incorrectly setting their chain IDs to their last input's ID. This resulted in errors where GetByBlob thought the merge ref and the final input ref were equivalent.
Now, merge refs have their chain IDs computed by digesting each blob in the full chain.
While the first commit fixes this error condition from happening, I also included a separate commit to make this error condition non-fatal to the build as it technically doesn't need to be. The condition is instead just logged at Error level now.
> Fix merge blobchainid

- client/client_test.go
When vendored into moby, the local exporter uses a user map that results
in all files being given at most 755 permissions. This change updates
the test to use permissions less than or equal to that to make tests
equivalent whether running w/ dockerd worker or any other type.
Additionally, add assertions that exported images also have the expected
contents, which helps ensures consistency between images created by
dockerd and those created by vanilla buildkit.
This was tested by running the buildkit mergeop integration tests against dockerd built using this branch: https://github.com/sipsma/moby/commits/mobymerge
I also have run the tests in the diffop PR (which expands test coverage of mergeop further) using this change  against dockerd and …
> Update tests for consistency w/ dockerd.

- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
- hack/binaries
- hack/cross
- hack/images
- hack/release-tar
> hack: use local platform if none defined

- session/filesync/filesync.go
- source/local/local.go
- Local op already has a session ID key, this was changed previously to use `session.Group` but that may mask errors from the real session, and other parallel sessions may not have the right file sync provider.
- `session.Group` dropped from snapshot args because the parent ref is always `nil`.
> Local should use session ID in op and only fallback to session group

- client/llb/fileop.go
Marshal the constraints after the capabilities are added, not before.
> Fix missing capabilities in FileOp

- frontend/dockerfile/shell/lex.go
- frontend/dockerfile/shell/lex_test.go
Adds a new method to the shell package. This is useful for getting the list of arguments that are actually in use.
> shell: add function to detect what env were used

- cmd/buildctl/build.go
follow-up https://github.com/docker/buildx/pull/946#discussion_r804400463
> buildctl: indent metadata json output

- go.mod
- go.sum
- vendor/github.com/containerd/go-cni/README.md
- vendor/github.com/containerd/go-cni/cni.go
- vendor/github.com/containerd/go-cni/namespace.go
- vendor/modules.txt
Fix CNI panic https://github.com/moby/buildkit/pull/2589#issuecomment-1032012405
https://github.com/containerd/go-cni/compare/v1.1.1...v1.1.2
> Bump github.com/containerd/go-cni to v1.1.2

- source/http/httpsource.go
fixes #2420
When a server returns a weak etag, the prefix can
cause a mismatch on a direct comparison with the old value.
@shatilov-diman
> http: handle weak etags on comparisons

- go.mod
- go.sum
- vendor/github.com/containerd/go-cni/opts.go
- vendor/modules.txt
follow-up https://github.com/moby/buildkit/pull/2637#issuecomment-1040410007
> Bump github.com/containerd/go-cni to v1.1.3

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/.dockerignore
- vendor/github.com/containerd/containerd/ADOPTERS.md
- vendor/github.com/containerd/containerd/BUILDING.md
- vendor/github.com/containerd/containerd/README.md
- vendor/github.com/containerd/containerd/RELEASES.md
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
https://github.com/containerd/containerd/compare/v1.6.0-rc.2...v1.6.0
> Bump github.com/containerd/containerd to v1.6.0

- docs/cni-networking.md
follow-up https://github.com/docker/buildx/pull/953#discussion_r805468576
> docs: custom image with cni networking

- solver/llbsolver/solver.go
When inline cache requests blobs to be computed for the new layers currently it doesn't show any output in progressbar and the build looks stuck. I've added a special progress row just for inline cache. I also removed the regular cache export progress row when the inline cache is used as I don't think it does anything.
> show progress when exporting inline cache

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/github.com/docker/docker/client/client.go
- vendor/github.com/docker/docker/client/container_wait.go
- vendor/github.com/docker/docker/client/options.go
- vendor/github.com/docker/docker/client/request.go
- vendor/github.com/docker/docker/opts/quotedstring.go
- vendor/github.com/docker/docker/pkg/archive/archive.go
- vendor/github.com/docker/docker/pkg/archive/archive_linux.go
- vendor/github.com/docker/docker/pkg/archive/archive_unix.go
- vendor/github.com/docker/docker/pkg/archive/diff.go
- vendor/github.com/docker/docker/pkg/system/syscall_windows.go
- vendor/github.com/docker/docker/testutil/daemon/daemon.go
- vendor/modules.txt
https://github.com/moby/moby/compare/40bb9831756f...c78f6963a1c0
> vendor: github.com/docker/docker c78f696

- hack/util
> ci: opt-in buildinfo attrs

- executor/containerdexecutor/executor.go
- executor/runcexecutor/executor.go
- solver/llbsolver/ops/exec.go
Adds more visibility into the traces for exec ops
> Add events for exec op for container start / exit

- executor/oci/spec.go
- util/network/netproviders/network.go
- util/network/netproviders/network_unix.go
- util/network/netproviders/network_windows.go
- worker/base/worker.go
- worker/containerd/containerd.go
- worker/runc/runc.go
- worker/worker.go
Expose the following labels:
- `org.mobyproject.buildkit.worker.network=(cni|host)`
- `org.mobyproject.buildkit.worker.apparmor.profile=PROFILE`
- `org.mobyproject.buildkit.worker.oci.process-mode=(sandbox|no-sandbox)`
> worker:  expose labels: o.m.b.worker.{network=(cni|host), apparmor.profile=PROFILE, oci.process-mode=(sandbox|no-sandbox)}

- solver/llbsolver/ops/exec.go
- solver/llbsolver/ops/file.go
- util/progress/progressui/display.go
- util/progress/progressui/printer.go
- worker/base/worker.go
These two commits fix the various issues mentioned in #2689
> Plain progress + progress controller fixes

- .github/workflows/build.yml
- Dockerfile
> ci: update to latest stable buildkit

- docs/images-readme.md
https://hub.docker.com/r/moby/buildkit
> docs: update images-readme

- solver/pb/ops.pb.go
- solver/pb/ops.proto
Signed-off-by: Ce Gao <ce.gao@outlook.com>
> fix(solver): Fix the comment of SSHOpt

- util/progress/progressui/printer.go
> [v0.10] progressui: fix printing of hidden vertexes.

- util/progress/progressui/printer.go
cherry-pick https://github.com/moby/buildkit/pull/2763
I messed up the target branch in #2766 :( and for some reason Github did not detect that there were no changes 🤷
> [v0.10] progressui: fix printing of hidden vertexes

- util/buildinfo/buildinfo.go
- util/buildinfo/buildinfo_test.go
fix case where build info dependencies attributes are not removed when build info is pushed to image config.
repro with https://github.com/crazy-max/buildx-buildkit-tests/tree/main/buildkit-2684
```console
$ docker buildx bake --metadata-file metadata.json --set *.args.foo=bar --set *.args.bar=foo app --push --set *.tags=crazymax/buildx:2684-1
$ docker buildx imagetools inspect crazymax/buildx:2684-1 --format "{{json .BuildInfo}}"
```
```json
{
"frontend": "dockerfile.v0",
"sources": [
{
"type": "docker-image",
"ref": "docker.io/library/busybox:1.35.0@sha256:20246233b52de844fa516f8c51234f1441e55e71ecdd1a1d91ebb252e1fd4603",
"pin": "sha256:20246233b52de844fa516f8c51234f1441e55e71ecdd1a1d91ebb252e1fd4603"
},
{
"type": "docker-image",
"ref": "docker.io/library/busybox:latest",
"pin": …
```
> buildinfo: fix attrs not removed from deps when formatted

- util/buildinfo/buildinfo.go
- util/buildinfo/buildinfo_test.go
#2716
(cherry picked from commit 1edee3e4cdd6fecb6889de69512dbe5d01b2bb1e)
> [v0.10] buildinfo: fix attrs not removed from deps when formatted

- docs/multi-platform.md
> docs: add cross-compile notes to multi-platform docs

- .golangci.yml
- cache/metadata.go
- client/client_test.go
- client/llb/marshal.go
- client/llb/state.go
- exporter/containerimage/writer.go
- frontend/dockerfile/dockerignore/dockerignore_test.go
- frontend/gateway/gateway.go
- session/manager.go
- solver/jobs.go
- solver/llbsolver/bridge.go
- solver/llbsolver/solver.go
- solver/scheduler.go
- source/containerimage/pull.go
- util/progress/multiwriter.go
- util/throttle/throttle.go
- util/winlayers/context.go
- util/winlayers/differ.go
+ [x] Enable the `gosimple` linter that catches many interesting simplifications
+ [x] Fix the offenses
Signed-off-by: David Gageot <david.gageot@doctolib.com>
> Enable gosimple linter

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
- frontend/gateway/forwarder/forward.go
- worker/workercontroller.go
@cpuguy83 @AkihiroSuda @crazy-max
> [v0.10.3] cherry-picks

- frontend/dockerfile/dockerfile_test.go
follow-up https://github.com/moby/moby/pull/43571#issuecomment-1121071014
> dockerfile: fix named contexts test for dockerd

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/.mailmap
- vendor/github.com/containerd/containerd/version/version.go
- vendor/github.com/containerd/go-cni/.golangci.yml
- vendor/github.com/containerd/go-cni/deprecated.go
- vendor/github.com/containerd/go-cni/opts.go
- vendor/github.com/containernetworking/cni/libcni/conf.go
- vendor/github.com/containernetworking/cni/pkg/version/plugin.go
- vendor/github.com/opencontainers/selinux/go-selinux/rchcon.go
- vendor/github.com/opencontainers/selinux/go-selinux/rchcon_go115.go
- vendor/modules.txt
lol; looks like I had this open, but didn't commit/push; so here goes
full diff: https://github.com/containerd/containerd/compare/v1.6.3...v1.6.4
> vendor: github.com/containerd/containerd v1.6.4

- util/testutil/integration/run.go
> integration: update tests cleanup

- frontend/dockerfile/dockerfile2llb/convert.go
This patch introduces a mutex in the opt.ContextByName function, which was not thread-safe when used in an ErrorGroup, as it accesses the buildInfo.Deps map variable. By introducing a mutex around this function, we ensure it's thread-safety, preventing an unnecessary crash.
> dockerfile2llb: protect against concurrent map write

- cmd/buildkitd/main_containerd_worker.go
fixes: https://github.com/moby/buildkit/issues/2965
cherry-picking https://github.com/moby/buildkit/pull/2968
> [v0.10 backport] rootless: containerd worker: Add fallback when buildkitd cannot access to containerd

- .gitignore
This adds a note about what should be added to the `.gitignore` file as recommended by @thaJeztah 
https://github.com/moby/buildkit/pull/2954#discussion_r921083195
cc/ @jedevc
> Add gitignore note

- cache/remotecache/export.go
- cache/remotecache/gha/gha.go
- cache/remotecache/s3/s3.go
- exporter/containerimage/export.go
- exporter/containerimage/writer.go
- exporter/oci/export.go
- exporter/tar/export.go
- solver/llbsolver/solver.go
- source/containerimage/pull.go
- util/progress/progress.go
- util/push/push.go
follow-up https://github.com/docker/buildx/pull/1177#discussion_r935384322
mutualize and expose `OneOff` progress.
> progress: mutualize OneOff helper

- Dockerfile
https://github.com/tonistiigi/binfmt/releases/tag/buildkit%2Fv7.0.0-29
> Dockerfile: update qemu binfmt to v7.0.0

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/buildx-image.yml
- .github/workflows/dockerd.yml
- .github/workflows/validate.yml
- frontend/gateway/pb/gateway.pb.go
also adds dependabot to keep the github actions being used in our workflows up to date.
> ci: update github actions

- exporter/containerimage/export.go
Follow up to #2935.
Signed-off-by: Justin Chadwell <me@jedevc.com>
> attestations: suppress containerd media type warnings

- README.md
Help out people such as 
- https://github.com/moby/buildkit/issues/2749
- https://github.com/moby/buildkit/issues/1280
- https://github.com/moby/buildkit/issues/2138
> docs: a note about filename opt

- frontend/dockerfile/shell/lex_test.go
`ADD https://.../something-${VERSION}.${TARGETOS}-${TARGETARCH}${TARGETVARIANT:+-${TARGETVARIANT}}.tar.gz` is a useful form but wasn't tested so far (AFAICS).
The string is expanded like:
- something-v1.2.3.linux-amd64.tar.gz
- something-v1.2.3.linux-arm-v7.tar.gz
- something-v1.2.3.linux-arm64.tar.gz
- something-v1.2.3.linux-ppc64le.tar.gz
- something-v1.2.3.linux-riscv64.tar.gz
- something-v1.2.3.linux-s390x.tar.gz
Corresponds to the filenames convention used in https://github.com/moby/buildkit/releases .
> dockerfile/shell/lex_test.go: test `${TARGETVARIANT:+-${TARGETVARIANT}}`

- MAINTAINERS
Please welcome @jedevc to maintainers 🎉 
Already agreed in Slack vote. Feel free to verify e-mails etc.
> add jedevc to maintainers

- client/client_test.go
- util/contentutil/buffer.go
- util/contentutil/buffer_test.go
- util/contentutil/source.go
- util/contentutil/source_test.go
- util/imageutil/config.go
- util/pull/pull.go
https://github.com/moby/buildkit/releases/tag/v0.10.5
> Bring in patches from v0.10.5

- go.mod
- go.sum
- solver/llbsolver/ops/exec.go
- source/git/gitsource.go
- util/progress/logs/logs.go
- vendor/github.com/armon/circbuf/.gitignore
- vendor/github.com/armon/circbuf/LICENSE
- vendor/github.com/armon/circbuf/README.md
- vendor/github.com/armon/circbuf/circbuf.go
- vendor/github.com/armon/circbuf/go.mod
- vendor/modules.txt
related to https://github.com/moby/buildkit/pull/1754#issuecomment-1280705920
backport of:
* https://github.com/moby/buildkit/pull/2577
* ~:warning: needs https://github.com/moby/buildkit/pull/2203~
* https://github.com/moby/buildkit/pull/1934 (commit f3e6120a6b019a2d8eaa3a774610beb69286287d)
> [v0.8 backport] log clipping fixes

- cmd/buildctl/build/exportcache.go
- cmd/buildctl/build/importcache.go
- cmd/buildctl/build/output.go
- cmd/buildctl/build/secret.go
- cmd/buildkitd/main.go
- frontend/attestations/parse.go
- util/progress/progressui/colors.go
see individual commits for details
> cmd/*: use strings.Cut for key/values, and some minor cleanups

- README.md
Signed-off-by: David Gageot <david.gageot@docker.com>
> Fix a few typos on the README.md

- .github/workflows/build.yml
See similar in https://github.com/docker/buildx/pull/1329.
> ci: skip build workflow on pure docs changes

- .github/CONTRIBUTING.md
- Dockerfile
closes #3225
related to #3235
As discussed remove these stages.
> Dockerfile: remove orphan stages

- docs/build-repro.md
- frontend/dockerfile/dockerfile_buildinfo_test.go
- util/buildinfo/buildinfo_test.go
Some tests were depending on the sha256sum of https://raw.githubusercontent.com/moby/moby/master/README.md
> moby/moby/master -> moby/moby/v20.10.21

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/copy/copy.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_linux.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_unix.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_windows.go
- vendor/github.com/tonistiigi/fsutil/copy/mkdir.go
- vendor/github.com/tonistiigi/fsutil/copy/mkdir_unix.go
- vendor/github.com/tonistiigi/fsutil/copy/mkdir_windows.go
- vendor/github.com/tonistiigi/fsutil/diskwriter.go
- vendor/modules.txt
:hammer_and_wrench: Pulls in fixes for https://github.com/moby/buildkit/issues/2884 and https://github.com/moby/buildkit/issues/2884#issuecomment-1301028540
> vendor: update fsutil to master@0127568

- Dockerfile
> Bump xx to 1.1.2

- README.md
- docs/buildctl.md
As discussed with @jedevc , start of a buildctl doc.
> start of documentation for buildctl

- Dockerfile
fixes https://github.com/moby/buildkit/issues/3060
> Dockerfile: update qemu binfmt to v7.1.0

- util/tracing/detect/detect.go
- util/tracing/detect/recorder.go
> tracing: fix error on process shutdown if tracing not enabled

- .github/workflows/build.yml
- Dockerfile
- hack/release-tar
- hack/util
> ci: generate provenance and sbom for release-tar

- go.mod
- go.sum
- vendor/github.com/Microsoft/hcsshim/internal/cow/cow.go
- vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/snapshots/overlay/overlayutils/check.go
- vendor/github.com/containerd/containerd/task.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
full diff: https://github.com/Microsoft/hcsshim/compare/v0.9.5...v0.9.6
full diff: https://github.com/containerd/containerd/compare/v1.6.11...v1.6.13
> vendor: github.com/containerd/containerd v1.6.13

- .github/workflows/build.yml
> github: update to latest dev version

- exporter/local/fs.go
- solver/llbsolver/provenance.go
- solver/llbsolver/solver.go
> fix indentation for in-toto and traces

- client/client_test.go
- hack/test
> cache: test gha cache exporter

- hack/azblob_test/test.sh
Attempt to fix the flakiness in the azblob test job by updating the logic for checking if buildkitd is up and running Fixes #3369
Signed-off-by: Pranav Pandit <pranavp@microsoft.com>
> Flakiness in azblob test job

- client/connhelper/nerdctlcontainer/nerdctlcontainer.go
- client/connhelper/nerdctlcontainer/nerdctlcontainer_test.go
> feat: add nerdctl-container support for client

- exporter/attestation/unbundle.go
If we have any SBOMs that are notated as primary, then we should ensure that they appear before the others in the list of attestations.
This ensures that clients should be able to naively take the "first" SBOM, to get the most relevant one that applies to the main rootfs.
> exporter: ensure spdx order prioritizes primary sbom

- .github/workflows/build.yml
- docs/attestations/slsa-definitions.md
No functional changes expected but make sure to use the latest release.
> github: update CI to buildkit version

- README.md
> docs: add nerdctl container buildkitd address docs

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/version/version.go
- vendor/github.com/docker/cli/cli/config/configfile/file.go
- vendor/github.com/docker/cli/cli/config/credentials/file_store.go
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/github.com/docker/docker/api/types/filters/parse.go
- vendor/github.com/docker/docker/pkg/homedir/homedir_linux.go
- vendor/modules.txt
no changes to vendored code, other than updated version
full diff: https://github.com/conainerd/containerd/compare/v1.6.14...v1.6.15
full diff: https://github.com/docker/docker/compare/v23.0.0-rc.1...v23.0.0-rc.2
full diff: https://github.com/docker/cli/compare/v23.0.0-rc.1...v23.0.0-rc.2
> vendor: github.com/docker/docker, github.com/docker/cli v23.0.0-rc.2

- README.md
Signed-off-by: Aaron Lehmann <alehmann@netflix.com>
> Correct manifests_prefix documentation for S3 cache

- cache/manager.go
- cache/opts.go
- cache/remotecache/local/local.go
- util/contentutil/multiprovider.go
- worker/base/worker.go
#3493
Signed-off-by: Kohei Tokunaga <ktokunaga.mail@gmail.com>
(cherry picked from commit c68af33fb637fb2e47c56b9a7dae4d8e9029866a)
> [v0.11] cherry-pick: Make local cache importer non-lazy

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/snapshots/overlay/overlay.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
Fix tx closed error when upperdirlabel specified
full diff: https://github.com/containerd/containerd/compare/1709cfe273d9...v1.6.16
> [0.11] vendor: github.com/containerd/containerd v1.6.16

- docs/stargz-estargz.md
This commit adds documents about configuration of rootless stargz-snapshotter using RootlessKit.
> docs: Enable rootless for stargz-snapshotter

- client/build_test.go
- client/client_test.go
- util/testutil/integration/dockerd.go
- util/testutil/integration/sandbox.go
> integration: fix compat check for CNI DNS test

- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
> frontend: fix typo in release script

- cache/remotecache/inline/inline.go
pick #3580
(cherry picked from commit 39ff1c04fef4a66906ccebfafba4ed0ff9b0a85b)
> [v0.11] inline cache: fix blob indexes by uncompressed digest

- source/gitidentifier_test.go
- util/gitutil/git_ref.go
- util/gitutil/git_ref_test.go
* backport of https://github.com/moby/buildkit/pull/3596
> [0.11 backport] git context: fix support for empty git ref with subdir

- .github/workflows/build.yml
- .github/workflows/validate.yml
This is not necessary to have a branch restriction on pull request event.
> ci: remove branch restriction on pull request event

- Dockerfile
fixes #3625 
https://github.com/tonistiigi/xx/compare/v1.1.2...v1.2.1
> Dockerfile: update xx to 1.2.1

- .github/workflows/build.yml
- .github/workflows/buildx-image.yml
- .github/workflows/dockerd.yml
- .github/workflows/validate.yml
> ci: update buildx to latest

- Dockerfile
* backport of https://github.com/moby/buildkit/pull/3627
> [0.10 backport] Dockerfile: update xx to 1.2.1

- cache/remote.go
- client/llb/definition.go
- client/llb/definition_test.go
- frontend/dockerfile/dockerfile_test.go
- snapshot/diffapply_unix.go
- #3670
- #3659
- #3671 (I didn't pick the test as it adds a new dependency)
> v0.11.4 cherry picks

- Dockerfile
- go.mod
- go.sum
- vendor/github.com/containerd/containerd/RELEASES.md
- vendor/github.com/containerd/containerd/install.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
https://github.com/containerd/containerd/compare/v1.7.0-rc.3...v1.7.0
> go.mod: github.com/containerd/containerd v1.7.0

- README.md
Just noticed this list, so adding mine to the pile. :pray:
> add Bass to list of LLB languages

- Dockerfile
https://github.com/opencontainers/runc/releases/tag/v1.1.5
> Dockerfile: RUNC_VERSION=v1.1.5

- solver/llbsolver/proc/sbom.go
- util/resolver/authorizer.go
> [v0.11] cherry-picks for v0.11.6

- exporter/containerimage/attestations.go
🙈 sorry, quite a silly PR, but noticed this when looking at this file, and couldn't help but fixing it.
> exporter/containerimage: remove redundant type for var declaration

- util/testutil/imageinfo.go
`ReadImages` should read single-platform images distributed as a single manifest.
Without this, the caller would need to call both `ReadImage` and `ReadImages` to read an image that may be distributed as a manifest or an index.
Will fix https://github.com/docker/buildx/actions/runs/5013336634/jobs/8986293860?pr=1770.
> testutil: update ReadImages to fallback to reading manifest

- go.mod
- go.sum
- vendor/github.com/spdx/tools-golang/json/writer.go
- vendor/github.com/spdx/tools-golang/spdx/v2/v2_1/creation_info.go
- vendor/github.com/spdx/tools-golang/spdx/v2/v2_1/package.go
- vendor/github.com/spdx/tools-golang/spdx/v2/v2_2/creation_info.go
- vendor/github.com/spdx/tools-golang/spdx/v2/v2_2/document.go
- vendor/github.com/spdx/tools-golang/spdx/v2/v2_2/package.go
- vendor/github.com/spdx/tools-golang/spdx/v2/v2_3/creation_info.go
- vendor/github.com/spdx/tools-golang/spdx/v2/v2_3/document.go
- vendor/github.com/spdx/tools-golang/spdx/v2/v2_3/package.go
- vendor/github.com/stretchr/testify/assert/assertion_compare.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertion_order.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/assert/doc.go
- vendor/github.com/stretchr/testify/assert/http_assertions.go
- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/modules.txt
:arrow_up: Follow-up to https://github.com/moby/buildkit/pull/3842 (cc @sozercan you may be interested)
Updates [spdx/tools-golang](https://github.com/spdx/tools-golang/) from [v0.5.0](https://github.com/spdx/tools-golang/releases/tag/v0.5.0) to [v0.5.1](https://github.com/spdx/tools-golang/releases/tag/v0.5.1).
Full changelog: https://github.com/spdx/tools-golang/compare/v0.5.0...v0.5.1.
> vendor: update spdx/tools-golang to v0.5.1

- client/llb/fileop.go
- client/llb/meta.go
- client/llb/source.go
- client/llb/state.go
Just some more method/fn documentation for various llb opts.
Still planning on more but wanted to get another chunk of this out.
> Adding more docs to client/llb

- .github/CONTRIBUTING.md
With some minor formatting changes as well.
> docs: add running instruction to CONTRIBUTING.md

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/Dockerfile
- vendor/github.com/tonistiigi/fsutil/copy/mkdir_windows.go
- vendor/github.com/tonistiigi/fsutil/diskwriter.go
- vendor/github.com/tonistiigi/fsutil/docker-bake.hcl
- vendor/github.com/tonistiigi/fsutil/walker.go
- vendor/modules.txt
https://github.com/tonistiigi/fsutil/compare/9e7a6df48576...36ef4d8c0dbb
> vendor: update fsutil to 36ef4d8

- Dockerfile
containerd v1.7.2: https://github.com/containerd/containerd/releases/tag/v1.7.2
> Dockerfile: update containerd to v1.7.2

- README.md
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/issues/3988
> docs: update README to reference OpenTelemetry instead of OpenTracing

- util/testutil/integration/dockerd.go
follow-up https://github.com/moby/moby/pull/45918
> test: always disable tls for dockerd worker

- .mailmap
- AUTHORS
cc @smira @dgageot @hinshun @ktock @nicks @vieux @vladaionescu
> chore: update AUTHORS and mailmap

- go.mod
- go.sum
- vendor/github.com/docker/docker/AUTHORS
- vendor/github.com/docker/docker/client/container_stats.go
- vendor/github.com/docker/docker/client/request.go
- vendor/github.com/docker/docker/pkg/archive/archive_unix.go
- vendor/github.com/docker/docker/pkg/chrootarchive/archive_freebsd.go
- vendor/github.com/docker/docker/pkg/chrootarchive/archive_linux.go
- vendor/github.com/docker/docker/pkg/chrootarchive/archive_unix.go
- vendor/github.com/docker/docker/pkg/chrootarchive/diff_unix.go
- vendor/modules.txt
related to #2376 
notable changes:
- pkg/chrootarchive: fix FreeBSD build
full diff: https://github.com/docker/docker/compare/8e51b8b...afd4805
cc @akhramov
> vendor: github.com/docker/docker@master (afd4805)

- hack/test
> [0.12 backport] integration: missing env var to check feature compat

- solver/llbsolver/file/backend.go
This avoids duplication of the AttemptUnpackDockerCompatability handling.
> chore: clean up file copy logic backend logic

- session/filesync/filesync.go
follow-up https://github.com/docker/buildx/pull/1927#discussion_r1250835214
> filesync: write closer err discarded

- session/filesync/filesync.go
> [0.12 backport] filesync: write closer err discarded

- docs/dev/solver.md
This gives a new example for the LLB case, explaining the purpose of what both the selectors and the content-based caching function can be used for.
> Improve CacheMap developer documentation

- Dockerfile
- go.mod
- go.sum
- vendor/github.com/opencontainers/runc/libcontainer/user/user.go
- vendor/modules.txt
https://github.com/opencontainers/runc/releases/tag/v1.1.8
https://github.com/opencontainers/runc/releases/tag/v1.1.9
https://github.com/opencontainers/runc/compare/v1.1.7...v1.1.9
> Dockerfile: RUNC_VERSION=v1.1.9

- client/llb/fileop_test.go
This commit adds three test cases for the `WithUser` function in the client's `llb` package. These tests cover different use cases of the `WithUser` function:
- "root:root": Tests the scenario where both the user and the group are root.
- "foo:bar": Tests the scenario where a non-root user and group are specified.
- "uid:gid": Tests the scenario where the user and group are specified by their numeric IDs.
These run a few previously untested paths which increases code coverage a bit.
> llb: Add tests for WithUser

- cmd/buildkitd/main.go
- control/control.go
- solver/bboltcachestorage/storage.go
Similar to #4185 the cache and history db were not closed on exit.
> fix(boltdb): close cache and history dbs on exit

- .github/workflows/.test.yml
- .github/workflows/buildkit.yml
- .github/workflows/buildx-image.yml
- .github/workflows/dockerd.yml
- .github/workflows/frontend.yml
- .github/workflows/test-os.yml
- .github/workflows/validate.yml
follow-up https://github.com/moby/buildkit/pull/4048#discussion_r1326858346
> ci: update github actions to latest stable

- docs/nydus.md
Fixed minor issue with incorrect wording
> docs: fix typo in nydus.md

- examples/buildkit0/buildkit.go
- examples/buildkit1/buildkit.go
- examples/buildkit2/buildkit.go
- examples/buildkit3/buildkit.go
- examples/buildkit4/buildkit.go
- examples/nested-llb/main.go
- go.mod
- go.sum
- hack/dockerfiles/vendor.Dockerfile
Updates go.mod to version 1.21
> Update to go 1.21

- .github/issue_reporting_guide.md
Add guidelines for how to report issues in this repository to give them the best probability of being resolved quickly. We can add a link to it to the "new issue" template and recommend new users to read it through as well as link to it from various issues when needed.
Feel free to review and leave suggestions but this can also be a living document where new sections can be added later.
> github: add issue reporting guide

- Dockerfile
- go.mod
- go.sum
- vendor/github.com/containerd/containerd/.mailmap
- vendor/github.com/containerd/containerd/pkg/unpack/unpacker.go
- vendor/github.com/containerd/containerd/remotes/docker/httpreadseeker.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
containerd v1.7.10 release note: https://github.com/containerd/containerd/releases/tag/v1.7.10
> Bump up containerd to v1.7.10

- MAINTAINERS
Welcome to maintainers @gabriel-samfira, and thanks for all the help with the WCOW work!
Already been confirmed with the maintainer vote.
> add gabriel-samfira to maintainers

- Dockerfile
- go.mod
- go.sum
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/oci/spec.go
- vendor/github.com/containerd/containerd/oci/spec_opts.go
- vendor/github.com/containerd/containerd/oci/spec_opts_nonwindows.go
- vendor/github.com/containerd/containerd/oci/spec_opts_windows.go
- vendor/github.com/containerd/containerd/pkg/deprecation/deprecation.go
- vendor/github.com/containerd/containerd/remotes/docker/resolver.go
- vendor/github.com/containerd/containerd/remotes/handlers.go
- vendor/github.com/containerd/containerd/tracing/tracing.go
- vendor/modules.txt
containerd 1.7.11 release note: https://github.com/containerd/containerd/releases/tag/v1.7.11
> Bump up containerd to 1.7.11

- cmd/buildkitd/main_containerd_worker.go
- cmd/buildkitd/main_oci_worker.go
> cmd/buildkitd: show "bridge" net mode in `--help`

- hack/test
- relates to https://github.com/moby/moby/pull/47054#issuecomment-1884715610
> hack/test: allow ALPINE_VERSION to be set from env

- hack/dockerfiles/authors.Dockerfile
3.17 reached EOL, so updating to current version.
> authors.Dockerfile: update to alpine 3.19

- docs/reference/buildctl.md
> docs: fix up named context docs

- frontend/gateway/gateway.go
Potential fix for https://github.com/moby/buildkit/issues/4571.
When closing pipes, we only need to close one side (which was previously correct), but we do need to ensure that we correctly discard both sides from our internal maps (which wasn't being done).
This could cause ExecProcess to potentially hang indefinitely. This was originally detected because this hang meant that shutting down the GRPC server with a graceful shutdown would wait for all ongoing RPCs to stop - which would then never happen, and cause a deadlock.
> gateway: ensure that all process io is correctly closed

- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
- hack/util
> [0.12 backport] use local context and disable image push if not upstream repo

- docs/buildkitd.toml.md
- frontend/dockerfile/docs/reference.md
Just a couple rephrasings, typo fixes, and deduplications in docs
relates to:
- https://github.com/docker/docs/issues/19165
- https://github.com/docker/docs/issues/19152
- https://github.com/docker/docs/issues/19151
> docs: tiny improvements

- executor/stubs.go
Fix for https://github.com/moby/buildkit/security/advisories/GHSA-4v98-7qmw-rqr8
(cherry picked from commit 96ccaec09c51176a6d954fd7c4ce57d519bae1b2)
> executor: recheck mount stub path within root after container run

- docs/rootless.md
- examples/eksctl/bottlerocket.yaml
> [v0.12] docs/rootless.md: move auxiliary information to the bottom

- client/client_test.go
related to https://github.com/moby/moby/pull/47364#discussion_r1488137611
When implementing multiple exporter we forgot to skip the oci exporter for the dockerd worker in https://github.com/moby/buildkit/commit/1c1777b7c02f9b6d262845546468b138938d8864.
cc @vvoland
> client: fix multiple exporter test for dockerd worker

- hack/test
related to https://github.com/moby/buildkit/pull/4606
> hack: fix unbound variable

- frontend/dockerfile/dockerfile2llb/exclude_patterns_test.go
Fixing merge conflict between #4561 and #4663
> dockerfile2llb: fix ci merge conflict

- go.mod
- go.sum
- vendor/github.com/serialx/hashring/.gitignore
- vendor/github.com/serialx/hashring/hash.go
- vendor/github.com/serialx/hashring/hashring.go
- vendor/github.com/serialx/hashring/key.go
- vendor/modules.txt
full diff: https://github.com/serialx/hashring/compare/8b2912629002...22c0c7ab6b1b
> vendor: update github.com/serialx/hashring to 22c0c7ab6b1b

- solver/llbsolver/file/backend.go
- solver/llbsolver/file/unpack.go
> file: fix idmap passed to unpack when userns enabled

- executor/resources/monitor.go
- executor/resources/types/types.go
- util/network/cniprovider/cni.go
- util/network/cniprovider/cni_linux.go
- util/network/cniprovider/cni_nolinux.go
- util/network/host.go
- util/network/network.go
- util/network/none.go
follow-up https://github.com/moby/buildkit/pull/4689
related to https://github.com/docker/buildx/pull/2280/commits/4c1003bc38986f6be546cf7b48f8c4215ab7a59b
> move network sample to resources types

- .github/workflows/validate.yml
- README.md
- docs/build-repro.md
- docs/windows.md
- frontend/dockerfile/docs/reference.md
backport of
* https://github.com/moby/buildkit/pull/4737
* https://github.com/moby/buildkit/pull/4739
* https://github.com/moby/buildkit/pull/4740
> [v0.13] cherry-picks

- util/testutil/dockerd/daemon.go
- util/testutil/integration/run.go
- util/testutil/workers/backend.go
- util/testutil/workers/containerd.go
- util/testutil/workers/dockerd.go
related to https://github.com/docker/buildx/pull/2307
> testutil: add binary and extraEnv opt for dockerd worker

- frontend/dockerfile/docs/reference.md
> docs: add type=tmpfs to run mounts overview

- .github/workflows/.test.yml
- .github/workflows/buildkit.yml
- .github/workflows/dockerd.yml
- .github/workflows/test-os.yml
follow-up https://github.com/moby/moby/pull/47636
> ci: update workflow artifacts retention

- client/llb/source.go
follow-up https://github.com/docker/buildx/pull/2363#discussion_r1543083218
> client: expose git auth header and token keys

- executor/oci/spec.go
> oci: fix missing release call

- solver/edge.go
- solver/jobs.go
- solver/scheduler.go
Dagger users have been hitting "inconsistent graph state errors" more and more: https://github.com/dagger/dagger/issues/6234 (corresponding issue in this repo: https://github.com/moby/buildkit/issues/2303)
I spent a while trying to repro in a test case and while I've triggered suspicious looking behavior have not yet figured out what specific scenario could cause the actual error. So falling back to adding more scheduler debug logs that should have enough information to track down what's going on next time it's hit.
---
Just for the record, similar to the discussion on #2303, the only way I can see this happening is:
1. An edge make requests for inputs
2. One of the dep edges was merged but the owner points to an edge which no longer has any states in the `actives` map
* This I can …
> solver: add more debug logs to track down inconsistent graph state

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli/config/configfile/file.go
- vendor/github.com/docker/docker/AUTHORS
- vendor/github.com/docker/docker/pkg/system/stat_illumos.go
- vendor/modules.txt
- full diff: https://github.com/docker/docker/compare/v26.0.2...v26.1.0
> vendor: update github.com/docker/docker to v26.1.0

- frontend/dockerfile/dockerfile_provenance_test.go
related to https://github.com/moby/moby/pull/47683#issuecomment-2077040769
> frontend: missing compat check for TestCommandSourceMapping

- MAINTAINERS
Add Shaun to curators so he can help us manage issue statuses, etc.
> Add thompson-shaun to curators

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/github.com/docker/docker/api/types/types.go
- vendor/modules.txt
full diff: https://github.com/golang/mod/compare/v0.13.0...v0.17.0
diffs:
- https://github.com/moby/moby/compare/v26.1.3...v26.1.4
- https://github.com/docker/cli/compare/v26.1.3...v26.1.4
> vendor: docker/docker, docker/cli v26.1.4

- frontend/dockerfile/docs/rules/undefined-arg-in-from.md
- frontend/dockerfile/linter/docs/UndefinedArgInFrom.md
Add doc for UndefinedArgInFrom
> lint: add doc for UndefinedArgInFrom

- cache/blobs.go
- cache/refs.go
- cache/remote.go
- cache/remotecache/inline/inline.go
- cache/remotecache/registry/registry.go
- client/build.go
- client/llb/marshal.go
- client/llb/state.go
- client/solve.go
- cmd/buildctl/build/opt.go
- cmd/buildkitd/main_containerd_worker.go
- exporter/containerimage/annotations.go
- exporter/containerimage/export.go
- exporter/oci/export.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/outline.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/shell/lex.go
- frontend/gateway/gateway.go
- solver/llbsolver/solver.go
- source/containerimage/pull.go
- util/converter/converter.go
- util/progress/multiwriter.go
- util/progress/progress.go
- util/resolver/authorizer.go
- util/testutil/integration/run.go
Rewrite some handwritten logic with recent helper function from go stdlib
> refactor with slices and maps pkg

- exporter/containerimage/export.go
- frontend/dockerfile/dockerfile_test.go
> [v0.14] Fix content not found with `push=true,rewrite-timestamp=true`

- util/resolver/resolver.go
The httpFallback mutates the `host` field, which needs a synchronization
when the same httpFallback is used by multiple goroutines.
This is happens with containerd push which uses `Dispatch` to
walk the image recursively to push every blob.
> util/resolver: Make httpFallback concurrent safe

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/builder/resolvecache.go
fixes #4971
~depends on #5022~
> dockerfile: deduplicate and cache config resolve requests

- go.mod
- go.sum
- vendor/github.com/klauspost/compress/.goreleaser.yml
- vendor/github.com/klauspost/compress/README.md
- vendor/github.com/klauspost/compress/internal/snapref/encode_other.go
- vendor/github.com/klauspost/compress/s2sx.mod
- vendor/github.com/klauspost/compress/zstd/blockdec.go
- vendor/github.com/klauspost/compress/zstd/blockenc.go
- vendor/github.com/klauspost/compress/zstd/decodeheader.go
- vendor/github.com/klauspost/compress/zstd/decoder.go
- vendor/github.com/klauspost/compress/zstd/dict.go
- vendor/github.com/klauspost/compress/zstd/enc_best.go
- vendor/github.com/klauspost/compress/zstd/enc_better.go
- vendor/github.com/klauspost/compress/zstd/encoder_options.go
- vendor/github.com/klauspost/compress/zstd/frameenc.go
- vendor/github.com/klauspost/compress/zstd/fse_decoder_generic.go
- vendor/github.com/klauspost/compress/zstd/internal/xxhash/xxhash_arm64.s
- vendor/github.com/klauspost/compress/zstd/matchlen_amd64.s
- vendor/github.com/klauspost/compress/zstd/seqdec_amd64.s
- vendor/modules.txt
https://github.com/klauspost/compress/compare/v1.17.4...v1.17.9
> vendor: update klauspost/compress to v1.17.9

- frontend/dockerfile/dockerfile2llb/convert.go
Discussed in:
- https://github.com/moby/buildkit/pull/5064#issuecomment-2187651364
> Disallow `ADD --checksum=<SUM> <GITSRC> <DST>`

- .github/workflows/.test.yml
- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
- .github/workflows/test-os.yml
- hack/images
- hack/release
- hack/util
follow-up https://github.com/moby/buildkit/pull/4788
Set `repository` and `ghtoken` attributes for `gha` cache to avoid getting rate limited in this repo.
> ci: set gha cache repository and token

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli/config/credentials/file_store.go
- vendor/github.com/docker/docker/api/types/types.go
- vendor/github.com/docker/docker/api/types/types_deprecated.go
- vendor/github.com/docker/docker/pkg/archive/archive_linux.go
- vendor/modules.txt
diffs:
- https://github.com/docker/docker/compare/v27.0.1...v27.0.2
- https://github.com/docker/cli/compare/v27.0.1...v27.0.2
> vendor: docker/docker, docker/cli v27.0.2

- go.mod
- go.sum
- vendor/github.com/docker/docker/pkg/archive/archive.go
- vendor/github.com/docker/docker/pkg/archive/archive_linux.go
- vendor/github.com/docker/docker/pkg/archive/archive_other.go
- vendor/github.com/docker/docker/pkg/archive/archive_unix.go
- vendor/modules.txt
diffs:
- https://github.com/docker/cli/compare/v27.0.2...v27.0.3
- https://github.com/docker/docker/compare/v27.0.2...v27.0.3
> vendor: docker/docker, docker/cli v27.0.3

- client/llb/imagemetaresolver/resolver.go
- source/containerimage/source.go
Without this, a single `ResolveImageConfig` may emit many `remotes.docker.resolver.HTTPRequest` spans. These can be difficult to track and organize, especially if a single client performs multiple of them.
To make traces a bit easier to navigate, these are now grouped under one top-level span, instead of cluttering up the top-level.
For example, this now looks like:
The `HTTP GET` is also annoying, but this requires the contained change in https://github.com/containerd/containerd/pull/10231.
> otel: add wrapping "resolving" spans for ResolveImageConfig

- .github/dependabot.yml
- .github/labeler.yml
- .github/workflows/labeler.yml
This PR adds a [**PR Labeler**](https://github.com/marketplace/actions/labeler) action workflow. 
> Automatically label new pull requests based on the paths of files being changed or the branch name.
At present, this is primarily applying `area/*` labels but can be extended if it helps. Labels would be applied to all new or modified PRs after the workflow is commited to the default branch.
Changes for this PR mimic a [docker/buildx PR](https://github.com/docker/buildx/pull/2536) that introduced the same workflow for that project.
<details>
<summary>Current area/ labels</summary>
| Label | Action |
| --- | --- |
| `area/attestations` | None | 
| `area/cache` | None | 
| `area/ci` | None | 
| `area/cli` | Rename | 
| `area/containerd` | None | 
| `area/distributed` | None | 
| …
> Add PR labeler GHA workflow and configuration

- Dockerfile
relates to https://github.com/moby/buildkit/pull/5161#pullrequestreview-2194873729
alternative to and closes https://github.com/moby/buildkit/pull/5161
> dockerfile: use ADD for fetching sources

- .github/labeler.yml
follow-up https://github.com/moby/buildkit/pull/5192#issuecomment-2252956342
> chore(labeler): fix area/storage filter and update area/hack one

- frontend/dockerfile/docs/reference.md
> docs: dockerfile chmod variable interpolation

- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
See: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
Closes: https://github.com/moby/buildkit/issues/3553
Signed-off-by: Craig Andrews <candrews@integralblue.com>
> ci: add OCI image annotations to Dockerfile frontend images

- Dockerfile
- release notes: https://github.com/containerd/containerd/releases/tag/v1.7.20
- full diff: https://github.com/containerd/containerd/compare/v1.7.19...v1.7.20
> dockerfile: update containerd to v1.7.20

- hack/dockerfiles/govulncheck.Dockerfile
relates to https://github.com/moby/moby/pull/48311#discussion_r1711079896
> hack: ensure SARIF output has results field defined for govulncheck

- frontend/dockerfile/docs/reference.md
> docs: list supported algorithms for ADD --checksum

- Dockerfile
Provide a better error and a hint if building without a .git directory. This can happen when building directly from Git with skipping adding .git to build context.
Currently fails with
```
14.40 + /usr/bin/buildctl --version
14.40 Incorrect Usage. flag provided but not defined: -version
```
Could of course also make it just pass, but I think it is better to validate to make sure we don't accidentally break something and build without a valid version.
> Dockerfile: check .git directory available in build context

- cache/remotecache/v1/utils.go
- client/llb/exec.go
- solver/llbsolver/ops/exec.go
> [v0.15] cherry-picks for v0.15.2

- go.mod
- go.sum
- vendor/github.com/containerd/typeurl/v2/README.md
- vendor/github.com/containerd/typeurl/v2/types.go
- vendor/modules.txt
full diff: https://github.com/containerd/typeurl/compare/v2.1.1...v2.2.0
> vendor: github.com/containerd/typeurl/v2 v2.2.0

- go.mod
- go.sum
- vendor/modules.txt
> vendor: github.com/moby/sys/signal v0.7.1

- go.mod
- go.sum
- vendor/github.com/moby/sys/mountinfo/mounted_linux.go
- vendor/modules.txt
> vendor: github.com/moby/sys/mountinfo v0.7.2

- .github/labeler.yml
Neglected the all on the first round
> Fix windows label rules

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/github.com/docker/docker/api/types/container/hostconfig.go
- vendor/modules.txt
full diff:
- https://github.com/docker/cli/compare/v27.2.0...v27.2.1
- https://github.com/docker/docker/compare/v27.2.0...v27.2.1
> vendor: github.com/docker/docker v27.2.1

- frontend/dockerfile/dockerfile_test.go
> We have split the tests in batches across a number of PRs with the same title + suffix `(part X)`
As a follow up of #5027, we will be adding more tests in batches, to bring the coverage at par with Linux where applicable.
Tests completed in `frontend/dockerfile`:
Partially addresses #4485
> tests: frontend/dockerfile: update integration tests for windows/wcow (part 1)

- frontend/dockerfile/docs/rules/json-args-recommended.md
- frontend/dockerfile/linter/docs/JSONArgsRecommended.md
> docs: fix broken link to dockerfile reference

- .github/workflows/test-os.yml
- hack/Vagrantfile.freebsd
* backport of https://github.com/moby/buildkit/pull/5353
> [v0.16] ci: switch to ubuntu runner for freebsd job

- api/services/control/control_vtproto.pb.go
- api/types/worker_vtproto.pb.go
Merge conflict between https://github.com/moby/buildkit/pull/5359 and #5356
> fix merge conflict in generated proto

- Dockerfile
- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
- hack/dockerfiles/archutil.Dockerfile
- hack/dockerfiles/authors.Dockerfile
- hack/dockerfiles/doctoc.Dockerfile
- hack/dockerfiles/generated-files.Dockerfile
- hack/dockerfiles/lint.Dockerfile
- hack/dockerfiles/shfmt.Dockerfile
- hack/dockerfiles/vendor.Dockerfile
follow-up https://github.com/moby/buildkit/pull/5374#issuecomment-2389799117
This reverts commit c5de0b902007c6b008d05333d55ced98dddc4cdf.
> Revert "dockerfile: pin dockerfile frontend image"

- frontend/dockerfile/docs/reference.md
> docs: s/parent image/base image/

- Dockerfile
Reverts moby/buildkit#5443
- https://github.com/moby/buildkit/issues/5491
> Revert "Dockerfile: update runc binary to 1.2.1"

- go.mod
- go.sum
- vendor/google.golang.org/grpc/internal/transport/transport.go
- vendor/google.golang.org/grpc/version.go
- vendor/modules.txt
candidate fix for https://github.com/docker/build-push-action/issues/1256
> vendor: update grpc to v1.66.3

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli/config/credentials/file_store.go
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/github.com/docker/docker/api/types/types.go
- vendor/github.com/docker/docker/client/client.go
- vendor/github.com/docker/docker/libnetwork/internal/resolvconf/resolvconf.go
- vendor/modules.txt
full diff: https://github.com/docker/docker/compare/v27.3.1...v27.4.0-rc.2
full diff: https://github.com/docker/cli/compare/v27.3.1...v27.4.0-rc.2
> vendor: github.com/docker/docker, github.com/docker/cli v27.4.0-rc.2

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: fix duplicate keys for same arg in history line

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/containerd.service
- vendor/github.com/containerd/containerd/content/local/store.go
- vendor/github.com/containerd/containerd/remotes/docker/resolver.go
- vendor/github.com/containerd/containerd/remotes/docker/resolver_unix.go
- vendor/github.com/containerd/containerd/remotes/docker/resolver_windows.go
- vendor/modules.txt
> vendor: update containerd to v1.7.24

- cache/metadata/metadata.go
> [v0.17] Use view transaction for metadata read

- .github/workflows/.test.yml
- .github/workflows/buildkit.yml
- .github/workflows/buildx-image.yml
- .github/workflows/dockerd.yml
- .github/workflows/frontend.yml
- .github/workflows/test-os.yml
- .github/workflows/validate.yml
similar to https://github.com/moby/moby/pull/48982
> ci: use edge releases of buildx

- cache/refs.go
- util/system/path_test.go
fix some function name in comment
> chore: fix some function name in comment

- client/client_test.go
Follow up on the #5554 PR series. Enabling a number of previously skipped tests for Windows platform.
Count: 6
> NOTE: this is a top-to-bottom runthrough of all the tests
> in `client/client_test.go` that were straight-forward.
> The rest will require code changes, especially most needing
> `llb.AddMount` support on Windows. These will be addressed
> in separate follow-up PRs.
> tests: client: enable a batch of integration tests for wcow (pt.2)

- go.mod
- go.sum
- vendor/modules.txt
no changes in vendored files
full diff: https://github.com/docker/docker/compare/v27.4.0-rc.2...v27.4.0
no changes in vendored files
full diff: https://github.com/docker/cli/compare/v27.4.0-rc.2...v27.4.0
> vendor: github.com/docker/docker, github.com/docker/cli v27.4.0

- frontend/dockerfile/dockerfile_test.go
Add extra test coverage for checking that the step names created by dockerfile frontend are stable.
> dockerfile: add test for step names stability

- cmd/buildkitd/main.go
The `RunningInUserNS()` function already uses `sync.OnceValue` and the
environment variable is quick enough that we likely don't need to have
any syncing primitives associated with this code.
> buildkitd: remove sync.Once from isRootlessConfig

- go.mod
- go.sum
- vendor/github.com/prometheus/client_golang/prometheus/histogram.go
- vendor/modules.txt
- relates to https://github.com/moby/buildkit/pull/5618
> vendor: github.com/prometheus/client_golang v1.20.5

- go.mod
- go.sum
- vendor/github.com/tonistiigi/go-actions-cache/cache.go
- vendor/modules.txt
https://github.com/tonistiigi/go-actions-cache/compare/394979b8119e...017636a73805
> vendor: github.com/tonistiigi/go-actions-cache 017636a73805

- frontend/dockerfile/parser/directives.go
- frontend/dockerfile/parser/directives_test.go
- frontend/dockerfile/parser/parser.go
> dockerfile: fix syntax forwarding for files with BOM

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/Dockerfile
- vendor/github.com/tonistiigi/fsutil/docker-bake.hcl
- vendor/github.com/tonistiigi/fsutil/filter.go
- vendor/modules.txt
Brings in fix for error message for invalid patterns.
> vendor: update fsutil to b14e27f4

- .github/CONTRIBUTING.md
- hack/shell
- hack/test
- util/contentutil/refs.go
- util/testutil/integration/run.go
similar to https://github.com/moby/buildkit-bench/pull/59 to avoid rate-limiting.
> hack: mount docker config on gha

- .github/workflows/buildkit.yml
- cache/remotecache/gha/gha_test.go
- client/client_test.go
follow-up https://github.com/moby/buildkit/pull/5575#issuecomment-2538428741 and closes https://github.com/moby/buildkit/pull/5575
relates to https://github.com/moby/buildkit/pull/5650
> test: move gha cache to its own suite

- .github/workflows/test-os.yml
relates to https://github.com/moby/buildkit/actions/runs/13311769322/job/37176102952#step:6:20
> ci: install latest vagrant

- cache/remotecache/gha/gha.go
oversight from https://github.com/moby/buildkit/pull/5759
> cache(gha): fix missing user-agent for importer

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/copy/copy.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_linux.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_unix.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_windows.go
- vendor/github.com/tonistiigi/fsutil/copy/hardlink_windows.go
- vendor/github.com/tonistiigi/fsutil/diskwriter_windows.go
- vendor/github.com/tonistiigi/fsutil/docker-bake.hcl
- vendor/modules.txt
fixes https://github.com/moby/buildkit/issues/4945
> vendor: update fsutil to 13604323

- session/upload/uploadprovider/provider.go
Removes the recursive invocation of `Write` from the `Write`
implementation that chunked the bytes message writes.
This is better suited for a non-recursive algorithm. The recursive
version will create a new stackframe for each chunk which can be a
problem from a performance and stability perspective.
The code is now changed to a simple for loop that writes each chunk.
> uploadprovider: remove recursion from uploadprovider write code

- go.mod
- go.sum
- vendor/github.com/tonistiigi/go-actions-cache/cache_v2.go
- vendor/modules.txt
Mitigation for 503 side of https://github.com/moby/buildkit/issues/5790
> vendor: update action-cache with longer azure retries

- cache/remotecache/gha/gha_test.go
> gha: mitigate cache v2 flakiness

- Dockerfile
Should help with segmentation fault on libc-bin
> update binfmt to v9.2.2

- util/resolver/pool.go
The manifest requests to registry use buildkit user-agent, but the layer requests via ref.Unlazy were not.
> resolver: fix missing user-agent on layer requests

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/v2/client/client.go
- vendor/github.com/containerd/containerd/v2/core/images/image.go
- vendor/github.com/containerd/containerd/v2/core/images/mediatypes.go
- vendor/github.com/containerd/containerd/v2/core/remotes/handlers.go
- vendor/github.com/containerd/containerd/v2/pkg/oci/spec_opts.go
- vendor/github.com/containerd/containerd/v2/version/version.go
- vendor/modules.txt
See release notes https://github.com/containerd/containerd/releases/tag/v2.0.4
> Update containerd to v2.0.4

- cache/manager.go
- client/solve.go
- cmd/buildkitd/main_oci_worker.go
- go.mod
- solver/cachekey.go
- solver/jobs.go
- solver/llbsolver/cdidevices/manager.go
- worker/containerd/containerd.go
- worker/runc/runc.go
Moby already updated it so should be safe for us as well.
> go.mod: update minimum go version to go1.23

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli/config/config.go
- vendor/github.com/docker/docker/libnetwork/resolvconf/resolvconf.go
- vendor/github.com/docker/docker/pkg/archive/archive.go
- vendor/github.com/docker/docker/pkg/archive/archive_linux.go
- vendor/github.com/docker/docker/pkg/archive/archive_unix.go
- vendor/github.com/docker/docker/pkg/archive/archive_windows.go
- vendor/github.com/docker/docker/pkg/archive/changes.go
- vendor/github.com/docker/docker/pkg/archive/copy.go
- vendor/github.com/docker/docker/pkg/archive/time_nonwindows.go
- vendor/github.com/docker/docker/pkg/archive/wrap.go
- vendor/github.com/docker/docker/pkg/atomicwriter/atomicwriter.go
- vendor/github.com/docker/docker/pkg/chrootarchive/diff_unix.go
- vendor/modules.txt
full diff: https://github.com/docker/docker/compare/v28.0.1...v28.0.2
full diff: https://github.com/docker/cli/compare/v28.0.1...v28.0.2
> vendor: github.com/docker/docker, docker/cli v28.0.2

- cache/refs.go
Show layer extraction in the opentelemetry trace.
Follow-up: it seems there might be some minor issue with the non-optimal download/extract order of the blobs that this exposes. I'll investigate further later (edit: opened https://github.com/moby/buildkit/issues/5832).
> cache: add tracing spans for layer extraction

- .github/labeler.yml
https://github.com/moby/buildkit/issues?q=label%3Aarea%2Fcdi%20
> chore(labeler): area/cdi

- client/client_test.go
- go.mod
- go.sum
- vendor/github.com/tonistiigi/dchapes-mode/mode.go
- vendor/modules.txt
> file: fix X mode to be Linux-compatible

- README.md
- cache/remotecache/local/local.go
- cache/remotecache/registry/registry.go
- client/client_test.go
- frontend/dockerfile/dockerfile_test.go
> remotecache: enable image-manifest by default

- go.mod
- go.sum
- solver/llbsolver/file/unpack.go
- vendor/github.com/moby/go-archive/.gitattributes
- vendor/github.com/moby/go-archive/.gitignore
- vendor/github.com/moby/go-archive/.golangci.yml
- vendor/github.com/moby/go-archive/archive.go
- vendor/github.com/moby/go-archive/archive_unix.go
- vendor/github.com/moby/go-archive/archive_windows.go
- vendor/github.com/moby/go-archive/changes.go
- vendor/github.com/moby/go-archive/changes_linux.go
- vendor/github.com/moby/go-archive/chrootarchive/archive.go
- vendor/github.com/moby/go-archive/chrootarchive/diff_unix.go
- vendor/github.com/moby/go-archive/chrootarchive/diff_windows.go
- vendor/github.com/moby/go-archive/compression/compression.go
- vendor/github.com/moby/go-archive/compression/compression_detect.go
- vendor/github.com/moby/go-archive/copy.go
- vendor/github.com/moby/go-archive/dev_freebsd.go
- vendor/github.com/moby/go-archive/diff.go
- vendor/github.com/moby/go-archive/internal/mounttree/switchroot_linux.go
- vendor/github.com/moby/go-archive/tarheader/tarheader.go
- vendor/github.com/moby/go-archive/tarheader/tarheader_unix.go
- vendor/github.com/moby/go-archive/tarheader/tarheader_windows.go
- vendor/modules.txt
full diff: https://github.com/moby/go-archive/compare/21f3f3385ab7...v0.1.0
> vendor: github.com/moby/go-archive v0.1.0

- README.md
Improve documentation after https://github.com/moby/buildkit/pull/5920.
CC @tonistiigi
> Improve documentation of S3 authentication

- .github/workflows/test-os.yml
similar to https://github.com/docker/buildx/pull/3143
> ci: fix vagrant build

- control/control.go
> control: make sure sending nil cache options does not panic

- cmd/buildctl/common/common.go
- cmd/buildctl/common/common_test.go
- cmd/buildctl/main.go
- control/control.go
- docs/reference/buildctl.md
- frontend/dockerui/build.go
- frontend/dockerui/build_test.go
backport of:
* https://github.com/moby/buildkit/pull/5925
* https://github.com/moby/buildkit/pull/5941
* https://github.com/moby/buildkit/pull/5950
> [v0.21] cherry-picks for v0.21.1

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
addresses https://github.com/docker/buildx/issues/3166#issuecomment-2856725666
> dockerfile: make WORKDIR respect SOURCE_DATE_EPOCH

- util/progress/progressui/display.go
> progressui: fix panic on very small terminal

- source/git/identifier.go
- util/gitutil/git_ref.go
- util/gitutil/git_url.go
- util/gitutil/git_url_test.go
No substantial code change.
Non-fragment data can be added in this structure too.
- - -
Split from:
- #5974
> git url: rename GitURLFragment to GitURLOpts

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/send.go
- vendor/modules.txt
> vendor: update fsutil to master@586307ad452f

- frontend/dockerui/config.go
- solver/jobs.go
Shown on race detector.
Still race remaining in ExportTo() , described in https://github.com/moby/buildkit/issues/5005
> solver: fix some data races

- go.mod
- go.sum
- vendor/github.com/tonistiigi/go-actions-cache/Dockerfile
- vendor/github.com/tonistiigi/go-actions-cache/cache.go
- vendor/github.com/tonistiigi/go-actions-cache/cache_v2.go
- vendor/modules.txt
fixes https://github.com/docker/build-push-action/issues/1382
> vendor: github.com/tonistiigi/go-actions-cache 388a2ec8cdf8

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/v2/core/content/helpers.go
- vendor/github.com/containerd/containerd/v2/core/mount/mount_linux.go
- vendor/github.com/containerd/containerd/v2/core/remotes/docker/errcode.go
- vendor/github.com/containerd/containerd/v2/core/remotes/docker/fetcher.go
- vendor/github.com/containerd/containerd/v2/core/remotes/docker/pusher.go
- vendor/github.com/containerd/containerd/v2/core/remotes/docker/resolver.go
- vendor/github.com/containerd/containerd/v2/core/remotes/errors/errors.go
- vendor/github.com/containerd/containerd/v2/core/transfer/proxy/transfer.go
- vendor/github.com/containerd/containerd/v2/core/unpack/unpacker.go
- vendor/github.com/containerd/containerd/v2/version/version.go
- vendor/modules.txt
~test https://github.com/containerd/containerd/pull/11998~
cherry-pick #6040
fix #6036
fix #6033
> [v0.23] Update containerd to v2.1.3

- .github/workflows/validate.yml
similar to https://github.com/docker/buildx/pull/3301
> ci(validate): use matrix subaction

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
This is to show a better error than the unprocessed value failing somewhere later in the build.
Implements suggestion from https://github.com/moby/moby/issues/34482#issuecomment-3201276646
> dockerfile: show error when args used in COPY --from

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli/config/configfile/file.go
- vendor/modules.txt
full diff: https://github.com/docker/cli/compare/v28.3.0...v28.3.3
> vendor: github.com/docker/cli v28.3.3

- go.mod
- go.sum
- vendor/github.com/cpuguy83/go-md2man/v2/md2man/md2man.go
- vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
- vendor/modules.txt
full diff: https://github.com/urfave/cli/compare/v1.22.16...v1.22.17
> vendor: github.com/urfave/cli v1.22.17

- frontend/dockerfile/builder/caps.go
- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
backport of:
* https://github.com/moby/buildkit/pull/6183
> [v0.24] cherry-picks for v0.24.0

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli/config/types/authconfig.go
- vendor/modules.txt
full diff: https://github.com/docker/cli/compare/v28.3.3...v28.4.0
> vendor: github.com/docker/cli v28.4.0

- client/client_test.go
- exporter/containerimage/writer.go
relates to https://github.com/moby/buildkit/issues/6171#issuecomment-3258373944
> fix subject for oci artifact of attestation manifest

- README.md
https://github.com/Azure/dalec
> Added Dalec frontend to README.md

- frontend/dockerfile/docs/reference.md
Resolves https://github.com/docker/docs/issues/23350.
> better demonstrate benefits of using heredocs in shell-form

- util/grpcerrors/grpcerrors.go
> Fix grpcerrors.AsGRPCStatus to ignore OK and Unknown status codes for

- frontend/dockerfile/dockerfile_provenance_test.go
> [v0.25] dockerfile: fix customenv test for dockerd
