- .github/workflows/test-os.yml
- hack/Vagrantfile.freebsd13
follow-up https://github.com/moby/buildkit/pull/4180
> ci(test-os): cross build freebsd binaries using the Dockerfile

- cache/blobs_nolinux.go
Looks like the CI have been skipping gofmt check for non-linux Go files.
> `go fmt cache/blobs_nolinux.go`

- cache/refs.go
I saw a panic while using the stargz snapshotter caused by the labels being nil.
My wild-guess as to why labels is nil is that the stargz snapshotter could not find a bolt bucket:
https://github.com/containerd/containerd/blob/b0a7f08aa7490a3d43787b9f2b444e4b20b96f8c/metadata/boltutil/helpers.go#L53
> fix: check snapshot labels to avoid panic

- README.md
- cache/blobs.go
- cache/manager_test.go
- docs/build-repro.md
- exporter/containerimage/export.go
- exporter/containerimage/exptypes/keys.go
- exporter/containerimage/opts.go
- exporter/containerimage/writer.go
- frontend/dockerfile/dockerfile_test.go
- util/contentutil/storewithprovider.go
- util/converter/converter.go
- util/converter/tarconverter/tarconverter.go
- util/converter/tarconverter/tarconverter_test.go
`rewrite-timestamp` rewrites timestamps in layers for reproducible builds.
When a layer is rewritten, an annotation `buildkit/rewritten-epoch=<INT64>` is set to the layer.
Example:
```
buildctl build
--frontend dockerfile.v0 \
--opt build-arg:SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} \
--output type=oci,dest=dest.tar,rewrite-timestamp=true \
...
```
Alternative to:
- #3560
- - -
With this commit, the following workarounds mentioned in [`docs/build-repro.md`](https://github.com/moby/buildkit/blob/v0.11.2/docs/build-repro.md#caveats) are no longer needed for reproducible builds:
> ```dockerfile
> # Limit the timestamp upper bound to SOURCE_DATE_EPOCH.
> # Workaround for https://github.com/moby/buildkit/issues/3180
> ARG SOURCE_DATE_EPOCH
> RUN find $( ls / | grep -E -v "^(dev|mnt|proc|sys)$" ) …
```
> exporter/containerimage: new option: rewrite-timestamp (Apply `SOURCE_DATE_EPOCH` to file timestamps)

- hack/Vagrantfile.freebsd13
related to: https://github.com/moby/buildkit/actions/runs/6194835878/job/16818500910#step:5:65
Vagrant VM can take some time to boot. Increase to 10m (default 5m).
> ci(test-os): increase vm boot time to 10m

- cmd/buildctl/build.go
- cmd/buildctl/build/registryauthtlscontext.go
- cmd/buildctl/build/registryauthtlscontext_test.go
- docs/reference/buildctl.md
- go.mod
- session/auth/authprovider/authconfig.go
- session/auth/authprovider/authprovider.go
- session/auth/authprovider/authprovider_test.go
Add configured TLS certificate to trust store when making calls to registry auth
> buildctl: Add configured TLS certificate to trust store when making calls to registry auth

- docs/buildkitd.toml.md
This reverts commit fd8e32debced4a82e57094fb3bc2e471f8faff34. gckeepstorage is indeed in byte units.
Closes: #2922
> Revert "Update buildkitd.toml.md"

- docs/buildkitd.toml.md
Follow up from https://github.com/moby/buildkit/pull/4264
See:
https://github.com/moby/buildkit/blob/f77e5212cdeb35111e58b8895bb047bea8eb1ee0/cmd/buildkitd/config/config.go#L63-L67
Maybe at some point, we should auto-generate the default config from the code? If that sounds good, we could open a beginner-friendly issue to note that.
> docs: note that gckeepstorage can take different types

- cache/blobs.go
- util/compression/compression.go
- util/compression/estargz.go
- util/compression/gzip.go
- util/compression/nydus.go
- util/compression/uncompressed.go
- util/compression/zstd.go
Fixes https://github.com/moby/buildkit/pull/4210#discussion_r1322863998
> containerd-rootless test uses containerd worker + native snapshotter. In this configuration, buildkitd relies on containred's differ via containerd client that doesn't support changing the compression level. So this doesn't produce the difference for the created blob. 
With containerd worker + non-overlayfs-snapshotter configuration, we've been using containerd's differ via containerd client but the compression level can't be applied in this configuration. This commit fixes this issue by compressing gzip with customized compression level on BuildKit't differ instead of containerd's differ. Uncompressed blobs and gzip blobs without customized compression level are still handled by containerd's differ.
> diff: gzip with custom level should be compressed by BuildKit's differ

- solver/llbsolver/ops/exec.go
- solver/llbsolver/ops/exec_test.go
Correctly set the content based selector when multiple bind mounts refer
to the same source. Previously, a selector that referred to the root
filesystem would be ignored. This is because a blank selector refers to
the root filesystem.
When two bind mounts referred to the same dependency, one mount would
add a selector while the other would be skipped. This caused the cache
key to be only computed based on the more narrow filesystem which caused
erroneous cache hits.
Now, the creation of the selector includes the root filesystem for
consideration. It fills in `/` as the selector and then removes it later
so that we don't narrow the selection in an invalid way.
Fixes #4123.
> solver: correctly set the content selector with multiple bind mounts references

- docs/rootless.md
- examples/eksctl/bottlerocket.yaml
Bottlerocket favors API configurations instead of manual calls to configure sysctl knobs
> docs/rootless: use Bottlerocket's API configurations

- cache/filelist.go
- cache/manager.go
- cache/refs.go
- client/client_test.go
fixes #3809 
What's happening is that two builds interact with layer that has same uncompressed digest and different compressed digest. In that case we detect this and "link" the records so they will use the same snapshot and avoid duplicates. https://github.com/moby/buildkit/blob/master/cache/manager.go#L218 This means that because of lazy references the blob saved with `getBlob()` has not been pulled while snapshot exists.
In the #3809 problem arises when `Filelist` is called because of the SBOM attestation https://github.com/moby/buildkit/blob/3d44ec218b0d9f6d42182654b0662ffa5f38de5f/cache/filelist.go#L37-L50 . The "not found" error happens inside the `ReaderAt` because it can't find the blob. While there is an `Unlazy` step before this call to make sure we have local data, the current …
> cache: don't skip unlazy without blob check

- Dockerfile
- docs/dev/README.md
- docs/dev/remote-debugging.md
- hack/images
- hack/shell
This introduces a debug variant of the buildkit docker image. This
version builds the binary in a way that disables optimizations so that
it can be run properly with delve. It also builds and installs delve
only in the debug variant of the image.
For the debug variant, a shim `buildkitd` binary is created that execs
with the proper arguments to delve and forwards to the underlying
binary.
In order to use this version, you can set `--build-arg BUILD_VARIANT=debug`
and it will pick up this version of the image. The default is `release`.
The debug variant is only available for linux and the variant is ignored
for any other target os. Most other targets don't support `buildkitd` at
all so the only os this affects is freebsd.
delve is exposed on port 5000 by default and this can be accessed …
> dockerfile: introduce a debug variant for the buildkit docker image

- hack/images
- hack/shell
`-ne` comparison errors `./hack/shell: line 10: [: : integer expression expected` on empty value. As we just need to pass the env as build-arg, no extra variable is needed.
> hack: update BUILDKIT_DEBUG handling

- util/testutil/integration/run.go
- util/testutil/integration/sandbox.go
- util/testutil/workers/dockerd.go
- util/testutil/workers/util.go
follow-up https://github.com/docker/buildx/pull/2035#discussion_r1323764389
related to https://github.com/moby/buildkit/pull/4101
Set otel socket path in integration tests using buildkit config instead of setting the `otel-socket-path` flag to avoid breaking change with older buildkit version.
tested in https://github.com/docker/buildx/pull/2060
> integration: set otel socket path through buildkit config

- .github/workflows/.test.yml
Reported by @jedevc 
This is a regression from https://github.com/moby/buildkit/pull/4048: https://github.com/moby/buildkit/actions/runs/6337159614/job/17211754423?pr=4288#step:8:1478
```
=== Failed
=== FAIL: client TestNydusIntegration/TestBuildExportNydusWithHybrid/worker=containerd (6.35s)
client_nydus_test.go:79: 
Error Trace:	/src/client/client_nydus_test.go:79
/src/client/client_nydus_test.go:133
/src/util/testutil/integration/run.go:91
/src/util/testutil/integration/run.go:205
Error:      	Received unexpected error:
unsupported compression type nydus
github.com/moby/buildkit/util/stack.Enable
/src/util/stack/stack.go:77
github.com/moby/buildkit/util/grpcerrors.FromGRPC
/src/util/grpcerrors/grpcerrors.go:198
github.com/moby/buildkit/util/grpcerrors.UnaryClientInterceptor …
```
> ci(test): fix unhandled buildkitd tags

- util/resolver/resolver.go
- related to: https://github.com/moby/moby/pull/45992
- related to: https://github.com/docker/buildx/issues/1642
Mirrors in `RegistryConfig.Mirrors` can be specified using a full URL (schema, trailing slashes) but registries in the input map are keyed by their hostname.
Previous code used the mirror URL as key which resulted in an empty `RegistryConfig` being passed to the `fillInsecureOpts` function and didn't set the insecure options.
Use Host part of the parsed registry as a key instead.
> util/resolver: Fix insecure mirrors

- util/resolver/resolver.go
- backport: https://github.com/moby/buildkit/pull/4293
Mirrors in `RegistryConfig.Mirrors` can be specified using a full URL (schema, trailing slashes) but registries in the input map are keyed by their hostname.
Previous code used the mirror URL as key which resulted in an empty `RegistryConfig` being passed to the `fillInsecureOpts` function and didn't set the insecure options.
Use Host part of the parsed registry as a key instead.
(cherry picked from commit ec655579da0192d785bf9c99e4a9946deee4c555)
> [0.12 backport] util/resolver: Fix insecure mirrors

- README.md
- util/progress/progressui/display.go
- util/progress/progressui/init.go
The output window was previously hard-coded to a height of 6; this patch makes it configurable at run-time by setting the BUILDKIT_TERMHEIGHT environment variable.
> Make output window configurable: BUILDKIT_TERMHEIGHT

- cache/util/fsutil.go
Follow-up to #3990, but this time for `StatFile` as well.
> This case is a little bit trickier, since it is wrapped by `errors.WithStack` as well, but we can use `errors.Cause` to extract the original error to modify it.
Messages returned by `fsutil.Stat` are guaranteed to return a `PathError` wrapped by a stack trace (since it calls `os.Lstat`). However, as these error messages are printed, they include the temporary directory for the mounted reference which is not useful to the caller.
On an error, we can restore the filename in the `PathError` to the requested filename, as also seen in `os.DirFS`.
> gateway: restore original filename in StatFile error message

- util/resolver/resolver.go
If both Insecure and PlainHTTP is requested for the host, use a
transport that falls back to HTTP in case of an HTTP request to a HTTPS
client error.
This also changes the order - before that an HTTP connection was
attempted first. Now an HTTPS connection with insecure TLS check will be
attempted first and will only fallback to HTTP if the former fails.
This fixes push to an insecure HTTPS-only registry.
> util/resolver: Perform Insecure HTTPS + HTTP fallback in one `docker.RegistryHost`

- executor/oci/spec.go
- executor/oci/spec_freebsd.go
- executor/oci/spec_linux.go
- executor/oci/spec_windows.go
Possibly fixes #4108.
Note that I have no idea what I'm doing; I'm basing the new stat call on what the tests in #4003 are doing (on the assumption that if it is not compatible with the test, it was probably what broke my use cases too).  Any suggestions on what to do instead (or even just PRs that replace this one) very welcome.
> Don't support cgroupns on cgroups v1

- util/imageutil/config.go
- util/imageutil/config_test.go
Before this change, all platforms that loosely match the provided platform will be fetched even though we only care about 1 of them. As an example when linux/amd64 is requested it will also fetch linux/386 because it is a compatible architecture.
This means extra round trips to the registry, potentially even for content that doesn't exist in the remote.
This is especially a problem when resolve mode is prefer-local because we'll have the index locally but most likely only one manifest. In this case we'll end up reaching out to the registry to fetch the other manifests unncessarily.
With this change instead of fetching all matching platforms it chooses only the best matching platform.
Related: https://github.com/moby/moby/issues/46584
> ResolveImageConfig: Only fetch best matching config

- client/client.go
- client/llb/sourcemap.go
- cmd/buildctl/common/common.go
- cmd/buildkitd/main.go
- control/control.go
- executor/oci/spec.go
- executor/oci/spec_unix.go
- executor/oci/spec_windows.go
- frontend/dockerfile/dockerfile_provenance_test.go
- frontend/dockerfile/dockerfile_test.go
- solver/bboltcachestorage/storage.go
- solver/llbsolver/provenance.go
- source/http/httpsource.go
- util/imageutil/config.go
- util/imageutil/config_test.go
- util/pull/pullprogress/progress.go
- worker/base/worker.go
See https://github.com/moby/buildkit/pull/4157#issuecomment-1745150754 - looks like we have 2 relatively nasty known issues in v0.12.2 that users have encountered (including a panic):
- https://github.com/moby/buildkit/pull/4200
- https://github.com/moby/buildkit/pull/4157
- https://github.com/moby/buildkit/pull/4293 (already cherry-picked in https://github.com/moby/buildkit/pull/4297)
And some more minor issues with a relatively low foot-print that would benefit from making it to a release:
- https://github.com/moby/buildkit/pull/4190 (not a clean cherry-pick, since https://github.com/moby/buildkit/pull/4093 refactored the number of `Tmpdir` returns)
- https://github.com/moby/buildkit/pull/4183
- https://github.com/moby/buildkit/pull/4185
- https://github.com/moby/buildkit/pull/4189
- …
> [v0.12] Cherry-picks for v0.12.3

- solver/cachemanager.go
If any of the `Load()` calls return an error, such as `not found`; then the `rres` pointer might be nil, which causes the deferred error message to panic.
> solver: protect against nil rres upon errors

- README.md
Unikraft enables users to build unikernels using BuildKit.
It allows builds to be decoupled from the dependencies on the underlying host machine.
> Add Unikraft to the list of BuildKit users

- Dockerfile
- relates to https://github.com/moby/buildkit/pull/4315
full diff: https://github.com/containerd/containerd/compare/v1.7.2...v1.7.7
> Dockerfile: update containerd binary to v1.7.7

- README.md
Since 23.0, we have used Buildx as the default `docker build` implementation, which in turn uses the full BuildKit gRPC API.
> README: BuildKit is now default in the Engine

- .github/workflows/docs-upstream.yml
> ci: fix docs upstream validation workflow

- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
- docker-bake.hcl
follow-up https://github.com/moby/buildkit/pull/4332#issuecomment-1765336499
related to https://github.com/moby/buildkit/issues/4316
> chore: temporarily disable riscv64 build

- cache/remotecache/inline/inline.go
- client/client_test.go
- client/ociindex/ociindex.go
- frontend/dockerfile/dockerfile_provenance_test.go
- frontend/dockerfile/dockerfile_test.go
- go.mod
- go.sum
- vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
- vendor/modules.txt
Broken out of #4331 since the actual change there may not be the right solution, and landing this lets me rebase that PR down to the essentials before possibly archiving it.
Changes per https://github.com/opencontainers/image-spec/compare/v1.1.0-rc3...v1.1.0-rc5. None of the changes required corresponding changes in the BuildKit source.
I took the opportunity to replace a bunch of existing strings with newly-added constants from image-spec. (If this is a concern, it'd be trivial to drop or split into a different commit)
The original motivation for updating image-spec was to get access to `DescriptorEmptyJSON`, which was renamed from `ScratchDescriptor` and had its media type changed. BuildKit had no existing users of this value, or the related media types.
Also, some other small fixes …
> Update opencontainers/image-spec to v1.1.0-rc5

- cache/remotecache/export.go
- client/client_test.go
These happen when a container image is built using only metadata actions, and hence does not generate any filesystem changes.
Such a degenerate cache is not interesting, and some OCI registries reject OCI images with no layers.
Specifically, this only affects the `registry` and `local` exporters.
The `inline` exporter already early-outs in this case with the same warning, and the `gha`, `s3`, and `azblob` exporters are unchanged.
This should finally resolve the last vestiges of negative user experience in https://github.com/aws/containers-roadmap/issues/876.
> Skip export of caches with no layers to OCI structures

- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
- docker-bake.hcl
backports of:
* https://github.com/moby/buildkit/pull/4344
> [0.12] cherry-picks 0.12.3 take 2

- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
- Dockerfile
- docker-bake.hcl
fixes #4316 
closes #4332
Related to https://github.com/moby/buildkit/issues/4316#issuecomment-1767760699, this is an issue with `ld` and not `musl`. Needs to update [xx to 1.3.0](https://github.com/tonistiigi/xx/releases/tag/v1.3.0) which includes update of binutils to 2.41 to fix this issue.
> fix riscv64 build

- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
- Dockerfile
- docker-bake.hcl
backport of:
* https://github.com/moby/buildkit/pull/4348
> [0.12 backport] fix riscv64 build

- util/resolver/resolver.go
- backport: https://github.com/moby/buildkit/pull/4299
If both Insecure and PlainHTTP is requested for the host, use a
transport that falls back to HTTP in case of an HTTP request to a HTTPS
client error.
This also changes the order - before that an HTTP connection was
attempted first. Now an HTTPS connection with insecure TLS check will be
attempted first and will only fallback to HTTP if the former fails.
This fixes push to an insecure HTTPS-only registry.
> [0.12 backport] util/resolver: Perform Insecure HTTPS + HTTP fallback in one `docker.RegistryHost`

- cache/manager.go
After loading snapshot failed  in the func init(), the compression variants lease was not cleaned, resulting in cache data not being garbage collected；
After run `buildctl prune --all`，there are still hundreds of GB of data remaining in the  /var/lib/buildkit/runc-overlayfs/content/blobs/sha256/ directory；
the error info：
level=debug msg="could not load snapshot zy9eqBpcso79doeajneev8iii: not found\n..."
Signed-off-by: fanjiyun.fjy <fanjiyun.fjy@alibaba-inc.com>
> cache: fix cache leak

- cmd/buildkitd/debug.go
The debug address handler was not serving because of the double listen. Regression from https://github.com/moby/buildkit/pull/3650/files#diff-6e528092fd700dc985cf83b9fe8ae2bed31a01bb8abfabf9c3d3a9007407a5bd
> buildkitd: fix debug handler listener

- hack/Vagrantfile.freebsd13
Related to https://github.com/moby/buildkit/actions/runs/6593087661/job/17915050926?pr=4362#step:5:48
Same as https://github.com/moby/buildkit/pull/4235. Hopefully this is enough now.
> ci(test-os): increase vm boot time to 15m

- solver/cachekey.go
- solver/combinedcache.go
- solver/exporter.go
fix https://github.com/moby/buildkit/issues/2458
fix #4305
I'm not super happy with this as ideally, we could guarantee the immutability of the cache keys before export and do a better job of avoiding leaks between `cacheManager` only used by specific build requests.
This adds some missing locks to the changing `ids` map. The rest of the places accessing `ids` should have exclusive access to the struct already. 
For the export path and `combinedManager` I make a copy of the map before to avoid holding the lock for the whole iteration and make sure no new cache managers are added in the middle of the function. Moving other (non `ids`) `e.k` accesses to local `k` variable is just for better readability/consitency and does not fix any race case.
@jedevc
> solver: fix possible concurrent map access on cache export

- cache/util/fsutil.go
- client/solve.go
- exporter/local/export.go
- exporter/local/fs.go
- go.mod
- go.sum
- session/filesync/filesync.go
- session/filesync/filesync_test.go
- util/staticfs/merge.go
- util/staticfs/merge_test.go
- util/staticfs/static.go
- util/staticfs/static_test.go
- vendor/github.com/tonistiigi/fsutil/filter.go
- vendor/github.com/tonistiigi/fsutil/followlinks.go
- vendor/github.com/tonistiigi/fsutil/fs.go
- vendor/github.com/tonistiigi/fsutil/send.go
- vendor/github.com/tonistiigi/fsutil/tarwriter.go
- vendor/modules.txt
This patch modifies the function signature of the FSSync provider to take an fsutil.FS instead of a simple raw path resolved to the client's root filesystem, and follows this through to allow specifying fsutil.FS objects on the SolveOpt itself.
Internally, we were already creating an fsutil.FS to Send to the buildkit server, however, this abstraction didn't reach the session attachable parameters, so we couldn't provide our own custom FS implementation.
The rationale behind this change is to allow providing more abstract custom filesystem implementations to a BuildKit client. This way, we can start to build from filesystems that might not be on disk - for example, we could use our Static filesystem implementation in tests to prevent creating lots of temporary directories, or we could use …
> client: modify SolveOpt to take fsutil.FS objects

- solver/llbsolver/history.go
The events for currently active builds were sent through pubsub channel instead of directly to the current request, like it was done for completed builds for example.
This meant that if there were more active builds running than the pubsub channel buffer (32), the sends will block. Because the history API mutex is held in this process, it will eventually block the requests for builds that try to update their history records.
> llbsolver: fix possible deadlock in history listen

- solver/edge.go
- solver/jobs.go
fix #4278
"Merged edges" is an optimization in the solve graph where two different active LLB edges can be combined into one after cache key computation finds that they generated equivalent cache chain.
In that case, one edge is released and is set to point to another. The reference count for the second one is increased.
An issue was discovered where an edge that was already pointing to another edge became a target to the third one. The current implementation did not handle the case where an edge that already had a different target itself became a target edge as well. This resulted in an inconsistent graph state where edges that were thought to be released could get scheduled again.
Instead of setting the same edge value to two different maps, the new logic is to chain the edges into a …
> solver: fix issue with double merged edges

- README.md
The link of `BuildKit-only Dockerfile features` is broken if viewing from the [repo homepage](https://github.com/moby/buildkit). This PR fixes this issue.
> Readme: Fix broken link

- frontend/dockerfile/dockerfile2llb/convert.go
This allows callers to pass in a non-default build context without creating and passing in a dockerui.Client.
> dockerfile2llb: Add a MainContext option to ConvertOpt

- cmd/buildkitd/main.go
When running buildkitd in a rootless environment but as root, buildkitd
misinterprets how it is being run and loads the config file from the
home directory instead of the global location in `/etc/buildkitd`.
This happens when buildkit is being run in docker and docker itself is
being run as rootless. The buildkit daemon sees the user remapping and
assumes that the remapping belongs to itself rather than to docker.
This causes it to load the wrong configuration file as buildkitd is
still being run as "root" but a remapped root that docker created.
Related to docker/buildx#2092.
> buildkitd: use default config file location when run as root in rootless

- .github/workflows/test-os.yml
follow-up https://github.com/moby/buildkit/pull/4368#issuecomment-1779186247
Switch to `macos-13` runner which looks reliable after several runs. Vagrant and VirtualBox are not pre-installed on this runner so needs an extra step to install them.
> ci(test-os): fix freebsd job

- executor/oci/user.go
- go.mod
- go.sum
- solver/llbsolver/ops/user_linux.go
- vendor/github.com/moby/sys/user/LICENSE
- vendor/github.com/moby/sys/user/lookup_unix.go
- vendor/github.com/moby/sys/user/user.go
- vendor/github.com/moby/sys/user/user_fuzzer.go
- vendor/modules.txt
relates to:
- https://github.com/moby/moby/pull/46711
- https://github.com/opencontainers/runc/issues/3998
- https://github.com/opencontainers/runc/pull/4017
- https://github.com/containerd/containerd/pull/9114
- https://github.com/moby/sys/pull/134
This migrates uses of github.com/opencontainers/runc/libcontainer/user to the new github.com/moby/sys/user module, which was extracted from runc at commit [opencontainers/runc@a3a0ec4].
This is the initial release of the module, which is a straight copy, but some changes may be made in the next release (such as fixing camel-casing in some fields and functions (Uid -> UID).
[opencontainers/runc@a3a0ec4]: https://github.com/opencontainers/runc/commit/a3a0ec48c464fe6458d2ba067f6707c027e5384e
> migrate to github.com/moby/sys/user

- docker-bake.hcl
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_parents_test.go
- frontend/dockerfile/docs/reference.md
- frontend/dockerfile/instructions/commands.go
- frontend/dockerfile/instructions/parse.go
- frontend/dockerfile/instructions/parse_parents.go
- frontend/dockerfile/release/labs/tags
`.parents_test.sh`:
```sh
#!/usr/bin/env sh
set -e
TMP_DIR=$(mktemp -dt parents_test.XXXXXXXX)
echo "Created \"$TMP_DIR\""
trap "echo \"Removing \\\"$TMP_DIR\\\"\"; rm -rf \"$TMP_DIR\"" EXIT
mkdir -p $TMP_DIR/src/dir1
mkdir -p $TMP_DIR/src/dir2/subdir2
touch $TMP_DIR/src/dir1/file1-1.py
touch $TMP_DIR/src/dir1/file1-2.go
touch $TMP_DIR/src/dir2/subdir2/file2-1.go
touch $TMP_DIR/src/dir2/subdir2/file2-2.js
touch $TMP_DIR/src/dir2/subdir2/file2-3.go
cat << DOCKERFILE > $TMP_DIR/dockerfile
FROM scratch
COPY ./src/*/*/*.go ./dst1/
COPY --parents ./src/*/*/*.go ./dst2/
CMD ["echo", "hello-world"]
DOCKERFILE
echo "======================================================="
SOCKET_DIR=$(realpath $(dirname $0))/.tmp
mkdir -p $SOCKET_DIR
sudo buildctl \
--addr=unix://$SOCKET_DIR/buildkitd.socket \ …
```
> Add --parents opt-in flag for ADD/COPY (labs)

- frontend/dockerfile/dockerfile2llb/convert.go
Hi,
The build target is not quoted and it makes it difficult for some persons to see what the problem is.
By quoting it we emphasize that the target name is variable.
Related to https://github.com/moby/moby/pull/46754
Thanks and cheers !
> frontend/dockerfile/dockerfile2llb: errmsg: quote build target

- README.md
Follow-up https://github.com/moby/buildkit/pull/4369, fixes https://github.com/moby/buildkit/issues/4140.
For users looking for Dockerfile-only features, it feels reasonable to just point people to the docker docs, instead of using a relative link.
Relative links in NOTE blocks still look broken, but it doesn't seem apparent that GitHub will fix it anytime soon :cry:
> docs: retarget dockerfile reference link

- snapshot/merge.go
In mergeSnapshotter.Usage(), if a snapshot Stat returned labels that are unrelated to MergeUsage, the actual Usage() was not called, and it returned empty usage.
So add relevant conditions in mergeUsageOf() to ensure that Usage() is called if the labels are unrelated to mergeUsage.
> fix usage loss for snapshots with labels in MergeSnapshotter

- client/llb/marshal.go
- client/llb/state.go
- exporter/containerimage/writer.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/image.go
- frontend/dockerui/build.go
- solver/llbsolver/ops/exec.go
- solver/llbsolver/ops/exec_binfmt.go
- solver/llbsolver/provenance/capture.go
- solver/llbsolver/vertex.go
- solver/pb/ops.proto
- solver/pb/platform.go
- source/containerimage/pull.go
- source/containerimage/source.go
This fixes a bunch of places where these OCI fields were being stripped or lost during processing.
It hasn't been visible until now as they are `nil` on all Linux platforms as far as I know, but WCOW needs them to select the appropriate image for `FROM` from a manifest list, and also probably in other places that I haven't tested.
~~Draft because of one TODO to be completed/improved, and because I suspect this will warrant discussion. I'd also like to see if CI passes, in case I'm wrong about this not affecting Linux at all, e.g., unexpected digest shifts.~~
> Include OS version and features in OCI platforms

- frontend/dockerfile/docs/reference.md
> docs: add a note that healthcheck --start-interval requires docker 25.0

- source/git/source.go
It's possible for a git url to contain encoded credentials - even though this practice is not recommended. For safety, we attempt to censor the credentials before putting them into cache descriptions and error messages.
However, we were previously missing one of these, and we would put an uncensored git url into the git checkout snapshot cache ref description.
I've manually checked all other usages of `gs.Src.Remote`, and it looks like this is the only case of `urlutil.RedactCredentials` missing.
> git: add missing RedactCredentials call in cache description

- solver/jobs.go
- util/progress/multiwriter.go
fixes #4330
~depends on #4285~
When different LLB vertexes (eg. parallel requests referencing
local sources from different sessions) generate the same cache keys
during solve, they are merged together into a single operation.
Currently, when this happened, the progress for the vertex that
was dropped got lost. This fixes this case by adding the
progressWriter of the redirected vertex as a target to the
source one.
This should also work with multiple levels of merged edges,
just multiple nested multiwriters as well.
> solver: fix printing progress messages after merged edges

- .github/workflows/buildkit.yml
- Dockerfile
follow-up https://github.com/moby/buildkit/pull/4356#issuecomment-1772463447
Our pipeline run tests regardless if binaries are broken. This adds smoke test to built binaries (runc, buildctl, buildkitd) and also makes test job depends on binaries one so we avoid unnecessary build queues.
> dockerfile: smoke tests for binaries

- frontend/dockerfile/docs/reference.md
In the Dockerfile reference ([1](https://docs.docker.com/engine/reference/builder/#run---networkhost), [2](https://docs.docker.com/engine/reference/builder/#run---securityinsecure), [3](https://docs.docker.com/engine/reference/builder/#arg)), the warning callouts were not rendered as intended, as shown in the picture below. Note the background color, the "i" icon and the trailing class attribute (`{:.warning}`):
Here is how they should appear instead (content not relevant to the issue):
The PR updates the class attribute to match [the Formatting Guide](https://docs.docker.com/contribute/components/call-outs/).
(Note: this is a redo of PR #4416, which I forgot to sign the commit)
> docs: Fix formatting for warning callouts

- session/filesync/diffcopy.go
- session/grpc.go
- session/upload/uploadprovider/provider.go
When exporting tar stream (with SBOM) it is possible to hit grpc message size limits atm. While we raise the limits to 16MB for grpc control API, we don't currently do the same for the session API.
This can be reproduced with:
```
FROM laurentgoderre689/tar-too-big
RUN echo "Hello World"
```
```
docker buildx b . --platform linux/amd64 -t blah --sbom=true --provenance=true -o type=tar,dest=tar.tar
```
The first commit makes it so that the tar producer never sends chunks bigger than 3MB in a single message.
The second commit raises the limits on the client side to match control API. Only one of the fixes is needed to fix the issue in the reproducer. The second commit is for consistency and to fix the issue in case a new client accesses the old daemon.
The third commit is for …
> session: fix grpc message size limits for tar streams

- hack/Vagrantfile.freebsd13
related to https://github.com/moby/buildkit/actions/runs/6811552818/job/18522186374#step:8:27
> ci(test-os): enable SSH keep alive in vagrant vm

- .github/workflows/validate.yml
- .golangci.yml
- docker-bake.hcl
- hack/dockerfiles/lint.Dockerfile
follow-up https://github.com/moby/buildkit/pull/4261#discussion_r1387369887
> enable golangci-lint for supported platforms

- cache/manager.go
Avoid keeping the cache manager lock for too long. Note that prune is already batched based on deletion criteria and when items become releaseable. This adds extra limit to make sure it never gets very large.
Ref #4401
> cache: set max batch size limit to prune

- cmd/buildkitd/config/config.go
- cmd/buildkitd/config/load_test.go
- cmd/buildkitd/main_containerd_worker.go
- docs/buildkitd.toml.md
- executor/containerdexecutor/executor.go
- executor/containerdexecutor/executor_unix.go
- executor/containerdexecutor/executor_windows.go
Follow-up to https://github.com/moby/buildkit/pull/4279
[Like CRI](https://github.com/containerd/containerd/blob/de55dfc0f184aa6ed19de4dc02a3a4bae3476c88/pkg/cri/config/config.go#L46-L49), we should support custom shim paths. We can just add this as a new config field `path` under the runtime object.
While `name` can be either the name of a custom shim (from which a path is derived), or a path itself, if configured as a path, no options can be provided - this is because to derive the type for the options struct, we need the name to be a member of a well-known set ([currently runc and hcs](https://github.com/moby/buildkit/blob/25e9aa8d396f706a6f1e7d6c98ae578574669b8f/cmd/buildkitd/main_containerd_worker.go#L374-L384)).
With this patch, it's now possible to configure a runtime with a custom …
> containerd: support custom shim path 

- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/docs/reference.md
- frontend/dockerfile/shell/lex.go
- frontend/dockerfile/shell/lex_test.go
Add `#`, `##`, `%` and `%%` to variable substitution (inspired by #3611 and the almost identical shell functionality).
Can be used like this:
```
ARG IMAGE=busybox:latest
ARG VERSION=1.2.3
FROM ${IMAGE%:*}:stable
ENV MAJOR_MINOR_VERSION=${VERSION%.*}
ENV MAJOR_VERSION=${VERSION%%.*}
```
> Trimming in variable substitution

- cmd/buildctl/build.go
- cmd/buildctl/build/registryauthtlscontext.go
- docs/reference/buildctl.md
- session/auth/authprovider/authconfig.go
- session/auth/authprovider/authprovider.go
push image to self-signed certificate registry will throw `failed to authorize: failed to fetch oauth token: Post \"https://harbor/service/token\": tls: failed to verify certificate: x509: certificate signed by unknown authority` .
I have to provide the certificate using the`--registry-auth-tlscontext` flag.  But in most usage scenarios, I cannot provide the certificate file. 
when i build and push image to self-signed harbor `harbor-registry.com`， and not provide cert
`buildctl build --frontend dockerfile.v0 -local context=. -local dockerfile=./ --opt  filename=Dockerfile --opt platform="linux/amd64" --output type=image,name=harbor-registry.com/demo/demo:latest,push=true,registry.insecure=true --registry-auth-tlscontext host=harbor-registry.com,insecure=true`
> buildctl: Add insecure config for registry-auth-tlscontext flag

- docs/reference/buildctl.md
This change updates buildctl.md to
1. fix the markdown links for local sources and frontend options
2. resolve a typo to denote **_source_** as the one ~requires~ -> *required* gateway-specific option
Validated the markdown links are working using VSCode local preview.
> docs: update builtctl.md to fix markdown links and typo

- cache/blobs_linux.go
I run into a problem that randomly happen, image build and pushed by buildkit cannot be pulled by containerd or docker.
containerd complains that `failed to convert whiteout file "etc/.wh.hosts": file exists: unknown`.
docker complains that `failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header`,
or `failed to register layer: Error processing tar file(duplicates of file paths not supported)`.
After dig a while, I found that layer which unpack fail contains duplicated files:
According to code at https://github.com/moby/buildkit/blob/master/vendor/github.com/containerd/containerd/content/local/store.go#L594 , content writer always use the already written content, this is ok for pulling content from registry, but when pushing image, content …
> fix bug that gen layer tar contains duplicated files

- frontend/dockerfile/dockerfile_provenance_test.go
- frontend/dockerfile/dockerfile_test.go
- solver/llbsolver/provenance.go
When a step in the dockerfile is a dependency of multiple other steps in
the dockerfile, the provenance attestation would record the layer chain
for that step multiple times even with the same layer chain.
This is because the provenance attestation reuses the exporter mechanic
and the exporter mechanic would need to visit this same step multiple
times to produce the appropriate cache entries.
Since these duplicate layer chains aren't intentional, this modifies the
provenance attestation capture to detect these duplicates and remove
them.
Fixes #4143.
> dockerfile: remove duplicate layer chains from provenance attestation

- solver/edge.go
- solver/scheduler.go
This adds new environment variables for allowing debugging scheduler for only specific steps. This is useful because the scheduler debugging is quite verbose so if you run it on production builds it can generate lots of data that is hard to analyze. Old behavior is unchanged.
> solver: allow debugging specific builder steps

- frontend/dockerfile/docs/reference.md
Adds a quick reference of available Dockerfile instructions with links.
> docs: dockerfile instructions quick reference

- frontend/dockerfile/docs/reference.md
Had a go at trying to improve some style & verbiage of the dockerfile frontend reference.
I also tried to deduplicate and consolidate some of the gotchas around the shell and exec forms, and created a section for that.
> docs: refresh dockerfile frontend reference

- Dockerfile
runc release note: https://github.com/opencontainers/runc/releases/tag/v1.1.10
> Dockerfile: Bump up runc to 1.1.10

- solver/llbsolver/history.go
When a record is marked for deletion the event is set to nil but we don't check if it's nil when sending events which could cause a panic.
> llbsolver: fix possible panic when setting event to nil

- cmd/buildkitd/debug.go
- solver/cachekey.go
- solver/combinedcache.go
- solver/exporter.go
- solver/llbsolver/history.go
backports of:
* https://github.com/moby/buildkit/pull/4346
* https://github.com/moby/buildkit/pull/4361
* https://github.com/moby/buildkit/pull/4362
* https://github.com/moby/buildkit/pull/4451
> [0.12] cherry-picks 0.12.4

- solver/cachemanager.go
- solver/llbsolver/ops/source.go
Just a tiny cleanup while I was in the area :broom: :broom: 
In these cases, we can just call digest.Encoded(), instead of needing to play around with removing the prefix.
> chore: tidy up removal of digest algorithm

- frontend/dockerfile/dockerfile_mount_test.go
- solver/llbsolver/ops/exec.go
- solver/llbsolver/ops/exec_test.go
This updates #4270 to add an integration test and also merge some of the
logic for how the selectors are created. Now, `toSelectors` will perform
the root path detection instead of some custom logic in `getMountDeps`.
`dedupePaths` has also been updated to check if the number of paths is 1
or less so it can avoid an allocation when the function is a no-op.
> solver: use toSelectors to filter root paths instead of custom logic

- util/tracing/detect/detect.go
This is a workaround for the brittleness when constructing OTel `Resource` objects. Internally, the OTel libraries do their own detection which can be merged with one created in code. However, the `semconv` spec versions must match. (NOT module version! the `semconv` package has multiple subpackages for each spec version, e.g. `semconv/v1.17`, `semconv/v1.21`, etc.)
This creates a problem when BuildKit is used as a library - the importing app might be using a different, otherwise compatible version of the OTel libraries, so when it creates a resource, it will be merged with one of a different version.
By allowing the `Resource` to be set (like the `Recorder`), the calling code can construct a resource using known consistent library versions that work, and then allow BuildKit to take over …
> tracing: allow the `Resource` to be set externally

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_runmount.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerui/config.go
- frontend/dockerui/namedcontext.go
This changes the llb generation in `dockerfile2llb` to add the
`llb.FollowPaths` option when named contexts are used in the same way
that happens with the default context.
This means that dockerfiles that look like this:
```
FROM scratch
COPY --from=mynamedctx ./a.txt /a.txt
```
Will only load the file `a.txt`. This behavior is consistent with the
default context.
This also removes the unused []llb.LocalOption from ContextOpt and
replaces it with an async counterpart. This is needed because we
initialize the named context before we know which paths are needed for
the filter.
Fixes #1765.
> dockerfile2llb: filter unused paths for named contexts

- source/git/source.go
- source/git/source_test.go
Originally reported by @vito in relation to https://github.com/dagger/dagger. You can see a simple example of this in https://play.dagger.cloud/playground/ak2KSRH_Gid.
Previously, it was very possible for the CacheKey function to return a sha key that was *not* the checked out commit.
There are two cases that I've encountered where this can happen:
- An annotated tag will have the pin of the tag, and not the underlying commit, which will be HEAD after the checkout.
- If multiple tags have the same path component (e.g. "mytag" and "abc/mytag") then the first alphabetical tag will be selected when (in this case "abc/mytag").
To avoid this kind of case, we can't just search for a single match in the results for ls-remote. There's no way to filter for just an exact match, so we need to scan …
> git: ensure that pin matches checked-out commit

- client/client.go
- cmd/buildctl/common/common.go
- examples/build-using-dockerfile/main.go
`WithFailFast` was not actually causing any change in behavior, so we can remove the option completely.
The option set `FailOnNonTempDialError(true)` on the gRPC connection. However, the help text for this method option [declares](https://github.com/moby/buildkit/blob/-/vendor/google.golang.org/grpc/dialoptions.go#L470-L471) that it "does not do anything useful unless you are also using `WithBlock()`" - which we do not do. I've verified that the only client-side code path that actually handles this option is under a check for if `WithBlock()` was also used.
We can remove this option instead of fixing it, since the need for this functionality has been replaced by the more buildkit-native client.Wait function - this function also correctly waits for the buildkit server to begin running, and …
> chore: remove unneccessary WithFailFast option

- .github/workflows/test-os.yml
- client/build_test.go
- client/client_test.go
- cmd/buildctl/build_test.go
- cmd/buildctl/buildctl_test.go
- cmd/buildctl/diskusage_test.go
- cmd/buildctl/prune_test.go
- frontend/dockerfile/dockerfile_addchecksum_test.go
- frontend/dockerfile/dockerfile_addgit_test.go
- frontend/dockerfile/dockerfile_heredoc_test.go
- frontend/dockerfile/dockerfile_mount_test.go
- frontend/dockerfile/dockerfile_outline_test.go
- frontend/dockerfile/dockerfile_provenance_test.go
- frontend/dockerfile/dockerfile_runnetwork_test.go
- frontend/dockerfile/dockerfile_secrets_test.go
- frontend/dockerfile/dockerfile_ssh_test.go
- frontend/dockerfile/dockerfile_targets_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/errors_test.go
- frontend/frontend_test.go
- solver/jobs_test.go
- util/testutil/integration/run.go
- util/testutil/workers/oci.go
- util/testutil/workers/oci_unix.go
- util/testutil/workers/oci_windows.go
The plan is to skip all the failing tests on windows so as to have the CI running on WS2022; and then we will go fixing each tests and enabling them in separate PRs -- see tracking issue here https://github.com/moby/buildkit/issues/4485
This will be a helpful approach as we bring parity between windows and unix.
> I think skipping failing tests on Windows is ok to get a general view of which ones currently do not work. As we move forward, we can move them one by one in a platform specific _test.go file if they don't make sense at all on Windows (like testShmSize) and enable the ones that should absolutely work on Windows such as: https://github.com/moby/buildkit/pull/4479/files#diff-93731187c2a292b7e92b852225675f88b41b7634dafd66cfeab50697bd806ddbR3053
> If we ever manage to enable LCOW …
> tests: enable integration test run on windows as baseline

- .github/workflows/test-os.yml
related to https://github.com/moby/buildkit/issues/4444
Mitigate flaky freebsd tests with a retry logic.
> ci(test-os): retry logic for freebsd smoke tests step

- .github/workflows/buildkit.yml
related to https://github.com/moby/buildkit/pull/4477#issuecomment-1851198008
Image build seems to hang and job timed out after 6h (default on GitHub Actions) for the past few days:
* https://github.com/moby/buildkit/actions/runs/7183260509/job/19562224050?pr=4460#step:13:464
* https://github.com/moby/buildkit/actions/runs/7163256834/job/19502241344?pr=4477#step:13:461
```
time="2023-12-11T06:13:24Z" level=debug msg="diff applied" d=2.806054ms digest="sha256:1f5f54dd06e9d17c845fb7c5fdf944c3160d6c4a7a8c645ee8b08e5618c0e65a" media=application/vnd.oci.image.layer.v1.tar+gzip size=942 spanID=62556bbbe3ab4d04 traceID=ca85fd7fcf30de02e721e83aa9c1c2e5
time="2023-12-11T06:13:24Z" level=debug msg="Using single walk diff for /tmp/buildkit-mount4051339310"
time="2023-12-11T06:13:24Z" level=debug …
```
> ci(buildkit): set timeout to image job

- docker-bake.hcl
- hack/dockerfiles/lint.Dockerfile
reported by @jsternberg 
```
> [lint-nydus golangci-lint 1/1] RUN --mount=target=/go/src/github.com/moby/buildkit     --mount=target=/root/.cache,type=cache,id=lint-cache-linux/arm64   xx-go --wrap &&   golangci-lint run --build-tags "nydus" &&   touch /golangci-lint.done:
61.01 cmd/buildkitd/main.go:17:46: directive `//nolint:staticcheck // SA1019 deprecated` is unused for linter "staticcheck" (nolintlint)
61.01   "github.com/containerd/containerd/pkg/seed" //nolint:staticcheck // SA1019 deprecated
61.01                                               ^
61.01 cmd/buildkitd/main.go:80:2: directive `//nolint:staticcheck // SA1019 deprecated` is unused for linter "staticcheck" (nolintlint)
61.01   //nolint:staticcheck // SA1019 deprecated
61.01   ^
```
Cache is shared across targets …
> lint: set proper cache key for golangci-lint target

- source/http/source_test.go
This enables 3 tests that had been previously skipped due to the lack of Windows support initially.
The remaining ones in that group, see #4485, will need some code modifications to be enabled.
--
> tests: enable previously skipped tests

- util/tracing/detect/detect.go
- cherry-pick of https://github.com/moby/buildkit/pull/4472
- relates to https://github.com/docker/compose/pull/11283#issuecomment-1861345014
- see also https://github.com/open-telemetry/opentelemetry-go/issues/2341
This is a workaround for the brittleness when constructing OTel `Resource` objects. Internally, the OTel libraries do their own detection which can be merged with one created in code. However, the `semconv` spec versions must match. (NOT module version! the `semconv` package has multiple subpackages for each spec version, e.g. `semconv/v1.17`, `semconv/v1.21`, etc.)
This creates a problem when BuildKit is used as a library - the importing app might be using a different, otherwise compatible version of the OTel libraries, so when it creates a resource, it will be merged with …
> [forward port to master] tracing: allow the `Resource` to be set externally

- util/tracing/detect/detect.go
This refactors the resource detector to ensure the detected resource is
initialized before use. It also removes the duplicate logic for setting
the service name through the environment variable.
> detect: refactor the default resource detector for detect

- client/mergediff_test.go
- snapshot/diffapply_unix.go
This PR attempts to fix the following error during a merge snapshot:
```
Dockerfile:17
15 |     # This dummy COPY is important to ensure that a snapshot is taken before RUN is executed. Otherwise the snapshotter is never called.
16 |
17 | >>> RUN echo "Hello"
18 |
ERROR: failed to solve: failed to compute cache key: failed to apply diffs: 1 error occurred:
* failed to handle changes: failed to hardlink during apply: failed to hardlink during apply: link /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/100/fs/file1 /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/100/fs/file2: no such file or directory
```
in the corresponding Dockerfile:
```
FROM busybox
RUN touch /file2
COPY --link empty-file /file1
RUN rm /file1 /file2
COPY --link …
```
> Fix hardlink issue with whiteout deletes in the merge snapshotter.

- frontend/dockerfile/docs/reference.md
> docs: clarify the purpose of the syntax parser directive

- .github/workflows/buildkit.yml
- Dockerfile
relates and closes https://github.com/moby/buildkit/pull/4491
`buildkitd --version` might hang when using emulation during smoke test. Add a timeout to mitigate this issue to avoid blocking CI.
> dockerfile: mitigate flaky smoke test with timeout

- go.mod
- go.sum
- vendor/modules.txt
no diff, as the tag is the same commit as we used already; https://github.com/docker/go-connections/compare/fa09c952e3ea...v0.5.0
> vendor: github.com/docker/go-connections v0.5.0

- go.mod
Some direct dependencies were in the "indirect" dependencies group.
> go.mod: fix dependencies being in the wrong group

- cmd/buildctl/build.go
- cmd/buildctl/cachemetrics.go
- docs/reference/buildctl.md
Hello there,
this adds a new `json-cache-metrics` parameter to write to an `os.File`. Handy in deamonless mode, mode with which it is a bit hard to scrape metrics the good way. 
At first it was just writting to stderr like the rest, after everything is done. But while seeking the end of log file to just get the last line _works_, it turned out a bit brittle at scale (in our case). 
So I made it possible to pick a file just like for `trace`. (But also kept the std(out/err) option, nice locally)
LMK what you think.
Closes #4445
> add an option to show JSON cache metrics

- client/client_test.go
- exporter/containerimage/export.go
- frontend/gateway/gateway.go
- solver/llbsolver/provenance.go
- solver/llbsolver/solver.go
- solver/result/result.go
Fixes https://github.com/docker/build-push-action/issues/1024.
The main fix is a bug in `ConvertResult` that accidentally discarded zero-values. This essentially meant that images that had nil entries in the refs map (i.e. scratch images) would lose those - this caused an error in the exporter: `cannot export multiple platforms without multi-platform enabled`.
Everything else is a fix needed to not get `nil` panics everywhere - there are certain parts of the code that never saw `nil` in the `Refs` map, so these now need to be handled (and mostly skipped over).
@tonistiigi raised this in https://github.com/moby/buildkit/commit/3c1deef413acc96397e08e285a2ac1450be1fcde#r135018757.
Note from the commit message:
> Instead, we just skip over nil refs. This isn't ideal - we *should* be able …
> Fix scratch multi-platform images

- hack/images
- hack/test
partial / modified backports of;
- https://github.com/moby/buildkit/commit/bb18da8347f6e8f6c810f28d70d5c6ba23bf63bf (part of https://github.com/moby/buildkit/pull/4048)
- https://github.com/moby/buildkit/pull/4541
relates to:
- https://github.com/moby/moby/pull/47054#issuecomment-1884715610
> [0.12 backport] hack/test: allow ALPINE_VERSION to be set from env

- Dockerfile
- hack/images
- hack/test
partial / modified backports of;
- https://github.com/moby/buildkit/commit/5955ccf77c3618970d336821fd75857155f9b6b9 (part of https://github.com/moby/buildkit/pull/4348)
- https://github.com/moby/buildkit/commit/bb18da8347f6e8f6c810f28d70d5c6ba23bf63bf (part of https://github.com/moby/buildkit/pull/4048)
- https://github.com/moby/buildkit/pull/4541
> [0.11 backport] hack/test: allow ALPINE_VERSION to be set from env

- frontend/dockerfile/docs/reference.md
> docs: fix copy/paste typo in Dockerfile reference

- frontend/dockerfile/docs/reference.md
- frontend/dockerfile/shell/lex.go
- frontend/dockerfile/shell/lex_test.go
One of the variable expansion functions missing from #4287 was string substition, so I implemented it.
Motivating example:
```dockerfile
ARG VERSION=1.2.3
ARG URL=https://github.com/foo-corp/foo/releases/download/$VERSION/foo-$VERSION-${TARGETARCH}.tar.gz
ADD ${URL//arm64/aarch64} /tmp/foo.tar.gz
RUN tar -xf /tmp/foo.tar.gz
```
The two parts following the variable name (pattern and replacement) need to be parsed separately with `processStopWords`, otherwise variable expansion could cause a `/` in a variable referenced in the pattern to be interpreted as separator between patern and replacement. This means that the second `/` is required (i.e. `${foo/bar/}` to remove `bar`, compared to `${foo/bar}` as accepted by various shells).
On the positive side, wildcards and slashes in referenced …
> String substitution in variable expansion

- frontend/dockerfile/docs/reference.md
Attempt to clarify how quoting the here-document word affects variable
expansion with more detailed examples.
> docs: clarify here-document word quote variable expansion

- session/filesync/filesync.go
This was a regression introduced in #4134 when editing the implementation of `CopyFileWriter` and `CopyToCaller` to support multiplexed imports.
Identical in style to #4049, we need to ensure that `CopyToCaller` also doesn't overwrite the provided metadata, but instead appends to it.
> filesync: append metadata for CopyToCaller

- go.mod
- go.sum
- vendor/github.com/docker/docker/errdefs/is.go
- vendor/github.com/vbatts/tar-split/archive/tar/reader.go
- vendor/modules.txt
full diff: https://github.com/vbatts/tar-split/compare/v0.11.3...v0.11.5
full diff: https://github.com/docker/docker/compare/v25.0.0-rc.1...v25.0.0-rc.2
full diff: https://github.com/docker/cli/compare/v25.0.0-rc.1...v25.0.0-rc.2
> vendor: update docker/docker and docker/cli to v25.0.0-rc.2

- cmd/buildkitd/main.go
- util/appdefaults/appdefaults_unix.go
- util/appdefaults/appdefaults_windows.go
Prior to this commit, the path of `/etc/buildkit/cni.json` was hard-coded for rootless users too
> rootless: use `~/.config/buildkit/cni.json`

- frontend/dockerfile/dockerfile_test.go
- solver/llbsolver/provenance.go
There was a reasonably significant typo in [`d709afd` (#3137)](https://github.com/moby/buildkit/pull/3137/commits/d709afdb96f539c49836f5874f7331a11287bee0), yikes.
Came across this while working in the area :scream: Slightly terrifying, I clearly wasn't playing close attention :cry: 
I don't think this is on a critical code-path anywhere, doing `Evaluate` on a frontend provided result was designed to be used in https://github.com/docker/buildx/pull/1197, but I don't think ever became relied-upon functionality.
> solver: ensure each ref in the result map is evaluated

- solver/jobs.go
- solver/scheduler.go
- solver/scheduler_test.go
- util/progress/multiwriter.go
Resolves https://github.com/moby/buildkit/pull/4347#issuecomment-1889353650.
Previously, the scheduler could create cycles in the edges it merged:
> Essentially, what appears to happen is that we have two vertexes, A and B. Both of these vertexes seem to have at least two edges, A1/A2 and B1/B2. Somehow, we perform a merge that merges A1 into B1, but then merges B2 into A2.
Prior to #4347 this could (at worst) lead to a slight unnecessary inefficiency, where we would execute both A and B (even though both of their edges be merged so we'd never need to perform both of them). However, after this PR, we can accidentally deadlock, due to attempting to nest progress writers.
> scheduler: always edge merge in one direction

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_runmount.go
- frontend/dockerfile/parser/errors.go
Update the detection and handling of circular dependency validation.
New output:
```
[+] Building 0.0s (1/1) FINISHED
=> [internal] load build definition from Dockerfile                                                                           0.0s
=> => transferring dockerfile: 197B                                                                                           0.0s
Dockerfile:9
7 |
8 |     FROM alpine AS build
9 | >>> COPY --from=target /Dockerfile /d2
10 |
11 |     FROM target
Dockerfile:3
1 |
2 |     FROM busybox AS target
3 | >>> COPY --from=build / /out
4 |
5 |     FROM target as b
error: failed to solve: circular dependency detected on stage: target
```
> dockerfile: add source location to circular dependency error

- go.mod
- go.sum
- vendor/modules.txt
full diff: https://github.com/docker/docker/compare/v25.0.0-rc.3...v25.0.0
full diff: https://github.com/docker/cli/compare/v25.0.0-rc.3...v25.0.0
> vendor: update docker/docker and docker/cli to v25.0.0

- solver/llbsolver/history.go
While debugging around, I found some instances of os.ErrNotExist appearing in the logs from the history API - however, no stack traces were available, since they're not wrapped.
This patch just adds wrapping for them, with some additional debbuging info.
> history: wrap os.ErrNotExist errors

- Dockerfile
- relates to https://github.com/moby/moby/pull/47054
Before this:
docker build --build-arg ALPINE_VERSION=3.18 --build-arg GO_VERSION=1.20.13 --target integration-tests .
> [dnsname 3/3] RUN --mount=target=/root/.cache,type=cache   set -e; make binaries; mv bin/dnsname /usr/bin/dnsname:
0.435 GO111MODULE=on go build -mod=vendor -ldflags '-X main.gitCommit=18822f9a4fb35d1349eb256f4cd2bfd372474d84' -o bin/dnsname github.com/containers/dnsname/plugins/meta/dnsname
0.610 # runtime/cgo
0.610 In file included from _cgo_export.c:3:
0.610 /usr/include/fortify/stdlib.h:23:15: fatal error: stdlib.h: No such file or directory
0.610    23 | #include_next <stdlib.h>
0.610       |               ^~~~~~~~~~
0.610 compilation terminated.
With this patch:
docker build --build-arg ALPINE_VERSION=3.18 …
> [0.11] Dockerfile: install musl-dev to fix build on alpine 3.18 and up

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_runmount.go
- frontend/dockerfile/dockerfile_test.go
Dockerfile stages always needed to be in order (you can not refer to a stage that is defined after your current command), but the behavior for incorrect order was undefined instead of consistently erroring.
Previously copying from a stage defined later would usually cause an error about a missing source file that could have been quite confusing. When the source path was "/" then the behavior could have been worse and resulted in COPY passing without error, without any files actually being copied (or only files from base image being copied).
This validates the order when on COPY and mount dispatch, returns proper error with correct source code location.
```
Dockerfile:5
3 |
4 |     FROM busybox AS target
5 | >>> COPY --from=build / /out
6 |
7 |     FROM alpine AS build …
```
> dockerfile: validate order when linking stages

- Dockerfile
- hack/dind: update comments around AppArmor
- Update blogpost URL
- Modify the DinD entrypoint scripts to make the issue reproducible inside DinD container.
Full diff (`git diff v20.10.21:hack/dind v25.0.1:hack/dind`);
```patch
git diff v20.10.21:hack/dind v25.0.1:hack/dind
diff --git a/hack/dind b/hack/dind
index 087270a7a8..456ba861a6 100755
--- a/hack/dind
+++ b/hack/dind
@@ -3,7 +3,7 @@ set -e
-# See the blog post: https://blog.docker.com/2013/09/docker-can-now-run-within-docker/
+# See the blog post: https://www.docker.com/blog/docker-can-now-run-within-docker/
#
@@ -11,8 +11,39 @@ set -e
+#
+# Set the container env-var, so that AppArmor is enabled in the daemon and
+# containerd when running docker-in-docker.
+#
+# see: https://github.com/containerd/containerd/blob/787943dc1027a67f3 …
```
> Dockerfile: update dind script to latest version

- util/network/cniprovider/cni_linux.go
Follow-up to https://github.com/moby/buildkit/pull/4546.
Because `withDetachedNetNSIfAny` is called in `Sample`, it regularly gets called, leaving this debug message throughout the logs if CNI is enabled (even when rootlesskit is disabled).
> chore: remove noisy rootlesskit cni log

- solver/errdefs/context.go
Since the change to replace uses of `context.WithCancel` with `WithCancelCause` in #4457, we've also begun wrapping all cancellations using `errors.WithStack`. This means that these would not directly match context.Canceled, so we need to make sure to use `errors.Is`.
I spotted this while reading over #4457 in more detail again, I wonder if this is the source of a particular deadlock we're encountering where gRPC streams aren't shutting down (though this may or may not be the actual root cause lol). That said, this code definitely seems wrong.
Ideally, we should have some linter check to prevent comparing errors like this *at all* - direct comparisons on errors should be the exception rather than the rule. cc @crazy-max do you know if this exists?
> solver: use errors.Is when checking context.Cause()

- executor/oci/spec.go
I can't see any reason why these `nil` returns could be intentional, so changing to correct error returns.
> oci: fix error handling on submount calls

- go.mod
- go.sum
- vendor/github.com/docker/docker/pkg/system/xattrs.go
- vendor/github.com/docker/docker/pkg/system/xattrs_linux.go
- vendor/modules.txt
- pkg/system: return even richer xattr errors
full diff: https://github.com/docker/docker/compare/v25.0.0...v25.0.1
No changes in vendored code
full diff: https://github.com/docker/cli/compare/v25.0.0...v25.0.1
> vendor: update docker/docker and docker/cli to v25.0.1

- control/control.go
- solver/llbsolver/solver.go
The solver has a Close method to shutdown the scheduler, which releases a goroutine. We should call it on shutdown.
While in the area, we can also close the `sysSampler`.
This shouldn't affect anything, but noticed that we should probably do this for consistency (I just noticed it while poking around `scheduler_test.go`. Also if we want better `SIGTERM` handling at some point, this feels like something that could potentially trip us up in implementing that.
> chore: close solver resources on shutdown

- solver/llbsolver/ops/exec.go
- solver/llbsolver/ops/exec_test.go
A cache ID should not have any impact on whether or not a step should be re-run any more than the content of that cache does (or rather, doesn't).
> Do not include a cache mount's ID in the ExecOp's cachemap

- cache/remotecache/v1/chains.go
- solver/llbsolver/provenance.go
- solver/types.go
I've spent a reasonable amount of time staring at this code, and myself writing comments and refactoring to improve clarity.
Instead of just keeping my changes local, I think it makes sense to upstream these so that future readers can also take advantage of this. There's only some small code changes in ~~our use of `digest`~~ (nope, we can't do this :scream: not every value of `digest.Digest` is a valid digest, fun), and a refactoring of `item.validate` to make it easier to comment and describe.
cc @sipsma, who asked if could share some of my inline docs on this.
> chore: start to improve cachechains readability

- cache/blobs.go
- cache/refs.go
- util/leaseutil/manager.go
fixes https://github.com/moby/buildkit/issues/4419
When one flightcontrol callback gets canceled
ctx.Value() stops working for aquiring leases for
remaining callbacks. While this behavior should be also looked at more carefully, returning a lease for the first callback or for the remaining callback would not be correct as some objects can be tracked by first lease and that lease could be already deleted by the first callpath.
This fixes it so that any object tracked by flightcontrol callback will be copied to the lease of every codepath after the callback has returned.
> fix lease management with flightcontrol

- cache/remotecache/v1/doc.go
This file mistakenly included an output index field. This field never seemed to exist, the output index is actually part of the record digest (see `rootKey`).
This mistake seems to have been here right at the very beginning in https://github.com/moby/buildkit/commit/7b5fc36f5f94ffa396c8646927f1b3cff512a205#diff-f1af45f50b0c62e0be01b77072ad6d5239cb0fc726fb841ed95decf086e000dc.
Compare the `spec.go` source of truth in that commit:
```go
type CacheRecord struct {
Results []CacheResult  `json:"layers,omitempty"`
Digest  digest.Digest  `json:"digest,omitempty"`
Inputs  [][]CacheInput `json:"inputs,omitempty"`
}
```
vs the misleading `doc.go`:
```go
//    {
//      "digest": "sha256:deadbeef",
//      "output": 1,                   <- optional output index
//      "layers": [ …
```
> chore: fix remotecache/v1/doc.go

- frontend/dockerfile/dockerfile2llb/convert.go
When using the parents flag, it will add CopyInfo to the end of opts
https://github.com/moby/buildkit/blob/ef61ad133d7fd20632eb964dfc78292360f2f09d/frontend/dockerfile/dockerfile2llb/convert.go#L1232-L1238
And since it's the last, it will replace any opts in front. So the chmod/chown flags in front will be disabled (like they don't exist).
https://github.com/moby/buildkit/blob/ef61ad133d7fd20632eb964dfc78292360f2f09d/client/llb/fileop.go#L481-L483
We should take it forward. Like this
https://github.com/moby/buildkit/blob/ef61ad133d7fd20632eb964dfc78292360f2f09d/frontend/dockerfile/dockerfile2llb/convert.go#L1206-L1209
> Fix missing chown/chmod when using parents flag with ADD/COPY command

- Dockerfile
Brings in the fix for GHSA-xr7r-f8xq-vfvv
> update runc to v1.1.12

- client/build_test.go
- cmd/buildkitd/main.go
- executor/executor.go
- frontend/frontend.go
- frontend/gateway/container/container.go
- frontend/gateway/forwarder/forward.go
- frontend/gateway/forwarder/frontend.go
- frontend/gateway/gateway.go
- snapshot/snapshotter.go
- solver/llbsolver/bridge.go
- solver/llbsolver/provenance.go
- solver/llbsolver/solver.go
- solver/llbsolver/vertex.go
- util/entitlements/entitlements.go
- worker/worker.go
- worker/workercontroller.go
Brings in fix for https://github.com/moby/buildkit/security/advisories/GHSA-wr6v-9f75-vh2g
First commit is only refactoring.
> llbsolver: make sure interactive container API validates entitlements

- executor/oci/spec.go
- executor/oci/spec_freebsd.go
- executor/oci/spec_linux.go
- executor/oci/spec_windows.go
- snapshot/localmounter.go
- snapshot/localmounter_freebsd.go
- snapshot/localmounter_linux.go
While submount paths were already validated there are some cases where the parent mount may not be immutable while the submount is created.
Fix for https://github.com/moby/buildkit/security/advisories/GHSA-m3r6-h7wv-7xxv
(cherry picked from commit 2529ec4121bcd8c35bcd96218083da175c2e5b77)
> exec: add extra validation for submount sources

- client/client_test.go
- client/validation_test.go
- control/control.go
- exporter/containerimage/exptypes/parse.go
- exporter/containerimage/writer.go
- frontend/gateway/client/attestation.go
- frontend/gateway/gateway.go
- solver/llbsolver/bridge.go
- solver/llbsolver/solver.go
- sourcepolicy/matcher.go
- util/tracing/transform/attribute.go
- util/tracing/transform/span.go
Brings in fix for https://github.com/moby/buildkit/security/advisories/GHSA-9p26-698r-w4hx
All but two of the changes have no security impact, only for consistency.
@cpuguy83
> Add more validations for nil values

- frontend/dockerfile/docs/reference.md
Make it clearer that people need to stop leaking their credentials by
putting them in build arguments.
> docs: make the warning about build arguments

- hack/test
When running tests with dockerd worker locally we often miss to disable features not yet supported like we are doing in moby workflow: https://github.com/moby/moby/blob/3e230cfdcc989dc524882f6579f9e0dac77400ae/.github/workflows/buildkit.yml#L71-L75
This change will print a warning in such case.
> test: warn if testing dockerd worker without disabled features

- source/git/identifier.go
- source/git/source.go
- util/gitutil/git_url.go
Building on top of #4326.
We still have a weird `isGitTransport` implementation that I originally missed - this meant that we could have easily diverged in the future.
> chore: refactor IsGitTransport to avoid duplication

- .github/dependabot.yml
- .github/workflows/.test.yml
- .github/workflows/buildkit.yml
- .github/workflows/dockerd.yml
- .github/workflows/docs-upstream.yml
- .github/workflows/test-os.yml
Follow-up
* https://github.com/docker/buildx/pull/2210
* https://github.com/docker/buildx/pull/2212
* https://github.com/docker/buildx/pull/2227
* https://github.com/moby/moby/pull/47250
* https://github.com/moby/moby/pull/47263
Update remaining GHA following the deprecation notice from GitHub:
> Please update the following actions to use Node.js 20: actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> ci: update gha to account for node 16 deprecation

- go.mod
- go.sum
- vendor/modules.txt
full diff: https://github.com/docker/docker/compare/v25.0.1...v25.0.2
full diff: https://github.com/docker/cli/compare/v25.0.1...v25.0.2
> vendor: update docker/docker and docker/cli to v25.0.2

- cmd/buildkitd/main.go
Fix #4618 (regression in v0.13.0-beta1)
> Fix regression `/run/buildkit is inaccessible for socket user`

- client/build_test.go
- client/client_test.go
- cmd/buildctl/build.go
- cmd/buildctl/build/local.go
- examples/build-using-dockerfile/main.go
- frontend/dockerfile/dockerfile_addchecksum_test.go
- frontend/dockerfile/dockerfile_addgit_test.go
- frontend/dockerfile/dockerfile_heredoc_test.go
- frontend/dockerfile/dockerfile_mount_test.go
- frontend/dockerfile/dockerfile_outline_test.go
- frontend/dockerfile/dockerfile_parents_test.go
- frontend/dockerfile/dockerfile_provenance_test.go
- frontend/dockerfile/dockerfile_runnetwork_test.go
- frontend/dockerfile/dockerfile_runsecurity_test.go
- frontend/dockerfile/dockerfile_secrets_test.go
- frontend/dockerfile/dockerfile_ssh_test.go
- frontend/dockerfile/dockerfile_targets_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/errors_test.go
- frontend/frontend_test.go
- solver/jobs_test.go
- util/testutil/integration/util.go
As `client.SolveOpt.LocalDirs` is marked as deprecated, this PR moves all usage to `LocalMounts` instead.
Unfortunately the PR ended up quite long, but the changes are essentially mechanical.
I am afraid that this PR will also conflict with existing open PRs that touch tests, but I believe that resolving the conflicts will be trivial.
Once this PR is merged, `client.SolveOpt.LocalDirs` will be ready for removal, in case no external projects is using it.
> Refactoring: Remove usage of deprecated LocalDirs field in SolveOpts

- docs/rootless.md
Move "Distribution-specific hint" and "Troubleshooting" to the bottom of the document to improve readability.
> docs/rootless.md: move auxiliary information to the bottom

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/github.com/docker/docker/api/types/network/endpoint.go
- vendor/github.com/docker/docker/api/types/network/ipam.go
- vendor/github.com/docker/docker/pkg/ioutils/readers.go
- vendor/github.com/docker/docker/pkg/ioutils/writers.go
- vendor/github.com/docker/docker/profiles/seccomp/default.json
- vendor/github.com/docker/docker/profiles/seccomp/default_linux.go
- vendor/modules.txt
full diff: https://github.com/docker/docker/compare/v25.0.2...v25.0.3
full diff: https://github.com/docker/cli/compare/v25.0.2...v25.0.3
> vendor: update docker/docker and docker/cli to v25.0.3

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/content/content.go
- vendor/github.com/containerd/containerd/images/archive/exporter.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
Adds `content.InfoReaderProvider` interface
full diff: https://github.com/containerd/containerd/compare/v1.7.12...v1.7.13
> go.mod: update containerd to v1.7.13

- util/resolver/resolver.go
Currently a localhost http registry will still attempt http after a redirect to an https host. The http fallback should only apply to the same host which previously had a fallback to http. The caching of the host is only an optimization and not necessary to function correctly, multiple fallback hosts using the same transport would still work.
See https://github.com/moby/moby/issues/47240
> Update fallback logic to only fallback with previous host

- frontend/dockerfile/dockerfile2llb/convert.go
I think the commit message of the COPY/ADD command should include chown/chmod information for clarity.
> Add --chown and --chmod to commitMessage for ADD/COPY command

- util/resolver/pool.go
Prior to this change, entries in the resolver's auth token cache was keyed only by remote name and action (push/pull). This resulted in remote authenticated sessions being leaked between distinct client sessions with the potential for one client's token to be used in authentication for another client's registry access.
While this may not have had a substantial impact for pull requests as the solver vertices are shared for all clients as is the local cache namespace—i.e. one client can always receive a cache entry that was the result of another client's cached pull request—the shared auth cache also allowed one client to push to a remote registry for a ref it may not have otherwise had rights to. This behavior is particularly problematic in shared CI environments where auth token scopes …
> resolver: Isolate auth token cache per session

- executor/containerdexecutor/executor.go
- executor/containerdexecutor/executor_unix.go
- executor/containerdexecutor/executor_windows.go
- executor/oci/resolvconf.go
- executor/oci/resolvconf_test.go
- executor/runcexecutor/executor.go
replaces and closes https://github.com/moby/buildkit/pull/3244
fixes https://github.com/moby/buildkit/issues/3210
related to https://github.com/docker/buildx/issues/175#issuecomment-1875540193
> keep local dns in resolv.conf when host network enabled

- Dockerfile
- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
- frontend/gateway/grpcclient/client.go
This fallback case was accidentally left out of https://github.com/moby/buildkit/pull/4563/files
It can appear for example if new dockerfile frontend resolves SBOM generator image.
> add missing fallback from new frontend to daemon without sourceresolver

- Dockerfile
Needed for bridge networking.
I'm not quite sure what has changed since the bridge support was added as I do remember testing it with buildx back then. The test suite did not catch this as iptables is installed in the integration-tests stage.
fix #4637
> make sure iptables installed in release image

- client/client_test.go
related to https://github.com/moby/moby/pull/47364#discussion_r1492394675
Currently, when exporting with moby exporter using dockerd without containerd snap, the history doesn't produce any result in the history. This might have been an oversight when vendoring buildkit 0.11 on moby.
I think it should at least return the config (`application/vnd.docker.container.image.v1+json`) in this case which @vvoland has implemented in https://github.com/moby/moby/pull/47364 (https://github.com/moby/moby/commit/5555a658cfbb81bc440f9bd3a8cc58df513f3d6d)
So fix this test to take that into account.
> client: fix result history media type with dockerd moby

- exporter/containerimage/image/docker_image.go
- frontend/dockerfile/dockerfile_test.go
- relates to https://github.com/moby/buildkit/pull/4634#discussion_r1486335753
Aligning with the docker image spec;
https://github.com/moby/docker-image-spec/blob/f1d00ebd2d6d6805170d5543dbca4b850f35f9af/specs-go/v1/image.go#L30C19-L30C100
> exporter: make OnBuild omiteempty

- .github/workflows/.test.yml
- .github/workflows/test-os.yml
related to https://github.com/moby/buildkit/actions/runs/7957965041/job/21723057849#step:9:41
Since https://github.com/codecov/codecov-action/releases/tag/v4.0.0, the token is now required for public repos when the action runs on a branch/tag of this repo. But contributors creating PRs from their forks to the upstream repo will be able to get coverage information from Codecov. I guess this is because they don't have access to the secret. This is related to https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/
As discussed with @thaJeztah, an org-wide secret has been created so it can be used across repos of this org to fix this issue.
> ci: set codecov token

- solver/llbsolver/mounts/mount.go
> secret mount: avoid setting `noexec` when an exec bit it set

- util/network/cniprovider/bridge.go
See:
- containerd/nerdctl#2818
Similar to:
- containerd/nerdctl#2819
> CNI bridge firewall: avoid using `iptables` backend on rootless mode

- exporter/containerimage/image/docker_image.go
- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/image.go
- frontend/dockerui/build.go
- frontend/dockerui/config.go
- frontend/dockerui/namedcontext.go
- frontend/gateway/gateway.go
- go.mod
- go.sum
- util/imageutil/schema1.go
- vendor/github.com/moby/docker-image-spec/LICENSE
- vendor/github.com/moby/docker-image-spec/specs-go/v1/image.go
- vendor/modules.txt
- relates to https://github.com/moby/moby/pull/47362
The Docker image specification (which extends the OCi types with additional fields) was moved to a separate module, so we can now use those definitions as a central place to define these types.
> exporter: use docker-spec instead of locally defined types

- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
when making changes to handle the codecov token in https://github.com/moby/buildkit/pull/4660 I forgot to enable [secrets inheritance for our reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow), otherwise secret is not passed.
> ci: inherit secrets from the caller workflow

- .github/workflows/test-os.yml
- Dockerfile
- hack/Vagrantfile.freebsd13
* needs #4652 
Builds containerd from source in the Dockerfile to avoid drifting with freebsd packages installed in vagrant image and merge windows and freebsd build to use the same `binaries-for-test` target in ci workflow.
cc @akhramov
> dockerfile: build containerd from source for freebsd

- cache/remote.go
- cache/remotecache/v1/chains.go
- cache/remotecache/v1/parse.go
- solver/types.go
- util/contentutil/multiprovider.go
- related: https://github.com/containerd/containerd/pull/9554
`client.Export` in v2 will need an `content.Info` implementation.
> util/multiprovider: Implement Info

- frontend/dockerfile/dockerfile2llb/convert.go
Set same llb custom name for `llb.HTTP` and `llb.Git` when used with `ADD` command to have a consistent progress output.
```dockerfile
FROM busybox
ADD --keep-git-dir=true "https://github.com/moby/buildkit.git#v0.10.1" /buildkit
ADD https://raw.githubusercontent.com/moby/moby/master/README.md /
```
Current:
```
#9 https://raw.githubusercontent.com/moby/moby/master/README.md
#9 DONE 0.3s
#10 git://github.com/moby/buildkit.git#v0.10.1
#10 0.061 Initialized empty Git repository in /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/767/fs/
#10 0.518 5bc9c7b15891eecab8d1e0c34ed62a0177c45ae7      refs/tags/v0.10.1
#10 5.831 From https://github.com/moby/buildkit
#10 5.831  * [new tag]         v0.10.1    -> v0.10.1
#10 5.864 Initialized empty Git repository in …
```
> dockerfile2llb: consistent progress for HTTP and Git ops with ADD

- cache/remote.go
- cache/remotecache/v1/chains.go
- cache/remotecache/v1/parse.go
- solver/types.go
- util/contentutil/multiprovider.go
This reverts commit 55afcdbc0d64ec0a9f3d43b84ac5a84a8f080388.
#4558
closes https://github.com/moby/buildkit/issues/4685
Breaks stargz CI
```
=== FAIL: client TestIntegration/TestStargzLazyRegistryCacheImportExport/worker=containerd-snapshotter-stargz (3.15s)
client_test.go:4433: 
Error Trace:	/src/client/client_test.go:4433
/src/util/testutil/integration/run.go:93
/src/util/testutil/integration/run.go:207
Error:      	Target error should be in err chain:
expected: "not found"
in chain: 
Test:       	TestIntegration/TestStargzLazyRegistryCacheImportExport/worker=containerd-snapshotter-stargz
Messages:   	unexpected error <nil> on layer {MediaType:application/vnd.oci.image.layer.v1.tar+gzip Digest:sha256:51d2d8bd60757918ba85b62a1b87d7a61a6483a7d71f9a122e71223d06582379 Size:3422723 URLs:[] …
```
> Revert "util/multiprovider: Implement Info"

- hack/test
Found this when executing `hack/test dockerfile`, it complains that `TESTFLAGS` is unset.
> Fix case where TESTFLAGS may be unset

- client/llb/fileop.go
- docker-bake.hcl
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_test.go
- frontend/dockerfile/dockerfile2llb/exclude_patterns_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/docs/reference.md
- frontend/dockerfile/exclude_patterns_test.go
- frontend/dockerfile/instructions/commands.go
- frontend/dockerfile/instructions/exclude_pattern_feature.go
- frontend/dockerfile/instructions/parse.go
- frontend/dockerfile/release/labs/tags
Ref https://github.com/moby/buildkit/issues/4439
***note to the reviewers:*** this PR is essentially the re-creation of the closed PR https://github.com/moby/buildkit/pull/4440 , as I could not find a way to reopen it.
This PR introduces new options in the Dockerfile frontend, namely `--exclude` on `COPY` and `ADD` commands.
It essentially exposes the existing `ExcludePatterns` from the LLB to the frontend.
This PR affects only the cache **does not** prevent file which are excluded by the ADD or COPY commands to be added to the context.
I have manually tested the changes and they work as expected, but I have not yet added integration tests.
TODO:
More information in the related issue #4439.
> Dockerfile: Allow files to be excluded from cache on COPY and ADD commands

- examples/dockerfile2llb/main.go
- exporter/containerimage/exptypes/types.go
- exporter/containerimage/writer.go
- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_test.go
- frontend/dockerfile/dockerfile2llb/image.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerui/build.go
- util/converter/converter.go
The exporter fetches the base image config via the `ExporterImageBaseConfigKey` metadata to detect the immutable layer diffIDs and the history objects.
Fix #4614
NOTE: For a multi-stage Dockerfile like below, the base image refers to `busybox`, not to `foo`:
```dockerfile
FROM busybox AS foo
FROM foo AS bar
```
> Avoid applying `SOURCE_DATE_EPOCH` to base images

- cache/remote.go
- cache/remotecache/v1/chains.go
- cache/remotecache/v1/parse.go
- solver/types.go
- util/contentutil/multiprovider.go
This PR carries #4558 (reverted in  #4686), fixing the patch to pass CI.
Based on that PR, this PR adds a patch (ca58fc5e6a1df73ad276a8938f6b706209c41a2b) to fix `DescriptorProviderPair` to export methods used by multiprovider (`UnlazySession` and `SnapshotLabels`).
> [Carry 4558]  util/multiprovider: Implement Info

- go.mod
- go.sum
- vendor/go.etcd.io/bbolt/bolt_openbsd.go
- vendor/go.etcd.io/bbolt/bucket.go
- vendor/go.etcd.io/bbolt/db.go
- vendor/golang.org/x/sync/errgroup/go120.go
- vendor/golang.org/x/sync/errgroup/pre_go120.go
- vendor/modules.txt
full diff: https://github.com/etcd-io/bbolt/compare/v1.3.7...v1.3.9
> vendor: update go.etcd.io/bbolt to v1.3.9

- README.md
- docs/windows.md
This commit adds a quick guide for setting up Buildkit on Windows, now that we currently have an experimental support.
> docs: add quick guide for windows

- README.md
- cache/remotecache/gha/gha.go
related to https://github.com/moby/buildkit/actions/runs/8062307240/job/22024437641?pr=4698#step:7:1683
closes #4705
On repositories relying heavily on GitHub Actions Cache backend with BuildKit, it can take more than 5 minutes ([current default](https://github.com/tonistiigi/go-actions-cache/blob/0bdeb6e1eac762aa4c57a3e8ccc2fdfb68a3f3c4/cache.go#L145)) for the request to succeed due to GitHub rate limit or if export is quite huge (often sees with `mode=max`).
This PR adds a `timeout` attribute for GitHub Actions cache export/import (maybe import is not necessary) so user can specify a custom value if he wants to.
Also increases default timeout to 10 minutes.
If we are not ok with this change, we can just set `ignore-error=true` in our workflows to avoid failures on this repo, see …
> cache(gha): add timeout attr for cache export/import

- frontend/dockerfile/docs/reference.md
Restructure information about `ADD`/`COPY` flags,
describing flags/options in dedicated sections.
Also made some changes to `RUN` for sake of uniformity
Follow-up to #4561
Previews:
- Markdown: https://github.com/moby/buildkit/blob/0189bd0c4ef84c1ce79429308f939d4df6f1a430/frontend/dockerfile/docs/reference.md
- HTML: https://deploy-preview-19498--docsdocker.netlify.app/reference/dockerfile/
> docs: restructure descriptions for add, copy, run flags

- solver/llbsolver/file/unpack.go
Default changed in Moby25 archive package. Setting this bool restores the previous behavior.
> file: use best-effort xattr behavior on unpacking

- frontend/gateway/gateway.go
On some systems this causes permission error if userns enabled.
fix #4556
Tbh. I do not know exactly what restriction controls this (it doesn't repro in regular systems as described in the issue) but `nodev` is what is causing the `EPERM` in the repro. The others are added for completeness.
> gateway: mount metadata with nodev

- frontend/dockerfile/instructions/parse.go
Instead of ignoring the flag and copying wrong files the build should error if labs is not enabled.
> dockerfile: don't silently ignore --parents if not labs

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_parents_test.go
- frontend/dockerfile/docs/reference.md
- util/system/path.go
follow-up for #3001
Similarily to `rsync` `--relative` flag add support for `/./` pivot point to mark which parent directories as kept.
This is especially useful in multi-stage builds because `--from` paths need to be always full paths.
```
FROM ... AS base
RUN ./generate-lot-of-files -o /out/
FROM scratch
COPY --from=base --parents /out/./**/bin/ /
``` 
cc @DYefimov
> dockerfile: allow pivot point for --parents flag

- solver/jobs.go
Noticed this while in the area.
> chore: remove unneccessary parameter in newSharedOp

- client/client_test.go
- client/ociindex/ociindex.go
Addresses issue #4595 and adds appropriate test. Specifically, this catches the case where `tar=false`, which is not covered by the incoming containerd fix. ( It should also happen fix the issue more generally, but getting the containerd was the *correct* fix in the general case. 😄 )
> Add MediaType in `index.json` when `--out type=oci`

- client/llb/exec.go
- client/llb/exec_test.go
- client/llb/fileop.go
- client/llb/fileop_test.go
- client/llb/state.go
This is a possible fix for #4695. I am opening to run against CI, as I've had trouble running full tests locally
> Fix: Marshal Input Vertices in a consistent order

- solver/jobs.go
This lock has been moved into `WalkProvenance` in #3240 and #3938.
Pointed out by @alexcb in the Buildkit community slack [here](https://dockercommunity.slack.com/archives/C7S7A40MP/p1709595421446549).
> solver: remove unneccessary solver lock

- .github/workflows/validate.yml
On moby we have a special threshold for public runners iirc but on some private repos outside this org, the linting against multi-platform fails with:
```
The hosted runner: GitHub Actions 271 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```
This change will enable multi-platform lint only for this repo.
> ci: enable multi-platform lint only for upstream repo

- docs/windows.md
By default, a fresh Windows installation does not come with `containers` feature enabled since not all users usually need the feature. It is therefore provided as a _feature on demand (FoD)_.
This commit introduces the one-step powershell command that enables this feature. This is necessary for anything to run successfully.
> fix(docs): add the containers feature enabling step

- util/tracing/detect/delegated/delegated.go
- util/tracing/detect/detect.go
- util/tracing/detect/jaeger/jaeger.go
- util/tracing/detect/otlp.go
The original design for adding metric exporters accidentally relied on
the traces exporter variable for enabling or disabling the metrics
exporter. It's normal for metrics to get auto-enabled with the same
environment variables that traces use, but it should also respond to
`none` for disabling.
Fixes #4743.
> detect: fix auto-detection of metric exporters to handle none correctly

- docs/dev/remote-debugging.md
- hack/compose
- hack/composefiles/.gitignore
- hack/composefiles/README.md
- hack/composefiles/buildkitd.toml
- hack/composefiles/compose.yaml
- hack/composefiles/extensions/buildx.yaml
- hack/composefiles/otelcol.yaml
Configure the otel-collector for `hack/compose` to use it for processing traces and forwarding to jaeger. This simplifies the configuration and also opens up the ability to configure additional behavior around traces and metrics for debugging.
This also removes the automatic override file and the gitignore file. It wasn't really working well for me and made it difficult to share extensions to the development environment. I'm going to try something different for that in a different change.
> hack: configure the otel-collector for hack/compose

- frontend/dockerfile/docs/reference.md
BuildKit doesn't warn if a provided build argument is not consumed,
unlike the classic builder.
relates to:
- docker/docs#19565
- moby/buildkit#2128
> docs: remove mention that buildkit warns about unconsumned build args

- cache/remotecache/v1/chains.go
- cache/remotecache/v1/utils.go
fixes #4765
This method is needed by GHA cache backend to detect if Github deletes blobs from the cache because of
storage caps. It went missing when Info() support was added in #4558 for the same issue as https://github.com/moby/buildkit/pull/4558#discussion_r1502053565 . Later #4694 added back stargz method but not `CheckDescriptor`.
Overall we need to find a safer approach to this, especially because it is impossible to test because of being controlled by Github's storage. For this case, I think `CheckDescriptor` is not really needed anymore but can be replaced with `Info()` as commented in https://github.com/moby/buildkit/pull/4558#discussion_r1483429940 . But the stragz methods should not rely on interface detection either. The current PR is the minimal change that we can pick to …
> remotecache: fix missing CheckDescriptor method

- solver/llbsolver/solver.go
Fixes https://github.com/moby/buildkit/issues/4774.
Follow-up to https://github.com/moby/buildkit/pull/4040 (cc @thaJeztah) - this didn't resolve the access to `sysSampler.Close`, we need to stub this one out as well!
> solver: stub out sysSampler close

- util/gitutil/git_ref.go
- util/gitutil/git_ref_test.go
Fixes https://github.com/moby/buildkit/pull/4326#issuecomment-2000436261 (thanks @stephanos! :tada:)
URLs that look like `./path/to/file` and `../path/to/file` definitely aren't git URLs - so we should bail out early.
This was causing a weird issue where if you copied `./.git` this would be detected as a valid url parsing with `host = "."` and `path = "/git"`. The fix for this is to make sure that for these explicit file-like paths, we *never* parse them as url-refs.
Also some tests to make sure this doesn't break again!
> git: ensure file-looking git refs aren't parsed as URLs

- executor/oci/spec.go
mitigation for https://github.com/moby/buildkit/issues/4764
The source path changed in v0.13 and there are reports that new path can cause error on starting a container. While this is investigated, check for missing path and make mounting optional like it was in v0.12.
> oci: make mounting oci socket optional

- cache/remotecache/v1/chains.go
- cache/remotecache/v1/utils.go
- executor/oci/spec.go
- solver/llbsolver/solver.go
- util/gitutil/git_ref.go
- util/gitutil/git_ref_test.go
> [v0.13] v0.13.1 cherry-picks

- Dockerfile
Instead of hardcoding all possible architectures
that can be built, define RiscV as exception and
any other architecture use $ALPINE_VERSION tag.
> improve alpine version selection per arch

- cache/remote.go
- cache/remotecache/azblob/importer.go
- cache/remotecache/gha/gha.go
- cache/remotecache/v1/chains.go
- cache/remotecache/v1/utils.go
- util/contentutil/multiprovider.go
- worker/base/worker.go
This tries to replace the `CheckDescriptor` interface detection with the `Info()` method that was added in v0.13 to the provider to avoid cases like https://github.com/moby/buildkit/pull/4771 .
> remotecache: replace CheckDescriptor with Info

- cache/remotecache/gha/gha.go
- go.mod
- go.sum
- vendor/github.com/tonistiigi/go-actions-cache/cache.go
- vendor/github.com/tonistiigi/go-actions-cache/rest.go
- vendor/modules.txt
In order to avoid getting rate limited when checking if previous cache already exists use the Github REST API that supports listing active keys.
This means additional GITHUB_TOKEN access is also
needed in addition to the RUNTIME_TOKEN needed for the cache API. The implementation is done with a fallback - if GITHUB_TOKEN is passed then it is used, if not then the old method checking individual cache records is still used.
Depends on https://github.com/tonistiigi/go-actions-cache/pull/19
> gha: add support for batch checking existing keys

- cache/remotecache/inline/inline.go
fix https://github.com/moby/buildkit/issues/2274
When Moby adapters are used without containerd backend, the descriptors are lacking the original compressed layer digest and there is a workaround to link in the uncompressed digest. If a build exporting the cache also imported it from the registry then the original imported records with compressed digest needs to be exported as well. If there were another exported records that referred to the same layers via the uncompressed digest through parent layers then such records could be overwritten and the original provider from cache import could get lost.
> inline: fix uncompressed digest importing from multiple providers

- frontend/dockerfile/docs/reference.md
Fixes for `COPY` documentation and some other minor issues
Relates to
- https://github.com/docker/docs/issues/19500
- https://github.com/docker/docs/issues/19646
- https://github.com/docker/docs/issues/19670
- https://github.com/docker/docs/issues/19657
> docs: dockerfile copy fixups

- solver/llbsolver/solver.go
- util/tracing/detect/detect.go
- util/tracing/detect/recorder.go
The trace recorder is now a separate entity and does not wrap another span exporter. It is added as another span processor to the underlying tracer provider so the two can be disconnected from each other and this removes the need to use `detect.Exporter()` to find the TraceRecorder along with the need to invoke flush manually.
The trace recorder is wrapped with a simple span processor instead of the batch one. That makes the flushing irrelevant for this purpose.
The trace recorder itself is also modified to avoid leaking goroutines and respecting context cancellations.
This is part of a general refactor of the detect package to separate the buildkit-specific functionality from the external exporter detection.
> tracing: refactor the trace recorder

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/instructions/parse.go
- frontend/dockerfile/instructions/parse_test.go
- frontend/dockerfile/linter/linter.go
- frontend/dockerfile/linter/ruleset.go
We should define a set of rules for evaluating a good or bad Dockerfile. Create a method for evaluating the Dockerfile to ensure obvious issues are highlighted to the user.
This PR adds 3 additional lint warnings for the Dockerfile frontend:
- lowercased stage names
- lowercased command flag values
- consistently cased commands
These rules are definitely not the comprehensive list of linting warnings we should add, but instead represent an initial set, with more to come in additional PRs moving forward! 😄 
( This PR existed in a similar, previous PR #4751, but only implements the warnings. The additional `--print=lint` functionality will come in its own PR. 😄 )
> Add additional warnings for lint rules

- client/client_test.go
- executor/oci/spec.go
fix #4810
Historic layer limit for Docker images is 127. Because in overlayfs mounting 127 layers usually reaches the page size limit of mount options in Linux kernel, there is special code to work around the limitation.
This custom code was used for rootfs of container because runc takes rootfs as a directory path, meaning buildkit needs to mount it and then pass the path. For non-rootfs mounts runc takes them as direct mount configuration and performs the mount itself. As runc does not have this special way to mount long overlayfs mounts it will perform the mount with clipped options what will fail in some way in kernel depending on the precise cutoff point.
Workaround is to detect when the mount passed to runc is too long for runc to mount it itself and it that case let BuildKit mount …
> executor: fix overlay layer limit for non-rootfs mounts

- exporter/containerimage/writer.go
- frontend/dockerfile/dockerfile_test.go
> rewrite-timestamp: fix incompatibility with `COPY --link`

- util/converter/tarconverter/tarconverter.go
The archive reader was not fully consumed on computating the diffID.
Fix #4805
> util/converter: fix diffID computation

- Dockerfile
Silences the following warning:
```
1 warning found (use --debug to expand):
- Lint Rule 'FromAsCasing': 'as' and 'FROM' keywords' casing do not match (line 262)
```
> chore: fix casing in containerd-alt-16 stage

- solver/llbsolver/bridge.go
`err` is not set in this conditional branch, so the err check is unneccessary and so can be removed.
> chore: remove impossible err check

- frontend/dockerfile/instructions/commands.go
- frontend/dockerfile/instructions/parse.go
- frontend/dockerfile/instructions/parse_heredoc_test.go
- solver/llbsolver/history.go
- source/containerimage/ocilayout.go
- util/compression/compression.go
- util/compression/uncompressed.go
- util/iohelper/helper.go
In separate commits:
- Strsclice  - only difference from `[]string` is custom `Unmarshal` that we do not seem to use
- Healthcheck should not come from apitypes, but from spec types
- ioutils - different places were using different wrappers. Now all use the same. The code that previously used `pkg/ioutils` was not even correct iiuc as it called `Close()` on the error handler of `Read`.
> Remove unneeded dependencies from moby/moby

- .golangci.yml
- cache/blobs_linux.go
- hack/dockerfiles/lint.Dockerfile
- source/git/source.go
- util/imageutil/config_test.go
- util/overlay/overlay_linux.go
- util/system/path_test.go
Enable new nilness and unusedwrite linters that seem to be quite useful and did point to some actual issues.
> updates and fixes to linters

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/linter/linter.go
- frontend/dockerui/requests.go
- frontend/subrequests/lint/lint.go
Following on the footsteps of #4759, this adds support for an additional subrequest frontends can choose to implement for exposing linting errors and implements this subrequest for the `dockerfile` frontend.
> Print lint warnings

- frontend/dockerfile/dockerfile2llb/convert.go
- solver/llbsolver/file/backend.go
In the case for Windows, this line at `frontend/dockerfile/dockerfile2llb/convert.go#L1142` was adding the `\\` to a path that is already normalized to unix-format, hence ending up with `dest` paths like: `/\\` for `C:\\` and `/test\\` for `C:\\test\\`.
https://github.com/moby/buildkit/blob/fb97e6defdc171d943c304565eeb72794ea0a648/frontend/dockerfile/dockerfile2llb/convert.go#L1142
The `src` paths are well normalized too at ~L1290:
https://github.com/moby/buildkit/blob/fb97e6defdc171d943c304565eeb72794ea0a648/frontend/dockerfile/dockerfile2llb/convert.go#L1287
This change removes the block of code and instead does the "/" appending using the `keepSlash` logic
that is in `system.NormalizePath` called in `pathRelativeToWorkingDir` function before.
Additionally in …
>  fix: use unix path separator since windows path already normalized

- solver/llbsolver/solver.go
follow-up https://github.com/docker/buildx/pull/2280#discussion_r1558599748
Provenance set in build record does not currently set any builder id even if set through attestation attribute:
```json
{
"builder": {
"id": ""
},
"buildType": "https://mobyproject.org/buildkit@v1",
"materials": [
{
"uri": "pkg:docker/docker/dockerfile@1",
"digest": {
"sha256": "ac85f380a63b13dfcefa89046420e1781752bab202122f8f50032edf31be0021"
}
},
{
"uri": "pkg:docker/golang@1.21-alpine?platform=linux%2Famd64",
"digest": {
"sha256": "cd5189337d797eac9e2299dc07096c598cd4f4f73f068a033402f3ded7a51714"
}
},
{
"uri": "pkg:docker/tonistiigi/xx@1.4.0?platform=linux%2Famd64",
"digest": {
"sha256": "0cd3f05c72d6c9b038eb135f91376ee1169ef3a330d34e418e65e2a5c2e9c0d4"
}
}
]
}
```
I think we can infer this value from user …
> solver: infer builder id from user input for provenance in build record

- frontend/dockerfile/dockerfile_lint_test.go
These validations were added before https://github.com/moby/buildkit/pull/4761 and did not pass CI.
> dockerfile: fix validation errors in linter tests

- util/gitutil/git_ref.go
- util/gitutil/git_ref_test.go
Fixes https://github.com/moby/buildkit/issues/4777 (again - thanks @raylu), and fixes https://github.com/moby/buildkit/issues/4846. See where this regression was introduced: https://github.com/moby/buildkit/pull/4142/files#diff-1bb11d110027d34708083bbbd69dbd446eadf916857680c279a31038268163b6L59-L60
During git refactoring, git refs accidentally became significantly broader in definition - specifically, files like "foo.bar/test.git" - is this a git repo at "foo.bar", or a local git directory?
We need to restrict this a lot more, previously, we only did this clever conversion for the "github.com" prefix. This restores this previous behavior.
> git: restrict definition of git ref to previous behavior

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/linter/linter.go
Addresses #4851 by making it so that the specific style of "short" message that includes the line number isn't generated as part of the lint rule formatting, but rather as an additional step that the builder does (so we can still get that short style inline during the normal build process).
> avoid appending line info in lint detail

- frontend/subrequests/lint/lint.go
fixes #4844
This is a follow-up to #4761, and updates the printed source map for the lint warnings to be consistent with how they are displayed when viewing them via the `docker --debug` flag.
Old:
```
Lint Rule StageNameCasing
Dockerfile:2
Lint Rule 'StageNameCasing': Stage name 'buildER' should be lowercase (line 2)
2  |  FROM $BASE:1.20-alpine AS buildER
```
New:
```
- Lint Rule 'StageNameCasing': Stage name 'buildER' should be lowercase (line 2)
Stage names should be lowercase
Dockerfile:2
1 |     ARG BASE=golang
2 | >>> FROM $BASE:1.20-alpine AS buildER
3 |
4 |     WOrkdIR /go/src/github.com/restic/restic
```
> sort lint warning output and make consistent

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/diff_containerd.go
- vendor/github.com/tonistiigi/fsutil/diskwriter.go
- vendor/github.com/tonistiigi/fsutil/receive.go
- vendor/github.com/tonistiigi/fsutil/send.go
- vendor/modules.txt
Full diff: https://github.com/tonistiigi/fsutil/compare/7525a1af2bb5..497d33b
Summary changes:
- https://github.com/tonistiigi/fsutil/pull/195 receive: ensure callback errors are propagated
- https://github.com/tonistiigi/fsutil/pull/196 Fix file transfers from windows to linux fixes #4741
- https://github.com/tonistiigi/fsutil/pull/197 recv: translate linkname to wire format
> vendor:  github.com/tonistiigi/fsutil @ 497d33b

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_provenance_test.go
- frontend/dockerfile/dockerfile_test.go
The `COPY --link` command lost its source mapping to the original Dockerfile when converted to LLB vertex. Regression from https://github.com/moby/buildkit/commit/cc1499e6d92722ce55ef34a08dac964a1778b636#diff-905097ba6a4e36b3afbb1204e52315791dc0915f2a845c768bc84c6af5db1e1fR1075 progressgroup PR. 
@sipsma The previous code is clearly incorrect as it is copying to nil slice (that does nothing), but do check that I didn't miss any progressgroup logic.
> dockerfile: fix missing source mapping for COPY --link command

- cmd/buildkitd/config/gcpolicy.go
- cmd/buildkitd/config/gcpolicy_unix.go
- cmd/buildkitd/config/gcpolicy_windows.go
Initially we had the GC Policy for Windows use only 2 GB (2e9 bytes) of disk space and this was limiting for some build scenarios that need more than that, especially ServerCore images.
This commit makes the policy to use percentages as it is on Linux. Also going for 20%, double for that on Linux, since Windows images are generally larger. For instance, after the change, on a dev machine, the configured space was `74694367232 / (1 << 30) = 69.5 GiB`.
fixes #4858 docker/buildx#2411
---
**Before:**
```
> main.getGCPolicy() C:/dev/container-core/buildkit/cmd/buildkitd/main.go:875 (hits goroutine(1):1 total:1) (PC: 0x1e1347e)
870:                         All:          rule.All,
871:                         KeepBytes:    rule.KeepBytes.AsBytes(root),
872:                         KeepDuration: …
```
> fix: gc policy for windows to use 20% of disk space

- client/client_test.go
- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/hardlinks.go
- vendor/github.com/tonistiigi/fsutil/send.go
- vendor/modules.txt
fix moby/buildkit#4831
depends on https://github.com/tonistiigi/fsutil/pull/198
Brings in fix/test for hardlink filters.
> vendor: update fsutil to master@91a3fc4

- frontend/dockerfile/docs/reference.md
Use front matter to specify the doc title for the Dockerfile reference
in order to make the title programmatically accessible with Hugo, making
it easier to properly render the title in templates.
Specifying the title in the document directly means we have no control
over the rendering of the top-level heading.
> docs: dockerfile reference title in front matter

- util/tracing/detect/detect.go
Checking for detected exporters doesn't really work properly because of implicit exporters like the recorder and the prometheus metrics. Removing that line because it interfered with the correct initialization of the tracer provider in moby.
> detect: remove extraneous check for detected exporters

- cache/manager.go
The command `buildctl du—-filter=...` or the associated RPC supports a wider range of filters than the `prune` command.
```
> buildctl --addr unix:///var/lib/buildkit/buildkitd.sock du --filter='description~=".*go build.*"'
ID									RECLAIMABLE	SIZE	LAST ACCESSED
wt5gwgj5p8m7croouarjwp2vp*                                             	true       	1.49GB
k5ysmyy2eahyze4783hobeh3i*                                             	true       	1.49GB
kcae1sloyiibspvg0grlgukre*                                             	true       	1.48GB
> buildctl --addr unix:///var/lib/buildkit/buildkitd.sock prune --filter='description~=".*go build.*"'
Total:	0B
```
The expected behavior is that the `prune` command should match the same layers as the `du` command if they are reclaimable.
```
> buildctl …
```
> align prune with disk usage (du) command behaviour

- client/client_test.go
- cmd/buildkitd/config/config.go
- cmd/buildkitd/config/gcpolicy.go
- cmd/buildkitd/config/gcpolicy_unix.go
- cmd/buildkitd/config/gcpolicy_windows.go
- cmd/buildkitd/main.go
- cmd/buildkitd/main_unix.go
- cmd/buildkitd/main_windows.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_provenance_test.go
- frontend/dockerfile/dockerfile_test.go
- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/diff_containerd.go
- vendor/github.com/tonistiigi/fsutil/diskwriter.go
- vendor/github.com/tonistiigi/fsutil/hardlinks.go
- vendor/github.com/tonistiigi/fsutil/receive.go
- vendor/github.com/tonistiigi/fsutil/send.go
- vendor/modules.txt
- #4798
- #4865
~- #4872 (not merged)~
- #4863
- #4870
- #4875 
- #4880
> [v0.13] cherry-picks for v0.13.2

- frontend/dockerfile/dockerfile_test.go
Currently, several of the integration tests in `dockerfile_test` rely upon the `alpine:latest` image. This adds that image to the mirrored images to reduce the number of image pulls while running tests.
> Adds alpine:latest to mirrored images in dockerfile integration tests

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/subrequests/lint/lint.go
This PR updates the `lint` subrequest so that in the case of encountering a build error, it can return the lint warnings which occurred up to that point as well as the error message and source location where the error occurred.
It also updates tests, refactoring a bit to better accommodate for the increasing number of parameters to the `checkLinterWarnings` function.
> update lint subrequest to return build error

- util/progress/progressui/display.go
> rawjson output: remove indent so that every message is printed in one line

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/linter/ruleset.go
- frontend/dockerfile/shell/lex.go
- frontend/dockerfile/shell/lex_test.go
This adds another linting rule related to unmatched ARGs in the FROM command.
> add linting rules for undeclared args in from

- cache/contenthash/checksum.go
(This is a smaller patch split off from #4896 which should be trivial to review and allow me to get CI runs without needing approval each time I push a fixed version.)
<hr>
Using []byte for paths is just begging for a mistake to be made, so update the signature of convert{PathToKey,KeyToPath} so that only keys are []byte and paths are always strings.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
> contenthash: make all paths strings when converting

- util/progress/multireader.go
In the case where the context provided to MultiReader.Reader is cancelled, the writer will be deleted.
Before this, closeWriter was not called in that codepath, which meant that MultiReader.handle would never see the writer and never close it.
* I don't have an isolated repro, but when running a few hundred of Dagger's tests I was seeing several thousand goroutines blocked on waiting for the progress pipe's context to be done.
Now, we just call closeWriter when it gets deleted so that the pipe's goroutine doesn't leak.
* After this change, those thousands of leaked goroutines are entirely gone.
> progress: fix leak of pipe goroutine from MultiReader

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/linter/ruleset.go
This lint requires json arguments to be used when the `SHELL` command isn't used previously for `ENTRYPOINT` and `CMD`. This is because using non-json arguments can block signals from properly being handled when used in shell mode.
This uses the `Shell` attribute on the image configuration and therefore
requires the stage to be included in the build for it to properly run.
This is done because we don't want to force image config resolution on
every stage even if the stage isn't part of the build, but the only way
to definitively know if a custom shell is set is to look at the image
configuration.
> linter: add lint rule for required json arguments

- cache/remotecache/s3/s3.go
Hello there !
This allows to have a more flat memory usage.
I took the insides of ReadBlob, to make it streamable:
https://github.com/moby/buildkit/blob/70db2a6bc609403eb0b7dd146294d7aedc4c1990/vendor/github.com/containerd/containerd/content/helpers.go#L58-L83
In our case the code is a little bit modified further in the sense that we allow to have 5 uploads at once, which exacerbated this even more.
The s3 uploader seems to make use of the ReadSeeker to do multipart uploads, hence why I implemented `ReadSeekerFromReaderAt`. I wish s3 would also handle ReaderAts.
https://github.com/moby/buildkit/blob/8d017a2b62a67692dd00996745e1de97b9703aca/vendor/github.com/aws/aws-sdk-go-v2/feature/s3/manager/upload.go#L577
Edit: Here are some logs with GC logs on:
Before(same image):
```
#31 preparing …
```
> s3: stream a layer to s3 if possible, instead of getting it then sending it

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/linter/ruleset.go
- frontend/dockerfile/shell/lex.go
- frontend/dockerfile/shell/lex_test.go
This adds a lint rule that warns when an `$VARIABLE` inside a dockerfile is unmatched within the context of the command.
> Add undefined arg lint rule

- frontend/dockerfile/dockerfile_lint_test.go
This removes the copy-pasta build-arg passed in as a frontend option in the dockerfile lint teste.
> removes the extra build-arg in dockerfile lint tests

- frontend/dockerfile/dockerfile_test.go
A tag needs to be set for the tag to be created on the mirror. Otherwise new registry access is needed to recreate the tag on repeated runs.
> dockerfile: fix test mirror config bullseye-slim

- util/testutil/integration/run.go
Currently some tests like TestSSHFileDescriptorsClosed can leak helper processes. Canceling the sandbox context sends sigkill to such processes.
> testutil: make sure context is canceled after test end

- cmd/buildkitd/config/config.go
- cmd/buildkitd/main.go
- docs/buildkitd.toml.md
- frontend/gateway/gateway.go
- frontend/gateway/gateway_test.go
This commit adds buildkitd configuration options `allowed-frontends` and `allowed-gateway-source`.  These options enable restricting the allowed frontends or gateways sources to enforce local policy.
If allowed-frontends is empty (the default), all frontends (e.g, "dockerfile.v0" and "gateway.v0") are allowed.  Otherwise, only those listed are allowed
If allowed-gateway-sources is empty (the default), all gateway sources are allowed.  Otherwise, only sources that match the patterns in this list will be allowed.  Patterns are matched using
<https://pkg.go.dev/github.com/moby/buildkit/util/wildcard>.  Note that implicit references to docker.io should not be used in the patterns since matching occurs on a fully expanded image name (for example "docker/dockerfile" expands to …
> buildkitd: Frontend restriction support

- cmd/buildkitd/main.go
- docs/windows.md
This commit is a follow up of #4875, documenting the user of `--group` flag and `grpc.SecurityDescriptor` toml config.
Also does a minor fix on the `help` for `--group` to specify Windows named pipe alongside Unix socket.
> docs: add documetation for --group and SecurityDescriptor config

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/linter/ruleset.go
This linter rule catches when ENTRYPOINT, CMD, and HEALTHCHECK are used
multiple times in the same stage. This is because the last usage of each
of these overrides the other usages which makes it so the earlier usage
is ignored and unnecessary.
> linter: add rule to catch multiple conflicting instructions used in the same stage

- cmd/buildkitd/config/gcpolicy_openbsd.go
Here a small adjustmend for OpenBSD's syscall.Statfs_t which is backport of https://github.com/openbsd/ports/blob/9c2aaca13bf333ac228677736b42f31cba441edd/sysutils/docker-buildx/patches/patch-vendor_github_com_moby_buildkit_cmd_buildkitd_config_gcpolicy_unix_go
> Adjusts syscall.Statfs_t for OpenBSD

- solver/llbsolver/solver.go
20 sec stall on an platter old hdd is not unexpected. Nor is 20s write on a low-tier cloud environment drive unexpected.
300s should however be enough to tell the difference between crappy hardware/environment and actual failure.
fixes #4327
> fix: 20 sec timeout for write to disc too short

- cache/remote.go
- solver/llbsolver/history.go
- solver/llbsolver/solver.go
Currently there is a temp lease creation in `GetRemotes()` called from exporters, cache-exporting, and provenance creation and gets called for every cache result when walking the graph. 99% time it returns nil or reference to blob that already existed but temp lease is needed for the odd case where it needs to create new blobs to make sure the code does not go to race against containerd GC. Although it looks like creating a lease is just `context.WithValue` it is actually quite expensive as it is written into containerd boltdb. This improves performance in this case by creating a single temp lease for the whole export phase of a single job so calls inside `GetRemotes()` don't need to create their own one for safety.
> llbsolver: create single temp lease for exports for performance

- hack/composefiles/compose.yaml
- hack/composefiles/datasources.yaml
- hack/composefiles/extensions/buildx.yaml
- hack/composefiles/grafana.ini
- hack/composefiles/prometheus.yml
Starts a prometheus server that automatically scrapes buildkit for metrics using the `/metrics` endpoint. Also configures a grafana instance to use prometheus as the default connection.
> hack: add prometheus and grafana to hack/compose

- cmd/buildkitd/main.go
- frontend/gateway/gateway.go
- frontend/gateway/grpcclient/client.go
fixes #4948
Correct app default should be 16MB but were control API and frontends used library defaults.
> ensure correct grpc max sizes for control API and frontends

- frontend/dockerfile/dockerfile2llb/convert.go
Avoid duplicates and exponential complexity in cases where there are lots of stages.
Discovered this while looking at the giant Dockerfile from https://github.com/moby/buildkit/issues/4948 .
> dockerfile: improve detection of reachable stages

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/linter/ruleset.go
- util/suggest/error.go
Improve the error messages for error messages if FROM flags if they are caused by mismatched variables.
Additional commits improve the messages for UndeclaredArgInFrom and UndefinedVar warnings.
Example:
```
Dockerfile:1
1 | >>> FROM --platform=$BULIDPLATFORM alpine
2 |     RUN apk add git
3 |
ERROR: failed to solve: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
```
```
Dockerfile:1
1 | >>> FROM --platform=$BULIDPLATFORM alpine
2 |     RUN apk add git
3 |     
ERROR: failed to solve: empty platform value from expression $BULIDPLATFORM (did you mean BUILDPLATFORM?)
````
> dockerfile: improve error messages and add suggest to flag parsing

- cmd/buildkitd/config/config.go
- cmd/buildkitd/main.go
- docs/buildkitd.toml.md
- util/archutil/detect.go
- worker/base/worker.go
Because detecting emulator changes can be relatively expensive, avoid doing it very frequently. A new config parameter allows controlling if users prefer more or less frequent updates or want to disable detecting changes completely and only rely on emultor configuration at boot time.
> allow controlling detected platforms cache timeout

- solver/exporter.go
- solver/llbsolver/provenance.go
- solver/types.go
closes #4942
Backlink walking should not be needed to determine layers for current build and should be safe to skip. This improves performance of provenance creation for certain builds.
I consider this only a quick mitigation. It seems likely that there is an issue with walking all cache chains on export that shows up on specific builds that needs further investigation.
> allow skipping backlinks where walking cache chains for provenance

- go.mod
- go.sum
- util/progress/progressui/display.go
- util/progress/progressui/init.go
- vendor/github.com/tonistiigi/vt100/vt100.go
- vendor/modules.txt
In order to print tty output, the termHeight for the vt100 module needs to be between 6 and (current window size - 7).
Fixes #4766.
> Add bounds to termHeight when BUILDKIT_TTY_LOG_LINES is set

- util/resolver/resolver.go
Synchronize with version in containerd which includes multiple fixes such as handling body after fallback, handling handshake timeouts, and connection refused when using default ports.
Once all fixes are backported to containerd 1.7 or buildkit updates to containerd 2.0, the fallback can be replaced with containerd's version.
Closes #4915 
Related to https://github.com/containerd/containerd/pull/10286
> Fix http fallback

- solver/jobs.go
- solver/scheduler.go
- solver/scheduler_test.go
Before this, it was possible for an edge merge to happen to a target
edge/state that is no longer in the actives map, e.g.
1. Job A solves some edges
2. Job B solves some edges that get merged with job A's edges
3. Job A is discarded
4. Job C solves some edges that get merged with job B's edges, which
recursively end up merging to job A's, which no longer exist in the
actives map.
While this doesn't always result in an error, given the right state and
order of operations this can result in `getState` or `getEdge` being
called on the "stale" edges that are inactive and an error. E.g. if a
stale dep transitions from desired state `cache-fast` to `cache-slow`,
the slow cache logic will call `getState` on it and return a `compute
cache` error.
I also *suspect* this is the same root cause …
> solver: prevent edge merge to inactive states

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: avoid ignoring errors global arg expansion

- .golangci.yml
- cache/manager_test.go
- cache/metadata/metadata_test.go
- client/client_test.go
- client/llb/fileop_test.go
- client/llb/llbbuild/llbbuild_test.go
- client/llb/llbtest/platform_test.go
- control/control_test.go
- executor/oci/mounts_test.go
- executor/resources/io_test.go
- frontend/dockerfile/dockerfile2llb/convert_test.go
- frontend/dockerfile/dockerfile_outline_test.go
- frontend/dockerfile/dockerfile_provenance_test.go
- frontend/dockerfile/dockerfile_targets_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/instructions/parse_test.go
- session/filesync/filesync_test.go
- solver/llbsolver/mounts/mount_test.go
- source/git/source_test.go
- sourcepolicy/engine_test.go
- util/apicaps/caps_test.go
- util/converter/tarconverter/tarconverter_test.go
- util/flightcontrol/flightcontrol_test.go
- util/progress/progress_test.go
- util/resolver/resolver_test.go
- util/throttle/throttle_test.go
- worker/runc/runc_test.go
~depends on #4931 (only last commit new)~
This does not cover all warnings yet but split into chunks to ease review. There are quite a lot of updates needed so we can do them in multiple PRs so that there isn't a big review or bad rebase needed.
> lint: fix some testifylint warnings

- client/build_test.go
- client/client_test.go
- exporter/verifier/opts.go
- exporter/verifier/platforms.go
- solver/llbsolver/solver.go
Check that the result returned from the frontend
matches the user request conventions and show a
warning if it doesn't.
I'll be following up to this with verification on image metadata (if image is exported) as well. Currently, in some cases image platform gets reset even if using `FROM --platform` and a new metadata field would need to be passed from Dockerfile, so leaving this to future changes.
> verifier: verify platforms of the build result

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/linter/ruleset.go
Detect the case where the resolved base image does not match the expected platform from request. This can happen in two main cases:
- Single arch image manifest for a wrong platform than expected by the build
- Wrong metadata info in the image config (common for cross-compiled images pre buildkit and `--platform` flag).
Fixes https://github.com/docker/buildx/issues/844
This isn't directly a linter issue as Dockerfile is not using a wrong command/flag but the base image is problematic. I still used the same naming schema but we probably don't want to include it in the rules docs.
> dockerfile: detect base image with wrong platform being used

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/instructions/parse.go
- frontend/dockerfile/linter/linter.go
- frontend/dockerfile/parser/directives.go
- frontend/dockerfile/parser/directives_test.go
- frontend/dockerui/config.go
Implements most of #4919  (the `check-skip` directive for skipping a specific is omitted as follow up work in a forthcoming PR)
> Add Lint Controls

- solver/bboltcachestorage/storage.go
There are some reports that the nosync configuration of the boltdb can
cause panics on restarts due to corruption of the database. Mitigate by
panic recovery until there is a better solution.
> bboltcachestorage: mitigate corrupt boltdb cache after panic

- docs/windows.md
Adds details on how to quickly set up CNI / networking for Windows, and hooking it with `buildkitd` using the `--containerd-cni-config-path` and `--containerd-cni-binary-dir` flags.
Also adds a note on running `buildkitd` as a Windows Service.
fixes #4960
> docs: add details for setting up CNI for windows

- frontend/dockerfile/dockerfile2llb/convert.go
If base was not reachable then the config was not loaded in and the platform to compare with is not correct.
> dockerfile: make sure stage is reachable before validating base

- frontend/subrequests/lint/lint.go
Updates the output of the `PrintLintViolations` to begin with the violation rule name, print the ULR inline to the name if it exists, and remove the printing of the `Detail` field, which is redundant when printing the `Description`.
Old:
```
- 'as' and 'FROM' keywords' casing do not match
The 'as' keyword should match the case of the 'from' keyword
Dockerfile:1
1 | >>> FROM scratch as base
2 |     copy Dockerfile .
3 |
- Command 'copy' should match the case of the command majority (uppercase)
All commands within the Dockerfile should use the same casing (either upper or lower)
Dockerfile:2
1 |     FROM scratch as base
2 | >>> copy Dockerfile .
3 |
4 |
```
Updated:
```
FromAsCasing
The 'as' keyword should …
```
> Update PrintLintViolations output

- util/stack/stack.go
- util/tracing/tracing.go
Use the pkg/errors and stack package interface to check for a stack. Use the standard library methods to unwrap errors.
> Update tracing check for whether error has stack

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
fix #4988
When linter subrequest is sent without target, the expected behavior is to check full Dockerfile, not only the last target. During build the warnings are unchanged.
Some issues with this:
- Some rules are not scoped by specific stages atm. Some like casing may be more expected than others like the `ENV key value` syntax.
- If the last stage is unnamed there isn't currently a way to check only that one with subrequest.
> dockerfile: default linter to run on all stages by default

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
- cache/contenthash/path.go
- cache/contenthash/path_test.go
This series fixes the symlink following implementation of `cache/contenthash`. The primary issue with the previous implementation is that it assumed that `path.Join` is a reasonable way of implementing trailing symlink following -- this is not correct on Linux. `path.Clean` is a Plan9-ism, and while it is useful, on Linux symlinks are resolved left-to-right and thus lexically transforming `a/b/../c` to `a/c` is incorrect if `b` is a symlink. [The paper describing Plan9's `path_clean` makes reference to this Unix-ism they fixed by removing symlinks from Plan9.](https://9p.io/sys/doc/lexnames.html)
As the trailing symlink logic was written in quite a few places, all of the implementations needed to be fixed. The headline changes are:
* All of the symlink following implementations are now …
> contenthash: implement proper Linux symlink semantics

- solver/llbsolver/proc/provenance.go
- solver/llbsolver/proc/sbom.go
- solver/llbsolver/solver.go
Add more OpenTelemetry spans to track the time for exporters, attestations and history record creation.
> llbsolver: add more otel spans for export and history

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/instructions/commands.go
- frontend/dockerfile/instructions/parse.go
This modifies the linter to only report the legacy key/value format if the stage is reachable to be more compatible with the other lints that operate this way.
Instead of reporting the warning in the parser, it records whether a delimiter is present in the KeyValuePair and this gets checked when the dispatch happens.
> dockerfile: only report legacy key/value format when stage is reachable

- go.mod
- go.sum
- vendor/github.com/distribution/reference/README.md
- vendor/github.com/distribution/reference/normalize.go
- vendor/github.com/distribution/reference/reference.go
- vendor/modules.txt
full diff: https://github.com/distribution/reference/compare/v0.5.0...v0.6.0
- remove deprecated SplitHostname
- refactor splitDockerDomain to include more documentation
- fix typo in readme
- Exclude domain from name length check
> vendor: github.com/distribution/reference v0.6.0

- util/flightcontrol/flightcontrol.go
- util/flightcontrol/flightcontrol_test.go
We had a report of https://github.com/moby/buildkit/issues/1822 error showing up in some logs.
Possibly important aspect of this race seems to be that callbacks returning errors are handled differently and retry happens right away when previous callback has errored in the beginning of `wait()`. This was not handled by previous contention test. With the new test it is easy to reach timeout with ~100 goroutines (and smaller with reduced probability).
This patch reduces the backoff factor so it does not increase too quickly and adds a random factor to initial timeout so that when lots of goroutines hit the error at the same time, they do not all retry at the same time as well. This seems to dramatically reduce the maximum backoff that can be reached by generating contention with the new …
> flightcontrol: protect contention timeouts

- client/client_test.go
- control/control.go
- exporter/containerimage/export.go
- exporter/exporter.go
- exporter/local/export.go
- exporter/oci/export.go
- exporter/tar/export.go
- frontend/dockerfile/dockerfile_provenance_test.go
- solver/llbsolver/solver.go
Since multiple exporters support https://github.com/moby/buildkit/pull/4134 in BuildKit 0.13, `Record.Exporters` is not set anymore.
This is related to the `Type` and `Attrs` fields not being set in the `llbsolver.ExporterRequest`: https://github.com/moby/buildkit/pull/4134/files#diff-0397d42d692ad676389ccf4b5a1126a3976ef69d4342b8423a6bbb51d21a9181L458-L459
But this is used when we want to set the `Exporters` for the build history: https://github.com/moby/buildkit/blob/eed17a45c62b2d6e26273e4ead7e177fb7022338/solver/llbsolver/solver.go#L176
To fix this, I have updated the `exporter.ExporterInstance` interface to expose attributes and name of the exporter. Also removes `Type` and `Attrs` fields `ExporterRequest` that don't seem used anymore.
> history: fix empty Exporters attribute

- .github/workflows/.test.yml
- .github/workflows/test-os.yml
related to https://github.com/moby/buildkit/pull/4938#discussion_r1621031729
this is actually the other way around, we need to "enable" the `disable_file_fixes` opt: https://docs.codecov.com/docs/cli-options#do-upload
Example:
> ci: enable disable_file_fixes in codecov action

- Dockerfile
full diff: https://github.com/opencontainers/runc/compare/v1.1.12...v1.1.13
Release notes:
* If building with Go 1.22.x, make sure to use 1.22.4 or a later version.
* Support go 1.22.4+.
* runc list: fix race with runc delete.
* Fix set nofile rlimit error.
* libct/cg/fs: fix setting rt_period vs rt_runtime.
* Fix a debug msg for user ns in nsexec.
* script/*: fix gpg usage wrt keyboxd.
* CI fixes and misc backports.
* Fix codespell warnings.
* Silence security false positives from golang/net.
* libcontainer: allow containers to make apps think fips is enabled/disabled for testing.
* allow overriding VERSION value in Makefile.
* Vagrantfile.fedora: bump Fedora to 39.
* ci/cirrus: rm centos stream 8.
> update runc binary to v1.1.13

- identity/randomid.go
It's only used in a panic, so the additional functionality of pkg/errors is unlikely needed for this. While at it, also removing an unneeded import alias.
> identity: remove pkg/errors

- exporter/containerimage/export.go
- frontend/dockerfile/dockerfile_test.go
> Fix content not found with `push=true,rewrite-timestamp=true`

- frontend/subrequests/lint/lint.go
Old Output
```
[+] Building 0.1s (2/2) FINISHED                                                                                                         docker-container:dev
=> [internal] connecting to local controller                                                                                                            0.0s
=> [internal] load build definition from Dockerfile                                                                                                     0.0s
=> => transferring dockerfile: 171B                                                                                                                     0.0s
FromAsCasing - https://docs.docker.com/go/dockerfile/rule/from-as-casing/
The 'as' keyword should match the case of the 'from' keyword
Dockerfile:1 …
```
> Adds 'WARNING' prefix to the rule check output

- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
During code maintenance, I realized that the function `Dockefile2Outline` seems to be misspelled, it should be `Dockerfile2Outline`
> Spelling correction

- frontend/dockerfile/dockerfile2llb/convert.go
Currently, when we initialize a new `dispatchState`, `buildArgs` are not carried forward from the `base`.
This causes a subtle issue while linting where a Dockerfile such as
```
FROM alpine AS declared
ARG foo
COPY $foo .
FROM declared AS dependent
COPY $foo .
```
Will erroneously emit a `UndeclaredVariable` linting warning for the occurrence of `$foo` in the `dependent` stage.
This updates `dispatchState` to initialize `buildArgs` from its base.
> Initialize build args from stage base

- cmd/buildkitd/config/config.go
- cmd/buildkitd/main_containerd_worker.go
- docs/buildkitd.toml.md
- worker/containerd/containerd.go
- worker/containerd/containerd_test.go
Using the `runc.v2` runtime, it is possible to configure containerd to start runc with the "systemd_cgroup" flag. This will cause runc to use systemd to manage the container cgroups. For this configuration to work, runc needs the cgroup name to be of a special form: `<systemd.slice>:<parent>:<name>`. This is already implemented in the containerd runtime package, provided that a parent cgroup of the form `<systemd.slice>:<parent>:` is set.
This commit adds the option to configure such a parent cgroup for the containerd worker. By default, it will still use an empty string as cgroup parent, keeping existing behaviour.
Using a configuration like:
```toml
[worker.containerd]
defaultCgroupParent = "system.slice:buildkit:"
[worker.containerd.runtime]
name = "io.containerd.runc.v2" …
```
> containerd: add option to set parent cgroup

- frontend/dockerfile/linter/linter.go
- frontend/subrequests/lint/lint.go
Currently, the `PrintLintViolations` output warning text includes the static description of the lint rule, rather than the formatted text message that often includes context specific to a given instance of rule violation.
This updates `PrintLintViolations` to print out the formatted lint message instead. Below is an instance where you can see the difference in the types of output.
Current:
```
UndefinedVar - https://docs.docker.com/go/dockerfile/rule/undefined-var/
Variables should be defined before their use
Dockerfile:3
1 |     FROM alpine
2 | >>> ENV PATH=$PAHT:/foo
3 |
```
New:
```
UndefinedVar - https://docs.docker.com/go/dockerfile/rule/undefined-var/
Usage of undefined variable '$PAHT' (did you mean $PATH?)
Dockerfile:3 …
```
> Updates lint output to print detail instead of description

- frontend/dockerfile/shell/lex.go
- frontend/dockerfile/shell/lex_test.go
Avoid nil dereference when variable replacements/trims are used with empty string argument.
> shell: handle empty string for var replacements

- cache/blobs_linux.go
- cache/manager.go
- cache/manager_test.go
- cache/refs.go
- cache/remote.go
- client/build_test.go
- executor/containerdexecutor/executor.go
- executor/runcexecutor/executor.go
- exporter/containerimage/export.go
- exporter/oci/export.go
- frontend/gateway/gateway.go
- solver/combinedcache.go
- solver/llbsolver/file/refmanager.go
- solver/llbsolver/history.go
- solver/llbsolver/ops/file.go
- solver/llbsolver/solver.go
- source/containerimage/pull.go
- source/git/source.go
- source/http/source_test.go
- source/local/source.go
Most of them only have impact if `context.Value()` is needed but did discover couple of potential bugs as well.
> ensure context.WithoutCancel in defer funcs

- client/llb/async.go
- client/llb/state.go
- frontend/dockerui/config.go
- util/flightcontrol/cached.go
- util/flightcontrol/cached_test.go
This adds an additional version of `flightcontrol.Group` that caches previous results and returns earlier result if callback was already called for the same key.
Also refactor `llb.Async` and `dockerui` to use the new group. There are more cases that can be updated in follow-ups, for example in solver and puller, when implementing https://github.com/moby/buildkit/issues/4971 and rewriting https://github.com/docker/buildx/blob/v0.15.0/build/driver.go#L50-L60 .
Initially, this version was not used because without generics, it would have been quite hacky to do the `interace{}` type casts everywhere.
> flightcontrol: add cachedgroup struct

- cmd/buildkitd/main_containerd_worker.go
- cmd/buildkitd/main_containerd_worker_unix.go
- cmd/buildkitd/main_containerd_worker_windows.go
address #5056
Split out the code for `getRuntimeOptionsType` so as to reduce the unnecessary imports, hence binary size.
> refactor: split containerd runtime options definions by OS

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
Commit f724d6fb0504 ("contenthash: implement proper Linux symlink semantics for needsScan") fixed issues with needScan's handling of symlinks, but the logic used to figure out if a parent path is in the cache was incorrect in a couple of ways:
1. The optimisation in getFollowSymlinksCallback to avoid looking up / in the cache lead to the callback not being called when we go through /. The upshot is that needsScan(/non-existent-path) would always return true because we didn't check if / has been scanned.
2. Similarly, the logic of skipping a cache lookup if the path is the same as the current path meant that we skipped the first / lookup (because we start with currentPath=/).
3. Because needsScan would only store the _last_ good path, cases with symlink jumps to non-existent paths within …
> contenthash: improve the correctness of needsScan

- source/git/source.go
- source/git/source_test.go
On commit SHA input we currently do a full fetch of remote so we can pick up the commit by SHA later. This only pulls in tags that are also part of branches. Extra flag is needed to also get the tags that are not part of branches.
> git: fix pulling commit SHA only referenced from a tag

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/linter/linter.go
- frontend/dockerui/config.go
This refactors the `parseLintOptions` to be an exported function in the `linter` package, which allows us to pass the `linter.Config` from the dockerfile ui as a struct, rather than a to-be-parsed string, and moves linting functionality into its designated package.
> Move parseLintOptions into linter package

- cmd/buildkitd/main_containerd_worker.go
- executor/containerdexecutor/executor.go
- worker/containerd/containerd.go
- worker/containerd/containerd_test.go
The function parameters of `containerd.NewWorkerOpt` and `containerdexecutor.New` are too long making it hard to read. This PR condenses the parameters into a singular struct. 
The struct naming could be adjusted, but since I'm not too familiar with the code I tried to stick with something similar to the package and function name. 
Based off of this discussion https://github.com/moby/buildkit/pull/5033#discussion_r1638659585
> Refactor containerd `NewWorkerOpt` & containerdexecutor `New` parameters

- frontend/dockerfile/linter/linter.go
Implements: https://github.com/moby/buildkit/issues/5082
This adds a `IsDeprecated` function to the `LinterRuleI` interface, and skips running a rule if `IsDeprecated` returns true. It also implements this function for the `LinterRule` type.
> Adds a deprecated flag to linter rules

- source/containerimage/ocilayout.go
- relates to https://github.com/containerd/containerd/pull/10394
- relates to https://github.com/containerd/containerd/pull/10393
We already have a `reference.Spec` and `reference.Spec.Digest()` does exactly this. In addition, buildkit was the only external consumer of the `reference.SplitObject` function, and it may be deprecated and removed for containerd 2.0.
> ociLayoutResolver.info: remove use of reference.SplitObject

- frontend/dockerfile/docs/rules/multiple-instructions-disallowed.md
- frontend/dockerfile/linter/docs/MultipleInstructionsDisallowed.md
The example for the multiple instructions rule used shell form, changed it to exec form.
> docs: use json args in multiple instructions example

- exporter/tar/export.go
- exporter/tar/export_unix.go
- exporter/tar/export_windows.go
- session/filesync/diffcopy.go
- session/filesync/diffcopy_unix.go
- session/filesync/diffcopy_windows.go
fixes #4985 
Windows has some special / metadata files that [need special privileges to access](https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/privileges), even if the process is running as Admin.
Some of those files (across `nanoserver` and `servercore`) currently are:
```
\\Program Files\\Windows Defender Advanced Threat Protection\\Classification\\Configuration
\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\Cache
\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\Cyber
\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\DLP
\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\DataCollection
\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\Downloads …
```
> fix: acquire privileges to access special files on windows

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
In my previous fix on #4825, I had removed this line knowing that all that had been addressed in `pahtRelativeToWorkingDir`:
```go
if cfg.params.DestPath == "." // <-- this one
|| cfg.params.DestPath == ""
|| cfg.params.DestPath[len(cfg.params.DestPath)-1] == filepath.Separator {
dest += string(filepath.Separator)
}
```
However, I had overlooked the `"."` and `""` scenarios. `""`. The  `"/"`case is handled correctly in `system.NormalizePath()`.
This change therefore undoes this, to make sure "." is transformed correctly to "./" during COPY operation, same to "" -> "./". This is important especially for WORKDIR that are not `/`, so that `COPY --link` operations are handled properly.
fixes #5070
> fix: dot and empty paths normalized correctly for COPY to WORKDIR

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/docs/rules/_index.md
- frontend/dockerfile/docs/rules/redundant-target-platform.md
- frontend/dockerfile/linter/docs/RedundantTargetPlatform.md
- frontend/dockerfile/linter/ruleset.go
Adds a linter check that checks if `--platform=$TARGETPLATFORM` is used and sends a linter message marking this as redundant. This is because `$TARGETPLATFORM` is the default.
> checks: add redundant target platform check

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_addchecksum_test.go
- frontend/dockerfile/docs/reference.md
Docs and error message didn't indicate whether checksum was supported for HTTPS.
- Addresses docker/docs#20159
> dockerfile: clarify that checksum works with HTTPS

- executor/runcexecutor/executor.go
If context is canceled before the process is ready then kill goroutine returns early because there is nothing to kill. But the process may still start after this and in that case remain running without cancellation. Fix is to skip cancellation only if the run goroutine is ended, as then the process will not be started.
> executor: fix cancellation before start signal

- cache/remotecache/s3/s3.go
- executor/runcexecutor/executor.go
- exporter/attestation/unbundle.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/parser/line_parsers.go
Fixes cases where `json.Decoder` was improperly used for parsing JSON values. `Decode()` only parses the next object and does not check if there is additional content after it (unlike `Unmarshal()`).
In Dockerfile it meant that currently invalid commands like this would cause no error and skip over the invalid bytes:
```
RUN ["ls"]random symbols in here
ENTRYPOINT []<-this is JSON array
```
> fix incorrect usage of json.NewDecoder

- Dockerfile
Update the containerd binary that's used in CI.
- release notes: https://github.com/containerd/containerd/releases/tag/v1.7.19
- full diff: https://github.com/containerd/containerd/compare/v1.7.18...v1.7.19
Welcome to the v1.7.19 release of containerd!
The nineteenth patch release for containerd 1.7 contains various updates and splits the main module from the api module in preparation for the same change in containerd 2.0. Splitting the modules will allow 1.7 and 2.x to both exist as transitive dependencies without running into API registration errors. Projects should use this version as the minimum 1.7 version in preparing to use containerd 2.0 or to be imported alongside it.
Highlights
- Fix support for OTLP config
- Add API go module
- Remove overlayfs volatile option on temp mounts
- …
> update containerd binary to v1.7.19

- frontend/gateway/gateway.go
- frontend/gateway/grpcclient/client.go
- session/grpc.go
- util/leaseutil/manager.go
This prevents cases where the returned nil context ends up overwriting another context in the caller which can mess up defers.
Ex:
```go
ctx := context.Background()
defer func() {
cleanup(ctx)
}()
ctx, done, err := leaseutil.WithLease(...)
```
In this cae when `leaseutil.WithLease` has an error, before this change the returned context is nil.
The solver this can trigger a panic when the context is cancelled because leaseutil will error out and then a prior defer function will call `context.WithoutCancel(ctx)` triggering the panic because context should never be nil.
leaseutil seems like the only place this was problematic but changed a couple of other places I found to make sure they don't cause problems if the caller changes in the future.
> Always return non-nil contexts

- frontend/dockerfile/docs/reference.md
- relates to https://github.com/moby/buildkit/issues/2173
The section describing `-P` / `--publish-all` was moved to the CLI run command reference, so updating the link.
Als updated a link caption that was using "here" as caption, which makes it harder to spot the link.
> docs: dockerfile-reference: fix links

- source/git/source_test.go
- source/git/source_unix_test.go
- util/gitutil/git_cli.go
Alternative to #5092, fixes #5066.
This option is already correctly specified in `gitCLI`, the call chain looks like:
- `gitutil.NewCLI(..., gitutil.WithExec(runWithStandardUmask))` called in `gitCLI`
- `gitCLI` called in `mountRemote`
- `git.New` called in `mountRemote`
The `exec` field specified by `WithExec` from the first `NewCLI` call should propagate down to `git.New` - but this wasn't being done, I clearly missed this somehow.
> git: ensure exec option is propagated to child git clis

- solver/bboltcachestorage/storage.go
If the result exists but the link has been deleted, it will cause the result to never be released, ultimately leading to data leakage.
> bboltcachestorage: only delete link after releasing result

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/docs/rules/_index.md
- frontend/dockerfile/docs/rules/invalid-default-arg-in-from.md
- frontend/dockerfile/linter/docs/InvalidDefaultArgInFrom.md
- frontend/dockerfile/linter/ruleset.go
Picks up the work left off here: https://github.com/moby/buildkit/pull/5102
> adds InvalidDefaultArgInFrom lint check

- frontend/dockerfile/docs/rules/from-as-casing.md
- frontend/dockerfile/linter/docs/FromAsCasing.md
The ConsistentInstructionCasing rule was renamed but there was still a link pointing to the old filename, causing docs build to fail:
```
0.133 Start building sites … 
0.133 hugo v0.127.0-74e0f3bd63c51f3c7a0f07a7c779eec9e922957e+extended linux/arm64 BuildDate=2024-06-05T10:27:59Z VendorInfo=gohugoio
0.133 
4.479 WARN  [introduced] version below threshold: buildx 0.9.0 "/src/content/build/building/variables.md:351:1"
7.442 ERROR [en] REF_NOT_FOUND: Ref "./file-consistent-command-casing.md" from page "/reference/build-checks/from-as-casing": page not found
9.221 Total in 9093 ms
9.221 Error: error building site: logged 1 error(s)
```
Updated the link to the new filename.
- We should probably have tests for this (e.g. docs validate) or have a way to generate "related" links. Or just remove …
> docs: fix broken link in lint docs after rule rename

- .github/workflows/docs-upstream.yml
relates to https://github.com/moby/buildkit/pull/5124#issuecomment-2209250809
> ci(docs-upstream): missing path for frontend rules docs

- solver/llbsolver/solver.go
These cases could cause early exit without calling `stopTrace`.
@cpuguy83 Related to https://github.com/moby/moby/issues/48144 but I don't think this is actual issue(build would fail without starting in this case). Also the `ImportStatus` is unreleased new code.
> llbsolver: make sure stoptrace called on bolt error

- frontend/dockerfile/docs/rules/legacy-key-value-format.md
- frontend/dockerfile/linter/docs/LegacyKeyValueFormat.md
Adds an example of a multiline ENV declaration, with and without a `=` separator.
- resolves docker/docs#20355
> docs: add a multi-line ENV example

- frontend/dockerfile/docs/reference.md
Updates the sections for COPY and ADD in the Dockerfile reference to make it
easier to understand the behaviors of these instructions in different
circumstances.
Also adds some information about permissions for COPY with Git contexts.
Preview:
- [ADD](https://deploy-preview-20363--docsdocker.netlify.app/reference/dockerfile/#add)
- [COPY](https://deploy-preview-20363--docsdocker.netlify.app/reference/dockerfile/#copy)
Relates to:
- https://github.com/moby/buildkit/issues/5066#issuecomment-2204012890
- https://github.com/docker/buildx/issues/2571
> docs: rewrite copy/add instruction reference

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/docs/rules/_index.md
- frontend/dockerfile/docs/rules/from-platform-flag-const-disallowed.md
- frontend/dockerfile/linter/docs/FromPlatformFlagConstDisallowed.md
- frontend/dockerfile/linter/ruleset.go
This linter rule triggers if a constant value has been used in the
`FROM --platform` flag and the stage name doesn't contain the OS or
architecture mentioned.
Fixes https://github.com/moby/buildkit/issues/5131.
> checks: add check for constant in from platform flag

- frontend/dockerfile/dockerfile_test.go
- solver/llbsolver/history.go
fixes #5122
Discard was called always, even if `Commit` had succeeded but it is not allowed as it removed the writer lease and blob could be deleted before it reaches the `AddResource` call of the history record.
> llbsolver: fix possible early delete of external error

- util/testutil/integration/run.go
- Instead of running a mirror for each `integration.Run` call,
only run it if there is actual sandboxed test running. This speeds
up running tests with a filter as if all the tests from a given
suite are inactive, no time is spent running the mirror.
- ProviderFromRef call is already making the HEAD request
to upstream registry to get digest. Avoid doing that if
image already exists in mirror anyway.
Before:
```
--- PASS: TestIntegration (6.46s)
--- PASS: TestIntegration/TestHistoryError/worker=containerd-1.6/frontend=builtin (0.40s)
PASS
ok      github.com/moby/buildkit/frontend/dockerfile    6.872s
```
After:
```
--- PASS: TestIntegration (0.39s)
--- PASS: TestIntegration/TestHistoryError/worker=containerd-1.6/frontend=builtin (0.36s)
PASS
ok …
```
> testutil: optimization for mirror handling

- go.mod
- go.sum
- vendor/github.com/tonistiigi/go-csvvalue/csvvalue.go
- vendor/modules.txt
fixes #5145
There was an issue with decoding quotes.
https://github.com/tonistiigi/go-csvvalue/compare/bb8dd5cba3c2...ddb21b71c0b4
> vendor: update go-csvvalue to ddb21b71

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
fixes #5147
Although #5147 does not list Dockerfile, this is the only case I see where this was possible. Build without stages is still error, but don't let the frontend panic.
> dockerfile: avoid frontend panic when no stages defined

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/docs/rules/_index.md
- frontend/dockerfile/docs/rules/copy-ignored-file.md
- frontend/dockerfile/linter/docs/CopyIgnoredFile.md
- frontend/dockerfile/linter/ruleset.go
- frontend/dockerui/config.go
Trying to COPY/ADD files excluded by dockerignore will cause the build to fail because they are missing from the context. This adds a rule check to catch this case.
> Rule Check: CopyIgnoredFiles

- cmd/buildctl/build.go
At the moment build --import-cache option is ignored when not using any frontend. This makes sure the option is passed along to the actual solve request.
> Pass cache imports from solve ptions to solve request

- cache/util/fsutil.go
- cache/util/fsutil_test.go
- util/resolver/retryhandler/retry.go
- util/system/path_test.go
This removes usages of `errors.Cause` in favor of using `errors.As` which is the more standard way of handling error causes. `Cause` was not used frequently and `errors.As` is part of the standard library and is supported by `github.com/pkg/errors`.
For one usage of `errors.Cause`, the underlying implementation itself has a reliance on the internal implementation of the error being returned and this method isn't guaranteed to work. Since we are relying on an implementation detail and not an API, I've added a test to ensure the behavior continues working as designed.
This also removes a check for an error being returned from containerd that has since been fixed so the code is dead.
> errors: remove usage of errors.Cause

- client/solve.go
- session/content/content_test.go
- session/filesync/filesync_test.go
- session/manager.go
- session/session.go
This seems to be completely unused.
I believe it is remnant of pre-buildkit session implementation and was used for either logging of some transfer reuse.
> session: remove session name property

- solver/llbsolver/solver.go
Theoretically this can result in panic so adding to v0.15 milestone
> llbsolver: avoid nil releaser on error

- frontend/dockerfile/dockerfile_test.go
- frontend/dockerui/attr.go
- frontend/dockerui/config.go
- frontend/dockerui/namedcontext.go
This allows frontend to associate a specific local to specific session when it is assembling LLB. It can be used to create builds using files from multiple sessions or multiple builds to use the same session that is different from default session for the build request.
> dockerui: allow passing sessionID for specific local source

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
The current implementation silently ignores the chmod option argument for COPY and ADD if it is invalid, so this PR change to check the validity of the argument.
> Check the validity of the chmod option arguments for COPY and ADD

- errdefs/errdefs.go
- solver/llbsolver/solver.go
- solver/scheduler.go
- util/grpcerrors/grpcerrors.go
Error during creating history or failure in graph concistency checks are signs of either bugs or system configuration issue. This makes sure that gRPC error code in the API error based on these cases has correct value to signify it.
This doesn't of course cover all the possible cases where error return from BuildKit could be considered internal, but can be used as a proof of concept.
> solver: mark history and graph concistency errors as internal

- .github/workflows/test-os.yml
- client/client_test.go
- frontend/dockerfile/dockerfile_test.go
- util/testutil/integration/pins.go
- util/testutil/integration/run.go
- util/testutil/integration/run_unix.go
- util/testutil/integration/run_windows.go
- util/testutil/integration/util.go
- util/testutil/integration/util_windows.go
Depends on #4994
Started addressing #4485
Starting off with this one as a POC on the approach, before we proceed to complete the rest under `/frontend/dockerfile`.
Tests covered so far:
> tests: enabling integration tests on windows

- cache/metadata/metadata.go
- cmd/buildkitd/main.go
- control/control.go
- solver/bboltcachestorage/storage.go
- solver/bboltcachestorage/storage_test.go
- solver/llbsolver/history.go
- util/db/boltutil/db.go
- util/db/db.go
- util/db/transactor.go
This allows more flexible control over DB transactions and compaction.
Similar change for containerd's boltdb is coming in containerd v2 https://github.com/containerd/containerd/pull/10385
> db: move DB dependencies to transactor interface

- hack/images
See: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
Closes: https://github.com/moby/buildkit/issues/3553
Signed-off-by: Craig Andrews <candrews@integralblue.com>
> ci: add OCI image annotations to docker images

- .github/workflows/buildkit.yml
- docker-bake.hcl
- hack/dockerfiles/govulncheck.Dockerfile
similar to https://github.com/docker/buildx/pull/2631
Runs [govulncheck](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) tool in our workflow to report known vulnerabilities that affect Go code using the Go vulnerability database at https://vuln.go.dev/ and output a SARIF report that will be uploaded to [GitHub Code scanning](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning) so we have these issues reported in the [Security tab](https://github.com/moby/buildkit/security) like done with Docker Scout in https://github.com/moby/buildkit/pull/5184.
Atm dependabot will open a pull request when such vulnerabilities are found similar to https://github.com/moby/buildkit/pull/4786 but we often close them because it needs …
> govulncheck to report known vulnerabilities

- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/instructions/commands.go
Add environment replacement support for chmod option argument for the ADD and COPY commands.
> Add environment replacement support for chmod option

- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
Adds an extra job for buildkit and frontend workflows to scan images with Docker Scout to report vulnerabilities.
Runs [`scout cves`](https://docs.docker.com/reference/cli/docker/scout/cves/) command and output a SARIF report that will be uploaded to [GitHub Code scanning](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning) so we have these issues reported in the [Security tab](https://github.com/moby/buildkit/security).
Example can be seen here for `moby/buildkit:master`: https://github.com/crazy-max/.github/security/code-scanning
> ci: scan images with docker scout

- .github/workflows/labeler.yml
relates to https://github.com/moby/buildkit/pull/515
When someone opens a PR and push new changes where files are reverted or no longer changed, the labels are not synced: https://github.com/moby/buildkit/pull/5139
I think we should use the `sync-labels` opt: https://github.com/actions/labeler?tab=readme-ov-file#inputs
I just wonder what this will do if we set a label manually so I'm going to test that in this one.
> ci: sync labels when files are reverted or no longer changed with labeler

- frontend/dockerfile/docs/reference.md
I was reading through the documentation trying to understand what's so
special about secret type mount except for extra options it takes as I
found that contents of bind mount doesn't get baked into the image too
but it can be found in /var/lib/docker in contrary to secret type
mount. I've learned that secret type mount uses tmpfs under the hood
and my findings were confirmed by
https://docs.docker.com/build/cache/invalidation/#general-rules: 'The
contents of build secrets are not part of the build cache.'. I think
it's worth emphasizing in the documentation.
Fixes https://github.com/docker/docs/issues/20436.
Signed-off-by: Arkadiusz Drabczyk <arkadiusz@drabczyk.org>
> docs: emphasize the fact that secrets aren't saved in cache

- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
Scan `master-rootless` tag for buildkit image and `master-labs` tag for dockerfile frontend with Scout.
Last commit make sure no-cache-filter is applied when master images are being built so we are aligned with release workflow to avoid Scout reporting false positives like https://github.com/moby/buildkit/security/code-scanning/6 that is already fixed in Alpine packages: https://pkgs.alpinelinux.org/package/v3.20/main/x86_64/libcurl
> ci: missing tags to be scanned with scout

- .github/workflows/buildkit.yml
- .github/workflows/frontend.yml
I'm a bit confused by what is reported by scout scan for https://github.com/moby/buildkit/security/code-scanning/9
It says we have libcurl 8.8.0 but looking at build logs it's 8.9.0: https://github.com/moby/buildkit/actions/runs/10302220041/job/28516403157#step:7:403
```
#49 6.078 (11/33) Installing zstd-libs (1.5.6-r0)
#49 6.153 (12/33) Installing libcurl (8.9.0-r0)
#49 6.220 (13/33) Installing libexpat (2.6.2-r0)
```
I can't repro locally so maybe there is an issue with Scout or our pipeline so adds an extra step to figure this out.
> ci: print scout result

- .github/labeler.yml
Expand globs for area/project in auto PR labeler for `area/project`.
The auto-formatter decided it didn't like single quotes, not quite sure why it was angry about that bit...but AFAIK that won't change functionality.
> expand globs for area/project in auto PR labeler

- frontend/dockerfile/docs/reference.md
All of these options are valid
https://github.com/moby/buildkit/blob/bc92b63b98aa0968614240082997483f6bf68cbe/frontend/dockerfile/instructions/commands_runmount.go#L196
and should be mentioned.
Partially fixes https://github.com/docker/docs/issues/20441.
Signed-off-by: Arkadiusz Drabczyk <arkadiusz@drabczyk.org>
> docs: mention `dst` and `destination` options too

- hack/images
- hack/release
`git` stage has been removed in https://github.com/moby/buildkit/pull/5187
> hack: fix no-cache-filter on release

- frontend/dockerfile/shell/lex.go
- frontend/dockerfile/shell/lex_test.go
Environment replacement form like below are invalid, so they should cause error.
- `${VAR:#pattern}`
- `${VAR:##pattern}`
- `${VAR:%pattern}`
- `${VAR:%%pattern}`
> Check invalid environment replacement form like ${VAR:%}

- frontend/dockerfile/instructions/commands_runmount.go
This list has now to be manually maintained but OTOH if keys were stored in a []string list there would be a risk that not all elements are used in switch.
> dockerfile: add missing mount completions

- frontend/dockerfile/docs/reference.md
> docs: clarify valid from targets for run --mount

- solver/llbsolver/ops/exec.go
fixes https://github.com/docker/buildx/issues/2479
regression from #4624 (v0.13)
Secret, SSH and Tmpfs mounts never have an input vertex and zero value for input should not be considered an input at index 0 .
Currently, if for example secret mount had a input=0, it caused content based checksum from first input(rootfs), that could take quite a lot of time when image was big and had lots of files. The computation result was cached but if there was a cache invalidation in previous commands it caused checksum to recomputed again for the command with the secret mount.
> exec: fix incorrect deps computation for special mounts

- client/llb/exec.go
See https://github.com/moby/buildkit/pull/5251#issuecomment-2286100909.
These mounts have no vertex inputs, and so should be *explicitly* marshaled as such.
I think this is the "root cause" of https://github.com/docker/buildx/issues/2479, but since marshaling is done on the client, https://github.com/moby/buildkit/pull/5251 is still required. However, the client should explicitly indicate that there is no vertex input on these special mount types.
> chore: set `pb.Empty` on ssh and secret mounts

- frontend/subrequests/lint/lint.go
Currently, the way we print out warnings in the rule checks is with the `PrintLintViolations(dt []byte, w io.Writer) error` function. One of the problems with this is that if you want to use this function to print the lint violations, but would also like to inspect other properties of the underlying data (type of `LintResults`), you currently have to no choice but to unmarshall the JSON twice, once implicitly in `PrintLintViolations` and the second in order to access the `LintResults`.
This PR moves this functionality to `(results *LintResults) PrintWarningsToWriter(w io.Writer) error`, and leaves `PrintLintViolations` in place as a function that simply unmarshals the bytes and calls the `PrintWarningsToWriter` method, which removes the redundant unmarshaling.
While I was at this, I also …
> frontend: refactor lint rule check printing functionality

- cache/remotecache/v1/utils.go
fixes https://github.com/moby/buildkit/issues/5242
Moby graphdriver backend does not implement Info() and such case should not be used as a signal for
blob needed to be skipped as it is unavailable.
This requires a change in Moby side as well to return a typed error instead of string.
> remotecache: handle not implemented error for Info()

- frontend/dockerfile/docs/reference.md
> docs: fix instruction name (s/ADD/COPY/)

- frontend/dockerfile/dockerfile_outline_test.go
- frontend/dockerfile/dockerfile_targets_test.go
- frontend/dockerfile/dockerfile_test.go
- util/testutil/integration/sandbox.go
- util/testutil/integration/util_windows.go
> We have split the tests in batches across a number of PRs with the same title + suffix `(part X)`
Additional translated tests for Windows in frontend/dockerfile.
Partially addresses https://github.com/moby/buildkit/issues/4485
> tests: frontend/dockerfile: update integration tests for windows/wcow (part 4)

- .golangci.yml
- cache/contenthash/tarsum.go
- executor/resources/cpu_test.go
- executor/runcexecutor/executor.go
- hack/dockerfiles/lint.Dockerfile
- session/secrets/secretsprovider/secretsprovider.go
- solver/testutil/cachestorage_testsuite.go
- util/appcontext/appcontext.go
- util/resolver/retryhandler/retry.go
- util/testutil/integration/run.go
- util/testutil/integration/sandbox.go
Previous version runs out of memory on go1.23
> ci: update golangci-lint to v1.60.1

- frontend/dockerfile/dockerfile_test.go
- session/upload/uploadprovider/provider.go
Helps detecting when uploadprovider has finished
with the source. This avoids deadlock, should the
same reader be shared by multiple uploads that sync with each other (https://github.com/docker/buildx/pull/2656).
> uploadprovider: allow closing used sources

- README.md
- docs/attestations/sbom-protocol.md
- docs/dev/README.md
- docs/dev/solver.md
- frontend/dockerfile/docs/reference.md
- frontend/dockerfile/docs/rules/copy-ignored-file.md
- frontend/dockerfile/linter/generate.go
GitHub markdown supports an extension for rendering notes, warnings, and tips.
This extension is now also supported by the Docker documentation site.
This PR updates the Markdown files to use the new syntax.
Example:
```
> [!NOTE]
> This is a note
```
Rendered version:
> [!NOTE]
> This is a note
- related pr: docker/docs#20608
> docs: use gh alert syntax for callouts

- frontend/dockerfile/docs/reference.md
Updates documentation ( in response to https://github.com/moby/buildkit/issues/5240 😄 ) to provide clarification that not all commands support `heredoc`. It leaves to the user to click through the follow-up link to learn more about heredocs.
> docs: clarify in #shell-form that heredocs apply to supported commands

- client/llb/exec.go
- frontend/dockerfile/dockerfile2llb/convert_secrets.go
- frontend/dockerfile/dockerfile_secrets_test.go
- frontend/dockerfile/instructions/commands_runmount.go
Implements frontend side of #2122.
This adds the syntax to Dockerfile frontend.
I purposefully chose to use a simple format for this as it's likely going to be debated. As implemented, the following format is supported:
```dockerfile
RUN --mount=type=secret,id=MYSECRET,env
```
or, more explicitly:
```dockerfile
RUN --mount=type=secret,id=mysecret,env=MYSECRET
```
will mount the secret with id `mysecret` as a new environment variable with the name `MYSECRET`).
Either way, the secret will be mounted as a file (existing behavior).
Note, that this already implements a suggestion from the PR comments.
Any suggestions on making it even more ergonomic or straightforward are welcome.
> frontend: allow mounting secret environment variables

- README.md
- cache/remotecache/s3/s3.go
Fix #4885
Tested locally with this Dockerfile
```
FROM python:3.11
RUN pip install torch
ARG x
RUN echo $x
```
And with the `touch_refresh` option set to 10s.
> S3 Cache: Use multipart upload instead of CopyObject for touching file > 5GB

- README.md
DevZero uses Buildkit for building all of workspaces.
Looking forward to being listed as a Buildkit user. 
Documentation: https://www.devzero.io/docs/recipes/build-process
> README.md: Add DevZero as consuming project

- executor/runcexecutor/executor.go
- executor/runcexecutor/executor_linux.go
If container exits with error and has invoked OOMKiller mark the origin error as ENOMEM so that it can be detected on the client side.
gRPC will set ENOMEM as codes.ResouceExhausted based on #5182
> executor: detect containers killed by OOMKiller

- README.md
- cache/remotecache/s3/s3.go
This PR allows to use multiple go routines to upload layers to S3 in parallel.
Parallelism is controlled by `upload_parallelism`
Individually, each layer is already send in parallel, using the standard Upload Manager provided by the S3 SDK.
Inspired by https://github.com/moby/buildkit/pull/4429/commits/6c439bdf8a839d2e86541beebe22caa2870a663a.
> Parallel layer upload for s3 cache

- frontend/dockerui/requests.go
- frontend/subrequests/lint/lint.go
Currently, when displaying lint check warnings, the warning only displays the name of the source file and does not include any path information for disambiguating Dockerfiles which may be named the same within a context but exist at different paths. This PR updates the functions around printing these warnings to accept an additional parameter which allows for specifying a different path to print, which allows the caller to provide path context rather than being limited to the source name.
(frontend work to address: https://github.com/docker/buildx/issues/2542)
> frontend: rule check print to include path to dockerfile

- executor/oci/resolvconf.go
- executor/oci/resolvconf_test.go
Hi,
this fixes #2404 . Instead of always checking for systemd-resolved it's sufficient to do so only if the run does not happen within the host networking mode.
I was a bit unsure what happens [here](https://github.com/moby/buildkit/blob/bc92b63b98aa0968614240082997483f6bf68cbe/executor/oci/resolvconf.go#L38) and if it might get problematic in consecutive builds with different networking modes. Maybe someone can explain this to me.
BR Kai
> fix: check network mode when choosing resolv.conf

- frontend/dockerfile/dockerfile_provenance_test.go
Updated tests in `frontend/dockerfile/dockerfile_test.go` to run on Windows.
Partially addressing https://github.com/moby/buildkit/issues/4485
- testClientLLBProvenance
- testNilProvenance
- testDuplicatePlatformProvenance
- testDockerIgnoreMissingProvenance
- testCommandSourceMapping
- testFrontendDeduplicateSources
> tests: frontend/dockerfile: update integration tests for windows/wcow (part 3)

- frontend/dockerfile/docs/reference.md
I think we meant to have this added before but never got around to it.
Please double-check the versions!
> docs: add min dockerfile version for flags

- util/stack/compress.go
- util/stack/compress_test.go
- util/stack/stack.go
Combines the shared parts of stacktraces so they
take up less space. For example if error is wrapped from similar codepath to the main error, the main error gets the stacktrace and wrapping gets only to stacktrace up to the point where same frame exists in main error as well.
This also means we need to be less careful about WithStack as if error already has a longer stack from current position, it would be ignored.
> stack: compress shared stacks for clearer output

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/instructions/commands.go
- frontend/dockerfile/instructions/parse.go
addresses @tonistiigi comments in #5240 
Currently we're checking the AST for command violations, but typically it is more convenient and correct for these checks to happen at the instruction level. This updates the consistent command casing check to occur after the AST is parsed out into instructions.
> frontend: command casing rule check after parsing the ast

- docs/buildkitd.toml.md
Use a front matter key for the title, instead of an in-line heading. This makes it possible to use the title in templates for docs.docker.com
> docs: use front matter title in buildkitd.toml doc

- errdefs/internal.go
- errdefs/internal_linux.go
- errdefs/internal_nolinux.go
- util/grpcerrors/grpcerrors.go
~depends on #5181~
~depends on #5163~
> errdefs: detect certain sycall errors as internal

- frontend/dockerfile/docs/reference.md
- frontend/dockerfile/docs/rules/_index.md
- frontend/dockerfile/linter/docs/_index.md
Adds documentation for the `checks` directive in the Dockerfile reference, and adds cross-references to the user guide for build checks.
> docs: update reference docs for `check` directive

- frontend/subrequests/lint/lint.go
Adds a `SourceInfoMap` callback paramter to `LintResults.PrintErrorTo` in order to keep the printing of warnings and errors consistent.
> frontend: add SourceInfoMap callback to LintResults.PrintErrorTo params

- Dockerfile
- fixes https://github.com/moby/buildkit/security/code-scanning/11
diff: https://github.com/opencontainers/runc/compare/v1.1.13...v1.1.14
Release Notes:
- Fix CVE-2024-45310 / GHSA-jfvp-7x6p-h2pv, a low-severity attack that allowed maliciously configured containers to create empty files and directories on the host.
- Add support for Go 1.23.
- Revert "allow overriding VERSION value in Makefile" and add EXTRA_VERSION.
- rootfs: consolidate mountpoint creation logic.
> Dockerfile: update runc binary to 1.1.14

- Dockerfile
Update the containerd binary that's used in CI
- full diff: https://github.com/containerd/containerd/compare/v1.7.20...v1.7.21
- release notes: https://github.com/containerd/containerd/releases/tag/v1.7.21
> Dockerfile: update containerd binary to v1.7.21

- frontend/dockerfile/docs/reference.md
- relates to https://github.com/moby/buildkit/pull/5215
> docs: run mount secret env dockerfile example

- hack/images
similar to https://github.com/moby/buildkit/pull/3543
fixes https://github.com/moby/buildkit/issues/5279
We got some false-positive reported in security tab when rootless image is analyzed by Docker Scout because alpine packages are cached. With this change we make sure this stage is not cached on release.
cc @cdupuis
> hack: do not cache rootless stage on release

- .github/labeler.yml
This issue updates the `area/windows` auto-labeling to exclude any files ending in `_windows.go` under the `vendor/` folder.
> exclude vendor directory from windows label

- cache/metadata.go
- cache/metadata/metadata.go
- cache/metadata/metadata_test.go
- frontend/dockerfile/dockerfile2llb/convert_runmount.go
- frontend/dockerfile/dockerfile_test.go
- solver/llbsolver/bridge.go
- solver/llbsolver/mounts/mount.go
- solver/llbsolver/vertex.go
- source/git/source.go
- source/http/source.go
- source/local/source.go
- worker/base/worker.go
- worker/worker.go
fixes #5305
On a build with no-cache, cache mounts were not pruned correctly if the mount was on top of another ref. This also appeared in Dockerfile when mode/uid/gid was set because implicit parent ref is created in these cases in order to change the permissions of a subdir that is used as a cache mount base.
Because it is not possible to know ahead of time what ref will become the parent of cache mount during build, all cache mounts matching the ID that have a parent will be pruned.
> exec: fix pruning cache mounts with parent ref on no-cache

- util/bklog/log.go
Previous version of the detect package would only enable trace ids in the build log if tracing was in use. For practical purposes, there was always a tracer in use (either the recorder which was always enabled or one of the detected tracers).
When this package was refactored, the call to enable the trace id was accidentally removed.
This removes the option to enable or disable the trace id from the log and instead just always enables it since this was the behavior previously.
Fixes #5310.
> bklog: always enable trace id if it exists

- .golangci.yml
- cache/contenthash/tarsum.go
- hack/dockerfiles/lint.Dockerfile
- solver/testutil/cachestorage_testsuite.go
- util/resolver/retryhandler/retry.go
- util/testutil/integration/run.go
Unblock CI with the schema verify error in 1.60 https://github.com/golangci/golangci-lint/issues/5003
> hack: update golangci-lint to 1.61

- .github/labeler.yml
- go.mod
- go.sum
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/github.com/docker/docker/api/types/container/hostconfig.go
- vendor/modules.txt
backport of
* https://github.com/moby/buildkit/pull/5318
* https://github.com/moby/buildkit/pull/5316
do it again https://github.com/moby/buildkit/pull/5319#issuecomment-2341098718
> [v0.16] cherry-picks for v0.16.0

- README.md
Thanks again for a great project.
r2d4/llb is a frontend that exposes the Solve rpc and the image config via JSON. The idea is that I found it difficult to generate the full gRPC stubs for languages other than Go. Additionally, some runtimes (like connect/grpc node/web) can't listen on a unix socket. Instead, you only have to compile ops.proto and build the graph. It takes in a JSON file with the schema: imageConfig (OCI image config) and definition (the base64-encoded binary-encoded protobuf)
The dacc project is a TypeScript project that uses the r2d4/llb frontend. It is similar to llb.State, but in TypeScript and calls the frontend to solve the graph.
> readme: add r2d4/llb frontend and dacc project

- .github/workflows/buildkit.yml
It needs at least content read to be able to checkout the repository.
> ci: Fix govulncheck permissions

- solver/edge.go
- solver/internal/pipe/pipe.go
- solver/internal/pipe/pipe_test.go
- solver/scheduler.go
This updates the pipe library to use generics for the request payload and the status value. This allows the solver to put in explicit types rather than rely on type casting from interfaces which helps with type safety and understandability.
The status value used by the solver uses the `any` type instead of an explicit type because the `unpark` method takes a generic list of pipes and the different pipes have different result types. We can likely change this in the future or create a discriminated union for the types that can be used in this package. That is left for future work because at least the request payload is typed now.
> solver: pipe implementation utilizes generics for better typing

- util/resolver/authorizer.go
- util/resolver/authorizer_test.go
This PR solves a problem specific for OCI registry. 
When starting auth process hitting `/v2` route, registry returns an empty scope which leads to a subsequent request as follow:
```
$ curl -v https://sa-saopaulo-1.ocir.io/v2/ 2>&1 | grep -i www
< WWW-Authenticate: Bearer realm="https://sa-saopaulo-1.ocir.io/20180419/docker/token",service="sa-saopaulo-1.ocir.io",scope=""
```
And them when hitting url `https://sa-saopaulo-1.ocir.io/20180419/docker/token`, buildkit try to send a invalid query string `scope=::`
This PR ignores empty scopes
> util/resolver: ignore invalid (empty) scope

- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/dockerfile_test.go
- util/testutil/integration/util_windows.go
A number of integration tests were initially skipped on Windows, waiting for their platform-specific translations. See #4485.
This commit enables all the dockerfile linter tests that had been skipped before. Some of the tests did not need any platform specific change since the lint warning were being generated before actual image pull.
> tests: frontend/dockerfile: add dockerfile lint tests for WCOW

- solver/cachemanager.go
If error is returned from `Save()`, `rck` is nil and causes nil dereference panic on accessing `TraceFields` when printing debug logs.
regression from https://github.com/moby/buildkit/pull/4109
@sipsma
> solver: fix possible panic from error handler

- cmd/buildkitd/main_containerd_worker.go
- executor/oci/spec_darwin.go
- snapshot/localmounter_darwin.go
- source/git/source_darwin.go
- source/git/source_unix_nolinux.go
- util/network/netproviders/network_nobridge.go
These changes are extracted from #4059. Other half was already merged in #5271.
`localmounter_darwin.go` is fully identical to `localmounter_freebsd.go` except that it uses `bind` mount type instead of FreeBSD-specific `nullfs`.
Not sure whether you want to enable CI job for Darwin `buildkitd`, I'm absolutely OK if that will be omitted from current PR.
> Add stub implementations to make buildkitd buildable for Darwin

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_secrets.go
- frontend/dockerfile/dockerfile_secrets_test.go
Replace variables with **** if they are used as secret env.
This is not needed to not leak secret values but to make sure output does not contain some incorrect default value.
Noticed via #5333 (@dvdksn @ryio1010)
> dockerfile: mask usage of secret env in command name

- frontend/dockerfile/dockerfile_lint_test.go
fixes https://github.com/moby/buildkit/issues/5338
Currently when we run tests for the rule checks, we sort by line number so that we can make sure the warnings are being compared in a easily predictable order (as opposed to whichever order the linter happens to run the checks). In the case where multiple warnings were present on a single line, the tests could fail. This adds a secondary sort on the `Detail` (or `Short` field when checking `VertexWarning`s) field so that warnings within the same line are presented in a similarly predictable order.
> frontend tests: add secondary sort on errors for more consistent rule check tests

- frontend/dockerfile/docs/reference.md
I added $ in 'Example: Mount as environment variable' sample command because it is needed to refer to env.
>  frontend/dockerfile/docs: add $ in mount env example

- frontend/dockerfile/dockerfile_test.go
Updated tests in `frontend/dockerfile/dockerfile_test.go` to run on Windows.
Partially addressing #4485
- testDockerignoreInvalid
- testDockerignore
- testExposeExpansion
- testDockerfileAddArchiveWildcard
- testDockerfileInvalidInstruction
- testWorkdirExists
- testOutOfOrderStage
- testWorkdirUser
- testEmptyWildcard
- testLabels
- testWildcardRenameCache
- testReproducibleIDs
- testPlatformArgsImplicit
- testFrontendSubrequests
- testFrontendEvaluate
> tests: frontend/dockerfile: update integration tests for windows/wcow (part 2)

- solver/debug.go
- solver/edge.go
- solver/scheduler.go
Move scheduler debug statements to their own functions and in their own file so that scheduler debug statements don't make the scheduler logic more complex to follow. Some of the scheduler logs can be quite long and can make it difficult to follow the code logic. This changes these log statements to `debugSchedulerXXX` where `XXX` is the message that would be printed.
> solver: move scheduler debug statements to their own functions

- docs/windows.md
`ContainerUser` is not permitted to write to `C:\` because of their limited permissions, `(WD)` at best.
Add a note explaining why we are using `USER ContainerAdministrator` in our dockerfile for us to be able to run:
```
RUN echo "Goodbye!" >> hello.txt
```
On client SKUs like Win11, there will be no issues since `ContainerUser` has `(M)` permissions on `C:\`
Fixes #4731 as by-design.
> docs: windows: add a note about ContainerUser limited permissions

- Dockerfile
- frontend/dockerfile/cmd/dockerfile-frontend/Dockerfile
- hack/dockerfiles/archutil.Dockerfile
- hack/dockerfiles/authors.Dockerfile
- hack/dockerfiles/doctoc.Dockerfile
- hack/dockerfiles/generated-files.Dockerfile
- hack/dockerfiles/lint.Dockerfile
- hack/dockerfiles/shfmt.Dockerfile
- hack/dockerfiles/vendor.Dockerfile
To unblock ci while #5360 is being worked on.
> dockerfile: pin dockerfile frontend image

- frontend/dockerfile/docs/reference.md
> docs: update "read more" link for dockerfile examples

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/convert_runmount.go
- frontend/dockerfile/dockerfile2llb/platform.go
- frontend/dockerfile/dockerfile_test.go
This adds support for the ONBUILD commands to refer to
other stages in commands like `COPY --from=` or
`RUN --mount=from=` . The source may be a stage in the
calling Dockerfile, implicit image or named build context.
depends on #5349
fixes https://github.com/moby/buildkit/pull/4568#issuecomment-2361915338
fixes https://github.com/moby/buildkit/issues/959
fixes https://github.com/moby/buildkit/issues/816
fixes https://github.com/moby/buildkit/issues/817
> dockerfile: add support for ONBUILD in combination with from

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/platform.go
This avoids many temporary conversion between maps/slices and shell.EnvGetter.
> dockerfile: update args definitions to llb.EnvList

- solver/llbsolver/history.go
follow-up https://github.com/moby/moby/pull/48565#issuecomment-2386268988
> history: remove records without attached blobs at startup

- client/llb/diff.go
- client/llb/exec.go
- client/llb/fileop.go
- client/llb/llbbuild/llbbuild.go
- client/llb/marshal.go
- client/llb/merge.go
- client/llb/source.go
- solver/llbsolver/vertex.go
This fixes a problem with the new protobuf marshaling with the standard library. LLB digests are now forced into deterministic marshaling to ensure they produce the same digest when marshaled multiple times.
In addition, the marshal cache has also been fixed to work in multi-threaded frontends with multiple different constraints. Previously, if an LLB vertex was used in multiple goroutines and marshaled concurrently, the cache would be broken. This could cause certain problems when a specific node was used multiple times in the same LLB tree.
> llb: deterministic marshaling for protobuf and store results from multiple constraints

- solver/llbsolver/vertex.go
Similar error already exists in loadLLB but was missing in newer recomputeDigests code.
> llbsolver: add input validation to policy recompute

- frontend/dockerfile/dockerfile_test.go
This test has been flaky, see #5384
Skip on Windows for now as investigations go on. This is to allow the rest of the pipeline to remain
unpoisoned.
> tests: skip TestContextChangeDirToFile on Windows

- frontend/dockerfile/docs/reference.md
- follow-up to https://github.com/moby/buildkit/pull/5357
> docs: remove `from` limitation for onbuild

- frontend/dockerfile/docs/reference.md
ARGs are inherited by downstream build stages, if declared in a base
stage. The documentation ambiguously stated that ARGs are out of scope
in other stages, where it really meant other stages that are not
child/downstream stages.
- Addresses docker/docs#21041
> docs: fix incorrect information about arg scoping

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/parser/errors.go
Fix progress lines like `[6/4] step`
Set error location for ONBUILD errors to the command
that pulled in the image with ONBUILD definitions.
Currently location was incorrectly set to the first
line as ONBUILD was parsed as a separate source code.
Location is handled both at parse time (for invalid
ONBUILD definition) and run time (when command set
via ONBUILD errors).
> Multiple fixes for ONBUILD behavior

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/copy_chmod_non_octal_disabled.go
- frontend/dockerfile/dockerfile2llb/copy_chmod_non_octal_enabled.go
- frontend/dockerfile/dockerfile_chmod_non_octal_test.go
- frontend/dockerfile/release/labs/tags
> dockerfile: add support for non-octal COPY --chmod in labs

- client/client_test.go
- control/control.go
- frontend/attestations/parse_test.go
- frontend/attestations/sbom/sbom.go
- frontend/dockerfile/builder/build.go
- frontend/dockerui/config.go
- solver/llbsolver/proc/sbom.go
This addresses #3791.
Using the following scanner image
```Dockerfile
FROM alpine
CMD [ "printenv" ]
```
With the following command:
```
echo "FROM alpine" | docker buildx b . --progress=plain --no-cache -f - --sbom=generator=laurentgoderre689/mock-scanner,EXTRA_SCANNERS=test
```
Yields
```
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 49B done
#1 DONE 0.0s
[...]
#8 DONE 0.7s
#9 [linux/arm64] generating sbom using docker.io/laurentgoderre689/mock-scanner:latest
#9 0.037 BUILDKIT_SCAN_DESTINATION=/run/out/
#9 0.037 BUILDKIT_SCAN_SOURCE=/run/src/core/sbom
#9 0.037 BUILDKIT_SCAN_type=sbom
#9 0.037 BUILDKIT_SCAN_EXTRA_SCANNERS=test
#9 DONE 0.1s
```
This also addresses the concerns about comma in values.
Running
```
echo "FROM alpine" | docker buildx b . …
```
> Added way to configure SBOM scanner

- cache/contenthash/checksum.go
- cache/contenthash/checksum_unix.go
- cache/contenthash/checksum_windows.go
fix (WCOW) file access failure for multistage builds
Fixes: #5193
The failure occurs on Windows Client SKUs (e.g., Windows 11) but generally works on server SKUs like WS2022, although similar failures can also occur on WS2022 in some cases.
> fix(WCOW): fix file access failure for multistage builds

- source/http/source.go
There is a possibility to get a digest mismatch error if the metadata for previous download does not point to a valid reference anymore.
To mitigate this, check that ref that etag points to is still valid before using it.
Additionally `.cacheKey` property was not previously set in the cases where the old reference was reused. This caused a case where even if the download needed to be performed again, it always failed validation, even if the digest had not actually changed since the previous download.
There is still a small possibility that gc/prune request will delete the downloaded record in between cachemap and exec call and that the contents changes in the server at that exact time. To fix that case, we would need to modify cachemap so that it can keep hold of references until build is …
> http: avoid possible digest mismatch error

- worker/containerd/containerd.go
relates to;
- https://github.com/moby/buildkit/pull/4432
- https://github.com/containerd/containerd/pull/9412
- https://github.com/moby/buildkit/pull/4530
This workaround was added in 414edfaa7d20ed5d22876fdaa82eff212944a233, pending changes in containerd. Those changes were included in containerd 1.7.12, which was vendored in bce2f79f8333275426a1560b7dce18067476d720, so the workaround should no longer be needed.
I also reformatted the code, as there's no longer a need to wrap this function since the list of arguments has been reduced.
> worker/containerd: NewWorkerOpt: remove workaround for named pipes

- frontend/dockerfile/dockerfile_test.go
- frontend/gateway/grpcclient/client.go
The grpcclient would take an empty reference and convert it into a `(*reference)(nil)` and then store that in a `client.Reference`. This caused the `nil` check in `convertRef` to return false because it wasn't `nil` but then it panicked because it was `nil`.
`newReference` has been minorly refactored to not return an error. The method is not exported, the error value is not used, and it obscured the functionality which made it harder to use correctly.
Fixes https://github.com/moby/buildkit/issues/5379.
> grpcclient: return proper nil reference from grpcclient

- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/docs/rules/_index.md
- frontend/dockerfile/docs/rules/invalid-definition-description.md
- frontend/dockerfile/instructions/parse.go
- frontend/dockerfile/linter/docs/InvalidDefinitionDescription.md
- frontend/dockerfile/linter/ruleset.go
- frontend/dockerfile/parser/parser.go
fixes #5169 
Implements a check around definition description comments used by `--call=outline` and `--call=targets`.
> InvalidDefinitionDescription Rule Check

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
fixes #5403
Adds the ability to add allowed tokens to the `SecretsUsedInArgOrEnv` check, which allows for `ARG` / `ENV` keys which might otherwise be considered a secret - such as `PUBLIC_KEY`.
> frontend: add an allow list for secret lint check and add public to said list

- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/docs/rules/_index.md
- frontend/dockerfile/docs/rules/invalid-definition-description.md
- frontend/dockerfile/linter/ruleset.go
Currently, the `InvalidDefinitionDescription` check generates a lot of noise. This PR marks this check as experimental in order to make it opt-in.
> frontend: sets the InvalidDefinitionDescription check to be experimental

- cmd/buildkitd/main.go
In order to bump `grpc-go` (in this repo or in external clients) we need to specify `h2` as the application protocol in buildkitd's TLS config.
The enforcement was introduced in `grpc-go v1.67.0`. 
`buildkit` and `buildx` are currently on `v1.66.2` so this patch is needed for the next update. I didn't update `grpc-go` in this patch, but can do if you prefer.
Testing with `buildctl` on `v1.67.1`
```
◊ cat go.mod | grep "google.golang.org/grpc\ "
google.golang.org/grpc v1.67.1
```
Before this patch
```
◊ ./buildctl --addr tcp://localhost:1234 --tlsdir /tmp/certs/client/ build --local context=. --local dockerfile=. --frontend dockerfile.v0
[+] Building 0.0s (0/0)
error: listing workers for Build: failed to list workers: Unavailable: connection error: desc = "transport: authentication …
```
> fix: set h2 protocol identifier to comply with TLS-ALPN

- solver/edge.go
Many of the functions in the solver that operated on the edges were very large which obscured their usage and the overall flow of the scheduler. This change refactors those functions into separate smaller functions to make it easier to follow the overall flow of the scheduler.
> solver: simplify edge-related functions in the solver

- docs/windows.md
Currently, the setup script has a static version that needs to be updated manually by the user. To make the experience easy, extend the script to pick the latest buildkit version using the GitHub API.
> docs: windows: add script to pick latest version

- frontend/dockerfile/docs/reference.md
Small update to the `ARG` syntax definition in the reference document. It should now reflect the ability to have multiple `ARG`s declared on a single line.
> Update ARG sytnax definition in dockerfile reference

- session/auth/authprovider/authprovider.go
- tracing: enable OTEL on authprovider HTTP requests
- authprovider: add OTEL spans for loading credentials
> Better OTEL tracing for authprovider

- docs/attestations/attestation-storage.md
- docs/attestations/sbom-protocol.md
- docs/attestations/sbom.md
- docs/attestations/slsa-definitions.md
- docs/attestations/slsa-provenance.md
When republish these on docs.docker.com, having the title in front
matter means we can access it programmatically in templates.
> docs: add front matter title to attestation docs

- frontend/dockerfile/docs/reference.md
Follow-up to suggestion from @thaJeztah in https://github.com/moby/buildkit/pull/5427
Update ARG and ENV syntax definitions to clarify that first KV-pair is required but additional ones are optional
> Update ARG, ENV and LABEL reference definitions

- session/filesync/diffcopy.go
Reuse the bytes message data buffer for diffcopy to allow memory to be reused when unmarshaling the bytes.
> filesync: reuse data buffer for diffcopy

- util/disk/disk_openbsd.go
- util/disk/disk_unix.go
- util/disk/disk_windows.go
While doing some debugging, realized we weren't doing any disk wrapping so it was difficult to work out *which* file on disk didn't exist.
> chore: add disk stat error wrapping

- source/git/source.go
- source/git/source_test.go
- util/gitutil/git_cli.go
- util/gitutil/git_commit.go
https://github.com/moby/buildkit/pull/5072 is only half the fix - it's still possible for a commit to not be tagged or part of a branch.
For a practical example, see `refs/pull/.../merge` - the commit referenced by this ref is not tagged or part of any branch, and so isn't advertised by `upload-pack`, and so won't be part of clone.
Modern git servers should support this though - https://git-scm.com/docs/protocol-capabilities#_allow_reachable_sha1_in_want - we should be able to specify a specific commit when `fetch`ing. We can include a fallback for if the server *doesn't* support this capability (not 100% sure about the logic here though :thinking: - can we assume everyone is using `upload-pack`?)
This might feel a little edge-casey - but they're still important! The main reason is - `git …
> git: allow cloning commit shas not referenced by branch/tag

- client/ociindex/ociindex.go
If file lock can't be taken because of a permission or readonly error then assume that the index is immutable and locks are not needed.
Writer side is unchanged as if lock would be skipped then the write is assumed to fail anyway.
> ociindex: allow readonly access

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/platform.go
- frontend/dockerfile/dockerfile_test.go
closes https://github.com/docker/buildx/issues/2646
Allows capturing what build stage is currently being built for patterns with better base stage reuse.
> dockerfile: expose TARGETSTAGE as builtin argument

- source/git/source.go
- source/git/source_test.go
This fixes a current issue when a Git commit is accessed multiple times through different refs, or a ref is added after the commit has already been pulled once.
When keep-git-dir option is true, then program can try to resolve the current reference via .git directory and because old cache key was only the git commit, previous .git directory can be reused without any refs inside.
There is no change to the behavior if keep-git-dir is false, as then requests through multiple refs yield identical content.
Only the reference in the user-provided identifier is added to the cache key, and that is the only one that can be expected in .git because of the shallow fetches. We do not do extra request to find named refs for a commit SHA if that is provided in the identifier.
This change can break old …
> git: fix caching git commit through multiple refs

- frontend/dockerfile/docs/rules/json-args-recommended.md
- frontend/dockerfile/linter/docs/JSONArgsRecommended.md
- Add/clarify possible workarounds for the JSONArgsRecommended build check
- Note that limitation with shell being PID 1 is still a thing
- docker/docs#21219
> docs: add workarounds for JSONArgsRecommended check

- frontend/dockerfile/docs/rules/undefined-var.md
- frontend/dockerfile/linter/docs/UndefinedVar.md
Updates the checks reference for the UndefinedVar rule to clarify the following:
- Variables declared in base images are considered valid (no warn)
- This rule does not apply to shell form instructions
- docker/buildx#2751
> docs: update undefined var check reference

- frontend/dockerfile/docs/reference.md
This change removes some older warning formatting.
> docs: remove older warning format

- Dockerfile
https://github.com/opencontainers/runc/releases/tag/v1.2.0
https://github.com/opencontainers/runc/releases/tag/v1.2.1
> Dockerfile: update runc binary to 1.2.1

- util/tracing/tracing.go
- relates to https://github.com/moby/moby/pull/48757#issuecomment-2437558426
Align the package to use the same version of semconv we use elsewhere. Worth noting that some modules still use v0.17;
- go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
- go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace
- go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp
Git grep on buildkit;
util/tracing/detect/resource.go:                                                                                      semconv "go.opentelemetry.io/otel/semconv/v1.21.0"
util/tracing/tracing.go:                                                                                              semconv "go.opentelemetry.io/otel/semconv/v1.17.0" …
> util/tracing: switch to semconv v0.21.0

- .github/workflows/validate.yml
follow-up https://github.com/moby/buildkit/pull/4392#issuecomment-1938223235
package now available on trixie: https://packages.debian.org/trixie/binutils-loongarch64-linux-gnu
> ci: enable archutil-arm64 job

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
> [v0.17] cherry-picks for v0.17.1

- util/gitutil/git_commit_test.go
See:
- https://github.com/moby/buildkit/pull/5471 (where this was peeled out of)
- https://github.com/moby/buildkit/pull/5441 (where this `IsCommitSHA` function was added)
> Add test for `IsCommitSHA` function

- frontend/dockerfile/docs/reference.md
A quick fix for https://github.com/moby/moby/issues/3639#issuecomment-482098988
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>
> docs(dockerfile): BuildKit does not discard Volume edits

- client/client_test.go
- exporter/containerimage/attestations.go
> fix leaving unreleased references behind after SBOM generation

- go.mod
- go.sum
- vendor/github.com/containerd/typeurl/v2/README.md
- vendor/github.com/containerd/typeurl/v2/types.go
- vendor/github.com/containerd/typeurl/v2/types_gogo.go
- vendor/modules.txt
This is a prerequisite to upgrading to containerd 2.x
See https://github.com/containerd/typeurl/pull/54
> Bump typeurl to 2.2.3

- util/tracing/detect/resource.go
- util/tracing/detect/resource_test.go
- util/tracing/tracing.go
We upgraded a dependency that upgraded otel and also changed the semconv schema for us to a newer version. We forgot to upgrade our own semconv.
In the future, we may want to find a way to have a detector that doesn't require us to manually specify a semconv so we don't have to remember this. For now, I've added a test to catch when this happens so it doesn't happen again.
> detect: use newer semconv for resource and add unit test

- cmd/buildkitd/main.go
- control/control.go
- solver/llbsolver/history.go
- worker/base/worker.go
- worker/worker.go
Current implementation based on leases.SynchronousDelete only works with the containerd worker and is ignored otherwise. This means that blobs referenced by history records were left on disc until the periodic background GC was initialized later.
> fix gc after delete history records

- client/client_test.go
- Check that no leases are left behind
- Runc worker still check leftover blobs
- Delete any images that might be keeping refs on blobs
- Check both buildkit and buildkit_history namespace
> client: improve releasable condition in tests

- cache/contenthash/checksum.go
- cache/contenthash/checksum_test.go
Before this commit, HandleChange would always recursively remove records whenever any Modify change was applied to a directory path.
This was wasteful in the case where HandleChange was called only due to a metadata modification to a directory. In that case, it makes sense to *update* the directory's node but no existing entries under the directory need to be thrown away.
Now, we only recursively remove records under a directory for the Delete case and when a Modify change replaces a directory with a non-directory.
> contenthash: don't delete records when a directory is only modified

- frontend/dockerfile/docs/reference.md
- Carry and closes docker/docs#21314
> docs: remove duplicate parser directives bullet list

- util/tracing/detect/resource.go
- util/tracing/detect/resource_test.go
Copies over the telemetry sdk detection to utilize our own version of semconv rather than mix the versions between different packages. This will keep a consistent schema url instead of constantly chasing whichever one the otel sdk is using.
The only thing left from the otel sdk is `WithFromEnv` which is schemaless and won't conflict for that reason so we can continue to use it.
> detect: sever semconv relationship to otel sdk

- solver/pb/json.go
- solver/pb/json_test.go
With the switch from gogo, the `oneof` fields no longer have their `json:"name"` fields emitted. Protobuf doesn't formally support these fields and tells users to use the `protojson` package, but we didn't and the official format is incompatible with the current format we use.
This adds some custom marshaling code to the already existant custom unmarshaling code to ensure these fields are marshaled with the correct casing.
> protobuf: fix casing of json attributes with the switch from gogo

- client/llb/fileop.go
- frontend/dockerfile/dockerfile_test.go
Enables `testDockerfileFromHTTP` integration test
for Windows.
Also fixes a bug where paths were being joined wrongly, for example:
```go
path.Join("/", "\\context") // would be "/\\context"
```
Addressing tests marked as Revisit for #4485
> tests: add `testDockerfileFromHTTP` for WCOW

- Dockerfile
follow-up https://github.com/moby/buildkit/pull/5291#discussion_r1832519755
> dockerfile: add delve to binaries-for-test

- cache/remotecache/local/local.go
- client/build_test.go
- client/client_test.go
- cmd/buildctl/common/common.go
- cmd/buildkitd/main.go
- control/gateway/gateway.go
- executor/runcexecutor/executor.go
- exporter/local/export.go
- exporter/oci/export.go
- exporter/tar/export.go
- frontend/dockerfile/dockerfile_test.go
- session/filesync/filesync.go
- session/group.go
- session/manager.go
- session/session.go
- solver/jobs.go
- solver/llbsolver/solver.go
- solver/scheduler.go
- solver/scheduler_test.go
- source/containerimage/ocilayout.go
- source/local/source.go
- util/flightcontrol/flightcontrol.go
- util/testutil/integration/registry.go
- util/testutil/integration/run.go
- util/tracing/otlptracegrpc/client.go
In this case the current stack trace points to the line where the context was created. Instead the stack should be captured when the defer is running so the return path to the defer call is also part of the stack.
> improve stacks of cancels from defers

- cmd/buildkitd/main.go
- control/control.go
- solver/llbsolver/history.go
~depends on #5515~
When GracefulStop is called, gRPC waits for current requests to finish
before closing. While this is generally the behavior we want, it is
not always the same for the History.Listen endpoint. That endpoint is
usually open even if buildkit is not actively processing any builds,
because the client may be waiting for new events.
The new logic is that if GracefulStop happens, history will
close active listeners if there are no active builds. If there are
active builds, then active listeners will be closed after all the
active builds have completed their finalizers.
> history: handle gracefulstop when history is active

- control/control.go
- solver/cachemanager.go
- solver/combinedcache.go
- solver/llbsolver/bridge.go
- solver/types.go
Previously this routine only ran after user ran
prune command or on reboot of the daemon.
> solver: release unreferenced cache keys after gc

- client/client_test.go
- util/testutil/workers/dockerd.go
- util/testutil/workers/features.go
follow-up https://github.com/moby/moby/pull/48923#issuecomment-2493201502
> dockerd: skip content check with containerd snapshotter

- .github/workflows/test-os.yml
- Dockerfile
> dockerfile: use lld linker for containerd build

- cache/metadata/metadata.go
Found this while trying to dig into some other issues.
I don't think `store.Get` should need a write transaction here.
> Use view transaction for metadata read

- frontend/dockerfile/docs/reference.md
- relates to docker/buildx#2816
> docs: add --checksum only supports sha256

- solver/llbsolver/vertex.go
- solver/llbsolver/vertex_test.go
fixes #5558
When recomputing digests happens, the metadata is lost. This previously happened only with sources that were affected by source policies so it wasn't noticed, but now any LLB Op that is rewritten is affected since the gogo protobuf switch will cause all digests to be rewritten if the frontend and buildkit are using different versions.
> llbsolver: tie op metadata to the op before recomputing digests

- solver/llbsolver/vertex.go
- solver/llbsolver/vertex_test.go
> [v0.18] pick llb metadata regression on version conflict fix

- solver/llbsolver/vertex.go
- solver/llbsolver/vertex_test.go
Although v0.18.0 is out, going to cut v0.17.3 because #5563 fixes a regression between v0.17.1 and v0.17.2
- #5563
#5551 will also be part of v0.17.3 (already picked)
> [v0.17.3] cherry-picks

- client/client_test.go
- cmd/buildkitd/debug.go
- cmd/buildkitd/main.go
- util/testutil/integration/run.go
- util/testutil/integration/sandbox.go
- util/testutil/workers/backend.go
- util/testutil/workers/containerd.go
- util/testutil/workers/oci.go
- util/testutil/workers/util.go
- util/testutil/workers/util_unix.go
- util/testutil/workers/util_windows.go
Add maximum timeout to each test and log all buildkitd
goroutines when a test gets stuck. Currently tests can time out
and will print daemon logs but these would already be after
shutdown signal is sent to the daemon.
Is there any other runtime info that is also worth printing?
Test with fake deadlock:
```
/src # go test -v --run /TestUserAdditionalGids/worker=oci$/frontend=builtin --count 1 ./frontend/dockerfile/
=== RUN   TestIntegration
=== RUN   TestIntegration/TestUserAdditionalGids/worker=oci/frontend=builtin
=== PAUSE TestIntegration/TestUserAdditionalGids/worker=oci/frontend=builtin
=== CONT  TestIntegration/TestUserAdditionalGids/worker=oci/frontend=builtin
sandbox.go:129: sandbox timeout reached, stopping worker
sandbox.go:169: buildkitd debug logs:
goroutine 254 [running]: …
```
> integration: log goroutine trace on test timeout

- client/llb/definition.go
- client/llb/diff.go
- client/llb/exec.go
- client/llb/fileop.go
- client/llb/fileop_test.go
- client/llb/llbbuild/llbbuild.go
- client/llb/marshal.go
- client/llb/merge.go
- client/llb/source.go
fixes #5570
Calling marshal changes the internal state of the op, for example addCap() helper adds capability constraints. These can race with same map being read by another Marshal call. Locking the Marshal function itself also makes sure that the cache is not recomputed in this case.
> llb: avoid concurrent map write on parallel marshal

- Dockerfile
- relates to https://github.com/opencontainers/runc/issues/4543
- relates to / fixes https://github.com/moby/buildkit/issues/5566
This is the third patch release of the 1.2.z release branch of runc. It primarily fixes some minor regressions introduced in 1.2.0.
- Fixed a regression in use of securejoin.MkdirAll, where multiple runc processes racing to create the same mountpoint in a shared rootfs would result in spurious EEXIST errors. In particular, this regression caused issues with BuildKit.
- Fixed a regression in eBPF support for pre-5.6 kernels after upgrading Cilium's eBPF library version to 0.16 in runc.
full diff: https://github.com/opencontainers/runc/compare/v1.2.2...v1.2.3
release notes: https://github.com/opencontainers/runc/releases/tag/v1.2.3
> Dockerfile: update runc binary to v1.2.3

- client/client_test.go
A number of tests have been skipped on Windows.
Enable the following tests in `client/`, with minor modifications to run/unskip on Windows:
count: +20
Addressing #4485
> tests: client: enable a batch of integration tests for wcow (pt.1)

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
Fixes bug that didn't allow named context replacement for stages that were inherited from another stage.
This is a regression from Dockerfile 1.11 ONBUILD changes where code was changed to call init() later to allow ONBUILD rules to change the dependency list of a stage. Calling this reinit caused the child stage to pick up its state from the parent stage in Dockerfile again.
fixes https://github.com/moby/buildkit/issues/5578#issuecomment-2538758509
@mzihlmann
> dockerfile: fix named context replacement for child stages

- frontend/dockerfile/dockerfile_mount_test.go
Checks for mkdir bug that was fixed in runc 1.2.3
Adds integration test for #5588
> dockerfile: add regression test for parallel cache mounts

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/image.go
- frontend/dockerfile/dockerfile_test.go
> dockerfile: fix onbuild propagation for child stages

- hack/dockerfiles/archutil.Dockerfile
Unbreak CI. Later we can change to run this only if archutil changes but even then we would also need to validate that amd64 and arm64 can both pass validation. Debian packages do not seem to be stable.
> hack: remove loong64 validation in archutil

- solver/jobs.go
Have a report of a panic on `walkProvenance` because the step does not have `op` initialized.
> solver: protect against nil dereference on uninitialized vertex

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/github.com/docker/docker/client/ping.go
- vendor/github.com/docker/docker/pkg/system/lstat_unix.go
- vendor/github.com/docker/docker/pkg/system/lstat_windows.go
- vendor/github.com/docker/docker/pkg/system/mknod.go
- vendor/github.com/docker/docker/pkg/system/mknod_freebsd.go
- vendor/github.com/docker/docker/pkg/system/mknod_unix.go
- vendor/github.com/docker/docker/pkg/system/stat_linux.go
- vendor/github.com/docker/docker/pkg/system/stat_unix.go
- vendor/github.com/docker/docker/pkg/system/stat_windows.go
- vendor/modules.txt
- related: https://github.com/docker/buildx/pull/2874
full diff: https://github.com/docker/docker/compare/v27.4.0...v27.4.1
full diff: https://github.com/docker/cli/compare/v27.4.0...v27.4.1
> vendor: github.com/docker/docker, github.com/docker/cli v27.4.1

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/release/labs/tags
- go.mod
fix #5611
It looks like there was some switch in build tags, resulting in the feature not being enabled in the release and the test being skipped.
> dockerfile: fix copy non-octal build tag

- .github/workflows/.test.yml
- docker-bake.hcl
- frontend/dockerfile/cmd/dockerfile-frontend/hack/release
- hack/images
- hack/test
- hack/util
This allows running Dockerfile tests so that the Dockerfile version and the BuildKit version are from different commits so that we can test that old Dockerfile releases remain compatible with the latest BuildKit.
The tests are based on the commit of the Dockerfile frontend as we can't expect that new test would work on old frontends. In future we might consider doing it the other way as well but then we need a way to mark tests that can be ignored if they are not expected to pass because of a new feature dependency.
Example:
```
DOCKERFILE_RELEASES=mainline TEST_SUITE_CONTEXT=https://github.com/moby/buildkit.git#v0.17.0 TESTPKGS=./frontend/dockerfile TESTFLAGS="-v --run /TestDockerignore$/"  ./hack/test dockerfile
```
This doesn't update Github workflows to trigger tests like this yet. We …
> test: allow testing frontends from different version

- client/ociindex/ociindex.go
- client/ociindex/ociindex_test.go
- client/solve.go
- frontend/dockerfile/dockerfile_test.go
> Fix invalid index.json annotations on tar=false export

- util/disk/disk_freebsd.go
- util/disk/disk_netbsd.go
- util/disk/disk_test.go
Was looking at netbsd support in buildx and it fails to build the `util/disk` package:
```
#18 [buildx-build 1/1] RUN --mount=type=bind,target=.   --mount=type=cache,target=/root/.cache   --mount=type=cache,target=/go/pkg/mod   --mount=type=bind,from=buildx-version,source=/buildx-version,target=/buildx-version <<EOT (set -e...)
#18 0.322 + CGO_ENABLED=0 go build -mod vendor -trimpath -ldflags '-X github.com/docker/buildx/version.Version=v0.19.0-49-g3e1a0982 -X github.com/docker/buildx/version.Revision=3e1a0982b6216e234e5576a5a30c30bf05ed4a6e -X github.com/docker/buildx/version.Package=github.com/docker/buildx -s -w' -o /usr/bin/docker-buildx ./cmd/buildx
#18 1.142 # github.com/moby/buildkit/util/disk
#18 1.142 vendor/github.com/moby/buildkit/util/disk/disk_unix.go:13:20: undefined: …
```
> util(disk): freebsd and netbsd support

- README.md
- client/client_test.go
- exporter/containerimage/exptypes/keys.go
- exporter/containerimage/opts.go
- exporter/containerimage/writer.go
fixes #5561
This adds a new exporter option oci-artifact. If set then it changes the attestation manifest to be exported with following changes:
- subject field is added to attestation manifest
- config uses empty descriptor instead of fake image config
- artifactType property is set
The intention is to change this behavior from opt-in to opt-out in some future release when target is OCI image.
Example https://explore.ggcr.dev/?image=docker.io/tonistiigi/buildkit@sha256:bf8355824354aee83a9874f7178ea91a17752603a949e89f00f9e3ca5404db35&mt=application%2Fvnd.oci.image.manifest.v1%2Bjson&size=915
Quick test:
```
docker buildx create --bootstrap --name=dev --driver-opt image=tonistiigi/buildkit:artifact-mfst
```
> add OCI artifact version of attestation manifest

- frontend/dockerfile/parser/directives.go
- frontend/dockerfile/parser/directives_test.go
regression from https://github.com/moby/buildkit/pull/4962
ParseDirectives code was changed when "check" directive was added and copied over logic from DetectSyntax function. This does not look correct as the only allowed formatting for Dockerfile directives is with a Dockerfile comment. "#syntax" is a special case because we want to allow frontend forwarding capability also in non-Dockerfile sources that use different style of comments or using config files with JSON as frontend entrypoints.
> dockerfile: don't allow non-Dockerfile syntax for directives

- go.mod
- go.sum
- vendor/golang.org/x/net/http2/client_conn_pool.go
- vendor/golang.org/x/net/http2/frame.go
- vendor/golang.org/x/net/http2/http2.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/http2/unencrypted.go
- vendor/modules.txt
contains a fix for CVE-2024-45338 / https://go.dev/issue/70906, but it doesn't affect our codebase:
govulncheck -show=verbose ./...
...
Vulnerability #1: GO-2024-3333
Non-linear parsing of case-insensitive content in golang.org/x/net/html
More info: https://pkg.go.dev/vuln/GO-2024-3333
Module: golang.org/x/net
Found in: golang.org/x/net@v0.29.0
Fixed in: golang.org/x/net@v0.33.0
Your code is affected by 0 vulnerabilities.
This scan also found 0 vulnerabilities in packages you import and 1
vulnerability in modules you require, but your code doesn't appear to call these
vulnerabilities.
> vendor: golang.org/x/net v0.33.0

- client/client_test.go
- client/llb/imagemetaresolver/resolver.go
- exporter/containerimage/annotations.go
- exporter/containerimage/exptypes/annotations.go
- exporter/containerimage/exptypes/parse.go
- exporter/verifier/platforms.go
- frontend/dockerfile/builder/build.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/platform.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerui/build.go
- frontend/dockerui/config.go
- solver/llbsolver/bridge.go
- source/containerimage/source.go
This allows platforms following the new `platforms.FormatAll` function, which allows for setting the `OSVersion` field of the platform with `<os>(<ver>)/<arch>`.
Closes #5115 
---
*Note*: In order to make `FROM <img>` match the correct OS version with the new platform format some changes need to be made to containerd/platforms (see vendor/ changes).
> Support OS version in platform string

- cmd/buildkitd/main.go
- util/testutil/workers/util.go
Unix socket support for --debugaddr was added later what means the test suite can not be used to test old versions of releases anymore. This makes debug address configurable via env variable so that old versions can just ignore it without crashing.
This resolves the need for extra patch in https://github.com/docker/buildx/pull/2914 to make full buildx test matrix run.
> testing: use env var for configuring debugaddress for tests

- frontend/dockerfile/dockerfile_test.go
we forgot to check feature compat in https://github.com/moby/buildkit/pull/5614
relates to: https://github.com/moby/moby/actions/runs/12778000243/job/35622992353?pr=49279#step:13:4311
```
=== FAIL: frontend/dockerfile TestIntegration/TestPlatformWithOSVersion/worker=dockerd/frontend=client (4.82s)
dockerfile_test.go:9511: 
Error Trace:	/src/frontend/dockerfile/dockerfile_test.go:9511
/src/util/testutil/integration/run.go:98
/src/util/testutil/integration/run.go:212
Error:      	Received unexpected error:
exporter "image" could not be found
github.com/moby/buildkit/util/stack.Enable
/src/util/stack/stack.go:82
github.com/moby/buildkit/util/grpcerrors.FromGRPC
/src/util/grpcerrors/grpcerrors.go:204
github.com/moby/buildkit/util/grpcerrors.UnaryClientInterceptor …
```
> test: missing direct push check feature compat

- cache/contenthash/filehash.go
Otherwise it is very tricky to understand which file produced the error.
Should help with https://github.com/docker/for-win/issues/14083
> chore: annotate errors returned from NewFromStat() with the file path

- frontend/dockerfile/docs/reference.md
Leading and trailing slashes in the source path for `ADD` and `COPY`, when
adding/copying files from the build context, have no effect.
- relates to docker/docs#21825
> docs: clarify leading and trailing slashes in add/copy source path

- solver/llbsolver/history.go
For active builds these records get stored in the memory and marshalled on user request. This leads to possibility that the original record may be updated while the marshalling is happening, leading to a crash.
> llbsolver: take copy of history record to avoid marshal race

- cache/contenthash/filehash.go
Clears ModeIrregular from the checksum generation. This may be sent by the client when the version of Go used is post Go 1.23. The behavior of `os.Stat` was modified in Go 1.23 to set `ModeIrregular` on reparse points in Windows. This clears `ModeIrregular` when any mode is set which was the previous behavior of `os.Stat`.
Fixes https://github.com/docker/for-win/issues/14083.
> contenthash: clear ModeIrregular before sending to archive/tar

- cache/manager.go
- control/control.go
- hack/composefiles/compose.yaml
The prune logic would prune multiple times because one prune could cause more things to be capable of pruning and change the logic. This was done through a recursive invocation.
Since go doesn't have support for function tail calls, this would result in a new stack entry for each loop. This unrolls the logic so the prune function is invoked iteratively rather than recursively.
`prune` and `pruneOnce` have also had their names swapped. In general, `pruneOnce` implies that it runs a single prune while `prune` sounds like the top level function. The current code had this reversed and `pruneOnce` would call `prune` and `prune` would call itself recursively.
I've also updated a section in the controller that invoked prune on each worker. In older versions of Go, the current version was correct …
> cache: convert prune loop from recursive invocation to iterative

- frontend/dockerfile/dockerfile_test.go
This is a follow-up from 94ddeb7dbe427ef6a39dbdbf0d5096b6752da296 to ensure that the expected OSVersion is set on the respective image configs.
> tests: add validation that config has OSVersion set

- util/gitutil/git_cli.go
fix #5329
Git commands are executed using [os/exec](https://pkg.go.dev/os/exec) package and therefore do not share environment variables with the main process, That's why `ADD` doesn't honor proxy related environment variables in this context.
That said, in a pure HTTP context, like:
```dockerfile
ADD https://example.com/archive.zip /usr/src/things/
```
`ADD` already respects proxy-related environment variables because it uses [net/http](https://pkg.go.dev/net/http) package internally.
> fix git http_proxy ignored

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/issue_reporting_guide.md
- .github/issue_template.md
Closes #5587 
This PR replaces the deprecated legacy markdown template at `.github/issue_template.md` with new YAML-based forms for bug reports and feature requests. Blank issues are still allowed under this PR's configuration. An issue type is also added when available.
Note that for the forms most fields are required.
- [Issue template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) added with links to discussions, slack and documentation
- Bug report form
- Feature request form
- [GitHub form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
- [Issue types …
> Replace legacy issue template with revised issue forms

- .github/ISSUE_TEMPLATE/config.yml
Removes the security report prompt in the issue chooser as there is already a dynamic one being shown.
> Remove dupe security entry from issue selection prompt

- cmd/buildctl/build.go
- session/auth/authprovider/authprovider.go
- session/auth/authprovider/authprovider_test.go
This exposes a mechanism to expire cached auth configs.
> authprovider: Add support for expiring auth cache

- go.mod
- go.sum
- vendor/modules.txt
- relates to https://github.com/moby/buildkit/pull/5663
no changes in vendored files
full diff: https://github.com/docker/docker/compare/v27.5.0...v27.5.1
no changes in vendored files
full diff: https://github.com/docker/cli/compare/v27.5.0...v27.5.1
> vendor: github.com/docker/docker, github.com/docker/cli v27.5.1

- docs/windows.md
The previous instructions had a slight mistake where the CNI version was similar to the CNI plugin Version. At that time, that was true, we had 0.3.0. However, the latest plugin version is 0.3.1 and supports upto CNI v 1.0.0.
Fix the installation scripts to have `$cniVersion` and `$cniPluginVersion` as separate variables.
Also add script to set up HNS Network on WS2019 when it is not already available by default, like in the rest of the SKUs WS2022+, after enabling Hyper-V.
> fix: docs: windows: enhance the CNI setup instructions

- solver/bboltcachestorage/storage.go
The `emptyBranchWithParents` method could accidentally leave link entries that shouldn't exist. When finding these links, deleting during the iteration can sometimes cause the cursor to jump entries that should be deleted.
This changes the code path to delete the links outside of the iteration to avoid this.
This is caused by a long-standing bug in bolt that can't be fixed easily. See https://github.com/etcd-io/bbolt/pull/611 for details.
> bboltcachestorage: delete links outside of cursor

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerui/config.go
- frontend/dockerui/namedcontext.go
- frontend/gateway/gateway.go
fixes https://github.com/docker/buildx/issues/2939
Avoids pulling in a named context if the build dependencies are not actually using it. The main case where this issue appears is when image is used as a named context and image config would be resolved. In addition to wasting resources, the image could also be invalid for the current build configuration and cause the build to fail.
> dockerfile: avoid too eager loading of unreachable named contextes

- .github/workflows/test-os.yml
**PR Description:**
PR updates the GitHub Actions workflow by expanding the OS matrix to include Windows 2025, ensuring broader compatibility and testing coverage.
**Changes Introduced:**
- Added `windows-2025` to the OS matrix for test-windows-amd64.
- Added `overwrite: true` to allow re-uploading the same artifact without failure
**Testing Steps:**
- Run the workflow and confirm jobs execute on both Windows 2022 and Windows 2025.
> Add Windows-2025 to GitHub Actions OS Matrix

- cache/remotecache/s3/s3.go
The `open` method did not handle the offset parameter. It was almost never used, except in the case reported in #5584, leading to a crash.
> [s3 cache] Fix upload of downloaded layer

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
Restores the behavior from v0.12.
fix #5713
@TBBle @cpuguy83 
Signef-off-by: Tonis Tiigi <tonistiigi@gmail.com>
> dockerfile: maintain osversion/variant from the base image

- util/testutil/workers/containerd.go
- util/testutil/workers/oci.go
- util/testutil/workers/util.go
https://github.com/docker/buildx/actions/runs/13273311632/job/37057606640#step:7:10250
```
2025/02/11 22:02:30 Incorrect Usage. flag provided but not defined: -cdi-spec-dir
2025/02/11 22:02:30 
2025/02/11 22:02:30 NAME:
2025/02/11 22:02:30    buildkitd - build daemon
2025/02/11 22:02:30 
2025/02/11 22:02:30 USAGE:
2025/02/11 22:02:30    buildkitd [global options] command [command options] [arguments...]
```
> testutil: set cdi spec dir with config

- solver/llbsolver/ops/exec.go
fixes https://github.com/moby/buildkit/issues/5724
> exec: check cdi manager not nil

- go.mod
- go.sum
- vendor/github.com/package-url/packageurl-go/Makefile
- vendor/github.com/package-url/packageurl-go/README.md
- vendor/github.com/package-url/packageurl-go/packageurl.go
- vendor/modules.txt
using a tagged release; picking the nearest release (newer versions are available, but would bring a larger diff)
full diff: https://github.com/package-url/packageurl-go/compare/89078438f170...v0.1.1
> vendor: github.com/package-url/packageurl-go v0.1.1

- client/client_test.go
- exporter/verifier/platforms.go
- solver/result/result.go
When `--call=lint` or `--call=outline` were used, the intention wasn't to run this check because the result doesn't have a platform. When those checks are run, there is no exporter platforms key.
We would check `Request` from the request operations, but this wasn't a reliable way to determine whether the result was from a lint because it is possible for subrequests to have different frontend attributes than the primary request and the primary request would sometimes not have the `requestid` attribute set.
Instead of detecting a subrequest with that method, the check has been updated to exit if there are no references and if there is no exporter key.
Fixes #5693.
> verifier: do not run invalid platforms check when there are no results

- Dockerfile
- solver/llbsolver/ops/exec_binfmt.go
New emulators that have been added to binfmt image are not actually referenced from the buildkit embedded loader. They are also rare enough not to be worth including. BuildKit can still use these emulators if they are installed into the kernel externally (what is recommended anyway).
> remove unused emulators from exported image

- docs/cdi.md
- util/appdefaults/appdefaults_windows.go
Since CDI support is enabled by default, add a default CDI spec directory for Windows. Without this, the
buildkitd fails to start with error:
buildkitd: No CDI specification directories specified
Also add a note on the docs that the support is yet to be tested on Windows.
> fix: cdi: add appdefaults.CDISpecDirs for windows

- cache/remotecache/gha/gha.go
- cmd/buildctl/build/util.go
If `url_v2` is sent it switches to API v2. Separate field would be needed so client can send either `url` or `url_v2` if they don't know if the buildkit can handle V2 URLs or not.
> gha: allow url_v2 input attribute

- .github/workflows/test-os.yml
**Summary**
Mark Windows 2025 tests as non-blocking by adding `continue-on-error: true`. This allows failures on Windows 2025 to be treated as warnings while keeping Windows 2022 required.
**Changes:**
- Added `continue-on-error: true` for Windows 2025 in the test matrix.
**Why?**
- some of Windows 2025 tests are flaky.
> mark Windows 2025 tests as non-blockin

- cache/remotecache/gha/gha.go
relates to https://github.com/docker/buildx/pull/3001#issuecomment-2663752020
`url` will always be empty if cache service v2 is detected and `url_v2` set.
> cache(gha): don't require url attr if url_v2 is set

- client/build_test.go
- client/client_test.go
- client/solve.go
- cmd/buildctl/build.go
- cmd/buildctl/build/allow.go
- cmd/buildctl/debug/workers.go
- cmd/buildkitd/config/config.go
- cmd/buildkitd/main.go
- cmd/buildkitd/main_containerd_worker.go
- cmd/buildkitd/main_oci_worker.go
- control/control.go
- frontend/dockerfile/dockerfile_rundevice_test.go
- frontend/dockerfile/dockerfile_runnetwork_test.go
- frontend/dockerfile/dockerfile_runsecurity_test.go
- solver/llbsolver/bridge.go
- solver/llbsolver/cdidevices/fixtures/vendor1-device.yaml
- solver/llbsolver/cdidevices/fixtures/vendor1-deviceclass.yaml
- solver/llbsolver/cdidevices/fixtures/vendor1-devicemulti.yaml
- solver/llbsolver/cdidevices/manager.go
- solver/llbsolver/cdidevices/manager_test.go
- solver/llbsolver/solver.go
- solver/llbsolver/vertex.go
- util/entitlements/entitlements.go
- worker/runc/runc.go
Devices can be marked as "automatically allowed" by TOML config or by the CDI spec of specific file via annotation.
Device that is is not "automatically allowed" needs to be allowed by the build request by passing entitlement. For example a Dockerfile may not use a device without use invoking the build permitting it.
```
--allow device grants access to any device.
--allow device=kind|name grants access to specific device.
--allow device=kind|name,alias=kind|name allows mapping kind to a specific device or one device to another. Alias is the name requested by the build and device is the actual device that is being enabled.
```
> add autoallow and entitlements support to CDI devices

- exporter/containerimage/exptypes/parse.go
- frontend/dockerfile/builder/build.go
- frontend/dockerui/build.go
- frontend/dockerui/config.go
- solver/llbsolver/ops/exec.go
I came across a number of calls to `platforms.DefaultSpec()` that were not necessary. That prompted me to take a look various other similar places.
At least on Windows, the call is a has some cost till doing a sycall `RtlGetNtVersionNumbers()`.
> refactor: avoid unnecessary calls to platforms.DefaultSpec()

- frontend/dockerfile/dockerfile_outline_test.go
- frontend/dockerfile/dockerfile_test.go
This is a continuation for the integration tests work #4485 We had some tests that we marked as Revit during our first pass through the tests.
This commit addresses the following tests in `frontedn/dockerfile`:
> tests: frontend/dockerfile: update integration tests for windows/wcow (revisited)

- cache/contenthash/checksum.go
- cache/contenthash/checksum_unix.go
- cache/contenthash/checksum_windows.go
- client/client_test.go
- executor/oci/spec.go
- executor/oci/spec_unix.go
- executor/oci/spec_windows.go
- frontend/dockerfile/dockerfile2llb/convert_runmount.go
- frontend/dockerfile/dockerfile_mount_test.go
- frontend/dockerfile/parser/parser.go
- frontend/dockerfile/parser/split_command.go
- util/system/path_unix.go
- util/system/path_windows.go
Currently, mounts are not supported for WCOW builds, see #5678. This commit introduces support for bind and cache mounts (through the dockerfile frontend). The remaining two require a little more work and consultation with the platform teams for enlightment.
WIP Checklist:
Addresses part of https://github.com/moby/buildkit/issues/5678
Fixes #5603
---
Prep the context directory:
```powershell
mkdir mounts-demo
cd mounts-demo
mkdir temp
echo "hello: root" > root.txt
echo "hello: inner" > .\temp\inner.txt
```
Dockerfile:
```dockerfile
FROM mcr.microsoft.com/windows/nanoserver:ltsc2022 AS base
USER ContainerAdministrator
RUN --mount=type=cache,target=/mycache echo "hello" > \mycache\foo
RUN --mount=type=cache,target=/mycache dir \mycache\foo
FROM base
RUN --mount=type=bind,target=/out type …
```
>  feat: wcow: add support for bind and cache mounts

- client/client_test.go
- client/llb/source.go
- solver/pb/attr.go
- solver/pb/caps.go
- source/http/identifier.go
- source/http/source.go
Support authentication for HTTP sources.
- llb: Define general `llb.AuthOption` interface composed of `HTTPOption` and `GitOption`.
- llb: Refactor `llb.AuthHeaderSecret` to return an `llb.AuthOption` so it may be used with both `llb.Git` and `llb.HTTP`.
- llb: Define `HTTPInfo.AuthHeaderSecret`.
- llb: Define and flag new `source.http.auth` capability when `HTTPInfo.AuthHeaderSecret` is set.
- solver: Define new `http.auth` source attribute.
- source/http: If an `http.auth` attribute is specified, resolve a secret named by its value and set the "Authorization" request header.
> http: Support authentication

- client/client_test.go
- client/llb/source.go
- solver/pb/attr.go
- solver/pb/caps.go
- source/http/identifier.go
- source/http/source.go
Support additional request header fields for HTTP sources, "Accept" and
"User-Agent" as a start.
The "Accept" header is required in some cases and some servers may vary
the response body based on the header value.
The "User-Agent" header may be useful in custom frontends and
potentially other cases.
- llb: Add `llb.Header` and `HTTPInfo.Header` to allow `client/llb`
users to set these header fields on HTTP sources. The argument to
`llb.Header` is a struct to effectively limit header fields to a
subset.
- llb: Define and flag new `source.http.header` capability when
`llb.Header` is used.
- solver: Define new `http.header.` source attribute prefix. Giving
each header field its own attribute (opposed to JSON encoding the
header struct) will allow source policy to make assertions on …
> http: Support additional request headers

- cmd/buildkitd/main.go
- go.mod
- go.sum
- vendor/modules.txt
- vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache.go
fix https://github.com/moby/buildkit/issues/5767
Test patch https://github.com/cncf-tags/container-device-interface/pull/254 on v0.8.0
Pushed test image `tonistiigi/buildkit:cdi-fsnotify-fix`
> vendor: cdi v0.8.1 for panic fix

- frontend/dockerfile/dockerfile2llb/convert.go
Base image may use unnormalized platform so if platform is inherited normalize needs to be called again.
OCI  specs lib could also do it in `MarshalJSON`. 
fix #5774
changed in https://github.com/moby/buildkit/pull/5714
> dockerfile: normalize platform in image config

- control/control.go
- snapshot/containerd/content.go
Trace blob is created 3 seconds after build completion. If this happens after test has cleaned all history records and before it checks for leaked blobs, test can report the trace blob as leaked. In practice it would be cleaned up next time containerd GC gets triggered.
> fix trace blob detected as leaked blob in tests

- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_test.go
- solver/llbsolver/file/backend.go
- util/system/path.go
- util/system/path_test.go
The call to CheckSystemDriveAndRemoveDriveLetter() does not preserve the trailing `/` or `\\`. This happens because `filepath.Clean()` strips away any trailing slashes. For example `/sample/` will be `\\sample` on Windows. This function was mainly written for Windows scenarios, which have System Drive Letters like C:/, etc.
This was causing cases like `COPY testfile /testdir/` to be intepreted as `COPY testfile /testdir`, and if `testdir` is not explictly created before the call, it ends up being treated as a destination file other than a directory.
Fix this by checking that if we have a trailing `/` or `\\`, we preserve it after the call to `filepath.Clean()`.
Fixes #5249
PS.
Also fixed for cross-building Windows from Linux, that would fail silently:
Repro dockerfile without `RUN`: …
> fix: util/path: `CheckSystemDriveAndRemoveDriveLetter` to preserve `/`

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/v2/core/content/proxy/content_writer.go
- vendor/github.com/containerd/containerd/v2/pkg/oci/spec_opts.go
- vendor/github.com/containerd/containerd/v2/version/version.go
- vendor/modules.txt
Brings in the gRPC message size fix for writing SBOMs.
closes https://github.com/moby/buildkit/issues/5327
replaces #5785
> vendor: update containerd to v2.0.3

- docs/rootless.md
- examples/kubernetes/README.md
- examples/kubernetes/deployment+service.userns.yaml
- examples/kubernetes/job.rootless.yaml
- examples/kubernetes/job.userns.yaml
- examples/kubernetes/pod.rootless.yaml
- examples/kubernetes/pod.userns.yaml
- examples/kubernetes/statefulset.rootless.yaml
- examples/kubernetes/statefulset.userns.yaml
Fix #5763
- Discourage `--oci-worker-no-process-sandbox`, due to the leakage of the processes (by design). Instead, encourage setting `systempaths=unconfined` in `docker run`. This corresponds to `securityContext.procMount: Unmasked` in Kubernetes, however, the configuration is hard on Kubernetes, as it has to be used in conjunction with `hostUsers: false`.
- Remove `--device /dev/fuse`, as fuse-overlayfs is no longer used typically.
- Use the new Kubernetes struct for AppArmor
- Add a hint about `kernel.apparmor_restrict_unprivileged_userns`
- Remove `$` from command snippets for ease of copypasting
- Make `job.*.yaml` more practical
- Add `*.userns.yaml`. Needs `UserNamespaceSupport` feature gate to be enabled.
- - -
TODO: update buildx to support UserNS mode too
> rootless: update docs and examples

- .github/workflows/test-os.yml
Since the integration tests on WS2025 are flaky,
pause them for the time being pending investigation.
Follow up on #5806
> fix: wcow: pause integration tests on WS2025

- Dockerfile
- cmd/buildkitd/main.go
- docs/rootless.md
- examples/kubernetes/README.md
- examples/kubernetes/deployment+service.userns.yaml
- examples/kubernetes/job.rootless.yaml
- examples/kubernetes/job.userns.yaml
- examples/kubernetes/pod.rootless.yaml
- examples/kubernetes/pod.userns.yaml
- examples/kubernetes/statefulset.rootless.yaml
- examples/kubernetes/statefulset.userns.yaml
- frontend/dockerfile/dockerfile2llb/convert.go
- go.mod
- go.sum
- vendor/github.com/containerd/containerd/v2/core/content/proxy/content_writer.go
- vendor/github.com/containerd/containerd/v2/pkg/oci/spec_opts.go
- vendor/github.com/containerd/containerd/v2/version/version.go
- vendor/github.com/tonistiigi/go-actions-cache/cache_v2.go
- vendor/modules.txt
- vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache.go
backport of:
* https://github.com/moby/buildkit/pull/5769
* https://github.com/moby/buildkit/pull/5797 (small conflict in go.mod)
* https://github.com/moby/buildkit/pull/5808
* https://github.com/moby/buildkit/pull/5765
* https://github.com/moby/buildkit/pull/5798
* https://github.com/moby/buildkit/pull/5776
> [v0.20] cherry-picks for v0.20.1

- solver/jobs.go
Buildx pulls images lazily on first access in the preprocess stage of child step. This fixes the trace spans still appearing under original command.
Before:
After:
> solver: fix parent span for preprocess traces

- frontend/gateway/container/container.go
- solver/llbsolver/ops/exec.go
- source/git/source.go
The current logic was incorrect in some places so that if first session randomly chosen by `Any()` returned NotFound then other sessions were not attempted.
For the main use case of mounting secrets as files the logic was correct, but it was incorrect for example for the case of adding secrets as environment variables.
fix https://github.com/docker/buildx/issues/3056
> solver: fix reading secrets from any session

- Dockerfile
BuildKit image does not have any CDI spec folders created so when running this container we have the following "CDI setup error" warnings:
```
time="2025-03-14T10:39:34Z" level=info msg="auto snapshotter: using overlayfs"
time="2025-03-14T10:39:34Z" level=warning msg="CDI setup error /etc/buildkit/cdi: failed to monitor for changes: no such file or directory"
time="2025-03-14T10:39:34Z" level=warning msg="CDI setup error /etc/cdi: failed to monitor for changes: no such file or directory"
time="2025-03-14T10:39:34Z" level=warning msg="CDI setup error /var/run/cdi: failed to monitor for changes: no such file or directory"
time="2025-03-14T10:39:34Z" level=warning msg="using host network as the default"
time="2025-03-14T10:39:34Z" level=info msg="found worker \"y0dyo8y35v6fohh1nepmgsnyz\", …
```
> create cdi spec folders in buildkit container

- Dockerfile
https://github.com/containerd/containerd/releases/tag/v2.0.4
> update containerd to v2.0.4

- .golangci.yml
similar to https://github.com/docker/buildx/pull/3069
> don't set go version in golangci-lint config

- Dockerfile
https://github.com/opencontainers/runc/releases/tag/v1.2.6
> update runc to v1.2.6

- frontend/dockerui/build.go
Because dockerui added osversion to original reference before calling res.AddRef() that meant that the sbom was looked up by the wrong key in scanTargets.Load(id) .
Currently build would fail with `ERROR: failed to solve: no scan targets for windows(10.0.17763.7009)/amd64`.
Not quite happy with the current fix. If I would keep the `OSVersion` in the key then I would need to copy the `extendWindowsPlatform` logic to `dockerfile/build` pkg as well as current helper is in `dockerui`. I guess collisions shouldn't be a problem for current patch as if multiple osversion are used by the same build then they should be set by user anyway, not detected from image. It would be better if there was some more direct way to capture the actual result key or `sbomTargets` should use some other way for …
> dockerfile: fix sbom attestation for windows targets

- exporter/containerimage/export.go
- exporter/containerimage/exptypes/keys.go
Modifies the containerd exporter to create dangling images by default. A
new exporter key has been added to keep the previous behavior where a
dangling image is only created when no image name is provided.
Related to moby/moby#48907 and moby/moby#46116.
> containerimage: container image exporter creates dangling images by default

- solver/llbsolver/vertex.go
`OnDemand` devices are never allowed with current entitlements validation logic. That's because this kind of device is not yet registered in CDI cache at this point.
> fix entitlements handling for OnDemand CDI devices

- session/auth/authprovider/authprovider.go
Tokens for Google Artifact Registry via Workload Identity expire after 5 minutes.
fixes #5852
> fix: reduce default expire time for opaque tokens

- snapshot/localmounter_windows.go
> WIP: still ongoing with investigation to determine
> exactly which process is accessing the file, will
> update on the issue #5807 thread for the records.
Fix the race condition with maximum 2 retries.
From several tests, 1 retry seems to be
enough, even without backoff. Added a simple
linear backoff for each retry starting at 30 ms.
fixes #5807
---
Here is a repro run + the mitigation - [repro_run_8min.webm](https://github.com/user-attachments/assets/9fecd8a0-48fd-45fc-bfeb-3f7b0267d3d7). See around t 1:55, on the 25th run. Hit the issue 1 in 100 runs, mostly it's been 2-3 in 100 runs.
Here's the repro script I was using:
```powershell
param(
[Parameter(Position = 0)]
[int]$Count = 50,
[Parameter(Position = 1)]
[int]$Pause = 3
)
$dockerfile = @"
FROM …
```
> fix: wcow: fix race condition in localmounter

- util/testutil/integration/run.go
- worker/containerd/containerd_test.go
- worker/runc/runc_test.go
- worker/tests/common.go
Worker unit tests pull images from registry, but don't use the mirroring support in the integration tests and can therefore get rate-limited.
> tests: integrate mirror into worker tests

- hack/dockerfiles/lint.Dockerfile
I wrote this to help bisect the lint error in https://github.com/moby/buildkit/pull/5814
```
> [golangci-lint 1/1] RUN --mount=target=/go/src/github.com/moby/buildkit     --mount=target=/root/.cache,type=cache,id=lint-cache-${TARGETNAME}-linux/s390x   xx-go --wrap &&   golangci-lint run --build-tags "${BUILDTAGS}" &&   touch /golangci-lint.done:
6.996 level=error msg="[linters_context] gocritic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt: setting an explicit GOROOT can fix this problem"
------
lint.Dockerfile:47
```
Fails in v1.64.2+, Passes in v1.63.4 . Note failures are for s390x. Both work fine for amd64/arm64.
But, when building from source then all latest versions pass as well 🤷‍♂️ . The issue in #5814 only appears when using their releases. …
> hack: allow building golangci from source for custom versions

- cache/manager.go
When free-space filter is set without max-space or reserved-space filter, the behaviour is that if the filter matches some records then these records would be pruned, but if it doesn't match any (there are more free space than filter sets already) then the keepBytes would be left to 0, resulting records to be deleted as if no storage constraint was set at all.
> prune: update free-space filter when no max-space set

- cmd/buildctl/common/common.go
In kubernetes environment when the certificate is created by cert-manager.io it will be saved as a secret with ca.crt, tls.crt and tls.key instead of the pem files.
> add support for cert-manager.io syntax for tls using tlsdir

- .github/workflows/test-os.yml
- client/client_test.go
After completing support for `llb.AddMount` in #5708 -- this made possible to add some more `client` integration tests that were making `llb.AddMount` calls.
Most of the tests below are related to this:
Skipped tests (due to registry setup issue, to be addressed separately):
- testUncompressedRegistryCacheImportExport
- testBasicRegistryCacheImportExport
- testMultipleRegistryCacheImportExport
Related to #5678
> tests: client: windows: add various llb.AddMount related tests

- hack/Vagrantfile.freebsd
relates to https://github.com/moby/buildkit/actions/runs/14322174133/job/40153267511#step:6:68
```
default: Running: inline script
default: + kldload nullfs
default: + pkg install -y git runj
default: Updating FreeBSD repository catalogue...
default: FreeBSD repository is up to date.
default: All repositories are up to date.
default: pkg: No packages available to install matching 'runj' have been found in the repositories
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Error: Process completed with exit code 1.
```
Latest http://pkg.freebsd.org/FreeBSD:14:amd64/latest/ does not seem compatible anymore with current Vagrant …
> ci: fix freebsd package repository

- cache/contenthash/tarsum.go
- cache/filelist.go
- cache/manager.go
- cache/remotecache/v1/utils.go
- client/diskusage.go
- client/llb/exec.go
- cmd/buildctl/debug/workers.go
- cmd/buildkitd/main.go
- exporter/verifier/platforms.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/dockerfile_test.go
- frontend/dockerfile/instructions/bflag_test.go
- frontend/dockerfile/instructions/parse.go
- frontend/gateway/container/container.go
- solver/llbsolver/history.go
- solver/llbsolver/ops/file.go
- solver/llbsolver/provenance/capture.go
- solver/progress.go
- util/apicaps/caps.go
- util/archutil/detect.go
- util/flightcontrol/flightcontrol.go
- util/progress/multiwriter.go
- util/progress/progress.go
- util/progress/progressui/display.go
- util/resolver/authorizer.go
- util/staticfs/static.go
- util/testutil/integration/run.go
- util/tracing/detect/detect.go
This is a partial update. Still places left that use `sort`.
> lint: update some sorting code to newer generics based libs

- docs/stargz-estargz.md
- util/resolver/authorizer.go
Link to https://distribution.github.io/distribution instead
Signed-off-by: Alberto Garcia Hierro <damaso.hierro@docker.com>
> chore: update broken links to https://docs.docker.com/registry

- Dockerfile
dlv is at /out, not at /usr/bin
> fix(debug): use correct path when copying delve to buildkit-linux-debug

- docs/windows.md
- util/appdefaults/appdefaults_windows.go
To enable CNI networking for WCOW, you needed to provide long paths when running the daemon, e.g.
```
buildkitd `
--containerd-cni-config-path="C:\Program Files\containerd\cni\conf\0-containerd-nat.conf" `
--containerd-cni-binary-dir="C:\Program Files\containerd\cni\bin"
```
Fix this so that the default paths are set in appdefaults, instead of the one that had be set previously.
Now you can just run: `buildkitd`.
Also, refactor the script for setting up CNI binaries and configs, to make it easy to refresh the configs without having to download the binaries afresh.
> fix: wcow: simplify CNI setup for windows

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/stat_unix.go
- vendor/modules.txt
Includes a change to ignore `com.apple.` extended file attributes when
using stat on a file so it is not considered for contenthash equality.
Fixes #5899.
> vendor: update fsutil to master

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/v2/client/container.go
- vendor/github.com/containerd/containerd/v2/client/task.go
- vendor/github.com/containerd/containerd/v2/client/task_opts.go
- vendor/github.com/containerd/containerd/v2/client/task_opts_unix.go
- vendor/github.com/containerd/containerd/v2/core/remotes/docker/pusher.go
- vendor/github.com/containerd/containerd/v2/defaults/defaults_snapshotter_linux.go
- vendor/github.com/containerd/containerd/v2/defaults/defaults_snapshotter_unix.go
- vendor/github.com/containerd/containerd/v2/pkg/oci/spec_opts.go
- vendor/github.com/containerd/containerd/v2/version/version.go
- vendor/github.com/docker/docker/libnetwork/internal/resolvconf/resolvconf.go
- vendor/modules.txt
full diff: https://github.com/containerd/containerd/compare/v2.0.4...v2.0.5
diff:  https://github.com/docker/docker/compare/v28.1.0...v28.1.1
diff:  https://github.com/docker/cli/compare/v28.1.0...v28.1.1
> vendor: github.com/docker/docker, docker/cli v28.1.1, containerd v2.0.5

- .github/workflows/.test.yml
- .github/workflows/buildkit.yml
- .github/workflows/dockerd.yml
- .github/workflows/frontend.yml
- .github/workflows/test-os.yml
- .github/workflows/validate.yml
- client/client_test.go
- Backport of https://github.com/moby/buildkit/pull/4605
- Skip testBasicGhaCacheImportExport  test due to https://gh.io/gha-cache-sunset
Since Moby 25.0.x LTS relies on the BuildKit v0.12 branch and actively runs its tests in CI, keeping that branch in a solid, working state is crucial for:
- Stability: Ensures Moby LTS users don’t encounter unexpected build issues.
- CI Integration: Prevents downstream failures in Moby’s CI pipeline.
> [v0.12] GitHub Actions update

- go.mod
- go.sum
- vendor/github.com/vbatts/tar-split/archive/tar/format.go
- vendor/github.com/vbatts/tar-split/archive/tar/reader.go
- vendor/github.com/vbatts/tar-split/archive/tar/writer.go
- vendor/modules.txt
- archive/tar: fix for CVE-2022-2879
used by estargz, which updated in upstream, but did not yet do a release including that update [containerd/stargz-snapshotter@b07768f].
full diff: https://github.com/vbatts/tar-split/compare/v0.11.6...v0.12.1
[containerd/stargz-snapshotter@b07768f]: https://github.com/containerd/stargz-snapshotter/commit/b07768ff1c446145108167aae1497fdda960ea8e
> vendor: github.com/vbatts/tar-split v0.12.1 (indirect)

- client/client_test.go
Ordering was wrong for the function which resulted in a test failure
showing "expected" as the "actual" and vice versa.
Noticed from https://github.com/moby/moby/pull/49702#issuecomment-2829759977.
> client: reorder arguments for integration test

- frontend/dockerui/build.go
- frontend/dockerui/build_test.go
Fix #5915
Test (on ARM):
```dockerfile
FROM hello-world
```
```console
buildctl build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --opt attest:sbom=
```
> frontend/dockerui/build: fix "no scan targets for linux/arm64/v8"

- cmd/buildctl/common/common.go
- cmd/buildctl/common/common_test.go
- cmd/buildctl/main.go
- docs/reference/buildctl.md
`tldir` flag handling now properly handles the old logic and the new
logic for cert-manager.io without failing.
Improved error message when files are missing.
Fixes #5931.
Replaces #5935.
Co-authored-by: Gleb Nebolyubov <gleb.nebo@gmail.com>
Signed-off-by: Jonathan A. Sternberg <jonathan.sternberg@docker.com>
> buildctl: fix tlsdir handling logic for cert-manager.io

- util/grpcerrors/grpcerrors.go
- util/grpcerrors/grpcerrors_test.go
If decoding the status fails, retain the original proto message by
registering it as a detail.
This change also adds a test to verify that unknown types are preserved when:
- Decoding a gRPC error with unknown detail types.
- Re-encoding and decoding the error using ToGRPC / FromGRPC.
Additionally, fix an issue where the codes.Code string prefix was
not handled correctly, resulting in a duplicate prefix.
> feat(grpc): preserve unknown detail types when decoding gRPC errors

- util/testutil/dockerd/daemon.go
- util/testutil/dockerd/daemon_unix.go
- util/testutil/dockerd/daemon_windows.go
- util/testutil/workers/dockerd.go
- util/testutil/workers/util_unix.go
- util/testutil/workers/util_windows.go
Currently, dockerd and dockerd-containerd integration tests are only ran for Linux at [moby/moby] `.github/workflows/buildkit.yml`
moby/moby runs this workflow against feature buildkit releases as evaluated by `./hack/buidkit-ref`.
This change facilitates adding support for Windows, see example run here [1], and updated workflow file here [2].
Work to integrate buildkit on Docker Engine is ongoing here [3], and this integration tests are part of what's needed to complete.
[1] https://github.com/profnandaa/moby/actions/runs/14811696298
[2] https://github.com/profnandaa/moby/blob/c9d2649f4ddb86f8f68dd3e56f358537c4d2b8f3/.github/workflows/buildkit.yml#L266-L381
[3] https://github.com/moby/moby/pull/49740
> util: testutil: enable `dockerd-containerd` worker for wcow integration tests

- cache/remotecache/export.go
- cache/remotecache/local/local.go
- cache/remotecache/registry/registry.go
fix #5965
Improve error message and don't default to `image-manifest=true` if user intentionally sets `oci-mediatypes=false`.
> cache: improve migration to image manifest cache

- client/llb/exec.go
- exporter/containerimage/writer.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile2llb/image.go
- frontend/dockerfile/dockerfile_lint_test.go
- frontend/dockerfile/dockerfile_test.go
- solver/llbsolver/ops/exec.go
The PATH is very critical during container runs on Windows. Windows stores the PATH details in its
registry hive, while in unix, this is often stored in the image's config. See further details at #5445
Setting a default path like we do on Linux (which is mostly not used since the PATH is
already set in the configs), works against the expected build experience, especially when
it comes to installers and commands like `setx`.
Therefore, we skip setting the default PATH on Windows, and leave it for the OS to load it from its registry hive.
This also further supports backward compatibilitiy with the current experience with docker classic
builder.
Users wishing to explicitly store this in the configs can opt-in by using the `ENV PATH= ..` in the Dockerfile, etc.
See also the same practices on …
> windows: leave default PATH env to be set by the OS

- cmd/buildkitd/config/config.go
Previously, when no platforms were explicitly defined in the config,
serialization would emit an empty array instead of omitting the field.
When loading this cofig, this prevented the worker from falling back
to default platform detection during initialization. By using `omitempty`,
we ensure the field is excluded when empty, allowing defaults to be
correctly applied.
Fixes #5740.
Signed-off-by: Alberto Garcia Hierro <damaso.hierro@docker.com>
> fix: omit empty list of platforms when serializing worker config

- frontend/dockerfile/parser/parser.go
- frontend/dockerfile/parser/parser_heredoc_test.go
- frontend/dockerfile/shell/lex.go
Fixes https://github.com/moby/buildkit/issues/5778.
FYI @tianon @thaJeztah
> dockerfile: allow whitespace in heredocs

- cache/blobs.go
- cache/manager.go
- cache/refs.go
- cache/remotecache/registry/registry.go
- docs/overlaybd.md
- go.mod
- go.sum
- source/containerimage/pull.go
- vendor/github.com/containerd/accelerated-container-image/LICENSE
- vendor/github.com/containerd/accelerated-container-image/pkg/label/label.go
- vendor/github.com/containerd/accelerated-container-image/pkg/types/types.go
- vendor/github.com/containerd/accelerated-container-image/pkg/utils/cmd.go
- vendor/github.com/containerd/accelerated-container-image/pkg/utils/du_unix.go
- vendor/modules.txt
[Overlaybd](https://github.com/containerd/overlaybd) is a remote image format based on the block device, which can load data on demand. You can see [the paper](https://www.usenix.org/conference/atc20/presentation/li-huiba) for more information.
In order to build overlaybd images using buildkit, some changes have been made that are separate from the original process. Please refer to the docs/overlaybd.md for guidance on building overlaybd images.
Signed-off-by: Haoqi Miao <miaohaoqi.mhq@alibaba-inc.com>
> Support for building overlaybd images

- client/client_test.go
- solver/llbsolver/cdidevices/fixtures/vendor1-devicemulti.yaml
- solver/llbsolver/cdidevices/manager.go
- solver/llbsolver/cdidevices/manager_test.go
follow-up https://github.com/moby/buildkit/pull/5923#pullrequestreview-2826593148
Current logic to find devices by class annotation was not correct. Now user can just specify the class of the device without it being a device qualifer so it handles multiple CDI specs registered.
> cdi: fix device request by class annotation

- go.mod
- go.sum
- vendor/modules.txt
- relates to https://github.com/moby/buildkit/pull/3867
full diff: https://github.com/containerd/accelerated-container-image/compare/v1.2.3...v1.3.0
> vendor: github.com/containerd/accelerated-container-image v1.3.0

- client/llb/source.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_addchecksum_test.go
- frontend/dockerfile/dockerfile_addgit_test.go
- solver/pb/attr.go
- solver/pb/caps.go
- source/git/identifier.go
- source/git/source.go
- source/git/source_test.go
Split from:
- https://github.com/moby/buildkit/pull/5903
- - -
Not integrated to util/giturl, as the following PR is not merged yet.
- #5974
> git source: add AttrGitChecksum

- client/client_test.go
Still investigating `testCachedMounts`, skipping for now to avoid blocking the CI.
ref: #5906
> tests: client: skip flaky test on windows

- Dockerfile
- docs/cni-networking.md
- docs/windows.md
-S, --show-error: show an error on failure
-f, --fail:       fail fast with no output at all on server errors
Prior to this commit, curl was just saving an error HTML as the content
> Dockerfile: curl: add -S -f

- .github/workflows/test-os.yml
- .github/workflows/validate.yml
- docker-bake.hcl
similar to https://github.com/docker/buildx/pull/2439
Before:
After:
> ci(validate): split by platform

- README.md
Massé is a BuildKit frontend that allows users to express complex container image build configurations in CUE.
It provides CUE definitions for most of the LLB API and allows users to author and share their own higher-level build definitions as CUE modules.
> README.md: Add Massé to the list of frontends

- frontend/dockerfile/dockerfile_test.go
- solver/llbsolver/file/backend.go
- solver/llbsolver/file/unpack.go
Note that chowner callback can't be passed in to unpack because callbacks can not be supported by reexec-chrootarchive because parameters are JSON encoded and because the IDMapping is passed separately to unpack so the passed value doesn't actually represent the real UID.
fix https://github.com/docker/buildx/issues/3144
> file: add chown to archive unpack from copy

- go.mod
- go.sum
- vendor/google.golang.org/grpc/internal/resolver/delegatingresolver/delegatingresolver.go
- vendor/google.golang.org/grpc/internal/transport/http2_client.go
- vendor/google.golang.org/grpc/internal/transport/http_util.go
- vendor/google.golang.org/grpc/version.go
- vendor/modules.txt
Proxy-related fixes in [v1.72.1](https://github.com/grpc/grpc-go/releases/tag/v1.72.1) and [v1.72.2](https://github.com/grpc/grpc-go/releases/tag/v1.72.2)
fixes https://github.com/moby/buildkit/issues/6002
These were brought in with containerd v2.1.1 update in https://github.com/moby/buildkit/pull/5985
@Nunction
> fix HTTP_PROXY errors on local sockets via grpc update

- solver/exporter.go
- solver/exporter_test.go
fixes #5784 (hopefully)
possible that this appears more frequently after #5692
When a cleanup happens while a build is running it may cause boltdb record to be deleted while that record would have been used for cache export of the running build, causing the cache export to fail with Not Found error. This is possible because when the cache is loaded to snapshots, then snapshots are reference counted, protecting against them being released or deleted, but when the cache key is just an intermediary, the query result just gets saved and is used later.
It should be safe to ignore this error and skip over the result if it doesn't exist anymore.
Note that cache export also gets called on provenance creation because cache chains are used for finding remote descriptors for build steps. This was …
> solver: handle not found error on cache export

- client/client_test.go
- source/http/source.go
fix #5978
Allow user to pass `HTTP_AUTH_HEADER_<host>` or `HTTP_AUTH_TOKEN_<host>` secrets with build that would then be used for authorization on `llb.HTTP` calls. Similar secrets are supported for Git operations.
@AkihiroSuda @marxarelli
> http: allow authorization secrets per hostname

- client/client_test.go
- exporter/local/export.go
- exporter/local/export_unix.go
- exporter/local/export_windows.go
- exporter/local/fs.go
- exporter/tar/export.go
Currently the option only worked when platform-split=false was set for multi-platform build but not for setting single platform build to use platform-split=true.
https://github.com/docker/buildx/issues/3215
> local: fix platform-split=true option

- util/resolver/pool.go
When looking up local images from container image store, Get() method only accepts direct name matches. This means that when image name is sent together with a digest value, it is not matched because containerd would expect digest to be part of the image name.
Fixes unnecessary requests in https://github.com/docker/buildx/issues/3225 when containerd image store is enabled in moby.
> resolver: allow reference matches for local image lookups

- util/resolver/pool.go
When looking up local images from container image store, Get() method only accepts direct name matches. This means that when image name is sent together with a digest value, it is not matched because containerd would expect digest to be part of the image name.
(cherry picked from commit 43580f91665c961d204b13e11b3c570278e3f069)
- #6029
> [v0.23] resolver: allow reference matches for local image lookups

- client/client_test.go
- client/solve.go
This just configures `SolveOpt` so that we can directly pass a containerd store through to an exporter (similar to how we do for `OCIStores`). No change in the protocol is needed, and all previous calls to `Solve` should still be valid.
> client: allow configuring exporter content store

- go.mod
- go.sum
- vendor/github.com/tonistiigi/go-actions-cache/cache.go
- vendor/github.com/tonistiigi/go-actions-cache/cache_v2.go
- vendor/modules.txt
In some conditions, there can be a pause between the initial load of the entry (that already contains a signed download URL even though we don't need it yet) and the time the cache blob is actually downloaded at the end of the build. One such case seems to be accessing SBOM scanner layers after the main build is completed. The signed URL is only valid for 10 minutes, and if more time has passed, then the old URL may receive a 403 error.
upstream version https://github.com/tonistiigi/go-actions-cache/pull/40
> gha cache: reload expired cache URLs

- cache/contenthash/checksum.go
- cache/contenthash/filehash.go
- cmd/buildkitd/debug.go
- cmd/buildkitd/main.go
- solver/bboltcachestorage/storage.go
- solver/cachemanager.go
- solver/llbsolver/ops/build.go
- solver/llbsolver/ops/exec.go
- solver/llbsolver/ops/file.go
- solver/llbsolver/ops/merge.go
- solver/llbsolver/ops/opsutils/contenthash.go
- solver/llbsolver/ops/source.go
- source/local/source.go
- util/cachedigest/db.go
- util/cachedigest/db_test.go
- util/cachedigest/digest.go
- util/cachedigest/frame.go
- util/cachestore/store.go
This allows opt-in to cache key debug database on
daemon startup.
If enabled, all cache keys generated by builds are saved into this database together with the plaintexts of the original data so a reverse lookup can be performed later to compare two checksums and find out their original difference. If checksum contains other checksums internally then these are saved as well. For storage constraints, the plaintext of file content is not saved but the metadata portion can be still looked up.
> add cache key debuginfo lookup

- client/client_test.go
- frontend/dockerfile/dockerfile_mount_test.go
This is to address the flaky tests being on moby/moby too.
ref - https://github.com/moby/moby/issues/50389
> fix: tests: skip flaky integration tests on Windows

- client/llb/state.go
The Env method returns the current environment variables for the state, not a new State with updated env variables.
Updated doc comment to reflect actual behavior.
> fix: corrected doc comment for llb.State.Env

- frontend/dockerfile/dockerfile2llb/convert.go
Fixes https://github.com/moby/buildkit/issues/6098
Created time for returned image config should be nil, and gets reset to the timestamp of last layer created during build in the exporter.
This was the case when using base images from registry but was not the case when base image was replaced with the named context.
> dockerfile: fix created time taken from base image if named context used

- go.mod
- go.sum
- vendor/github.com/docker/go-connections/nat/nat.go
- vendor/github.com/docker/go-connections/nat/parse.go
- vendor/modules.txt
- deprecate sockets.GetProxyEnv, sockets.DialerFromEnvironment
- add support for unix sockets on Windows
- remove legacy CBC cipher suites from client config
- align client and server defaults to be the same.
- remove support for encrypted TLS private keys.
- nat: optimize ParsePortSpec
full diff: https://github.com/docker/go-connections/compare/v0.5.0...v0.6.0
> vendor: github.com/docker/go-connections v0.6.0

- cache/remote.go
The walkBlob function was called with a function having a side effect: appending a descriptor to a list. However, the function could be called multiple times for the same descriptor (once in `walkBlob` and once in `walkBlobVariantsOnly` in that case) leading to duplicate entries in the final list. Instead of the list, we can use a map to store the descriptors. With the digest as key, it will ensure we don't store duplicates.
This fixes one of the problem encountered in #6088
cc @ktock
> [cache] Fix descriptor duplication in getAvailableBlobs

- cache/remotecache/v1/cachestorage.go
- cmd/buildkitd/debug.go
- solver/bboltcachestorage/storage.go
- util/cachedigest/db_test.go
- util/cachedigest/digest.go
- util/cachestore/store.go
follow-up to https://github.com/moby/buildkit/pull/6061
Allows debugging from remote config passed via POST request in addition to debugging local cache store.
> debug: allow debug from remote cache config

- go.mod
- go.sum
- vendor/golang.org/x/sync/errgroup/errgroup.go
- vendor/modules.txt
Brings in the errgroup implementation for reverted auto-recover from panics. https://github.com/golang/go/issues/53757
> vendor: update x/sync to v0.16.0

- README.md
- docs/images-readme.md
Follow suit on what Rootless mode docs state, as to not confuse users.
> Remove mention of --oci-worker-no-process-sandbox on daemonless mode

- client/llb/git_test.go
- client/llb/source.go
- frontend/dockerfile/dfgitutil/git_ref.go
- frontend/dockerfile/dfgitutil/git_ref_test.go
- frontend/dockerfile/dockerfile2llb/convert.go
- frontend/dockerfile/dockerfile_addgit_test.go
- frontend/dockerui/context.go
- frontend/dockerui/namedcontext.go
- util/gitutil/git_url.go
- util/gitutil/git_url_test.go
- util/sshutil/scpurl.go
> Support querystring form Git URLs

- frontend/dockerfile/dockerfile_addgit_test.go
relates to https://github.com/moby/moby/pull/50858
> dockerfile: fix client init in testGitQueryString

- frontend/dockerfile/docs/reference.md
> [v0.24] docs: use latest "labs" for --parents and --exclude

- frontend/gateway/gateway.go
The `iter.Seq` returned from `maps.Keys` does not print properly with
`%+v` so it prints the pointer location instead of the contents. Use
`slices.Collect` to collect the iterator into a slice so it can be
printed properly into the error message.
> gateway: no such ref now prints the all refs properly

- Dockerfile
Upgrading the Minio installation from the 2022 version, to the latest 2025 version.
There was a message in the unit test logs about it, and that is now gone 👍 
<pre>
You are running an older version of MinIO released 3 years ago, update: Run `mc admin update`
</pre>
> remotecache: Upgrade minio to latest version

- solver/llbsolver/solver.go
I'm not really sure why this was set originally. We don't support nested builds in provenance that would allow replay (meaning we don't save the subbuild properties), but this shouldn't affect materials collection. If input contained sources they are still captured in the provenance.
Example build showing the issue: https://oci.dag.dev/?blob=docker.io/tonistiigi/dockerfile@sha256:29d88a9d397e45c98e475225bd510622b4eef65bdf9274729ddb166ce75ee91e&mt=application%2Fvnd.in-toto%2Bjson&size=1544
> llbsolver: don't set materials=false on inputs

- solver/llbsolver/provenance/predicate.go
follow-up: https://github.com/docker/buildx/pull/3415
```
BUILDX_SEND_GIT_QUERY_AS_INPUT=true BUILDX_BUILDER=builder docker buildx build -t crazymax/dockerfile:1.18.0-builder2  --platform linux/amd64  --push "https://github.com/moby/buildkit.git?tag=dockerfile/1.18.0&checksum=b772c318368090fb2ffc9c0fed92e0a35bf82389&keep-git-dir=true"
```
https://oci.dag.dev/?blob=docker.io/crazymax/dockerfile@sha256:132c00161686ce417f1909cfbe34b75ed698c5c79958f70b0195928a70a82784&mt=application%2Fvnd.in-toto%2Bjson&size=2280
> provenance: handle input:context frontend opt to set config source

- frontend/dockerfile/dockerfile_provenance_test.go
Custom provenance can only be configured with buildkitd config
> dockerfile: skip customenv tests in dockerd worker

- solver/llbsolver/solver.go
fix #6256
When multiple exports run in parallel, inline cache exporting can run for each of them into the same cache exporter instance. Inline cache exporter can only be invoked multiple times sequentially. There is a 'reset()` call after every invocation that completely switches out the internal cache chains collector.
Before v0.25, this caused some corruption in the inline cache (or some unknown error). Since v0.25, this case is likely to trigger an internal consistency check error and fail the build.
> remotecache: fix inline cache used with multiple exporters

- cache/remotecache/azblob/exporter.go
- cache/remotecache/azblob/importer.go
- cache/remotecache/export.go
- cache/remotecache/gha/gha.go
- cache/remotecache/import.go
- cache/remotecache/inline/inline.go
- cache/remotecache/s3/s3.go
- cache/remotecache/v1/chains.go
- cache/remotecache/v1/parse.go
- cache/remotecache/v1/types/doc.go
- cache/remotecache/v1/types/spec.go
- cache/remotecache/v1/utils.go
- client/client_test.go
- frontend/dockerfile/dockerfile_test.go
Integration test covering case in #6261
> client: add test for deleted blobs in remote cache

- docs/buildkitd.toml.md
relates to https://github.com/moby/buildkit/pull/6210
> docs: provenanceEnvDir in buildkitd.toml

- cache/remotecache/azblob/importer.go
- cache/remotecache/gha/gha.go
- cache/remotecache/v1/chains.go
- docs/buildkitd.toml.md
- hack/images
- solver/exporter.go
- solver/llbsolver/provenance/types/types.go
- solver/llbsolver/provenance/types/types_test.go
- solver/llbsolver/solver.go
backport of:
* https://github.com/moby/buildkit/pull/6258
* https://github.com/moby/buildkit/pull/6261
* https://github.com/moby/buildkit/pull/6263
* https://github.com/moby/buildkit/pull/6269
* https://github.com/moby/buildkit/pull/6275
> [0.25] cherry-picks for v0.25.1

- frontend/dockerfile/dockerfile_provenance_test.go
Zero value after unmarshal changed in https://github.com/moby/buildkit/pull/6275/files .
Would be better to change it back to nil, but this can be done in another release as v0.25.1 is already tagged.
> dockerfile: fix customenv test for dockerd
